### ISSUE TITLE
where is the eval() function from?

### ISSUE THREAD

**Issue by lunasdejavu** [deepinsight/insightface#1005]
Since I am modifying the source code,I tracked it to 
the 10th line in load_data.py:
`imdb = eval(dataset_name)(image_set_name, root_path, dataset_path)`

I can't find which library the eval is from and why it has two pairs of brackets?

**Comment by louielu1027** [comment]
it's in python.
dataset_name='retinaface'
eval(dataset_name) : retinaface
so, eval(dataset_name)(image_set_name, root_path, dataset_path) is same as retinaface(image_set_name, root_path, dataset_path)

go to find: class retinaface()
