### ISSUE TITLE
关于模型蒸馏的问题

### ISSUE THREAD

**Issue by xiexuliunian** [deepinsight/insightface#1023]
想基于insightface大模型进行小模型的蒸馏训练，采用最基本的KD方法，请问我应该取fc1层的输出还是fc7层的输出作为logits呢？

**Comment by goodgoodstudy92** [comment]
我感觉应该是fc7,不然soft target和 hard target没法计算

**Comment by xiexuliunian** [comment]
是的，我目前也是取fc7的输出，谢谢。

**Comment by ctgushiwei** [comment]
@xiexuliunian  mxnet该怎么去弄蒸馏呢？

**Comment by xiexuliunian** [comment]
@ctgushiwei you can look at `https://github.com/TuSimple/neuron-selectivity-transfer` for use,good luck for you !

**Comment by ctgushiwei** [comment]
@xiexuliunian  thank you very much
