### ISSUE TITLE
Train with losstype 4 error

### ISSUE THREAD

**Issue by yewuyue111** [deepinsight/insightface#103]
Have someone know how to do with this error?I am new to mxnet,thaks very much!! 

CUDA_VISIBLE_DEVICES='0,1,2' python -u train_softmax.py --network r34 --loss-type 4 --per-batch-size 64 --margin-m 0.35 --data-dir ../datasets/faces_ms1m_112x112 --prefix ../result/model-r34-amsoftmax
gpu num: 3
num_layers 34
image_size [112, 112]
num_classes 85164
Called with argument: Namespace(batch_size=192, beta=1000.0, beta_freeze=0, beta_min=5.0, c2c_mode=-10, c2c_threshold=0.0, center_alpha=0.5, center_scale=0.003, ckpt=1, coco_scale=8.676161173096705, ctx_num=3, cutoff=0, data_dir='../datasets/faces_ms1m_112x112', easy_margin=0, emb_size=512, end_epoch=100000, gamma=0.12, image_channel=3, image_h=112, image_w=112, images_per_identity=0, incay=0.0, loss_type=4, lr=0.1, lr_steps='', margin=4, margin_a=0.0, margin_b=0.0, margin_m=0.35, margin_s=64.0, margin_verbose=0, max_steps=0, mom=0.9, network='r34', noise_sgd=0.0, num_classes=85164, num_layers=34, output_c2c=0, patch='0_0_96_112_0', per_batch_size=64, power=1.0, prefix='../result/model-r34-amsoftmax', pretrained='', rand_mirror=1, rescale_threshold=0, retrain=False, scale=0.9993, target='lfw,cfp_fp,agedb_30', train_limit=0, triplet_alpha=0.3, triplet_bag_size=3600, triplet_max_ap=0.0, use_deformable=0, use_val=False, verbose=2000, version_input=1, version_output='E', version_se=0, version_unit=3, wd=0.0005)
init resnet 34
0 1 E 3
INFO:root:loading recordio ../datasets/faces_ms1m_112x112/train.rec...
/usr/local/lib/python2.7/dist-packages/mxnet/recordio.py:370: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  header = header._replace(label=np.fromstring(s, np.float32, header.flag))
header0 label [3804847. 3890011.]
id2range 85164
0 0 3804846
c2c_stat [0, 85164]
3804846
rand_mirror 1
(192,)
[11:37:36] src/engine/engine.cc:54: MXNet start using engine: ThreadedEnginePerDevice
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
(12000L, 3L, 112L, 112L)
ver lfw
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
loading bin 13000
loading bin 14000
(14000L, 3L, 112L, 112L)
ver cfp_fp
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
(12000L, 3L, 112L, 112L)
ver agedb_30
lr_steps [266666, 373333, 426666]
[11:37:52] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py:466: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (0.333333333333 vs. 0.00520833333333). Is this intended?
  optimizer_params=optimizer_params)
call reset()
[11:38:00] src/kvstore/././comm.h:327: only 2 out of 6 GPU pairs are enabled direct access. It may affect the performance. You can set MXNET_ENABLE_GPU_P2P=0 to turn it off
[11:38:00] src/kvstore/././comm.h:336: ...
[11:38:00] src/kvstore/././comm.h:336: ..v
[11:38:00] src/kvstore/././comm.h:336: .v.
[11:38:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [11:38:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:58: too large launch parameter: MapReduceKeepDim1[85164,1], [256,1,1]

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff6dc7217cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20aea71) [0x7ff6de5faa71]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20b3007) [0x7ff6de5ff007]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xfa5304) [0x7ff6dd4f1304]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe4aedf) [0x7ff6dd396edf]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe3451d) [0x7ff6dd38051d]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (9) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]

[11:38:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [11:38:01] src/engine/./threaded_engine.h:347: [11:38:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:58: too large launch parameter: MapReduceKeepDim1[85164,1], [256,1,1]

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff6dc7217cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20aea71) [0x7ff6de5faa71]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20b3007) [0x7ff6de5ff007]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xfa5304) [0x7ff6dd4f1304]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe4aedf) [0x7ff6dd396edf]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe3451d) [0x7ff6dd38051d]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (9) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]

An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

Stack trace returned 8 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff6dc7217cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe347c4) [0x7ff6dd3807c4]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (5) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]
[bt] (6) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7ff74c15d184]
[bt] (7) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff74be89ffd]

terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:38:01] src/engine/./threaded_engine.h:347: [11:38:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:58: too large launch parameter: MapReduceKeepDim1[85164,1], [256,1,1]

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff6dc7217cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20aea71) [0x7ff6de5faa71]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20b3007) [0x7ff6de5ff007]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xfa5304) [0x7ff6dd4f1304]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe4aedf) [0x7ff6dd396edf]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe3451d) [0x7ff6dd38051d]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (9) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]

An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

Stack trace returned 8 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff6dc7217cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe347c4) [0x7ff6dd3807c4]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (5) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]
[bt] (6) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7ff74c15d184]
[bt] (7) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff74be89ffd]

Aborted (core dumped)
libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (9) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]

[11:38:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [11:38:01] src/engine/./threaded_engine.h:347: [11:38:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:58: too large launch parameter: MapReduceKeepDim1[85164,1], [256,1,1]

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff6dc7217cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20aea71) [0x7ff6de5faa71]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20b3007) [0x7ff6de5ff007]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xfa5304) [0x7ff6dd4f1304]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe4aedf) [0x7ff6dd396edf]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe3451d) [0x7ff6dd38051d]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (9) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]

An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

Stack trace returned 8 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff6dc7217cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe347c4) [0x7ff6dd3807c4]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (5) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]
[bt] (6) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7ff74c15d184]
[bt] (7) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff74be89ffd]

terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:38:01] src/engine/./threaded_engine.h:347: [11:38:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:58: too large launch parameter: MapReduceKeepDim1[85164,1], [256,1,1]

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff6dc7217cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20aea71) [0x7ff6de5faa71]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20b3007) [0x7ff6de5ff007]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xfa5304) [0x7ff6dd4f1304]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe4aedf) [0x7ff6dd396edf]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe3451d) [0x7ff6dd38051d]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (9) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]

An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

Stack trace returned 8 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff6dc7217cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe347c4) [0x7ff6dd3807c4]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37373) [0x7ff6dd383373]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe37576) [0x7ff6dd383576]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe353eb) [0x7ff6dd3813eb]
[bt] (5) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7ff6f7c01a60]
[bt] (6) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7ff74c15d184]
[bt] (7) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff74be89ffd]

Aborted (core dumped)

**Comment by nttstar** [comment]
What is your mxnet version and how did you install it?

**Comment by yewuyue111** [comment]
I use pip with mxnet_cu80-0.11.0-py2.py3-none-manylinux1_x86_64.whl
Thanks.

**Comment by nttstar** [comment]
Make sure to use mxnet>=0.12
