### ISSUE TITLE
Did you use SE-NET in your r50 model?

### ISSUE THREAD

**Issue by wzn0828** [deepinsight/insightface#1035]
Did you use SE-NET in your r50 model?

**Comment by Walstruzz** [comment]
https://github.com/deepinsight/insightface/blob/fdedc4a396987ab785ca4ef61908c2eb643b7163/recognition/sample_config.py#L11

https://github.com/deepinsight/insightface/blob/fdedc4a396987ab785ca4ef61908c2eb643b7163/recognition/symbol/fresnet.py#L93-L103

**Comment by wzn0828** [comment]
@Walstruzz OK, thank you.
