### ISSUE TITLE
RetinaFaceAntiCov Dropbox

### ISSUE THREAD

**Issue by uday60** [deepinsight/insightface#1060]
Kindly provide alternate links for download.

**Comment by nttstar** [comment]
https://www.dropbox.com/s/6rhhxsbh2qik65k/cov2.zip?dl=0

**Comment by pourfard** [comment]
> https://www.dropbox.com/s/6rhhxsbh2qik65k/cov2.zip?dl=0

This link is dead. Can you provide another link?
