### ISSUE TITLE
Why faces_emore dataset are BGR?

### ISSUE THREAD

**Issue by leeeeeeo** [deepinsight/insightface#1062]
I follow the Third-party Re-implementation [InsightFace_Pytorch](https://github.com/TreB1eN/InsightFace_Pytorch/blob/master/prepare_data.py) to unpack the faces_emore dataset. As shown below, BGR Images can be seen after unpack. I thought they might be RGB. Why is that? Is the training using BGR instead of RGB?
![image](https://user-images.githubusercontent.com/25877709/74717085-b7b00a80-526a-11ea-86b8-95014dd1c64f.png)

**Comment by nttstar** [comment]
It's jpg encoded binary data. All training processes use RGB.
