### ISSUE TITLE
face2rec2.py count number problem

### ISSUE THREAD

**Issue by WIll-Xu35** [deepinsight/insightface#1065]
Hi all,

I know a few people asked this earlier but none of there solution solves my problem.

The .lst file contains 5880026 lines, which means my dataset contains 5880026 images. And the line's format in .lst file is '1 image_path id' since all images are aligned. ID starts from 0 and all images belong to the same person are listed together. And I run the code use python2.7, not python3.

The time count during the execution is around 0.3s per 1000 images before it counts to 5880000 images. After that, the image count still grows until 5967000 and the time count is around 0.05, which is much less than before.

Any idea why the count is more than actual image count?

Many thanks.

**Comment by nttstar** [comment]
Those are subjects ID to image indices mapping label data, not image data.

**Comment by WIll-Xu35** [comment]
@nttstar Got it. Thanks.
