### ISSUE TITLE
不同版本的MXNet训练的R50模型在CPU上耗时相差很大。

### ISSUE THREAD

**Issue by AmigoCDT** [deepinsight/insightface#1071]
你好。
我们用MXNet的C++接口去调用R50模型并得到模型的耗时。发现我们采用MXNet-1.3.1训练的R50模型和你们所开放的R50模型在CPU上的耗时相差10倍。
| 模型             | MXNet版本 | CPU上平均耗时 | model-symbol.json.attrs.mxnet_version |
| ---------------- | --------- | --------- | --------- |
| model-r50-am-lfw | 0.12.1    | 0.5s      | 1201 |
| our-r50          | 1.3.1     | 1.6s      | 10301 |

我们比对两个模型的`model-symbol.json`，发现model-r50-am-lfw的是`"attrs": {"mxnet_version": ["int", 1201]}`， 而our-r50的是`"attrs": {"mxnet_version": ["int", 10301]}`. 除此之外两个模型的`model-symbol.json`完全一致。
请问这是由于训练模型的MXNet版本不同引起的吗？或者这种情况该如何解决？
谢谢。

**Comment by AmigoCDT** [comment]
发现是因为模型中小于e-10的非零参数太多，如果我将小于e-10参数全部置为零，那么速度就正常了下来。

**Comment by Light--** [comment]
所以跟mxnet版本没关系是吗？
