### ISSUE TITLE
And rational behind choosing  the arc loss zy_keep value

### ISSUE THREAD

**Issue by zhenglaizhang** [deepinsight/insightface#108]
Hi,  after reading the code, I didn't understand why the specific value `zy_keep` is chosen, could you help share some inghts here? thanks in advance!
https://github.com/deepinsight/insightface/blob/c9e5188ae289bef0e1a010e8f6846402d66be6c7/src/train_softmax.py#L227

```python
mm = math.sin(math.pi-m)*m
...
zy_keep = zy - s*mm
```

**Comment by nttstar** [comment]
To make the function cos(theta+m) monotonic decreasing while theta in [0°,180°]. But actually it's not necessary as theta will not go much larger than 90°.

**Comment by douhaoexia** [comment]
Hello, I have some doubt.
 From the code , I know when theta > threshold, ' cos(theta+m)' will be changed to zy_keep , namely 'cos(theta)-m*sin(m)'. The min of  cos(theta+m) is  -1 . To make  the function monotonic decreasing while theta in [0°,180°] , we need to make sure ' cos(theta)-m*sin(m) < =  -1' when ' theta > pi - m ' ．
However, I can't prove  'cos(theta)-m*sin(m) < =  -1' . Any problem about my analysis?

**Comment by siahewei** [comment]
![image](https://user-images.githubusercontent.com/5320994/40292896-92f0dc12-5d00-11e8-9f3d-c687f67d9fed.png)

when m = 0.5

**Comment by twotwoiscute** [comment]
> To make the function cos(theta+m) monotonic decreasing while theta in [0°,180°]. But actually it's not necessary as theta will not go much larger than 90°.

hI, I would like to know what's the purpose of "making cos(theta+m) monotonic decreasing " ? Thanks
