### ISSUE TITLE
face preprocess transpose step for model input?

### ISSUE THREAD

**Issue by kafan1986** [deepinsight/insightface#1086]
I am trying to convert the face preprocess for c++ using opencv. Can someone tell me equivalent code for below step using opencv?

`aligned = np.transpose(nimg, (2,0,1))`

I already have the aligned face image in RGB format (i.e. nimg). Also, what is the need for this transpose in the first place? Does it rotate the image?

**Comment by zhongqingyang** [comment]
Hi，Have you solved it now? I think I have the same problem.

**Comment by zhongqingyang** [comment]
`float *ptr_image = image_data;

    float mean_b = 0.485;
    float mean_g = 0.456;
    float mean_r = 0.406;
    float std_b = 0.229;
    float std_g = 0.224;
    float std_r = 0.225;
    auto data1 = im.ptr<uchar>(0);

    //
    for (int i = 0; i < im.rows; ++i)
    {
        auto data = im.ptr<uchar>(i);
        for (int j = 0; j < im.cols; j++)
        {
                *ptr_image++ = (static_cast<float>(*data++) / 255.0 - mean_b) / std_b;
                *ptr_image++ = (static_cast<float>(*data++) / 255.0 - mean_g) / std_g;
                *ptr_image++ = (static_cast<float>(*data++) / 255.0 - mean_r) / std_r;
        }
    }

    //transpose shape from (h,w,c) to (c,h,w)
    for (int k = 0; k < 1; k++)
    {
        for (int c = 0; c < 3; ++c)
        {
            for (int i = 0; i < new_height; ++i)
            {
                for (int j = 0; j < new_width; ++j)
                {
                    array.push_back(static_cast<float>(image_data[(i * new_width + j) * 3 + c]));
                }
            }
        }
    }
`
This is my preprocessing code and it works

**Comment by siddharthshah3030** [comment]
@zhongqingyang 
How did you implement `input_blob = np.expand_dims(aligned, axis=0)`  

mentioned in below line
https://github.com/deepinsight/insightface/blob/1684c14a4975b2fb399f8fbe63c741ac340a6f1d/deploy/face_model.py#L87
