### ISSUE TITLE
Naming conversion of MS1M-clean list

### ISSUE THREAD

**Issue by wangxianliang** [deepinsight/insightface#109]
Thanks for your cleaning list.

In MS1M dataset, each line has the following format:
MID,ImageSearchRank,ImageURL,PageURL,FaceID,FaceRectangle,FaceData
What is the naming conversion of your list?
For example:
m.0933t2\0.jpg
the directory name corresponds to MID, what about the file name? Which item does the file name correspond to?
Thanks a lot.
![qq 20180314162817](https://user-images.githubusercontent.com/10250053/37390971-c2356d30-27a4-11e8-8b7e-f2cc2d5b5896.png)

**Comment by nttstar** [comment]
#28
