### ISSUE TITLE
different features values for using mxnetcu80 and mxnetcu75

### ISSUE THREAD

**Issue by xuduo35** [deepinsight/insightface#111]
I have one machine which is running mxnetcu75 on old ubuntu. I found model.get_feature generate different feature value for the same face with the other machine running mxnetcu80. How can I get same result for mxnetcu75? Thanks.

**Comment by nttstar** [comment]
Did you use the same model?  How much different?

**Comment by xuduo35** [comment]
Same model. I think the accuracy rate drop about 5%. Every number of one feature array for the same face is different.

**Comment by xuduo35** [comment]
After upgrade below modules, I get the same features. Thank you for your project and help!
pip install opencv-contrib-python
pip install -U scikit-image

**Comment by nttstar** [comment]
So the difference is from how you parsing the images.
