### ISSUE TITLE
CUDA_VISIBLE_DEVICES='0,1' python2.7 -u train_softmax.py --network r100 --loss-type 4 --margin-m 0.5 --data-dir ../datasets/faces_ms1m_112x112  --prefix ../model-r100

### ISSUE THREAD

**Issue by molyswu** [deepinsight/insightface#112]
CUDA_VISIBLE_DEVICES='0,1' python2.7 -u train_softmax.py --network r100 --loss-type 4 --margin-m 0.5 --data-dir ../datasets/faces_ms1m_112x112  --prefix ../model-r100
gpu num: 2
num_layers 100
image_size [112, 112]
num_classes 85164
Called with argument: Namespace(batch_size=256, beta=1000.0, beta_freeze=0, beta_min=5.0, ckpt=1, ctx_num=2, cutoff=0, data_dir='../datasets/faces_ms1m_112x112', easy_margin=0, emb_size=512, end_epoch=100000, gamma=0.12, image_channel=3, image_h=112, image_w=112, loss_type=4, lr=0.1, lr_steps='', margin=4, margin_a=1.0, margin_b=0.0, margin_m=0.5, margin_s=64.0, max_steps=0, mom=0.9, network='r100', num_classes=85164, num_layers=100, per_batch_size=128, power=1.0, prefix='../model-r100', pretrained='', rand_mirror=1, rescale_threshold=0, scale=0.9993, target='lfw,cfp_fp,agedb_30', use_deformable=0, verbose=2000, version_act='prelu', version_input=1, version_output='E', version_se=0, version_unit=3, wd=0.0005)
init resnet 100
0 1 E 3 prelu
INFO:root:loading recordio ../datasets/faces_ms1m_112x112/train.rec...
/home/t/Documents/mxnet/python/mxnet/recordio.py:370: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  header = header._replace(label=np.fromstring(s, np.float32, header.flag))
header0 label [3804847. 3890011.]
id2range 85164
3804846
rand_mirror 1
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver lfw
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
loading bin 13000
(14000L, 3L, 112L, 112L)
ver cfp_fp
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver agedb_30
lr_steps [200000, 280000, 320000]
Traceback (most recent call last):
  File "train_softmax.py", line 453, in <module>
    main()
  File "train_softmax.py", line 450, in main
    train_net(args)
  File "train_softmax.py", line 444, in train_net
    epoch_end_callback = epoch_cb )
  File "/home/t/Documents/mxnet/python/mxnet/module/base_module.py", line 460, in fit
    for_training=True, force_rebind=force_rebind)
  File "/home/t/Documents/mxnet/python/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/home/t/Documents/mxnet/python/mxnet/module/executor_group.py", line 264, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/t/Documents/mxnet/python/mxnet/module/executor_group.py", line 360, in bind_exec
    shared_group))
  File "/home/t/Documents/mxnet/python/mxnet/module/executor_group.py", line 638, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/home/t/Documents/mxnet/python/mxnet/symbol/symbol.py", line 1515, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (128, 3, 112, 112)
softmax_label: (128,)
[14:46:26] src/storage/storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage

Stack trace returned 10 entries:

Thank you for your help!

**Comment by nttstar** [comment]
Please install mxnet with GPU support, such as `pip install mxnet-cu80`

**Comment by molyswu** [comment]
python2.7 -m pip install mxnet-cu80
The directory '/home/t/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/t/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: mxnet-cu80 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: requests in /home/t/.local/lib/python2.7/site-packages (from mxnet-cu80)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from mxnet-cu80)
Requirement already satisfied: graphviz in /usr/local/lib/python2.7/dist-packages (from mxnet-cu80)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/t/.local/lib/python2.7/site-packages (from requests->mxnet-cu80)
Requirement already satisfied: idna<2.7,>=2.5 in /home/t/.local/lib/python2.7/site-packages (from requests->mxnet-cu80)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/t/.local/lib/python2.7/site-packages (from requests->mxnet-cu80)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages/certifi-2017.11.5-py2.7.egg (from requests->mxnet-cu80)
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by molyswu** [comment]
python2.7 -m pip install mxnet-cu80
The directory '/home/t/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/t/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: mxnet-cu80 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: requests in /home/t/.local/lib/python2.7/site-packages (from mxnet-cu80)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from mxnet-cu80)
Requirement already satisfied: graphviz in /usr/local/lib/python2.7/dist-packages (from mxnet-cu80)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/t/.local/lib/python2.7/site-packages (from requests->mxnet-cu80)
Requirement already satisfied: idna<2.7,>=2.5 in /home/t/.local/lib/python2.7/site-packages (from requests->mxnet-cu80)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/t/.local/lib/python2.7/site-packages (from requests->mxnet-cu80)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages/certifi-2017.11.5-py2.7.egg (from requests->mxnet-cu80)
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
