### ISSUE TITLE
How to use Lsoftmax in other code?

### ISSUE THREAD

**Issue by taylover-pei** [deepinsight/insightface#114]
I just want to use the LSoftmax Loss in my own code. And I have saw you write the *.h, *.cc and *.cu file. But I do not know how to use it? I have saw the answers in other issues like this:
![image](https://user-images.githubusercontent.com/27360803/37563276-f58bf6d4-2ab7-11e8-9099-1d3a782b6255.png)
But I still do not know how to use it. Can you explain it a little clear? Thank you so much.

**Comment by nttstar** [comment]
You need to compile the `LSoftmax` layer as it is written in c++.  SphereLoss is not recommended to use. Use ArcFace/CosFace to obtain a better accuracy.
