### ISSUE TITLE
Face identification in real-time application

### ISSUE THREAD

**Issue by pourfard** [deepinsight/insightface#1140]
Hi,

I'm am trying to use face biometrics to identify peoples. I have a few questions:

1- How can we use multiple images of a person to better identification?
* One way is using [SVM](https://github.com/ageitgey/face_recognition/blob/5fe85a1a8cbd1b994b505464b555d12cd25eee5f/examples/face_recognition_svm.py) classifier to find the closest embedding to the input embedding.
* Another heuristic way that I'm not sure about it, but it results better accuracy is that I choose one of  the embeddings as (the best) a baseline embedding for a person and use that embedding for identification. I choose an embedding which has the closest average distance to all other embeddings of the same person (If we have two embeddings for one person, we choose one of them randomly). I think this is very crazy. When we choose one embedding as the best, other embeddings are not useful anymore. 

2- What is the best threshold for identification. I mean how should I choose a threshold for similarity to get a 95% accuracy. If I set it 0.6 False-Positive rate is high (false person is accepted) and when it is 0.8 False-Negative rate is high (true person is rejected). I know that it depends on application, but after trying different thresholds in different places, with different peoples, cameras, and hardware resource (different frame rated) I still cannot get a fix number for my application which is using face biometrics for access control with a 95% accuracy.

**Comment by bartolootrit** [comment]
I wouldn't use a face recognition system for biometrics if it works with flat images. Apple "Face ID" and "Windows Hello" use depth cameras.

If there are 512-D feature vectors of several faces, then we may create a cluster for each face. If we get a new feature vector, we may compute a distance to the centers of clusters. If the new feature vector is close enough to some of them, we add the vector to the cluster and update its center, otherwise, we create a new cluster. If it's close enough to more than one center - something is wrong - a network trained with ArcFace should discourage such embeddings.

**Comment by pourfard** [comment]
I think depth image is mostly used to liveness or spoof detection, if not so, what are the applications of 2d face recignition models such as insight face or facenet?

**Comment by siddharthshah3030** [comment]
@pourfard 

Would like to know how you chose threshold further
and what conclusions you made for real-time application

**Comment by pourfard** [comment]
It really depends, but for verification I used 0.85 cinsidering distance of two embeddings as the measure meaning if the distance of two embeddings is less than this value I verify them. For identification I used similarity measure and for most of the applications 80% is good enough meaning if two persoms are 80% similar to each other, they are the same.

**Comment by siddharthshah3030** [comment]
I understand
seems I'll need to gather data and measure ideal threshold value for best performance

Thanks for sharing
