### ISSUE TITLE
Pretrained model on VGGFace2

### ISSUE THREAD

**Issue by ThanosRoidis** [deepinsight/insightface#1156]
In the ArcFace paper you report results on models trained on VGGFace2, but they are not in the model zoo. Would it be possible to upload it somewhere, preferably on DropBox (or anywhere but Baidu actually) and post the link here? Thanks a lot.

**Comment by vuvko** [comment]
You can use model they uploaded as part of the evaluation release: https://github.com/deepinsight/insightface/tree/master/Evaluation/IJB
