### ISSUE TITLE
Retinaface using network='net5'

### ISSUE THREAD

**Issue by srinivasn1** [deepinsight/insightface#1161]
Retinaface by default is using network='net3' but if you change it to use net5 then it gives an error, 

ValueError: operands could not be broadcast together with shapes

according to the comments in the code, net5 represents the retinaface network.

Is there any solutions for it?

**Comment by nttstar** [comment]
You should train a model with the 'net5' setting first.

**Comment by srinivasn1** [comment]
Thanks for the clarification.
