### ISSUE TITLE
Switch from MTCNN to Retinaface in deploy/test.py

### ISSUE THREAD

**Issue by symisc** [deepinsight/insightface#1164]
**deploy/test.py**  uses the MTCNN for face detction and landmark which is quite outdated and fails in a lot of tests.

Is there a way to switch to **Retinaface detection**? How to change the face detection to Retinaface in deploy/test.py?

**Comment by phamthienvuong98** [comment]
I have the same question. Do you sold it ??

**Comment by nttstar** [comment]
Now test.py uses retinaface.
