### ISSUE TITLE
请教一下how to custom loss function in get_symbol()？

### ISSUE THREAD

**Issue by jhgfkdj** [deepinsight/insightface#1169]
我想写一个circle loss来试试看，但是如果按照mxnet的方式来写，我想的是直接MakeLoss(circle_loss)，但是却不知道如何写入这个get_symbol中，可能还是我没有完全理解透这个函数。所以想请教一下，如果我目前只写出了公式的前提下，该如何加入到这个get_symbol中可行？

**Comment by huangman168** [comment]
可以get_symbol中再添加一种loss分支，但是我使用mx sym实现circle loss时因为没有上三角矩阵操作的函数，你是怎么实现的呢

**Comment by jhgfkdj** [comment]
> 可以get_symbol中再添加一种loss分支，但是我使用mx sym实现circle loss时因为没有上三角矩阵操作的函数，你是怎么实现的呢

_weight跟nembedding使用L2Normalization就相当于实现了cos similarity。我也是参考gluon跟tensorflow的版本写的。

**Comment by shuyikong** [comment]
@jhgfkdj 你好，请问可以参考一下你的get_symbol代码吗，我参考网上的写了一下但训练有问题，想看看是怎么实现的，非常感谢～～～我的邮箱是shuyi_hk@163.com
