### ISSUE TITLE
RetinaFace代码错误

### ISSUE THREAD

**Issue by gengyanlei** [deepinsight/insightface#1180]
from rcnn.config import config, default, generate_config
rcnn.config应该改成sample_config!

**Comment by yaoshuyu** [comment]
他文档中的意思是让你在放置sample_config的文件夹中再建一个config.py，其中内容可以复制sample_config或者自己更改。

**Comment by gengyanlei** [comment]
嗯嗯，知道，我复制了一份，改了名字  我以为它是忘记了修改呢   尴尬
