### ISSUE TITLE
Question about paper, section 3.4 MegaFace Challenge1 on FaceScrub

### ISSUE THREAD

**Issue by Jumabek** [deepinsight/insightface#119]
Hi, thanks for the amazing work.
I am going through the paper to understand more.
In the above section you removed 578 identities from MS1M dataset because those identities had a close distance with the identities from FaceScrub.

My question is "Are those removed identities occur in both MS1M and FaceScrub dataset or you remove them only because they have close distance(smaller than 0.45)"

Once more thank you for the work!

**Comment by nttstar** [comment]
Only because they have close distance. We have no time to check them one by one manually, it's a huge work.
