### ISSUE TITLE
Deployment  Error：I  cannot  calculate  accuracy  of  lfw！

### ISSUE THREAD

**Issue by jianbaba** [deepinsight/insightface#120]
当我使用test.py文件的的时候，我发现 mtcnn 只使用了detect_face_limited  函数，而没有用detect_face函数，导致lfw有些图片检测不到人脸，之后我把threshold[2]=0.2改为0（按照sphereface论文测试lfw的方法）将lfw原图输入程序进来测试，准确率只有80%。
请问问题是出在mtcnn的方法选择上么？但是readme写的就是只用mtcnn的R+O部分网络就ok了呀？求解

**Comment by nttstar** [comment]
好像很多人误会了deploy下的MTCNN如何使用, 我会重新写一个版本.
