### ISSUE TITLE
 No module named 'fresnet'

### ISSUE THREAD

**Issue by flydragon2018** [deepinsight/insightface#1208]
python -u train.py --network r100 --loss arcface --dataset emore
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    import fresnet
ModuleNotFoundError: No module named 'fresnet'

***************************************************

should have requirements.txt for dependencies.

**Comment by flydragon2018** [comment]
after fixing above error:


File "/home/zzl/anaconda3/lib/python3.6/site-packages/mxnet/recordio.py", line 79, in open
    check_call(_LIB.MXRecordIOReaderCreate(self.uri, ctypes.byref(self.handle)))
  File "/home/zzl/anaconda3/lib/python3.6/site-packages/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:09:45] src/io/local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "../../datasets/faces_emore/train.rec": No such file or directory

**Comment by nttstar** [comment]
"python -u train.py --network r100 --loss arcface --dataset emore"
It is ok on my side.

**Comment by flydragon2018** [comment]
where and which train.py  are you running?

**Comment by flydragon2018** [comment]
waiting for update.
