### ISSUE TITLE
What kind of type train.rec file?

### ISSUE THREAD

**Issue by Gerkam** [deepinsight/insightface#121]
Hello. I want to try this module on pytorch. And I want use cropped images for train network. What kind of type train.rec? Maybe you know, how can I use it on pytorch?

**Comment by nttstar** [comment]
I don't know much about pytorch. Maybe you can write a new pytorch data loader to read face images from our rec files.

**Comment by Allloginsbusy** [comment]
So .rec is archive, or binary, or smth else?

**Comment by nttstar** [comment]
local k-v storage.

**Comment by Allloginsbusy** [comment]
Thanks. Could You Say What instrument should I use to read this storage?Any k-v db like mongo?

**Comment by ymcasky** [comment]
@Allloginsbusy 
Here is one example: https://github.com/deepinsight/insightface/issues/65
Another example of my own is as following:
```
from mxnet import recordio
import mxnet as mx
import matplotlib.pyplot as plt
path_imgidx = 'D:/code/DeepLearning/Face/InsightFace/insightface/datasets/faces_ms1m_112x112/train.idx'
path_imgrec = 'D:/code/DeepLearning/Face/InsightFace/insightface/datasets/faces_ms1m_112x112/train.rec'

imgrec = recordio.MXIndexedRecordIO(path_imgidx, path_imgrec, 'r')
#%% 1 ~ 3804847
for i in range(3804846):
    header, s = recordio.unpack(imgrec.read_idx(i+1))
    img = mx.image.imdecode(s).asnumpy() 
    plt.imshow(img)
    plt.title('id=' + str(i) + 'label=' + str(header.label))
    plt.pause(0.1)
```

**Comment by benjmcarr** [comment]
You can use ffmpeg
``ffmpeg -i train.rec train/thumb%04d.jpg -hide_banner``

**Comment by RyanCV** [comment]
@ymcasky 
> Here is one example: #65
> Another example of my own is as following:
> 
> ```
> from mxnet import recordio
> import mxnet as mx
> import matplotlib.pyplot as plt
> path_imgidx = 'D:/code/DeepLearning/Face/InsightFace/insightface/datasets/faces_ms1m_112x112/train.idx'
> path_imgrec = 'D:/code/DeepLearning/Face/InsightFace/insightface/datasets/faces_ms1m_112x112/train.rec'
> 
> imgrec = recordio.MXIndexedRecordIO(path_imgidx, path_imgrec, 'r')
> #%% 1 ~ 3804847
> for i in range(3804846):
>     header, s = recordio.unpack(imgrec.read_idx(i+1))
>     img = mx.image.imdecode(s).asnumpy() 
>     plt.imshow(img)
>     plt.title('id=' + str(i) + 'label=' + str(header.label))
>     plt.pause(0.1)
> ```
How to get the list of index in imgrec as mentioned here ?> #%% 1 ~ 3804847 

Thanks.

**Comment by dg-chitharthan** [comment]
Thanks for this code, with which I could able to determine the different classes form the data set.

**Comment by ZubairKhan001** [comment]
> @ymcasky
> 
> > Here is one example: #65
> > Another example of my own is as following:
> > ```
> > from mxnet import recordio
> > import mxnet as mx
> > import matplotlib.pyplot as plt
> > path_imgidx = 'D:/code/DeepLearning/Face/InsightFace/insightface/datasets/faces_ms1m_112x112/train.idx'
> > path_imgrec = 'D:/code/DeepLearning/Face/InsightFace/insightface/datasets/faces_ms1m_112x112/train.rec'
> > 
> > imgrec = recordio.MXIndexedRecordIO(path_imgidx, path_imgrec, 'r')
> > #%% 1 ~ 3804847
> > for i in range(3804846):
> >     header, s = recordio.unpack(imgrec.read_idx(i+1))
> >     img = mx.image.imdecode(s).asnumpy() 
> >     plt.imshow(img)
> >     plt.title('id=' + str(i) + 'label=' + str(header.label))
> >     plt.pause(0.1)
> > ```
> 
> How to get the list of index in imgrec as mentioned here ?> #%% 1 ~ 3804847
> 
> Thanks.

The last idx of train.idx file represents the number of images.
