### ISSUE TITLE
Why do you specify label in feature extraction?

### ISSUE THREAD

**Issue by yamada-sakura** [deepinsight/insightface#1220]
【I'm using mxnet version 1.1.0.】

src/eval/validation.py:def test():L229:db = mx.io.DataBatch(data=(_data,), label=(_label,)):
https://github.com/deepinsight/insightface/blob/836db1b89677b566fe80575e6b694079b3c6f299/src/eval/verification.py#L229

Here, label is also specified in creating data for feature extraction.
I didn't feel it was necessary to specify a label. 
（In model.bind, label_shapes is not specified.）
①Can someone please tell me why I need to specify label in the model run for feature extraction?

Furthermore, the error occurs under these conditions.
[Batch when loading a model! = Batch at inference]

```
Traceback (most recent call last): |   |  
File "verification_on_memory.py", line 169, in <module>
main(parse_arguments(sys.argv[1:]))
File "verification_on_memory.py", line 92, in main
learned_embeddings = mxnet_util.get_reps(learned_data, model, args.batch_size_1)
File "C:\libai\yamada\src\variable_batch\error_fix\symbol\mxnet_util.py", line 246, in get_reps
model.forward(db, is_train=False)
File "C:\Users\mitsu\Anaconda3\envs\yamada_bookai\lib\site-packages\mxnet\module\module.py", line 611, in forward
for i, j in zip(self._label_shapes, data_batch.label)]
TypeError: zip argument #1 must support iteration
```

②Let me know how to solve the error

Any input would be appreciated！

**Comment by nttstar** [comment]
Set label = none in databatch

**Comment by yamada-sakura** [comment]
> データバッチにラベル=なしを設定

Thank you. I'll refer to it.
I'll close it now that it's resolved.
