### ISSUE TITLE
How do you deal with the broken images in facescrub when testing in Megaface?

### ISSUE THREAD

**Issue by myfighterforever** [deepinsight/insightface#123]
@nttstar Such as Pamela Anderson_2367 in facescrub_uncropped_features_list.json

**Comment by nttstar** [comment]
Pamela Anderson_2367 is not broken on my side. Some images in facescrub may corrupted but they're not in feature list.

**Comment by myfighterforever** [comment]
Thanks! But they are in my feature list, I wonder how you deal with your broken images? Did every one have a different feature list? This file "facescrub_uncropped_features_list.json" is in devkit tools of megaface.
I am confused. Hope your reply!
