### ISSUE TITLE
libcudart.so always missing

### ISSUE THREAD

**Issue by Fenzime** [deepinsight/insightface#1239]
I have to begin with apologize with starting this, because i'm not experienced in working with such tools and CUDA, but I really want to try and I can't do it for like 3 month because of the following issue:
**OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory** when i start any of .py programs inside the folder.
I had installed cuda-10.2 at first, then i thought that it wouldn't work with mxnet101, so I installed cuda-10.1 too and add all of their pathes to library_path. When I had cuda10-2 this error looked like OSError: libcudart.so.**10.1**: cannot open shared object file: No such file or directory
but now, when I installed 10.1, I still have the same issue, but with libcudart.so.10.0. 
I have troubles with installing cuda-10.0, but I also think that it shouldn't work like this, so maybe I failed somewhere, but I can't find where.
I use ubuntu through VirtualBox, so maybe this could be the reason too, but I didn't find out any thoughts about this here.
There is an issue #1022 and i don't know if anyone solved this yet. 
Much love

**Comment by nttstar** [comment]
If you have cuda-10.2, install mxnet-cu102 should work.

**Comment by Fenzime** [comment]
> If you have cuda-10.2, install mxnet-cu102 should work.

Thanks for the answer! I installed mxnet-cu102, but accidently I realised that "cuda-10.2" folder is not really installed cuda, but just a part of it, so it doesn't have libcudart.so.10.2, which I am missing now. 
Anyway, I tried to install cuda-10.2, but ran into some troubles with gcc version. 
Should I try to solve this, or is there any easier option to work with this project, for example with cuda-11, or it doesn't support mxnet?
Many thanks again!

**Comment by Fenzime** [comment]
Also i wonder if there's any "simple way" of setting the system to work with this project. I could make new virtual machine or even try to install this on windows (which i tried and failed) if there was any way like "install Ubuntu XX, CUDA XX, mxnet XX", run the following file.
Maybe that's too much, but as I've said im new to this software and just want to begin the easy way

**Comment by Fenzime** [comment]
Well, I moved to using google colab. It has cuda10.1 already installed, so mxnet-cu101 fits and no such errors appear. 
This helped me to go further on discovering this project

**Comment by SthPhoenix** [comment]
Actually Docker solves all this problems, and give you opportunity to test different cuda and MXNet versions without need to mess up host system
