### ISSUE TITLE
mosaic数据增强会提升人脸检测精度！

### ISSUE THREAD

**Issue by gengyanlei** [deepinsight/insightface#1248]
已经实验过，可以提升0.6-0.8个百分点。

**Comment by nttstar** [comment]
Thanks! Can you share your code?

**Comment by gengyanlei** [comment]
抱歉，我是基于pytorch实现的，暂时还不能开源代码。只是告诉一些想用mosaic数据增强的人，可以采用。

**Comment by cavalleria** [comment]
> 抱歉，我是基于pytorch实现的，暂时还不能开源代码。只是告诉一些想用mosaic数据增强的人，可以采用。

我实验下来发现，用了mosaic增强后对小目标提升不错，我用640训练的，在widerface上测试的时候320输入会提升很多，但是在640输入的时候easy和medium会下降

**Comment by gengyanlei** [comment]
@cavalleria 
参考yolov5和yolov4_pytorch的数据增强，但绝对不是直接复制过来应用的，而是需要考虑实际情况把mosaic中的一些操作去掉，这样效果会有提升。

**Comment by cavalleria** [comment]
@gengyanlei 比如说什么操作呀

**Comment by gengyanlei** [comment]
@cavalleria 
你得根据widerface的数据情况，人脸检测任务的一些情况和yolo使用的mosaic进行匹配啊，看看哪些合适？难道你直接把yolov5的mosaic代码直接复制过来，直接用的么？那肯定不行的啊。

**Comment by cavalleria** [comment]
我直接用来训练，wideface easy/medium/hard结果如下,第一行没用masaic，第二行用了，第一列是320输入，第二列是640输入
`81.4/73.3/35.5  87.4/84.7/64.6`

`83.6/76.0/37.1  86.8/84.5/65.6`
你是怎么修改的，可以给点提示吗，你的结果能贴下吗

**Comment by gengyanlei** [comment]
@cavalleria
你这个是mobilenet的吧，我用的pytorch版本的，基于resnet50，我测试精度基于源码默认的1600，所以测试都是基于此。并且我做的是加入属性分支后，精度下降，然后一系列操作后，再无法提升精度，后加入mosaic，提升明显，与未加分支前精度基本一致。

**Comment by gengyanlei** [comment]
具体选择哪些操作，反正都是mosaic的那些操作，只删除，基本不加。

**Comment by cavalleria** [comment]
> 具体选择哪些操作，反正都是mosaic的那些操作，只删除，基本不加。

你的意思是删除四张图片拼接后删除一些放射变化和色彩变化的操作吗？

**Comment by gengyanlei** [comment]
更新一下，mosaic我实现的是在某个batch下提升了，但是其它batch下均下降(尝试了多个batch)；batch提高，精度反而下降，尴尬。
结论：实验多次batch，仅某个batch可以提高，不能说明mosaic一定提升效果。sorry！
