### ISSUE TITLE
TVM inference code for RetinaFace in python

### ISSUE THREAD

**Issue by ashuezy** [deepinsight/insightface#1249]
@nttstar 

After converting the models to TVM. 
How to get the actual coordinates in a particular image via python ? 

Thanks.

**Comment by deimsdeutsch** [comment]
+1 This has been on the list for a very long time.

**Comment by ashuezy** [comment]
@nttstar Any updates ?

**Comment by marisancans** [comment]
Same, I have spent days trying to figure out how to deploy face detection. The documentation is really, really bad

**Comment by ashuezy** [comment]
I don't think anyone is willing to share so might as well leave it.

**Comment by JohannesTK** [comment]
+1

**Comment by Counterfeiter** [comment]
please see my fork... I have modifed the python source package (quick and dirty) to add tvm test

On an raspberry pi 4b I could reduce inference time by factor two.... (retinaface + arcface)
