### ISSUE TITLE
No module named 'embedding' in Evaluation/IJB/

### ISSUE THREAD

**Issue by eesaeedkarimi** [deepinsight/insightface#1251]
When I run Evaluation/IJB/IJB_1N.py or Evaluation/IJB/IJB_11.py this error occurs:
`No module named 'embedding'.`

I think there may be an inconsistency or I have missed some files because at:
https://github.com/deepinsight/insightface/blob/master/Evaluation/IJB/IJB_11.py#L19
a path should be added to the system.
There should be a "recognition" folder.

**Comment by eesaeedkarimi** [comment]
This error occurred because I had not downloaded the files completely.

**Comment by maywander** [comment]
I meet the same problem. I don't know which file I forget to download. If you are free,can you share your experience?

**Comment by liurs1990** [comment]
@eesaeedkarimi  I have the same error. Can you tell me how to get the 'recognition' folder?

**Comment by liurs1990** [comment]
I get it.  the codes are in the tar file.
