### ISSUE TITLE
Have you tested in other popular network backbones except for Resnet?

### ISSUE THREAD

**Issue by wjxdp** [deepinsight/insightface#126]
hello,I tested in Densenet with InsightFace loss,but i got the acc 50% all the time.Besides, I also tested in DPN with InsightFace loss ,i got the the highest acc 74% in the same epoch as Resnet,but resnet acc is 96%.
Can you help me solve this problem or share some training trick? Thank you !

**Comment by nttstar** [comment]
What about the batch-size?

**Comment by wjxdp** [comment]
the per-batch-size is 12,the number of GPU is 2. @nttstar

**Comment by nttstar** [comment]
Make sure total batch size>=128, 512 is recommended.

**Comment by wjxdp** [comment]
if i set the bath-size as 128 or bigger,the error (out of memory) will occur.thank you all the same @nttstar

**Comment by jamessmith90** [comment]
@nttstar 

For 512 batch what is the minimum GPU needed ?
