### ISSUE TITLE
Will release Glint360k dataset?

### ISSUE THREAD

**Issue by John1231983** [deepinsight/insightface#1264]
Hi , do you have plan to release Glint360k? If not, what is Glint360k dataset? Is Glint360k = Celeb +DeepGlint? Why not uses MS1M? Thanks

**Comment by jm-pro** [comment]
see https://github.com/deepinsight/insightface/tree/master/recognition/partial_fc#Glint360k

**Comment by mlourencoeb** [comment]
@anxiangsir is the Glint360K dataset aligned with the standard alignment method based on the retinaface detector? When do you plan to release the google drive link?

Thanks

**Comment by anxiangsir** [comment]
> @anxiangsir is the Glint360K dataset aligned with the standard alignment method based on the retinaface detector? When do you plan to release the google drive link?
> 
> Thanks

Glint360K has a same aligned method with MS1M-retinaface， google drive link has been released

**Comment by facereco** [comment]
The link is down can you upload it again ?

**Comment by facereco** [comment]
Maybe you can upload to https://academictorrents.com/

**Comment by facereco** [comment]
@mlourencoeb

Any chance you successfully downloaded the data and can upload it again to Dropbox / Google Drive / https://academictorrents.com/ ?

Thanks

**Comment by anxiangsir** [comment]
> @mlourencoeb
> 
> Any chance you successfully downloaded the data and can upload it again to Dropbox / Google Drive / https://academictorrents.com/ ?
> 
> Thanks

We are fixing a bug and update the glint360k, after that, we will upload to Google Drive.

**Comment by facereco** [comment]
@anxiangsir  It will be great, thanks!

**Comment by mlourencoeb** [comment]
@anxiangsir can you please let us know what the bug is? is it with the data itself?

Thanks

**Comment by mlourencoeb** [comment]
@facereco Yes, I was able to download it from Dropbox and the checksums seem right

**Comment by anxiangsir** [comment]
> @anxiangsir can you please let us know what the bug is? is it with the data itself?
> 
> Thanks

This rec supports both softmax and triplet training. There is no problem with softmax training, but triplet training has bugs.

**Comment by BattashB** [comment]
is there an option to upload the data to a website that does not require to know fluent Chinese in order to download?

**Comment by jm-pro** [comment]
@BattashB 
see anxiangsir reply above:
"We are fixing a bug and update the glint360k, after that, we will upload to Google Drive."

https://github.com/deepinsight/insightface/issues/1264#issuecomment-712654348

**Comment by anxiangsir** [comment]
Hello, we have released glint360k's downloading magnet link,  you can try it.

**Comment by yichaojin** [comment]
> > @anxiangsir can you please let us know what the bug is? is it with the data itself?
> > Thanks
> 
> This rec supports both softmax and triplet training. There is no problem with softmax training, but triplet training has bugs.

No performance drop or huge difference if using previous dataset with softmax training ?   @anxiangsir

**Comment by anxiangsir** [comment]
> > > @anxiangsir can you please let us know what the bug is? is it with the data itself?
> > > Thanks
> > 
> > This rec supports both softmax and triplet training. There is no problem with softmax training, but triplet training has bugs.
> 
> No performance drop or huge difference if using previous dataset with softmax training ?   @anxiangsir 
> 

yes

**Comment by yossibiton** [comment]
> > > > @anxiangsir can you please let us know what the bug is? is it with the data itself?
> > > > Thanks
> > > 
> > > 
> > > This rec supports both softmax and triplet training. There is no problem with softmax training, but triplet training has bugs.
> > 
> > 
> > No performance drop or huge difference if using previous dataset with softmax training ?   @anxiangsir
> 
> yes

So can you explain what was wrong with dropbox file ? 
I already downloaded it and going to use it - is the data & labels there are all correct ?

**Comment by anxiangsir** [comment]
> > > > > @anxiangsir can you please let us know what the bug is? is it with the data itself?
> > > > > Thanks
> > > > 
> > > > 
> > > > This rec supports both softmax and triplet training. There is no problem with softmax training, but triplet training has bugs.
> > > 
> > > 
> > > No performance drop or huge difference if using previous dataset with softmax training ?   @anxiangsir
> > 
> > 
> > yes
> 
> So can you explain what was wrong with dropbox file ?
> I already downloaded it and going to use it - is the data & labels there are all correct ?

see:
https://github.com/deepinsight/insightface/tree/master/recognition/partial_fc#why-update-glint360k-is-there-a-bug-in-the-previous-version

**Comment by yossibiton** [comment]
I saw that part in the readme but it only explains a bug in the training
part (triplet loss), but not a bug in the data itself

**Comment by anxiangsir** [comment]
Data and labels there are all correct, we only fix a bug for triplet training.

**Comment by yossibiton** [comment]
Ok thank you. I didn't know the rec file itself affects the triplet
training.

**Comment by dodler** [comment]
guys, did anyone uploaded dataset to gdrive?
or maybe can someone please start uploading in torrent? (no peers, can't download)

**Comment by maxcrous** [comment]
Same issue here. Haven't had any peers for the past week. It would be great if the authors could re-seed Glint360K. I have a machine that could seed for the next few months.

**Comment by anxiangsir** [comment]
Does anyone know a better way to share data?

**Comment by maxcrous** [comment]
I can set up an FTP server for a direct file transfer if you're interested.
After that, I have acces to 2 machines which could seed 24/7.
