### ISSUE TITLE
ModuleNotFoundError: No module named 'rcnn.cython'

### ISSUE THREAD

**Issue by mhmddpkts** [deepinsight/insightface#1265]
When I  run test.py in RetinaFace Anti Cov Face Detector, I get "ModuleNotFoundError: No module named 'rcnn.cython'" error.  How can I solve it ?

![Screenshot from 2020-10-13 21-31-35](https://user-images.githubusercontent.com/15729405/95901509-2151cb80-0d9c-11eb-9043-22adc030b235.png)

**Comment by welliechen** [comment]
i have met the same problem.

**Comment by fengyuentau** [comment]
@mhmddpkts you could just replace the whole `rcnn` folder with `insightface/detection/RetinaFace/rcnn`, type `make` under `insightface/detection/RetinaFaceAntiCov` to build some cython libraries, then you should be ready to go.

**Comment by mhmddpkts** [comment]
@fengyuentau Thanks for your helping. It's worked.

**Comment by woctezuma** [comment]
This happens when I try to use `pip`. If I clone the repository, and install with `make`, etc., then it is fine.

**Comment by alexeybozhchenko** [comment]
@woctezuma Well I did clone it but there are no make files. Could you please explain me what have you done exactly?

**Comment by woctezuma** [comment]
I think it is the solution suggested above, with the Makefile in:

https://github.com/deepinsight/insightface/tree/master/detection/RetinaFace

**Comment by mnakhaeecourse** [comment]
> @mhmddpkts you could just replace the whole `rcnn` folder with `insightface/detection/RetinaFace/rcnn`, type `make` under `insightface/detection/RetinaFaceAntiCov` to build some cython libraries, then you should be ready to go.

what do you mean by make? 
How can I make in an IDE for instance Pycharm?

**Comment by woctezuma** [comment]
> what do you mean by make?

https://en.wikipedia.org/wiki/Make_(software)
