### ISSUE TITLE
When unpacking Glint360k rec, about 500k images are got lost.

### ISSUE THREAD

**Issue by overpresentme** [deepinsight/insightface#1269]
Before unpacking rec file, the number of images (described in train.idx) was 17,507,700

But after unpacking rec file with your unpacking code, the number of images becomes 17,091,657

Is 17 million real # of images of Glint360k?

◈ Note that I downloaded Glint360k using baidu.

**Comment by anxiangsir** [comment]
This is a small bug that will not affect the usage.
 The number of images is 17091657.
 We will fix this bug immediately.

**Comment by yichaojin** [comment]
@anxiangsir  the number of ids was about 416K (described in train.idx) not 360K, is 360K real # of ids of Glint360k?

**Comment by anxiangsir** [comment]
> @anxiangsir the number of ids was about 416K (described in train.idx) not 360K, is 360K real # of ids of Glint360k?

Yes，The new rec will be finished soon, please follow us, we will update immediately

**Comment by mlourencoeb** [comment]
Deae @anxiangsir,

I am already using glint360k. These 50K difference are replicated ids?

**Comment by huanleo** [comment]
> > @anxiangsir the number of ids was about 416K (described in train.idx) not 360K, is 360K real # of ids of Glint360k?
> 
> Yes，The new rec will be finished soon, please follow us, we will update immediately

when i unpack the train.rec to get images, some images are corrupted,  wil this be solved in the updating train.rec?

**Comment by anxiangsir** [comment]
> Deae @anxiangsir,
> 
> I am already using glint360k. These 50K difference are replicated ids?

see https://github.com/deepinsight/insightface/issues/1264#issuecomment-712765364

**Comment by anxiangsir** [comment]
Hello, we have released glint360k's downloading magnet link, triplet bug has been fixed, you can try it.

https://github.com/deepinsight/insightface/blob/master/recognition/partial_fc/README.md#download

**Comment by codewithAshray** [comment]
Can someone give me train.rec and train.idx file

**Comment by rrajj** [comment]
Yeah the magnet link isnt really working for me. @anxiangsir can we get some other link to download the new dataset? Thanks
