### ISSUE TITLE
The build of the LSoftmax loss

### ISSUE THREAD

**Issue by PkuRainBow** [deepinsight/insightface#128]
Here I see that we can call the mx.sym.LSoftmax() directly, I am wondering how to build this API as I see that you implement it  with C++/CU(it seems that you refer other's implementation).

```
fc7 = mx.sym.LSoftmax(data=embedding, label=gt_label, num_hidden=args.num_classes,
                              weight = _weight,
                              beta=args.beta, margin=args.margin, scale=args.scale,
                              beta_min=args.beta_min, verbose=1000, name='fc7')
```

**Comment by nttstar** [comment]
Take a look at mxnet official document on how to build your own operator.
