### ISSUE TITLE
training 10 Million Identities with no pretrained model

### ISSUE THREAD

**Issue by Gary-Qinghua** [deepinsight/insightface#1283]
I want to train my own model on 10 Million Identities. At the beginning of training, speed is 10000 samples/sec. In a few minutes, speed is 300 samples/sec. Why?
GPU: V100 * 8

**Comment by anxiangsir** [comment]
I updated some configuration information,  you can set HOROVOD_CACHE_CAPACITY to 1024 in run.sh.
https://github.com/deepinsight/insightface/blob/13da03427255d4efd24d52247ccbec32cee59dc4/recognition/partial_fc/mxnet/run.sh#L5

**Comment by anxiangsir** [comment]
Also can turn on the debug mode to check whether your slow training speed is the cause of IO.
https://github.com/deepinsight/insightface/tree/master/recognition/partial_fc/mxnet#block-io

**Comment by Gary-Qinghua** [comment]
@anxiangsir Thanks. After update the run.sh, speed is 800 smaples/sec. But about pytorch, how to speed up.

**Comment by anxiangsir** [comment]
We have released a pytorch version of the model parallel distributed training method. Full softmax can reproduce the accuracy of the paper, but the sampling accuracy is much lower than that of mxnet. We are looking for the cause of this bug.

**Comment by yossibiton** [comment]
> We have released a pytorch version of the model parallel distributed training method. Full softmax can reproduce the accuracy of the paper, but the sampling accuracy is much lower than that of mxnet. We are looking for the cause of this bug.

Did you get the same accuracy with pytorch for glint360k training ? or only just for emore (because i see the config has only emore)

**Comment by anxiangsir** [comment]
The community has already adopted my pytorch code, using glint360k to reach 97.6 for IJB-C (TPR@FPR=1e-4)!

**Comment by yossibiton** [comment]
That's great, can you send me a reference or recommended training
parameters ?

**Comment by Gary-Qinghua** [comment]
@anxiangsir I have another question. At the begining of model-training, loss rised. After two thousand batch, it's still going up.  Now, loss is 55. Normal?
batch: 64 * 8
backbone_lr: 0
memmort_bank_lr: 0.1
pretrained_model : resnet50  you submitted
id: 1200W
smaple_ratio:0.1

**Comment by anxiangsir** [comment]
@Gary-Qinghua 
![image](https://user-images.githubusercontent.com/31175974/97679462-3fc00280-1ad0-11eb-9222-11ccbc0aea33.png)
First of all, I need to confirm whether you are using mxnet training. We have only tested the mxnet version of the ultra-large-scale classification. Then your phenomenon is normal, and the loss will continue to decline after it rises. We can share our loss curve, the loss function we use is cosface

**Comment by anxiangsir** [comment]
@Gary-Qinghua mybee you can train with CosFace?

**Comment by Gary-Qinghua** [comment]
@anxiangsir I used mxnet for training.

**Comment by anxiangsir** [comment]
@Gary-Qinghua 
There is no problem. Just adjust the learning rate so that the loss does not explode. Perhaps you can first adjust a proper hyperparameter using a subset of the data set.

**Comment by Gary-Qinghua** [comment]
How many GPUs do you use to train with 4K. If I use Resnet50 as backbone,  the largest batchsize is 128 * 8.      
GPU: v100 * 8

**Comment by anxiangsir** [comment]
![image](https://user-images.githubusercontent.com/31175974/97686321-3df83e00-1ad4-11eb-8e9d-237094dddd19.png)
This is an example of our training, we used warmup+ snpslike learning rate decay strategy

**Comment by anxiangsir** [comment]
> How many GPUs do you use to train with 4K. If I use Resnet50 as backbone, the largest batchsize is 128 * 8.
> GPU: v100 * 8

RTX2080Ti * 64

**Comment by Gary-Qinghua** [comment]
I choosed 100W from my dataset. At the begining, the loss rised from 45 to 51. After one thousand batch, it declined.

**Comment by anxiangsir** [comment]
> I choosed 100W from my dataset. At the begining, the loss rised from 45 to 51. After one thousand batch, it declined.

This is a normal phenomenon .

**Comment by Gary-Qinghua** [comment]
Thanks. The backbone_lr i set 0. I want to train the classifier first. Is it helpful?

**Comment by Gary-Qinghua** [comment]
@anxiangsir After one epoch, loss decline from 55 to 28. But about 1.5 epoch, the errors like this:  "One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock". The error lasted six hours and loss informationwas not be printed.

**Comment by anxiangsir** [comment]
This is a very rare bug. We have a very low probability of encountering it during training. It is usually solved by restarting or using a new server. (The cloud service we use is easy to reinstall the system). We will investigate this bug as soon as possible and provide a solution.

**Comment by Gary-Qinghua** [comment]
I meet this error twice. When it first appeared, it only lasted a few minutes.

**Comment by fucker007** [comment]
@anxiangsir 
Hello sir, , I train partial fc with mxnet , but I meet an error， Can I continue train by using checkpiont？
```
mxnet.base.MXNetError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[40194,1],5]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by anxiangsir** [comment]
of course, resume class centers in 'memory_bank.py' and backbone in 'init_params' function.

**Comment by fucker007** [comment]
> of course, resume class centers in 'memory_bank.py' and backbone in 'init_params' function.

Hi, I have worked on `memory_bank.py`  and successed  loading `center params weight` , however I failed  loading checkpoint params in `memory_module.py`,  I check difference on it , but not work. do you  have any suggestion about how to load `model_average-0000.params` and `model_average-symbol.json`  to init backbone 


My code int `init_params` function like this .

```
    def init_params(self, initializer, arg_params=None, aux_params=None,
                    allow_missing=False, force_init=False, allow_extra=False):
        """Initializes the parameters and auxiliary states.

        Parameters
        ----------
        initializer : Initializer
            Called to initialize parameters if needed.
        arg_params : dict
            If not ``None``, should be a dictionary of existing arg_params. Initialization
            will be copied from that.
        aux_params : dict
            If not ``None``, should be a dictionary of existing aux_params. Initialization
            will be copied from that.
        allow_missing : bool
            If ``True``, params could contain missing values, and the initializer will be
            called to fill those missing params.
        force_init : bool
            If ``True``, will force re-initialize even if already initialized.
        allow_extra : boolean, optional
            Whether allow extra parameters that are not needed by symbol.
            If this is True, no error will be thrown when arg_params or aux_params
            contain extra parameters that is not needed by the executor.
        """
        if self.pretrain == 'True':
            print("loading backbone .....")
            #self.backbone_module.load(prefix=os.path.join(self.prefix,"model_average"), epoch=0000, logger=self.logger, context=self.gpu, data_names=['data'],label_names=['softmax_label'])
            #print("==========> load backbone module <=============")
            #print(self.backbone_module)
            #print("===============================================")
            symbol, arg_params, aux_params = mx.model.load_checkpoint(prefix=os.path.join(self.prefix,"model_average"),epoch=0000)
            allow_extra = True
            allow_missing = True
            print("=====================arg_params==========================")
            print(type(arg_params))
            print("===============================================")
            print("=====================aux_params==========================")
            print(type(aux_params))
            print("===============================================")
        # backbone
        self.backbone_module.init_params(
            initializer=initializer, arg_params=arg_params,
            aux_params=aux_params, allow_missing=allow_missing,
            force_init=force_init, allow_extra=allow_extra)

```

**Comment by fucker007** [comment]
@anxiangsir  oh, No, It's not work write like this. I found the symbol is difference  between old one and loaded one.  
when I write like this, I will get this problem , `softmax_label` layer's problem?
```
Traceback (most recent call last):
  File "train_memory.py", line 159, in <module>
    train_net()
  File "train_memory.py", line 151, in train_net
    train_module.fit(
  File "/home/liuyang/work/insightface/recognition/partial_fc/mxnet/memory_module.py", line 106, in fit
    self.forward_backward(data_batch)
  File "/home/liuyang/work/insightface/recognition/partial_fc/mxnet/memory_module.py", line 67, in forward_backward
    self.backward_all(total_feature, total_label)
  File "/home/liuyang/work/insightface/recognition/partial_fc/mxnet/memory_module.py", line 242, in backward_all
    grad, loss = self.backward(total_feature, total_label)
  File "/home/liuyang/work/insightface/recognition/partial_fc/mxnet/memory_module.py", line 304, in backward
    memory_bank.weight.attach_grad()
AttributeError: 'list' object has no attribute 'attach_grad'
```

**Comment by fucker007** [comment]
@anxiangsir can you share this function?

**Comment by fucker007** [comment]
I check the `insightface/recognition/partial_fc/mxnet/memory_module.py", line 306`  
I found that  the right type is ,
`memory bank type <class 'mxnet.ndarray.ndarray.NDArray'>` 
however when I change `init_params` function , It's will change like this.
`memory bank type <class 'list'>`
I will work for it new, continue.

**Comment by fucker007** [comment]
I have sovled this problem,

if anyone wanna load checkpoint file,and continue train, maybe  this information will help you.

- **`step 1`** change config.sh like this:
 '''
export CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7'
export HOROVOD_GPU_ALLREDUCE=NCCL
export HOROVOD_GPU_ALLGATHER=NCCL
export HOROVOD_GPU_BROADCAST=NCLL
export MXNET_CPU_WORKER_NTHREADS=3

# use `which python` to get the absolute path of your python interpreter
#
PYTHON_EXEC=/home/liuyang/anaconda3/bin/python
${PYTHON_EXEC} train_memory.py \
--dataset glint360k_8GPU \
--loss cosface \
--network r100 \
--models-root ./models/glint360k_8GPU_r100FC_1.0_fp16_cosface \
--pretrain True
''' 
- **`step 2`** chang ` train_memory.py` like this:
'''
def parse_args():
    parser = argparse.ArgumentParser(description='Train parall face network')
    # general
    parser.add_argument('--dataset', default='emore', help='dataset config')
    parser.add_argument('--network', default='r100', help='network config')
    parser.add_argument('--loss', default='cosface', help='loss config')
    parser.add_argument('--pretrain', default='False', help='pretrain or not')

    args, rest = parser.parse_known_args()
    default.generate_config(args.loss, args.dataset, args.network)
    parser.add_argument('--models-root', default="./test", help='root directory to save model.')
    args = parser.parse_args()
    return args
def train_net():
     ........
    train_module = SampleDistributeModule(
        pretrain=args.pretrain,
        prefix = prefix_dir,
        symbol=esym,
        fc7_model=fc7_model,
        memory_bank=memory_bank,
        memory_optimizer=memory_bank_optimizer)

'''
- **`step 3` ** chang `memory_bank.py` like this
'''
class MemoryBank(object):
    def __init__(self,pretrain,num_sample, num_local, rank, local_rank, embedding_size, prefix, gpu=True):
        """
        Parameters
        ----------
        num_sample: int
            The number of sampled class center.
        num_local: int
            The number of class center storage in this rank(CPU/GPU).
        rank: int
            Unique process(GPU) ID from 0 to size - 1.
        local_rank: int
            Unique process(GPU) ID within the server from 0 to 7.
        embedding_size: int
            The feature dimension.
        prefix_dir: str
            Path prefix of model dir.
        gpu: bool
            If True, class center and class center mom will storage in GPU.
        """
        self.num_sample = num_sample
        self.num_local = num_local
        self.rank = rank
        self.embedding_size = embedding_size
        self.gpu = gpu
        self.prefix = prefix

        if self.gpu:
            context = mx.gpu(local_rank)
        else:
            context = mx.cpu()

        # In order to apply update, weight and momentum should be storage.
        #print("num_local :",self.num_local)
        self.weight = nd.random_normal(
            loc=0, scale=0.01, shape=(self.num_local, self.embedding_size),
            ctx=context)
        self.weight_mom = nd.zeros_like(self.weight)
        #print("init weight type", self.weight)
        if pretrain == 'True':
            print("load center.... ", pretrain)
            self.load()
            #print("load weight type", self.weight)

        # Sampler object
        self.weight_index_sampler = WeightIndexSampler(num_sample, num_local,  rank)


'''
- **`step 4`**
'''
    def init_params(self, initializer, arg_params=None, aux_params=None,
                    allow_missing=False, force_init=False, allow_extra=False):
        """Initializes the parameters and auxiliary states.

        Parameters
        ----------
        initializer : Initializer
            Called to initialize parameters if needed.
        arg_params : dict
            If not ``None``, should be a dictionary of existing arg_params. Initialization
            will be copied from that.
        aux_params : dict
            If not ``None``, should be a dictionary of existing aux_params. Initialization
            will be copied from that.
        allow_missing : bool
            If ``True``, params could contain missing values, and the initializer will be
            called to fill those missing params.
        force_init : bool
            If ``True``, will force re-initialize even if already initialized.
        allow_extra : boolean, optional
            Whether allow extra parameters that are not needed by symbol.
            If this is True, no error will be thrown when arg_params or aux_params
            contain extra parameters that is not needed by the executor.
        """
        if self.pretrain == 'True':
            _, arg_params, aux_params = mx.module.module.load_checkpoint(prefix=os.path.join(self.prefix,"model_average"),epoch=0)
            allow_missing = True
            allow_extra = True
        # backbone
        self.backbone_module.init_params(
            initializer=initializer, arg_params=arg_params,
            aux_params=aux_params, allow_missing=allow_missing,
            force_init=force_init, allow_extra=allow_extra)


'''

**Comment by 22wei22** [comment]
> @Gary-Qinghua
> ![image](https://user-images.githubusercontent.com/31175974/97679462-3fc00280-1ad0-11eb-9222-11ccbc0aea33.png)
> First of all, I need to confirm whether you are using mxnet training. We have only tested the mxnet version of the ultra-large-scale classification. Then your phenomenon is same as ours, and the loss will continue to decline after it rises. We can share our loss curve, the loss function we use is cosface, and ours batchsize is very large(4k), sample rate is 0.1.

when batch_size is 512, the learning rate is 0.1. When the batch_size is 4000, is the leaning rate set to 4000/512*0.1?
当使用了大的batch_size后，如何设置学习率，直接线性么？

**Comment by markncx** [comment]
> We have released a pytorch version of the model parallel distributed training method. Full softmax can reproduce the accuracy of the paper, but the sampling accuracy is much lower than that of mxnet. We are looking for the cause of this bug.

have you reproduce the sampling accuracy by pytorch?

**Comment by anxiangsir** [comment]
> > We have released a pytorch version of the model parallel distributed training method. Full softmax can reproduce the accuracy of the paper, but the sampling accuracy is much lower than that of mxnet. We are looking for the cause of this bug.
> 
> have you reproduce the sampling accuracy by pytorch?

Yes
