### ISSUE TITLE
Undefined name 'make_list' in ace2rec2.py

### ISSUE THREAD

**Issue by cclauss** [deepinsight/insightface#13]
flake8 testing of https://github.com/deepinsight/insightface on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```./src/data/face2rec2.py:194:9: F821 undefined name 'make_list'
        make_list(args)
        ^
1     F821 undefined name 'make_list'
```
There is a __make_list()__ defined at:
* https://github.com/deepinsight/insightface/blob/master/src/data/face2rec.py#L74

**Comment by nttstar** [comment]
this helper is deprecated, now I removed it. Thank you!

**Comment by cclauss** [comment]
This problem still exists:
* https://github.com/deepinsight/insightface/blob/master/src/data/face2rec2.py#L194
But enabling #14 should help you to see what I am seeing.

**Comment by eladrich** [comment]
@nttstar, if the make_list does not exist what would be the recommended method to create a new .rec file from a directory of images? Seems like face2rec still depends on defining a .lst file.

**Comment by nttstar** [comment]
@eladrich It depends on how to align these images. So a simple program that generate .rec from a directory is not very straightforward.

**Comment by eladrich** [comment]
Thanks for the quick response :-)

So can you describe the scripts one would need to call to create a training binary from a raw dataset (directories of pre-alignment images by identity)? Or is that not part of the repository?
