### ISSUE TITLE
Problem opening glint360k files downloaded by torrent 

### ISSUE THREAD

**Issue by BattashB** [deepinsight/insightface#1304]
Hi, first I want to say thanks for your sharing and effort to make glint360 dataset available.
We've downloaded the torrent and got 7 files, the first :
glint360k/glint360k_00 is gzip type file.
When we try to open it using the command you gave or others we get error, problem with EOF.

The rest are data files, are those files suppose to be used directly with "unpack_glint360k.py"? or open in a different way?

Thanks a lot.

**Comment by xliangp** [comment]
Same problem with glint360k files downloaded from Baidu Drive. We could only unzip glint360k_00 to get lfw.bin, cfp_fp.bin, cfp_ff.bin and train.rec (7.26GB). And then it shows the following error:

```
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive.
tar: Error is not recoverable: exiting now
```

**Comment by anxiangsir** [comment]
1. Please make sure that each file is downloaded and the md5sum is consistent。
```
cf7433cbb915ac422230ba33176f4625  glint360k_00
589a5ea3ab59f283d2b5dd3242bc027a  glint360k_01
8d54fdd5b1e4cd55e1b9a714d76d1075  glint360k_02
cd7f008579dbed9c5af4d1275915d95e  glint360k_03
64666b324911b47334cc824f5f836d4c  glint360k_04
a318e4d32493dd5be6b94dd48f9943ac  glint360k_05
c3ae1dcbecea360d2ec2a43a7b6f1d94  glint360k_06
```
2. Make sure to unzip using the unzip command I provided。
```
cat glint360k_* | tar -xzvf -
# md5sum:
5d9cd9f262ec87a5ca2eac5e703f7cdf train.idx
8483be5af6f9906e19f85dee49132f8e train.rec
```

**Comment by BattashB** [comment]
We had a broken file. redownload fixed it , thanks.

**Comment by tinhchuquang** [comment]
I download dataset in Baidu and run "cat glint360k_* | tar -xvf -" and it error.
"
celeb_deepglint/vgg2_fp.bin
celeb_deepglint/cfp_ff.bin
celeb_deepglint/cfp_fp.bin
celeb_deepglint/calfw.bin
celeb_deepglint/train.rec
tar: celeb_deepglint/train.rec: Wrote only 3584 of 10240 bytes
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
"
Can you fix it? Thanks

**Comment by anxiangsir** [comment]
see this

https://github.com/deepinsight/insightface/issues/1304#issuecomment-720877208

**Comment by tinhchuquang** [comment]
When download folder I rename file -> md5 change. redownload fixed it. Thanks.
You show me how to install horovod in docker? thanks.

**Comment by anxiangsir** [comment]
mxnet does not currently support cuda11, we have plans to update docker recently, you can directly use the official docker of horovod.

**Comment by codewithAshray** [comment]
I am not able to find train.idx file. Can anyone please share me the file.
