### ISSUE TITLE
unlabeled face cluster

### ISSUE THREAD

**Issue by zgsxwsdxg** [deepinsight/insightface#1306]
Everybody，how do face cluster for unlabeled face image？ths.

**Comment by NNDam** [comment]
You can use Glint360k or MS1MV2 pretrained model to get embedding of all images and then use  agglomerative clustering

**Comment by zgsxwsdxg** [comment]
> You can use Glint360k or MS1MV2 pretrained model to get embedding of all images and then use agglomerative clustering

But  theagglomerative clustering firstly need to set the number of group. For the unknown number of clustering group, Is there a better way for cluster？

**Comment by mlourencoeb** [comment]
Take a look at chinese whispers: https://www.pyimagesearch.com/2018/07/09/face-clustering-with-python/

**Comment by zgsxwsdxg** [comment]
> Take a look at chinese whispers: https://www.pyimagesearch.com/2018/07/09/face-clustering-with-python/

thx.
