### ISSUE TITLE
IFRT accuracy on east asian

### ISSUE THREAD

**Issue by maxlacourchristensen** [deepinsight/insightface#1309]
Could you comment on the main reason for the large difference in accuracy on east asian between InsightFace-Private with ArcFace (91.67) vs all other datasets/methods for example: Glint360k with PartialFC (63.91)?

R100 | Glint360k | PartialFC(r=0.1) | 90.45 | 94.60 | 93.96 | 63.91 | 88.23

R180 | InsightFace-Private | ArcFace | 94.45 | 96.98 | 96.02 | 91.67 | 96.26

It is a huge difference. Can it be explained by more/better data on east asians?

**Comment by nttstar** [comment]
Yes.

**Comment by trantrungpixta** [comment]
@nttstar which dataset did you use to benchmark on East Asian? I cannot find the name of the dataset.
