### ISSUE TITLE
issues about MS1M clean list

### ISSUE THREAD

**Issue by Landwind-Xin** [deepinsight/insightface#131]
Hello,
I have some questions about the MS1M clean list (https://pan.baidu.com/s/1eTn6O62):
1. The image number in the list is 3.5M, however, the number stated in ArcFace paper is 3.8M. Why are the numbers different?
2. Could you please explain the naming rules for each item in the list. I'm particularly confused on some long-name items, e.g. line 452-475 as below, 

./m.09q1kt/1U1513P28T3D1331193F328DT200611188655.jpg
./m.09q1kt/1U2519P28T3D2249286F329DT20081113220204.jpg
./m.09q1kt/1U2519P28T3D2249286F329DT200811188766.jpg
./m.09q1kt/1U3088P28T3D3230987F358DT201102188800.jpg
./m.09q1kt/1U765P8T1D210847F62DT20051128144648.jpg
./m.09q1kt/1xin_5520403131049966203664.jpg

Thank you for your help!

**Comment by rockzhan** [comment]
same problem

**Comment by ShuoYang129** [comment]
I also wondering the name rules of the provided clean list. It seem that the name rule is "MID/ImageSearchRank.jpg", however I find large number of None exists images.

**Comment by ShuoYang129** [comment]
@Landwind-Xin I recently download the ms1m_corpwithoutalignment dataset,  and I want to use the clean list you mentioned above, could you tell me how you read the tsv files, like the name rules of save_path?
name  rule I use  is "MID/ImageSearchRank.jpg", but I find a lot of None exists images in the clean list, so I  definitely  use the wrong name rules.

**Comment by KangolHsu** [comment]
@ShuoYang129 where did dou download ms1m_corpwithoutalignment dataset ？
i can only download aligned image in official website 。could you tell me ？thank you

**Comment by KangolHsu** [comment]
@Landwind-Xin  Maybe we can ignore this images with strange name ？

**Comment by Sherry40931** [comment]
@Landwind-Xin Could you upload the list you downloaded previously? The link seems to be broken.

**Comment by ShuoYang129** [comment]
@KangolHsu  I download the dataset from [here](https://www.msceleb.org/download/cropped).

**Comment by Sherry40931** [comment]
@ShuoYang129 Thank you very much for your feedback! It appears that the baidu cloud service is no longer available in Taiwan therefore the web page appears 404 not found on my browser.

**Comment by Rigel-1994** [comment]
@ShuoYang129, I have the same problem with you. How many images left in your case?

**Comment by ShuoYang129** [comment]
@Rigel-1994 The official ms1m dataset says there are 8,456,240 images, and I read the tsv file to "MID/ImageSearchRank-FaceId" and I got exactly 8,456,240 images, however, the name format does not match the clean list. It seems we need clean it by ourselves. So I ignore the clean list, which seems useless because we can not get the matched images by ourselves. By the way, there are multiple FaceIds(means multiple images) which have the same <MID/ImageSearchRank>. .

**Comment by xmuszq** [comment]
Did the author provide the clean list for MS1m?

**Comment by yxchng** [comment]
@shuoyang Have you figured out the problem or is the list fake?

**Comment by shuoyang129** [comment]
@yxchng  the dataset is modified by @nttstar based on ms1m, so you may use the provided bin dataset.

**Comment by yxchng** [comment]
@shuoyang129 @nttstar Will the modification be shared? My pipeline requires the use of image size 112x96 data and it also better fit the ratio of the human face.
