### ISSUE TITLE
what are the .bin files for in the glint360k

### ISSUE THREAD

**Issue by lunasdejavu** [deepinsight/insightface#1312]
`unpack_glint360.py` only needs `train.rec` and `train.idx`

what are `agedb_30.bin  calfw.bin cfp_ff.bin cfp_fp.bin cplfw.bin lfw.bin vgg2_fp.bin `for?
and how to read them?

**Comment by mlourencoeb** [comment]
The *.bin files are the evaluation/tests sets.

**Comment by nikky4D** [comment]
I want to split my glint360 dataset following your split here. Where do I find the ids used in training set?
