### ISSUE TITLE
lfw.bin from downloaded glint360k is not aligned the same as the one from Lightweight Face Recognition Challenge & Workshop (ICCV2019))

### ISSUE THREAD

**Issue by PavitFaaiz** [deepinsight/insightface#1313]
So I downloaded and extracted glint360k and now I found that lfw.bin from glint360k is not the same as what I got from [ICCV 2019 workshop](https://ibug.doc.ic.ac.uk/resources/lightweight-face-recognition-challenge-workshop/) . I then inspect the images in the bin files and found that images from glint360's lfw.bin are aligned pretty badly comparing to the one from ICCV 2019. Here are some of the images:

lfw.bin from glint360k:
![glint2](https://user-images.githubusercontent.com/37909282/98338952-89af6800-203d-11eb-8fe0-390b1058b362.png)
![glint1](https://user-images.githubusercontent.com/37909282/98339033-acda1780-203d-11eb-8b08-1503e0ded48c.png)
![glint1](https://user-images.githubusercontent.com/37909282/98339385-35f14e80-203e-11eb-98b5-faec4323f84b.png)

lfw.bin from ICCV2019 workshop:
![ins2](https://user-images.githubusercontent.com/37909282/98338969-95029380-203d-11eb-8be7-8dd09cd6b78d.png)
![ins1](https://user-images.githubusercontent.com/37909282/98339051-b2cff880-203d-11eb-98fa-dbc45169cbab.png)
![ins1](https://user-images.githubusercontent.com/37909282/98339388-37bb1200-203e-11eb-9c55-e991a6839e57.png)

**Comment by anxiangsir** [comment]
We will investigate this issue seriously, thanks for your feedback.
This is an interesting finding. Even if our align is wrong, we still use glint360k to get state of the art for LOFW, lol.

**Comment by nttstar** [comment]
The bin files of glint360k were copied from ms1m-v2(emore) which was aligned by mtcnn. But the challenge dataset uses retinaface.

**Comment by PavitFaaiz** [comment]
@nttstar I see, thanks! btw, any reason behind this? should I train with mtcnn cropped and aligned lfw as validation dataset?

**Comment by nttstar** [comment]
It's better to use the retinaface aligned version.

**Comment by aidansmyth95** [comment]
Why is it better to use the RetinaFace version? Is it not better to use the version that matches the training data alignment?

I notice MTCNN aligned often is better for some harder faces than RetinaFace for val datasets like LFW, and it shows in the eval accuracy metrics.
