### ISSUE TITLE
Glint360k dropbox/drive link?

### ISSUE THREAD

**Issue by John1231983** [deepinsight/insightface#1314]
We cannot download baidu link, so please help us to provide Dropbox or Drive link? Thanks

**Comment by nttstar** [comment]
The network traffic cost of dropbox or gdrive is too high.

**Comment by anxiangsir** [comment]
Try this torrent?

magnet:?xt=urn:btih:E5F46EE502B9E76DA8CC3A0E4F7C17E4000C7B1E&dn=glint360k

**Comment by John1231983** [comment]
Noone uses torrent

**Comment by xxxpsyduck** [comment]
@John1231983 they tried the best to share. Stop complaint and start downloading then re-upload to dropbox/drive to share with the others

**Comment by alicera** [comment]
Can anyone share the model for Glint360k  and  gdrive for Glint360k?
thanks
