### ISSUE TITLE
_embedding = self.model.get_outputs()[0].asnumpy()

### ISSUE THREAD

**Issue by wyc2015fq** [deepinsight/insightface#133]
我调用抽特征函数，用两张相同的照片同时在一次测试中，发现“_embedding = self.model.get_outputs()[0].asnumpy()“第一次比较耗时，大约用1s,第二次只用了0.01s,请问是这是什么原因？？

**Comment by nttstar** [comment]
确定计算的时间是在这段代码前后吗？

**Comment by wyc2015fq** [comment]
code：time10 = time.time()
            _embedding = self.model.get_outputs()[0].asnumpy()
            time11 = time.time()
            print("the time of _embedding: %.4f" %(time11 - time10))
result：the time of _embedding: 1.0490
             the time of _embedding: 0.0104
            the time of _embedding: 0.0109
在一次代码运行中，我采用前两张是相同照片，第三张是不同照片，测试了多次，结果还是
第一张，时间1s，后面都是0.01s。是不是更mxnet自身有关？还是其他原因？（备注：我的gpu：tesla，m40,12g）

**Comment by simplc** [comment]
遇到了同样的问题，求解！

**Comment by baishiruyue** [comment]
> code：time10 = time.time()
> _embedding = self.model.get_outputs()[0].asnumpy()
> time11 = time.time()
> print("the time of _embedding: %.4f" %(time11 - time10))
> result：the time of _embedding: 1.0490
> the time of _embedding: 0.0104
> the time of _embedding: 0.0109
> 在一次代码运行中，我采用前两张是相同照片，第三张是不同照片，测试了多次，结果还是
> 第一张，时间1s，后面都是0.01s。是不是更mxnet自身有关？还是其他原因？（备注：我的gpu：tesla，m40,12g）

在进行mxnet耗时测试时，一定要注意的是，mxnet的很多操作都是异步进行的。比如self.model.forward()函数，调用过后，立马返回，但实际上前向并没有执行完毕。所以此时在该函数前后添加时间函数进行耗时计算是错误的。正确的做法是调用nd.waitall()函数等待前面所有的操作同步之后，再进行耗时计算。
这里的.asnumpy()函数也是会强制让之前的ndarray操作执行完毕，才会执行。

题主这里的问题应该是首次运行时系统初始化，推理引擎需要时间的问题。

**Comment by ubuntuyumiao** [comment]
遇到同样的问题，总感觉是asnumpy() 转换时间太长？？
