### ISSUE TITLE
Poor result on IJBC at 1e-6 using Glint360K

### ISSUE THREAD

**Issue by John1231983** [deepinsight/insightface#1336]
I trained model on Glint360K dataset. The performance on IJBC at 1e-4 is very good (about 97.3) but very poor at 1e-6 (about 85) in comparsion with MS1M (about 90). Any reason for the result? Thanks

**Comment by anxiangsir** [comment]
IJBC e-4 and e-5 are more discriminative.
Or you can submit your models to test on our IFRT.

**Comment by John1231983** [comment]
Thanks @anxiangsir, so how can we improve the performance at 1e-6? Any related paper ?
