### ISSUE TITLE
Infer with Multiple Batches after Converting to Onnx

### ISSUE THREAD

**Issue by shroudie** [deepinsight/insightface#1344]
Hello all,

I was wondering if anyone has successfully do so, and I am specifically talking about arcface_v100 and MobileFaceNet.

I was able to import params with mxnet, and export with onnx format. I think mxnet currently does not support exporting to onnx with dynamic shapes. So I have to manually modify the onnx graph to take dynamic input. And this is where I got the error: Shuffle]: **at most one dimension may be inferred**. I did some searches and it seems that error was related to BatchNormalization.

I was wondering if anyone has been successfully converting the model to onnx with dynamic shapes or if there is workaround. Any ideas would be helpful. Thanks a lot.

My environment:
onnx: 1.3.0
mxnet: 1.6.0

**Comment by shroudie** [comment]
Closing, resolved with replacing unsupported layers with custom plugins

**Comment by silverlining21** [comment]
Hi  I got the same ERROR `Shuffle]: at most one dimension may be inferred`.

could you show me some details about how did you fix it? any advices would be appreciated!

**Comment by shroudie** [comment]
> Hi I got the same ERROR `Shuffle]: at most one dimension may be inferred`.
> 
> could you show me some details about how did you fix it? any advices would be appreciated!

There is a related issue [here](https://github.com/SthPhoenix/InsightFace-REST/issues/9). I have not tried this yet. 

Otherwise the issue was with the last "Gemm" Layer. The output shape was undetermined. You can load the onnx model with verbose output, you should also be able to locate the problem. 

So you will have to create your own gemm layer, and specific declare the output shape (of course the batch is still unknown at compile time), and modify the onnx graph and replace that gemm layer with your own.
