### ISSUE TITLE
Where is the face align code?

### ISSUE THREAD

**Issue by zeakey** [deepinsight/insightface#1346]
Currently the [alignment/](https://github.com/deepinsight/insightface/tree/d95aeb8029d9478815f2dcf986b3a76f83d93ad7/alignment) part actually presents the landmark detection, rather than the face alignment given the image and landmarks as input.

So is there any codes associated to the face alignment ?

**Comment by xjock** [comment]
@zeakey have resolved this problem？

**Comment by zeakey** [comment]
@xjock not yet.

**Comment by KiLJ4EdeN** [comment]
> @xjock not yet.

Check this out:

https://github.com/deepinsight/insightface/blob/master/python-package/insightface/utils/face_align.py

**Comment by zeakey** [comment]
> > @xjock not yet.
> 
> Check this out:
> 
> https://github.com/deepinsight/insightface/blob/master/python-package/insightface/utils/face_align.py

Thx!

I will close this issue since the problem has been solved.
