### ISSUE TITLE
Question about facescrub dataset clean in your paper.

### ISSUE THREAD

**Issue by juicecwc** [deepinsight/insightface#135]
In your paper, your said:

> We manually clean the FaceScrub dataset and finally find 605 noisy face images. During testing, we change the noisy face to another right face, which can increase the identification accuracy by about 1%. 

So I'd like to know if your  83.27% identity result on megaface is tested using the cleaned facescrub list  or official list. Because in my test on megaface using official list, I got only 79.65% identity accuracy. Thank you! @nttstar

**Comment by nttstar** [comment]
We got 83.27% after removing facescrub noises. But it only leads to about 1% improvement.

**Comment by juicecwc** [comment]
I see. So if I use your code in this repo to preprocess the datasets and train, I should get ~82% on megaface without any other trick, right?

**Comment by nttstar** [comment]
83.27% was got by full refined-ms1m and resnet100.

**Comment by khawar-islam** [comment]
You can download cleaned version from here, if dataset is helpful for you, please consider to cite it
https://github.com/khawar-islam/FPVT_BMVC22
