### ISSUE TITLE
Sub-center ArcFace drop.py failed

### ISSUE THREAD

**Issue by santapo** [deepinsight/insightface#1360]
I have followed the training steps in sub-center arcface and recognized that the model don't have any key = 'fc7_%d_weight'. That lead to the error in below picture. Could anyone fix it?
![image](https://user-images.githubusercontent.com/54897327/102183904-31dc0a80-3ee1-11eb-8a41-9468224aaf49.png)

**Comment by nttstar** [comment]
You should save the fc7 weights during the full size dataset training. (set ckpt_embedding=False )

**Comment by ZubairKhan001** [comment]
Issue with this line
header.flag==0 and raises error, tried to replace it with range of images but the results are strange
a, b = int(header.label[0]), int(header.label[1])
