### ISSUE TITLE
IJBB 和 IJBC测试集

### ISSUE THREAD

**Issue by Abraham423** [deepinsight/insightface#1361]
作者你好，我在自测的IJBC测试集上的指标跟论文中有很大差异(test1,test2,test4)，这可能是数据清洗和裁剪导致的，为了保持数据一致，能否提供下IJBC和IJBB的测试集链接呢，不胜感激~

**Comment by sun-ching** [comment]
请问您的数据集下载成功了吗？文章链接中的IJBB和IJBC数据集我都下载失败，可以分享一份数据集给我吗？不胜感激
