### ISSUE TITLE
When training in float16, how to still store the master copy of the weights in float32 for better accuracy? 

### ISSUE THREAD

**Issue by maryhh** [deepinsight/insightface#1367]
When training the model using partial_fc (mxnet) code in float16,i found the model can't be stored in fp32. it should be storing automatically for FP32.how to solve it?

**Comment by anxiangsir** [comment]
fp16 has no accuracy less.

**Comment by anxiangsir** [comment]
ypu can cast params to float32，and generate a no cast symbol. This method has no accuracy lost.

**Comment by anxiangsir** [comment]
Fp16 means multi precision training.
See optimizer doc:
multi_precision : bool, optional, default False
    Flag to control the internal precision of the optimizer.
    False: results in using the same precision as the weights (default),
    True: makes internal 32-bit copy of the weights and applies gradients
    in 32-bit precision even if actual weights used in the model have lower precision.
    Turning this on can improve convergence and accuracy when training with float16.

**Comment by anxiangsir** [comment]
Fp16 means multi precision training.
See optimizer doc:
```python
    """The base class inherited by all optimizers.

    Parameters
    ----------
    multi_precision : bool, optional, default False
       Flag to control the internal precision of the optimizer.
       False: results in using the same precision as the weights (default),
       True: makes internal 32-bit copy of the weights and applies gradients
       in 32-bit precision even if actual weights used in the model have lower precision.
       Turning this on can improve convergence and accuracy when training with float16.


    """
```
