### ISSUE TITLE
verification using L2norm instead of angular distance

### ISSUE THREAD

**Issue by ymcasky** [deepinsight/insightface#137]
請問我看您算accuracy時使用的是看dist來判斷正確性
但這個dist實際上用的是L2norm而不是角度距離

您在test.py則會使用2個距離判斷，
一個是dist, 一個則是sim
請問這是為什麼呢?

**Comment by ymcasky** [comment]
我實際測試了
用L2norm和angular distance的效果一模一樣@@

**Comment by nttstar** [comment]
2-2*cos = L2_dist

**Comment by ymcasky** [comment]
Thank you.
