### ISSUE TITLE
Question about 512-dim feature extraction in deploy/test.py

### ISSUE THREAD

**Issue by NjuHaoZhang** [deepinsight/insightface#1383]
Hello, jia guo. 
This work is very good and it has helped me a lot, but I encountered a problem: in the 512-D Feature Embedding section, you have said: 

> Put the model under $INSIGHTFACE_ROOT/models/. For example, $INSIGHTFACE_ROOT/models/model-r100-ii. 

However, there are two problems, 
1) In deploy/test.py, I need to enter a (model_prefix, epoch) as the input of --model, which seems to contradict your document  /models/model-r100-ii. 
2) I cannot find a list of these pre-trained models similar to (model_prefix, epoch) elsewhere. 
Is this ?  
https://github.com/deepinsight/insightface/wiki/Model-Zoo  (**3. Face Recognition models. section?**)

Hope to get your help, thank you!

**Comment by NjuHaoZhang** [comment]
sorry, I have solved this problem by myself.

The answer is :
1) you need to download the pre-trained model from https://github.com/deepinsight/insightface/wiki/Model-Zoo. 
For example, i have download **[3.1 LResNet100E-IR,ArcFace@ms1m-refine-v2]** from Dropbox. Then operate this model_dir follow this guideline, https://github.com/deepinsight/insightface#512-d-feature-embedding

2) you need to check the prefix and epoch of the pre-trained model in the pre-trained model dir, 

![image](https://user-images.githubusercontent.com/34995228/104208777-dc593600-546b-11eb-93b9-d74e0c527945.png)

the prefix is **model**, the epoch is 0000. 

3) then, you need to run the command like this:

```
python test.py \
--model ../models/model-r100-ii/model,0000
```

Then it works for me.
![image](https://user-images.githubusercontent.com/34995228/104209333-889b1c80-546c-11eb-822b-c74f66958bae.png)

**Comment by railton** [comment]
you could use the ready python package to make it easier, http://insightface.ai/

**Comment by NjuHaoZhang** [comment]
> you could use the ready python package to make it easier, http://insightface.ai/
Thank you very much for your recommendation, this module looks very cool and convenient, but I need to customize some functions later, so this package is not very helpful to me.

**Comment by NjuHaoZhang** [comment]
> you could use the ready python package to make it easier, http://insightface.ai/

Thank you very much for your recommendation, this module looks very cool and convenient, but I need to customize some functions later, so this package is not very helpful to me.
