### ISSUE TITLE
How to use 16backbone.pth

### ISSUE THREAD

**Issue by wytcsuch** [deepinsight/insightface#1390]
Hello, I'm doing face super-resolution reconstruction recently based on glint360k dataset，and I've noticed that you've published the pre trained model 16backbone.pth.I wonder to know whether this model can be used to evaluate the similarity between reconstructed face and origin face, and what is the output of this model? Looking forward to your reply~

**Comment by anxiangsir** [comment]
Hi，see this

**Comment by wytcsuch** [comment]
> Hi，see this
> 
> https://github.com/deepinsight/insightface/blob/master/recognition/partial_fc/pytorch/IJB/recognition/embedding_test.py#L76

I tried this code, but there was an error
`16backbone.pth is a zip archive (did you mean to use torch.jit.load()?)`
 torch version is 1.2

**Comment by anxiangsir** [comment]
The recommended use is Torch 1.6, which is the version we tested

**Comment by wytcsuch** [comment]
> The recommended use is Torch 1.6, which is the version we tested

Thank you very much for your reply. But I still have a question. When the number of images I input is odd, there will be dimension mismatch.In other words，the input batch size of the model must be even，does this have any meaning？
