### ISSUE TITLE
Is there any document about datasets listed in Dataset Zoo?

### ISSUE THREAD

**Issue by PhanThanhTrung** [deepinsight/insightface#1391]
I am very confused with datasets in Dataset Zoo. 

For example:
 - Is MS1M ArcFace, MS1M IBUG and MS1M RetinaFace created by refining from MS1M dataset?
 - What is the difference between MS1M ArcFace, MS1M IBUG and MS1M RetinaFace?
 
Is there any document about datasets in Dataset Zoo?

**Comment by anxiangsir** [comment]
MS1M-Arcface      means MS1MV2
MS1M-RetinaFace means MS1MV3

document is a good idea, we will update later.
