### ISSUE TITLE
AP in validation Wider Face of Face Detection

### ISSUE THREAD

**Issue by tinhchuquang** [deepinsight/insightface#1405]
I use model face detection R-50, you report is:
         - WiderFace validation mAP: Easy 96.5, Medium 95.6, Hard 90.4
I test in WiderFace in validation and results:
         - Easy   Val AP: 0.9031890567440208
         - Medium Val AP: 0.8786441818813505 
         - Hard   Val AP: 0.6533242254169304
You can show hyperparamater in face detection for me. Thanks.

**Comment by nttstar** [comment]
It's multi-scale testing, if I remember correctly.
