### ISSUE TITLE
No module named 'config' while train arcface

### ISSUE THREAD

**Issue by zhuguangqiang** [deepinsight/insightface#1411]
when I run recognition/ArcFace/train.py, error happened,saying "No module named 'config' ",and I can't find any config.py in the whole project except "recognition/partial_fc/pytorch/config.py",did the author miss config.py or just indeed not providing it? can anyone tell where to find the config.py?thanks a lot !

**Comment by deepage** [comment]
you should do `mv sample_config.py config.py` first.

**Comment by zhuguangqiang** [comment]
> you should do `mv sample_config.py config.py` first.

thank you very much!!

**Comment by zhuguangqiang** [comment]
close
