### ISSUE TITLE
training stop with call reset()

### ISSUE THREAD

**Issue by xuyingzhongguo** [deepinsight/insightface#1416]
Hello!
I have ran into a problem when training the network.
After running few batches, it stops with call_reset and starts the next batch.
![IMG_4087](https://user-images.githubusercontent.com/55081401/109399003-67b95880-7940-11eb-9000-02f302f5cb7d.JPG)

Please help me with it.

**Comment by nttstar** [comment]
It's correct.

**Comment by xuyingzhongguo** [comment]
> It's correct.

Thank you!
