### ISSUE TITLE
the code implementation of arcface loss 

### ISSUE THREAD

**Issue by cbing88** [deepinsight/insightface#142]
<img width="943" alt="wx20180330-110802 2x" src="https://user-images.githubusercontent.com/9246255/38122937-dadd728e-340a-11e8-871c-84e356edb076.png">
I'm confused about line 206 in the screenshot: variable zy is already cos_t, why it still needed divide by a feature scale value?

**Comment by nttstar** [comment]
nembedding was already multiplied by `s`

**Comment by mlinxiang** [comment]
@nttstar why there need to first multiplied by s, as this may no scene?
