### ISSUE TITLE
Question about embedding size

### ISSUE THREAD

**Issue by xsr-ai** [deepinsight/insightface#143]
in facenet，author had done experiment proved that embedding size setting to 128 is the best size，and bigger embedding size will lead to model size bigger，bigger size model mean that latency, RAM ,etc. all will be increase. so, why insightface embedding size is 512, and why don't use 128 or smaller？look forward to you guide, thanks.

**Comment by nttstar** [comment]
In my experiments, 512 is better than 128. And also it will not lead to much bigger model size as the last weight matrix will be removed after training done.

**Comment by xsr-ai** [comment]
@nttstar thanks for your help，but i'm a green hand of mxnet，there i still have some question need your help. the last layers of LResnet50IR network is not a fullyconnect layer？if it is，then bottlenet size must effect to model size，so i think 512 embedding size must be lead to model size bigger than 128. And the last weight matrix which you said is the loss function weight？

**Comment by nttstar** [comment]
It effects, but not effects too much. Accuracy is much more important.
