### ISSUE TITLE
error when I convert .pt model to .onnx 

### ISSUE THREAD

**Issue by daixiangzi** [deepinsight/insightface#1436]
version:pytorch 1.8.0
model: rank_0_softmax_weight_mom.pt

File "convert_onnx.py", line 15, in convert_onnx
    model.load_state_dict(weight)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1196, in load_state_dict
    state_dict = state_dict.copy()
AttributeError: 'Tensor' object has no attribute 'copy'

**Comment by daixiangzi** [comment]
when I convert backbone.pth to onnx  is ok

**Comment by anxiangsir** [comment]
backbone is all you need， you donot need softmax weight for testing

**Comment by daixiangzi** [comment]
> backbone is all you need， you donot need softmax weight for testing

haha, ok thank you,"all you need" I know

**Comment by alicera** [comment]
How to convert onnx?
I try to convert it and the onnx model only has 34.9kb.

Thanks
