### ISSUE TITLE
About  allign matrix mtcnn detect the face to 112x112?

### ISSUE THREAD

**Issue by xubenxiang** [deepinsight/insightface#144]

**Comment by xubenxiang** [comment]
@nttstar Can you tell me about your allign matrix about mtcnn detect the face to 112x112.
I know the mtcnn detect the face to 112x96 is  src = np.array([
      [30.2946, 51.6963],
      [65.5318, 51.5014],
      [48.0252, 71.7366],
      [33.5493, 92.3655],
      [62.7299, 92.2041] ], dtype=np.float32 )
How can I get 112x112 size face from mtcnn detec face?

**Comment by nttstar** [comment]
+8 on x axis

**Comment by xubenxiang** [comment]
@nttstar I'm sorry I disturb you again. I found mtcnn detect the face is very compact. but when I download your facescrub_images_112x112.tar file. I found the face not very compact, the face left and right contant some background.can you tell me what preprocess do you did?

**Comment by HaoLiuHust** [comment]
any progress?

**Comment by NocturnalPig** [comment]
@nttstar 你好，请问一下，你知道关于
[30.2946, 51.6963],
[65.5318, 51.5014],
[48.0252, 71.7366],
[33.5493, 92.3655],
[62.7299, 92.2041] 
坐标值是怎么求出来的吗？
