### ISSUE TITLE
 config.fp16

### ISSUE THREAD

**Issue by li-an-sheng** [deepinsight/insightface#1440]
Hello! Your project insightface/recognition/ArcFace/sample_config.py None of them config.fp16 This parameter。

The error is as follows ：
    if config.fp16:
AttributeError: 'EasyDict' object has no attribute 'fp16'

**Comment by brightbsit** [comment]
i have same error. Do someone know how to fix it?

**Comment by li-an-sheng** [comment]
> 我有同样的错误。有人知道如何解决吗？

Why don't we add the parameter fp16 to false? What do you think

**Comment by nttstar** [comment]
Yes please set fp16 = False as default value

**Comment by brightbsit** [comment]
what do you mean set fp16 to False?  How can I do that?

**Comment by brightbsit** [comment]
Thank you. I fixed this problem :)

**Comment by mzhda** [comment]
I also have a problem like you, could you please suggest me how you make a solution to that
in addition I use google colab as my environment 
![image](https://user-images.githubusercontent.com/19206896/112681289-89462b00-8e7f-11eb-9985-2442e81e3f54.png)

**Comment by nttstar** [comment]
Fixed: 
https://github.com/deepinsight/insightface/blob/master/recognition/ArcFace/sample_config.py#L32
Or you can just set config.fp16 = False in the first line of main() function.
