### ISSUE TITLE
NameError: name 'config' is not defined

### ISSUE THREAD

**Issue by aywkwok** [deepinsight/insightface#1445]
I'm new to Insightface. When I run the first Train "ArcFace with LResNet100E-IR" example, I got:

NameError: name 'config' is not defined

Anyone knows why?

=====================================================================
%CUDA_VISIBLE_DEVICES='0,1,2,3' python3 -u train.py --network r50 --loss cosface --dataset emore

gpu num: 4
prefix ./models/r50-cosface-emore/model
image_size [112, 112]
num_classes 85742
Called with argument: Namespace(batch_size=512, ckpt=3, ctx_num=4, dataset='emore', frequent=20, image_channel=3, kvstore='device', loss='cosface', lr=0.1, lr_steps='100000,160000,220000', models_root='./models', mom=0.9, network='r50', per_batch_size=128, pretrained='', pretrained_epoch=1, rescale_threshold=0, verbose=2000, wd=0.0005) {'fp16': False, 'bn_mom': 0.9, 'workspace': 256, 'emb_size': 512, 'ckpt_embedding': True, 'net_se': 0, 'net_act': 'prelu', 'net_unit': 3, 'net_input': 1, 'net_blocks': [1, 4, 6, 2], 'net_output': 'E', 'net_multiplier': 1.0, 'val_targets': ['lfw', 'cfp_fp', 'agedb_30'], 'ce_loss': True, 'fc7_lr_mult': 1.0, 'fc7_wd_mult': 1.0, 'fc7_no_bias': False, 'max_steps': 0, 'data_rand_mirror': True, 'data_cutoff': False, 'data_color': 0, 'data_images_filter': 0, 'count_flops': True, 'memonger': False, 'is_shuffled_rec': False, 'loss_name': 'margin_softmax', 'loss_s': 64.0, 'loss_m1': 1.0, 'loss_m2': 0.0, 'loss_m3': 0.35, 'net_name': 'fresnet', 'num_layers': 50, 'dataset': 'emore', 'dataset_path': '../datasets/faces_emore', 'num_classes': 85742, 'image_shape': [112, 112, 3], 'loss': 'cosface', 'network': 'r50', 'num_workers': 1, 'batch_size': 512, 'per_batch_size': 128}
0 1 E 3 prelu False
Network FLOPs: 12.6G
loading: ../datasets/faces_emore/train.rec False
Traceback (most recent call last):
  File "train.py", line 484, in <module>
    main()
  File "train.py", line 480, in main
    train_net(args)
  File "train.py", line 341, in train_net
    train_dataiter = get_face_image_iter(config, data_shape, path_imgrec)
  File "/home/akwok/TVM/insightface/recognition/ArcFace/image_iter.py", line 330, in get_face_image_iter
    rand_mirror=config.data_rand_mirror,
NameError: name 'config' is not defined

**Comment by mzhda** [comment]
I have the same error:

![image](https://user-images.githubusercontent.com/19206896/112682732-982ddd00-8e81-11eb-99ca-f9460ca541ab.png)

**Comment by nttstar** [comment]
copy sample_config.py to config.py

**Comment by aywkwok** [comment]
I already copy sample_config.py to config.py. The only other thing I did was to add

config.fp16 = False 

in config.py according to here: 
https://github.com/deepinsight/insightface/blob/master/recognition/ArcFace/sample_config.py#L32

**Comment by mzhda** [comment]
I already do that

![image](https://user-images.githubusercontent.com/19206896/112716282-79b5f900-8ef6-11eb-8a67-ed077714b9a5.png)

still have problem

![image](https://user-images.githubusercontent.com/19206896/112716305-9e11d580-8ef6-11eb-9c1d-40dc8f7d3ad6.png)

thank you for your time.

**Comment by nttstar** [comment]
Fixed, thank you @mzhda

**Comment by GigaGene** [comment]
Dear gents. 
I also have similar problem.

NameError: name 'Config' is not defined

C:\AI\Auto-GPT>python -m autogpt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\AI\Auto-GPT\autogpt\__main__.py", line 12, in <module>
    from autogpt import commands as cmd
  File "C:\AI\Auto-GPT\autogpt\commands.py", line 9, in <module>
    cfg = Config()
          ^^^^^^
NameError: name 'Config' is not defined

Would appreciate your help.

**Comment by Nikhlesh16** [comment]
> copy sample_config.py to config.py

please help it is not resolved
