### ISSUE TITLE
identity label mismatch with img label while unpacking glint360k

### ISSUE THREAD

**Issue by Kuro96** [deepinsight/insightface#1447]
Hi there, i found an interesting issue in `glint360k` dataset.
According to your code in [unpack_glint360k.py](https://raw.githubusercontent.com/deepinsight/insightface/master/recognition/partial_fc/unpack_glint360k.py), indices within `[17091658., 17451890.]` stores `identity`, and `[1., 17091657.]` stores `image`. But it seems that label information stored in `identity` **occationally** doesn't match with labels in `image`.

For example, when i use
```python
s = imgrec.read_idx(17444270)
header, _ = mx.recordio.unpack(s)
print(header.label.astype(int))
```
i get `[16880352 16880388]`, which i think it means images with idx in `range(16880352, 16880388)` belongs to a **single** person, but actually they're NOT!

Here's the code:
```python
# this belongs to a man
s = imgrec.read_idx(16880352)
image_header, image_bytes = mx.recordio.unpack(s)

encoded_array = np.frombuffer(image_bytes, np.uint8)
img = cv2.imdecode(encoded_array, cv2.IMREAD_ANYCOLOR)

print(image_header.label.astype(int))
plt.imshow(img[..., ::-1])

# this belongs to a woman
s = imgrec.read_idx(16880353)
image_header, image_bytes = mx.recordio.unpack(s)

encoded_array = np.frombuffer(image_bytes, np.uint8)
img = cv2.imdecode(encoded_array, cv2.IMREAD_ANYCOLOR)

print(image_header.label.astype(int))
plt.imshow(img[..., ::-1])
```

This happens often to latter indexed identities, which I think is misleading. Since indices within `[0., 17091657.]` already provided adequate information, why appending it with those confusion data?

**Comment by nttstar** [comment]
Yes, it will be inaccurate if we want to represent large integers by float32.
See [https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e](https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e)

**Comment by Kuro96** [comment]
> Yes, it will be inaccurate if we want to represent large integers by float32.
> See https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e

Oops, i see... So why we use float32 rather than int32 or something else?

**Comment by nttstar** [comment]
mxnet.record supports fp32 only.

**Comment by Kuro96** [comment]
ok...
