### ISSUE TITLE
in partial_fc.py pytorch code two weigth files are created. why ?

### ISSUE THREAD

**Issue by bokey007** [deepinsight/insightface#1462]
optimizer.state[self.sub_weight]['momentum_buffer'] = self.sub_weight_mom

what does momentum buffer mean ? why do we need it ?

what does following statement do ?
optimizer.state.pop(optimizer.param_groups[-1]['params'][0], None)

**Comment by bokey007** [comment]
one seems to be for parameters of network and other for storing gradient history.

**Comment by lizhenstat** [comment]
> one seems to be for parameters of network and other for storing gradient history.
I think this means "momentum_buffer" in SGD optimizer:
optimizer.state[self.sub_weight]['momentum_buffer'] = self.sub_weight_mom
as in [here](https://pytorch.org/docs/stable/_modules/torch/optim/sgd.html#SGD)
