### ISSUE TITLE
which dataset have you been used in arcface, related to Bs128-R100-2 Million Identities, 4M Ids and 8MIds.

### ISSUE THREAD

**Issue by ArthurZhao39** [deepinsight/insightface#1471]
Hi, 
could you please tell me which dataset have you been used in arcface_torch(speed benchmark part)
![image](https://user-images.githubusercontent.com/32949741/115505670-66efd380-a2ac-11eb-98d0-4f9ff58f974e.png)

**Comment by anxiangsir** [comment]
Only modify `config.num_classes = 360232` to  `config.num_classes = 8000000` in config.py.

https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/config.py#L44

**Comment by ArthurZhao39** [comment]
thanks
