### ISSUE TITLE
the length of glint360k 

### ISSUE THREAD

**Issue by twmht** [deepinsight/insightface#1474]
Hi,

I found out the training steps of one epoch is 16650 (https://raw.githubusercontent.com/anxiangsir/insightface_arcface_log/master/glint360k_cosface_r18_fp16_0.1/training.log).

this means that the total number of images in one epoch is 

16650 * 8 * 64 = 8524800

but what i got the total length is 17091584

did you resize the dataset when training?

**Comment by twmht** [comment]
or did you train glint360k with batch size 128 and 8 gpu cards?

**Comment by anxiangsir** [comment]
> or did you train glint360k with batch size 128 and 8 gpu cards?

yes，all batchsize is 128 * 8

**Comment by alicera** [comment]
Does everyone know the glint360k process ?
Does the face have the alignmet or only crop?

**Comment by austingg** [comment]
@alicera alignment based on insightface, landmarks are private, which are more accurate

**Comment by alicera** [comment]
landmarks are private
Where can I get the landmarks point
