### ISSUE TITLE
Pre-trained model of sub-center with celeb500k

### ISSUE THREAD

**Issue by haoyayuzzz** [deepinsight/insightface#1481]

**Comment by haoyayuzzz** [comment]
Hi, thanks for sharing your nice code. I don't find pretrained-model of sub-center with celeb500k dataset. So if the pretrained-model can be released? I try to train the model by torch version, but sub-center haven't been implenmented in torch version.

**Comment by nttstar** [comment]
not available

**Comment by haoyayuzzz** [comment]
> not available

ok, it's fine.
