### ISSUE TITLE
about the encoding problem

### ISSUE THREAD

**Issue by lmmcc** [deepinsight/insightface#149]
I use PYTHON 3.6.3 ,when i run your code,i get the error:   File "eval/verification.py", line 186, in load_bin     bins, issame_list = pickle.load(open(path, 'rb')) UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
I have tried many method ,but can't solve it.....should i change the python version to 2.7 or is there any other method,,,,please help

**Comment by lmmcc** [comment]
solve it ! 3Q

**Comment by cici-tan** [comment]
@lmmcc hey, I met the same problem, can I ask how did  u solve this? thanks

**Comment by anshumankmr** [comment]
Hey @cici-tan, did you figure it out?

**Comment by sadeghineda** [comment]
Hi. Did anyone solve this 

> solve it ! 3Q

Hi. How did you solve it?
I have the same problem
