### ISSUE TITLE
easy problem

### ISSUE THREAD

**Issue by Dylan-get** [deepinsight/insightface#1496]
I want to use dataset ms1m-retinaface-t1 to train arcface_torch,but I donot know how to do it ,please help me

**Comment by anxiangsir** [comment]
1. modify config.py
https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/config.py#L27

2. train with this command:
https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch#2-single-node-8-gpus
