### ISSUE TITLE
关于训练时间

### ISSUE THREAD

**Issue by costantine20** [deepinsight/insightface#1497]
![image](https://user-images.githubusercontent.com/62049652/117533315-b52c0300-b01e-11eb-9f4b-64b5232ae1d6.png)
为什么一开始有1000+图片/Sec，而后面越来越小

**Comment by anxiangsir** [comment]
try this:
https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/config.py#L40

**Comment by anxiangsir** [comment]
set num_works > 0

https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/train.py#L48
