### ISSUE TITLE
关于学习率

### ISSUE THREAD

**Issue by liuchang0523** [deepinsight/insightface#1500]
在arcface_pytorch项目中，我把backbone的lr设置位0了，为什么backbone还是会有变化？(在测试集上测试出来的精度不同)

![Snipaste_2021-05-10_10-05-10](https://user-images.githubusercontent.com/20027988/117597004-3ac2c680-b177-11eb-8ede-5600093a283c.png)

**Comment by anxiangsir** [comment]
加QQ聊吧
