### ISSUE TITLE
onnx model performance

### ISSUE THREAD

**Issue by C-Jaewon** [deepinsight/insightface#1502]
Hi, thank you for the good work.

I downloaded the most up-to-date model(https://github.com/deepinsight/insightface/tree/master/challenges/IFRT)
When i tested this on LFW, a performance is low. The validation rate was 4%.

I extracted the embedding with the method below.

ort_session = onnxruntime.InferenceSession(rec_name)
input_name = ort_session.get_inputs()[0].name #'data'
outputs = ort_session.get_outputs()[0].name #'fc1'

img = cv2.imread('image path')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = np.transpose(img, (2, 0, 1))
img = np.expand_dims(img, axis=0)
img = img.astype(np.float32)

emb = ort_session.run([outputs], input_feed={input_name: img})

**Comment by nttstar** [comment]
img = img/127.5 - 1.0
the model was trained by arcface_torch

**Comment by eeric** [comment]
recognition r100 onnx inference example for single image:
https://github.com/eeric/Face_recognition_cnn/tree/main/code/insightface/onnx_inference
