### ISSUE TITLE
face detection scrfd

### ISSUE THREAD

**Issue by ducdung98tb** [deepinsight/insightface#1514]
face detection scrfd output does not have 5 points on the face. How can I get those 5 points?

**Comment by nttstar** [comment]
2.5G_KPS and 10G_KPS models have 5 points output.

**Comment by ducdung98tb** [comment]
I ran the demo/image_demo.py file with the model SCRFD_2.5G_KPS and the results were as follows:

[https://lh3.googleusercontent.com/pw/ACtC-3dKxB0Q7JOXLjYr_p9x9yZqjWwF-okWhy1ORfNP5awfWX-AgoP7J5FA5kNfEJKZt8QRqHcMTmq7CRfdzzQ7Ow3qadeCQrMh6cRey9HG891N_b_s4m89rQUDUUEpgrf4TbsAZB_iSVklU4Kb5jqkDDyN=w1562-h888-no?authuser=0](url)[https://photos.google.com/album/AF1QipP11sjHLUnVs9-szrjdqTATYsMWGnWg1goKwvDC/photo/AF1QipMmawwnMPiiWi54MZSpTqiardxJ68-_VDWTF7tG](url)

**Comment by ducdung98tb** [comment]
![Screenshot from 2021-05-14 11-40-10](https://user-images.githubusercontent.com/35362922/118222870-9a3c1180-b4aa-11eb-9e37-59c398dd41a8.png)
![Screenshot from 2021-05-14 11-48-50](https://user-images.githubusercontent.com/35362922/118222876-9dcf9880-b4aa-11eb-8cc7-820bb1b0c094.png)

**Comment by nttstar** [comment]
Right now please convert the model to onnx and use tools/scrfd.py to do the inference.

**Comment by ducdung98tb** [comment]
Ok, thank bro. I was successful
![t1](https://user-images.githubusercontent.com/35362922/118249075-3415b580-b4cf-11eb-999e-24b723a5b5aa.jpg)

**Comment by fisakhan** [comment]
While using scrfd2onnx.py, What should be the values of build_model_from_cfg, generate_inputs_and_wrap_model, preprocess_example_input in `from mmdet.core import (build_model_from_cfg, generate_inputs_and_wrap_model, preprocess_example_input)`
