### ISSUE TITLE
about data augmentation

### ISSUE THREAD

**Issue by meanmee** [deepinsight/insightface#152]
Hi, It is a great work! And thank u for releasing this amazing project.
I want to use some data augmentation tricks to train my data, like brightness or contract augmentation, I know how to do it in mx.io.ImageRecIter(), But Could you tell me How to do it in FaceImageIter?

**Comment by nttstar** [comment]
just apply augmentation operations on img object in image_iter.

**Comment by bleakie** [comment]
AttributeError: 'FaceImageIter' object has no attribute 'auglist'
where is auglist？
