### ISSUE TITLE
Pretrained models url are removed.

### ISSUE THREAD

**Issue by prajinkhadka** [deepinsight/insightface#1533]
I was using arcface_r100_v1 model in my project and insightface version 0.1.5. 
The model used to be downloaded automatically but that download link is now expired. 

http://insightface.ai/files/models/arcface_r100_v1.zip

This link is expired, and the latest package of insightface also does not download the model.

Where are these models hosted now ?

**Comment by nttstar** [comment]
see this link: https://github.com/deepinsight/insightface/tree/master/python-package

**Comment by woreom** [comment]
Hi, @nttstar 
So Now there is no need to install mxnet anymore?
and are the models trained on the same datasets?

**Comment by prajinkhadka** [comment]
Thank u. 
I managed to solve it.

**Comment by AsimFayyazRaja** [comment]
@prajinkhadka how did you resolve it? Can you kindly tell me?
I have updated to insightface==0.2.1 but I am unable to deploy on docker but in local it is working because the models are present in the local.

**Comment by prajinkhadka** [comment]
> 
> 
> @prajinkhadka how did you resolve it? Can you kindly tell me?
> I have updated to insightface==0.2.1 but I am unable to deploy on docker but in local it is working because the models are present in the local.

For now I did these changes. 
1. Remove Insightface dependecy from requirements file. 
2. Added Insightface in the project directory itself. 
3. In insightface/model_zoo/face_recognition.py, I was using arcfac_r100_v1 model. so I changed download=False, so that it would not try to download model from broken link ( i.e download.py )
4. Uploaded the model zip file onto drive and change the code to download the zip file and extract it in project directory.
5.  And, in the class FaceRecognition in same ( facerecognition.py ) file, change the self.param_file to the model(params file) downloaded.


This was the immediate solution for me. If you have time, you should be using the latest model and change your code accordingly but for the mean time, this would work fine. I am also runnning as docker container.
