### ISSUE TITLE
All dropbox links are down

### ISSUE THREAD

**Issue by gwakor** [deepinsight/insightface#1535]
It is bit struggle to collect dataset.  Can you please correct those links?
Can I get the link of drive link MS1M-Arcface 85k?

**Comment by nttstar** [comment]
We will make them available before next month.

**Comment by gwakor** [comment]
Thanks!!!

**Comment by domingomery** [comment]
Could it be possible to share the link of `model-r100-arcface-ms1m-refine-v2.zip`? Thanks in advance!

**Comment by gwakor** [comment]
May be this will help: https://pan.baidu.com/s/1wuRTf2YIsKt76TxFufsRNA

**Comment by AndreiC1987** [comment]
Can you add the training dataset on an other option besides the one on baidu? 

Thank you.

**Comment by gwakor** [comment]
I am not a contributor. But I have that file I will upload and give you the temporary link.



Sent from my Galaxy



-------- Original message --------
From: AndreiC1987 ***@***.***>
Date: 5/26/21 4:58 AM (GMT+09:00)
To: deepinsight/insightface ***@***.***>
Cc: Abhijeet ***@***.***>, Comment ***@***.***>
Subject: Re: [deepinsight/insightface] All dropbox links are down (#1535)


Can you add the training dataset on an other option besides the one on baidu?

Thank you.

**Comment by domingomery** [comment]
> May be this will help: https://pan.baidu.com/s/1wuRTf2YIsKt76TxFufsRNA

Many thanks @gwakor  but unfortunately it is not the same file... I'm looking for `model-r100-arcface-ms1m-refine-v2.zip`

**Comment by nttstar** [comment]
Some links were updated to using onedrive: https://github.com/deepinsight/insightface/wiki/Dataset-Zoo

**Comment by gwakor** [comment]
Thank for updating the link, I am closing this thread.

**Comment by SugarSpinda** [comment]
Hi @nttstar 

Please update IJB-C meta data 1:1 and 1:N.  https://github.com/deepinsight/insightface/tree/master/evaluation/IJB

IJBC_tid_mid.txt & 5pts score.txt

Thanks in advance.

**Comment by nttstar** [comment]
OK soon

**Comment by luan1412167** [comment]
@nttstar @SugarSpinda do you have IJBB-IJBC link for download?

**Comment by SugarSpinda** [comment]
@luan1412167 Not yet.

**Comment by nttstar** [comment]
We plan to fix the documentations in recent days. Anyone who wants to join can contact us. Thanks!
