### ISSUE TITLE
scrfd train error

### ISSUE THREAD

**Issue by staystay** [deepinsight/insightface#1541]
训练scrfd时，config用scrfd_10g_bnkps.py，报错如下：
`mmdet/models/losses/iou_loss.py", line 365, in forward
    return (pred * weight).sum()  # 0
RuntimeError: The size of tensor a (4) must match the size of tensor b (8) at non-singleton dimension 1`
请问这怎么解决呀？感谢 @nttstar

**Comment by xun-0612** [comment]
https://github.com/open-mmlab/mmdetection/pull/4982 看看這個

**Comment by staystay** [comment]
> [open-mmlab/mmdetection#4982](https://github.com/open-mmlab/mmdetection/pull/4982) 看看這個

谢谢，解决啦
