### ISSUE TITLE
Batch size?

### ISSUE THREAD

**Issue by ygtxr1997** [deepinsight/insightface#1544]
In 'insightface/recognition/arcface_torch/config.py', the 'config.batch_size' is set as '64'.
But in your paper, you set the batch size to 512 and trained models on four GPUs.
Did you mean each single GPU accepts the mini-batch_size of 512?
Or maybe the total four GPUs accept the effective-batch_size of 512, where effective-batch_size = config.batch_size * WORLD_SIZE?

**Comment by ygtxr1997** [comment]
In the model zoo, the 'train.log' shows that the model is trained on 8 GPUs and mini-batch_size is 64 or 128.

**Comment by FengMu1995** [comment]
Have you understand it?

**Comment by FengMu1995** [comment]
Have you understand it?
