### ISSUE TITLE
Has anyone succeeded in training with embedding_size=256?

### ISSUE THREAD

**Issue by gerald-ftk** [deepinsight/insightface#1553]
I'm trying to train with using the arcface_torch/train.py script but with embedding_size=256 in the config.

When doing this, I get: 

```
Traceback (most recent call last):
  File "train.py", line 138, in <module>
    main(args_)
  File "train.py", line 105, in main
    x_grad, loss_v = module_partial_fc.forward_backward(label, features, opt_pfc)
  File "/home/ubuntu/insightface/recognition/arcface_torch/partial_fc.py", line 118, in forward_backward
    dist.all_gather(list(total_features.chunk(self.world_size, dim=0)), features.data)
  File "/home/ubuntu/insightface/.venv/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1863, in all_gather
    work = default_pg.allgather([tensor_list], [tensor])
RuntimeError: All tensor operands to scatter/gather must have the same number of elements
```
But it works when embedding_size=512

Any ideas on how to reduce the embedding size with the Pytorch training model?

**Comment by anxiangsir** [comment]
please create a new "cfg.output"， and try again.

**Comment by gerald-ftk** [comment]
> cfg.output

Hi, thanks for your response

Is cfg.output just an empty directory? Where does it go?

**Comment by 22wei22** [comment]
I have the same error? Do you solve it

**Comment by anxiangsir** [comment]
The latest version of the code has fixed this problem.

**Comment by tianxingyzxq** [comment]
I get similar problem, using configs/3millions_pfc, with latest version.

Traceback (most recent call last):
  File "train.py", line 142, in <module>
    main(parser.parse_args())
  File "train.py", line 112, in main
    x_grad, loss_v = module_partial_fc.forward_backward(label, features, opt_pfc)
  File "/home1/test/DL/insightface/recognition/arcface_torch/partial_fc.py", line 177, in forward_backward
    total_label, norm_weight = self.prepare(label, optimizer)
  File "/home1/test/DL/insightface/recognition/arcface_torch/partial_fc.py", line 151, in prepare
    dist.all_gather(list(total_label.chunk(self.world_size, dim=0)), label)
  File "/home/test/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1185, in all_gather
    work = _default_pg.allgather([tensor_list], [tensor])
RuntimeError: All tensor operands to scatter/gather must have the same size

**Comment by tianxingyzxq** [comment]
@anxiangsir

**Comment by anxiangsir** [comment]
@tianxingyzxq 

Can you give me more information? .
The torch,
And your changes?

**Comment by anxiangsir** [comment]
> I get similar problem, using configs/3millions_pfc, with latest version.
> 
> Traceback (most recent call last):
> File "train.py", line 142, in
> main(parser.parse_args())
> File "train.py", line 112, in main
> x_grad, loss_v = module_partial_fc.forward_backward(label, features, opt_pfc)
> File "/home1/test/DL/insightface/recognition/arcface_torch/partial_fc.py", line 177, in forward_backward
> total_label, norm_weight = self.prepare(label, optimizer)
> File "/home1/test/DL/insightface/recognition/arcface_torch/partial_fc.py", line 151, in prepare
> dist.all_gather(list(total_label.chunk(self.world_size, dim=0)), label)
> File "/home/test/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1185, in all_gather
> work = _default_pg.allgather([tensor_list], [tensor])
> RuntimeError: All tensor operands to scatter/gather must have the same size

has been fixed.

**Comment by hande6688** [comment]
@anxiangsir 
I am using my own data set for arcface for migration learning. I freeze the previous network layer and only train the fully connected layer. I modified the embedding_size=256. Finally, the test found that the size of the weight does not match. How do I modify it?
Modify the code as follows:
for name, child in backbone.named_children():
        if name != 'fc':
            for param in child.parameters():
                param.requires_grad = False

backbone_pth = os.path.join(cfg.output, "backbone.pth")
pretrained_dict=torch.load(backbone_pth, map_location=torch.device(local_rank))
model_dict = backbone.state_dict()
pretrained_dict = {k: v for k, v in pretrained_dict.items() if (k in model_dict and 'fc' not in k)}
model_dict.update(pretrained_dict)
backbone.load_state_dict(model_dict)

Finally found that there is no fully connected layer in the pre-trained pth？
