### ISSUE TITLE
Up side down face align C++

### ISSUE THREAD

**Issue by cannguyen275** [deepinsight/insightface#1559]
Hi,
I sometimes receive up-side-down aligned face by using this code https://github.com/deepinsight/insightface/blob/master/recognition/tools/cpp-align/FacePreprocess.h to align face.

Here is some sample:
![0](https://user-images.githubusercontent.com/35292523/120663102-f1367480-c4b3-11eb-99bb-a1747392af71.jpg)
![1](https://user-images.githubusercontent.com/35292523/120663148-fabfdc80-c4b3-11eb-89c9-da87f4b433d8.jpg)

Align code in python works perfectly. I don't know what wrong with c++ version.
Can you pls help to fix?

Thanks,

**Comment by szad670401** [comment]
Can you show some sample data which can reproduce this problem?

**Comment by cannguyen275** [comment]
@szad670401 [Here](https://drive.google.com/file/d/1Y7I0ulZLr7ycWDNdY8wkux3LgLbN-LwJ/view?usp=sharing) the images is! 

Might this extra information can help you to reproduce the problem:
- Face detection model based is [this repo](https://github.com/biubug6/Face-Detector-1MB-with-landmark/tree/master/Face_Detector_ncnn), used without any modifications.
- The code flow to use that provided align code is just the same [here](https://www.programmersought.com/article/45963896604/)

**Comment by dummynope** [comment]
this worked for me (also with your images):
https://github.com/EasyFaceOrg/EasyFace/blob/0c127c7a3557277ac66908cdf925f3e41d055c78/face_recognizer/src/face_aligner.cpp

**Comment by cannguyen275** [comment]
@dummynope Thanks for sharing. But I found that align code has no difference.
The C++ align version has some different calculations after doing cv:SVD.

I've fixed this by re-implement the SimilarityTransform in python version to C++.

**Comment by nttstar** [comment]
@cannguyen275 Can you share your implementation?

**Comment by GivralNguyen** [comment]
Hi. We created a pull request to fix the face align bug. There were some inconsistencies when calculating matrix T in cv::Mat similarTransform compared to the Python version.

**Comment by cannguyen275** [comment]
> @cannguyen275 Can you share your implementation?

Pls check #1662

**Comment by dummynope** [comment]
Note: I cannot reproduce the problem with the pictures uploaded here, but I tried 1000 other pictures and actually 2 of them were wrong (probably small differences in the networks used and thus deviations in the landmarks). With #1662 it now seems to be correct.

**Comment by nttstar** [comment]
@cannguyen275 @GivralNguyen Thanks for your work!

**Comment by nttstar** [comment]
@dummynope Thanks for your test!
