### ISSUE TITLE
scrfd_500m_bnkps backbone question

### ISSUE THREAD

**Issue by LeeKyungwook** [deepinsight/insightface#1561]
Thanks for sharing great code.

I have a question.  In README.md mobile family chart, SCRFD-0.5GF use Depth-wise Conv.
But in scrfd_500m_bnkps.py code, it used mobilenetv1  not depth-wise conv. 

Although mobilenetv1 contained depth-wise conv, Strictly speaking, aren't you using mobilenetv1 instead of depth-wise conv?

Then it should be changed to Mobilenetv1, not Depth-wise Conv.

Thanks

**Comment by nttstar** [comment]
We changed the blocks setting of mobilenetv1.

**Comment by LeeKyungwook** [comment]
Thx
