### ISSUE TITLE
Mobilefacenet Pretrained Model

### ISSUE THREAD

**Issue by AthanatiusC** [deepinsight/insightface#1567]
Hello, does anybody share mirror repository or links to Mobilefacenet pretrained model inside the Model zoo? I cannot download due to:
1. Baidu is inaccessible
2. Dropbox return 404

thank you!

**Comment by tuuzhang** [comment]
MobileFaceNet,ArcFace@ms1m-refine-v1??
链接：https://pan.baidu.com/s/1-gseP5Sca8za02IEurRnwA 提取码：fw6w

**Comment by AthanatiusC** [comment]
![image](https://user-images.githubusercontent.com/48944565/121492471-1cafe680-ca01-11eb-9997-497deac49811.png)
yes its MobileFaceNet,ArcFace@ms1m-refine-v1
I'm sorry but i am from outside china and i have tried registering under the number of Chinese number, but it was not possible for me to register and download it. May i please request google drive link?

**Comment by tuuzhang** [comment]
https://drive.google.com/file/d/1S48p2KuPcL9HyCwxWuwFpVHEbleZBop2/view?usp=sharing

**Comment by AthanatiusC** [comment]
Yes! that is exactly what i needed, Thank you very much!!!

**Comment by AyushAgrawal25** [comment]
> https://drive.google.com/file/d/1S48p2KuPcL9HyCwxWuwFpVHEbleZBop2/view?usp=sharing

Hi, I just downloaded this model, but not sure how can I load it in Keras. Can anyone help, please?
Thanks a lot for the model.
