### ISSUE TITLE
加载样本速率每隔一段时间都会下降再上升

### ISSUE THREAD

**Issue by hukangli** [deepinsight/insightface#1570]
用arcface_torch里的train.py脚本能正常进行训练，但是加载样本的速率每隔400step都会由500多 samples/sec下降到90多 samples/sec ，请问是什么原因导致的？
![image](https://user-images.githubusercontent.com/50003218/121130216-ad02f580-c860-11eb-9809-96891c8d684b.png)

>

**Comment by Caozhou1995** [comment]
请问你训练的时候，5个epoch后的fps与前5个相比下降很多，并且后面就稳定了？

**Comment by hukangli** [comment]
> 请问你训练的时候，5个epoch后的fps与前5个相比下降很多，并且后面就稳定了？

@Caozhou1995 目前训练到第6个epoch，训练过程中差不多每400step就会有一次加载样本速率下降的现象
![image](https://user-images.githubusercontent.com/50003218/121312164-aeebb800-c937-11eb-8aaf-c02f499cbc0d.png)
每次在加载样本速率变慢时，观察了下GPU的利用率波动情况，大多数时间都停留在0%，等到这50steps过了之后，GPU利用率又恢复到100%

**Comment by lizhenstat** [comment]
I came across a similar problem before, and after I change the HDD to SSD, the problem solved.
