### ISSUE TITLE
SCRFD model throw error when run on image with shape (300, 300)

### ISSUE THREAD

**Issue by huytuong010101** [deepinsight/insightface#1578]
Thank u for you repository very useful
I 'am trying to run face detection with SCRFD , it work very well on (640, 640) image
But i get this error when run with another image shape (300, 300)
```
File "D:\FTechAI\fid-face\SCRFD.py", line 101, in distance2bbox
    x1 = points[:, 0] - distance[:, 0]
ValueError: operands could not be broadcast together with shapes (2738,) (2888,)
```
I run it via scrfd.py after convert model to onnx 
Do i need do something to run this model on another image shape?

**Comment by nttstar** [comment]
make sure H&W can be divided by 32

**Comment by huytuong010101** [comment]
> make sure H&W can be divided by 32

yessssssssss it work for me,
thank u so much
