### ISSUE TITLE
onnx support for Arcface and RetinaFace 

### ISSUE THREAD

**Issue by woreom** [deepinsight/insightface#1585]
Hi, I have read some of your codes and noticed that `deploy/test.py` with the model named 'antelope' is a merge of all your models together, I was wondering if is there separate .onnx files for your models or if they are still going to be still running on Mxnet?
since from what I gathered for using models separately for instance `Retinaface`,  the code still imports Mxnet.

**Comment by nttstar** [comment]
Models in antelope pack are all in onnx format.

**Comment by nttstar** [comment]
and uses onnxruntime as inference backend

**Comment by woreom** [comment]
So, you mean that the models are still being trained in mxnet but then converted to onnx for easier usage?
Can you make a script on how to use only one model in 'antelope' for example arcface or retinaface.

**Comment by nttstar** [comment]
We will reorganize our inference library soon and at that time you can see more documentations.

**Comment by nttstar** [comment]
actually you can call insightface.model_zoo.get_model('xxx/scrfd_10g_bnkps.onnx') which will return a SCRFD instance.
