### ISSUE TITLE
Cudnn error when facedetect

### ISSUE THREAD

**Issue by DaddyWesker** [deepinsight/insightface#1588]
Hello.

I've got some strange problem right there. Here is the simple code (without imports though)

```
cap = cv2.VideoCapture(0)

detector = insightface.app.FaceAnalysis(name="antelope")

detector.prepare(ctx_id=0)

while cap.isOpened():
    ret, img = cap.read()
    if not ret:
        break
    faces = detector.get(img)
```

And on the detector.get line i'm receiving following error:
`raceback (most recent call last):
  File "/home/daddywesker/anaconda3/envs/tf/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'Conv_0_Relu_2' Status Message: CUDNN error executing cudnnFindConvolutionForwardAlgorithmEx( s_.handle, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.y_tensor, s_.y_data, 1, &algo_count, &perf, algo_search_workspace.get(), max_ws_size)
python-BaseException`

I've tried to remove conda environment and reinstall insightface once again. Both ways - via conda install and pip install. Nothing changes. Cuda 11.3, RTX 3070 Laptop, Linux Mint 20. Will be glad to hear any advices. I've tried to install onnx both ways too - via pip and conda.
Cudnn installe using tar installation from official nvidia guide.

**Comment by DaddyWesker** [comment]
WEll, it seems that problem somehow related to insightface/onnx/keras interaction. Code which i've pasted above is the part of the script which is using both keras and insightface antelope model.
So, let the code be like that now 

```
from tensorflow.keras.models import load_model
import insightface

cap = cv2.VideoCapture(0)
detector = insightface.app.FaceAnalysis(name="antelope")
model_b = load_model('models/blinkdetection.h5')
detector.prepare(ctx_id=0)
while cap.isOpened():
    ret, img = cap.read()
    if not ret:
        break

    faces = detector.get(img)
```

If I'll delete line model_b = load_model('models/blinkdetection.h5') everything will work (though, it will be kinda slow, 35 ms face detection on 640x480 image. Or is that fine?). But with this line, everything will crash as i've described previously. I don't know if it is related to insightface, keras/tensorflow, onnx or something else (maybe nvidia?). If it is not related with onnx, can you point me out where should i ask about that issue?

**Comment by nttstar** [comment]
@DaddyWesker I don't know. And ff you need a faster detector, just replace the scrfd model under antelope with a smaller one.

**Comment by DaddyWesker** [comment]
Not like i want to use facter detector, more like i'm thinking if eveything works as intended. DO you have any time measures?

ANd anything about my main question about cudnn error?

**Comment by nttstar** [comment]
what i can suggest is to convert `blinkdetection.h5` to onnx

**Comment by DaddyWesker** [comment]
alright, i'll try. Thanks.

**Comment by nttstar** [comment]
pip install -U insightface
and
detector = insightface.app.FaceAnalysis(name="antelope", allowed_modules=['detection'])

it will be faster if you only need the detector.

**Comment by DaddyWesker** [comment]
> pip install -U insightface
> and
> detector = insightface.app.FaceAnalysis(name="antelope", allowed_modules=['detection'])
> 
> it will be faster if you only need the detector.

Thanks. Could you tell me how long does it take to detect image 640x480 on your machine? Without "allowed_modules".

**Comment by DaddyWesker** [comment]
Well, i've tried to convert h5 model to onnx, though it wasn't easy due to some errors, but now i'm getting 
`google.protobuf.message.DecodeError: Protobuf decoding consumed too few bytes: 11 out of 10618152`
when i'm trying to load it. ANd there are not much solutions there about that problem - update onnx. It is already 1.9.0. Meh...

**Comment by DaddyWesker** [comment]
You know, for some reason converting h5 model to onnx worked... THanks!

**Comment by DaddyWesker** [comment]
By the way, when detector.get(img) returns face with None in landmarks field. Is it possible to get those landmark without using this one? https://github.com/deepinsight/insightface/tree/master/alignment/coordinateReg Problem is, that i don't want to use mxnet. I though if it is possible to use only antelope model?
