### ISSUE TITLE
Check failed: allow_null:  LocalFileSystem::Open "../datasets/faces_emore\train.rec": No such file or directory

### ISSUE THREAD

**Issue by nhatduy19599** [deepinsight/insightface#1596]
I have a problem when I run the executable with the command:
python -u train.py --network r100 --loss arcface --dataset emore
-----------------------------------------------------------------------
gpu num: 4
prefix ./models\r100-arcface-emore\model
image_size [112, 112]
num_classes 85742
Called with argument: Namespace(batch_size=512, ckpt=3, ctx_num=4, dataset='emore', frequent=20, image_channel=3, kvstore='device', loss='arcface', lr=0.1, lr_steps='100000,160000,220000', models_root='./models', mom=0.9, network='r100', per_batch_size=128, pretrained='', pretrained_epoch=1, rescale_threshold=0, verbose=2000, wd=0.0005) {'bn_mom': 0.9, 'workspace': 256, 'emb_size': 512, 'ckpt_embedding': True, 'net_se': 0, 'net_act': 'prelu', 'net_unit': 3, 'net_input': 1, 'net_blocks': [1, 4, 6, 2], 'net_output': 'E', 'net_multiplier': 1.0, 'val_targets': ['lfw', 'cfp_fp', 'agedb_30'], 'ce_loss': True, 'fc7_lr_mult': 1.0, 'fc7_wd_mult': 1.0, 'fc7_no_bias': False, 'max_steps': 0, 'data_rand_mirror': True, 'data_cutoff': False, 'data_color': 0, 'data_images_filter': 0, 'count_flops': True, 'memonger': False, 'is_shuffled_rec': False, 'fp16': False, 'loss_name': 'margin_softmax', 'loss_s': 64.0, 'loss_m1': 1.0, 'loss_m2': 0.5, 'loss_m3': 0.0, 'net_name': 'fresnet', 'num_layers': 100, 'dataset': 'emore', 'dataset_path': '../datasets/faces_emore', 'num_classes': 85742, 'image_shape': [112, 112, 3], 'loss': 'arcface', 'network': 'r100', 'num_workers': 1, 'batch_size': 512, 'per_batch_size': 128}
0 1 E 3 prelu False
Network FLOPs: 24.2G
loading: ../datasets/faces_emore\train.rec False
INFO:root:loading recordio ../datasets/faces_emore\train.rec...
Traceback (most recent call last):
  File "train.py", line 485, in <module>
    main()
  File "train.py", line 481, in main
    train_net(args)
  File "train.py", line 342, in train_net
    train_dataiter = get_face_image_iter(config, data_shape, path_imgrec)
  File "E:\DataTraining\insightface\insightface\recognition\ArcFace\image_iter.py", line 334, in get_face_image_iter
    images_filter=cfg.data_images_filter,
  File "E:\DataTraining\insightface\insightface\recognition\ArcFace\image_iter.py", line 45, in __init__
    'r')  # pylint: disable=redefined-variable-type
  File "C:\Users\nhatd\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\recordio.py", line 245, in __init__
    super(MXIndexedRecordIO, self).__init__(uri, flag)
  File "C:\Users\nhatd\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\recordio.py", line 71, in __init__
    self.open()
  File "C:\Users\nhatd\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\recordio.py", line 248, in open
    super(MXIndexedRecordIO, self).open()
  File "C:\Users\nhatd\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\recordio.py", line 79, in open
    check_call(_LIB.MXRecordIOReaderCreate(self.uri, ctypes.byref(self.handle)))
  File "C:\Users\nhatd\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:22:13] C:\Jenkins\workspace\mxnet-tag\mxnet\3rdparty\dmlc-core\src\io\local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "../datasets/faces_emore\train.rec": No such file or directory
-----------------------------------------------------------------------
i use python version 3.6 and my cuda version 10.1. I install the library mxnet-1.7.0.post2
 and version mxnet-cu101.
 What is the problem I have here? What to do to fix the error. I need help, thank you.

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md
