### ISSUE TITLE
Megaface

### ISSUE THREAD

**Issue by MartinDione** [deepinsight/insightface#16]
What is the accuracy you have got on Megaface for both verification, and identification,  because through the published paper 
ArcFace(m=0.5) Rank1@10^6:  83.27 
VR@FAR10^6:    98.48 
LResNet100E-IR@MS1M

Is there any problem with that?

**Comment by nttstar** [comment]
This is the result before removing distractor overlaps.

**Comment by MartinDione** [comment]
@nttstar  When you use distractor remover is this accepted by Megaface, because you remove some of the identities. We have a discussion with megaface committee they said, we will publish a new dataset for the evaluation purpose.

**Comment by nttstar** [comment]
@MartinDione Thank you for your information. I'm not very sure but the results will not be stable and reliable if those overlap images are not removed.
