### ISSUE TITLE
How can I get "spherefacei-s60-p0_15_96_112_0-symbol.json" in gen_megaface.py?

### ISSUE THREAD

**Issue by z384647062** [deepinsight/insightface#160]
How can I get "spherefacei-s60-p0_15_96_112_0-symbol.json" in gen_megaface.py?
`
parser.add_argument('--model', type=str, help='', default='../model/spherefacei-s60-p0_15_96_112_0,95')
`
run any script or download it somewhere?

**Comment by z384647062** [comment]
@nttstar

**Comment by nttstar** [comment]
it is the path of mxnet pretrained model.
