### ISSUE TITLE
Why detector trained with kps has lower AP than those without kps supervision?

### ISSUE THREAD

**Issue by huangh12** [deepinsight/insightface#1601]
Hello @nttstar ,  
Thanks for the great work which promotes the face analysis community a lot.
From the SCRFD project, I've noticed the hard-set mAP of SCRFD_2.5G_KPS and SCRFD_10G_KPS model is lower than their no-kps version ([table here](https://github.com/deepinsight/insightface/tree/master/detection/scrfd#pretrained-models)). I'm curious how do you comprehend this phenomena. Thank you!

![图片](https://user-images.githubusercontent.com/18748036/122890798-97b8bb80-d376-11eb-9327-16e294927ba9.png)

**Comment by nttstar** [comment]
Intuitively, I think the small face training(shallow feature map) is affected by kps loss as it is hard to be optimized.

**Comment by liufinback** [comment]
Hello @nttstar ,
I found 500M&2.5G KPS version's key points is not very accurate. Even compare to MTCNN. Is that correct or I miss something? Thank you very much if you can reply.
