### ISSUE TITLE
Why *0.75 in get_flops.py

### ISSUE THREAD

**Issue by huangh12** [deepinsight/insightface#1605]
Hello @nttstar ,  I am puzzled by below line in `get_flops.py`.  Why flops is multiplied by 0.75？

https://github.com/deepinsight/insightface/blob/e1300d32774da859b2f6c1538168c29f6cb8fb4c/detection/scrfd/tools/get_flops.py#L62

**Comment by nttstar** [comment]
compare 640x480 in contrast to 640x640

**Comment by huangh12** [comment]
Thank you.
