### ISSUE TITLE
Retinaface pre-trained model download link broken

### ISSUE THREAD

**Issue by marc-tonsen** [deepinsight/insightface#1618]
Hi all! Wanted to give retinaface a try but the Dropbox download link seems to be broken! Could you update it?
[https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0](https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0)

Thanks for your help!

**Comment by nttstar** [comment]
You can get it from insightface==0.1.5 models pack: https://1drv.ms/u/s!AswpsDO2toNKrUy0VktHTWgIQ0bn?e=UEF7C4

**Comment by marc-tonsen** [comment]
Thank you @nttstar those models work well! :+1:
