### ISSUE TITLE
where can i find these files to create my dataset? removed? eg: face2rec

### ISSUE THREAD

**Issue by xiaose26** [deepinsight/insightface#1619]

**Comment by nttstar** [comment]
https://github.com/deepinsight/insightface/blob/master/python-package/insightface/data/rec_builder.py

**Comment by conghau0112** [comment]
@nttstar  You mean? Can you help me a little more clearly?

**Comment by nttstar** [comment]
Use this class to create rec dataset. It is slower but more clear.

**Comment by conghau0112** [comment]
@nttstar  What is input and output?

**Comment by conghau0112** [comment]
@xiaose26  Why did you closed the comment? Can you help me!

**Comment by nttstar** [comment]
@conghau0112 You can read the source code and it's very simple.

**Comment by xiaose26** [comment]
https://github.com/apache/incubator-mxnet/blob/master/tools/im2rec.py

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md

**Comment by Rushikeshkoli15** [comment]
face2rec.py contains 2 classes ,which one do i use in order to create my own recordio dataset??
