### ISSUE TITLE
Do we really need multiplication?

### ISSUE THREAD

**Issue by Kwentar** [deepinsight/insightface#1620]
https://github.com/deepinsight/insightface/blob/996d844e12ed315b44935131c1f25bc4aef4e15e/recognition/arcface_torch/partial_fc.py#L158

Hi guys, I recheck your piplene and have a question: why do you multiplicate gradients by world size after backward? It means gradients in backbone will be world_size times bigger and dont looks like correct. In my toy example gradients equivalent without multiplication

**Comment by anxiangsir** [comment]
Hi, you can see this:

https://github.com/deepinsight/insightface/commit/cc4d6623023841a845ea71aa801c19af7266d1ad#commitcomment-48605254
