### ISSUE TITLE
Is ResNetV1e better than ResNetV1d?

### ISSUE THREAD

**Issue by huangh12** [deepinsight/insightface#1623]
Hi @nttstar ,  as far as I know, this is the first time I've seen an e-version ResNet. Compared with ResNetV1d, it replaces the first 3x3 maxpool with 2x2. Did you observe any accuracy gain from that?  Thank you!
https://github.com/deepinsight/insightface/blob/54b97b0c23fdbd2083c91e54526a407037399958/detection/scrfd/mmdet/models/backbones/resnet.py#L702

**Comment by nttstar** [comment]
``nn.MaxPool2d(kernel_size=3, stride=2, padding=1)`` in ResNet-D may lead to inconsistent behaviour while we convert it to caffemodel.

**Comment by huangh12** [comment]
Thank you. Why the 3x3 maxpool will cause inconsistency when converting to caffemodel？

**Comment by nttstar** [comment]
related to `ceil_mode`
