### ISSUE TITLE
[arcface_torch]几百个step后训练速度突然变慢

### ISSUE THREAD

**Issue by zhouyongxiu** [deepinsight/insightface#1624]
Training: 2021-07-03 00:08:28,141-Reducer buckets have been rebuilt in this iteration.
Training: 2021-07-03 00:09:37,089-Speed 1473.00 samples/sec   Loss 48.4599   Epoch: 0   Global Step: 100   Required: 99 hours
Training: 2021-07-03 00:10:10,158-Speed 1548.32 samples/sec   Loss 47.0618   Epoch: 0   Global Step: 150   Required: 87 hours
Training: 2021-07-03 00:10:44,123-Speed 1507.46 samples/sec   Loss 45.0560   Epoch: 0   Global Step: 200   Required: 81 hours
Training: 2021-07-03 00:11:17,872-Speed 1517.13 samples/sec   Loss 43.4365   Epoch: 0   Global Step: 250   Required: 77 hours
Training: 2021-07-03 00:11:51,112-Speed 1540.35 samples/sec   Loss 41.9377   Epoch: 0   Global Step: 300   Required: 75 hours
Training: 2021-07-03 00:12:24,561-Speed 1530.72 samples/sec   Loss 41.0083   Epoch: 0   Global Step: 350   Required: 73 hours
Training: 2021-07-03 00:12:57,934-Speed 1534.23 samples/sec   Loss 40.2119   Epoch: 0   Global Step: 400   Required: 71 hours
Training: 2021-07-03 00:13:54,513-Speed 904.93 samples/sec   Loss 39.6560   Epoch: 0   Global Step: 450   Required: 75 hours
Training: 2021-07-03 00:15:40,041-Speed 485.18 samples/sec   Loss 39.0769   Epoch: 0   Global Step: 500   Required: 87 hours
Training: 2021-07-03 00:17:25,048-Speed 487.59 samples/sec   Loss 38.5804   Epoch: 0   Global Step: 550   Required: 97 hours
Training: 2021-07-03 00:19:09,988-Speed 487.90 samples/sec   Loss 38.2579   Epoch: 0   Global Step: 600   Required: 105 hours
Training: 2021-07-03 00:20:54,885-Speed 488.10 samples/sec   Loss 37.8968   Epoch: 0   Global Step: 650   Required: 112 hours
Training: 2021-07-03 00:22:38,605-Speed 493.64 samples/sec   Loss 37.6360   Epoch: 0   Global Step: 700   Required: 117 hours
Training: 2021-07-03 00:24:22,966-Speed 490.60 samples/sec   Loss 37.3774   Epoch: 0   Global Step: 750   Required: 122 hours
Training: 2021-07-03 00:26:03,244-Speed 510.58 samples/sec   Loss 37.1269   Epoch: 0   Global Step: 800   Required: 126 hours

**Comment by anxiangsir** [comment]
Probably because of `IO`，you can set `--debug 1` to test.

**Comment by zhouyongxiu** [comment]
> Probably because of `IO`，you can set `--debug 1` to test.

yes， it lead by `IO`

**Comment by zhaoxin111** [comment]
> > Probably because of `IO`，you can set `--debug 1` to test.
> 
> yes， it lead by `IO`

How to solve the problem?
