### ISSUE TITLE
How  to train retinaface mnet?

### ISSUE THREAD

**Issue by lovehuanhuan** [deepinsight/insightface#1627]
I use the paras as these,but after 10000 epochs, the losses are still big.
network.mnet = edict()
network.mnet.pretrained = 'model/mobilenet_0_25'
network.mnet.FIXED_PARAMS = ['^stage1', '^.*upsampling']
network.mnet.BATCH_IMAGES = 16
network.mnet.HEAD_FILTER_NUM = 64
network.mnet.CONTEXT_FILTER_RATIO = 1
network.mnet.PIXEL_MEANS = np.array([0.0, 0.0, 0.0])
network.mnet.PIXEL_STDS = np.array([1.0, 1.0, 1.0])
network.mnet.PIXEL_SCALE = 1.0
network.mnet.pretrained_epoch = 0
network.mnet.max_feat_channel = 8888
network.mnet.COLOR_MODE = 1
network.mnet.USE_CROP = True
network.mnet.RPN_ANCHOR_CFG = RAC_SSH
network.mnet.LAYER_FIX = True
network.mnet.LANDMARK_LR_MULT = 2.5
network.mnet.end_epoch = 10000
**network.mnet.lr_step = '55,68,80'
network.mnet.lr = 0.01**
Are the lr and lr_step set properly?

**Comment by nttstar** [comment]
To ensure that the pixel_means and pixel_stds are consistent with your pretrained model.

**Comment by nttstar** [comment]
lr and lr_step are correct

**Comment by lovehuanhuan** [comment]
My mxnet version is v1.7.0,  and useing warming up with lr=0.001,it goes well,such as 
network.mnet.lr_step = '1,2,3,4,5,55,68,80'
network.mnet.lr = 0.001
after 80 epoches,  I get 
NFO:root:Epoch[79] Train-RPNAcc_s32=0.993882
INFO:root:Epoch[79] Train-RPNAcc_s32_BG=0.999065
INFO:root:Epoch[79] Train-RPNAcc_s32_FG=0.795863
INFO:root:Epoch[79] Train-RPNL1Loss_s32=0.109263
INFO:root:Epoch[79] Train-RPNLandMarkL1Loss_s32=0.132027
INFO:root:Epoch[79] Train-RPNAcc_s16=0.992713
INFO:root:Epoch[79] Train-RPNAcc_s16_BG=0.998643
INFO:root:Epoch[79] Train-RPNAcc_s16_FG=0.792716
INFO:root:Epoch[79] Train-RPNL1Loss_s16=0.112236
INFO:root:Epoch[79] Train-RPNLandMarkL1Loss_s16=0.131885
INFO:root:Epoch[79] Train-RPNAcc_s8=0.990188
INFO:root:Epoch[79] Train-RPNAcc_s8_BG=0.999250
INFO:root:Epoch[79] Train-RPNAcc_s8_FG=0.455645
INFO:root:Epoch[79] Train-RPNL1Loss_s8=0.166171
INFO:root:Epoch[79] Train-RPNLandMarkL1Loss_s8=0.254850
INFO:root:Epoch[79] Time cost=907.198
,but it end at epoch 80,too early,and I can't reload the module by setting pretained and pretained epoch params,i get errors as these:
INFO:root:lr 0.001000 lr_epoch_diff [1, 2, 3, 4, 5, 55, 68, 80, 130, 200] lr_steps [(1609, 0.1), (3219, 0.1), (4828, 0.1), (6438, 0.1), (8047, 0.1), (88522, 0.1), (109446, 0.1), (128760, 0.1), (209235, 0.1), (321900, 0.1)]
[01:57:01] ../src/common/exec_utils.cc:70: Variable name RF_L32_weight is used more than once!
[01:57:01] ../src/executor/graph_executor.cc:1228: Graph contains duplicate names for some of its inputs - fusion is NOT enabled!
[01:57:02] ../src/storage/storage.cc:199: Using Pooled (Naive) StorageManager for GPU
Traceback (most recent call last):
  File "train.py", line 514, in <module>
    main()
  File "train.py", line 510, in main
    lr_step=args.lr_step)
  File "train.py", line 403, in train_net
    num_epoch=end_epoch)
  File "/opt/mxnet/python/mxnet/module/base_module.py", line 499, in fit
    for_training=True, force_rebind=force_rebind)
  File "/opt/mxnet/python/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/opt/mxnet/python/mxnet/module/executor_group.py", line 280, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/opt/mxnet/python/mxnet/module/executor_group.py", line 391, in bind_exec
    self._collect_arrays()
  File "/opt/mxnet/python/mxnet/module/executor_group.py", line 316, in _collect_arrays
    for name, _ in self.data_shapes]
  File "/opt/mxnet/python/mxnet/module/executor_group.py", line 316, in <listcomp>
    for name, _ in self.data_shapes]
  File "/opt/mxnet/python/mxnet/module/executor_group.py", line 315, in <listcomp>
    self.data_arrays = [[(self.slices[i], e.arg_dict[name]) for i, e in enumerate(self.execs)]
  File "/opt/mxnet/python/mxnet/executor.py", line 279, in arg_dict
    self._symbol.list_arguments(), self.arg_arrays)
  File "/opt/mxnet/python/mxnet/executor.py", line 96, in _get_dict
    raise ValueError('Duplicate names detected, %s' % str(names))
ValueError: Duplicate names detected, ['data', 'mobilenet0_conv0_weight', 'mobilenet0_batchnorm0_gamma', 'mobilenet0_batchnorm0_beta', 'mobilenet0_conv1_weight', 'mobilenet0_batchnorm1_gamma', 'mobilenet0_batchnorm1_beta',.........

**Comment by nttstar** [comment]
The code just supports pretrained from imagenet models.

**Comment by lovehuanhuan** [comment]
thanks

**Comment by nadaboulares** [comment]
plz help how to make recognition work after trained model arcface mxnet
who can send me how to test recognition plz its urgent
