### ISSUE TITLE
np package not found, maybe it shoud be numpy

### ISSUE THREAD

**Issue by mikeshi80** [deepinsight/insightface#1633]
https://github.com/deepinsight/insightface/blob/54611b420771e89289dcf53a65c71e0777bedf05/python-package/insightface/model_zoo/arcface_onnx.py#L71

Even `import numpy as np` is added at the begining of the file, but `from np.linalg import norm` still does not work, I think it should be `from numpy.linalg import norm`

**Comment by nttstar** [comment]
Thanks, can you make a PR for this?

**Comment by nttstar** [comment]
fixed
