### ISSUE TITLE
root parameter is not used, it should use here

### ISSUE THREAD

**Issue by mikeshi80** [deepinsight/insightface#1634]
https://github.com/deepinsight/insightface/blob/54611b420771e89289dcf53a65c71e0777bedf05/python-package/insightface/app/face_analysis.py#L29

User cannot specify the root of models directory, because the `root` parameter does not be passed to `ensure_available` function.

**Comment by nttstar** [comment]
Yes, can you make a PR for this issue?

**Comment by nttstar** [comment]
fixed

**Comment by mikeshi80** [comment]
OK, I will make a PR in the future if there is another issue.

**Comment by nttstar** [comment]
thanks!
