### ISSUE TITLE
mesh_core_cython.pyx is missing in the package file

### ISSUE THREAD

**Issue by mikeshi80** [deepinsight/insightface#1635]
https://github.com/deepinsight/insightface/blob/2669ad984fa1d828373de3ab3381f7a65910837d/python-package/insightface/thirdparty/face3d/mesh/cython/setup.py#L16

When I try to install 0.3.6, I got an error, the reason is that there is no `mesh_core_cython.pyx` file in the package downloaded from pypi.org.

**Comment by nttstar** [comment]
It's strange that the pyx file is not packaged. I'm working on it. Do you know how to fix it?

**Comment by nttstar** [comment]
@mikeshi80 I just make it temporarily work(0.3.8), can you have a try? Maybe not the best solution.

**Comment by fungtion** [comment]
@nttstar Still the same problem.

**Comment by mikeshi80** [comment]
@nttstar Great, it works well now.

@fungtion If you are using the mirror of pypi.org, it will take some time to sync. I use the official pypi, 0.3.8 works well.

**Comment by fungtion** [comment]
@mikeshi80 @nttstar Yes. it works.

**Comment by Parisa-Bagherzadeh** [comment]
> @mikeshi80 I just make it temporarily work(0.3.8), can you have a try? Maybe not the best solution.

Hi, what do you mean of (0.3.8) ?
I have this error : ValueError: 'mesh_core_cython.pyx' doesn't match any files
