### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface.thirdparty.face3d.mesh.cython'

### ISSUE THREAD

**Issue by mikeshi80** [deepinsight/insightface#1636]
When I clone the current version (0.3.6), and install it by `python setup.py install`. When I try to `import insightface` after installation is finished, I got this error message:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/mikeshi/test/insightface/venv/lib/python3.7/site-packages/insightface-0.3.6-py3.7-linux-x86_64.egg/insightface/__init__.py", line 18, in <module>
>   File "/home/mikeshi/test/insightface/venv/lib/python3.7/site-packages/insightface-0.3.6-py3.7-linux-x86_64.egg/insightface/app/__init__.py", line 2, in <module>
>   File "/home/mikeshi/test/insightface/venv/lib/python3.7/site-packages/insightface-0.3.6-py3.7-linux-x86_64.egg/insightface/app/mask_renderer.py", line 8, in <module>
>   File "/home/mikeshi/test/insightface/venv/lib/python3.7/site-packages/insightface-0.3.6-py3.7-linux-x86_64.egg/insightface/thirdparty/face3d/__init__.py", line 3, in <module>
>   File "/home/mikeshi/test/insightface/venv/lib/python3.7/site-packages/insightface-0.3.6-py3.7-linux-x86_64.egg/insightface/thirdparty/face3d/mesh/__init__.py", line 9, in <module>
> ModuleNotFoundError: No module named 'insightface.thirdparty.face3d.mesh.cython'

And I also tried to run `python setup.py install` in `thirdparty/face3d/mesh/cython` directory, and the building is success, but the name of installed package is `mesh_core_cython`, I can `import mesh_core_cython` successfully.

**Comment by nttstar** [comment]
Is `python setup.py install` works in the previous version?
It seems ``pip install -e .`` can work.

**Comment by mikeshi80** [comment]
I installed 0.3.5 by `pip install insightface` directly, it downloaded from pypi.org and everything is OK.

I tried to run `pip install -e .`, it does work well.

**Comment by nttstar** [comment]
@mikeshi80 I have updated to 0.3.7 to fix the root location issue

**Comment by mikeshi80** [comment]
@nttstar Yes, I tried 0.3.7, it is OK now. And please check #1635, I still cannot install from pypi.org directly because of missing `mesh_core_cython.pyx` file. Thanks a lot.

**Comment by Parisa-Bagherzadeh** [comment]
> @nttstar Yes, I tried 0.3.7, it is OK now. And please check #1635, I still cannot install from pypi.org directly because of missing `mesh_core_cython.pyx` file. Thanks a lot.

I have this error , ValueError: 'mesh_core_cython.pyx' doesn't match any files
how can i solve it?

**Comment by Parisa-Bagherzadeh** [comment]
> @nttstar Yes, I tried 0.3.7, it is OK now. And please check #1635, I still cannot install from pypi.org directly because of missing `mesh_core_cython.pyx` file. Thanks a lot.

I have this error , ValueError: 'mesh_core_cython.pyx' doesn't match any files
how can i solve it?
