### ISSUE TITLE
arcface-torch inference.py

### ISSUE THREAD

**Issue by TonyRaven** [deepinsight/insightface#1638]
Hello!
I'm trying to run insightface/recognition/arcface_torch/inference.py with my jpg picture.
`python inference.py --weight ms1mv3_arcface_r18_fp16/backbone.pth --network r18 --img test.jpg`
Getting 
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x32768 and 25088x512)
What am i doing wrong?

**Comment by anxiangsir** [comment]
fixed

**Comment by usmancheema89** [comment]
same issue while training. Could you kindly guide me how to fix it

**Comment by NicoLivesey** [comment]
Hello, I just ran into the same issue unfortunately. Does someone have a solution ?

**Comment by NicoLivesey** [comment]
Ok for the record this is due to input size mismatch on the full connected layer at the end. The model I was using (iresnet100) was expecting an input resized to (112, 112).

**Comment by usmancheema89** [comment]
I believe all face recognition models in insight face (and others I have found) use a 112 by 112 input.
You can resize your image in data loader to 112x112.
If you want to resize a tensor (such as an image fresh out of a generator) you can use
pooler = torch.nn.AdaptiveAvgPool2d((112, 112))
resize_img = pooler(img)

**Comment by NicoLivesey** [comment]
@usmancheema89 Thanks for the answer, I was just not aware of this convention haha

**Comment by usmancheema89** [comment]
found out after banging my head a couple of time too :D
