### ISSUE TITLE
Can you provide IJBB-IJBC link?

### ISSUE THREAD

**Issue by luan1412167** [deepinsight/insightface#1647]
Hi authors,
Thanks for your useful project,
I want to test my pretrain model on IJBB-IJBC dataset, but it is not available on DatasetZoo.
Can you share link to download?
Many thanks,

**Comment by anxiangsir** [comment]
https://pan.baidu.com/s/1oer0p4_mcOrs4cfdeWfbFg

https://github.com/deepinsight/insightface/tree/master/recognition/_evaluation_/ijb
