### ISSUE TITLE
arcface pytorch inference

### ISSUE THREAD

**Issue by TonyRaven** [deepinsight/insightface#1649]
Hello!
Is it possible somehow to send several images in one time to the net and get vectors for all of them? https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/inference.py
For example, `feat = net((img1, img2)).numpy()`

**Comment by kormalev** [comment]
Something like this should work:
```python
feat = net(torch.cat((img1, img2)).numpy()
```
or
```python
# remove unsqueeze() in preprocessing above!
feat = net(torch.stack(img1, img2)).numpy()
```

**Comment by TonyRaven** [comment]
> Something like this should work:
> 
> ```python
> feat = net(torch.cat((img1, img2))).numpy()
> ```
> 
> or
> 
> ```python
> # remove unsqueeze() in preprocessing above!
> feat = net(torch.stack((img1, img2))).numpy()
> ```

It works, thank you!

**Comment by sainivedh** [comment]
@TonyRaven Are you getting good verification results with the provided arcface-torch inference script.

In my case, the cos distance between two (1, 512) embeddings for two similar faces is only 0.31.
I have tried with ms1mv3 - resnet50/100 backbones. Should I make some changes to preprocessing of image ?? 

Thanks

**Comment by Yagna24** [comment]
Hi, can you share the torch model weights used to run inference ?
