### ISSUE TITLE
Memory leak (CPU's RAM) when using Insightface detector on GPU

### ISSUE THREAD

**Issue by ybloch** [deepinsight/insightface#1659]
I use the Insightface library from Pypi (https://pypi.org/project/insightface/) and there is a severe memory leak of the CPU RAM, over 40 GB until I stopped it (not the GPU memory, it is fine, stable), 
it happens when I use the detector as follows:
```
import insightface
import cv2
import time

model = insightface.app.FaceAnalysis()

# It happens only when using GPU !!!
ctx_id = 0

image_path = "my-face-image.jpg"
image = cv2.imread(image_path)

model.prepare(ctx_id = ctx_id, det_thresh=0.3, det_size=[416, 416])

detector =  model.models["detection"]

for i in range(100000):
    start_t = time.time()
    bboxes, landmarks = detector.detect(image)
    end_t = time.time()
    print('Time detect is {}'.format(end_t - start_t))

print(f'DONE')
```
**My setup is (inside docker):**
- Docker Base Image - nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04
- Nvidia Driver - 465.27
- python - 3.6.9
- insightface==0.3.8
- mxnet==1.8.0.post0
- mxnet-cu110==2.0.0a0
- numpy==1.18.5
- onnx==1.9.0
- onnxruntime-gpu==1.8.1

**Comment by ybloch** [comment]
**I manage to solve it with the following setup:**

Ubuntu-20.04
Python-3.8
Nvidia-470
Cuda-11.3
Cudnn-8

mxnet==1.8.0.post0
onnx==1.9.0
onnxruntime-gpu==1.8.1
insightface==0.4

**Comment by nttstar** [comment]
@ybloch How do you solve it? What's the key problem?

**Comment by ybloch** [comment]
@nttstar Yes, I solve it by upgrading Ubuntu, Python, Insightface, and Cuda... 
Unfortunately, I cannot say which one (or two) caused the issue, some things couldn't be upgraded without upgrading the others, for example, Insightface does not support Python 3.6...

**Comment by nttstar** [comment]
LoL, I also found this problem by using onnxruntime-gpu=1.8. https://github.com/microsoft/onnxruntime/issues/8147
