### ISSUE TITLE
About 3D recognition

### ISSUE THREAD

**Issue by Wisgon** [deepinsight/insightface#166]
Hey, I recently found an interesting 3D alignment repo in github, it's base on ["Joint 3D Face Reconstruction and Dense Alignment with Position Map Regression Network"](https://arxiv.org/abs/1803.07835).
The repo's name is : [PRNet]( https://github.com/YadiraF/PRNet) .
I had tried it, and it's really fast. I hope it can helps you guys to build the 3D recognition.
Close it when you see it, thank you.

**Comment by nttstar** [comment]
Thank you! @jiankangdeng
