### ISSUE TITLE
Partial FC 训练一段时间，一个卡的进程没有了

### ISSUE THREAD

**Issue by 22wei22** [deepinsight/insightface#1673]
训练一段时间，就不再动了，查看GPU有一个卡进程没了，试了好几次都这样
![image](https://user-images.githubusercontent.com/25198185/126742247-84c710e3-66bd-46e6-8e04-5d650c55f953.png)

**Comment by anxiangsir** [comment]
这种情况很罕见，你可以尝试用`CUDA_VISIBLE_DEVICES`屏蔽掉那张卡

**Comment by 22wei22** [comment]
随着迭代次数的增加，CPU 总的memory会慢慢变大，但是每个进程基本上不变，最后被系统给kill掉了。这个情况是因为什么？
![image](https://user-images.githubusercontent.com/25198185/126777981-775b23a7-3886-44d3-8475-0f8634fc2d2a.png)

**Comment by anxiangsir** [comment]
可以贴一下`git diff`中你修改的部分吗？

**Comment by 22wei22** [comment]
我把项目拉下来，只改变了数据的路径，就可以训练了。其他没有改变。 我是有300万类别，3000万数据，是因为这个量太大了么

**Comment by anxiangsir** [comment]
我测试过webface40m，大概200wid，4000w图片，是没有问题的，你的torch版本可以提供一下吗，我复现复现。

**Comment by 22wei22** [comment]
我使用的是 1.6.0 我之前跑过50万id 700万数据是没问题的。麻烦你了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: AnXiang ***@***.***&gt;
发送时间: 2021年7月23日 21:36
收件人: deepinsight/insightface ***@***.***&gt;
抄送: 22wei22 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[deepinsight/insightface] Partial FC 训练一段时间，一个卡的进程没有了 (#1673)

**Comment by 22wei22** [comment]
我这边用100w类别，1000w数据，可以正常训练，CPU memory最开始训练的时候是占用38%逐渐涨到54%，目前已经稳定不再变化。
类别数量是300万的和数据量是3000万的时候就不行了。

**Comment by anxiangsir** [comment]
嗯，我复现复现找找原因，问题出在内存泄漏，内存会一直涨，这个是不正常的

**Comment by anxiangsir** [comment]
嗯，我复现复现找找原因，问题出在内存泄漏，内存会一直涨，这个是不正常的

**Comment by 22wei22** [comment]
我是这周五提issue的时候，重新拉的代码哈，拉了最新的代码也有这个问题哈。
请问你这边torch用的哪个版本？

**Comment by anxiangsir** [comment]
试试1.7，1.8，1.9我都测试过了

**Comment by 22wei22** [comment]
我换了版本之后，还是出现这个memory逐渐增大被kill掉的情况。
我用50wID，700w数据训练的时候也会出现这个问题，不过每次从一个epoch开始逐渐增大，当一个epoch结束的时候，memory就掉下来了，然后重复这个过程。因为label和数据量少没有被kill掉。
我是将图像的路径放在了一个txt文件里面进行读取，跟这个有关系么？

**Comment by 22wei22** [comment]
> 试试1.7，1.8，1.9我都测试过了

请问你这边程序运行起来之后，cpu memory一直是恒定的么？ 基本没有变化么？
我的会从一开始占用45%逐渐占用到60%，最后被kill掉

**Comment by 22wei22** [comment]
请问一下你的CPU memory是多大？

**Comment by 22wei22** [comment]
原因找到了，我这边读取图片的时候，用python list保存img_path和label，数据量大的时候，会出现内存泄露的问题

**Comment by anxiangsir** [comment]
好的

**Comment by ygtxr1997** [comment]
> 

可以讲讲具体问题是出在哪里？解决思路是怎样的吗？我这边也遇到了内存泄漏的问题

**Comment by anxiangsir** [comment]
如果要对有梯度记录的tensor进行积累操作的时候，最好移除计算图外，或者加上item()例如：

```python
some_list: List = []
some_tensor: torch.nn.Tensor
with torch.no_grad():
    some_list.append(some_tensor.item())
```

**Comment by 22wei22** [comment]
> > 
> 
> 可以讲讲具体问题是出在哪里？解决思路是怎样的吗？我这边也遇到了内存泄漏的问题

你是通过读取txt来获取文件路径的么？
比如 imgpath.txt里面放着这些路径
/data1/1.jpg
/data1/2.jpg

**Comment by xggIoU** [comment]
> 



> Reference

请问您是怎么解决的呀，我也遇到这个问题，读取txt，内存使用率慢慢增大，最后就崩了

**Comment by xggIoU** [comment]
> > > 
> > 
> > 
> > 可以讲讲具体问题是出在哪里？解决思路是怎样的吗？我这边也遇到了内存泄漏的问题
> 
> 你是通过读取txt来获取文件路径的么？ 比如 imgpath.txt里面放着这些路径 /data1/1.jpg /data1/2.jpg

我就是这样的txt，内存泄漏一直解决不了

**Comment by NOTGOOOOD** [comment]
> > > > 
> > > 
> > > 
> > > 可以讲讲具体问题是出在哪里？解决思路是怎样的吗？我这边也遇到了内存泄漏的问题
> > 
> > 
> > 你是通过读取txt来获取文件路径的么？ 比如 imgpath.txt里面放着这些路径 /data1/1.jpg /data1/2.jpg
> 
> 我就是这样的txt，内存泄漏一直解决不了

我想可能是因为list长期占用了太多的内存，导致内存泄漏。通常我会用numpy.ndarray 而不是用built-in对象 List，这是因为底层Cbind可以很好的支持numpy.Array对象

**Comment by nttstar** [comment]
https://github.com/pytorch/pytorch/issues/13246
