### ISSUE TITLE
What Threshold to use for Face Verification?

### ISSUE THREAD

**Issue by Nelthirion** [deepinsight/insightface#168]
Dear Author

The `test.py' code in the deploy package calculates the Distance and Similarity of 2 faces. But is there a proper threshold to dismiss two faces or accept them as from the same person?

For example DLib's network is trained for a `0.6` radius and if the L2 distance of the faces is more than that, then the faces are not from the same person.

Thanks

**Comment by Nelthirion** [comment]
Thanks for the response.

I've been testing the Cosine Similarity (`sim = np.dot(f1, f2.T)` ) and it seems that a threshold of `sim>=0.5` is good enough. 

Do you suggest I should use `dist = np.sum(np.square(f1 - f2))` or `sim = np.dot(f1, f2.T)` ? Since the 0.8~1.4 threshold you mentioned seems to only be attainable with `dist = np.sum(np.square(f1 - f2))`.

**Comment by xxllp** [comment]
I get an error 

> Traceback (most recent call last):
  File "../deploy/test.py", line 19, in <module>
    f1 = model.get_feature(img)
  File "/home/mlp/xxl/insightface/deploy/face_embedding.py", line 62, in get_feature
    ret = self.detector.detect_face_limited(face_img, det_type = self.args.det)
  File "/home/mlp/xxl/insightface/deploy/mtcnn_detector.py", line 397, in detect_face_limited
    height, width, _ = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by hzzengyang3** [comment]
maybe no face detected @xxllp
