### ISSUE TITLE
Partial-fc of with mxnet: setting sample rate raises AssertionError

### ISSUE THREAD

**Issue by JokaHD** [deepinsight/insightface#1691]
Hi, 
I'm using partial fc training on mxnet. 
When sample rate is set to 0.1, an AssertionError is raised by line 321 of memory_module.py [(link)](https://github.com/deepinsight/insightface/blob/337c8abda9a9930ac05f9562921510171935afd0/recognition/partial_fc/mxnet/memory_module.py#L321) as below:
```
assert memory_bank.num_local == memory_bank.num_sample, "pass"
```
I found that these two parameters are defined in line 106 and 107 of train_memory.py [(link)](https://github.com/deepinsight/insightface/blob/337c8abda9a9930ac05f9562921510171935afd0/recognition/partial_fc/mxnet/train_memory.py#L106) as below:
```
num_local = (config.num_classes + size - 1) // size
num_sample = int(num_local * config.sample_ratio)
``` 
Apparently they are not equal if sample_ratio is set to 0.1. 
Is it not supported now or is there something I haven't noticed?
Thank you.

**Comment by anxiangsir** [comment]
```python
if not bool(config.sample_ratio - 1):
    grad, loss = self.backward(total_feature, total_label)
else:
    grad, loss = self.backward_sample(total_feature, total_label)
```
when sample rate is set to 0.1, The following function is executed：

https://github.com/deepinsight/insightface/blob/337c8abda9a9930ac05f9562921510171935afd0/recognition/partial_fc/mxnet/memory_module.py#L388
