### ISSUE TITLE
Can not download MS1MV2

### ISSUE THREAD

**Issue by hamid-mp** [deepinsight/insightface#1697]
Hi, I tried to download MS1MV2 with R100 backbone on MXnet, but it is uploaded on Bdrive which is in chinese language and I can't download it. could you please upload that in google drive? thanks in advance

**Comment by nttstar** [comment]
https://github.com/deepinsight/insightface/tree/master/model_zoo
Link updated. 

ps: you can also download the ONNX models.

**Comment by hamid-mp** [comment]
Thanks a lot
