### ISSUE TITLE
trained arcface_torch model by one gpu?

### ISSUE THREAD

**Issue by eeric** [deepinsight/insightface#1699]

**Comment by anxiangsir** [comment]
https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch#1-single-node-8-gpus

**Comment by eeric** [comment]
> https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch#1-single-node-8-gpus

not answer

**Comment by anxiangsir** [comment]
just set `--nproc_per_node=1`

```python
python -m torch.distributed.launch --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port=1234 train.py configs/ms1mv3_r50
```

**Comment by eeric** [comment]
> just set `--nproc_per_node=1`
> 
> ```python
> python -m torch.distributed.launch --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port=1234 train.py configs/ms1mv3_r50
> ```

Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main(parser.parse_args())
  File "train.py", line 108, in main
    for step, (img, label) in enumerate(train_loader):
  File "/mnt/sdb_solid/code/2021/insightface/recognition/arcface_torch/dataset.py", line 49, in __iter__
    self.iter = super(DataLoaderX, self).__iter__()
  File "/mnt/sdb_solid/code/2021/insightface/recognition/arcface_mxnet/insightface_rec/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/mnt/sdb_solid/code/2021/insightface/recognition/arcface_mxnet/insightface_rec/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/mnt/sdb_solid/code/2021/insightface/recognition/arcface_mxnet/insightface_rec/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by lizhenstat** [comment]
@eeric hi, I have only one GPU too, do you know what does parameter "master_port" mean?
Thanks

**Comment by anxiangsir** [comment]
just `python train.py configs/xxx.py`
@lizhenstat

**Comment by anxiangsir** [comment]
@eeric using a training server which has large RAM

**Comment by eeric** [comment]
> @eeric hi, I have only one GPU too, do you know what does parameter "master_port" mean?
> Thanks

server port

**Comment by eeric** [comment]
> just `python train.py configs/xxx.py`
> @lizhenstat

arcface_mxnet, ok，
while arcface_torch, not

**Comment by lizhenstat** [comment]
@eeric @anxiangsir  Hi, thanks for your help, I have followed the provided code and successful run the code
[https://github.com/eeric/Face_recognition_cnn/tree/main/code/insightface/arcface_torch](url)
 
it run the code on "emore" dataset with "r18" network, it looks like it will take about 300+ hours.
```bash
Training: 2021-08-12 11:06:36,028-Speed 75.49 samples/sec   Loss 47.8657   LearningRate 0.0125   Epoch: 0   Global Step: 100   Required: 323 hours
Training: 2021-08-12 11:07:12,610-Speed 87.49 samples/sec   Loss 48.8414   LearningRate 0.0125   Epoch: 0   Global Step: 150   Required: 314 hours
Training: 2021-08-12 11:07:49,507-Speed 86.75 samples/sec   Loss 48.9012   LearningRate 0.0125   Epoch: 0   Global Step: 200   Required: 310 hours
Training: 2021-08-12 11:08:26,635-Speed 86.21 samples/sec   Loss 48.8971   LearningRate 0.0125   Epoch: 0   Global Step: 250   Required: 308 hours
Training: 2021-08-12 11:09:03,467-Speed 86.90 samples/sec   Loss 48.9376   LearningRate 0.0125   Epoch: 0   Global Step: 300   Required: 306 hours
```

Thanks a lot!

**Comment by anxiangsir** [comment]
> @eeric @anxiangsir Hi, thanks for your help, I have followed the provided code and successfully run the code
> [https://github.com/eeric/Face_recognition_cnn/tree/main/code/insightface/arcface_torch](url)
> 
> it run the code on "emore" dataset with "r18" network, it looks like it will take about 300+ hours.
> 
> ```shell
> Training: 2021-08-12 11:06:36,028-Speed 75.49 samples/sec   Loss 47.8657   LearningRate 0.0125   Epoch: 0   Global Step: 100   Required: 323 hours
> Training: 2021-08-12 11:07:12,610-Speed 87.49 samples/sec   Loss 48.8414   LearningRate 0.0125   Epoch: 0   Global Step: 150   Required: 314 hours
> Training: 2021-08-12 11:07:49,507-Speed 86.75 samples/sec   Loss 48.9012   LearningRate 0.0125   Epoch: 0   Global Step: 200   Required: 310 hours
> Training: 2021-08-12 11:08:26,635-Speed 86.21 samples/sec   Loss 48.8971   LearningRate 0.0125   Epoch: 0   Global Step: 250   Required: 308 hours
> Training: 2021-08-12 11:09:03,467-Speed 86.90 samples/sec   Loss 48.9376   LearningRate 0.0125   Epoch: 0   Global Step: 300   Required: 306 hours
> ```
> 
> Thanks a lot!

you can try a small datasets

**Comment by eeric** [comment]
one-gpu and partial pc, not pytorch, while paddle
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/arcface_paddle/code/one-gpu

**Comment by DXJ-Xiao** [comment]
@eeric Hello, do you still have the r18 training link model on 360 face data set? I wonder if you can provide it, thank you very much

**Comment by eeric** [comment]
not use r18, but mobilefacenet or r50, r100

**Comment by DXJ-Xiao** [comment]
@eeric Hello, do you still have the r18 training link model on 360 face data set? I wonder if you can provide it, thank you very much

> 
Thank you for your reply. I want a model of R18 to test, but the equipment conditions are not enough
