### ISSUE TITLE
How do you deal with the profile faces when aligning faces in CFP dataset?

### ISSUE THREAD

**Issue by BraveApple** [deepinsight/insightface#171]

**Comment by nttstar** [comment]
Nothing special, use 5 landmarks and similarity transformation.

**Comment by cannguyen275** [comment]
Hey guys, sorry for bothering you. But my issue might be related to this issue.

That is I sometimes received an up-side-down aligned face when I used the C++ version of the face align code. Especially, it's usually happened with the profile images in CFP dataset.

Debugging brings me to a conclusion that it's an error in calculating the rotation value in SimilarityTransform in C++, when its scikit-image version in Python works perfectly without any issues.

I've created an issue in #1559 but no one care, then I try to re-post this issue around to find if someone can help.

Thanks a lot for your attention.
