### ISSUE TITLE
mbf + vit transformer, arcface_torch error

### ISSUE THREAD

**Issue by eeric** [deepinsight/insightface#1710]
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.

may because that multi input to model

**Comment by anxiangsir** [comment]
try this:


```python
backbone = torch.nn.parallel.DistributedDataParallel(
module=backbone, broadcast_buffers=False, device_ids=[local_rank], find_unused_parameters=True)
```

**Comment by eeric** [comment]
thanks, but I tried, failedly, because loss=nan that no than 1st epoch.

**Comment by anxiangsir** [comment]
vit model has been updated
