### ISSUE TITLE
FaceAnalysis(allowed_modules)的参数allowed_modules有哪些值可以传入以及返回什么样的结果？

### ISSUE THREAD

**Issue by json007** [deepinsight/insightface#1719]
class FaceAnalysis:
    def __init__(self, name=DEFAULT_MP_NAME, root='~/.insightface', allowed_modules=None):
        onnxruntime.set_default_logger_severity(3)
        self.models = {}
        self.model_dir = ensure_available('models', name, root=root)
        onnx_files = glob.glob(osp.join(self.model_dir, '*.onnx'))
        onnx_files = sorted(onnx_files)

没看到文档，代码中也没有注释

**Comment by nttstar** [comment]
文档后续会陆续完善 谢谢关注

**Comment by json007** [comment]
多谢。能先回复下allowed_modules有哪些值吗，我先测试测试

**Comment by nttstar** [comment]
代码可以通过app.models.keys()来获取
