### ISSUE TITLE
Error: undefined symbol: _ZN3c104cuda12device_countEv 

### ISSUE THREAD

**Issue by kevinzezel** [deepinsight/insightface#1721]
Hi,

I got this error on image_demo.py:

Traceback (most recent call last):
  File "image_demo.py", line 3, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result_pyplot
  File "/dados/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/dados/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/opt/conda/lib/python3.6/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .bbox import bbox_overlaps
  File "/opt/conda/lib/python3.6/site-packages/mmcv/ops/bbox.py", line 4, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/opt/conda/lib/python3.6/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/conda/lib/python3.6/site-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda12device_countEv

>>> torch.__version__
'1.7.0a0+8deb4fe'

>>> torch.version.cuda
'11.0'

>>> torch.cuda.is_available()
True

mmcv-full 1.3.11

**Comment by nttstar** [comment]
Torch image_demo.py is not fully tested. Please use ONNX test scripts instead.

**Comment by kevinzezel** [comment]
Thanks for the answer! 

I got the same error on scrfd2onny.py. I think is the version of cuda.

Please, what are the cuda, pytorch and mmcv that you are using?

**Comment by nttstar** [comment]
Take a look at mmcv's homepage and make sure you have installed the right version to satisfy your cuda driver.

**Comment by kevinzezel** [comment]
Thanks!! I managed to run on docker container nvidia/cuda:10.2-cudnn8-runtime-ubuntu18.04.

conda install pytorch=1.9.0 torchvision=0.10.0 torchaudio=0.9.0 cudatoolkit=10.2 -c pytorch
pip install mmcv-full==1.3.3 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html
pip install onnxruntime-gpu==1.6.0
