### ISSUE TITLE
🔥 How to get feats

### ISSUE THREAD

**Issue by yfq512** [deepinsight/insightface#1725]
I want to use this "insightface/recognition/arcface_torch/inference.py" to get feats from image, Do I need to perform face detection and face alignment first？Can you show me the usage?

我想用这段代码—“insightface/recognition/arcface_torch/inference.py”从图像提取特征，我是否事先要进行人脸检测和人脸对齐的操作呢？我希望有人能写个简单的例子说明下。

**Comment by wuli66ly** [comment]
maybe it doesnot need. but I have the same question about **how to update face database** when i inference on a test viseo

**Comment by yfq512** [comment]
@wuli66ly Thanks for you reply, in "insightface/recognition/arcface_torch/inference.py", input image resize (112,112),  in my idea, if not face detection and face alignment first, It seems unreasonable.

谢谢你的回复，在这个代码里，输入图像给缩放置（112,112），实际上，如果输入图是一张全身照，我觉得如若不事先进行人脸检测和人脸对齐，这种直接对原图resize(112,112)肯定是不合常理的。

**Comment by Zmmccc** [comment]
您好，我和您有相同的问题。所以是不是用inference.py进行推理时，如果直接输入一张全身图，会出问题吗？我提取出的特征进行对比时没有一个识别对的555555，所以我觉得问题可能在这里，想跟您确认一下。希望得到您的回复！
