### ISSUE TITLE
Dataset link Not working 

### ISSUE THREAD

**Issue by ajay01994** [deepinsight/insightface#1730]
the dataset link given in the  repo isnt working

**Comment by nttstar** [comment]
which one

**Comment by ajay01994** [comment]
![image](https://user-images.githubusercontent.com/31235529/131242250-5f42a369-2983-4590-970a-7d11dd212398.png)

**Comment by nttstar** [comment]
Updated

**Comment by ajay01994** [comment]
Thank you , if possible would you mind  releasing the SCFRD method with FBNET V3 and faster RCNN ? generally who follow the d2go module (https://github.com/facebookresearch/d2go)
