### ISSUE TITLE
Questions about agedb2pack and cfp2pack.py

### ISSUE THREAD

**Issue by philoxmyu** [deepinsight/insightface#174]
what's the format in cfp_frontal_paris.mat and 04_FINAL_protocol_30_years.mat? 
I want to re-generation these bin files, could you share these matlab files and related txt files?
thanks!

**Comment by HaoLiuHust** [comment]
same question with you

**Comment by cici-tan** [comment]
same question here!

**Comment by wangchust** [comment]
same question here!

**Comment by mengzhibin** [comment]
these files need to be download from the data websit. look through the issues, i have seen the answer of your question. @wangchust

**Comment by clhne** [comment]
same question.
@philoxmyu Did you get the mat file?
Thanks.
