### ISSUE TITLE
Arcface PyTorch Backbones and Inference

### ISSUE THREAD

**Issue by CengizhanYurdakul** [deepinsight/insightface#1745]
Hello and thanks for great works,
My first question was while examining the pytorch implementation of Arcface, I saw the r2060 backbone in the table. But I could not find the weights of this model in the link. Haven't you posted yet or did I miss something?

![Screenshot from 2021-09-08 11-40-49](https://user-images.githubusercontent.com/53911245/132479994-91c066f5-c0c2-47db-9207-2972a6e76b95.png)
My second question is, I couldn't see any alignment process while inference. Did you use a different alignment template or is the old template still up to date? (Here I am assuming that you have trained pytorch from scratch and have not made any conversions from mxnet)
![Screenshot from 2021-09-08 12-05-14](https://user-images.githubusercontent.com/53911245/132480814-695053a0-3e5c-4b09-825c-cb778d30e72d.png)

**Comment by eeric** [comment]
align face
https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/onnx_ijbc.py
e.g.: class AlignedDataSet(mx.gluon.data.Dataset)

recognition onnx inference example for single image:
https://github.com/eeric/Face_recognition_cnn/tree/main/code/insightface/onnx_inference
