### ISSUE TITLE
recognition onnx inference

### ISSUE THREAD

**Issue by eeric** [deepinsight/insightface#1746]
recognition onnx inference example for single image:
https://github.com/eeric/Face_recognition_cnn/tree/main/code/insightface/onnx_inference

**Comment by nttstar** [comment]
no advertising plz

**Comment by eeric** [comment]
??????
  providing solution for some people need, not while advertising, you are  nervous.

**Comment by nttstar** [comment]
You can **ANSWER**  issues by your own projects/codes. But this thread is not quite an issue.

**Comment by eeric** [comment]
at original, I do not find answer about onnx inference. 
to avoid waste time, I 'd like share my code.

**Comment by kivan11** [comment]
thank you  very much @eeric

**Comment by nttstar** [comment]
> at original, I do not find answer about onnx inference.
> to avoid waste time, I 'd like share my code.

If anyone asks a question about onnx inference, you can give an answer as
https://github.com/eeric/Face_recognition_cnn/tree/main/code/insightface/onnx_inference

**Comment by kivan11** [comment]
@eeric  CAN THIS SHOW ME THE IDENTITIES OF PERSONS.?????

**Comment by kivan11** [comment]
@eeric can you help how to predict the identity of person in image with onnx model???
can you help me please
