### ISSUE TITLE
About the model comparison in SCRFD

### ISSUE THREAD

**Issue by Monkey-D-Luffy-star** [deepinsight/insightface#1748]
Thank you for your work.
but why are your reported retinaface accuracy so low in hard subset?
<img width="647" alt="37858330911fd89c9012bb77c98e7b7" src="https://user-images.githubusercontent.com/59432975/132636751-47355af9-42f1-4f9f-87ba-9eda0c6a5b66.png">

**Comment by nttstar** [comment]
Test on VGA resolution

**Comment by Monkey-D-Luffy-star** [comment]
Thank you for your reply. I noticed it too.

**Comment by jiangxiangchuan** [comment]
@nttstar 

What does "VGA resolution" mean? Thank you.

**Comment by Monkey-D-Luffy-star** [comment]
@jiangxiangchuan 640×480 pixels
