### ISSUE TITLE
Two extra noisy images in Facescrub for Megaface Challenge

### ISSUE THREAD

**Issue by MartinXM** [deepinsight/insightface#175]
I checked the Facescrub dataset for Megaface Challenge and found two extra noisy images after using facescrub_noises.txt provided by the author:

Christian_Bale_12006.png
Pamela_Anderson_2474.png

These two images are not real person. One is a toy figure and the other one is a painting.

**Comment by nttstar** [comment]
^^ Thank you for reporting this!
