### ISSUE TITLE
Question about the Used Preprocessing

### ISSUE THREAD

**Issue by marcohuber** [deepinsight/insightface#1753]
Hi,
first of all thank you for providing the code, models and preprocessed images.

I downloaded the MS1M-ArcFace (85K ids/5.8M images) [5,7] from [here](https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_) and extracted the images from the bin file using this [code](https://github.com/wujiyang/Face_Pytorch/blob/master/utils/load_images_from_bin.py).

Now when I compare the images that I aligned with the current face alignment (based on landmarks detected by MTCNN) and the ones I extracted, they look slightly different. I even tried the face alignment code from [2018](https://github.com/deepinsight/insightface/blob/60bb5829b1d76bfcec7930ce61c41dde26413279/src/common/face_preprocess.py), but I cannot reproduce the same alignment.

(Mine)
![Abel_Pacheco_0001](https://user-images.githubusercontent.com/38668954/133396842-0737ca1d-3208-4b30-bb6d-32da3925e510.jpg)
(Yours)
![0](https://user-images.githubusercontent.com/38668954/133396854-f5c20b1f-8c8d-4ed5-a44d-5017009addc1.jpg)

Can you provide me with more information on which alignment you used at the time? I don't think it's because of MTCNN and the landmarks, because at least the timestamp of the files says they are from 2018, so before RetinaFace.

My problem is that I have models that have been trained with this alignment, but the performance drops sharply when I evaluate them with the current alignment.

Thanks in advance!
Best,
Marco

**Comment by nttstar** [comment]
I believe there's a difference between predicted landmarks.

**Comment by marcohuber** [comment]
Can you link me the script that was used to predict the landmarks for the images in MS1M-ArcFace? I used [this script](https://github.com/deepinsight/insightface/blob/60bb5829b1d76bfcec7930ce61c41dde26413279/deploy/face_model.py) which was probably used at that time.
