### ISSUE TITLE
Feature mismatch

### ISSUE THREAD

**Issue by leoaaaaaaa** [deepinsight/insightface#1756]
There are two pictures and they include the same person, but one picture rotation exceeds 90 degrees by rotating taking in Mobile, and another is normal.
then call the `detector.detect` to detect the person, then call `model.get_input` and `model.get_feature` to generate the feature for these two pictures. 
after two features are generated, then compare them, they are not matched, but they are the same person.

And it looks like if I use another rotating picture to generate a feature, and it is similar to the current rotating picture.

Can you help with this? thanks

**Comment by leoaaaaaaa** [comment]
@nttstar Can you help with this? thanks very much!

**Comment by nttstar** [comment]
The landmark may be inaccurate for 90 degrees rotated picture.

**Comment by leoaaaaaaa** [comment]
@nttstar Thank you very much for your reply.

Is there a solution to fix it? thanks
