### ISSUE TITLE
A question about resuming ArcFace-Torch.

### ISSUE THREAD

**Issue by csbhr** [deepinsight/insightface#1758]
Hi, Thanks for your nice work!

I am going to fine-tune the ArcFace-Torch by using the checkpoints download from BaiduYun(e8pw):
link: https://pan.baidu.com/share/init?surl=CL-l4zWqsI1oDuEEYVhj-g
file path: arcface_torch/ms1mv3_arcface_r50_fp16/

I notice that the MS1M-RetinaFace training dataset's "num_classes" is 93431. However, the num_classes in "weight" loaded from the files "rank_0_softmax_weigh.pt"~"rank_0_softmax_weigh.pt" are 11398, 11398, 11398, 11398, 11397, 11397, 11397, 11397, respectively. And the sum of them is 91180, which is not 93431.

Thus, when I set "resume=True", the "weight" and "weight_mom" can not resume successfully. And then they are initialized randomly.

I wonder what is wrong with this?
Is it ok when I only load the pre-trained "backbone" but don't load the "weight" and "weight_mom"?

I will be very happy if you can kindly reply to me.

**Comment by anxiangsir** [comment]
I will re-upload the pre-training model of the latest code in a day.

**Comment by anxiangsir** [comment]
I will re-upload the pre-training model of the latest code in a day.

**Comment by csbhr** [comment]
Thank you. This is very helpful for me.

**Comment by anxiangsir** [comment]
Pre-training model of `ms1mv3_arcface_r50`  has been re-uploaded. 
 
```python3
config.resume = True
config.lr = 0.0001  
+---------------+-------+-------+--------+-------+-------+-------+
|    Methods    | 1e-06 | 1e-05 | 0.0001 | 0.001 |  0.01 |  0.1  |
+---------------+-------+-------+--------+-------+-------+-------+
| ms1mv3_r50    | 89.91 | 94.91 | 96.64  | 97.74 | 98.49 | 99.12 |
+---------------+-------+-------+--------+-------+-------+-------+

```

**Comment by zzzzz314314** [comment]
Hello,
for the [Resnet34, Arcface, MS1MV3], the weights do not get updated. The number of classes is still inconsistent (91180!=93431) in both baidu and one drive.

https://pan.baidu.com/s/1CL-l4zWqsI1oDuEEYVhj-g#list/path=%2Fsharelink3494273403-838107067808247%2Farcface_torch%2Fms1mv3_arcface_r34_fp16&parentPath=%2Fsharelink3494273403-838107067808247

https://onedrive.live.com/?authkey=%21AFZjr283nwZHqbA&id=4A83B6B633B029CC%215579&cid=4A83B6B633B029CC
 
Would it be possible that you re-upload them?
Many thanks
