### ISSUE TITLE
Do you know why C++ Caffe Model  is slower then Python MXnet model in insight face?

### ISSUE THREAD

**Issue by jeehyun100** [deepinsight/insightface#176]
I tested a 112 by 112 image get 512 features using insightface source  in the same machine.

Caffe LResNet50E-IR is about 0.8 - 0.9 sec base on c++.
Mxnet LResNet50E-IR is about 0.3 - 0.4 sec base on python.

Do you know why? I think c++ caffe should be faster than python.

**Comment by nttstar** [comment]
Sorry I don't know.. But I think it is nothing related to the binding language as all computations are done on GPU CUDA side.

**Comment by jeehyun100** [comment]
Thank you very much.
I just wondering how much time does it spend for training with K80?
I tried to train like (1). Train ArcFace with LResNet100E-IR you writed on github  with NVIDIA 1080, but It spends so much time. 100000 epoch looks like almost impossible to train.

Can you tell me how much time spend to training?

**Comment by nttstar** [comment]
#163

**Comment by yxchng** [comment]
@jeehyun100 Have you solved the speed problem?

**Comment by youthM** [comment]
Can you release your caffemodel and prototxt( LResNet50E-IR)? @jeehyun100
