### ISSUE TITLE
pretrained model of resnet50

### ISSUE THREAD

**Issue by maiduchoang98** [deepinsight/insightface#1762]
Hello,
I am currently using your pretrained model: ms1mv2_arcface_r50_fp16 according this link: https://onedrive.live.com/?authkey=%21AFZjr283nwZHqbA&id=4A83B6B633B029CC%215583&cid=4A83B6B633B029CC 
I try to inference on LFW and TAR@FAR=1e-3 is only about 22.7% while in the arcface paper this number is over 90%
Because I run the file inference.py to test so I think it's not because of the code
Can you tell me whether the model in above link is your best model or just an average model?
Thank you very much!

**Comment by nttstar** [comment]
why do you need FAR=1e-3 on LFW set?

**Comment by nttstar** [comment]
why do you need FAR=1e-3 on LFW set?

**Comment by maiduchoang98** [comment]
oh i have checked the preprocess again, i did not align images before inference so it leads to the decrease of result. I tested on FAR=1e-3 because if FAR=1e-6, the result was almost zero ( without alignment). Thank you for replying!
