### ISSUE TITLE
What is WebFace600k dataset? 

### ISSUE THREAD

**Issue by SthPhoenix** [deepinsight/insightface#1770]
Hi! I have noticed you mentioned this dataset for many recently released pretained models, but when I try to google it I can only find WebFace260k dataset.

Is it a typo, or this is you internal unreleased dataset?

**Comment by anxiangsir** [comment]
WebFace600K(600K identities) means WebFace12M(12 million images), a subset of WebFace42M(cleaned WebFace260M).

**Comment by SthPhoenix** [comment]
Thanks, @anxiangsir ! 
This cleaned dataset can be obtained as part of WebFace260M from face-benchmark.com? Or it must be requested separately?

**Comment by anxiangsir** [comment]
This cleaned dataset can be obtained from face-benchmark.com, named WebFace12M.

**Comment by SthPhoenix** [comment]
Thanks for help!

**Comment by 205418367** [comment]
请问 face-benchmark.com的地址打不开怎么解决？具体地址是什么？

**Comment by 205418367** [comment]
请问WebFace12M有下载链接吗？

**Comment by anxiangsir** [comment]
> 请问WebFace12M有下载链接吗？

face-benchmark.com

**Comment by SthPhoenix** [comment]
It's actually face-benchmark.org, excuse me for misleading.

**Comment by jyshee** [comment]
> 

Hi, where could I find the attributes list of the webface dataset, like pose, race, mask, which were described in the paper? 
Thanks a lot

**Comment by anxiangsir** [comment]
> > 
> 
> 
> 
> Hi, where could I find the attributes list of the webface dataset, like pose, race, mask, which were described in the paper? 
> 
> Thanks a lot

https://www.face-benchmark.org/download.html

WebFace260M: A Benchmark Unveiling the Power of Million-scale Deep Face Recognition

**Comment by jyshee** [comment]
> > > 
> > 
> > 
> > Hi, where could I find the attributes list of the webface dataset, like pose, race, mask, which were described in the paper?
> > Thanks a lot
> 
> https://www.face-benchmark.org/download.html
> 
> WebFace260M: A Benchmark Unveiling the Power of Million-scale Deep Face Recognition

I have downloaded the clean part, but could find the attributes of each image, like pose, race, mask e.g.

**Comment by wavelet2008** [comment]
> It's actually face-benchmark.org, excuse me for misleading.



> > > > 
> > > 
> > > 
> > > Hi, where could I find the attributes list of the webface dataset, like pose, race, mask, which were described in the paper?
> > > Thanks a lot
> > 
> > 
> > https://www.face-benchmark.org/download.html
> > WebFace260M: A Benchmark Unveiling the Power of Million-scale Deep Face Recognition
> 
> I have downloaded the clean part, but could find the attributes of each image, like pose, race, mask e.g.

i need  baidu  pan download  link,  thans
