### ISSUE TITLE
iResNet

### ISSUE THREAD

**Issue by fisakhan** [deepinsight/insightface#1774]
Can some please help me what is iResnet? What is the difference between resnet and iresnet? where can find details about iResnet?

**Comment by LightManxx** [comment]
paper: https://arxiv.org/abs/2004.04989

**Comment by nttstar** [comment]
original defined in https://github.com/deepinsight/insightface/blob/master/recognition/arcface_mxnet/symbol/fresnet.py

**Comment by fisakhan** [comment]
thanks @LightManxx and @nttstar

**Comment by OrkhanHI** [comment]
What does the 2060 number refer to in iResNet2060?

**Comment by IsidoreSong** [comment]
After checking the papers and their code, I finally found the "iresnet" is to our surprising: which is an implementation of _Deep Pyramidal Residual Networks_.
Actually, in the paper ArcFace, it tells us the version of the resnet. You may search "9,8" and found the reference.

BN-Conv-BN-PReLU-Conv-BN is not the structure of iresnet but exactlly the structure of _Deep Pyramidal Residual Networks_ (if we agree that iresnet is the _Improved Residual Networks for Image and Video Recognition)._

What's more, the code in [fresnet.py](https://github.com/deepinsight/insightface/blob/master/recognition/arcface_mxnet/symbol/fresnet.py) contains a resnet_v4, which is an option at line 969 but never implemented.

So I think the implemented iresnet is actually resnet_v3 and other versions in the original code could be:
v1: Deep Residual Learning for Image Recognition
v2: Identity Mappings in Deep Residual Networks
v3: Deep Pyramidal Residual Networks
v4 (iresnet): Improved Residual Networks for Image and Video Recognition
