### ISSUE TITLE
谁有WebFace600K数据集训练的MobileFacenet模型？

### ISSUE THREAD

**Issue by 205418367** [deepinsight/insightface#1803]
![image](https://user-images.githubusercontent.com/47652945/139006630-2d58309a-ab0a-40ce-97fa-b304d293b79f.png)

**Comment by kkzh2313** [comment]
> It is in our latest pip package.

Hi, I don't find this model . Can you provide a link?
![image](https://user-images.githubusercontent.com/34201133/142367105-7b786c48-2b76-457d-b23c-d02474de53cd.png)
