### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#181]
Hi,

Are they pre-trained model to test with different face domains ? 

Best

**Comment by nttstar** [comment]
what do you mean?

**Comment by MyraBaba** [comment]
Le me make myself more clear :) 

I dont have powerfull GPU  at the moment. But I want try produced model with my 30.000 faces . 

I didnt clearly understand how I can test recognition with our own faces db to see is it fit our needs.

Any help appreciated. If it its better our current recognition we would love get paid support from you to integration.

First we want to test the model produced by this ARCface.

(do we have to train with our faces db ? or is it enough your trained model)

best
