### ISSUE TITLE
AttributeError: module 'mxnet.symbol' has no attribute 'LSoftmax'

### ISSUE THREAD

**Issue by lemo2012** [deepinsight/insightface#182]
I first copy "operator" folder of insightface to “3rdparty” folder of mxnet, then compile mxnet successfully. At last I bind python with mxnet. 
What do I miss?

**Comment by nttstar** [comment]
Copy LSoftmax operators to mxnet operator folders.

**Comment by shdyn** [comment]
Hi, I copied files in 3rdparty/operators of InsightFace to src/operator of MXNet. After compiling the MXNet source codes and install the python bindings, the program still cannot have no attribute "LSoftmax".  Can you please tell me how to install them properly?
