### ISSUE TITLE
Webface600k r50 accuracy in model_zoo documentation

### ISSUE THREAD

**Issue by SthPhoenix** [deepinsight/insightface#1820]
Hi! I have noticed that r50 Webface600k model is mentioned twice in model zoo readme, with different reported accuracy.

First is the `w600k_r50` model from `buffalo_l` and `buffalo_m` [packages](https://github.com/deepinsight/insightface/tree/master/model_zoo#recognition-accuracy-of-python-library-model-packs) with reported MR-All accuracy 91.25 and IJB-C(E4) accuracy 97.25, which seems to be higher than accuracy reported for Glint360K r100 model.

Second is `WebFace600K` model from IResNet-50 [block](https://github.com/deepinsight/insightface/tree/master/model_zoo#list-of-models-by-iresnet-50-and-different-training-datasets) with reported MR-All accuracy 90.566 and IJB-C(E4) accuracy 97.120.

I have checked outputs of both models, they are different for same face, so models seems to be different indeed, but is it true that r50 model is more accurate than you previous best r100 model?

**Comment by nttstar** [comment]
The model in `buffalo_l` is from a different learning rate policy which obtains a better accuracy.
Yes webface600k has a better performance than glint360k in our MFR testing.

**Comment by SthPhoenix** [comment]
Thanks, that's great news!
