### ISSUE TITLE
Error in python example

### ISSUE THREAD

**Issue by shekarneo** [deepinsight/insightface#1822]
```
import cv2
import numpy as np
import insightface
from insightface.app import FaceAnalysis
from insightface.data import get_image as ins_get_image

app = FaceAnalysis()
app.prepare(ctx_id=0, det_size=(640, 640))
img = ins_get_image('t1')
faces = app.get(img)
rimg = app.draw_on(img, faces)
cv2.imwrite("./t1_output.jpg", rimg)
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-91a2923a61d1> in <module>
      3 import insightface
      4 from insightface.app import FaceAnalysis
----> 5 from insightface.data import get_image as ins_get_image
      6 
      7 app = FaceAnalysis()

ModuleNotFoundError: No module named 'insightface.data'

**Comment by shekarneo** [comment]
!pip install -U insightface --force-reinstall fixed the issue

**Comment by samreen98** [comment]
> !pip install -U insightface --force-reinstall fixed the issue

It didn't solve the issue.

**Comment by YuzheMao** [comment]
I have the same problem too

**Comment by nttstar** [comment]
@samreen98 @YuzheMao  OS and insightface version?

**Comment by YuzheMao** [comment]
> @samreen98 @YuzheMao OS and insightface version?
Thank you. I've solved it after reinstalling Cython.

**Comment by samreen98** [comment]
Yes, issue was coming due to older version. Cython installation enabled latest version download. So issue solved.

**Comment by nttstar** [comment]
so I have to put Cython into the prerequisites
