### ISSUE TITLE
add center loss problem

### ISSUE THREAD

**Issue by IrvingShu** [deepinsight/insightface#183]
1. add losstype=8 //centerloss.
problem: 
mxnet.base.MXNetError: [13:38:41] src/io/image_io.cc:186: Check failed: inputs[00
].ctx().dev_mask() == Context::kCPU (2 vs. 1) Only supports cpu input

**Comment by GuitarZhang** [comment]
I also have this problem.

**Comment by IrvingShu** [comment]
1.3.0 mxnet version fixed it

**Comment by GuitarZhang** [comment]
I use pip install mxnet-cu80, how to change to 1.3.0, when I upgrade, another error "RuntimeError: simple_bind error" happened.
