### ISSUE TITLE
Facescrub Bounding Boxes Error Correction

### ISSUE THREAD

**Issue by MartinXM** [deepinsight/insightface#184]
When I used the align_facescrub.py to handle the original Facescrub, I found some of the cropped images are badly cropped, the faces are not at center and even no face in image at all. I checked the code and found that the problem is that some bounding boxes provided by Facescrub in facescrub_actors.txt and facescrub_actresses.txt are wrong. The align_facescrub.py uses that bounding boxes information to calculate IOU. As wrong bounding boxes have low IOU with faces detected by MTCNN, the face detection fails. I fixed wrong bounding boxes in facescrub_actors.txt and facescrub_actresses.txt , and here is the correction I made: 

Not center, bad crop:

Image                           |    original bounding boxes |     corrected bounding boxes
actresses:
Erin_Cummings_17432        (278,131,427,280)                    (175,60,325,250)
Erin_Cummings_17279        (208,162,429,383)                   (150,50,340,325)
Morena_Baccarin_3599      (50,477,831,1258)                    (75,50,575,700)
Andrea_Bowen_9073          (105,89,237,221)                       (160,40,260,160)
Brianna_Brown_10442        (105,38,237,170)                       (50,30,270,300) 
actors:
Mark_Wahlberg_40368      (103,87,229,213)                        (125,40,325,350)
Robert_Duvall_49660        (177,181,562,566)                       (70,35,325,410)

No face:
actresses:
Fran_Drescher_22942      (434,169,544,279)                      (365,125,445,240)
Joanna_Kerns_40134        (183,102,290,209)                      (350,125,540,400)
actors:
Shia_LaBeouf_53180        (351,118,665,432)                        (210,10,400,250)
Robert_Duvall_49687        (283,94,435,246)                       (200,30, 310,200)

By doing this, you do not have to change the code in align_facescrub.py in order to detect the missing faces, so that ensures you are using same codes to deal with megaface distraction images.

#167 mentioned failed to replicate the results in megaface, using the align_facescrub.py

#144 also mentioned the differences between images in aurthor's facescrub_images_112x112.tar, and images generated by the align_facescrub.py

This may help you get all the faces. But I still find that, after this correction, the faces generated by align_facescrub.py are not exactly the same as images in facescrub_images_112x112.tar . The face images in facescrub_images_112x112.tar cropped a smaller region centered in face, so after resize, the face looks bigger. Is there any extra preprocessing you did to generate face images provided in facescrub_images_112x112.tar ?

**Comment by nttstar** [comment]
This is a very important point which we have not realized before. We will do some research on it. Thank you!

**Comment by HaoLiuHust** [comment]
any progress?

**Comment by nttstar** [comment]
Hi, at that time we used the aligned facescrub images which produced by Matlab code with the same face detector(MTCNN) and transformed landmark coordinates. But it may have subtle differences on the part of similarity transformation comparing with our python code. As a result, this may affect the Megaface accuracy by around 1%. We will make changes accordingly in our paper later.
