### ISSUE TITLE
Model recommendation with decent accuracy and speed tradeoff for face detection

### ISSUE THREAD

**Issue by dreamflasher** [deepinsight/insightface#1842]
This is not a bug report nor feature request, at best it can be seen as a documentation request.

Which model available for the python package gives currently the best accuracy for face detection? (It seems to be RetinaFace-R50 right?)
If we allow to be 5% below the best accuracy, which model has the highest prediction speed? (ie. could you add infer (ms) to the RetinaFace table? It looks like SCRFD_10G gives a good tradeoff?)

I am looking at: https://github.com/deepinsight/insightface/tree/master/model_zoo#2-face-detection-models and to me it's not clear which models use PyTorch.

**Comment by nttstar** [comment]
You can check the arxiv paper.
