### ISSUE TITLE
buffalo_l seems to load RetinaFace not SCRFD?

### ISSUE THREAD

**Issue by dreamflasher** [deepinsight/insightface#1845]
```
from insightface.app import FaceAnalysis
import insightface
app = FaceAnalysis(allowed_modules=["detection"])
detector = insightface.model_zoo.get_model('buffalo_l/det_10g.onnx', download=True)
print(detector.__class__)
```
> insightface.model_zoo.retinaface.RetinaFace

**Comment by nttstar** [comment]
Right now they're the same.

**Comment by dreamflasher** [comment]
But you claim faster speed with scrfd, how do we actually get that model? Or are they interface compatible?

**Comment by nttstar** [comment]
They're actually scrfd models, but can be called with both `retinaface` and `scrfd` names.

**Comment by dreamflasher** [comment]
Does that mean we can use them with mmdet without needing the code changes of your forked mmdet?

**Comment by nttstar** [comment]
if you only need to do inference, mmdet is not required.
