### ISSUE TITLE
can't run pretrained models with verification.py

### ISSUE THREAD

**Issue by ariel415el** [deepinsight/insightface#185]
HI i'm trying to use the pretrained  MXnet models on the ms1m datasset , both available on site, but without sucess.
the pretrained model i downloaded,"model-r50-am-lfw", had only two files in it, "model-0000.params" and "model-symbol.json" but the verification.py script seem to not work when i feed it with the following command:  
`python -u verification.py --gpu 0 --data-dir '<INSIGHTFACE_ROOT>/datasets/faces_ms1m_112x112'  -- <INSIGHTFACE_ROOT>/datasets/model-r50-am-lfw'   --target agedb_30 --batch-size 128
`
im getting 

> image_size [112, 112]
model number 0
model loading time 2.1e-05
loading..  lfw
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
Traceback (most recent call last):
  File "verification.py", line 580, in <module>
    print('Max of [%s] is %1.5f' % (ver_name_list[i], np.max(results)))
  File "/home/ariel-e/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2272, in amax
    out=out, **kwargs)
  File "/home/ariel-e/.local/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no 

> 

I't seems like the script itself is not good and expecting to get other files in the model prameter then the model dir.

Did you overcheck this script is working with the supllied pretrained model and datsets?

I'm using:
Cuda: 7.5
cudnn: 5.1
GPU: GeForce GTX 1070
System: Ubuntu
![36717978-d0c3c1e2-1ba8-11e8-90c6-7b0b2bb214f7](https://user-images.githubusercontent.com/32613612/39093507-6049760e-4629-11e8-934a-4cd6a07943df.PNG)

Thanks,
Ariel

**Comment by nttstar** [comment]
Set `model-r50-am-lfw,0` to load epoch-num==0

**Comment by ariel415el** [comment]
Great, thanks.
I also needed to specify the prefix name of the files i.e "model"

**Comment by xisi789** [comment]
I had another problem:
Traceback (most recent call last):
  File "E:/0-project/1-facerecognition/1-code/2-insightface-master/insightface-master/gluon/verification.py", line 358, in <module>
    acc1, std1, acc2, std2, xnorm, embeddings_list = test(ver_list[i], model, ctx, args.batch_size, args.nfolds)
  File "E:/0-project/1-facerecognition/1-code/2-insightface-master/insightface-master/gluon/verification.py", line 227, in test
    z = net.feature(x)
AttributeError: 'Module' object has no attribute 'feature'
testing verification..
