### ISSUE TITLE
Using own model

### ISSUE THREAD

**Issue by wngTn** [deepinsight/insightface#1850]
Hello, I am kinda a noob, so I'm sorry for asking such a forward question. But how can I use my own model to detect faces on a picture?

I have this code snippet:

```python
import cv2
import numpy as np
import insightface
from insightface.app import FaceAnalysis
from insightface.data import get_image as ins_get_image

detector = insightface.model_zoo.get_model('retinaface_r50_v1.onnx')
detector.prepare(ctx_id=0, det_size=(640, 640))
```

But I don't know how to go on. Can somebody help me please?

**Comment by hmh10098** [comment]
you go to ../insightface/model_zoo/retinaface.py, in line 207 you should see detect function detail. With the above question, you can call detector.detect(your_image)

**Comment by gg22mm** [comment]
1、
python torch2onnx.py ./glint360k_cosface_r100_fp16_0.1/backbone.pth --network r100 --output inswapper_128_glint360k_r100.onnx
2、
import cv2
import insightface
from insightface.app import FaceAnalysis 
if __name__ == '__main__':    
    
    face_analyer = FaceAnalysis(name='buffalo_l', providers=['CPUExecutionProvider'])
    face_analyer.prepare(ctx_id=0, det_size=(640, 640))    
    
    face_swapper = insightface.model_zoo.get_model('./models/inswapper_128_glint360k_r100.onnx', download=False, download_zip=False)
    
    source_img = cv2.imread("1.jpg") 
    source_faces = face_analyer.get(source_img)
    source_faces = sorted(source_faces, key = lambda x : x.bbox[0])
    
    assert len(source_faces)==1
    source_face = source_faces[0]     

    target_img = cv2.imread("obj.jpg")
   
    target_faces = face_analyer.get(target_img) 
    target_faces = sorted(target_faces, key=lambda x: x.bbox[0])     
   
    for target_face in target_faces:        
        target_img = face_swapper.get(target_img, target_face, source_face, paste_back=True) 
     
    cv2.imwrite('11.jpg', target_img )

3、error
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    target_img = face_swapper.get(target_img, target_face, source_face, paste_back=True) #替换
TypeError: get() got an unexpected keyword argument 'paste_back'

**Comment by arad2022** [comment]
Hi, how I can use other pre-trained model for face recognition?
Can you help me?

handler = insightface.model_zoo.get_model("cisia_r50.onnx", providers=['CUDAExecutionProvider'])


handler.prepare(ctx_id=0)

embedding = handler.get(img1)
print(embedding)

I got this error     embedding = handler.get(img1)
TypeError: get() missing 1 required positional argument: 'face'

But if I pass the face I get another error. 
I just want to extract embedding from face.
