### ISSUE TITLE
数据集文件夹名称MS1M_v3

### ISSUE THREAD

**Issue by wang-kangkang** [deepinsight/insightface#1860]
在insightface/recognition/arcface_paddle/README_cn.md里面
解析数据的时候是：python tools/mx_recordio_2_images.py --root_dir ms1m-retinaface-t1/ --output_dir MS1M_v3/
启动训练的时候配置的参数是    
     --dataset MS1M_v2 \
     --data_dir MS1M_v2/ \
这个是不是写错了？
而且这里训的是人脸识别 arcface，为什么解析数据贴到是retinaface

**Comment by nttstar** [comment]
ms1m-retinaface means the ms1m dataset cleaned by retinaface paper.

**Comment by GuoxiaWang** [comment]
@wang-kangkang
