### ISSUE TITLE
training with pytorch

### ISSUE THREAD

**Issue by nikky4D** [deepinsight/insightface#1864]
Is it possible to use this library for training retinanet and other models in pytorch? Are there copies of the mxnet model weights/code in pytorch?

**Comment by nttstar** [comment]
right now we can try [SCRFD](https://github.com/deepinsight/insightface/tree/master/detection/scrfd), written in pytorch

**Comment by nikky4D** [comment]
I've also seen that there is an arcface-pytorch available. Thanks I'll try these. Are there any plans to include more pytorch versions of the models in the future?

**Comment by nttstar** [comment]
@nikky4D Maybe soon

**Comment by nikky4D** [comment]
Thank you.
