### ISSUE TITLE
Question about the acc in log.

### ISSUE THREAD

**Issue by blessxu** [deepinsight/insightface#187]
My acc is always like this  "acc=0.144043", but the LFW Accuracy-Flip is already 0.99433+-0.00403, I don't change the code, is there anything wrong with my environment? Thanks!

**Comment by nttstar** [comment]
What are your network setting, training-data and batch-size respectively?

**Comment by blessxu** [comment]
I use       CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7' python -u train_softmax.py --network r100 --loss-type 4 --margin-m 0.5 --data-dir ../datasets/faces_ms1m_112x112  --prefix ../model-r100 --lr 0.1 --per-batch-size 64

**Comment by KangolHsu** [comment]
I get the same error

INFO:root:Epoch[1] Batch [4900] Speed: 184.91 samples/sec       acc=0.005469
INFO:root:Epoch[1] Batch [4920] Speed: 178.70 samples/sec       acc=0.004883
INFO:root:Epoch[1] Batch [4940] Speed: 196.43 samples/sec       acc=0.004102
INFO:root:Epoch[1] Batch [4960] Speed: 196.92 samples/sec       acc=0.005859
INFO:root:Epoch[1] Batch [4980] Speed: 196.72 samples/sec       acc=0.006250
INFO:root:Epoch[1] Batch [5000] Speed: 196.76 samples/sec       acc=0.008008
INFO:root:Epoch[1] Batch [5020] Speed: 170.13 samples/sec       acc=0.006055
INFO:root:Epoch[1] Batch [5040] Speed: 238.17 samples/sec       acc=0.004883
INFO:root:Epoch[1] Batch [5060] Speed: 232.29 samples/sec       acc=0.005273
INFO:root:Epoch[1] Batch [5080] Speed: 170.89 samples/sec       acc=0.004883
INFO:root:Epoch[1] Batch [5100] Speed: 226.59 samples/sec       acc=0.004297
INFO:root:Epoch[1] Batch [5120] Speed: 207.64 samples/sec       acc=0.004297
lr-batch-epoch: 0.1 5137 1
testing verification..
(12000, 512)
infer time 43.11326
[lfw][20000]XNorm: 23.841703
[lfw][20000]Accuracy-Flip: 0.93500+-0.01698
testing verification..
(14000, 512)
infer time 53.073712
[cfp_fp][20000]XNorm: 21.599537
[cfp_fp][20000]Accuracy-Flip: 0.67171+-0.01099
testing verification..
(12000, 512)
infer time 44.275807
[agedb_30][20000]XNorm: 22.780737
[agedb_30][20000]Accuracy-Flip: 0.76767+-0.02175
[20000]Accuracy-Highest: 0.76767

**Comment by shaoxiang** [comment]
@USTCSQQ @KangolHsu @blessxu The same problem, has anyone solved it?

**Comment by yxchng** [comment]
@blessxu @KangolHsu @USTCSQQ @shaoxiang Have you solved the problem? Is the code wrong?

**Comment by rocinant** [comment]
same problem here.

**Comment by ayush431** [comment]
[40]Accuracy-Highest:1.00000
getting this every time while runnig verifictaion ??
anyone can tell what's wrong here??
