### ISSUE TITLE
微软合成数据中的代码bug

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [deepinsight/insightface#1870]
![image](https://user-images.githubusercontent.com/30692249/147542350-b1ced342-4f21-4580-b425-609ad13b3ecd.png)
随机边缘遮挡这里存在bug，应该如下，否则大概率产生全黑的图像
![image](https://user-images.githubusercontent.com/30692249/147542421-442c02a9-97a1-4212-af3e-300eb21eb442.png)

**Comment by nttstar** [comment]
yes right, can you make a PR for this please?

**Comment by nttstar** [comment]
fixed
