### ISSUE TITLE
Pretrained mode for face alignment training on synthetic data

### ISSUE THREAD

**Issue by chuanli11** [deepinsight/insightface#1875]
Hi, I came across this
https://github.com/deepinsight/insightface/tree/master/alignment/synthetics

afaik it is the first open source implementation of a face alignment model train on that synthetic dataset. Thanks for sharing. 

Wonder if there is any plan to share the pre-trained model?

**Comment by nttstar** [comment]
OK I will prepare one soon

**Comment by ForrestPi** [comment]
> OK I will prepare one soon

How to solve the domain gap,  could you share some tips ?

**Comment by nttstar** [comment]
https://drive.google.com/file/d/1kNP7qEl3AYNbaHFUg_ZiyRB1CtfDWXR4/view?usp=sharing @chuanli11

**Comment by nttstar** [comment]
> > OK I will prepare one soon
> 
> How to solve the domain gap, could you share some tips ?

To myself there's nothing new, just train it with proper data augmentations.

**Comment by chuanli11** [comment]
> 

Thank you very much for getting it on line so quickly. Will test more but it seems to generate more robust landmarks for some of our most challenging tests. 

BTW, is this the script to reproduce the model (for 30 epochs?): https://github.com/deepinsight/insightface/blob/master/alignment/synthetics/trainer_synthetics.py
