### ISSUE TITLE
Exact license of pretrained models from python-package

### ISSUE THREAD

**Issue by magicaltoast** [deepinsight/insightface#1877]
[Here](https://github.com/deepinsight/insightface/tree/master/python-package) is clearly stated that pre-trained models weights are not under an MIT license.
So under what license they are published?
 
Would be it ok if I modify the models and publish them on Github attributing this repo for base weights?
```
The code of InsightFace Python Library is released under the MIT License. There is no limitation for both academic and commercial usage.

The pretrained models we provided with this library are available for non-commercial research purposes only, including both auto-downloading models and manual-downloading models.
```

**Comment by nttstar** [comment]
> Would be it ok if I modify the models and publish them on Github attributing this repo for base weights?
It's ok if you don't use it in a commercial way.
