### ISSUE TITLE
SCRFD: training on more than 1 class with different box scale and ratio

### ISSUE THREAD

**Issue by edwardnguyen1705** [deepinsight/insightface#1888]
Dear @nttstar ,
Thanks for sharing your excellent work.
I am interested in training `SCRFD` for multi-classes datasets, for example `{"person", "head", "face"}`.
I refer to your change from training face to person: https://github.com/deepinsight/insightface/blob/f1e4b1291a388b0721463bdb7ec50b50bc7bd684/detection/scrfd/configs/scrfd_crowdhuman/scrfd_crowdhuman_2.5g_bnkps.py#L144
and I set configs to my 3-class {"person", "head", "face"} detection dataset:

```
        scale_mode=2,
        anchor_generator=dict(
            type='AnchorGenerator',
            ratios=[1.0, 2.0],
            scales = [1,2,3],
            base_sizes = [8, 16, 32, 64, 128],
            strides=[8, 16, 32, 64, 128]),
```

and I observe that the `person AP` is very small. It is unusual. Normally, `person AP` is larger than that of face. 
![Screen Shot 2022-01-18 at 16 21 36](https://user-images.githubusercontent.com/7928673/149914101-01d32d2c-262b-4e6f-a048-d2e693c613a9.png)

Do you have any suggestion?
Thanks for your time.

**Comment by nttstar** [comment]
You can firstly check the not-detected objects from your test dataset.
The anchor setting may be too dense by using the anchor-free method. Right now what I can suggest is to use only one anchor for each feature map to see the final accuracy.

**Comment by edwardnguyen1705** [comment]
> You can firstly check the not-detected objects from your test dataset. The anchor setting may be too dense by using the anchor-free method. Right now what I can suggest is to use only one anchor for each feature map to see the final accuracy.
Thanks for your suggestions.  I will try with

```
        scale_mode=2,
        anchor_generator=dict(
            type='AnchorGenerator',
            ratios=[1.0, 2.0],
            scales = [3],
            base_sizes = [8, 16, 32, 64, 128],
            strides=[8, 16, 32, 64, 128]),
```

Or I will find best matched anchor set for my dataset.

**Comment by Doanhdz** [comment]
@edwardnguyen1705 I have a problem need to train with more than 1 class, can you show me the way you modify the model to train multi class ?

**Comment by edwardnguyen1705** [comment]
> @edwardnguyen1705 I have a problem need to train with more than 1 class, can you show me the way you modify the model to train multi class ?

Please check `scrfd` branch: https://github.com/edwardnguyen1705/insightface/tree/scrfd/detection/scrfd

**Comment by dFuong** [comment]
@edwardnguyen1705 chào bạn
label_personheadfacefacemask.txt mình có mail cho bạn đó ạ
