### ISSUE TITLE
Bug only CosFace is called

### ISSUE THREAD

**Issue by OrkhanHI** [deepinsight/insightface#1895]
In `train.py` loss is not being passed as an argument, so default CosFace loss is used even the config file shows different loss name.

Line 54 add **cfg.loss**
```
module_partial_fc = PartialFC(
        cfg.embedding_size, 
        cfg.num_classes, 
        cfg.sample_rate, 
        cfg.fp16,
        cfg.loss
    )
```

**Comment by anxiangsir** [comment]
Thank you,we will fixed it soon.

**Comment by anxiangsir** [comment]
fixed
