### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface.data'

### ISSUE THREAD

**Issue by Beartx** [deepinsight/insightface#1901]
i am trying to run the simple python-package, folder but am getting : ModuleNotFoundError: No module named 'insightface.data'
what might be the issue?

Package                Version
---------------------- -----------
albumentations         1.1.0
certifi                2021.5.30
chardet                3.0.4
charset-normalizer     2.0.11
colorama               0.4.4
cycler                 0.11.0
Cython                 0.29.27
decorator              4.4.2
easydict               1.9
flatbuffers            2.0
graphviz               0.8.4
idna                   2.6
imageio                2.14.1
insightface            0.2.1
joblib                 1.1.0
kiwisolver             1.3.1
matplotlib             3.3.4
mxnet                  1.7.0.post2
networkx               2.5.1
numpy                  1.16.6
onnx                   1.10.2
onnxruntime            1.10.0
opencv-python          4.5.5.62
opencv-python-headless 4.5.5.62
Pillow                 8.4.0
pip                    21.2.2
protobuf               3.19.4
pyparsing              3.0.7
python-dateutil        2.8.2
PyWavelets             1.1.1
PyYAML                 6.0
qudida                 0.0.4
requests               2.18.4
scikit-image           0.17.2
scikit-learn           0.24.2
scipy                  1.5.4
setuptools             58.0.4
six                    1.16.0
threadpoolctl          3.1.0
tifffile               2020.9.3
tqdm                   4.62.3
typing_extensions      4.0.1
urllib3                1.22
wheel                  0.37.1
wincertstore           0.2

**Comment by Beartx** [comment]
> please install the latest version: 0.6.2

when i specify the version it says  Could not find a version that satisfies the requirement 0.6.2 and if i didn't specify it will download by default 0.2.1 so i need to know what else i need to update, am using python 3.6 is that might be causing the issue?

**Comment by nttstar** [comment]
Maybe it's the problem of win10..  Can you try to build the library from source? You can go to the ``python-package`` directory and then type ``pip install -e .``

**Comment by Beartx** [comment]
> Maybe it's the problem of win10.. Can you try to build the library from source? You can go to the `python-package` directory and then type `pip install -e .`

the issue is resolve but , many other error showed up.

C:\Users\Anaconda3\envs\pythonProject\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:56: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  "Available providers: '{}'".format(name, ", ".join(available_provider_names)))
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Traceback (most recent call last):
  File "C:/Users/PycharmProjects/pythonProject/python-package/insightface/main.py", line 7, in <module>
    app = FaceAnalysis(providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
  File "C:\Users\PycharmProjects\pythonProject\python-package\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "C:\Users\PycharmProjects\pythonProject\python-package\insightface\model_zoo\model_zoo.py", line 83, in get_model
    model = router.get_model(providers=kwargs.get('providers'), provider_options=kwargs.get('provider_options'))
  File "C:\Users\jPycharmProjects\pythonProject\python-package\insightface\model_zoo\model_zoo.py", line 50, in get_model
    return Landmark(model_file=self.onnx_file, session=session)
  File "C:\Users\PycharmProjects\pythonProject\python-package\insightface\model_zoo\landmark.py", line 69, in __init__
    self.mean_lmk = get_object('meanshape_68.pkl')
NameError: name 'get_object' is not defined

**Comment by nttstar** [comment]
Have you updated to the latest commit? 
https://github.com/deepinsight/insightface/blob/master/python-package/insightface/model_zoo/landmark.py#L14

**Comment by Beartx** [comment]
> Have you updated to the latest commit? https://github.com/deepinsight/insightface/blob/master/python-package/insightface/model_zoo/landmark.py#L14
 i get Cannot find reference 'get_object' in '__init__.py' so i updated the data folder and added object folder but pycharm doesn't recognize pkl format  for meanshape_68.pkl and am stuck there

**Comment by nttstar** [comment]
Can you try the pure command-line environment?  Instead of using pycharm.

**Comment by Beartx** [comment]
> Can you try the pure command-line environment? Instead of using pycharm.

am getting a different error, may i know all the libraries versions you have used to get it work in addtion to the python version and IDE if you used any?

**Comment by Beartx** [comment]
i tired with colab am not having anymore issue with library, but am getting error with the code am running the quick example the one in python-package folder,however am confused do i need to run Call Detection Models and Call Recognition Models before the quick example or not? i believe the error am getting is somehow related to it:

/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:56: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  "Available providers: '{}'".format(name, ", ".join(available_provider_names)))
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
/content/insightface/python-package/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4

**Comment by Beartx** [comment]
so any idea what is causing the issue?

**Comment by nttstar** [comment]
``Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'``
which means your installed onnxruntime does not support GPU inference. Make sure that you install ``onnxruntime-gpu`` instead of ``onnxruntime``

**Comment by Beartx** [comment]
> `Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'` which means your installed onnxruntime does not support GPU inference. Make sure that you install `onnxruntime-gpu` instead of `onnxruntime`

i get another error, why it is complicated just to run simple code:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    app = FaceAnalysis(providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
  File "/content/insightface/python-package/insightface/app/face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "/content/insightface/python-package/insightface/model_zoo/model_zoo.py", line 83, in get_model
    model = router.get_model(providers=kwargs.get('providers'), provider_options=kwargs.get('provider_options'))
  File "/content/insightface/python-package/insightface/model_zoo/model_zoo.py", line 39, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/content/insightface/python-package/insightface/model_zoo/model_zoo.py", line 24, in __init__
    super().__init__(model_path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 379, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 100: no CUDA-capable device is detected ; GPU=192872448 ; hostname=0da7d16c8444 ; expr=cudaSetDevice(info_.device_id);

**Comment by Beartx** [comment]
> i tired with colab am not having anymore issue with library, but am getting error with the code. am running the quick example the one in python-package folder,however am confused do i need to run Call Detection Models and Call Recognition Models before the quick example or not? i believe the error am getting is somehow related to it:
> 
> /usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:56: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider' "Available providers: '{}'".format(name, ", ".join(available_provider_names))) Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5 set det-size: (640, 640) /content/insightface/python-package/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times `max(M, N)` where M and N are the input matrix dimensions. To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`. P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4

well basically this output mean it works, i thought it error because i was expecting an output of image,but it just create an image inside the folder

**Comment by joytsay** [comment]
@nttstar sorry, where do i get `meanshape_68.pkl` if i need pose

**Comment by nttstar** [comment]
@joytsay inside the latest python package
