### ISSUE TITLE
Face detection for insightFace

### ISSUE THREAD

**Issue by ariel415el** [deepinsight/insightface#192]
Hi,
I'm trying to use the pre-trained models on my own images and noticed that the face detection section is not implemented.
Since its necessary to forward the model on the cropped faces only i wonder what face detector should i use. Do you have any tips for what will be the best face detector to use?
I saw that the datasets on the site contain already cropped faces. what detector did you use to create them?

Thanks,
Ariel.

**Comment by nttstar** [comment]
MTCNN.
