### ISSUE TITLE
eval Glint360K

### ISSUE THREAD

**Issue by alicera** [deepinsight/insightface#1927]
How to use [Glint360K](https://github.com/deepinsight/insightface/tree/master/recognition/partial_fc#4-download) dataset to eval model ?
How can I follow the step to eval ?
https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch

**Comment by anxiangsir** [comment]
you can try [onnx_ijbc.py](https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/onnx_ijbc.py), [mfr_ongoing](https://github.com/deepinsight/insightface/tree/master/challenges/mfr).
