### ISSUE TITLE
train verification on my own dataset

### ISSUE THREAD

**Issue by zhouxiwen0416** [deepinsight/insightface#193]
hi, thank you for your so nice project!
I want to train and verify on my own dataset, but your readme just show how to make train set by face2rec2.py, I want to verify on my own dataset instead of lfw.bin, can you tell us how to make verification set, which file?
thank you!

**Comment by nttstar** [comment]
check `src/data/**2pack.py`

**Comment by lmmcc** [comment]
hello,i want to know how to do train.rec using my own dataset,i read the face2rec.py,and i think the first step is create a lst file,and then make *.rec file.
when i do the lst file, there is no make_list function in your code.

**Comment by wtHuo** [comment]
I met the same problem,have you solved it yet? @lmmcc

**Comment by mengzhibin** [comment]
python glint2lst.py /data/glint_data celebrity > glint_cn.lst, the author has told the method to generate *.lst file. the web sit is :https://github.com/deepinsight/insightface/issues/256. @lmmcc @wtHuo

**Comment by Neelisha-saxena** [comment]
@mengzhibin I am unable to signup at   [http://trillionpairs.deepglint.com/data](http://trillionpairs.deepglint.com/data)

**Comment by YokkaBear** [comment]
> hello,i want to know how to do train.rec using my own dataset,i read the face2rec.py,and i think the first step is create a lst file,and then make *.rec file.
> when i do the lst file, there is no make_list function in your code.

I met the same problem but also can not find methods to construct an available .lst file. This really make me confused.
