### ISSUE TITLE
r200 backbone

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#1936]
Hi,

@nttstar @yingfeng 
Is there any r200 model or training example ? 

Best

**Comment by nttstar** [comment]
Right now there's no R200 pretrained weight

**Comment by anxiangsir** [comment]
This is the latest update

https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/configs/wf42m_pfc03_32gpu_r200.py
