### ISSUE TITLE
train loss type 2 with sphereface net error

### ISSUE THREAD

**Issue by philoxmyu** [deepinsight/insightface#194]
(1) when train loss type 2 with sphereface net,  there will be a shape error, as follows; but use other nets, it's ok. The error occurs in the sphereface_net.init_weights when infer_shape, but I can't figure it out 

> src/operator/nn/./../tensor/../elemwise_op_common.h:123: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node _minus0 at 1-th input: expected [128,85164], got [85164]

(2) I am new to mxnet from pytorch and  how to debug mxnet conveniently?

any help will be appreciate.

**Comment by nttstar** [comment]
Use newer version of MXNet.

**Comment by philoxmyu** [comment]
Indeed,  my mxnet version is already 1.1. Could you help verification it, I just want to figure it out because i use resnet not sphereface net for training. Thanks!
