### ISSUE TITLE
PBIDR error

### ISSUE THREAD

**Issue by ForrestPi** [deepinsight/insightface#1942]
In reconstruction/PBIDR  paert,
running "bash script/data_process.sh"  seems wrong.
creating images in data/image and data/mask folder.  all images are whilte

**Comment by nttstar** [comment]
@XingyuRenSJTU

**Comment by XingyuRenSJTU** [comment]
Hi, this bug may be caused by an incorrect version of Pytorch3D. We have tested our codes on Pytorch 1.7.1+cu101 and Pytorch3D 0.4.0 and it works well. 

Thanks for your question, we will test our codes on the newest Pytorch3D later.

**Comment by ForrestPi** [comment]
@XingyuRenSJTU   yeah  
My version   pytorch3d   0.5.0
![001_1](https://user-images.githubusercontent.com/12846142/159173147-ca42500b-5a7a-4d09-ae18-780e33cabb9a.png)
