### ISSUE TITLE
PBIDR reconstrution issue

### ISSUE THREAD

**Issue by ForrestPi** [deepinsight/insightface#1943]
I have used pytorch3d==0.4.0.
And I trained and tested using your data and scripts.
But the result seems not so good.
training result blew
Detailed_3dmm_400.obj  
<img width="454" alt="image" src="https://user-images.githubusercontent.com/12846142/159428765-54ae61fa-03d3-428e-ba09-1f6a5c9b42a7.png">

and eval result blew
eval_013.png
<img width="370" alt="image" src="https://user-images.githubusercontent.com/12846142/159429093-c76fcbf8-bdca-47bb-96ac-70178487a60a.png">

could you provide some tips for training?

**Comment by ForrestPi** [comment]
@XingyuRenSJTU

**Comment by XingyuRenSJTU** [comment]
Hi, it looks like your preprocessed data still has some bugs. You can send me the processed data, and I'll check them. (rxy_sjtu@sjtu.edu.cn)

Also, we'll put the processed data on Google Drive later to make it easier to reproduce.

**Comment by XingyuRenSJTU** [comment]
@ForrestPi We have updated the installation requirements, and it works when testing on the new machine. Please recheck your environment and let me you if any problems.

**Comment by ForrestPi** [comment]
In get_aux_dataset.py
img = Image.fromarray((target_images[i, ..., :3].cpu().numpy() * 255).astype(np.uint8))
img.save(os.path.join(IMAGE_DIR, 'image/{0}.png'.format('%03d' % int(i+1))))
img.save(os.path.join(IMAGE_DIR, 'mask/{0}.png'.format('%03d' % int(i+1))))

image folder mask folder  are the same
<img width="369" alt="image" src="https://user-images.githubusercontent.com/12846142/159693402-2abf4b73-8a3a-4cd5-92d0-1a8e171593f5.png">
@XingyuRenSJTU 
so   is the preprocessed data   correct？

**Comment by XingyuRenSJTU** [comment]
Correct! Please check if your trimesh package has pyembree. An incomplete trimesh package will lead to werid results.

**Comment by ForrestPi** [comment]
@XingyuRenSJTU  
yeah.  
needs to install the complete version trimesh package.  
Thanks
