### ISSUE TITLE
AttributeError: 'DistributedDataParallel' object has no attribute '_set_static_graph'

### ISSUE THREAD

**Issue by eeric** [deepinsight/insightface#1955]
backbone = torch.nn.parallel.DistributedDataParallel(
        module=backbone, broadcast_buffers=False, device_ids=[args.local_rank], bucket_cap_mb=16, 
        find_unused_parameters=True)

backbone._set_static_graph()

**Comment by eeric** [comment]
> backbone._set_static_graph()

torch==1.8.1

**Comment by anxiangsir** [comment]
```python
  if hasattr(backbone, "_set_static_graph"):
      # TODO ViT model must set torch version >= 1.9.0
      backbone._set_static_graph()
```

because of gradient checkpoint is conflict to `find_unused_parameters=True` in vit model of mask parameters.

**Comment by anxiangsir** [comment]
In order to enjoy the features of the new torch, we have upgraded the Torch version to 1.9.0.
Torch versions later than 1.9.0 May not work In the future.

**Comment by anxiangsir** [comment]
```python
assert torch.__version__ >= "1.9.0", "In order to enjoy the features of the new torch, \
we have upgraded the torch to 1.9.0. torch before than 1.9.0 may not work in the future."

```
