### ISSUE TITLE
About face2rec2.py

### ISSUE THREAD

**Issue by Drsea123** [deepinsight/insightface#197]
can you give me those codes about     # make_list(args) in the face2rec2.py,I want to reduce training samples，please！

**Comment by recordcode** [comment]
I wanna know where I can get the MS1M dataset the author cleaned. picture or the list, not bin file. Thank you! @Drsea123 @nttstar

**Comment by zhongyy** [comment]
@nttstar

**Comment by zhongyy** [comment]
Please provide make_list(args) in the face2rec2.py, thank you. @nttstar

**Comment by nttstar** [comment]
#80
