### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by quanh1990** [deepinsight/insightface#1992]
您好，我在训练glint360数据集的时候使用8卡V100 32G显存的一台服务器，batch_size设置为512的时候，第一张显卡显存会爆，提示RuntimeError: CUDA out of memory，但是剩余7张显卡都没有用满32G显存，请问下这个问题怎么解决呢？期待您的回复，十分感谢！

**Comment by anxiangsir** [comment]
检查一下预训练模型加载问题

**Comment by quanh1990** [comment]
> 
感谢大佬，我用的backbone是r50，然后pretrained是False 没有加载预训练模型，还有其他可以分析原因么？
iresnet50(False, **kwargs)

**Comment by quanh1990** [comment]
> 检查一下预训练模型加载问题

感谢大佬，我用的backbone是r50，然后pretrained是False 没有加载预训练模型，还有其他可以分析原因么？
iresnet50(False, **kwargs)

**Comment by quanh1990** [comment]
> 检查一下预训练模型加载问题
@anxiangsir 感谢大佬，确实是我加载了其他人脸检测和关键点的预训练模型导致的0号显卡过载，已经解决了
