### ISSUE TITLE
the inference time (17ms) is run CPU or GPU?

### ISSUE THREAD

**Issue by billtiger** [deepinsight/insightface#20]
first,it is really appreciate for sharing your codes!Now, i want to know the time consuming!
For single cropped face image(112x112), total inference time is only 17ms on my testing server(Intel E5-2660 @ 2.00GHz, Tesla M40, LResNet34E-IR).
the inference time (17ms) is run CPU or GPU?

**Comment by AKSHAYUBHAT** [comment]
GPU ```Tesla M40```
