### ISSUE TITLE
用webface42M数据集训练arcface模型，Lossvalue异常，测试集精度很低问题

### ISSUE THREAD

**Issue by sattychen** [deepinsight/insightface#2000]
您好，最近我用webface42m数据集从头训练arcface模型（用的是mxnet），训练时，lossvalue初始值很低（8点几），lfw、cfp-fp,agedb-30测试集下的精度都只有0.5左右，而且长时间不提升或者提升很慢
我曾经用faces_emore数据集做过对比（把faces_emore数据集解开再重新用自己的方法制作成rec），用来做训练是可以的。lossvalue正常（初始值是48左右）

请问webface42m数据集会引起这个问题吗？还是我制作的方法有问题（我用了2种方法，一种是用mx.tools.im2rec制作，一种是face2rec2.py制作），都有相同的问题？

非常感谢！

训练开始时的log如下：
lr_steps [320000, 640000, 960000]
[07:27:52] ../src/base.cc:80: cuDNN lib mismatch: linked-against version 8201 != compiled-against version 8100.  Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning.
/root/anaconda3/envs/mxnet_py39/lib/python3.9/site-packages/mxnet/module/base_module.py:503: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/b
atch_size/num_workers (0.25 vs. 0.00390625). Is this intended?
  self.init_optimizer(kvstore=kvstore, optimizer=optimizer,
[07:28:16] ../src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_
CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:Epoch[0] Batch [0-20]	Speed: 326.31 samples/sec	acc=0.000000	lossvalue=8.866494
INFO:root:Epoch[0] Batch [20-40]	Speed: 331.88 samples/sec	acc=0.000000	lossvalue=8.142130
INFO:root:Epoch[0] Batch [40-60]	Speed: 441.95 samples/sec	acc=0.000000	lossvalue=8.831406
INFO:root:Epoch[0] Batch [60-80]	Speed: 440.96 samples/sec	acc=0.000000	lossvalue=8.677649
INFO:root:Epoch[0] Batch [80-100]	Speed: 441.77 samples/sec	acc=0.000000	lossvalue=8.372708
INFO:root:Epoch[0] Batch [100-120]	Speed: 439.85 samples/sec	acc=0.000000	lossvalue=8.388589
INFO:root:Epoch[0] Batch [120-140]	Speed: 441.72 samples/sec	acc=0.000000	lossvalue=8.543470
INFO:root:Epoch[0] Batch [140-160]	Speed: 441.22 samples/sec	acc=0.000000	lossvalue=8.334433
INFO:root:Epoch[0] Batch [160-180]	Speed: 439.92 samples/sec	acc=0.000000	lossvalue=8.642203
INFO:root:Epoch[0] Batch [180-200]	Speed: 441.18 samples/sec	acc=0.000000	lossvalue=8.228543
INFO:root:Epoch[0] Batch [200-220]	Speed: 437.92 samples/sec	acc=0.000000	lossvalue=8.557396
INFO:root:Epoch[0] Batch [220-240]	Speed: 320.54 samples/sec	acc=0.000000	lossvalue=8.379030
INFO:root:Epoch[0] Batch [240-260]	Speed: 437.61 samples/sec	acc=0.000000	lossvalue=8.042100
INFO:root:Epoch[0] Batch [260-280]	Speed: 438.39 samples/sec	acc=0.000000	lossvalue=8.470531
INFO:root:Epoch[0] Batch [280-300]	Speed: 439.90 samples/sec	acc=0.000000	lossvalue=8.324872

**Comment by anxiangsir** [comment]
建议使用arcface_torch训练WF42M，以后的维护都会以arcface_torch为主，arcface_torch也放出了很多个训练WF42M的配置。

**Comment by sattychen** [comment]
感谢！
再请问下，mxnet上出现的问题，以前有人碰到过吗？

**Comment by yuleung** [comment]
> 感谢！ 再请问下，mxnet上出现的问题，以前有人碰到过吗？

请问webface42M有多大呀？

**Comment by qinfendekaizhou** [comment]
> 您好，最近我用webface42m数据集从头训练arcface模型（用的是mxnet），训练时，lossvalue初始值很低（8点几），lfw、cfp-fp,agedb-30测试集下的精度都只有0.5左右，而且长时间不提升或者提升很慢 我曾经用faces_emore数据集做过对比（把faces_emore数据集解开再重新用自己的方法制作成rec），用来做训练是可以的。lossvalue正常（初始值是48左右）
> 
> 请问webface42m数据集会引起这个问题吗？还是我制作的方法有问题（我用了2种方法，一种是用mx.tools.im2rec制作，一种是face2rec2.py制作），都有相同的问题？
> 
> 非常感谢！
> 
> 训练开始时的log如下： lr_steps [320000, 640000, 960000] [07:27:52] ../src/base.cc:80: cuDNN lib mismatch: linked-against version 8201 != compiled-against version 8100. Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning. /root/anaconda3/envs/mxnet_py39/lib/python3.9/site-packages/mxnet/module/base_module.py:503: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/b atch_size/num_workers (0.25 vs. 0.00390625). Is this intended? self.init_optimizer(kvstore=kvstore, optimizer=optimizer, [07:28:16] ../src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_ CUDNN_AUTOTUNE_DEFAULT to 0 to disable) INFO:root:Epoch[0] Batch [0-20] Speed: 326.31 samples/sec acc=0.000000 lossvalue=8.866494 INFO:root:Epoch[0] Batch [20-40] Speed: 331.88 samples/sec acc=0.000000 lossvalue=8.142130 INFO:root:Epoch[0] Batch [40-60] Speed: 441.95 samples/sec acc=0.000000 lossvalue=8.831406 INFO:root:Epoch[0] Batch [60-80] Speed: 440.96 samples/sec acc=0.000000 lossvalue=8.677649 INFO:root:Epoch[0] Batch [80-100] Speed: 441.77 samples/sec acc=0.000000 lossvalue=8.372708 INFO:root:Epoch[0] Batch [100-120] Speed: 439.85 samples/sec acc=0.000000 lossvalue=8.388589 INFO:root:Epoch[0] Batch [120-140] Speed: 441.72 samples/sec acc=0.000000 lossvalue=8.543470 INFO:root:Epoch[0] Batch [140-160] Speed: 441.22 samples/sec acc=0.000000 lossvalue=8.334433 INFO:root:Epoch[0] Batch [160-180] Speed: 439.92 samples/sec acc=0.000000 lossvalue=8.642203 INFO:root:Epoch[0] Batch [180-200] Speed: 441.18 samples/sec acc=0.000000 lossvalue=8.228543 INFO:root:Epoch[0] Batch [200-220] Speed: 437.92 samples/sec acc=0.000000 lossvalue=8.557396 INFO:root:Epoch[0] Batch [220-240] Speed: 320.54 samples/sec acc=0.000000 lossvalue=8.379030 INFO:root:Epoch[0] Batch [240-260] Speed: 437.61 samples/sec acc=0.000000 lossvalue=8.042100 INFO:root:Epoch[0] Batch [260-280] Speed: 438.39 samples/sec acc=0.000000 lossvalue=8.470531 INFO:root:Epoch[0] Batch [280-300] Speed: 439.90 samples/sec acc=0.000000 lossvalue=8.324872

能分享一下数据集吗？万分感谢！

**Comment by yz666521** [comment]
> > 您好，最近我用webface42m数据集从头训练arcface模型（用的是mxnet），训练时，lossvalue初始值很低（8点几），lfw、cfp-fp，agedb-30测试集下的精度都只有0.5左右，而且长时间不提升或者提升很慢 我曾经用faces_emore数据集做过对比（把faces_emore数据集解开再重新用自己的方法制作成rec），用来做训练是可以的。lossvalue正常（初始值是48左右）
> > 请问webface42m数据集会引起这个问题吗？还是我制作的方法有问题（我用了2种方法，一种是用mx.tools.im2rec制作，一种是 face2rec2.py 制作），都有相同的问题？
> > 非常感谢！
> > 训练开始时的log如下： lr_steps [320000， 640000， 960000] [07：27：52] ../src/base.cc：80：cuDNN 库不匹配：针对版本 8201 链接 ！= 针对版本 8100 编译。设置 MXNET_CUDNN_LIB_CHECKING=0 可静音此警告。/root/anaconda3/envs/mxnet_py39/lib/python3.9/site-packages/mxnet/module/base_module.py：503：UserWarning：在模块外部手动创建的优化器，但rescale_grad未规范化为 1.0/b atch_size/num_workers（0.25 与 0.00390625）。这是故意的吗？self.init_optimizer（kvstore=kvstore， optimizer=optimizer， [07：28：16] ../src/operator/nn/./cudnn/./cudnn_algoreg-inl.h：97： 运行性能测试以找到最佳卷积算法，这可能需要一段时间......（将环境变量 MXNET_ CUDNN_AUTOTUNE_DEFAULT 设置为 0 以禁用）信息：根：纪元[0] 批处理 [0-20] 速度：326.31 个样本/秒 acc=0.000000 损失值=8.866494 信息：根：纪元[0] 批处理 [20-40] 速度：331.88 个样本/秒 acc=0.000000 损失值=8.142130 信息：根：纪元[0] 批处理 [40-60] 速度：441.95 个样本/秒 acc=0.000000 损失值=8.831406 信息：根：纪元[0] 批处理 [60-80] 速度：440.96 个样本/秒 acc=0.000000 损失值=8.677649 信息：根：纪元[0] 批次 [80-100] 速度：441.77 样本/秒 acc=0.000000 lossvalue=8.372708 信息：root：纪元[0] 批处理 [100-120] 速度：439.85 样本/秒 acc=0.000000 lossvalue=8.388589 信息：根：纪元[0] 批处理 [120-140] 速度：441.72 样本/秒 acc=0.000000 lossvalue=8.543470 信息：根：纪元[0] 批处理 [140-160] 速度：441.22 样本/秒 acc=0.000000 lossvalue=8.334433 信息：根：纪元[0] 批次 [160-180] 速度：439.92 个样本/秒 acc=0.000000 lossvalue=8.642203 信息：root：纪元[0] 批处理 [180-200] 速度：441.18 样本/秒 acc=0.000000 lossvalue=8.228543 信息：root：纪元[0] 批处理 [200-220] 速度：437.92 样本/秒 acc=0.000000 lossvalue=8.557396 信息：root：纪元[0] 批处理 [220-240] 速度：320.54 样本/秒 acc=0.000000 损失值=8.379030 信息：根：纪元[0] 批次 [240-260] 速度：437.61 个样本/秒 累积=0.000000 损失值=8.042100 信息：根：纪元[0] 批处理 [260-280] 速度：438.39 样本/秒 累积=0.000000 损失值=8.470531 信息：根：纪元[0] 批处理 [280-300] 速度：439.90 样本/秒 累积=0.000000 损失值=8.324872
> 
> 能分享一下数据集吗？万分感谢！

可以分享一下数据集吗？百度网盘链接

**Comment by 22wei22** [comment]
> 您好，最近我用webface42m数据集从头训练arcface模型（用的是mxnet），训练时，lossvalue初始值很低（8点几），lfw、cfp-fp,agedb-30测试集下的精度都只有0.5左右，而且长时间不提升或者提升很慢 我曾经用faces_emore数据集做过对比（把faces_emore数据集解开再重新用自己的方法制作成rec），用来做训练是可以的。lossvalue正常（初始值是48左右）
> 
> 请问webface42m数据集会引起这个问题吗？还是我制作的方法有问题（我用了2种方法，一种是用mx.tools.im2rec制作，一种是face2rec2.py制作），都有相同的问题？
> 
> 非常感谢！
> 
> 训练开始时的log如下： lr_steps [320000, 640000, 960000] [07:27:52] ../src/base.cc:80: cuDNN lib mismatch: linked-against version 8201 != compiled-against version 8100. Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning. /root/anaconda3/envs/mxnet_py39/lib/python3.9/site-packages/mxnet/module/base_module.py:503: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/b atch_size/num_workers (0.25 vs. 0.00390625). Is this intended? self.init_optimizer(kvstore=kvstore, optimizer=optimizer, [07:28:16] ../src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_ CUDNN_AUTOTUNE_DEFAULT to 0 to disable) INFO:root:Epoch[0] Batch [0-20] Speed: 326.31 samples/sec acc=0.000000 lossvalue=8.866494 INFO:root:Epoch[0] Batch [20-40] Speed: 331.88 samples/sec acc=0.000000 lossvalue=8.142130 INFO:root:Epoch[0] Batch [40-60] Speed: 441.95 samples/sec acc=0.000000 lossvalue=8.831406 INFO:root:Epoch[0] Batch [60-80] Speed: 440.96 samples/sec acc=0.000000 lossvalue=8.677649 INFO:root:Epoch[0] Batch [80-100] Speed: 441.77 samples/sec acc=0.000000 lossvalue=8.372708 INFO:root:Epoch[0] Batch [100-120] Speed: 439.85 samples/sec acc=0.000000 lossvalue=8.388589 INFO:root:Epoch[0] Batch [120-140] Speed: 441.72 samples/sec acc=0.000000 lossvalue=8.543470 INFO:root:Epoch[0] Batch [140-160] Speed: 441.22 samples/sec acc=0.000000 lossvalue=8.334433 INFO:root:Epoch[0] Batch [160-180] Speed: 439.92 samples/sec acc=0.000000 lossvalue=8.642203 INFO:root:Epoch[0] Batch [180-200] Speed: 441.18 samples/sec acc=0.000000 lossvalue=8.228543 INFO:root:Epoch[0] Batch [200-220] Speed: 437.92 samples/sec acc=0.000000 lossvalue=8.557396 INFO:root:Epoch[0] Batch [220-240] Speed: 320.54 samples/sec acc=0.000000 lossvalue=8.379030 INFO:root:Epoch[0] Batch [240-260] Speed: 437.61 samples/sec acc=0.000000 lossvalue=8.042100 INFO:root:Epoch[0] Batch [260-280] Speed: 438.39 samples/sec acc=0.000000 lossvalue=8.470531 INFO:root:Epoch[0] Batch [280-300] Speed: 439.90 samples/sec acc=0.000000 lossvalue=8.324872

可以分享下数据集百度网盘链接么

**Comment by 22wei22** [comment]
> > > 您好，最近我用webface42m数据集从头训练arcface模型（用的是mxnet），训练时，lossvalue初始值很低（8点几），lfw、cfp-fp，agedb-30测试集下的精度都只有0.5左右，而且长时间不提升或者提升很慢 我曾经用faces_emore数据集做过对比（把faces_emore数据集解开再重新用自己的方法制作成rec），用来做训练是可以的。lossvalue正常（初始值是48左右）
> > > 请问webface42m数据集会引起这个问题吗？还是我制作的方法有问题（我用了2种方法，一种是用mx.tools.im2rec制作，一种是 face2rec2.py 制作），都有相同的问题？
> > > 非常感谢！
> > > 训练开始时的log如下： lr_steps [320000， 640000， 960000] [07：27：52] ../src/base.cc：80：cuDNN 库不匹配：针对版本 8201 链接 ！= 针对版本 8100 编译。设置 MXNET_CUDNN_LIB_CHECKING=0 可静音此警告。/root/anaconda3/envs/mxnet_py39/lib/python3.9/site-packages/mxnet/module/base_module.py：503：UserWarning：在模块外部手动创建的优化器，但rescale_grad未规范化为 1.0/b atch_size/num_workers（0.25 与 0.00390625）。这是故意的吗？self.init_optimizer（kvstore=kvstore， optimizer=optimizer， [07：28：16] ../src/operator/nn/./cudnn/./cudnn_algoreg-inl.h：97： 运行性能测试以找到最佳卷积算法，这可能需要一段时间......（将环境变量 MXNET_ CUDNN_AUTOTUNE_DEFAULT 设置为 0 以禁用）信息：根：纪元[0] 批处理 [0-20] 速度：326.31 个样本/秒 acc=0.000000 损失值=8.866494 信息：根：纪元[0] 批处理 [20-40] 速度：331.88 个样本/秒 acc=0.000000 损失值=8.142130 信息：根：纪元[0] 批处理 [40-60] 速度：441.95 个样本/秒 acc=0.000000 损失值=8.831406 信息：根：纪元[0] 批处理 [60-80] 速度：440.96 个样本/秒 acc=0.000000 损失值=8.677649 信息：根：纪元[0] 批次 [80-100] 速度：441.77 样本/秒 acc=0.000000 lossvalue=8.372708 信息：root：纪元[0] 批处理 [100-120] 速度：439.85 样本/秒 acc=0.000000 lossvalue=8.388589 信息：根：纪元[0] 批处理 [120-140] 速度：441.72 样本/秒 acc=0.000000 lossvalue=8.543470 信息：根：纪元[0] 批处理 [140-160] 速度：441.22 样本/秒 acc=0.000000 lossvalue=8.334433 信息：根：纪元[0] 批次 [160-180] 速度：439.92 个样本/秒 acc=0.000000 lossvalue=8.642203 信息：root：纪元[0] 批处理 [180-200] 速度：441.18 样本/秒 acc=0.000000 lossvalue=8.228543 信息：root：纪元[0] 批处理 [200-220] 速度：437.92 样本/秒 acc=0.000000 lossvalue=8.557396 信息：root：纪元[0] 批处理 [220-240] 速度：320.54 样本/秒 acc=0.000000 损失值=8.379030 信息：根：纪元[0] 批次 [240-260] 速度：437.61 个样本/秒 累积=0.000000 损失值=8.042100 信息：根：纪元[0] 批处理 [260-280] 速度：438.39 样本/秒 累积=0.000000 损失值=8.470531 信息：根：纪元[0] 批处理 [280-300] 速度：439.90 样本/秒 累积=0.000000 损失值=8.324872
> > 
> > 
> > 能分享一下数据集吗？万分感谢！
> 
> 可以分享一下数据集吗？百度网盘链接

请问有数据集了么？方便分享下么

**Comment by zxs23130** [comment]
可以分享一下数据集吗，谢谢

**Comment by qinfendekaizhou** [comment]
我找找，找到回复你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年4月22日(周二) 中午11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [deepinsight/insightface] 用webface42M数据集训练arcface模型，Lossvalue异常，测试集精度很低问题 (Issue #2000)


   
可以分享一下数据集吗，谢谢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  zxs23130 left a comment (deepinsight/insightface#2000)
 
可以分享一下数据集吗，谢谢

**Comment by xiaohan147** [comment]
> 我找找，找到回复你
> […](#)

可以分享一下链接/数据集吗

**Comment by cicijohn1983** [comment]
可以分享一下数据集吗

**Comment by ll8657** [comment]
求数据集！

**Comment by fanyongkang87** [comment]
求数据集

**Comment by prozyy** [comment]
求分享数据集

**Comment by xiaohan147** [comment]
用高校邮箱向作者请求，回复很快

**Comment by prozyy** [comment]
> 用高校邮箱向作者请求，回复很快

已收到数据集，方便加你个联系方式么，方便交流人脸识别算法，我邮箱 mail163_zyy@163.com

**Comment by xiaohan147** [comment]
> > 用高校邮箱向作者请求，回复很快
> 
> 已收到数据集，方便加你个联系方式么，方便交流人脸识别算法，我邮箱 [mail163_zyy@163.com](mailto:mail163_zyy@163.com)

数据量太大了，训练起来也麻烦，光是下载、转成lmdb就要几天，训练起来耗时更长，不建议用，一般来说，Glint360K就够了，在网上找人家转好的Glint360K.lmdb

**Comment by shicaiwei123** [comment]
> 用高校邮箱向作者请求，回复很快

您好，是向哪一个作者邮箱请求呢？ 我发给这个 zhengzhu@tsinghua.edu.cn，给我返回收件方服务器反馈收件人地址不存在的信息给我们服务器呢？

**Comment by xiaohan147** [comment]
谷歌学术上有朱老师ieee的邮箱
