### ISSUE TITLE
Multi-Process Running Issue on GPU

### ISSUE THREAD

**Issue by pouryajafarzadeh** [deepinsight/insightface#2002]
I have run the bufallo_l model on the GPU successfully, but when I run the code multi-processing in python for getting the embedding vector I receive an exception:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : CUDA error executing cudaSetDevice(GetDeviceId())
2022-05-10 13:14:52.595859223 [E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDA failure 3: initialization error ; GPU=0 ; hostname=ttai03 ; expr=cudaSetDevice(GetDeviceId()); 
```
Can we run multi-process (parallel) program on the insightface package with GPU?

**Comment by pouryajafarzadeh** [comment]
No, I couldn't solve the problem, I just run on the GPU with a single process.

**Comment by Oswells** [comment]
OK. Thank you!
