### ISSUE TITLE
wf42m 数据集的图片数量问题

### ISSUE THREAD

**Issue by sattychen** [deepinsight/insightface#2005]
您好，我看到arcface_torch提供的wf42m_pfc02_r100.py里，图片数量是
config.num_image = 42474557

但是我自己生成的train.lst里，却有42474558条记录，和上面的差1张图片（图片是我直接解压缩出来的，没有动过）

请问下，为啥官方的数量会少一张呢？是有啥说法吗？

**Comment by anxiangsir** [comment]
有一张打rec的时候打不进去

**Comment by sattychen** [comment]
是图片后缀是jpeg？
我昨天开启dali后跑到了70000多块，然后dali报错了，会不会是这个图片引起的？

我用的是arcface_torch里的那个打包命令（im2rec）打的，这个会把jpeg打包进去不？pass_through好像默认是true的

**Comment by anxiangsir** [comment]
--pass-through 默认为false
pass-through意思为不对图片进行解码，直接向rec写入文件，你检查一下是否开启了pass-through
有张图片jpg错了，打不进去，可能是这个原因

**Comment by sattychen** [comment]
默认是true，我看了im2rec源代码
argroup.add_argument('--pass-through', action='store_true',

**Comment by sattychen** [comment]
我执行时没有设置，应该是false

**Comment by sattychen** [comment]
重新制作数据集后，问题解决

**Comment by guyanxiao** [comment]
能否给下打包的命令？pass throuth为false的，打包处理还是多一张，没有报错。
