### ISSUE TITLE
PBIDR evaluate

### ISSUE THREAD

**Issue by Yangleyang** [deepinsight/insightface#2011]
Thank you for your excellent work！
Can you share your test code on the micc florence dataset?

**Comment by XingyuRenSJTU** [comment]
Hi, Hi, we have followed the test code from GANFIT [https://github.com/barisgecer/GANFit](https://github.com/barisgecer/GANFit). Please check it.

**Comment by sunsunshark** [comment]
@Yangleyang  Hi ,it is difficult for me to obtain the permission to download the data set on the official website. Could you please share this MICC Florence data set? If it is convenient for you, my email address is: 1969380827@qq.com,or  you can show me a web link to download the dataset.Thank you.
