### ISSUE TITLE
# TODO the params of partial fc must be last in the params list 什么意思啊

### ISSUE THREAD

**Issue by qiu-pinggaizi** [deepinsight/insightface#2029]
![image](https://user-images.githubusercontent.com/52409244/173769699-7437b416-d88a-4e39-920a-d8fb8b6dd340.png)
arcface_torch的train.py里初始化partial fc的时候，partial fc必须放在opt的最后吗？为什么会有这样的处理

**Comment by anxiangsir** [comment]
这是后续的一个feature，目前暂未push上来，目的是让优化器知道优化器组中第二组的参数是pfc的参数，支队

**Comment by qiu-pinggaizi** [comment]
我使用一个backbone，两个partial fc，分别用来处理两个单独的数据集，在opt里面叠加partial fc的参数就可以吧，这样对两个partial fc的参数更新会有问题吗
![1655291182122](https://user-images.githubusercontent.com/52409244/173812895-b0c584dc-594b-4120-bc20-6ddd90d20b99.png)

**Comment by anxiangsir** [comment]
有问题，这块需要更改一下

**Comment by qiu-pinggaizi** [comment]
修改成这样呗？
if isinstance(optimizer, torch.optim.SGD):
            # TODO the params of partial fc must be last in the params list
            optimizer.state.pop(optimizer.param_groups[-1]["params"][0], None)
            optimizer.param_groups[-1]["params"][0] = self.weight_activated
            optimizer.state.pop(optimizer.param_groups[-2]["params"][0], None)
            optimizer.param_groups[-2]["params"][0] = self.weight_activated
            optimizer.state[self.weight_activated][
                "momentum_buffer"
            ] = self.weight_activated_mom

**Comment by qiu-pinggaizi** [comment]
![image](https://user-images.githubusercontent.com/52409244/174023920-510efec2-f838-49f6-8ef4-a62b7fa313f7.png)
有个奇怪的现象，昨天更改完代码后，opt里-2位置对应数据集的loss更新很慢；同样俩数据集，更换数据集的opt初始化顺序进行测试，都是-2位置数据集loss降低超级慢。是我们上面这部分代码修改的有问题吗 @anxiangsir

**Comment by qiu-pinggaizi** [comment]
没问题了。感谢

**Comment by epns** [comment]
partial_fc_v2是不是不需要保证位于最后了

**Comment by anxiangsir** [comment]
是的

**Comment by anxiangsir** [comment]
> partial_fc_v2是不是不需要保证位于最后了，好像没有传入优化器了 @anxiangsir

是的
