### ISSUE TITLE
Regarding licence of model file and dataset. 

### ISSUE THREAD

**Issue by selva18** [deepinsight/insightface#203]
hi,
I have gone through the repository and found that the license type used in this repository is "MIT".
1.Is the model file also covered under MIT license?
2.With your knowledge, any idea about the licensing of datasets you used?

**Comment by selva18** [comment]
@nttstar Can you pls answer for the above question.

**Comment by Akshai** [comment]
@nttstar Can you please let us know the license of the pretrained models?
