### ISSUE TITLE
PBIDR where can I find the video?

### ISSUE THREAD

**Issue by Chromer163** [deepinsight/insightface#2068]
"we attach a video with high-resolution rotating rendered mesh
results, which showcases the quality and accuracy of the texture completion and
geometric details acquisitio"

thanks for your wonderful work!
BTW., where can I find the video?

**Comment by Chromer163** [comment]
@XingyuRenSJTU

**Comment by XingyuRenSJTU** [comment]
Sorry, our video is not publicly available yet, we will update this page later.
