### ISSUE TITLE
PBIDR how to generate raw data

### ISSUE THREAD

**Issue by Chromer163** [deepinsight/insightface#2074]
there are  image mask and cameras.npz and mesh in raw data ,
I just wonder how to generate these files?
@XingyuRenSJTU

**Comment by XingyuRenSJTU** [comment]
Hi, you can start by using OSTeC (https://github.com/deepinsight/insightface/tree/master/reconstruction/ostec) to generate texture meshes.

**Comment by waleedrazakhan92** [comment]
@Chromer163 were you able to use the OSTeC to produce raw data on your images and get them working with the PBIDR?
I've produced the obj and mtl files but unable to use them with insightface PBIDR. I get the error about "meshes doesnt have textures". Can you please tell if you were able to solve the problem.
