### ISSUE TITLE
What size is mobilefacenet?

### ISSUE THREAD

**Issue by jeehyun100** [deepinsight/insightface#209]
Hello. I have some questions about facemobilenet.
I have trained the mobilefacenet.
According to MobileFaceNet Paper, the mobilenet model size is only 4M. 
However, My mobilefacenet model size is about 172M.
Do you know why?? 

My train code is below.
CUDA_VISIBLE_DEVICES='0' python -u train_softmax.py --network y1 --loss-type 0 --data-dir ../datasets/faces_ms1m_112x112 --prefix ../model-y1-softmax

**Comment by ShiyangZhang** [comment]
#208 I've faced a similar problem

**Comment by AleximusOrloff** [comment]
Hi, I see in your paper, as we as in your repo, that 'E' model is used
https://github.com/deepinsight/insightface/blob/master/src/symbols/fmobilenet.py#L43
As I got, 'E' model means that we have fc layer from 7*7*1024 inputs to 512 outputs
It means at least 100M of data from this FC layer, so how can we achieve 4M?

**Comment by cuongpdkaopiz** [comment]
@AleximusOrloff Because they use kernel 1x1 which can reduce number of parameters
