### ISSUE TITLE
inference_simple.py list index out of range

### ISSUE THREAD

**Issue by divastar** [deepinsight/insightface#2096]
Hi , thank you for sharing your work
I am trying to run the inference
but getting this error
File "insightface\reconstruction\jmlr\inference_simple.py", line 75, in __init__
    backbone_pth = sorted(ckpts)[-1]
IndexError: list index out of range

**Comment by tungedng2710** [comment]
The default code doesn't have config.ckpt, you should manually add it to quick inference.
1. Download the pretrained model (backbone_ep9999.pth)
2. Add `config.ckpt = "backbone_ep9999.pth"` to the ` configs/base.py`

**Comment by divastar** [comment]
Amaizing Thank you!
