### ISSUE TITLE
about lfw2pack.py

### ISSUE THREAD

**Issue by billtiger** [deepinsight/insightface#210]
i have run the lfw2pack.py to generate my own eval datasets.but the accuracy is very low,so i make the lfw.bin again,named lfw112jpg.bin. and i find the accuracy is also two low when contrast your lfw.bin.
here is the accuracy.
testing verification..
(12000, 512)
infer time 11.238896
[lfw][4000]XNorm: 22.697246
[lfw][4000]Accuracy-Flip: 0.92200+-0.01503
testing verification..
(12000, 512)
infer time 11.237962
[lfw112jpg][4000]XNorm: 22.694899
[lfw112jpg][4000]Accuracy-Flip: 0.72300+-0.01709

i don't know how to solve this?can this have any data process i ignored？
@nttstar

**Comment by gogowarriors** [comment]
i have the same problem. have you solved it?

**Comment by billtiger** [comment]
@cici-tan 
hello,i don't know the 04_FINAL_protocol_30_years.mat file you said.
Can you give me more informations?thanks.

**Comment by cici-tan** [comment]
I am talking about this:
Traceback (most recent call last):
  File "agedb2pack.py", line 82, in <module>
    mat_data = loadmat(mat_file)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 135, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 58, in mat_reader_factory
    byte_stream = _open_file(file_name, appendmat)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 23, in _open_file
    return open(file_like, 'rb')
IOError: [Errno 2] No such file or directory: '/medical_data/Datasets/insightface/datasets/image_face/roger/04_FINAL_protocol_30_years.mat'

**Comment by billtiger** [comment]
I didn't use the "agedb2pack.py" to generate my own dataset,I just use the lfw2pack.py to generate lfw.bin.
I think you can recover the data from agedb_30.bin which the author provided. 
I am wondered that you said the lfw2pack.py does not work for you to generate data?
@cici-tan

**Comment by cici-tan** [comment]
oh sorry, thought I used lfw2pack.py last time.... @billtiger

**Comment by nttstar** [comment]
pairs.txt and 04_FINAL_protocol_30_years.mat are both used to indicate whether it is the same person for each image pair.

**Comment by cici-tan** [comment]
@nttstar thx! but how can I create pairs.txt for my own datasets?

**Comment by billtiger** [comment]
the "pairs.txt" you can download from the LFW website,this is a official file. or you can generate the pairs.txt from you dataset according the format. @cici-tan

**Comment by nttstar** [comment]
For N pairs verification dataset, what you actually need is (N*2 images+N boolean values). How to generate them depends on yourself.

**Comment by cici-tan** [comment]
@billtiger @nttstar thx for your helps!
but I checked official pairs.txt, like this:
10	300
Abel_Pacheco	1	4
Akhmed_Zakayev	1	3
Akhmed_Zakayev	2	3

not quite understand what those numbers represent.

**Comment by heshao90** [comment]
when I run the verification.py, I got this problem. FileNotFoundError: [Errno 2] No such file or directory:'../datasets/property'. So, how do you get the property file?

**Comment by jinfei3459** [comment]
@cici-tan 
where to download this pairs.txt, i don't know LFW websites@

**Comment by jinfei3459** [comment]
@cici-tan 
Did you fix the problem about .txt file?
Can you tell me?
Thanks

**Comment by jinfei3459** [comment]
@billtiger 
@nttstar
@yingfeng 
@yuzhichang 
I want to know where to get  like agedb_30.bin、 cfp_ff and cfp_fp.bin .txt file or get these data's website

**Comment by nttstar** [comment]
From our training data.

**Comment by clhne** [comment]
@cici-tan 
Have you got the mat file?
Thanks.

**Comment by khawar512** [comment]
Hi, @cici-tan  Are you testing on MORPH, FGNET, and CACD-VS datasets using the .bin file? I require some urgent help, please
