### ISSUE TITLE
Swapping Code

### ISSUE THREAD

**Issue by k128** [deepinsight/insightface#2115]
Can you add (or point me to) the code/model used for the face swapping demo?  I'd like to do inference tests vs existing models like Simswap and MegaFS.

**Comment by nttstar** [comment]
Right now we don't have a plan to release the model. Just have fun with the web demo.

**Comment by k128** [comment]
Ok, let me know if that changes.  Thanks for everything else you've contributed!

**Comment by taruntiwar** [comment]
Hey, I just want to know when you will release interference code for Face Swap, thanks

**Comment by nttstar** [comment]
https://github.com/deepinsight/insightface/tree/master/examples/in_swapper

**Comment by taruntiwar** [comment]
Thank you so much :)
