### ISSUE TITLE
JMLR code couldn't get the correct result

### ISSUE THREAD

**Issue by lcaikk1314** [deepinsight/insightface#2119]
Hello, when I used your JMLR code (without any modification) to train on the WCPA dataset, I couldn't get the correct result, especially when the face is sideways, the effect is shown below.  I have done a complete walkthrough of your code, but have found no problems. can you give me some suggestions？Or does the code have any special requirements for the environment? Thank you very much.
![draw](https://user-images.githubusercontent.com/21968304/192991391-4bb45030-ff7f-478c-a7b2-b41964e93b32.jpg)

**Comment by xiaoyang333** [comment]
WCPA数据集能不能分享一下，特别感谢，现在早已经结束比赛了

**Comment by nttstar** [comment]
需要向组织方申请，我们没有权利分享这个数据集
