### ISSUE TITLE
Prediction Time Issue!!!

### ISSUE THREAD

**Issue by mrhossain** [deepinsight/insightface#213]
I trained 50 layer network with loss type 4 and my prediction time almost 3-4 second per image but the pre trained model ("Refined-MS1M@BaiduDrive") only 1.5-2 second. I compared the model size network layer,  "json" file and layer name . All are same in both model. Please advice me, where is my mistake.

**Comment by MyraBaba** [comment]
which code you used for prediction ? can you share here to look ?
