### ISSUE TITLE
How to obtain landmarks from scrfd example

### ISSUE THREAD

**Issue by cyrusbehr** [deepinsight/insightface#2136]
Hi there, I'm looking over your scrfd example [here](https://github.com/deepinsight/insightface/blob/master/detection/scrfd/tools/scrfd.py).

First of all, great work. 

The example shows how to obtain the bounding boxes, however it does not demonstrate how to obtain the 5 face landmark points (eyes, nose, mouth corners).

Can you please walk me through how I would modify the example to obtain the face landmark coordinates?

**Comment by nttstar** [comment]
'kpss' means the keypoints.
