### ISSUE TITLE
partial_fc_v2 为什么不需要传入优化器了

### ISSUE THREAD

**Issue by Youngboy12** [deepinsight/insightface#2140]
我理解 partial_fc_v2里边参与计算的仍然是采样后的sub_weight，而不是原始的weight，那么优化器直接对weight不会有问题吗？

我仿写的代码报了 AttributeError: 'generator' object has no attribute 'grad'。

想请问下作者这是为什么？和pytorch的版本有关系吗？谢谢。

**Comment by anxiangsir** [comment]
这里提供了两个版本，各有利弊：

**Comment by Youngboy12** [comment]
那还是想问作者 partial_fc_v2里边参与计算的仍然是采样后的sub_weight，而不是原始的weight，那么优化器是如何对原始的weight做更新呢？

 我的报错 AttributeError: 'generator' object has no attribute 'grad' 还是没解决。

以及另外一个问题：我理解 梯度累计应该是 计算多个iters的平均loss然后计算一次梯度并更新。而作者的代码在做梯度累计时，是多次计算梯度后统一更新，这样是等价的吗？

感谢回复。

**Comment by anxiangsir** [comment]
索引这个操作 `weight[index]`，也会有反向传播，`subweight`的梯度会写到` weight` 里。

loss的确需要平均，已经有 PR 发了过来，我后续修复一下；

**Comment by Youngboy12** [comment]
问题已经解决了，是我自己代码的问题，多谢！

**Comment by abcsimple** [comment]
你好，请问partial_fc_v1与partial_fc_v2在功能上有差异吗？使用v2训练是否会比v1占用更多的显存？
