### ISSUE TITLE
why interpolate raise "Expect x to not have duplicates" error when training arcface-torch ms1mv2?

### ISSUE THREAD

**Issue by wengmingao** [deepinsight/insightface#2152]
python train.py configs/ms1mv2_mbf                                              
...
Training: 2022-10-27 04:59:19,503-Speed 927.28 samples/sec   Loss 28.4681   LearningRate 0.098250   Epoch: 0   Global Step: 2000   Fp16 Grad Scale: 262144   Required: 58 hours
testing verification..
(12000, 512)
infer time 33.411153999999975
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    main(parser.parse_args())
  File "train.py", line 176, in main
    callback_verification(global_step, backbone)
  File "/workspace/insightface/recognition/arcface_torch/utils/utils_callbacks.py", line 55, in __call__
    self.ver_test(backbone, num_update)
  File "/workspace/insightface/recognition/arcface_torch/utils/utils_callbacks.py", line 30, in ver_test
    acc1, std1, acc2, std2, xnorm, embeddings_list = verification.test(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/insightface/recognition/arcface_torch/eval/verification.py", line 272, in test
    _, _, accuracy, val, val_std, far = evaluate(embeddings, issame_list, nrof_folds=nfolds)
  File "/workspace/insightface/recognition/arcface_torch/eval/verification.py", line 191, in evaluate
    val, val_std, far = calculate_val(thresholds,
  File "/workspace/insightface/recognition/arcface_torch/eval/verification.py", line 151, in calculate_val
    f = interpolate.interp1d(far_train, thresholds, kind='slinear')
  File "/opt/conda/lib/python3.8/site-packages/scipy/interpolate/_interpolate.py", line 571, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "/opt/conda/lib/python3.8/site-packages/scipy/interpolate/_bsplines.py", line 1252, in make_interp_spline
    raise ValueError("Expect x to not have duplicates")
ValueError: Expect x to not have duplicates

**Comment by IsidoreSong** [comment]
Degrading scipy to 1.8.1 works for me.
It's interesting that I re-deploy my project and meet the same problem an hour after your post.
Hope it helps you.

**Comment by wengmingao** [comment]
> Degrading scipy to 1.8.1 works for me. It's interesting that I re-deploy my project and meet the same problem an hour after your post. Hope it helps you.

Thanks a lot. Downgrade to 1.8.1 works for me too.

**Comment by angrebobo** [comment]
Thank you, I have also solved this problem

**Comment by bravejpg** [comment]
> Degrading scipy to 1.8.1 works for me. It's interesting that I re-deploy my project and meet the same problem an hour after your post. Hope it helps you.

Really thanks.

**Comment by nedstarkofhe** [comment]
真的 谢谢

**Comment by Hqscesz** [comment]
> Degrading scipy to 1.8.1 works for me. It's interesting that I re-deploy my project and meet the same problem an hour after your post. Hope it helps you.

really thanks

**Comment by nganntt** [comment]
scipy 1.8.1 works for me. Thank you very much

**Comment by DLumi** [comment]
If downgrading scipy to 1.8.1 is not an option (for whatever reason, say you use python=3.11), but still want to use the evaluation function, you can replace the line  `f = interpolate.interp1d(far_train, thresholds, kind='slinear')` with  `f = interpolate.BSpline.construct_fast(far_train, thresholds, k=1)`. This is what's called under the hood anyway, and it bypasses the checks introduced in later versions. However, note that **we're bypassing some of the preprocessing**, too, so the **output will be slightly different**. 

P.S. what's shocking to me is that technically, scipy's `interp1d` is not meant to work with vectors containing duplicates? So the evaluation function technically relies on undefined behavior. I'd rather rewrite it with some healthier alternative, but I'm down this rabbit hole for long enough
