### ISSUE TITLE
ViT的训练为什么不使用Dali加载数据？

### ISSUE THREAD

**Issue by Youngboy12** [deepinsight/insightface#2155]
请教作者两个问题：

1、如题，ViT的训练为什么没使用Dali加载数据？是会影响效果吗？

2、如果我只有单机8卡的机器，训练ViT是否使用了梯度累计对结果大概有多大影响？根据作者的实验，Single-Host GPU训练实验中，ViT-T使用了梯度累计而ViT-B没使用梯度累计，相比64卡训练差异都比较小（MFR-ALL分别为92.04→92.24和97.16→97.42），从这个结果如何看代梯度累计的影响呢？

因计算资源较少，希望从作者的实验中多看到一些结论。非常感谢！

**Comment by anxiangsir** [comment]
1. 使用DALI训练，不会对训练造成影响，如果磁盘IO不够的话，建议使用DALI；
2. 为了快速实验，大模型都是用64卡跑的，如果为了复现论文的结果，建议使用累计梯度，有同学反馈，大模型使用较小的batchsize训练结果会差一些，累计梯度是为了增加batchsize。

**Comment by Youngboy12** [comment]
好的，谢谢！

**Comment by twmht** [comment]
@anxiangsir 

請問你們用 dali 訓練 glint360k 的時候，是先透過 unpack_glint360k.py 然後再用 im2rec.py 去弄一個新的 rec 出來嗎?
