### ISSUE TITLE
while loading bin file for verification, what do you mean by issame_list?

### ISSUE THREAD

**Issue by Isaver23** [deepinsight/insightface#217]
Hi, recently I'm very confused about the format of verification sets, such as lfw.bin. Specially, whats the meaning of Ture or False in lfw.bin???
`bins, issame_list = pickle.load(open(path, 'rb'))`
Looking forward to your reply, and thank you for your resources very much!

**Comment by nttstar** [comment]
the same person or not, for one pair of images.

**Comment by Isaver23** [comment]
Thank you very much! I got it.
