### ISSUE TITLE
why cant't I achieve the proposed accuracy on the dataset Megface?

### ISSUE THREAD

**Issue by arleyzhang** [deepinsight/insightface#219]
I  downloaded the resnet-34 model and I followed the instructions about the "Test on MegaFace":
1. Align all face images of facescrub dataset and megaface distractors
2. Generate feature files for both facescrub and megaface images.
3. Remove Megaface noises which generates new feature files.

Next, I ran the MegFace's test script "run_experiment.py" with the following command:
```
python run_experiment.py -p ../templatelists/facescrub_features_list.json ../../MegaFace_Features_cm ../../FaceScrub_Features_cm _arcface.bin ../../results
```

Finlly, I got the result files, and  I opened the file "cmc_facescrub_megaface_arcface_1000000_1.json"  and I saw the following (part of the file content) : 
```
	"cmc" : 
	[
		[ 0, 2, 16, 425, 444333, 1000000 ],
		
		[
			0.9542288780212402,
			0.9660166501998901,
			0.9761315584182739,
			0.9861488938331604,
			0.9961531758308411,
			1.0
		]
	],
```
While the rank1@10^6 accuracy is  95.4% , but I see the proposed accuracy is 96.7%.
What I tested is the model provided by the user, but why  there is a difference between these two results?
I use the cropped facescrub set to test the result, which is a subset of FaceScrub including 80 identities, is the method I used to test wrong? 
I check the official website of megface, there is a dataset named “FaceScrub cropped + json zip ” in which the images are all aligned and cropped, should I use this dataset to test? But I think the test results should be the same. 
Plese help me and give me a little guidance. Thanks!

**Comment by FafeiXuan** [comment]
Hi, I want to test the downloaded model r50 on megaface, and I follow the instructions, I changed the path of lst and others, and then run align_megaface.py to align facescrub and megaface, and also run gen_megaface.py and remove_noises.py, and at last I use run_experiment.py, but the result is rank-1 41%, there must be something wrong, what maybe I miss? Thank you!
And I also download facescrub_images_112x112.tar but the pictures are all png, should I change the format as the facescrub_uncropped_features_list.json so that I can run run_experiment.py?
Thanks :)

**Comment by larsoncs** [comment]
I think you should use align_megaface.py to align FaceScrub full   , but not align FaceScrub cropped  @arleyzhang

**Comment by nttstar** [comment]
Hi, at that time we used the aligned facescrub images which produced by Matlab code with the same face detector(MTCNN) and transformed landmark coordinates. But it may have subtle differences on the part of similarity transformation comparing with our python code. As a result, this may affect the Megaface accuracy by around 1%. We will make changes accordingly in our paper later.

**Comment by 2151330** [comment]
@nttstar Can you give a baidu network disk linkI cannot download the Linux Development Kit (.zip) from the Megaface official website.
