### ISSUE TITLE
Something was wrong with modelzoo

### ISSUE THREAD

**Issue by huytuong010101** [deepinsight/insightface#2195]
Hi,
I got this error when using modol_zoo to download the person_detection scrfd model.
The URL to download model was died (http://d1gsb2o3ihr2l5.cloudfront.net/models/scrfd_person_2.5g.onnx).
Can you check it
![image](https://user-images.githubusercontent.com/53045632/207627250-5c056df8-8841-4ad6-87e2-9cd2676e31a0.png)

![image](https://user-images.githubusercontent.com/53045632/207626965-da5bc4fb-c564-4819-84d6-041c2ec3b9cb.png)
Thanh you so much,

**Comment by nttstar** [comment]
I will put it into cloudfront soon

**Comment by nttstar** [comment]
@huytuong010101 finished
