### ISSUE TITLE
Questions about the easy_margin option

### ISSUE THREAD

**Issue by fengshikun** [deepinsight/insightface#22]
Thanks for your amazing work! After reading your paper and some code in this project, i have some questions:
1. What's the meaning of option  ```easy_margin```?
```
    if args.easy_margin:
      cond = mx.symbol.Activation(data=cos_t, act_type='relu')
      #cond_v = cos_t - 0.4
      #cond = mx.symbol.Activation(data=cond_v, act_type='relu')
    else:
      cond_v = cos_t - threshold
      cond = mx.symbol.Activation(data=cond_v, act_type='relu')
```
2. Why do relu activation on cos_t, will it let the minus value in fc7 not use amsoftmax's margin to do finnal softmax loss computing?

**Comment by nttstar** [comment]
'easy_margin' means we just add margin on the subset of "WX>0". It works but the defined formula is not monotone decreasing anymore.
'relu' here can be thought of 'if-else' condition.

**Comment by BrettLL** [comment]
hi,@nttstar , when I set easy_margin=false, what does  "zy_keep = zy - s*mm" mean? According to my understandings, it means "zy_keep = s*cos(theta)-s*m*sin(m)". however, I can not understand m*sin(m), waiting for your reply~
