### ISSUE TITLE
where is the official link of agedb_30.bin, cfp_fp.bin, lfw.bin ?

### ISSUE THREAD

**Issue by zhangming8** [deepinsight/insightface#2208]
Where is the official link of agedb_30.bin, cfp_fp.bin, lfw.bin ?
I cannot find the link of above bin files.
Can someone provide it ?

**Comment by zhangming8** [comment]
> Where is the official link of agedb_30.bin, cfp_fp.bin, lfw.bin ? I cannot find the link of above bin files. Can someone provide it ?

Oh, I know it.
Unzip any dataset, you will find them.

Such as "MS1M-ArcFace":
faces_emore
├── agedb_30.bin
├── calfw.bin
├── cfp_ff.bin
├── cfp_fp.bin
├── cplfw.bin
├── lfw.bin
├── property
├── train.idx
├── train.rec
└── vgg2_fp.bin

**Comment by aidansmyth95** [comment]
Is there a script that was used to create these?
