### ISSUE TITLE
Validation Loss

### ISSUE THREAD

**Issue by stavyadatta** [deepinsight/insightface#2217]
Hello,
I am new to training facial recognition models and would greatly appreciate any insights you may have. Can you explain how to calculate validation loss for a facial recognition model. I do realise that the head is different for training and validation. Is there a way to calculate validation loss? 

Thanks
@nttstar

**Comment by stavyadatta** [comment]
Anyone on this?

**Comment by nttstar** [comment]
Unlike image classification, there's no common class-labeled validation dataset in facial recognition training.

**Comment by stavyadatta** [comment]
Thank you so much for confirmation!
