### ISSUE TITLE
PBIDR no model saved after fast_train

### ISSUE THREAD

**Issue by waleedrazakhan92** [deepinsight/insightface#2224]
Hello, I've been trying to run the script on the provided scans. The preprocessing steps run fine but when i try to run `bash script/fast_train.sh` the code runs okay but at the end the model is not stored in the produced checkpoint folders so i cannot run the eval script.

**Comment by waleedrazakhan92** [comment]
Found out that it wasnt saving after each epoch.

**Comment by waleedrazakhan92** [comment]
> Is you found the solution for it? I am same this error.

If I remember correctly, by default it doesn't save after one epoch.

**Comment by wengjincheng** [comment]
> > Is you found the solution for it? I am same this error.
> 
> If I remember correctly, by default it doesn't save after one epoch.

Thanks your reply, sorry for my next question, I am confused that this method(PBIDR) should train every time before I want to reconstructe a human face? For example , I need use OSTC to get the coarse mesh and preprocess the raw data and do the train then I can render the promised reconstructed result, is it correct? Sorry for your time...
