### ISSUE TITLE
[BUG] - typo in the wandb code

### ISSUE THREAD

**Issue by stavyadatta** [deepinsight/insightface#2228]
Hi, Please fix this on the train.py in the arcfaace_torch library. This is at line number 81. 

![Screenshot_20230124_181951](https://user-images.githubusercontent.com/62042596/214296204-8773d591-19a6-416b-acb8-8bb45cd535ea.png)

Thank you

**Comment by nttstar** [comment]
Fixed, thank you!
Next time you can create a PR :)
