### ISSUE TITLE
face swapping training code question

### ISSUE THREAD

**Issue by gyupro** [deepinsight/insightface#2229]
Hi.

I really enjoyed the face swapping example that you uploaded. I was just wondering how you did & if you plan to release training code.

Is there any paper that I can look into or give me a guide how I can achieve the goal you did?

Thanks in advance

**Comment by nttstar** [comment]
no such plan yet but maybe in the future.

**Comment by shineway14** [comment]
> 

> Hi.
> 
> I really enjoyed the face swapping example that you uploaded. I was just wondering how you did & if you plan to release training code.
> 
> Is there any paper that I can look into or give me a guide how I can achieve the goal you did?
> 
> Thanks in advance

have got any solution to train
