### ISSUE TITLE
PnP Process of "Perspective Reconstruction of Human Faces by Joint Mesh and Landmark Regression"

### ISSUE THREAD

**Issue by YongtaoGe** [deepinsight/insightface#2234]
Hi, I found the ProjectionLoss in https://github.com/deepinsight/insightface/blob/c7bf2048e8947a6398b4b8bda6d1958138fdc9b5/reconstruction/jmlr/losses.py#L45.

But I couldn't find the loss used in train.py. Could you give me some hint about the code? Thanks!

**Comment by nttstar** [comment]
projectionloss is not used.

**Comment by YongtaoGe** [comment]
Thanks for your reply!
