### ISSUE TITLE
Can't Download Dataset 4th Face Anti-spoofing Workshop and Challenge@CVPR2023 

### ISSUE THREAD

**Issue by oggyfaker** [deepinsight/insightface#2248]
Hi insightfaces organizer !  
i got some error when i use your provided google link for download dataset competition. But it **limit times for downloading**. I don't have any account of Baidu so download from Baidu is not easy for me. Can you fix the dataset on GG Drive as soon as for all participants can  access dataset early. Hope to see your response !

**Comment by nttstar** [comment]
This problem will probably be restored automatically tomorrow. Also, we will try to upload another copy to OneDrive.

**Comment by oggyfaker** [comment]
Thanks for your reply !

**Comment by mlourencoeb** [comment]
Dear @nttstar,
The download problem persists with Google Drive. Any news if you were able to upload to OneDrive?
BEst,
Miguel

**Comment by oggyfaker** [comment]
Hi authors, after get all files train, i cant unzip it. Could you show me how to unzip it by command line ? I used this command and unzip it by password but error is null !

`cat CVPR2023-Anti_Spoof-Challenge-Release-Data-20230209.z0* > ~/train.zip`

**Comment by thaint2901** [comment]
@nttstar I'm unable to extract the test data with the password provided in the email. Could you please update the password?
filename: CVPR2023-Anti_Spoof-Challenge-ReleaseData-Test-20230211.zip
Regards.
