### ISSUE TITLE
Getting error when fetching model

### ISSUE THREAD

**Issue by bharatsingh430** [deepinsight/insightface#2253]
I am getting this error

RuntimeError: Failed downloading url http://insightface.cn-sh2.ufileos.com/models/inswapper_128.onnx.zip . Is this available via some other url?

**Comment by bharatsingh430** [comment]
Found google drive link, https://drive.google.com/file/d/1GW7Q41Uk4H30wVFL2Tl4Kl8MWIV4fVFC/view

**Comment by YuanBo66668888** [comment]
https://drive.google.com/file/d/1GW7Q41Uk4H30wVFL2Tl4Kl8MWIV4fVFC/view is not found
