### ISSUE TITLE
shuffle_rec error

### ISSUE THREAD

**Issue by HeChengHui** [deepinsight/insightface#2254]
Trying WebFace42M + DALI following the instructions in [arcface_torch](https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch). When I get to `python scripts/shuffle_rec.py <path to folder containing train.idx/.lst/.rec>`, I got the following error:
```
Process Process-1:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/insightface/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/user/anaconda3/envs/insightface/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/user/FR/insightface/recognition/arcface_torch/scripts/shuffle_rec.py", line 17, in read_worker
    assert header.flag > 0
AssertionError

```

What went wrong?

**Comment by jovialio** [comment]
I think the way the header.flag was arbitrarily added using im2rec was different from other datasets. i removed the assert and manually changed the total idx. shuffle_rec.py can now run. Will train and verify if the dataset is still able converge for my current model.

`#assert header.flag > 0
# 42474557 number of images in the Webface42M dataset
 imgidx = np.array(range(1, 42474558))`

**Comment by HeChengHui** [comment]
@jovialio 
were you able to see if Dali is working using your fix?

**Comment by deep-practice** [comment]
Same error

**Comment by jovialio** [comment]
Yes Dali is working.

**Comment by HeChengHui** [comment]
> I think the way the header.flag was arbitrarily added using im2rec was different from other datasets. i removed the assert and manually changed the total idx. shuffle_rec.py can now run. Will train and verify if the dataset is still able converge for my current model.
> 
> ```
> #assert header.flag > 0
> # 42474557 number of images in the Webface42M dataset
>  imgidx = np.array(range(1, 42474558))
> ```

---
Working with this
