### ISSUE TITLE
Could you provide the ga-model of the InsightFace project?

### ISSUE THREAD

**Issue by gwsbhqt** [deepinsight/insightface#226]
Hello author, I am very happy to learn from your open source InsightFace project. 
I recently found that the project has updated the function of recognizing age and gender. 
This is also a function that I am very much looking forward to and I would like to express my thanks again.

I have a question that I saw in deploy/test.py
```
parser.add_argument('--model', default='', help='path to load model.')
parser.add_argument('--ga-model', default='', help='path to load model.')
```
In previous versions, the model parameter of test.py was the r34 model. 
Why was the model parameter empty in test.py this time?
And this time the ga-model has been added. 
It seems that I can't find the download of the ga-model model. 
I do not know if it is convenient for you to provide a download of ga-model?

Looking forward to your reply.
Good luck.

**Comment by gwsbhqt** [comment]
@nttstar

**Comment by gwsbhqt** [comment]
I found these in the code history
···
parser.add_argument('--age-model', default='../models2/model-r34-age/model,0', help='path to load model.')
parser.add_argument('--gender-model', default='../models2/model-r18-gender/model,0', help='path to load model.')
···
I think there should be a ga-model and it is still integrating.
Hope to provide ga-model download after the integration is completed.
Thanks.

**Comment by glorioushedgehog** [comment]
nttstar just posted a ga model!

https://github.com/deepinsight/insightface/issues/272

**Comment by gwsbhqt** [comment]
@glorioushedgehog oh my god, thank you very much for reminding me

**Comment by Gabit07** [comment]
> parser.add_argument('--age-model', default='../models2/model-r34-age/model,0', help='path to load model.')

Doo you know what does "0" mean in parser.add_argument('--age-model', default='../models2/model-r34-age/model,0', help='path to load model.')?
