### ISSUE TITLE
Question about training datasets for buffalo_l

### ISSUE THREAD

**Issue by kymillev** [deepinsight/insightface#2269]
On which datasets were the available face detection (SCRFD-10GF) and face recognition (ResNet50@WebFace600K) models trained for the buffalo_l model pipeline? Am I correct in assuming that SCRFD was trained on WIDER FACE and the face recognition model on WebFace600K, or were these trained on multiple datasets?

**Comment by nttstar** [comment]
> Am I correct in assuming that SCRFD was trained on WIDER FACE and the face recognition model on WebFace600K

Right.
