### ISSUE TITLE
Could you publicly release inswapper_256 or inswapper_512?

### ISSUE THREAD

**Issue by mike-hearn** [deepinsight/insightface#2270]
Just for the fun of it.

SimSwap has their 512px model out there, but I find insightface's method to be much better, so it would be great if there were a higher resolution model available.

Thanks.

**Comment by nttstar** [comment]
We are currently preparing a paper, so not now.

**Comment by mike-hearn** [comment]
I just saw this: https://github.com/deepinsight/insightface/tree/master/web-demos/swapping_discord. This seems like a cool service, so congrats on that.

Does this make it more or less likely that higher resolution models will be available to the public? My gut tells me "less likely" but I am an eternal optimist, so perhaps we still might get access to these models soon?

Please let me know. The 128x128 model is amazing even at a low resolution. If you don't see yourself releasing the model any time soon, feel free to close this issue and I'll re-open in a couple of years when perhaps incentives have changed.

**Comment by nttstar** [comment]
Yes not now we can close this issue.

**Comment by phineas-pta** [comment]
@nttstar since you pulled out the 128 model, does it mean the 256 & 512 models won't be released?

**Comment by MantisTree** [comment]
Bump :)  Thanks for your great work!

**Comment by arnold408** [comment]
Please provide 256 or 512 model. 
It will greatly improve quality of output images.
Waiting for your positive reply.
Thanks a lot!

**Comment by ArchEight** [comment]
There

> Please provide 256 or 512 model. It will greatly improve quality of output images. Waiting for your positive reply. Thanks a lot!

There will be no other models released to the public with higher resolution outputs. The existing model is out in the wild now, but even that one has been pulled. All further use and more performant models are accessed solely via the bot on InsightFaceSwap's Discord.

https://github.com/deepinsight/insightface/tree/master/web-demos/swapping_discord

**Comment by ArchEight** [comment]
> @nttstar since you pulled out the 128 model, does it mean the 256 & 512 models won't be released?

There will be no other models released to the public with higher resolution outputs. The existing model is out in the wild now, but even that one has been pulled. All further use and more performant models are accessed solely via the bot on InsightFaceSwap's Discord.

https://github.com/deepinsight/insightface/tree/master/web-demos/swapping_discord

**Comment by phineas-pta** [comment]
sr but who r u ? do u participate in the project ?

**Comment by nttstar** [comment]
Just have fun but make sure that all insightface open-sourced models are not available for commercial usage.

**Comment by flydragon2018** [comment]
> > Just for the fun of it.
> > SimSwap has their 512px model out there, but I find insightface's method to be much better, so it would be great if there were a higher resolution model available.
> > Thanks.
> 
> Ultimately since the 128 method works so well already, I get excellent results using inswapper to generate the synthetic face and then engaging to 512 with codeformer. Don't need any new models.

could you please give some demo how to use codeformer for high resolution?

**Comment by puritysb** [comment]
@nttstar,
The quality of the inswapper provided by Discord Bot is impressive.
I'd like to discuss the possibility of using it by API or model for a fee.
Could you let me know contact point for the business discussion?

**Comment by nttstar** [comment]
> @nttstar, The quality of the inswapper provided by Discord Bot is impressive. I'd like to discuss the possibility of using it by API or model for a fee. Could you let me know contact point for the business discussion?

@puritysb please contact joey@insightface.ai

**Comment by Neltherion** [comment]
> We are currently preparing a paper, so not now.

Is the paper available? I'm curious how different it is from other approaches in the field🤔

**Comment by zsxkib** [comment]
+1 is the paper out? i'd like to just train my own 512 version

**Comment by dyhsia0** [comment]
+1 for the paper! wondering the magic of inside! :)

**Comment by tejassssssss** [comment]
ching chong mf

**Comment by MantisTree** [comment]
March chiming in for the paper 😁🙏

**Comment by zsxkib** [comment]
Are there similar papers anyone knows about?

**Comment by zhch-sun** [comment]
> We are currently preparing a paper, so not now.

have you publish your paper?

**Comment by zsxkib** [comment]
I get the feeling y'all aren't gonna publish this paper...

**Comment by irux** [comment]
paper?

**Comment by Pantonia4** [comment]
128 has reached its limit with flux. But guess the devs have sold their soul and dont give a shit

**Comment by Darlanio** [comment]
https://github.com/deepinsight/inswapper-512-live - is it possible to extract an inswapper512.onnx from this?

**Comment by LGrafx** [comment]
> https://github.com/deepinsight/inswapper-512-live - is it possible to extract an inswapper512.onnx from this?

Thanks for the find! I followed through with downloading the app (pretty neat actually) and I'm scouring through the Application/Packages, but nothing so far. Although, I don't have much experience in this sort of thing - hopefully someone can find it in there. Otherwise, it also seems possible it is calling on the model from a network as it requires an internet connection.

**Comment by Buumcode** [comment]
> https://github.com/deepinsight/inswapper-512-live - is it possible to extract an inswapper512.onnx from this?

"The inswapper-512-live model itself is not included in this release and is only available under strict licensing agreements"

**Comment by tedbiv** [comment]
https://huggingface.co/datasets/Gourieff/ReActor/blob/main/models/reswapper_256.onnx works in comfyui, won't work in forge or auto1111.

**Comment by Buumcode** [comment]
>https://huggingface.co/datasets/Gourieff/ReActor/blob/main/models/reswapper_256.onnx works in comfyui, won't work in forge or auto1111.

Reswapper is other model. INSWAPPER needed.

Reswapper is bad in similarity quality. Inswapper is pretty good.

**Comment by iEddie-cmd** [comment]
they will never opensource anything anymore. Lost all hopes!
