### ISSUE TITLE
Consider relying on onnxruntime-gpu for both CPU / GPU for the Python Package

### ISSUE THREAD

**Issue by christidis** [deepinsight/insightface#2276]
Having only `onnxruntime-gpu` installed I get the following when deploying on CPU. (No issues on GPU).
```
CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version
```

According to the [installation](https://github.com/deepinsight/insightface/tree/master/python-package#install) instructions of the Python package

_You have to install `onnxruntime-gpu` manually to enable GPU inference, or install `onnxruntime` to use CPU only inference._

It's been a while since `onnxruntime-gpu` (`v1.9.0`+) is eligible to run both on CPU and GPU.
https://github.com/Microsoft/onnxruntime/releases/tag/v1.9.0
https://github.com/microsoft/onnxruntime/issues/7313
https://github.com/microsoft/onnxruntime/issues/9292

Will you consider removing the `onnxruntime` depencendy from the python package for running on CPU?
This will allow users maintaining a single Docker immage in the build/CI for the Apps relying on InsightFace in order to deploy both on CPU and GPU servers.

**Comment by nttstar** [comment]
Our python library does not have the onnxruntime dependency.

**Comment by christidis** [comment]
Right, sorry, not as a python dependency, a prerequisite let's say. Manually installing `onnxruntime-gpu` should allow CPU inference or GPU inference if the system supports it. Currently `onnxruntime-gpu` doesn't support inference over CPU.

**Comment by nttstar** [comment]
If you have the right GPU installed, `onnxruntime-gpu` can support both GPU and CPU inference.

**Comment by christidis** [comment]
What if you don't have GPU installed at all? This is what I get and I can only workaround the issue by removing `onnxruntime-gpu` and installing `onnxruntime` (building and maintaining two images). I was expecting the GPU package to be eligible to run on a CPU-only machine.

```
File "/fd_app/src/main.py", line 3, in <module>
    from .routes import router
  File "/fd_app/src/routes.py", line 12, in <module>
    face_app = FaceAnalysis(name=model_pack_name, allowed_modules=['detection'], root=".")
  File "/opt/conda/envs/app_env/lib/python3.8/site-packages/insightface/app/face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "/opt/conda/envs/app_env/lib/python3.8/site-packages/insightface/model_zoo/model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "/opt/conda/envs/app_env/lib/python3.8/site-packages/insightface/model_zoo/model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/opt/conda/envs/app_env/lib/python3.8/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "/opt/conda/envs/app_env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/envs/app_env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=0 ; hostname=main-fd-app-production-cpu-964fff8cf-bmjb5 ; expr=cudaSetDevice(info_.device_id); 


[2023-03-31 10:12:35 +0000] [8] [INFO] Worker exiting (pid: 8)
[2023-03-31 10:12:35 +0000] [1] [INFO] Shutting down: Master
[2023-03-31 10:12:35 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by nttstar** [comment]
You have no GPU but installing onnxruntime-gpu? That does not make sense.

**Comment by christidis** [comment]
Please, take a moment to review the links that I have attached in the issue. According to onnxruntime v1.9.0+
>GPU package can be used on both CPU-only and GPU machines

So, yes I have no GPU and I am installing `onnxruntime-gpu`. Actually, my goal is to have platform agnostic images, simpler and faster CICD pipelines, and images eligible to be deployed and scale in CPU (and GPU) workers.

**Comment by nttstar** [comment]
I think platform-agnostic images is impossible, even for different GPU series, like P100 versus V100 versus A100.

**Comment by christidis** [comment]
Of course they are. The issue is with CPU-only machines and insightface Python package which expects `onnxruntime` but fails with `onnxruntime-gpu` when it shouldn't. Anyway I think I explained the issue pretty clear. If it is not going to be included let's move on.
