### ISSUE TITLE
Loss does not decrease when use resume training in arcface_torch

### ISSUE THREAD

**Issue by deep-practice** [deepinsight/insightface#2277]
Fp16 Grad Scale becomes 0 and loss does not decrease for a long time

Training: 2023-04-07 09:02:24,067-Speed 931.38 samples/sec   Loss 9.5353   LearningRate 0.066591490546   Epoch: 5   Global Step: 440620   Fp16 Grad Scale:  0   Required: 187 hours

**Comment by TouchSkyWf** [comment]
> Solved

Excuse me, how do you solve the problem that the loss does not decrease? I met the same problem

**Comment by Jongsik-mo** [comment]
Excuse me, how do you solve the problem that the loss does not decrease? I met the same problem
