### ISSUE TITLE
Alignment in Insightface python-package

### ISSUE THREAD

**Issue by akirs82** [deepinsight/insightface#2280]
Hello there,

I am trying to use the insightface python-package. I would like to know whether face alignment is used in the FaceAnalysis from insightface.app. If we are doing face detections separately and  doing feature extraction separately,do we need to align the face detected images for better accuracy?

```
import insightface,cv2
from insightface.app import FaceAnalysis
from insightface.utils import face_align

handler = FaceAnalysis(name='buffalo_l',allowed_modules=['detection'])
handler.prepare(ctx_id=0,det_thresh=0.5,det_size=(640,640))
img = cv2.imread('c9dbc9adfac86609b7844e96adabb1be.jpg')
out = face_align.norm_crop(img,faces[0]['kps'],112) #aligned image
```

The face image with alignment seems extra regions in the border are taken. Is this image good for feature extraction or we can skip this alignment step,as the image without alignment does not have background pixels. 

Input IMage
![image](https://user-images.githubusercontent.com/76611837/231132470-f6fdd152-ea07-4c05-98a5-0aa136481023.png)

Face Detection Aligned
![aligned3](https://user-images.githubusercontent.com/76611837/231132617-c5c15f24-953d-4c3a-ba3a-6196e6d0bd2b.jpg)

Face Detection NOT ALigned
![non-aligned3](https://user-images.githubusercontent.com/76611837/231132701-db00d606-7a0e-4e82-a604-b91b6247d22f.jpg)

regards
akirs

**Comment by nttstar** [comment]
The alignment process is a must.

**Comment by AmanPSingh2004** [comment]
how the alignment take place in insightface
