### ISSUE TITLE
The performance variation with scaling parameter: s

### ISSUE THREAD

**Issue by yoookoo** [deepinsight/insightface#229]
Have you ever done ablation analysis on the scaling parameter s?
In other words, what do we rely on to set s? the number of IDs? or the distribution of dataset?

**Comment by nttstar** [comment]
It will not affect a lot while s in the range of [30,100] in our experiments.

**Comment by yoookoo** [comment]
Thank you！ In our own dataset with 170k ids， s affects a lot in [32-256]. So we suggest that it depends on the norm distribution of images. And dataset with high quality images should have larger s, vice verse. I think you can try some experiments. It is also an interesting observation.

**Comment by nttstar** [comment]
@yoookoo Did you use the same network backbone as ours?

**Comment by yoookoo** [comment]
@nttstar Yes, we use r100 as the backbone. Maybe some reweighting methods between fixed scale and original feature norm  are more useful.

**Comment by nttstar** [comment]
@yoookoo Can you post your detail acc vs different ``s`` setting? It's ok if you can email me{guojia AT gmail.com}, thanks~

**Comment by zhaowwenzhong** [comment]
what is  the meaning  of " Maybe some reweighting methods "?
@yoookoo

**Comment by AITTSMD** [comment]
@yoookoo @nttstar hi，I also want to know the effect of s~

**Comment by rose-jinyang** [comment]
Hello
How are you?
I also am using arcface but I did not understand the effect of scale parameter s.
How should we set this parameter?
Most arcface implementations used s=64.0.
But some implementations used small values such as 16.06 or 8.0.
Please let me know the effect of the scale parameter and how to set it.
Thanks
