### ISSUE TITLE
why is the threshold set 1.24 in test step

### ISSUE THREAD

**Issue by ronyuzhang** [deepinsight/insightface#23]

**Comment by nttstar** [comment]
empirical value from lfw 10-fold cross validation

**Comment by ronyuzhang** [comment]
i remember threshold range of facenet is 0-2, and the insightface is 0-3?

**Comment by nttstar** [comment]
What do you mean by this `threshold`?  Where do you refer to?

**Comment by ronyuzhang** [comment]
sorry I understand mistakes. please close this issue
