### ISSUE TITLE
training error with cuda broken!

### ISSUE THREAD

**Issue by anguoyang** [deepinsight/insightface#230]
Hi all,
I tried to train according to the tutorial, but after loading the data, cuda broken with hints:
"no capable cuda device", it is very strange, because I always train the yolo networks without any error before, so I checked with gpu-z, the cuda/opencl had been disabled! I googled for each solution but still failed, I have to re-install the windows and cuda, then everything is fine, but if I install mxnet and train insightface, then the same nightmare happened, I have to re-install windows again:(
anyone with the same experience? plz help...

**Comment by nttstar** [comment]
I have no knowledge about running mxnet on Windows. Hope anyone can help. If on Linux, please try re-installing nvidia-driver, cuda and mxnet. Nvidia-driver and cuda can be installed in one step if I remember correctly.

**Comment by anguoyang** [comment]
thank you, it seems that I have to re-install windows again, maybe it is a bug in mxnet
