### ISSUE TITLE
InsightFace Swap Bot implementation

### ISSUE THREAD

**Issue by elenajoness** [deepinsight/insightface#2311]
Hi Sir,
Hope you are doing well,

✅ You said that "To explain roughly; I want to make an adaptation where InsightFace's &quot;Face Swap Bot&quot;
can be used as an API....." and we can do it with very high quality and fast, you can check our strong portfolio during meeting to make sure.

📩 Mind if I send over a few times to quick chat? email me ellenaa.joness@gmail.com

Thanks, 
- Elena.

**Comment by nttstar** [comment]
I never said this.
