### ISSUE TITLE
Help Error: Could not build wheels for insightface

### ISSUE THREAD

**Issue by tamal777** [deepinsight/insightface#2316]
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by anish9** [comment]
@tamal777  how was this solved ?

**Comment by andrewcharlwood** [comment]
> @tamal777  how was this solved ?
> 

For anyone else unsure - I wasn't able to build for python 3.10 after plenty of trial and error, it managed to build without a problem for python 3.8 & 3.9 for me  though.
