### ISSUE TITLE
why use skimage.transform for similarity transform

### ISSUE THREAD

**Issue by zhenglaizhang** [deepinsight/insightface#233]
I noticed the following code:

```python3
  tform = trans.SimilarityTransform()
  tform.estimate(dst, src)
  M = tform.params[0:2,:]
  #M = cv2.estimateRigidTransform( dst.reshape(1,5,2), src.reshape(1,5,2), False)
```
I looks like originally the transform M is estimated with opencv estimateRigidTransform, it may return None for bad data, is this  the **only reason** to switch to skimage.transform.SimilarityTransform()?

**Comment by xmuszq** [comment]
version in cv2 is not robust. Do you have any other source to use other than skimage?

**Comment by safwankdb** [comment]
> version in cv2 is not robust. Do you have any other source to use other than skimage?

Please check out [petyr library](https://github.com/safwankdb/petyr). It is well suited for the task.
