### ISSUE TITLE
[Question] Comparison about face embeddings (recognition)

### ISSUE THREAD

**Issue by soribido** [deepinsight/insightface#2332]
First of all, thank you for great repo.
I have a question about the comparison between face embeddings.

Suppose we get 50 reference face embeddings for 10 people.
When input new face, I want to recognize it by comparing the reference faces. 
Do we need to compare each of the 50 embeddings or average the 50 embeddings per person and compare them to the 10 embeddings?

**Comment by nttstar** [comment]
There is no definitive conclusion as to which is better, you can test it on an actual test set.

**Comment by soribido** [comment]
@nttstar Thank you for your answer.
