### ISSUE TITLE
[QUESTION] Do you plan to release inswapper model for higher resolution? E.g. 320?

### ISSUE THREAD

**Issue by NikolayKozyrskiy** [deepinsight/insightface#2333]

**Comment by NikolayKozyrskiy** [comment]
I've tried the in swapper model released several days ago on HF. It's awesome! Thank you very much for it! I'm really eager to try a bigger one for high-fidelity results. Do you plan to release the in swapper model with higher resolution? Looking forward to try it

**Comment by phineas-pta** [comment]
the huggingface release isn't official see #2339

unclear about higher resolution models see #2270
