### ISSUE TITLE
download the inswapper_128.onnx swapping model from Google Drive Here

### ISSUE THREAD

**Issue by iftekharalammithu** [deepinsight/insightface#2335]
download the inswapper_128.onnx swapping model from Google https://drive.google.com/file/d/1krOLgjW2tAPaqV-Bw4YALz0xT5zlb5HF/view

**Comment by nttstar** [comment]
#2315

**Comment by Shreyas-Mahajan21** [comment]
where to move this file

**Comment by Shubhamsinghara** [comment]
download the file from https://drive.google.com/file/d/1krOLgjW2tAPaqV-Bw4YALz0xT5zlb5HF/view

**Comment by MohammedSardarSaajit4488** [comment]
thanks buddy

**Comment by alokvbv** [comment]
did this work?

**Comment by jocoin-project** [comment]
Download the file into the directory ComfyUI\models\insightface\inswapper_128.onnx

**Comment by Nicolaskicks** [comment]
same, getting still this error INVALID_PROTOBUF : Load model from inswapper_128.onnx failed:Protobuf parsing failed.
Any solution?

**Comment by MohammedSardarSaajit4488** [comment]
> did this work? Getting this: INVALID_PROTOBUF : Load model from inswapper_128.onnx failed:Protobuf parsing failed. Any solution?

Yes it did WORK!!
