### ISSUE TITLE
authentic huggingface account ?

### ISSUE THREAD

**Issue by phineas-pta** [deepinsight/insightface#2339]
is this authentic ? https://huggingface.co/deepinsight/inswapper

**Comment by nttstar** [comment]
NOT us.

**Comment by phineas-pta** [comment]
thank you 👍

**Comment by phineas-pta** [comment]
fake acc removed

https://huggingface.co/deepinsight-unofficial/inswapper/discussions/2#64e4dedfc7c084f92ac442fb
