### ISSUE TITLE
discord bot keeps failing

### ISSUE THREAD

**Issue by Tdrinker** [deepinsight/insightface#2370]
Hi, whenever I tried to do the /saveid, it always tells me "The application did not respond". This has been happening to me all day and i have tried around 30 times. I believe the bot is no longer functional. Thanks!

**Comment by ramjamx** [comment]
I can confirm, the bot is not working on discord.

**Comment by nttstar** [comment]
works now

**Comment by Tdrinker** [comment]
nice. curious on what was the issue?
