### ISSUE TITLE
Error when I run verification.py.

### ISSUE THREAD

**Issue by cici-tan** [deepinsight/insightface#241]
mxnet.base.MXNetError: [17:18:55] src/io/local_filesys.cc:166: Check failed: allow_null  LocalFileSystem::Open "/medical_data/Datasets/insightface/models/model-r50-am-lfw-symbol.json": No such file or directory

I run verification.py like this, but got an error says cannot find this file model-r50-am-lfw-symbol.json, but seems like it is a wrong file path.

sudo python3 -u verification.py --gpu 0 --data-dir /medical_data/Datasets/insightface/datasets/faces_ms1m_112x112 --model /medical_data/Datasets/insightface/models/model-r50-am-lfw,0 --target agedb_30 --batch-size 128

**Comment by nttstar** [comment]
--model /medical_data/Datasets/insightface/models/model-r50-am-lfw/model,0

**Comment by cici-tan** [comment]
@nttstar thx, I fixed that.

**Comment by wangtao2668129173** [comment]
> mxnet.base.MXNetError: [17:18:55] src/io/local_filesys.cc:166: Check failed: allow_null LocalFileSystem::Open "/medical_data/Datasets/insightface/models/model-r50-am-lfw-symbol.json": No such file or directory
> 
> I run verification.py like this, but got an error says cannot find this file model-r50-am-lfw-symbol.json, but seems like it is a wrong file path.
> 
> sudo python3 -u verification.py --gpu 0 --data-dir /medical_data/Datasets/insightface/datasets/faces_ms1m_112x112 --model /medical_data/Datasets/insightface/models/model-r50-am-lfw,0 --target agedb_30 --batch-size 128

hi ,我也遇到和你一样问题，想和你交流一下可以吗？遇到如下的问题：
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
torch.Size([12000, 3, 112, 112])
testing verification..
Traceback (most recent call last):
  File "verification.py", line 395, in <module>
    acc1, std1, acc2, std2, xnorm, embeddings_list = test(ver_list[i], model, args.batch_size, args.nfolds)
  File "/home/wangtao/miniconda3/envs/torch16/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "verification.py", line 242, in test
    net_out: torch.Tensor = backbone(img)
TypeError: 'Module' object is not callable

**Comment by wangtao2668129173** [comment]
> --model /medical_data/Datasets/insightface/models/model-r50-am-lfw/model,0

能请教关于运行verification.py

**Comment by PPPPPPPeng** [comment]
> > mxnet.base.MXNetError: [17:18:55] src/io/local_filesys.cc:166: Check failed: allow_null LocalFileSystem::Open "/medical_data/Datasets/insightface/models/model-r50-am-lfw-symbol.json": No such file or directory
> > I run verification.py like this, but got an error says cannot find this file model-r50-am-lfw-symbol.json, but seems like it is a wrong file path.
> > sudo python3 -u verification.py --gpu 0 --data-dir /medical_data/Datasets/insightface/datasets/faces_ms1m_112x112 --model /medical_data/Datasets/insightface/models/model-r50-am-lfw,0 --target agedb_30 --batch-size 128
> 
> hi ,我也遇到和你一样问题，想和你交流一下可以吗？遇到如下的问题：
> loading bin 5000
> loading bin 6000
> loading bin 7000
> loading bin 8000
> loading bin 9000
> loading bin 10000
> loading bin 11000
> torch.Size([12000, 3, 112, 112])
> testing verification..
> Traceback (most recent call last):
> File "verification.py", line 395, in
> acc1, std1, acc2, std2, xnorm, embeddings_list = test(ver_list[i], model, args.batch_size, args.nfolds)
> File "/home/wangtao/miniconda3/envs/torch16/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
> return func(*args, **kwargs)
> File "verification.py", line 242, in test
> net_out: torch.Tensor = backbone(img)
> TypeError: 'Module' object is not callable

Do you fix that problem? I got thie typeError too!
