### ISSUE TITLE
为什么你们让那个roop下架了，还说你们是原作者？

### ISSUE THREAD

**Issue by zouzhe1** [deepinsight/insightface#2417]
可是我在你们这个代码里没看到roop啊，我想玩roop，我应该去哪里玩？？

**Comment by nttstar** [comment]
请给出我让roop下架这件事的出处，谢谢

**Comment by zouzhe1** [comment]
@nttstar  我百度搜roop，然后找到个链接，然后链接到了https://huggingface.co/deepinsight-unofficial/inswapper，然后
![image](https://github.com/deepinsight/insightface/assets/13077962/5429ad80-2dd4-4dc4-ad69-1b1f56d10625)
然后
![image](https://github.com/deepinsight/insightface/assets/13077962/db8752aa-a1e6-4234-9c94-47f2792ca82e)
https://huggingface.co/deepinsight-unofficial/inswapper/discussions/2

我不知道内情，反正就是想玩一下roop，然后找不到，就跟你们反馈了这个事

**Comment by nttstar** [comment]
这是huggingface, 不是roop.

**Comment by phineas-pta** [comment]
@zouzhe1 roop关闭的原因是另一场争议
