### ISSUE TITLE
How can I get the thresholds which are used in megaface ROC test? 

### ISSUE THREAD

**Issue by HsuTzuJen** [deepinsight/insightface#242]
Hi, with the megaface development kit,  we can get the cmc and roc.
I am curious about the thresholds used in the roc test.
Do you have any idea?

**Comment by nttstar** [comment]
You may need to dig into the dev kit source code.

**Comment by liquor233** [comment]
But the results on megaface are given by some execution file (maybe written by C I guess?).
So how can I dig into the source code?
