### ISSUE TITLE
Error with using model "antelopev2"

### ISSUE THREAD

**Issue by Mr-Nobody-dey** [deepinsight/insightface#2420]
my code:
pip install -U insightface
import insightface
model_pack_name = 'antelopev2'
app = insightface.app.FaceAnalysis(name=model_pack_name)

error ->
RuntimeError                              Traceback (most recent call last)
[<ipython-input-25-8f3c5bb3c275>](https://localhost:8080/#) in <cell line: 1>()
      3   import insightface
      4   model_pack_name = 'antelopev2'
----> 5   app = insightface.app.FaceAnalysis(name=model_pack_name)

3 frames
[/usr/local/lib/python3.10/dist-packages/insightface/utils/download.py](https://localhost:8080/#) in download_file(url, path, overwrite, sha1_hash)
     71         r = requests.get(url, stream=True)
     72         if r.status_code != 200:
---> 73             raise RuntimeError("Failed downloading url %s" % url)
     74         total_length = r.headers.get('content-length')
     75         with open(fname, 'wb') as f:

RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip

**Comment by nttstar** [comment]
use 'buffalo_l'

**Comment by Mr-Nobody-dey** [comment]
The model is not saved where it was supposed to be and that is the reason I got that error. Solution would be download the model and use it.

**Comment by MATEMATNKx** [comment]
> my code: pip install -U insightface import insightface model_pack_name = 'antelopev2' app = insightface.app.FaceAnalysis(name=model_pack_name)
> 
> error -> RuntimeError Traceback (most recent call last) in <cell line: 1>() 3 import insightface 4 model_pack_name = 'antelopev2' ----> 5 app = insightface.app.FaceAnalysis(name=model_pack_name)
> 
> 3 frames [/usr/local/lib/python3.10/dist-packages/insightface/utils/download.py](https://localhost:8080/#) in download_file(url, path, overwrite, sha1_hash) 71 r = requests.get(url, stream=True) 72 if r.status_code != 200: ---> 73 raise RuntimeError("Failed downloading url %s" % url) 74 total_length = r.headers.get('content-length') 75 with open(fname, 'wb') as f:
> 
> RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip

https://github.com/deepinsight/insightface/issues/1525#issuecomment-2510257429
