### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by rollingrabit** [deepinsight/insightface#2428]
"D:\IDE\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IC:\Users\Administrator\AppData\Local\Temp\pip-build-env-_5_1f2zo\overlay\Lib\site-packages\numpy\core\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python310\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python310\Include "-ID:\IDE\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-ID:\IDE\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core.obj
      mesh_core.cpp
      C:\Users\Administrator\AppData\Local\Temp\pip-install-jr5z09al\insightface_39adfb2fdfd84580853082cea5d4536d\insightface\thirdparty\face3d\mesh\cython\mesh_core.h(4): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory
      error: command 'D:\\IDE\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

I have installed  Desktop development with C++ And Windows 11 SDK C++ x64/x86 build tools on my win11 PC, and almost tried everything I can find, still not work

**Comment by nursie999** [comment]
同求2.........

**Comment by allankouidri** [comment]
Same issue, @rollingrabit did you find a solution? Thank you
