### ISSUE TITLE
How to set the valid set?

### ISSUE THREAD

**Issue by divided7** [deepinsight/insightface#2435]
Generally, we should set the valid_set in `train.py` to varify the model preformance in time, but I can't find this module in `arcface_torch/train_v2.py` ?

**Comment by marlowinnovations** [comment]
You set your validation datasets in the config files.  I believe the .bin files need to be in the same folder as the train.rec file as well.

**Comment by Sunshine066** [comment]
config.rec = "/mnt/face_recognition/train_tmp/WebFace42M"
config.val_targets = ["lfw", "cfp_fp", "agedb_30"]

As following, and you must set the {agedb_30.bin   lfw.bin cfp_fp.bin } file into config.rec path
