### ISSUE TITLE
Can I save only the CNN architecture related instead of all in MXNET?

### ISSUE THREAD

**Issue by xmuszq** [deepinsight/insightface#244]
I ran the r50 and the saved model is 570MBytes. I think it saves all variables and unnecessary parts like data pre-processing. 
I just want to save the forward architecture and weights only and used for calculating the embedding. Any way to achieve that? 
I'm new in Mxnet. I read the docs and I didn't find such functions. 
@nttstar I found the pre-trained model you provided for r50 is only ~400Mbytes. Which function you used to save the model?

**Comment by nttstar** [comment]
Use `deploy/model_slim.py` to remove the last FC layer.
