### ISSUE TITLE
错误 Error: [image] This option is required. Specify a value.

### ISSUE THREAD

**Issue by yaro97** [deepinsight/insightface#2449]
As follow:
![微信截图_20231011154733](https://github.com/deepinsight/insightface/assets/12781825/f95667c8-d9f5-4728-81ac-32995bae4337)

**Comment by nttstar** [comment]
goto discord

**Comment by yaro97** [comment]
I have added insightface to the deiscord server, I don't know why this error is prompted when using the `/saveid` command, I also uploaded the picture.

**Comment by nttstar** [comment]
Github is not the right place to answer this question, we have discord help server.
