### ISSUE TITLE
the data preprocess(train data and test data)

### ISSUE THREAD

**Issue by zhaowwenzhong** [deepinsight/insightface#246]
train data preprocess： 
                _data = self.imdecode(s)
......................................
                if self.nd_mean is not None:
                    _data = _data.astype('float32')
                    _data -= self.nd_mean
                    _data *= 0.0078125

test data preprocess： 
def load_bin(path, image_size):
  ..............
   img = mx.image.imdecode(_bin)
    img = nd.transpose(img, axes=(2, 0, 1))

Why training data is to subtract the mean and multiply by 0.0078, but why not tesing data?

**Comment by nttstar** [comment]
nd_mean is None.

**Comment by Edwardmark** [comment]
@nttstar so you do not subtract mean and multiply by 0.0078? Just use the original uint8 value or where you do the image normalization ?

**Comment by ImOmid** [comment]
Hi @nttstar,
I am also curious about why we did not normalize the input image while testing, do we? I couldn't find it in the codes.
