### ISSUE TITLE
Wild Anti-Spoofing dataset providing is stop?

### ISSUE THREAD

**Issue by ralpyna** [deepinsight/insightface#2461]
Hello,

I'm interested in Anti-Spoofing dataset. 
A month ago, I had submitted the application to get the permission of dataset.
But, I haven't received any contact. 
Do you still provide the dataset?

Thanks.

**Comment by nttstar** [comment]
Please submit the application according to this guideline: https://github.com/deepinsight/insightface/tree/master/challenges/cvpr23-fas-wild#updates

**Comment by ralpyna** [comment]
Thanks, nttstar.

**Comment by niujindacidian** [comment]
Hello,

I'm interested in Anti-Spoofing dataset.
Last week, I had submitted the application to get the permission of dataset  according to this guideline:
https://github.com/deepinsight/insightface/tree/master/challenges/cvpr23-fas-wild#updates

But, I haven't received any contact.
Do you still provide the dataset?

Thanks.

**Comment by nttstar** [comment]
@niujindacidian Have you included the e-mail address of wangdong?

**Comment by niujindacidian** [comment]
I submitted the application to insightface.challenge@gmail.com last week, and I submitted the application to wangdong@moredian.com this morning.

**Comment by nttstar** [comment]
OK please wait for the response.

**Comment by niujindacidian** [comment]
Okay, thank you.

**Comment by niujindacidian** [comment]
@nttstar I'm unable to extract the data(train,test_v2,dev) with the password provided in the email. Could you please update the password?
Regards.
