### ISSUE TITLE
License and Copyright??

### ISSUE THREAD

**Issue by Echolink50** [deepinsight/insightface#2466]
Trying to understand how to properly use this tech? I see the recent issues. So don't use Roop, Reactor, ect? Insight approved alternatives?  Give credit to insight face in a video? Is the issue with monetized videos? Is it the models or the code that's the issue? Thanks anyone that can clear this up.

**Comment by huyzer** [comment]
You referring to this issue?
https://www.youtube.com/watch?v=aOsr6zhjKtY

**Comment by Echolink50** [comment]
> You referring to this issue? https://www.youtube.com/watch?v=aOsr6zhjKtY

Yes that's where the issue was brought to my attention. Someone else asked in a post that was closed but the answers didn't have any solutions. I use all these ai things as a hobby but I would like some clarification.

**Comment by nttstar** [comment]
This YouTuber has not disclosed all the facts, including his one-on-one conversation with my partner Joey last night. He also continues to insist that all our assets are MIT's, which is clearly a misunderstanding. I don't intend to comment too much on this matter. The reason we have taken strict measures recently is that a large group of companies have been illegally using our model for commercial business.

**Comment by Nomad42022** [comment]
> This YouTuber has not disclosed all the facts, including his one-on-one conversation with my partner Joey last night. He also continues to insist that all our assets are MIT's, which is clearly a misunderstanding. I don't intend to comment too much on this matter. The reason we have taken strict measures recently is that a large group of companies have been illegally using our model for commercial business.

You're about to have a PR disaster, it takes less than 2 minutes to drop them a message asking them to take it down. Instead you harm the dudes livelihood and abuse YouTube's copyright system because you want to spite them? Complete scummy move.

**Comment by nttstar** [comment]
> You're about to have a PR disaster, it takes less than 2 minutes to drop them a message asking them to take it down. Instead you harm the dudes livelihood and abuse YouTube's copyright system because you want to spite them? Complete scummy move.

OK, then let my own open-sourced model harm me, fortunately, I am mentally strong enough. If it weren't for the issues of commercial misuse and deepfake abuse, I would even be happy to open source the best performing, highest resolution models. But reality isn't as I had anticipated.

**Comment by lviolal** [comment]
> > This YouTuber has not disclosed all the facts, including his one-on-one conversation with my partner Joey last night. He also continues to insist that all our assets are MIT's, which is clearly a misunderstanding. I don't intend to comment too much on this matter. The reason we have taken strict measures recently is that a large group of companies have been illegally using our model for commercial business.
> 
> You're about to have a PR disaster, it takes less than 2 minutes to drop them a message asking them to take it down. Instead you harm the dudes livelihood and abuse YouTube's copyright system because you want to spite them? Complete scummy move.

Totally agree with [Nomad42022](https://github.com/Nomad42022). Maybe contacting the community you value before commencing most dangerous legal actions against them would be wise. (This could have ended his channel and income!)

And as I'm uncertain as well now, can you please clarify what use is illegally exactly?

**Comment by nttstar** [comment]
> Totally agree with [Nomad42022](https://github.com/Nomad42022). Maybe contacting the community you value before commencing most dangerous legal actions against them would be wise. (This could have ended his channel and income!)
> 
> And as I'm uncertain as well now, can you please clarify what use is illegally exactly?
> 
> Because to cite your github main page: "The code of InsightFace is released under the MIT License. There is no limitation for both academic and commercial usage."

We have communicated with about 10 high-profile YouTubers about this matter, and they all agree with our perspective, except for Olivio. Regarding the licensing, Olivio also misled in his video, because there are two more lines below that sentence:

```
The training data containing the annotation (and the models trained with these data) are available for non-commercial research purposes only.

Both manual-downloading models from our github repo and auto-downloading models with our [python-library](https://github.com/deepinsight/insightface/blob/master/python-package) follow the above license policy(which is for non-commercial research purposes only).
```

**Comment by nttstar** [comment]
If you have any more questions, please leave a comment under that YouTube video. I have also made a response there.

**Comment by Alquitron** [comment]
> This YouTuber has not disclosed all the facts, including his one-on-one conversation with my partner Joey last night. He also continues to insist that all our assets are MIT's, which is clearly a misunderstanding. I don't intend to comment too much on this matter. The reason we have taken strict measures recently is that a large group of companies have been illegally using our model for commercial business.

Yes, surely the Youtuber has not told everything, and surely neither have you. I am not a recurring follower of this YouTuber but I have seen some of his videos and they are educational, simple and spread enthusiasm for these technologies. It's a shame that you jeopardized his channel and his income while he was praising your technology while channels that show less ethical uses of roop or reactor are still so blatant. In any case, if you offer a technology like this, I don't think it is ethical to go against the one who teaches how to use it, but rather against the one who creates the software that misuses it.

**Comment by nttstar** [comment]
@Alquitron Personally, I think such videos are in a gray area, between reasonable and unreasonable. However, my partner Joey believes that his videos involve the use of roop/reactor to deepfake well-known figures, which goes beyond purely technical content, hence the subsequent actions taken.

**Comment by lviolal** [comment]
> @Alquitron Personally, I think such videos are in a gray area, between reasonable and unreasonable. However, my partner Joey believes that his videos involve the use of roop/reactor to deepfake well-known figures, which goes beyond purely technical content, hence the subsequent actions taken.

Risking other's peoples careers on a 'believe' hence 'subsequent actions' were taken is one, let's say, bold move against a person that wanted to clearly promote your technology. 

And if the 'commercial use' is actually happened here is a very grey zone by the way, but I'm no attorney.

**Comment by lviolal** [comment]
> > Risking other's peoples careers on a 'believe' hence 'subsequent actions' were taken is one, let's say, bold move against a person that wanted to clearly promote your technology.
> > And if the 'commercial use' actually happened here is a very grey zone by the way, but I'm no attorney.
> 
> I don't think taking down two videos equates to jeopardizing a career, and they are even unrelated matters. People might think we are abusing copyright protection, but in reality, we are the weaker party in this situation. Olivio can use his influence and number of followers to broadcast his personal views through his videos, but we cannot.

I really don't want to dwell on this further. Just a [link to the youtoube strike policy for you](https://support.google.com/youtube/answer/2802032?hl=en-GB). 
As you can see you are not the weaker party, especially not if you reach out to the community, like those youtubers, and ask for promotion.

**Comment by nttstar** [comment]
An interesting thing is that Olivio has hidden my comments under his YouTube video, so none of you can see them. What is he afraid of? You can guess; I have no idea.

**Comment by opensourcefan** [comment]
128 was released to the Internet for all use.

A desperate effort was then made to do what no one has been able to do yet, turn back time. 

128 was no longer made available by you. 

Then some form of licensing was established. 

IMO, your legal claims to 128 and its licensing are only what existed at the time of dissemination. 

So this is why I personally am having an issue with this. You're moving the goal posts and expecting everyone to follow in line. That's not how the law works and it's not how the Internet works. 

If I haven't interpreted the amendment history correctly I apologize.

**Comment by nttstar** [comment]
> 128 was released to the Internet for all use.
> 
> A desperate effort was then made to do what no one has been able to do yet, turn back time.
> 
> 128 was no longer made available by you.
> 
> Then some form of licensing was established.
> 
> IMO, your legal claims to 128 and its licensing are only what existed at the time of dissemination.
> 
> So this is why I personally am having an issue with this. You're moving the goal posts and expecting everyone to follow in line. That's not how the law works and it's not how the Internet works.
> 
> If I haven't interpreted the amendment history correctly I apologize.

The model was open-sourced in November 2022, and our open-source license was established in 2020 and has never changed. You don't need to apologize, just need to check our GitHub commit history.

**Comment by DLohn** [comment]
For the purposes of preservation, here is the response on Olivio's video.
@nttstar Even after your recent edit, you still claim that Olivio insists all your assets are MIT license, but at 1:42 he acknowledges the noncommercial use restriction and specifically states that it applies to the extensions using inswapper128.
![if_response](https://github.com/deepinsight/insightface/assets/41272253/312db4da-f4c4-426c-bd71-2130049ba329)

**Comment by nttstar** [comment]
@DLohn Check his new post here: https://github.com/deepinsight/insightface/issues/2468

**Comment by tpcdaz** [comment]
> This YouTuber has not disclosed all the facts, including his one-on-one conversation with my partner Joey last night. He also continues to insist that all our assets are MIT's, which is clearly a misunderstanding. I don't intend to comment too much on this matter. The reason we have taken strict measures recently is that a large group of companies have been illegally using our model for commercial business.

Your license states MIT Licence. So yes. It is MIT

**Comment by tpcdaz** [comment]
> > Risking other's peoples careers on a 'believe' hence 'subsequent actions' were taken is one, let's say, bold move against a person that wanted to clearly promote your technology.
> > And if the 'commercial use' actually happened here is a very grey zone by the way, but I'm no attorney.
> 
> I don't think taking down two videos equates to jeopardizing a career, and they are even unrelated matters. People might think we are abusing copyright protection, but in reality, we are the weaker party in this situation. Olivio can use his influence and number of followers to broadcast his personal views through his videos, but we cannot.

Youtube operate on a 3 strikes and you're out rule. Meaning fake strikes that you filed can harm the livelihood of people

**Comment by nttstar** [comment]
> > This YouTuber has not disclosed all the facts, including his one-on-one conversation with my partner Joey last night. He also continues to insist that all our assets are MIT's, which is clearly a misunderstanding. I don't intend to comment too much on this matter. The reason we have taken strict measures recently is that a large group of companies have been illegally using our model for commercial business.
> 
> Your license states MIT Licence. So yes. It is MIT

OK you win(I'm not saying you're right)

**Comment by Echolink50** [comment]
I was just looking for clarification on how to use this properly but it just turned into an argument. I don't need any info on the situation with Sarakis. I am trying to understand how to use this? So don't use Roop, Reactor, ect? Insight approved alternatives? Give credit to insight face in a video? Is the issue with monetized videos? Is it the models or the code that's the issue?

**Comment by tpcdaz** [comment]
> I was just looking for clarification on how to use this properly but it just turned into an argument. I don't need any info on the situation with Sarakis. I am trying to understand how to use this? So don't use Roop, Reactor, ect? Insight approved alternatives? Give credit to insight face in a video? Is the issue with monetized videos? Is it the models or the code that's the issue?

If I was you I would avoid all insightface projects since they have clearly shown they are willing to ignore the licences put in front of them. Protect yourself and use alternatives in your videos. I see no reason why anyone at this point would adverrtise anything from Insightface.

**Comment by Echolink50** [comment]
> > 
> 
> If I was you I would avoid all insightface projects since they have clearly shown they are willing to ignore the licences put in front of them. Protect yourself and use alternatives in your videos. I see no reason why anyone at this point would adverrtise anything from Insightface.

Thanks for the advise. Which alternatives would you recommend?

**Comment by tpcdaz** [comment]
> > > 
> > 
> > 
> > If I was you I would avoid all insightface projects since they have clearly shown they are willing to ignore the licences put in front of them. Protect yourself and use alternatives in your videos. I see no reason why anyone at this point would adverrtise anything from Insightface.
> 
> Thanks for the advise. Which alternatives would you recommend?

Try IP adapter through Control Net. Maybe they are more ethical then InsightFace.

**Comment by tuftkyle** [comment]
> @Alquitron Personally, I think such videos are in a gray area, between reasonable and unreasonable. However, my partner Joey believes that his videos involve the use of roop/reactor to deepfake well-known figures, which goes beyond purely technical content, hence the subsequent actions taken.

Is Joey not aware that your own [InsightFace twitter account ](https://twitter.com/InsightFace_ai) currently presents your projects using celebrity deepfakes?

I count:
* 2 of Emma Watson
* 2 of Anne Hathaway
* 2 of Taylor Swift
* 1 of Leonardo DiCaprio
* 1 of Tom Hiddleston

@nttstar can you comment?

**Comment by nttstar** [comment]
> > @Alquitron Personally, I think such videos are in a gray area, between reasonable and unreasonable. However, my partner Joey believes that his videos involve the use of roop/reactor to deepfake well-known figures, which goes beyond purely technical content, hence the subsequent actions taken.
> 
> Is Joey not aware that your own [InsightFace twitter account ](https://twitter.com/InsightFace_ai) currently presents your projects using celebrity deepfakes?
> 
> I count:
> 
> * 2 of Emma Watson
> * 2 of Anne Hathaway
> * 2 of Taylor Swift
> * 1 of Leonardo DiCaprio
> * 1 of Tom Hiddleston
> 
> @nttstar can you comment?

This is not u, fake account. I already informed about this in the Discord community a few months ago

**Comment by nttstar** [comment]
u -> us, I dont want to edit the above answer.

**Comment by tuftkyle** [comment]
> This is not u, fake account. I already informed about this in the Discord community a few months ago

Can you inform us then what Joey's doing to take down this fake account? I assume this issue, if this is serious enough to warrant Youtube copyright strikes, means you would take this even more seriously?
