### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by codster17** [deepinsight/insightface#2476]
from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)

I get this when importing insightface

**Comment by yuukisaber** [comment]
I have encountered the same problem, could you please tell me how you solved it

**Comment by codster17** [comment]
> I have encountered the same problem, could you please tell me how you solved it

Can you paste the code producing the error. I don`t have access to the project.
