### ISSUE TITLE
Can buffalo_* models be used in production application?

### ISSUE THREAD

**Issue by Manideep0425** [deepinsight/insightface#2486]
I'm developing face recognition application for login purpose(internal applications only)  and using buffalo_l model. 
Can I use this model used in production?

**Comment by nttstar** [comment]
No, all open source models from our repo are for non-commercial research purposes only.

**Comment by RajbirSehrawat** [comment]
@nttstar then which model can we use for our application. can you please suggest some model name like buffalo s or l. in speed and accuracy.
