### ISSUE TITLE
ComfyUI - ModuleNotFoundError: No module named 'insightface.app'

### ISSUE THREAD

**Issue by RyujiTomita** [deepinsight/insightface#2509]
Hello,

I am running into issues running ComfyUI where I get the error below

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 527, in load_insight_face
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface.app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 529, in load_insight_face
    raise Exception(e)
Exception: No module named 'insightface.app'

When I run 
pip show insightface I get this result

:\ComfyUI_windows_portable\ComfyUI\custom_nodes>pip show insightface
Name: insightface
Version: 0.7.3
Summary: InsightFace Python Library
Home-page: https://github.com/deepinsight/insightface
Author: InsightFace Contributors
Author-email: [contact@insightface.ai](mailto:contact@insightface.ai)
License: MIT
Location: C:\Users\AppData\Roaming\Python\Python311\site-packages
Requires: albumentations, cython, easydict, matplotlib, numpy, onnx, Pillow, prettytable, requests, scikit-image, scikit-learn, scipy, tqdm

**Comment by RyujiTomita** [comment]
had incorrect Folder inside my ComfyUI Custom nodes. I have the main folder while it worked immediately when I only installed the folder inside the Python_package https://github.com/deepinsight/insightface/tree/master/python-package

**Comment by AIBASE150** [comment]
@RyujiTomita : I'm having the same issue with my ComfyUI. Can you please explain the solution more in detail? I'm afraid that I didn't understand "when I only installed the folder inside the Python_package". What is that Package? And where do I find it? Thanks!

**Comment by connectionsearthly-glitch** [comment]
Download and install: pip install insightface-0.7.3-cp312-cp312-win_amd64.whl
https://github.com/skippzz/insightface-0.7.3-cp312-cp312-win_amd64.git

Change the cp312 into your python version
