### ISSUE TITLE
Inference with batching in mind

### ISSUE THREAD

**Issue by Neltherion** [deepinsight/insightface#253]
@nttstar 

Hi

First of all thanks for your support in the issues section. I had a question regarding the possibility to batch multiple images for faster inference:

**Is it possible to get the embedding of many images in one go instead of repeatedly calling the `get_feature` method?**

My inference time for just one cropped image is nearly 20ms per image but I was wondering if this time could be reduced for batches of images.

I wrote a code to initialize the Model with variable `batch_size`s (I used 10, 25 and 50) and fed `self.model.forward(db)` with a list of cropped and aligned images (between 100 or a 1000 images) but two strange things happened:

1. The inference time increased when passing `n` images to it compared to when I called `get_feature` repeatedly `n` times.

2. No matter how much I changed the `batch_size` (from 1 to 50), the inference time stayed near 30 ms per image.

I'm more familiar with Tensorflow than MXNet and I was wondering if I'm doing something wrong with these parts of the code:

```
data = mx.nd.array(aligned_face_images)
db = mx.io.DataBatch(data=(data,))
self.model.forward(db)
```

**Comment by nttstar** [comment]
Try referring to `src/utils/benchmark.py`. 
Commonly you could get >5x performance increase by doing batch inferencing.

**Comment by Neltherion** [comment]
@nttstar Thanks for the fast response. I'll check it out and let you know.

**Comment by nmzszxsl01** [comment]
@Neltherion 
How about the inference time now. Does it go faster?
If so, how did you change the code?

**Comment by alighofrani95** [comment]
@Neltherion @nmzszxsl01 @nttstar 
How can I access src/utils/benchmark.py ?
There is no benchmark.py in the repo.
