### ISSUE TITLE
Copyright question

### ISSUE THREAD

**Issue by hsiutayu** [deepinsight/insightface#2534]
Is it okay to make a website that lets users upload their photos and create profile images, but I'm not charging them anything?

**Comment by nttstar** [comment]
No, building a website is a commercial activity in itself, regardless of whether there is explicit charging for the service. It is also not for academic purposes.

**Comment by hsiutayu** [comment]
Gotcha

**Comment by mike-hearn** [comment]
> building a website is a commercial activity in itself, regardless of whether there is explicit charging for the service

This isn't right. If there is no attempt to monetize the site (e.g. through payment, ads, referrals or using it as a marketing tool for another commercial site) it is considered non-commercial.

**Comment by nttstar** [comment]
I won't argue about these things, it's pointless, no one would just pay for server costs out of their own pocket to provide services for free. Besides, either way, this kind of behavior is not for academic purposes.
