### ISSUE TITLE
Failed downloading url 

### ISSUE THREAD

**Issue by codewithdark-git** [deepinsight/insightface#2573]
71         r = requests.get(url, stream=True)
     72         if r.status_code != 200:
---> 73             raise RuntimeError("Failed downloading url %s" % url)
     74         total_length = r.headers.get('content-length')
     75         with open(fname, 'wb') as f:

RuntimeError: Failed downloading url [https://github.com/deepinsight/insightface/releases/download/v0.7/./checkpoints/inswapper_128.onnx.zip](https://github.com/deepinsight/insightface/releases/download/v0.7/checkpoints/inswapper_128.onnx.zip)

how to solve this Error please help...

**Comment by paulocoutinhox** [comment]
Hi,

It is here: https://huggingface.co/ezioruan/inswapper_128.onnx/tree/main
