### ISSUE TITLE
Pricing of  Buffalo Model

### ISSUE THREAD

**Issue by RajbirSehrawat** [deepinsight/insightface#2587]
As it mentioned in document the Buffalo se, l models are only for non commercial purpose only. But this library insight face is open source. 

So we can use this library for our clients. 

how t purchase the license of buffalo models

or pls suggest any other open source mode like buffalo models.

**Comment by SpaceWarpStudio** [comment]
I would also be very interested in this information. What are your commercial licensing options?

**Comment by moulichand1622** [comment]
i am also searching the all the relevant issues in insightface repo for knowing the pricing of buffalo_l model for commercial purpose. would be helpful for many people if you reply.

**Comment by nttstar** [comment]
Please use your business email address to send an email to contact@insightface.ai
