### ISSUE TITLE
Pre trained model LFW test

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#259]
Hi,

I would like to test  LResNet50E-IR@BaiduDrive,  which is shown %99.80 accuracy in the readme.

I tried to use deploy / test.py but it gives error.

What is the basic baby step to use this LResNet50E-IR@BaiduDrive model to test to images similarity ? I could help other beginners ..

thx

**Comment by goodpp** [comment]
这里有个Http接口，可以比较图片的相似度
src/api/app.py

**Comment by yunchangxiaoguan** [comment]
> 这里有个Http接口，可以比较图片的相似度
> src/api/app.py

大佬，请问一下这个接口怎么用啊，我用postman发送post一直报错，不知道怎么传图片进去
