### ISSUE TITLE
how to do mtcnn crop before running test.py

### ISSUE THREAD

**Issue by zhenglaizhang** [deepinsight/insightface#26]
per the code in `deploy/test.py`: 
```python
parser.add_argument('--image-size', default='112,112', help='')
```

it seems that the input should be cropped as square with width as 112, however the mtcnn output may be rectangle, I thought the detailed steps to run `test.py` are as below:

1. use mtcnn to crop the face images with margin 44
2. resize cropped face to 112x112
3. run `test.py` and the script will do face alignment with mtcnn

I am curious if my understanding is wrong, I thought the alignment before resizing should be more reliable?

**Comment by nttstar** [comment]
There's no limit of input image size,  112,112 is the data shape config of recognition network.

**Comment by zhenglaizhang** [comment]
sounds great, thanks for the quick response!
