### ISSUE TITLE
Error in downloading buffalo_l inside docker container

### ISSUE THREAD

**Issue by Prathamesh314** [deepinsight/insightface#2611]
When I am running insightface application inside my Docker container, it is showing error that url for downloading buffalo_l model is wrong and my code breaks there.

But when I run it locally it works absolutely fine and also downloads buffalo_l model from correct url, it is giving me issue only when I am running it inside my docker container.

Here are the images to describe my issue:-

1. Dockerfile:-

![image](https://github.com/user-attachments/assets/474130f2-7bf8-4bee-99b3-f3bbcd135fc0)

2. Error:-

 /root/.insightface/models/buffalo_l.zip from http://insightface.cn-sh2.ufileos.com/models/buffalo_l.zip...
    face_analysis_app = FaceAnalysis(name='buffalo_l', providers=providers, download=False, download_zip=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/insightface/app/face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/insightface/utils/storage.py", line 30, in ensure_available
    return download(sub_dir, name, force=False, root=root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/insightface/utils/storage.py", line 19, in download
    download_file(model_url,
  File "/usr/local/lib/python3.12/site-packages/insightface/utils/download.py", line 73, in download_file
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url http://insightface.cn-sh2.ufileos.com/models/buffalo_l.zip

**Comment by Prathamesh314** [comment]
I have been trying to fix this from last few days, but I was unable to find the root cause why is this error is happening.

Whether my dockerfile is incorrect or something else, I don't know.

please help.

**Comment by Prathamesh314** [comment]
issue is solved. 
I was installing old version of insightface.

We need to install latest version of insigtface and onnxruntime.

The app worked fine

**Comment by GZ-Alinx** [comment]
nice, your issue solve for slef.

**Comment by big-lilijiang** [comment]
thanks，this is useful to me
