### ISSUE TITLE
Failed downloading antelopev2.zip

### ISSUE THREAD

**Issue by chany-king** [deepinsight/insightface#2619]
** Platform: Windows
** Python version: 3.11.6
** CUDA Version: 12.2 
** Total VRAM 12282 MB, total RAM 65304 MB
** pytorch version: 2.3.0+cu121
** xformers version: 0.0.26.post1
** Set vram state to: NORMAL_VRAM
** Disabling smart memory management
** Device: cuda:0 NVIDIA GeForce RTX 4070 : native
** Using xformers cross attention
---------------------------------

I referred to Antelope v2 unable to download # 2517 and tried placing Antelopev2.zip in : 
ComfyUI \ models \ insightface \, 
or \ ComfyUI \ models \ insightface \ models, 
or \ ComfyUI \ models \ insightface \ antelopev2 separately\

I tried both decompressing and not decompressing, but when running comfyui, it still prompts：
【 Runtime Error: Failed downloading URL ' https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip
Prompt executed in 0.97 seconds】

If you have time, please help me analyze how to solve it. Thank you!

**Comment by Lilien86** [comment]
Hey, I have exactly the same issue

**Comment by williamqian** [comment]
me too
