### ISSUE TITLE
Apart from human faces, can this model apply to recognition of other objects?

### ISSUE THREAD

**Issue by guanshantingbai** [deepinsight/insightface#2626]
There is a dataset of stones I would like to train a model. I wonder if this model will be suitable for recognizing these stones, and here is an example:
![15_13_08_sideview_day1](https://github.com/user-attachments/assets/11ab3112-2e1b-4d93-9ca5-3fb2ad6a6439)

**Comment by Mr-Nobody-dey** [comment]
No. This is only trained to detect human faces. Try yolo.

**Comment by guanshantingbai** [comment]
> No. This is only trained to detect human faces. Try yolo.

thank you very much
