### ISSUE TITLE
Couldn't upload models to ICCV21-MFR

### ISSUE THREAD

**Issue by codonna9** [deepinsight/insightface#2649]
I haven't been able to upload the zip files of the models to ICCV21-MFR for a few days now. It looks like the server doesn't respond to the upload request. Can you please check if the server is still running?

Thanks a lot for providing this very useful service.

**Comment by nttstar** [comment]
Restarted, you can try again.

**Comment by codonna9** [comment]
Thanks a lot. I tried to upload models in my computer network but it still fails. I'll try to upload models using another Internet provider this weekend

**Comment by codonna9** [comment]
@nttstar 
I tried another Internet provider over the weekend but I couldn't even login. That is, when I clicked the "Sign-in" button, the website didn't go to the Leaderboard page. It just stayed in the login page indefinitely. I tried my company's Internet again today but I still couldn't upload the model to the server. Do you know if other people have been successful in uploading and evaluating models recently?

**Comment by nttstar** [comment]
Yes, I saw some model submission history in the backend.

**Comment by codonna9** [comment]
Thanks a lot. I'll try to use another Internet provider and probably use some proxies to see if I have any luck in the next few days. I'll let you know when I got this done

**Comment by codonna9** [comment]
I tried another Internet provider and it worked. Thanks so much for your help
