### ISSUE TITLE
通过lst生成rec

### ISSUE THREAD

**Issue by zhaowwenzhong** [deepinsight/insightface#265]
我利用mxnet\trunk\tools\im2rec.py生成lst文件
再利用这lst文件，通过insightface\trunk\src\data\face2rec2.py 生成rec文件
是否要修改这些地方，insightface\trunk\src\train_softmax.py读取数据。
1、insightface\trunk\src\common\face_preprocess.py
def parse_lst_line(line):
  vec = line.strip().split("\t")
  assert len(vec)>=3
  aligned = int(vec[0])
  image_path = vec[1]
  label = int(vec[2])
  bbox = None
  landmark = None
。。。
修改为：
def parse_lst_line(line):
  vec = line.strip().split("\t")
  assert len(vec)>=3
  aligned = True#int(vec[0])
  image_path = vec[2]
  label = int(float(vec[1]))
  bbox = None
  landmark = None

2、insightface\trunk\src\data\face2rec2.py

def read_list(path_in):
    path_ = path_in[:-4]        #获取文件所在目录
    with open(path_in) as fin:
        identities = []
        last = [-1, -1]
        _id = 1
        while True:
            line = fin.readline()
            if not line:
                break
            item = edict()
            item.flag = 0
            item.image_path, label, item.bbox, item.landmark, item.aligned = face_preprocess.parse_lst_line(line)
            item.image_path = os.path.join(path_, item.image_path)             #图片路径
            if not os.path.exists( item.image_path):
                continue
            if not item.aligned and item.landmark is None:
              #print('ignore line', line)
              continue
            item.id = _id
            item.label = [label, item.aligned]  => item.label = label        #label

**Comment by nttstar** [comment]
是的 image_path和label换一下位置

**Comment by DuckJ** [comment]
> 我利用mxnet\trunk\tools\im2rec.py生成lst文件
> 再利用这lst文件，通过insightface\trunk\src\data\face2rec2.py 生成rec文件
> 是否要修改这些地方，insightface\trunk\src\train_softmax.py读取数据。
> 1、insightface\trunk\src\common\face_preprocess.py
> def parse_lst_line(line):
> vec = line.strip().split("\t")
> assert len(vec)>=3
> aligned = int(vec[0])
> image_path = vec[1]
> label = int(vec[2])
> bbox = None
> landmark = None
> 。。。
> 修改为：
> def parse_lst_line(line):
> vec = line.strip().split("\t")
> assert len(vec)>=3
> aligned = True#int(vec[0])
> image_path = vec[2]
> label = int(float(vec[1]))
> bbox = None
> landmark = None
> 
> 2、insightface\trunk\src\data\face2rec2.py
> 
> def read_list(path_in):
> path_ = path_in[:-4] #获取文件所在目录
> with open(path_in) as fin:
> identities = []
> last = [-1, -1]
> _id = 1 while True: line = fin.readline() if not line: break item = edict() item.flag = 0 item.image_path, label, item.bbox, item.landmark, item.aligned = face_preprocess.parse_lst_line(line) item.image_path = os.path.join(path_, item.image_path) #图片路径
> if not os.path.exists( item.image_path):
> continue
> if not item.aligned and item.landmark is None:
> #print('ignore line', line)
> continue
> item.id = _id
> item.label = [label, item.aligned] => item.label = label #label

hello ,can you help me?
when I use my own dataset (total 20000 images)to create the lst and rec file, I am confused.  My train.lst like 
`1   /home/duckj/.../1.jpg 0`
`1 /home/duckj/.../2.jpg 0`
`...`
means aligned \t path\t label, and copy into path **src/data/**
Then I make a **property** file ,means 9980 classes in the dataset,and the aligned size is 112 112.
`9980,112,112`
when I use **src/data/face2rec2.py** ,run
`python face2rec.py .`
I get the train.rec and train.idx, but in the train.idx, it has 29981 rows, why is not 20000?
and when i run recognition/train.py, why the log print the id2range more than 9980?https://github.com/deepinsight/insightface/blob/master/recognition/image_iter.py#L58
Where did I go wrong?
Can you give me some advices? 
Whether I need to change the face2rec2.py
> item.label = [label, item.aligned] => item.label = label #label

**Comment by ctgushiwei** [comment]
@DuckJ 你好，请问你的问题解决了吗
