### ISSUE TITLE
How to construct triplet dataset?

### ISSUE THREAD

**Issue by rockstone533** [deepinsight/insightface#268]
`
    anchor = mx.symbol.slice_axis(nembedding, axis=0, begin=0, end=args.per_batch_size//3)
    positive = mx.symbol.slice_axis(nembedding, axis=0, begin=args.per_batch_size//3, end=2*args.per_batch_size//3)
    negative = mx.symbol.slice_axis(nembedding, axis=0, begin=2*args.per_batch_size//3, end=args.per_batch_size)`

As your code in train.py, should I construct my data in each batch by the format that the first 1/3 are anchor samples, then positive samples, and the last 1/3 are negative samples? @nttstar

**Comment by nttstar** [comment]
check my new triplet training code.
