### ISSUE TITLE
How to load images from an image list instead of an image rec ?

### ISSUE THREAD

**Issue by shaohuawan** [deepinsight/insightface#269]
I know that image rec is fast to load, but I need to load training images from image list file.

Is this currently supported ? If not, will this be supported in the future ?

Thanks!

**Comment by chinakook** [comment]
If a folder contains many images, to read images from that folder is too slower to feed training. The best method is that build a single big file from shuffled images and then sequentially read images in training.

**Comment by shaohuawan** [comment]
@chinakook  I completely agree with you that rec is fast and image list is slow. But I'm in a situation in which reading from an image list is considered to be the best.

**Comment by hjy1312** [comment]
Referred to a before answer in a similar issue，my code is:
from mxnet import recordio
import mxnet as mx
import os
import os.path as osp
#import matplotlib.pyplot as plt
import cv2
path_imgidx = './train.idx'
path_imgrec = './train.rec'

des_dir = './ms-celeb-1m-arcface'
if not osp.exists(des_dir):
    os.makedirs(des_dir)
f_out = open('./training_list.txt','w')
imgrec = recordio.MXIndexedRecordIO(path_imgidx, path_imgrec, 'r')
#1 ~ 3804847
for i in range(3804846):
    print('processing %d th image' %(i+1))
    header, s = recordio.unpack(imgrec.read_idx(i+1))
    img = mx.image.imdecode(s).asnumpy()
    img[:,:,[0,2]] = img[:,:,[2,0]]
    save_path = osp.join(des_dir,str(i+1) + '.jpg') 
    cv2.imwrite(save_path,img)
    f_out.writelines([save_path, ' ', str(header.label), '\n'])
f_out.close()
