### ISSUE TITLE
Regarding facescrub overlapped identities

### ISSUE THREAD

**Issue by lucwan** [deepinsight/insightface#27]
Hello,

Ca you please give us/upload the 500+ overlap between facescrub identities and ms1m
also when can you upload the megface distractor noise list ?

Thanks,
Gsquared

**Comment by nttstar** [comment]
No, they were already removed in my provided dataset.

**Comment by lucwan** [comment]
I want to remove the overlap from the list ms1m_clean_list.txt provided by you. Do you have overlapping identity names for this list?

**Comment by nttstar** [comment]
I removed them by comparing the center vectors of all identities. Removing by name is unpractical.  See my script at `src/data/dataset_merge.py`

**Comment by lucwan** [comment]
i understood that you removed them by comparing the center vectors of all identities, but do you have the list if identities from msceleb1m that were removed using this process ?

**Comment by nttstar** [comment]
No, I do not record the name.
