### ISSUE TITLE
关于predict和deploy/test.py

### ISSUE THREAD

**Issue by mengzhibin** [deepinsight/insightface#270]
有哪位大佬可以给出这两个的具体使用方法，比如test的时候
'--model', default='', help='path to load model.'
'--ga-model', default='', help='path to load model.'
两个参数，哪个是使用训练好的模型路径，那另外一个model路径是什么，是指的mtcnn-dodel路径地下的文件吗？

**Comment by zhcroman** [comment]
--model   相似度模型
--ga-model   性别年龄模型
