### ISSUE TITLE
C++ SDK加载模型时失败

### ISSUE THREAD

**Issue by junanxia** [deepinsight/insightface#2704]
使用交叉编译的C++ SDK在RV1106 ARMv7设备上无法加载模型（Gundam_RV1109、Megatron、Pikachu都不能加载），编译的测试程序也同样无法加载，HFLaunchInspireFace函数返回1361，提示错误信息如下，模型文件从官方提供的网盘文件test_res.zip(https://drive.google.com/drive/folders/1krmv9Pj0XEZXR1GRPHjW_Sl7t4l0dNSS?usp=sharing)中提取得到。
[root@luckfox home]# ./FaceRecognitionSample test_res/pack/Pikachu
opencv-mobile HW JPG encoder with rk mpp
opencv-mobile HW JPG encoder with rk mpp
[simple_archive.h][47]: Invalid archive file: -7
Load Resource error: 1361
[root@luckfox home]# ./FaceRecognitionSample test_res/pack/Gundam_RV1109
opencv-mobile HW JPG encoder with rk mpp
opencv-mobile HW JPG encoder with rk mpp
[simple_archive.h][47]: Invalid archive file: -7
Load Resource error: 1361
[root@luckfox home]# ./FaceRecognitionSample test_res/pack/Megatron
opencv-mobile HW JPG encoder with rk mpp
opencv-mobile HW JPG encoder with rk mpp
[simple_archive.h][47]: Invalid archive file: -7
Load Resource error: 1361

硬件环境：LuckFox Pico Max, RV1106, ARMv7, buildroot 
编译环境：WSL2 Ubuntu 20.04.6 LTS,  工具链arm-rockchip830-linux-uclibcgnueabihf，OpenCV-mobile 4.8.1

**Comment by junanxia** [comment]
开启脚本中-DISF_BUILD_WITH_TEST=ON, 后使用测试程序的输出日志如下：
[root@luckfox home]# ./Test
opencv-mobile HW JPG encoder with rk mpp
opencv-mobile HW JPG encoder with rk mpp
2021-01-01 14:26:17.170 [Test Message] ===> Using default test dir: test_res
2021-01-01 14:26:17.171 [Test Message] ===> Using default global Pack: Pikachu
test_res/pack/Pikachu
[simple_archive.h][47]: Invalid archive file: -7
[2021-01-01 14:26:17.176] [error] An error occurred while starting InspireFace: 1361
[root@luckfox home]# ./TestSource
opencv-mobile HW JPG encoder with rk mpp
opencv-mobile HW JPG encoder with rk mpp
[simple_archive.h][47]: Invalid archive file: -7
Load error

**Comment by junanxia** [comment]
@nttstar @tunmx 另外请问一下大神，数据包里的模型和python版的onnx模型是什么关系，通过什么方法可以转换。多有打扰！

**Comment by tunmx** [comment]
收到，我这边检查一下

**Comment by tunmx** [comment]
请问你编译的版本是什么，可以把你编译的cmake option展示一下吗

**Comment by junanxia** [comment]
修改了build_cross_rv1109rv1126_armhf.sh脚本文件，其它参数均未修改

export ARM_CROSS_COMPILE_TOOLCHAIN=/opt/toolchain/arm-rockchip830-linux-uclibcgnueabihf
cmake -DCMAKE_SYSTEM_NAME=Linux \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_SYSTEM_VERSION=1 \
  -DCMAKE_SYSTEM_PROCESSOR=armv7 \
  -DCMAKE_C_COMPILER=$ARM_CROSS_COMPILE_TOOLCHAIN/bin/arm-rockchip830-linux-uclibcgnueabihf-gcc \
  -DCMAKE_CXX_COMPILER=$ARM_CROSS_COMPILE_TOOLCHAIN/bin/arm-rockchip830-linux-uclibcgnueabihf-g++ \
  -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -flax-vector-conversions" \
  -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -std=gnu99" \
  -DTARGET_PLATFORM=armlinux \
  -DISF_BUILD_LINUX_ARM7=ON \
  -DISF_ENABLE_RKNN=ON \
  -DISF_RK_DEVICE_TYPE=RV1106 \
  -DISF_BUILD_WITH_SAMPLE=ON \
  -DISF_BUILD_WITH_TEST=ON \
  -DISF_ENABLE_BENCHMARK=OFF \
  -DISF_ENABLE_USE_LFW_DATA=OFF \
  -DISF_ENABLE_TEST_EVALUATION=OFF \
  -DISF_BUILD_SHARED_LIBS=ON ${SCRIPT_DIR}

**Comment by junanxia** [comment]
junan@DESKTOP-UD8IPDQ:~/insightface-master/cpp-package/inspireface$ bash command/build_cross_rv1109rv1126_armhf.sh
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /opt/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/arm-rockchip830-linux-uclibcgnueabihf-gcc
-- Check for working C compiler: /opt/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/arm-rockchip830-linux-uclibcgnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/arm-rockchip830-linux-uclibcgnueabihf-g++
-- Check for working CXX compiler: /opt/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/arm-rockchip830-linux-uclibcgnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use rknpu2
The OpenCV that builds the gnueabihf version depends on is specialized!
-- Found OpenCV: /home/junan/insightface-master/cpp-package/inspireface/3rdparty/inspireface-precompile/opencv/4.10.0 (found version "4.10.0")
Default or fallback case for MNN setup
-- The ASM compiler identification is GNU
-- Found assembler: /opt/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/arm-rockchip830-linux-uclibcgnueabihf-gcc
CMake Warning at 3rdparty/MNN/CMakeLists.txt:69 (message):
  Close MNN_SEP_BUILD for static library


-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Linux
--      Processor: armv7
--      Version: 2.8.2
--      Metal: OFF
--      OpenCL: OFF
--      OpenGL: OFF
--      Vulkan: OFF
--      ARM82: OFF
--      oneDNN: OFF
--      TensorRT: OFF
--      CoreML: OFF
--      NNAPI: OFF
--      CUDA: OFF
--      OpenMP: OFF
--      BF16:
--      ThreadPool: ON
--      Hidden: TRUE
--      Build Path: /home/junan/insightface-master/cpp-package/inspireface/build/inspireface-linux-armv7-rv1109rv1126-armhf/3rdparty/MNN
--      CUDA PROFILE: OFF
-- WIN_USE_ASM:
-- Enabling AArch32 Assemblies
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- InspireFace Core:
--       Version: 1.1.7
--       MNN_INCLUDE_DIRS: /home/junan/insightface-master/cpp-package/inspireface/3rdparty/MNN/include
--       MNN_LIBS: MNN
--       ENABLE_TRACKING_BY_DETECTION: OFF
--       ISF_BUILD_SHARED_LIBS: ON
--       ISF_ENABLE_RKNN: ON
--       ISF_RKNN_API_INCLUDE_DIRS: /home/junan/insightface-master/cpp-package/inspireface/3rdparty/inspireface-precompile/rknn/rknpu2/runtime/RV1106/Linux/librknn_api/include
--       ISF_RKNN_API_LIB: /home/junan/insightface-master/cpp-package/inspireface/3rdparty/inspireface-precompile/rknn/rknpu2/runtime/RV1106/Linux/librknn_api/armhf/
-- InspireFace Sample:
--       ISF_BUILD_SAMPLE_CLUTTERED: OFF
Enable RKNN Inference
-- InspireFace Test:
--       ISF_ENABLE_BENCHMARK: OFF
--       ISF_ENABLE_USE_LFW_DATA: OFF
--       ISF_ENABLE_TEST_EVALUATION: OFF
-- InspireFace Project Global:
--       CMAKE_SYSTEM_NAME: Linux
--       CMAKE_BUILD_TYPE: Release
--       ISF_THIRD_PARTY_DIR: /home/junan/insightface-master/cpp-package/inspireface/3rdparty
--       ISF_SANITIZE_ADDRESS: OFF
--       ISF_SANITIZE_LEAK: OFF
--       ISF_ENABLE_RKNN: ON
--       ISF_RKNPU_MAJOR: rknpu2
--       ISF_RK_DEVICE_TYPE: RV1106
--       ISF_BUILD_LINUX_ARM7: ON
--       ISF_BUILD_LINUX_AARCH64: OFF
--       ISF_BUILD_WITH_TEST: ON
--       ISF_BUILD_WITH_SAMPLE: ON
--       OpenCV_DIR: /home/junan/insightface-master/cpp-package/inspireface/3rdparty/inspireface-precompile/opencv/4.10.0/lib/cmake/opencv4
--       CMAKE_INSTALL_PREFIX: /home/junan/insightface-master/cpp-package/inspireface/build/inspireface-linux-armv7-rv1109rv1126-armhf/install
-- Configuring done
-- Generating done

**Comment by junanxia** [comment]
另外cpp-package/inspireface下的CMakeLists.txt，替换了Opencv为预编译的Opencv-mobile(https://github.com/nihui/opencv-mobile/releases/latest/download/opencv-mobile-4.10.0-luckfox-pico.zip)

131             if(ISF_BUILD_LINUX_ARM7)
132                 set(PLAT linux-arm7)
133                 message("The OpenCV that builds the gnueabihf version depends on is specialized!")
134                 #set(OpenCV_DIR ${ISF_THIRD_PARTY_DIR}/inspireface-precompile/opencv/3.4.5/opencv-linux-armhf/share/OpenCV)
135                 #set(OpenCV_STATIC_INCLUDE_DIR ${PATH_3RDPARTY}/inspireface-precompile/opencv/3.4.5/opencv-linux-armhf/include/)
136
137                 set(OpenCV_DIR ${ISF_THIRD_PARTY_DIR}/inspireface-precompile/opencv/4.10.0/lib/cmake/opencv4)
138                 set(OpenCV_STATIC_INCLUDE_DIR ${PATH_3RDPARTY}/inspireface-precompile/opencv/4.10.0/include/opencv4/)
139             elseif(ISF_BUILD_LINUX_AARCH64)
140                 set(PLAT linux-aarch64)
141                 message("The OpenCV that builds the aarch64 version depends on is specialized!")
142                 set(OpenCV_DIR ${ISF_THIRD_PARTY_DIR}/inspireface-precompile/opencv/3.4.5/opencv-linux-aarch64/share/OpenCV)
143                 set(OpenCV_STATIC_INCLUDE_DIR ${PATH_3RDPARTY}/inspireface-precompile/opencv/3.4.5/opencv-linux-aarch64/include/)
144                 # set(OpenCV_LIBS )
145             endif()

**Comment by tunmx** [comment]
SDK目前还没对RV1106进行适配，如果你需要在RV1106上部署，只能使用CPU版本搭配Pikachu或Megatron资源文件

**Comment by junanxia** [comment]
你指的CPU版本是指不开启RKNN加速吗？关闭RKNN出现的错误是相同的。

**Comment by tunmx** [comment]
已经添加指针RV1106的依赖，可以到develop仓库拉取项目进行测试：[https://github.com/HyperInspire/InspireFace/tree/feature/rv1106](https://github.com/HyperInspire/InspireFace/tree/feature/rv1106)

**Comment by junanxia** [comment]
新版本测试了一下，问题解决，暂未发现其它问题。

**Comment by oowwkk** [comment]
请问大神，你们在cmake编译C++检测时有没有遇到configure成功了，但是生成的时候报错缺失 Objects of target "inspirecv" referenced but no such target exists.的问题

<img width="1051" height="677" alt="Image" src="https://github.com/user-attachments/assets/49d65aa9-eddb-4f7f-b7e4-dceb8468f8d1" />

**Comment by junanxia** [comment]
你这个看着应该是在Windows上使用VS编译，官方文档的支持列表中似乎没有该选项，可能会有一些兼容性的问题。

**Comment by changeCPL** [comment]
> [@nttstar](https://github.com/nttstar) [@tunmx](https://github.com/tunmx) 另外请问一下大神，数据包里的模型和python版的onnx模型是什么关系，通过什么方法可以转换。多有打扰！

 [@nttstar](https://github.com/nttstar) [@tunmx](https://github.com/tunmx)  [@junanxia](https://github.com/junanxia) 同问，C++ SDK中用到的模型和python中的模型是什么关系？[model_zoo](https://github.com/deepinsight/insightface/tree/master/model_zoo)中是不是所有可用的模型？

**Comment by oowwkk** [comment]
> 你这个看着应该是在Windows上使用VS编译，官方文档的支持列表中似乎没有该选项，可能会有一些兼容性的问题。

是的，我想在Windows部署，遇到的这个问题

**Comment by junanxia** [comment]
> > [@nttstar](https://github.com/nttstar) [@tunmx](https://github.com/tunmx) 另外请问一下大神，数据包里的模型和python版的onnx模型是什么关系，通过什么方法可以转换。多有打扰！
> 
> [@nttstar](https://github.com/nttstar) [@tunmx](https://github.com/tunmx) [@junanxia](https://github.com/junanxia) 同问，C++ SDK中用到的模型和python中的模型是什么关系？[model_zoo](https://github.com/deepinsight/insightface/tree/master/model_zoo)中是不是所有可用的模型？

因为语言环境推理框架的不同，SDK里用的是应该是转换为MNN框架支持的版本，不排除做过一些额外的OP加工处理。
