### ISSUE TITLE
gpu memory used

### ISSUE THREAD

**Issue by xizi** [deepinsight/insightface#274]
![42222141-d519be74-7f06-11e8-9a68-d4535013702e](https://user-images.githubusercontent.com/3853150/42269333-752d7ca8-7fb0-11e8-80b1-7413a9b8c2a3.png)
When i train a classification network in multi-GPU style, the gpu0 memory is larger than others. Is a test network occupy the gpu0 memory. In that circumstances, how can i remove the test network ?

**Comment by nttstar** [comment]
It also includes gradients.
