### ISSUE TITLE
关于insightface/src/data/dataset_merge.py用来合并数据集

### ISSUE THREAD

**Issue by YunYang1994** [deepinsight/insightface#275]
您好，非常感谢您将程序开源。现在我在合并celebrity和msrc数据集时遇到这么一个问题：关于msrc数据集的.rec和.idx文件我已经下载得到，celebrity数据集我也使用face2rec2.py转化得到了.rec和.idx文件，使用的模型下载了model-r50-am-lfw，但是我没能使用dataset_merge.py将这两个数据集合并下来。请您指导一下，万分感谢！！！

**Comment by BUAA-21Li** [comment]
你好，我现在也想将两个.rec合并到一起，请问能告知一下怎么做吗？

**Comment by yang0817manman** [comment]
你好，同问，怎么将两个.rec合并到一起解决了吗？我也遇到同样问题，求指教。谢谢。 @BUAA-21Li @YunYang1994
