### ISSUE TITLE
Nearly dead neurons found in conv0

### ISSUE THREAD

**Issue by rocketbear** [deepinsight/insightface#277]
Hi there,

I find that many filters in conv0_weight have near-zero weights. For example, in the r50 model I trained, 34 out of the 64 filters have abs sum of weights < 1e-5, and the weakest filter have abs sum of weight < 1e-14.

The trained model behaves well though, reaching > 99.8 on lfw and >98.0 on agedb and cfp_fp, and reaching TPR>80%@FAR<1e-8 on one of my own testing dataset.

But problem happens when I try to convert the mxnet model to my own format for serving purpose. I have a light weighted inference library which does not support bn layers, so I have to merge the bn layers into the conv layers.  Since conv0 have many weak filters, and the following bn0 and stage1_unit1_bn1 try to normalize the very weak responses, using very small gamma and moving_var,  the order of computation matters. It is ok to merge bn0 into conv0, but it is problematic when merging stage1_unit1_bn1 into stage1_unit1_conv1, significant numerical errors will be produced after merging stage1_unit1_bn1 into stage1_unit1_conv1.

My problem can be bypassed by introducing the bn layer into my inference library so that the first bn in each residual block is left as it is. But I think these nearly dead neurons are worthy of further investigation.

**Comment by nttstar** [comment]
Thanks!
