### ISSUE TITLE
optimal m: m = 0.5   but why ? Any thoughts behind experiments result ? 

### ISSUE THREAD

**Issue by hustzeyu** [deepinsight/insightface#280]
I have trained my own model and with my own different datasets and networks for different cases. The test result shows that it performs best when m = 0.5 which is consistent with the outcome in your paper (testing on lfw).  Sure experiments give us the result. But isn't m larger, the condition is more strict, and the result will be better? What's the reason behind?

**Comment by hustzeyu** [comment]
@guojia

**Comment by nttstar** [comment]
Now these hyperparameters are almost selected by experiments.
