### ISSUE TITLE
About  alignment parameters ?

### ISSUE THREAD

**Issue by vipcualo** [deepinsight/insightface#282]
Thanks for sharing your code.
I want to ask some question:
 1, you  cropped and aligned MS1M ,VGG2 for training . do you have given parameters which you use to crop and align ?
	detector.extract_image_chips(img, points, desired_size, padding)
	which padding do you use for MS1M,VGG2 ?
2. In folder src/align/  , you use diffrent alignments for diffrent datasets ?
	What did you base on to choose these parameter for the data?
3. if i use my custom data, which padding should  i use? 
	detector.extract_image_chips(img, points, desired_size, padding)
who can help me? Thanks very much .

**Comment by vipcualo** [comment]
@nttstar  please help me !

**Comment by nttstar** [comment]
all the same: detect 5 landmarks and use the similarity transformation to crop to 112x112.
