### ISSUE TITLE
where is the SSH e2ef model ?

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#284]
where is the SSH model **e2ef** in the : 

insightface/SSH/test.py

`detector = SSHDetector('./model/e2ef', 0)
`

**Comment by MyraBaba** [comment]
gives 404 error:

啊哦，你所访问的页面不存在了。
可能的原因：
1.在地址栏中输入了错误的地址。
2.你点击的某个链接已过期。
返回上一级页面>
回到网站首页>

**Comment by nttstar** [comment]
https://drive.google.com/open?id=1r7FjiAFTb1jbdU-iee-s5s8BMyeSewOj

**Comment by nttstar** [comment]
https://github.com/deepinsight/insightface/wiki/Model-Zoo
