### ISSUE TITLE
where is the 3d_I5 model ?

### ISSUE THREAD

**Issue by rockstone533** [deepinsight/insightface#285]

**Comment by anshumankmr** [comment]
@nttstar

**Comment by nttstar** [comment]
It will be open source soon.

**Comment by autocar23** [comment]
How do I perform face recognition without this model?

**Comment by hymanzhu1983** [comment]
Hi @nttstar, 
any news about the model?

**Comment by robi56** [comment]
I am searching for an alignment model for insightface use case? Which model should be used now? Any link is available?

**Comment by robi56** [comment]
> It will be open source soon.

Any update?
