### ISSUE TITLE
train and test by glint dataset

### ISSUE THREAD

**Issue by mengzhibin** [deepinsight/insightface#288]
1. When i look through the face2rec2.py and glint2lst.py, I cannot find the step of detecting and crop face by mtcnn. So is the rec file could train dictectly?
2. when I packing the glint dataset to bin, there is not a standard way to build the bin file. your way suit to the lfw and cfp dataset which is special. So could you help provide py file generating bin from images?

Thank you very much.
@nttstar

**Comment by anshumankmr** [comment]
Use [`this`](https://github.com/apache/incubator-mxnet/blob/master/tools/im2rec.py) to generate .rec files. That's what I did.

**Comment by mengzhibin** [comment]
Thank you for reply, I have get the .rec files. But when verification, the input file is .bin file, the way to generate .bin file is what confused me. for example, when generate cfp bin file, the input data conclude CFP_frontal_paris.mat which glint dataset dont have. We dont have whole method to generate .bin file from just images and it's fold name. @anshumankmr  thanks very much

**Comment by Edwardmark** [comment]
@mengzhibin @anshumankmr What is your result in glint data? I fine-tune r50 model using glint train-data, get pretty good result in the test log, but got very bad result when submitting the bin file, got only 20% acc compared to r50 original 48% acc. Could you provide any tricks or result that I can refered to? Thanks.

**Comment by Edwardmark** [comment]
@mengzhibin @anshumankmr @nttstar What is your result in glint data? I fine-tune r50 model using glint train-data, get pretty good result in the test log, but got very bad result when submitting the bin file, got only 20% acc compared to r50 original 48% acc. Could you provide any tricks or result that I can refered to? Thanks.

**Comment by maywander** [comment]
@Edwardmark  Did you get good result at last?

**Comment by Edwardmark** [comment]
@maywander no, I didn't. At last , I use the emore data instead.

**Comment by anguoyang** [comment]
> DeepGlint have already provided the five face landmarks so it's not necessary to do it again. Please use the scripts and follow the steps in that discussion thread and you can generate the .rec dataset easily.

不好意思，我用的也是discussion里的，但是只能生产glint.lst，运行face2rec2.py说是没有property路径，我是严格按照那个命令来的，但是就是不行，请问有什么办法么？我的环境ubuntu 18.04 ，不过我用conda安装的python3.6/mxnet，但是我想应该不是python版本的问题，谢谢
