### ISSUE TITLE
How do you have m=1.5 for sphereface? Isn't it only for integer m? 

### ISSUE THREAD

**Issue by yxchng** [deepinsight/insightface#290]
I check your code and you used lsoftmax which only allows integer m

**Comment by nttstar** [comment]
use combined margin loss(loss-type=5) and set margin-a=1.5, margin-m=0, margin-b=0

**Comment by wuyxiquanquan** [comment]
I used m1=1.5, m2=0, m3=0.35,  but it's hard to converge.

INFO:root:Epoch[33] Batch [1000]        Speed: 453.97 samples/sec       acc=0.364844
INFO:root:Epoch[33] Batch [1020]        Speed: 446.50 samples/sec       acc=0.374219
INFO:root:Epoch[33] Batch [1040]        Speed: 455.31 samples/sec       acc=0.351953
INFO:root:Epoch[33] Batch [1060]        Speed: 455.66 samples/sec       acc=0.347461
INFO:root:Epoch[33] Batch [1080]        Speed: 455.59 samples/sec       acc=0.345508
INFO:root:Epoch[33] Batch [1100]        Speed: 454.26 samples/sec       acc=0.350000
INFO:root:Epoch[33] Batch [1120]        Speed: 455.46 samples/sec       acc=0.358594
INFO:root:Epoch[33] Batch [1140]        Speed: 438.19 samples/sec       acc=0.356445
INFO:root:Epoch[33] Batch [1160]        Speed: 455.19 samples/sec       acc=0.366406
INFO:root:Epoch[33] Batch [1180]        Speed: 454.37 samples/sec       acc=0.352734
INFO:root:Epoch[33] Batch [1200]        Speed: 452.48 samples/sec       acc=0.363086
INFO:root:Epoch[33] Batch [1220]        Speed: 447.37 samples/sec       acc=0.368750
INFO:root:Epoch[33] Batch [1240]        Speed: 456.75 samples/sec       acc=0.360742
INFO:root:Epoch[33] Batch [1260]        Speed: 459.65 samples/sec       acc=0.363281
INFO:root:Epoch[33] Batch [1280]        Speed: 453.25 samples/sec       acc=0.368945
INFO:root:Epoch[33] Batch [1300]        Speed: 456.27 samples/sec       acc=0.355273
INFO:root:Epoch[33] Batch [1320]        Speed: 453.67 samples/sec       acc=0.342187
INFO:root:Epoch[33] Batch [1340]        Speed: 453.53 samples/sec       acc=0.345117
INFO:root:Epoch[33] Batch [1360]        Speed: 449.54 samples/sec       acc=0.362891
INFO:root:Epoch[33] Batch [1380]        Speed: 453.28 samples/sec       acc=0.353516
INFO:root:Epoch[33] Batch [1400]        Speed: 455.15 samples/sec       acc=0.361914
INFO:root:Epoch[33] Batch [1420]        Speed: 451.86 samples/sec       acc=0.360742
INFO:root:Epoch[33] Batch [1440]        Speed: 455.02 samples/sec       acc=0.350977
INFO:root:Epoch[33] Batch [1460]        Speed: 456.96 samples/sec       acc=0.369141
INFO:root:Epoch[33] Batch [1480]        Speed: 458.90 samples/sec       acc=0.355273
INFO:root:Epoch[33] Batch [1500]        Speed: 457.74 samples/sec       acc=0.351953
INFO:root:Epoch[33] Batch [1520]        Speed: 454.05 samples/sec       acc=0.353906
INFO:root:Epoch[33] Batch [1540]        Speed: 453.68 samples/sec       acc=0.361914
