### ISSUE TITLE
performance of mobilenetFaceNet on MegaFace

### ISSUE THREAD

**Issue by heshao90** [deepinsight/insightface#293]
Do you test the mobilenetFaceNet on MegaFace or Asian training dataset(from glint)? How about the perfomance ?

**Comment by nttstar** [comment]
No. You can try it.

**Comment by xiezheng-cs** [comment]
I test mobilenetFaceNet on MegaFace is VR= 89.62%@FAR10^6, but in paper is VR=90.16%@FAR10^6.

**Comment by xiezheng-cs** [comment]
It is because that I didn't use filped images ??? @nttstar

**Comment by borisgribkov** [comment]
This is because current MobileFaceNet differs from the published version
