### ISSUE TITLE
more id ,need more GPU memory?

### ISSUE THREAD

**Issue by xinguanxi** [deepinsight/insightface#296]
training a model with 700k id and 5000k image ，r50 model，image_size 112*112 ,  using eight 1080ti ,even per-batch-size=1 out of memory ，is this normal?
i was doubt that if more id ,need more memory

**Comment by nttstar** [comment]
700K id may hard to train in normal GPU.

**Comment by 1frey** [comment]
Why more ids need more memory?
Can you explain please?
I was thinking it affects only training time coz of more images to feed.

**Comment by xxllp** [comment]
这个里面支持多个GPU 的训练和预测嘛
