### ISSUE TITLE
Definition of Loss Type

### ISSUE THREAD

**Issue by csgcmai** [deepinsight/insightface#3]
Hi there, thanks for the great work, could you please provide the definition of different loss type. It would be many appreciated if the corresponding paper could be indicated.

**Comment by nttstar** [comment]
losstype0 is pure softmax;  losstype1 is sphereface, you can google it;  other loss types are not fully ready, you can ignore them currently.

**Comment by csgcmai** [comment]
Thanks for the reply.

**Comment by clhne** [comment]
> losstype0 is pure softmax; losstype1 is sphereface, you can google it; other loss types are not fully ready, you can ignore them currently.

so, what's the other loss types, now ?
