### ISSUE TITLE
A tiny mistake about mobilefacenet?

### ISSUE THREAD

**Issue by MrCPlusPlus** [deepinsight/insightface#300]
As I review your code about mobilefacenet, I find the repeat time of first bottleneck is 4 in your code, but the repeat time in the original paper is 5.
![_75f1f04a-09d0-43b0-ac20-1f846ababfca](https://user-images.githubusercontent.com/34436077/43252213-8e1a7298-90f4-11e8-9104-8858ebf3efd4.png)
![mobilefacenet](https://user-images.githubusercontent.com/34436077/43252293-b5334346-90f4-11e8-9812-c40503023df1.jpg)
I'm not sure if it is my misunderstanding.

**Comment by MrCPlusPlus** [comment]
Sorry, it is my misunderstanding. The code is correct.

**Comment by Lucien7786** [comment]
the same confused about this n repeat, could you please explain your understanding?
