### ISSUE TITLE
SSH . ImportError: No module named bbox

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#301]
Try to test SSH detector it gives 👍 

> SSH . ImportError: No module named bbox

python 2.7 and added the . sys.path.

any idea?

**Comment by nttstar** [comment]
make to compile

**Comment by MyraBaba** [comment]
Thanks.  I missed that part :)
it took 4 sec for oscar_big.png attached here.

with mtcnn it took 0.4 sec.

1- Can we improve speed ? 
2- is there an easy way to produce result.img with boxed detected faces ? 

best

![oscar_big](https://user-images.githubusercontent.com/17505439/43276065-386e578e-910c-11e8-87fb-19dc50975862.png)

**Comment by nttstar** [comment]
I will test it tomorrow and it is unlikely to take 4 sec.
What's your input resolution, do you resize the image before sending it to network?

**Comment by MyraBaba** [comment]
I am using default test.py as it is.

**Comment by nttstar** [comment]
Set threshold=0.5 and also check the 'detection uses xxx seconds' as the cost time. The first run is warm-up.

**Comment by nttstar** [comment]
I can get 158 faces and time-cost is 0.158s on my M40 GPU.

**Comment by nttstar** [comment]
get 155 faces by setting scales=[600,1200] and the time-cost reduced to 0.1s.

**Comment by MyraBaba** [comment]
I forgot to say I am using cpu in both mtcnn and shh :)

**Comment by nttstar** [comment]
it's not good for SSH.

**Comment by MyraBaba** [comment]
Hi . @nttstar ,
what do you think is the best fit for realtime face detection with SSH ? I know cpu is really not enough.

What would be your suggestion for 1980 X 1200 resolution realtime video face detection ?

Which nvidia could be handle this ?

I have one time budget :) so I need to use it which solve the problem & the cost effective.
Best.

PS: by the way what you suggest for cpu based detection ?
