### ISSUE TITLE
mood recognition

### ISSUE THREAD

**Issue by mrazimi** [deepinsight/insightface#302]
Using deploy/test.py it would be possible to estimate gender and age, how can I estimate the mood using your code?
Do I need to write my own classifier using the extracted feature vector or it is already possible? (pretrained model can give me an estimation)

**Comment by gwsbhqt** [comment]
Training code, deployment code, and models are all given and can be predicted directly.
[issues/272](https://github.com/deepinsight/insightface/issues/272)

**Comment by mrazimi** [comment]
actually there is no pretrained model for mood recognition can be found

**Comment by gwsbhqt** [comment]
@mrazimi 
Forgive me for being wrong. What I just said is the prediction of gender age. I have not found any emotional predictions for this project. It should be that this project has not made emotional predictions for the time being.
