### ISSUE TITLE
About batchnorm layer para "fix_gamma" 

### ISSUE THREAD

**Issue by harhar539** [deepinsight/insightface#310]
I use insightface to retrain **mobilefacenet** , then get new params.
But when I transfer it into **NCNN** and validate the **infer** result ,it's **quite different** from the infer result by **MXNET.**
I found "**fix_gamma**" param in the last bn layer of json file is the key factor.
“fix_gamma” is set to true in the original json file of mobilefacenet，when I change it into false in infer stage, the infer result out by MXNET becomes same with NCNN.
After reading MXNET code ,I guess this param should be set to false when doing infer.
But in insightface code train_softmax.py, the verification func ver_test , this param seems doesnot change to false, thus the verification result is correct?

I just started to learn MXNET, not quite familiar with both MXNET and insightface,maybe made some misunderstanding about this.
Bow~

**Comment by nttstar** [comment]
check this issue: https://github.com/apache/incubator-mxnet/issues/9624

**Comment by harhar539** [comment]
Thx a lot!
