### ISSUE TITLE
MXNet Version Compatibility

### ISSUE THREAD

**Issue by ahkarami** [deepinsight/insightface#317]
Dear @nttstar,
I have used the MXNet version 1.2.1. When using your pre-trained models the following messages are shown:
```
[10:38:11] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[10:38:11] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
```
Would you please help me to remove above messages?

**Comment by ahkarami** [comment]
Dear @nttstar,
Thank you for your response. But I mean a way that the Symbol upgraded just once (_i.e.,_ something like load model & save it in the new MXNet version which the compatibility issue will address).

**Comment by ccl-private** [comment]
why this closed?

**Comment by falimoradi** [comment]
> Dear @nttstar, Thank you for your response. But I mean a way that the Symbol upgraded just once (_i.e.,_ something like load model & save it in the new MXNet version which the compatibility issue will address).

Hi
did you find any solution for that?
