### ISSUE TITLE
ssh pretrain model inference very slowly

### ISSUE THREAD

**Issue by uniquezhengjie** [deepinsight/insightface#319]
hi,i run https://github.com/deepinsight/insightface/blob/master/SSH/test.py with model https://pan.baidu.com/s/1wjgc227L-pPhdwunk948DA ,every image(size about 400px*500px) inference cost about 12s by GPU , I confuse about the code why warmup cost many time but run second time become quickly

 for i in xrange(t-1): #warmup
      faces = detector.detect(img)
timea = datetime.datetime.now()
faces = detector.detect(img, threshold=0.5)
timeb = datetime.datetime.now()

**Comment by nttstar** [comment]
mxnet will init the params in its first call.

**Comment by uniquezhengjie** [comment]
o , i see,but if src images have different shapes,every time need init the params ...

**Comment by nttstar** [comment]
fix input size in production.
