### ISSUE TITLE
A few questions regarding the performance of r100 network

### ISSUE THREAD

**Issue by gaohuazuo** [deepinsight/insightface#32]
I have ran training to epoch 34, minibatch 1700 using code at https://github.com/deepinsight/insightface/tree/af4a4e8f5c47de08e9f069a6a5e65988b6e91888 with a few modification (adding memonger). Typical performance is

LFW | CFP-FF | CFP-FP | AgeDB-30
--|--|--|--
99.817% | 99.771% | 94.257% | 98.000%

1. Are the reported LFW, CFP-FF, CFP-FP, AgeDB-30 results measured on the same set of network parameters?
2. How many epochs/minibatches need to be run in order to obtain the reported result?
3. Is my current trained network a successful reproduction?

**Comment by nttstar** [comment]
a good result.
learning rate drops at 100K,140K,160K iterations in all my previous experiments.
You can try smaller minibatches like '60K,90K,110K'.

**Comment by KiXiang** [comment]
@gaohuazuo What type of GPU do you use, when adding memonger is able to train the model successfully

**Comment by zhenglaizhang** [comment]
@gaohuazuo Could you share how  you did to make the memonger works as expected, thanks in advance! I tried to make r50 with residual_unit_v3 work with memonger, but failed with following exception:
```
Using memonger to optimize memory usage
infer_shape error. Arguments:
Traceback (most recent call last):
  File "train_softmax.py", line 880, in <module>
    main()
  File "train_softmax.py", line 877, in main
    train_net(args)
  File "train_softmax.py", line 600, in train_net
    sym = memonger.search_plan(sym) # net_planned
  File "/home/zhenglai/repo/insightface/src/memonger.py", line 141, in search_plan
    sym = make_mirror_plan(sym, threshold=threshold, plan_info=info, **kwargs)
  File "/home/zhenglai/repo/insightface/src/memonger.py", line 62, in make_mirror_plan
    _, out_shapes, _ = internals.infer_shape(**kwargs)
  File "/home/zhenglai/repo/incubator-mxnet/python/mxnet/symbol/symbol.py", line 989, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/home/zhenglai/repo/incubator-mxnet/python/mxnet/symbol/symbol.py", line 1119, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/zhenglai/repo/incubator-mxnet/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator bn0: [11:02:52] src/operator/nn/batch_norm-inl.h:239: Check failed: channelAxis < dshape.ndim() (1 vs. 0) Channel axis out of range:
```
it looks like  memonger alter the strucure? I am new to mxnet, and have no clear idea yet.
the training could go smooth without the memonger,

**Comment by gaohuazuo** [comment]
@KiXiang @zhenglaizhang 
Please see my [fork](https://github.com/deepinsight/insightface/compare/master...gaohuazuo:master)
Tested on 1080Ti x4, mxnet-cu80, r100, per GPU batch size 128. Memory 8.3G, speed 308 examples/sec.

A few things to note:
* I disabled cudnn for all bn layers (hard coded), due to a bug. Therefore, there will be some performance loss even when memonger is not enabled. Use the original code when possible.
* I only changed code path of resnet+softmax, so other settings won't use memonger.
* memonger requires shape of each symbol, so input shape must be set (only done for resnet).
* Do not set MXNET_BACKWARD_DO_MIRROR as it will override memonger.

**Comment by zhenglaizhang** [comment]
@gaohuazuo thanks for the quick & detailed info, it's very helpful!. 

As you mentioned, you disabled cudnn for all bn layers due to a bug, is the bug related to mxnet or something else?

**Comment by bruinxiong** [comment]
@gaohuazuo Thank you for your advise. But after operations you suggested, the training speed is still very low on my server, it is only 28 examples/sec. I test on P100x4 with each 16 GB,  mxnet-cu80, r100, per GPU batch size 128, Memory 8.3G (I also try the setting with per GPU batch size 192, Memory 10.3G, also very low only 32 examples/sec.). Do you know how to fix the issue of speed ?

**Comment by Lane565** [comment]
@gaohuazuo  Hello, I am a freshman in CQUPT who is interesting in DL .I will be grateful if you can answer my questions below.
(1) How do you install the mxnet? Simply by "pip install mxnet-cu80"？I tried this way also, but I don't know how to configue cuda_use in this way (I cannot find the config.mk). So I isntall by compiling the source.
(2) According to Insight Laboratory(https://zhuanlan.zhihu.com/p/33750684), they use 4 * P40(12G) while  training, so i am wondering if using 6 * GTX1080 can also achieve the same effect ?! I tried on one GTX1080 and failed last weekend.

**Comment by fengxxue** [comment]
@gaohuazuo Thank you for your advise. But after operations you suggested, there is still as bug 'out of memory',  Tested on 1080Ti x4, mxnet-cu80, r100, per GPU batch size 128, which is the same as you. Are there other notes to notice?

**Comment by leiyu1980** [comment]
现在1.3.1 版本依然要 设置 cudnn_off=True ，mxnet官方宣称用nnvm就不会有该bug，难道mxnet不是默认启用nnvm？
