### ISSUE TITLE
Using Another Face Detection Algorithm

### ISSUE THREAD

**Issue by ahkarami** [deepinsight/insightface#320]
I want to use another face detection algorithm instead of MTCNN. As MTCNN accuracy isn't very good for detecting some faces. So, I have used my own implemented Face Detection Algorithm which it's accuracy is better than MTCNN. However, I have faced a new problem. The problem is that I can't get appropriate results with integration of the new face detection method via your face embedding model. I think the problem related to the face alignment method. As your example (in `./deploy/test.py`) you have used the MTCNN face detector and then by using its landmark detection you have aligned the face image and then pass it to the face embedding model (_e.g.,_ _LResNet50E-IR_). Unfortunately, my face detector just detect faces and doesen't have any face landmark localization method. Would you please kindly help me to guide me how I can integrate this new face detection method (without landmark localization) into your face embedding models?
It is worth nothing that I can integrate it into the face embedding model (i.e., without face alignment) but the results were bad.

**Comment by nttstar** [comment]
Face alignment is a must. You may consider to use dlib to extract 68 face landmarks.

**Comment by xizi** [comment]
look foward to the face alignement model release

**Comment by ahkarami** [comment]
Dear @Jacky3213,
Thank you for your complete answer. I will test it.

**Comment by Ancho5515** [comment]
@Jacky3213  Hi, can you share the accuracy and speed under MTCNN and pyseeta? Is the pyseeta better than MTCNN?
