### ISSUE TITLE
卡通图片误检率非常高

### ISSUE THREAD

**Issue by mariolew** [deepinsight/insightface#322]
RT。此repo提供的MTCNN对卡通图片误检率特别高，但原版MTCNN并不会这样，不知是对MTCNN做了何种处理？关键的是，检测到的框也并非卡通人物的人脸区域。但用repo给出的emore训练模型，就必须用此repo的MTCNN对齐才能得到好的结果。。

**Comment by nttstar** [comment]
哪个MTCNN?tf还是mxnet的

**Comment by nttstar** [comment]
对齐不限制用哪个库 只要能检测对应5点的都可以

**Comment by mariolew** [comment]
就是这个repo里的，mxnet的。我不知道怎么插图，我可以给个图。

**Comment by mariolew** [comment]
我以为insightface里的MTCNN是原版转过来的，但看结果貌似并非如此。

**Comment by mariolew** [comment]
我从代码上也没发现什么问题。。。只可能是模型的问题了。。

**Comment by nttstar** [comment]
我用的是这里的: https://github.com/pangyupo/mxnet_mtcnn_face_detection 
你可以用其他库来抽landmark, 理论上不会影响精度

**Comment by mariolew** [comment]
OK，我看看

**Comment by shenriver** [comment]
> 我用的是这里的: https://github.com/pangyupo/mxnet_mtcnn_face_detection
> 你可以用其他库来抽landmark, 理论上不会影响精度
你的意思是说不用你公开的mtcnn也不影响精度？我发现你代码的mtcnn很多时候找不着脸
