### ISSUE TITLE
对模型输出维度的疑问

### ISSUE THREAD

**Issue by MengWangTHU** [deepinsight/insightface#323]
您好，今天在做mxnet C++版本实现人脸识别的时候，发现一个有趣的问题。
按我对人脸识别流程的理解，训练本质其实是分类，训练生成的模型最后一层输出维度应该是num_classes，就是类别数目；要找到任一张图片的embedding特征，应该在交叉熵或者其他形式的损失之前的一层去查看，这个层的输出一般来讲是512维的。
但是我今天用C++版本进行前向过程的时候发现，在没有做中间某一层的特征提取的时候，模型最后一层的输出是512维！这个我感到很有意思！
是您在保存模型的时候已经做了处理，把模型保存到了交叉熵前一层吗？
而且我在阅读您的源码的时候，确实发现在某一特定模型在调用get_symbol()函数时，确实是将实参emb_size传给了形参num_classes，这里我也不是特别了然。

 @nttstar 盼 望您的解答，多谢！

**Comment by nttstar** [comment]
我给的模型已经去掉最后的分类层了

**Comment by MengWangTHU** [comment]
@nttstar 感谢，我拿自己制作的数据训练的时候得到的模型输出也是512维的；这样确实省却了feature extract的麻烦。您很贴心呐！

另，我提到的一个问题，就是在train_softmax.py源码中，get_symbol函数调用其他固定模型类的get_symbole函数时，将实参emb_size传给了形参num_classes，这个我再接着读一下源码吧。

**Comment by elogi** [comment]
> @nttstar 感谢，我拿自己制作的数据训练的时候得到的模型输出也是512维的；这样确实省却了feature extract的麻烦。您很贴心呐！
> 
> 另，我提到的一个问题，就是在train_softmax.py源码中，get_symbol函数调用其他固定模型类的get_symbole函数时，将实参emb_size传给了形参num_classes，这个我再接着读一下源码吧。

感觉这个“形参num_classes” 也应该命名为emb_size比较合适
