### ISSUE TITLE
对齐工具的差异

### ISSUE THREAD

**Issue by jianbaba** [deepinsight/insightface#324]
我使用的是sphereface中的matlab程序代码进行的裁剪的lfw图片（112X112），也是使用他的matlab测试代码进行的测试（使用你release的caffe模型），但是效果不到99%，请问是因为我使用的matlab，而你使用的是python的原因么？

**Comment by nttstar** [comment]
96x112->112x112的过程中注意坐标的变化 另外其他预处理也有可能不一样, 没办法给出准确结论

**Comment by jianbaba** [comment]
@nttstar ,我有看坐标变化，您二人使用的相似对齐坐标变换是完全一样，只是裁剪尺寸由96x112->112x112变换而已！另外请问作者有使用cosface损失，在sphereface的64层结构做过实验么？结果能达到99.7+么？

**Comment by nttstar** [comment]
坐标不一样

**Comment by jianbaba** [comment]
@nttstar 哦哦，我看到了！还有请问请问作者有使用cosface损失，在sphereface的64层结构做过实验么？结果能达到99.7+么？

**Comment by nttstar** [comment]
没试过

**Comment by jianbaba** [comment]
好的，谢谢郭总！

**Comment by deepage** [comment]
@jianbaba 你看看你的基准点坐标改了没有，之前的那个是96x112的，你需要改成如下形式：
imgSize     = [112, 112];
coord5point = [38.2946, 51.6963;
               73.5318, 51.5014;
               56.0252, 71.7366;
               41.5493, 92.3655;
               70.7299, 92.2041];
我之前也是利用sphereface的测试代码测试insightface的模型（转换成caffemodel），结果是正确的，你最好检查下你对齐之后的图片。

**Comment by jianbaba** [comment]
@deepage 感谢感谢，坐标没问题！我的图片有几张变脏了（被其他人画了几个框在上面）现在准确率99.75%（爱你哟）

**Comment by zorrocai** [comment]
@deepage 你好， 我想问一下96x112->112x112的过程中，坐标的变化公式是什么呢？

**Comment by deepage** [comment]
@jianbaba 原来的五个基准点的坐标是针对96X112（即宽是96，高是112）图像的，但是现在把图像的宽扩充了，再继续用原来的基准点肯定不对，因为人脸在W方向上拉伸了，所以只是把这块线性的各加8像素，这样也就是补足了16像素（W方向上面扩充的部分）。而H方向上没有任何改变，则原有位置不变。不知道这么解释你能不能弄清楚。

**Comment by zorrocai** [comment]
@deepage 非常感谢您的解释。
我做了点实验，也发现了其中的不同。
1)这是96x112 
coord5point = [30.2946, 51.6963;
65.5318, 51.5014;
48.0252, 71.7366;
33.5493, 92.3655;
62.7299, 92.2041];
![001](https://user-images.githubusercontent.com/24424749/50817715-b28e4580-135f-11e9-8230-78228414155a.jpg)
2)这是128x128,采用96x112的coord5point
coord5point = [30.2946, 51.6963;
65.5318, 51.5014;
48.0252, 71.7366;
33.5493, 92.3655;
62.7299, 92.2041];
![001](https://user-images.githubusercontent.com/24424749/50817819-144eaf80-1360-11e9-95d2-909f330fbafe.jpg)
3)这是128x128,采用您说的方法修改corrd5point
coord5point = [46.2946, 59.6963;
81.5318, 59.5014;
64.0252, 79.7366;
49.5493, 100.3655;
78.7299, 100.2041];
![001](https://user-images.githubusercontent.com/24424749/50817914-67c0fd80-1360-11e9-99f4-d8b6398b4520.jpg)
4)这是128x128,采用线性缩放coord5point
coord5point = [40.3928, 59.0815;
87.3757, 58.8587;
64.7091, 81.9847;
44.7324, 105.5605;
83.6399, 105.3761];
![001](https://user-images.githubusercontent.com/24424749/50818002-a656b800-1360-11e9-9351-602f668e3031.jpg)
似乎4）和原始的96x112更接近呢。

**Comment by deepage** [comment]
@zorrocai 128X128图像的对齐建议你看下[https://github.com/huangyangyu/SeqFace/blob/master/code/util.py](url)。他们采用的是128X128的输入，我之前测试他们提供的模型时，按照我自己修改的对齐方式，识别结果要比他们提供的要低一些。其实你需要保证你训练还有测试时所做的处理一样，这样得到的结果就是正确的。不过看对齐的效果好像是做线性缩放效果要好一些。

**Comment by NocturnalPig** [comment]
@deepage 你好！请问一下，你知道五个基准点的坐标是怎么求出来的吗？

**Comment by MuggleWang** [comment]
同求，如何得到的五个基准点坐标？是从哪里统计得来的吗？
