### ISSUE TITLE
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'

### ISSUE THREAD

**Issue by xxllp** [deepinsight/insightface#325]
在windows 下 准备跑ssh 模型，遇到这个问题

**Comment by nttstar** [comment]
不要用windows

**Comment by xxllp** [comment]
好的

**Comment by sxl1007** [comment]
https://github.com/deepinsight/insightface/issues/679
windows可以使用。

**Comment by maycuatroi** [comment]
I fixed this issues with change compile method. Hope it work for you https://github.com/deepinsight/insightface/pull/1032
![image](https://user-images.githubusercontent.com/5876946/118957954-29ee2e00-b98b-11eb-8044-5006417dd7a3.png)
