### ISSUE TITLE
Low accuracy when trained by photos collected from social media

### ISSUE THREAD

**Issue by shangleyi** [deepinsight/insightface#326]
The dataset I used contains unaligned photos of about 50k people collected from several Chinese social media platforms. I used mtcnn to detect the faces, align_megaface.py to align and face2rec2.py to generate the .idx and .rec files. Then I called train_softmax.py with arguments r50, loss type 2, margin-m 0.35 and max-step 400000. When the training ended the classification accuracy was only about 0.70 and the lfw accuracy was only about 98.2%.
I found that some of the faces are deformed or blurred by photoshop and some of them have bad resolutions. Does these two factors negatively affect the overall performance of the algorithm? Is it possible to improve the accuracy just by adjusting parameters like margin and lr?

Thanks in advance for any help.

**Comment by nttstar** [comment]
Do not care about LFW accuracy. Test it in your production environment.

**Comment by chenkingwen** [comment]
我使用作者提供的MS1M数据集训练mobilefacenet， loss=softmax，准确率到70%就上不去了，但是lfw上的精度可以达到99.3%

**Comment by shangleyi** [comment]
After cleaning and combining the private dataset with the provided ms1m dataset the accuracy on lfw is now around 99.6
