### ISSUE TITLE
在lfw上测试，为什么正确率只有97.69

### ISSUE THREAD

**Issue by xiyan77** [deepinsight/insightface#327]
我的对齐代码如下：
import os
import numpy as np
import math
import cv2
import os.path
import scipy.io as scio
from skimage import transform as trans

def to_rgb(img):
    w, h = img.shape
    ret = np.empty((w, h, 3), dtype=np.uint8)
    ret[:, :, 0] = ret[:, :, 1] = ret[:, :, 2] = img
    return ret

def preprocess(img, bbox=None, landmark=None, **kwargs):
    M = None
    str_image_size = kwargs.get('image_size', '')
    #image_size = int(str_image_size)
    image_size = str_image_size    
    src = np.array([
      [38.2946, 51.6963],
      [73.5318, 51.5014],
      [56.0252, 71.7366],
      [41.5493, 92.3655],
      [70.7299, 92.2041] ], dtype=np.float32 )
    dst = landmark.astype(np.float32）

    tform = trans.SimilarityTransform()
    tform.estimate(dst, src)
    M = tform.params[0:2,:]
   
    if M is None:
        if bbox is None: #use center crop
            det = np.zeros(4, dtype=np.int32)
            det[0] = int(img.shape[1]*0.0625)
            det[1] = int(img.shape[0]*0.0625)
            det[2] = img.shape[1] - det[0]
            det[3] = img.shape[0] - det[1]
        else:
            det = bbox
        margin = kwargs.get('margin', 44)
        bb = np.zeros(4, dtype=np.int32)
        bb[0] = np.maximum(det[0]-margin/2, 0)
        bb[1] = np.maximum(det[1]-margin/2, 0)
        bb[2] = np.minimum(det[2]+margin/2, img.shape[1])
        bb[3] = np.minimum(det[3]+margin/2, img.shape[0])
        ret = img[bb[1]:bb[3],bb[0]:bb[2],:]
        ret = cv2.resize(ret, (image_size[0], image_size[1]))
        return ret
    else: 
        warped = cv2.warpAffine(img,M,(image_size[0],image_size[1]), borderValue = 0.0)
        bgr = warped[...,::-1]        
        return bgr

if __name__ == "__main__":
    f = open('/data2/lmy/lfw_ori_2.txt','r')
    points_prob = scio.loadmat("/data2/lmy/InsightFace/MTCNNv2/landmark_lfw.mat")
    bbox_prob = scio.loadmat("/data2/lmy/InsightFace/MTCNNv2/bbox_lfw.mat")
    m = f.readlines()
    i = 0
    for a in m:
        path = str(a[0:-1])
        print(path)
        img_or = cv2.imread(path)        
        if img_or.ndim == 2:
            img_or = to_rgb(img_or)
            img_or = img_or[:,:,0:3]                
        temp = points_prob['landmark'][i]
        temp = np.resize(temp,(1,10))
        points = temp
        print(points)
        points_5_2 = np.zeros((5,2))
        #print(points[0,2])
        for j in range(5):
            points_5_2[j,0] = points[0,j]
            points_5_2[j,1] = points[0,j+5]
        print(points_5_2)
        #print(bbox_prob['bbox'])
        points_5_2 = np.float32(points_5_2)
        temp = bbox_prob['bbox'][i]
        temp = np.resize(temp,(1,4))
        bbox_prob_2 =temp
        #print(bbox_prob_2)
        i = i+1
        crop_imgs = preprocess(img_or, bbox=bbox_prob_2, landmark = points_5_2, image_size=[112,112])
        element = a.replace('\r\n','').split("/") 
        save_path = "/data2/lmy/mtcnn_lfw/"+str(element[-2])
        if not os.path.exists(save_path):
            os.makedirs(save_path)
        save_name = save_path + '/' + str(element[-1][0:-1])
        cv2.imwrite(save_name,crop_imgs)

**Comment by anyface** [comment]
mtccn
