### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'forward'

### ISSUE THREAD

**Issue by wangwentaodeheimaojingzhang** [deepinsight/insightface#330]
![image](https://user-images.githubusercontent.com/35397905/44035347-d91a9c36-9f41-11e8-873a-8ed28e7b5bb6.png)
How to solve this problem? It's the problem of mxnet editon?
thank you! @nttstar

**Comment by wangwentaodeheimaojingzhang** [comment]
I have slove the problem. thank you!

**Comment by zealinux** [comment]
@nttstar 

which line?

**Comment by deimsdeutsch** [comment]
@lao-jiu @nttstar 
I am facing the same issue. Can you plz tell me which line to comment ..

**Comment by hsqaihkl** [comment]
> I have slove the problem. thank you!

@lao-jiu hi，I met the same error，could tell me how to solve this problem？

**Comment by hsqaihkl** [comment]
I hava slove it .
Here are the modification steps and the modified code：

First, you have to add the model to the net (The pretrained models is download from link 'model zoo')，create a folder name model and then copy the mode files to here .

second， Comment the code of age and gender .

Then, check the image path。

My modify code ：

import face_model
import argparse
import cv2
import sys
import numpy as np
parser = argparse.ArgumentParser(description='face model test')
# general
parser.add_argument('--image-size', default='112,112', help='')
parser.add_argument('--model', default='model/model,0', help='path to load model.')
parser.add_argument('--ga-model', default='', help='path to load model.')
parser.add_argument('--gpu', default=0, type=int, help='gpu id')
parser.add_argument('--det', default=0, type=int, help='mtcnn option, 1 means using R+O, 0 means detect from begining')
parser.add_argument('--flip', default=0, type=int, help='whether do lr flip aug')
parser.add_argument('--threshold', default=1.24, type=float, help='ver dist threshold')
args = parser.parse_args()

model = face_model.FaceModel(args)
img = cv2.imread('/home/water/PycharmProjects/insightface/deploy/0002.png')
img = model.get_input(img)
f1 = model.get_feature(img)
#print(f1[0:10])
#gender, age = model.get_ga(img)
#print(gender)
#print(age)
#sys.exit(0)
img = cv2.imread('/home/water/PycharmProjects/insightface/deploy/0001.png')
cv2.imshow('show',img)
cv2.waitKey(2000)
img = model.get_input(img)
f2 = model.get_feature(img)
dist = np.sum(np.square(f1-f2))
print(dist)
sim = np.dot(f1, f2.T)
print(sim)
#diff = np.subtract(source_feature, target_feature)
#dist = np.sum(np.square(diff),1)

**Comment by hsqaihkl** [comment]
I hava slove it .
Here are the modification steps and the modified code：

First, you have to add the model to the net (The pretrained models is download from link 'model zoo')，create a folder name model and then copy the mode files to here .

second， Comment the code of age and gender .

Then, check the image path。

My modify code ：

import face_model
import argparse
import cv2
import sys
import numpy as np

parser = argparse.ArgumentParser(description='face model test')
#general
parser.add_argument('--image-size', default='112,112', help='')
parser.add_argument('--model', default='model/model,0', help='path to load model.')
parser.add_argument('--ga-model', default='', help='path to load model.')
parser.add_argument('--gpu', default=0, type=int, help='gpu id')
parser.add_argument('--det', default=0, type=int, help='mtcnn option, 1 means using R+O, 0 means detect from begining')
parser.add_argument('--flip', default=0, type=int, help='whether do lr flip aug')
parser.add_argument('--threshold', default=1.24, type=float, help='ver dist threshold')
args = parser.parse_args()

model = face_model.FaceModel(args)
img = cv2.imread('/home/water/PycharmProjects/insightface/deploy/0002.png')
img = model.get_input(img)
f1 = model.get_feature(img)
print(f1[0:10])
#gender, age = model.get_ga(img)
#print(gender)
#print(age)
#sys.exit(0)
img = cv2.imread('/home/water/PycharmProjects/insightface/deploy/0001.png')
cv2.imshow('show',img)
cv2.waitKey(2000)
img = model.get_input(img)
f2 = model.get_feature(img)
dist = np.sum(np.square(f1-f2))
print(dist)
sim = np.dot(f1, f2.T)
print(sim)
#diff = np.subtract(source_feature, target_feature)
#dist = np.sum(np.square(diff),1)

**Comment by zhangkaijing960806** [comment]
> 我已经解决了这个问题。谢谢你！

请问是修改什么地方，这是什么原因呢
