### ISSUE TITLE
用triplet训练 spherenet报错

### ISSUE THREAD

**Issue by tianxingyzxq** [deepinsight/insightface#336]
File "train_triplet.py", line 233, in train_net
    spherenet.init_weights(sym, data_shape_dict, args.num_layers)
  File "symbols/spherenet.py", line 71, in init_weights
    arg_shape_dict = dict(zip(arg_name, arg_shape))
TypeError: zip argument #2 must support iteration

用spherenet训练softmax没有问题，用triplet训练r34也没有问题

**Comment by nttstar** [comment]
pull and try again

**Comment by tianxingyzxq** [comment]
[13:04:53] src/engine/engine.cc:55: MXNet start using engine: ThreadedEnginePerDevice
symbols/spherenet.py:63: UserWarning: Cannot decide shape for the following arguments (0s in shape means unknown dimensions). Consider providing them as input:
	softmax_label: ()
  arg_shape, aaa, aux_shape = sym.infer_shape(**data_shape_dict)
{'data': (180, 3, 112, 112)}
['data', 'conv1_1_weight', 'conv1_1_bias', 'relu1_1_gamma', 'conv1_2_weight', 'relu1_2_gamma', 'conv1_3_weight', 'relu1_3_gamma', 'conv1_4_weight', 'relu1_4_gamma', 'conv1_5_weight', 'relu1_5_gamma', 'conv2_1_weight', 'conv2_1_bias', 'relu2_1_gamma', 'conv2_2_weight', 'relu2_2_gamma', 'conv2_3_weight', 'relu2_3_gamma', 'conv2_4_weight', 'relu2_4_gamma', 'conv2_5_weight', 'relu2_5_gamma', 'conv2_6_weight', 'relu2_6_gamma', 'conv2_7_weight', 'relu2_7_gamma', 'conv2_8_weight', 'relu2_8_gamma', 'conv2_9_weight', 'relu2_9_gamma', 'conv3_1_weight', 'conv3_1_bias', 'relu3_1_gamma', 'conv3_2_weight', 'relu3_2_gamma', 'conv3_3_weight', 'relu3_3_gamma', 'conv3_4_weight', 'relu3_4_gamma', 'conv3_5_weight', 'relu3_5_gamma', 'conv3_6_weight', 'relu3_6_gamma', 'conv3_7_weight', 'relu3_7_gamma', 'conv3_8_weight', 'relu3_8_gamma', 'conv3_9_weight', 'relu3_9_gamma', 'conv3_10_weight', 'relu3_10_gamma', 'conv3_11_weight', 'relu3_11_gamma', 'conv3_12_weight', 'relu3_12_gamma', 'conv3_13_weight', 'relu3_13_gamma', 'conv3_14_weight', 'relu3_14_gamma', 'conv3_15_weight', 'relu3_15_gamma', 'conv3_16_weight', 'relu3_16_gamma', 'conv3_17_weight', 'relu3_17_gamma', 'conv4_1_weight', 'conv4_1_bias', 'relu4_1_gamma', 'conv4_2_weight', 'relu4_2_gamma', 'conv4_3_weight', 'relu4_3_gamma', 'conv4_4_weight', 'relu4_4_gamma', 'conv4_5_weight', 'relu4_5_gamma', 'fc1_weight', 'fc1_bias', 'softmax_label']
None
Traceback (most recent call last):
  File "train_triplet.py", line 390, in <module>
    main()
  File "train_triplet.py", line 387, in main
    train_net(args)
  File "train_triplet.py", line 233, in train_net
    spherenet.init_weights(sym, data_shape_dict, args.num_layers)
  File "symbols/spherenet.py", line 71, in init_weights
    arg_shape_dict = dict(zip(arg_name, arg_shape))
TypeError: zip argument #2 must support iteration

**Comment by tianxingyzxq** [comment]
已经是最新的版本，老版本train_softmax.py --loss-type 12 同样的错误

**Comment by tianxingyzxq** [comment]
arg_shape is None

**Comment by nttstar** [comment]
暂时把这个初始化去掉，后续我把初始化加到symbol里面

**Comment by anyface** [comment]
你跑通了没？

**Comment by tianxingyzxq** [comment]
跑通了，正常收敛

**Comment by nttstar** [comment]
修复了

**Comment by anyface** [comment]
可以加个微信吗？想请教你一下。

**Comment by zhongyy** [comment]
@nttstar, 请问为什么spherenet64 + arcface（loss_type=4, m=0.5）不收敛呢？

**Comment by nttstar** [comment]
@zhongyy 看下输出层

**Comment by zhongyy** [comment]
@nttstar 感谢回复。请问输出层是指fc7还是embedding呢？我尝试过spherenet64 + softmax可以收敛，也试过LResnet50E-IR+arcface，感觉不是程序的问题。很困惑。

**Comment by zhongyy** [comment]
@nttstar 我还尝试了用spherenet64 + softmax训练的中间结果来改成arcface再finetune，也可以收敛。所以是初始化的问题吗？

**Comment by nttstar** [comment]
embedding层(fc1), spherenet网络主体没有BN, 输出层可能加BN会不好. symbol_utils里考虑加一个选项. 但是我感觉加了BN应当也不会有问题

**Comment by zhongyy** [comment]
嗯嗯，现在您提供的spherenet的程序fc1不带bn，我开始按这个试过，用arcface不收敛，但softmax可以。后来我尝试在fc1加入bn和dropout，arcface也不好收敛，没有试过softmax。
