### ISSUE TITLE
About the image data in *.bin files

### ISSUE THREAD

**Issue by ruyiweicas** [deepinsight/insightface#337]
Such as agedb_30.bin cfp_ff.bin cfp_fp.bin lfw.bin
Now I have a batch of my own training data,I want to convert them to bin format. What should I do?

**Comment by nttstar** [comment]
refer to `src/data/lfw2pack.py` etc..

**Comment by ruyiweicas** [comment]
@nttstar 
in lfw2pack.py len 17-20

```python
image_size = [int(x) for x in args.image_size.split(',')]
lfw_pairs = lfw.read_pairs(os.path.join(lfw_dir, 'pairs.txt'))
lfw_paths, issame_list = lfw.get_paths(lfw_dir, lfw_pairs, 'jpg')
lfw_bins = []
```

where is pairs.txt??
