### ISSUE TITLE
performance difference between fmobilenet and fmobilenetv2

### ISSUE THREAD

**Issue by zhenglaizhang** [deepinsight/insightface#34]
Hi, from the paper and readme, it seems the mobilenet `m1 == fmobilenet ==LMobileNetE `, and curiors  the performance of `fmobilenetv2`.

**Comment by nttstar** [comment]
I haven't finished a whole training process with fmobilenetv2 yet, you can try it.

**Comment by zhenglaizhang** [comment]
@nttstar Yeah, I will do in the near future, I have just tried to train fmobilenet, but find the checkpoint params file is around 227M, it is so big, trained with following configurations (I used the memonger so that I could set the per batch size as 128, for the pool 1060 6G memory -:( )
```
--network m1 --loss-type 4 --margin-m 0.5 --per-batch-size 128 --memonger ...
```

insightface paper states the size of mobilenet is around 112 Mb, I am a bit confused here.

**Comment by nttstar** [comment]
remove last weight matrix by `deploy/model_slim.py`

**Comment by zhenglaizhang** [comment]
@nttstar Oh, thanks man, I should have thought of it -:)
