### ISSUE TITLE
关于GNAP实现

### ISSUE THREAD

**Issue by dl8207531** [deepinsight/insightface#347]
spatial_norm=body*body 
维度应该是[minibatch,7,7,512]？
后面
spatial_norm=mx.sym.sum(data=spatial_norm, axis=1, keepdims=True)
axis=1是什么意思，输出维度是否变成[minibatch,1,7,512] 不应该是对宽高都计算吗？
还有后面的spatial_attention_inverse=mx.symbol.tile(spatial_div_inverse, reps=(1,filters_in,1,1))   也不是很了解，能否讲解下

**Comment by nttstar** [comment]
直接用broadcast_mul也可以的 有很多种实现方法. 我有空还会实验一下

**Comment by dl8207531** [comment]
主要是没明白spatial_norm=mx.sym.sum(data=spatial_norm, axis=1, keepdims=True) 后的维度是否对应宽高

**Comment by dl8207531** [comment]
难道第二维是通道数？ [minibatch,channel,7,7] 这样的？

**Comment by nttstar** [comment]
@dl8207531 是的. mxnet排列方式 [batch-size, channel, H, W]

**Comment by dl8207531** [comment]
谢谢你的回答，因为我是用的tensorflow channel在最后，所以没看明白，最后问一下还是接上面的代码 后面的求平均 spatial_mean=mx.sym.mean(spatial_sqrt) 没带axis 这里是对整个batch求平均？

**Comment by nttstar** [comment]
实验发现没什么区别, 其实应当对每个样本求.
``spatial_mean=mx.sym.mean(spatial_sqrt, axis=(1,2,3), keepdims=True)``

**Comment by dl8207531** [comment]
接着上面 spatial_div_inverse=mx.sym.broadcast_div(spatial_mean, spatial_sqrt) 对应维度应该是
broadcast_div([batch,],[batch,1,7,7])=[batch,batch,7,7] 是这样吗？

**Comment by nttstar** [comment]
看一下mxnet文档
