### ISSUE TITLE
A little confusing about the arcface loss and combine loss implementation

### ISSUE THREAD

**Issue by huyangc** [deepinsight/insightface#348]
As code [here](https://github.com/deepinsight/insightface/blob/master/src/train_softmax.py#L219-L236):
```
    threshold = math.cos(math.pi-m)
    if args.easy_margin:
      cond = mx.symbol.Activation(data=cos_t, act_type='relu')
    else:
      cond_v = cos_t - threshold
      cond = mx.symbol.Activation(data=cond_v, act_type='relu')
    body = cos_t*cos_t
    body = 1.0-body
    sin_t = mx.sym.sqrt(body)
    new_zy = cos_t*cos_m
    b = sin_t*sin_m
    new_zy = new_zy - b
    new_zy = new_zy*s
    if args.easy_margin:
      zy_keep = zy
    else:
      zy_keep = zy - s*mm
    new_zy = mx.sym.where(cond, new_zy, zy_keep)
```
Some codes are meant to make sure the theta+m is in  [0, pi]. However, when in the combine loss codes, this constrain is not done. I am not very sure why in combine loss this constrain can be deleted.

**Comment by nttstar** [comment]
The theta on target class is close to pi/2 at the beginning and it will not become larger as training goes on. So these two implementations are the same but using ``arccos`` is simpler.
