### ISSUE TITLE
finetune occur error!

### ISSUE THREAD

**Issue by wangpupanjing** [deepinsight/insightface#351]
mxnet.base.MXNetError: [16:42:12] src/operator/nn/../tensor/../elemwise_op_common.h:123: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected [512,25088], got [512,61952]

python -u train_softmax.py --network r100 --loss-type 4 --margin-m 0.5 --data-dir  /zqzn/LLface_rec/ --prefix ../model-r100 --per-batch-size 28 --pretrained ../models/model-r100-ii/model,0

finetune imagesize is 171*171

why? help me!

**Comment by nttstar** [comment]
Make sure the input is 112*112 if you want to fine-tune the provided pretrained model.

**Comment by wangpupanjing** [comment]
OK,  3Q

**Comment by Talgin** [comment]
Hi, the same problem:
c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\../elemwise_op_common.h:135: Check failed: assign(&dattr, vec.at(i)) Incompatible attr in node  at 0-th output: expected [512,25088], got [512,819200]
While loading our dataset of aligned images (112*112). We've made following steps: 
- aligned our images with mxcnn;
- run build_eval_pack.py with :
       --data-dir our_images_dir
       --det-prefix r100-arcface-emore
       --output our output folder
The result is the above error.
