### ISSUE TITLE
Alignment model missing

### ISSUE THREAD

**Issue by 1frey** [deepinsight/insightface#353]
@nttstar First thanks for your great work.

When i want to try _/recognition/test.py_ the alignment model is missing and i can not find any model provided by your repository (there is no model in Model-Zoo)

Do i have to train it myself? If so, what dataset and what script i have to use?
Would be awesome if you could provide your pretrained model, so i can run your test.py script.

Greetings.

**Comment by nttstar** [comment]
It will be made open source soon.
