### ISSUE TITLE
finetune with triplet loss makes the acc decrease

### ISSUE THREAD

**Issue by HaoLiuHust** [deepinsight/insightface#354]
I am trying to use triplet loss to finetune mobilefacenet, but the acc on lfw,cfp,agedb all decrease after use it

**Comment by jinwu07** [comment]
Wonder why this thread was closed without any explanation?

**Comment by HaoLiuHust** [comment]
@jinwu07 do you meet the same problem?

**Comment by jinwu07** [comment]
Yes, I see the same problem - even when I tried to fine tune the emore-trained mobilefacenet model on emore itself with triplet. The accuracy decreased over time.
