### ISSUE TITLE
finetune with different embedding size

### ISSUE THREAD

**Issue by mpaffolter** [deepinsight/insightface#355]
Hi
I want to finetune your pretrained model (r50) with embedding size 128. Starting point is your train_softmax.py:
`CUDA_VISIBLE_DEVICES='0' python -u train_softmax.py --emb-size=128 --pretrained '../models/model-r50-am-lfw/model,0' --network r50 --loss-type 0 --margin-m 0.5 --data-dir ../datasets/faces_ms1m_112x112  --prefix ../models/model-r50-am-lfw/`

this results in:
`mxnet.base.MXNetError: [08:51:39] src/operator/nn/../tensor/../elemwise_op_common.h:123: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected [512], got [128]`

I have tried to remove the last fc layer (fc1), then add fc7 as done in your code, then freeze all layers except fc7. Still the dimensions don't match.

Any advise on how to do this? Thanks.

**Comment by nttstar** [comment]
Please use the same embedding size to do fine-tuning.

**Comment by mpaffolter** [comment]
Thanks for answering. Does this mean, that if I want to use a different embedding size, I will have to train the model from scratch (as opposed to just the last fully connected layer)? You mentioned you tested different embedding sizes, would you mind sharing the results here?

**Comment by nttstar** [comment]
Embedding layer(fc1) is not the last FC layer, but fc7(embedding to number of classes) is. You should training from scratch with different embedding size

**Comment by zhaowwenzhong** [comment]
train fc1 and fc7 from scratch

**Comment by mpaffolter** [comment]
@nttstar thanks for you answer. I had figured out the same as @zhaowwenzhong and managed to finetune the model by replacing the last two fully connected layers fc1 and fc7 and freezing all others.

The results after approx. one epoch (batch 57999 with batch-size 64):

> lr-batch-epoch: 0.1 57999 0
> testing verification..
> (12000, 128)
> infer time 32.649729
> [lfw][58000]XNorm: 73.725490
> [lfw][58000]Accuracy-Flip: 0.99767+-0.00271
> testing verification..
> (14000, 128)
> infer time 38.195482
> [cfp_fp][58000]XNorm: 65.571361
> [cfp_fp][58000]Accuracy-Flip: 0.91700+-0.01722
> testing verification..
> (12000, 128)
> infer time 32.622431
> [agedb_30][58000]XNorm: 74.715656
> [agedb_30][58000]Accuracy-Flip: 0.97300+-0.00862

Unfortunately the 'acc' output is always zero

> INFO:root:Epoch[0] Batch [57940]	Speed: 668.45 samples/sec	acc=0.000000
> INFO:root:Epoch[0] Batch [57960]	Speed: 677.91 samples/sec	acc=0.000000
> INFO:root:Epoch[0] Batch [57980]	Speed: 678.13 samples/sec	acc=0.000000

since there is no val.rec provided in the dataset faces_ms1m-refine-v1_112x112.zip.
Is there another dataset including validation data?

**Comment by staceycy** [comment]
@mpaffolter yes. Actually I have the same question. If there is no validation set, how can we know whether our model is overfitting? 

@nttstar Could you please help to answer, thank you. :)

**Comment by zhaowwenzhong** [comment]
@nttstar I want to train from scratch with different embedding size. 
1、_weight = mx.symbol.Variable("fc7_weight", shape=(args.num_classes, args.emb_size), lr_mult=1.0, wd_mult=args.fc7_wd_mult)
change to ---->>>_weight = mx.symbol.Variable("fc7_weight_finetune", init = mx.init.Xavier(rnd_type='gaussian', factor_type="out", magnitude=2),shape=(args.num_classes, args.emb_size), lr_mult=1.0, wd_mult=args.fc7_wd_mult)

2、fc7 = mx.sym.FullyConnected(data=nembedding, weight = _weight, no_bias = True, num_hidden=args.num_classes, name='fc7')
change to --->> >fc7 = mx.sym.FullyConnected(data=nembedding, weight = _weight, no_bias = True, num_hidden=args.num_classes, name='fc7_finetune')

**Comment by nttstar** [comment]
use ``--emb-size`` to set different embedding size other than 512

**Comment by wlwu92** [comment]
> @mpaffolter yes. Actually I have the same question. If there is no validation set, how can we know whether our model is overfitting?
> 
> @nttstar Could you please help to answer, thank you. :)

@mpaffolter @staceycy @nttstar same question. The comparison with state-of-the-art seems unfair.
