### ISSUE TITLE
s = self.imgrec.read_idx(0)  KeyError: 0

### ISSUE THREAD

**Issue by mooncakehe** [deepinsight/insightface#357]
I  follow the steps to change glint data to train.rec and train.idx, but when i run train_softmax.py, it has this erro   s = self.imgrec.read_idx(0)  KeyError: 0, the idx file is attached! thanks!
![2018-09-06 10-43-02](https://user-images.githubusercontent.com/26209785/45131949-b5b2d280-b1c1-11e8-8b7a-4abc0295f630.png)

**Comment by nttstar** [comment]
You image rec was not built correctly.

**Comment by zhouwei5113** [comment]
@nttstar @mooncakehe  What causes such error?  I've also encountered such a problem...

**Comment by xiaoruiruia** [comment]
> @nttstar @mooncakehe What causes such error? I've also encountered such a problem...

你好请问你解决这个问题了吗？

**Comment by herokarimpoor** [comment]
how create ,rec correctly?
i use face2rec2.py
