### ISSUE TITLE
How to modify MobileFaceNet to make it faster?

### ISSUE THREAD

**Issue by PotentialPie** [deepinsight/insightface#358]
I want to modify the MobileFaceNet  to make it faster in some device to meet the requirement of FPS. Is there any modification suggestion?

**Comment by nttstar** [comment]
try using GAP

**Comment by PotentialPie** [comment]
What does GAP mean?

**Comment by golunovas** [comment]
@PotentialPie GAP = Global average pooling

**Comment by PotentialPie** [comment]
Got it. 
Thank you.
I'll try it.
