### ISSUE TITLE
about MS1M-refine-v2(emore)

### ISSUE THREAD

**Issue by ddwktv** [deepinsight/insightface#359]
I have the same question with @bruinxiong. Emore only have hundreds more identities, but two million more images, can you please tell me how you setup this dataset?

**Comment by staceycy** [comment]
@ddwktv I extracted the images out and found that it seems they do some augmentation offline.

**Comment by ddwktv** [comment]
@staceycy thank you very much

**Comment by zhouyang2640** [comment]
@staceycy, which type of augmentation do you find ? Is that closely related to pose ? It seems the performance is largely improved on cfp_fp if using emore.

**Comment by liu1004010308** [comment]
@ddwktv  can you tell me how to modify a few the .py in the insightface model about maxnet change to caffe. I am worried. thanks.
