### ISSUE TITLE
Backpropagation

### ISSUE THREAD

**Issue by golunovas** [deepinsight/insightface#36]
Thank you for the great work! I'm not quite familiar with mxnet framework so sorry for a stupid question. Can you tell me where the backpropagation is implemented in your code, please?

**Comment by nttstar** [comment]
Not required. Automatically.

**Comment by golunovas** [comment]
Can you elaborate on that, please? Is it done by mxnet or what?

**Comment by nttstar** [comment]
https://mxnet.incubator.apache.org/api/python/autograd.html

**Comment by golunovas** [comment]
Ah, I see. thanks a lot.
