### ISSUE TITLE
mobilefacenet-res4-8-16-4，lfw-99.8%, cfp-97.6%, agdb-98.0单线程只需135ms

### ISSUE THREAD

**Issue by zuoqing1988** [deepinsight/insightface#361]
![1234](https://user-images.githubusercontent.com/20920889/45276640-0abe5380-b4f6-11e8-993b-cd403265dfbe.png)
请访问我的github项目https://github.com/zuoqing1988/ZQCNN-v0.0

**Comment by zuoqing1988** [comment]
觉得好用的请给我的gitHub点星，谢谢！

**Comment by nttstar** [comment]
付一下广告费 谢谢 :-) 
开玩笑的 这个研究很不错.
MKLDNN+r100 差不多是200~300ms

**Comment by zuoqing1988** [comment]
@nttstar opencv号称很快，但是我机器E5 1650V4测了一下单线程MobileNet-SSD感觉和我写的ZQCNN差不多，多线程它确实快得多。其他网络没测。

**Comment by zuoqing1988** [comment]
我在model zoo的链接里放了这个网络的mxnet, caffe, ZQCNN三种格式的模型，有兴趣的可以都测一测。

**Comment by zuoqing1988** [comment]
今天找人问了下，opencv3.4.2默认是没有inter inference engine。这个模型单线程下，opencv和ZQCNN速度差不多。intel inference engine以后编译了再试试。

**Comment by masbbx** [comment]
这个是指在PC上单线程135ms吗

**Comment by zuoqing1988** [comment]
@masbbx E5 1650 v4的CPU， win7 64位。实际时间有波动，最快的时候114ms, 比较慢时候135ms

**Comment by masbbx** [comment]
有个问题，论文中不是在手机上24ms，那这个pc上114ms，是不是模型不一样的

**Comment by masbbx** [comment]
666

**Comment by xmuszq** [comment]
@zuoqing1988 
where can I get the model definition (like xx.py) file?

**Comment by zuoqing1988** [comment]
@xmuszq https://github.com/zuoqing1988/ZQCNN-v0.0/wiki/Model-Zoo-for-Face-Recognition
https://pan.baidu.com/s/143j7eULc2AqpNcSugFdTxA#list/path=%2FZQlib%2FZQlibCNN%2FZQCNN-model%2Fmodel%2Farcface%2Fmobilefacenet-res2-6-10-2-dim256&parentPath=%2FZQlib%2FZQlibCNN%2FZQCNN-model%2Fmodel%2Farcface

**Comment by zuoqing1988** [comment]
@xmuszq https://pan.baidu.com/s/1f_VtqNRxDNe972h8UrOsPw#list/path=%2FZQlib%2FZQlibCNN%2FZQCNN-model%2Fmodel%2Farcface%2Fmobilefacenet-res4-8-16-4-dim256&parentPath=%2FZQlib%2FZQlibCNN%2FZQCNN-model%2Fmodel%2Farcface

**Comment by WANG-MengJiao** [comment]
@nttstar 
> 付一下广告费 谢谢 :-)
> 开玩笑的 这个研究很不错.
> MKLDNN+r100 差不多是200~300ms
Hello there. For the inference time of r100, did you just use MKL-DNN, or combine MKL-DNN with ZQCNN? Based on my experiments, the r50 model will take 700ms for inference with MKL-DNN library (without using ZQCNN). I am wondering how did you achieve such fast speed with r100 model?

**Comment by WANG-MengJiao** [comment]
> 付一下广告费 谢谢 :-)
> 开玩笑的 这个研究很不错.
> MKLDNN+r100 差不多是200~300ms
@nttstar 
Hello there. For the inference time of r100, did you just use MKL-DNN, or combine MKL-DNN with ZQCNN? Based on my experiments, the r50 model will take 700ms for inference with MKL-DNN library (without using ZQCNN). I am wondering how did you achieve such fast speed with r100 model?

**Comment by sharonjunjun** [comment]
@zuoqing1988 请问mobilefacenet-res-4-8-16模型训练过程是和@nttstar说的一样还是和@moli一样初绐化的时候用uniform

**Comment by zuoqing1988** [comment]
@sharonjunjun 把我的脚本替换掉原有的mobilefacenet.py，其他的按照mobilefacenet的训练方式训练

**Comment by smonefrmsouth** [comment]
Hi @zuoqing1988 Can you please share the fmobilefacenet.py code used to train your model in google drive or dropbox.
thanks.
