### ISSUE TITLE
get stuck with subprocess in multithread

### ISSUE THREAD

**Issue by guoguangchao** [deepinsight/insightface#364]
`# -*- coding: utf-8 -*-
from multiprocessing import Process,Queue
import time,random,os
import cv2
import mxnet as mx
from mtcnn_detector import MtcnnDetector
cap = cv2.VideoCapture(0)

detector = MtcnnDetector(model_folder='mtcnn-model', ctx=mx.cpu(0), num_worker = 1 , accurate_landmark = False)'

def consumer(queue):
    while True: 
        frame=queue.get()
        results = detector.detect_face(frame)
        print('queue.size()=={}'.format(queue.qsize()))

def producer(queue):
    while True:
        ret_flag, frame = cap.read()
        queue.put(frame)

if __name__ == '__main__':
    q=Queue()
    p1=Process(target=producer,args=(q,))
    c1=Process(target=consumer,args=(q,))

    p1.start()
    c1.start()'

the output is:
queue.size()==6
queue.size()==11
queue.size()==17
queue.size()==22
queue.size()==27
queue.size()==31
queue.size()==36
queue.size()==41
queue.size()==46
queue.size()==51
queue.size()==55
queue.size()==60
queue.size()==65
queue.size()==70

the size not reduce, it seems get stuck when running mtcnn.

**Comment by nttstar** [comment]
use multiple processes
