### ISSUE TITLE
How to make feature comparing faster?

### ISSUE THREAD

**Issue by liuxcc** [deepinsight/insightface#374]
As for a M:N face recognition task, my current method is to compare the calculated features with the features of the test datasets one by one, which is very time consuming if M and N is large. Is there any accelerating algorithms that do not need to compare features one by one? How to make this process faster?

**Comment by 1frey** [comment]
Do you mean recognition task?
Try to use k-NN or LSH Forest to fit train data and predict test data. There are scikit-learn implementations.
@nttstar what do you recommend to classify 512d embeddings in recognition tasks?

**Comment by MyraBaba** [comment]
Hi Gentleman,

Can we make a c++ example same as in test.py ?

1-align
2-extract features
3-comparing

it would be faster in c++ specially recognition(comparing or k-NN)

any idea how we can transform this to c++ example ?

**Comment by zuoqing1988** [comment]
@liuxcc  First of all

**Comment by liuxcc** [comment]
@1frey @zuoqing1988 @jimeffry Thanks very much for the advices.

**Comment by MyraBaba** [comment]
@1frey @zuoqing1988 @jimeffry  Thanks for your reply. Our system based on C++ . We are very happy its speed and framework.

I am looking for a C++ example for insight face:
Extract_future.cpp
recognize_compare.cpp
:)

is there any way to use current models in c++ for this purposes ?

Best

**Comment by MyraBaba** [comment]
Help :)

isnt there any c++ user / fan / lover :)

how can I use from my c++ code this fantastic model ?

I need to extract_future and compere from c++ . 

How I can use this model from inside c++ ?

Or how can I call from outside ?

or finally but the ugly one do I have to make service just extract future and send back results ?
