### ISSUE TITLE
how to output the face feature？

### ISSUE THREAD

**Issue by cmdares** [deepinsight/insightface#376]
how to output the face feature vector?
ref:
https://github.com/ageitgey/face_recognition/blob/master/examples/face_distance.py
Key code:
known_obama_image = face_recognition.load_image_file("obama.jpg")
obama_face_encoding = face_recognition.face_encodings(known_obama_image)[0]
the "obama_face_encoding"  variable is the numpy vector.
And how to get the face_encoding vector from insightface api.
please show the demo code. thanks.

**Comment by nttstar** [comment]
see deploy/test.py
