### ISSUE TITLE
Reference paper to the face attribute (gender and age) model

### ISSUE THREAD

**Issue by twmht** [deepinsight/insightface#378]
Any reference paper to the face attribute (gender, age) model (https://www.dropbox.com/s/2xq8mcao6z14e3u/gamodel-r50.zip?dl=0)?

**Comment by nttstar** [comment]
Ordinal regression for age estimation.
Simple two-classes softmax for gender.

**Comment by jake221** [comment]
> Ordinal regression for age estimation.
> Simple two-classes softmax for gender.

So you are refering this paper: "Ordinal Regression With Multiple Output CNN for Age Estimation"?
