### ISSUE TITLE
convergence problem in gluon code 

### ISSUE THREAD

**Issue by qzying** [deepinsight/insightface#379]
When I use the arcface loss with gluon code, there is something wrong with the convergence.(s=64,m=0.5)
And the cross entropy loss does not drops when it is about 20.

**Comment by nttstar** [comment]
gluon has a bug which is not resolved yet.

**Comment by qzying** [comment]
Thank you very much, so it is the problem of gluon?

**Comment by nttstar** [comment]
I think so

**Comment by qzying** [comment]
ok, I was confused for many days~T_T

**Comment by nttstar** [comment]
https://github.com/apache/incubator-mxnet/issues/11019
