### ISSUE TITLE
The url of Refined-MS1M@GoogleDrive lost?

### ISSUE THREAD

**Issue by lgqfhwy** [deepinsight/insightface#381]
Hello, the url of Refined-MS1M@GoogleDrive is  lost, the BaiduDrive is too slow. Could you give me a new url of GoogleDrive? Thank you so much!

**Comment by nttstar** [comment]
https://github.com/deepinsight/insightface/wiki/Dataset-Zoo

**Comment by AGenchev** [comment]
I guess magnet/torrent links would be the fastest, because employ M:M topology. To survive, they could be backed by web seeding https://en.wikipedia.org/wiki/BitTorrent#Web_seeding
