### ISSUE TITLE
Facescrub image align !!!

### ISSUE THREAD

**Issue by zhouyang2640** [deepinsight/insightface#383]
What's the difference between given "faescrub_images_112x112.tar" and the facescrub aligned by "align_facescrub.py" ?
It's well-known that the detection and alignment largely affect the face recognition performance, and there should be a 1% top-1 identification performance gap on Megaface (the given faescrub_images_112x112.tar is better).
Without knowing this detail, it is quite hurting the re-producible of the Arcface paper, could you help share it ? Thanks in advance !

**Comment by quietsmile** [comment]
agree!

**Comment by nttstar** [comment]
Hi, at that time we used the aligned facescrub images which produced by Matlab code with the same face detector(MTCNN) and transformed landmark coordinates. But it may have subtle differences on the part of similarity transformation comparing with our python code. As a result, this may affect the Megaface accuracy by around 1%. We will make changes accordingly in our paper later.

**Comment by zhouyang2640** [comment]
Hi Guojia, thanks for your time for answering the question. What if I want the 1%:

1) What could be the key difference between the two detection and align ? There must be some explicit and reasonable tricks, this could be quite helpful for all in practice, which could be even more helpful for all the engineers than pure publications.

2) What's your recommendation to try on detection and align, from your perspective in practice ?

Your help is greatly appreciated !!!

**Comment by LCorleone** [comment]
agree！

**Comment by nttstar** [comment]
please use the new megaface testing tool

**Comment by HaoLiuHust** [comment]
@nttstar could you explain more about align, for example, how to decide the align ref points, how to decide how many background around the aligned face

**Comment by khawar-islam** [comment]
You can download cleaned version from here, if dataset is helpful for you, please consider to cite it
https://github.com/khawar-islam/FPVT_BMVC22

**Comment by LCorleone** [comment]
您好，我是陆鑫益，您的邮件已经收到，我会尽快回复，谢谢。
