### ISSUE TITLE
主页链接的InsightFace_TF

### ISSUE THREAD

**Issue by dl8207531** [deepinsight/insightface#388]
请问下主页链接的InsightFace_TF 里实现的arcloss 是否有了解过  我发现哪里的实现和这里的似乎有很多不一样？？

**Comment by masbbx** [comment]
没有了解过，我想一个是tf框架一个是tensorflow框架，那loss写的肯定不一样吧

**Comment by dl8207531** [comment]
倒不是语法上的区别
1.本文 mm = math.sin(math.pi-m)*m 那边是mm = math.sin(m)*m
2.本文loss最后fc7 = fc7+body fc7是没有乘s的 那边是有乘的
s_cos_t = tf.multiply(s, cos_t, name='scalar_cos_t')
output = tf.add(tf.multiply(s_cos_t, inv_mask), tf.multiply(cos_mt_temp, mask), name='arcface_loss_output')

**Comment by masbbx** [comment]
看这么仔细，赞！

**Comment by nttstar** [comment]
没仔细看过，因为他是当时第一个做的tf实现, 所以链接了一下

**Comment by dl8207531** [comment]
那你认为这两点会有问题吗？

**Comment by dl8207531** [comment]
能否帮忙简单看下呢？

**Comment by JingyuanHu** [comment]
我觉得两者没有明显的差别 
1.数学上math.sin(m)*m 和 math.sin(math.pi-m)*m 是完全相同的 
2. 从论文思想上，归一化特征，是需要乘以s的。而具体到代码上，这里的实现中注意看train_softmax.py 的 213 和 237行，也是乘以了s的
@dl8207531

**Comment by dl8207531** [comment]
@JingyuanHu 谢谢解答
1.数学上两者完全相同，不太明白能否解答下？
2.确实是我没看仔细，看漏了213行的乘s

**Comment by JingyuanHu** [comment]
我认为这是显然的，正弦函数的简单性质
@dl8207531

**Comment by dl8207531** [comment]
这下明白了，谢谢指教
@JingyuanHu

**Comment by zfs1993** [comment]
我发现这个tf，版本训练结果和mxnet的有很大差距，请问是这样的吗
