### ISSUE TITLE
no LSoftmax when use spherefaceloss

### ISSUE THREAD

**Issue by yanglilian** [deepinsight/insightface#39]
- 
Traceback (most recent call last):
  File "train_softmax.py", line 873, in <module>
    main()
  File "train_softmax.py", line 870, in main
    train_net(args)
  File "train_softmax.py", line 593, in train_net
    sym, arg_params, aux_params = get_symbol(args, arg_params, aux_params)
  File "train_softmax.py", line 245, in get_symbol
    fc7 = mx.sym.LSoftmax(data=embedding, label=gt_label, num_hidden=args.num_classes,
AttributeError: 'module' object has no attribute 'LSoftmax'

-

**Comment by nttstar** [comment]
compile lsoftmax in `3rdparty/operator`

**Comment by yanglilian** [comment]
how to compile ，could you please tell me more details about it？

**Comment by nttstar** [comment]
download mxnet source code, put lsoftmax to operator dir, build/install mxnet from source.

**Comment by yanglilian** [comment]
got it ，thank you so much

**Comment by yuzehui1996** [comment]
@yanglilian can you explain more details about the compiling lsoftmax?
