### ISSUE TITLE
dataset_merge.py: 在合并glint和其他数据集时的错误

### ISSUE THREAD

**Issue by AmigoCDT** [deepinsight/insightface#394]
我将glint数据集进行清洗,得到了rec和idx文件, 然后想要将该数据集和其他数据集(已经有train.rec和train.idx)进行合并.
调用dataset_merge.py,报错:

File "dataset_merge.py", line 292, in <module>
    main(args)
  File "dataset_merge.py", line 125, in main
    s = imgrec.read_idx(0)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/recordio.py", line 264, in read_idx
    self.seek(idx)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/recordio.py", line 226, in seek
    pos = ctypes.c_size_t(self.idx[idx])
KeyError: 0

意思是我在glint数据集上生成的rec文件,没有0这个idx.
请问是我调用face2rec2.py出错还是其他问题?

万分感谢!

**Comment by AmigoCDT** [comment]
我觉得我可能找到原因了...可能是因为我直接从lmk文件中删除了很多行,并没有自己重新生成lmk文件,导致了这个问题

**Comment by test4fest** [comment]
@AmigoCDT 
would you please provide an example how to run dataset_merge.py file?should I use a pre-trained model or I do need to train the model?
when I download LResNet50E-IR model and put it in the folder "../model/LResNet50E-IR"
do I need to add epoch number at the end of model path or I have to change model name in "LResNet50E-IR, 50".

Thanks in advance.

**Comment by AmigoCDT** [comment]
@test4fest 
Sorry, I am late to answer. I just see your problem.
When I run the dataset_merge.py, I use:    
python dataset_merge.py --include /mnt/sdf_6t/cdt/datasets/DeepGlint,/mnt/sdf_6t/cdt/datasets/megaface --output /mnt/sdf_6t/cdt/datasets/rec/merge_5 --model ./model-r50-am-lfw/model,0 --param1 0.7 --gpu 0,1,2,3 --batch-size 256
in the --model ./model-r50-am-lfw/model,0 . the 0 mean that the model file is model-0000.params. param1 0.7 suggest that if two ID mean feature innerproduct is greater than 0.7, do not put one ID in output dataset .
If you use "LResNet50E-IR, 50", maybe you need change to "../model/LResNet50E-IR/model,50", and the model size is larger than 300M or 200M, you should use /deploy/model_slim.py to truncate the FC layer of this model.
