### ISSUE TITLE
ImportError: No module named bbox

### ISSUE THREAD

**Issue by mayidu** [deepinsight/insightface#395]
您好！我运行SSH/test.py，出现一下错误：
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from ssh_detector import SSHDetector
  File "/home/fll/work/Face recognition project/Age_Estimation/insightface/SSH/ssh_detector.py", line 10, in <module>
    from rcnn.processing.bbox_transform import nonlinear_pred, clip_boxes
  File "/home/fll/work/Face recognition project/Age_Estimation/insightface/SSH/rcnn/processing/bbox_transform.py", line 2, in <module>
    from ..cython.bbox import bbox_overlaps_cython
ImportError: No module named bbox

如何解决呢，谢谢！

**Comment by Neltherion** [comment]
@nttstar Thanks for the answer, but is this viable on Windows too? Is there any way to run RetinaFace on Windows?

**Comment by tosonw** [comment]
But it's error also , after 'make'. Do you have any other method？

**Comment by tosonw** [comment]
I just find my command `python` use `python3`, but my project use `python2`.
So, I make it with `python2 setup.py build_ext --inplace` again.

So the problem was solved.

**Comment by engmubarak48** [comment]
You can also enter the folder where the Cython files are placed and simply run:
  
   python setup.py build_ext --inplace

make sure the setup.py is in the folder.

**Comment by ltcs11** [comment]
thanks a lot！Anaconda user will also get this problem
Just enter into your conda env and run python setup.py build_ext --inplace(under Cython dir)

**Comment by sky186** [comment]
@tosonw 
hi ,
I can use python 3.6   to test,
but I use pythoh2.7 not ,will error

I use your resolution
cd ~/nas/Pytorch_Retinaface/rcnn/cython$ python2 setup.py build_ext --inplace
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
skipping 'anchors.c' Cython extension (up-to-date)
skipping 'cpu_nms.c' Cython extension (up-to-date)
skipping 'gpu_nms.cpp' Cython extension (up-to-date)


then python2.7 test.py  will
ImportError: Building module rcnn.cython.bbox failed: ["CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n"]


Could you help me?

**Comment by sky186** [comment]
@ltcs11 
hi ,
I can use python 3.6 to test,
but I use pythoh2.7 not ,will error

I use your resolution
cd ~/nas/Pytorch_Retinaface/rcnn/cython$ python2 setup.py build_ext --inplace
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
skipping 'anchors.c' Cython extension (up-to-date)
skipping 'cpu_nms.c' Cython extension (up-to-date)
skipping 'gpu_nms.cpp' Cython extension (up-to-date)

then python2.7 test.py will
ImportError: Building module rcnn.cython.bbox failed: ["CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n"]

Could you help me?

**Comment by mnakhaeecourse** [comment]
> do `make` first

what do you mean by "make" ( for example in pycharm IDE)

**Comment by maycuatroi** [comment]
You can change 2 lines in setup.py to change compile method, and it works :). I hope it works your you.

https://github.com/deepinsight/insightface/pull/1032
