### ISSUE TITLE
Paid help request C++

### ISSUE THREAD

**Issue by AnjeliquePink** [deepinsight/insightface#399]
Hi,

We have small budget to use:

We need to use model from C++ and extract futures like in test.py

Is there anyone who expert on the both C++ and mxnet to spare a few hours?

Best

**Comment by hoavt-54** [comment]
Did you solve it?

**Comment by MyraBaba** [comment]
not exactly..  I have the c++ feature extraction but still miles to go..  

do you know how we can do this ? or wanna help?

**Comment by hoavt-54** [comment]
I started with the classification example from [Mxnet cpp](https://github.com/apache/incubator-mxnet/tree/master/example/image-classification/predict-cpp). And that's all you need. Did you try that? I got the same accuracy as I got on Python. However, on my dataset Facenet performs much better.

**Comment by stereomatchingkiss** [comment]
I solve the problem already, I use dlib to detect, align the face, compare features with deepinsight, you can find the example at [youtube](https://www.youtube.com/watch?v=eHAJh74z-fA&feature=youtu.be)

**Comment by MyraBaba** [comment]
Can you share the c++ part of the deepinsight ?  Or you used the python for recognition ?

**Comment by stereomatchingkiss** [comment]
> 
> 
> Can you share the c++ part of the deepinsight ? Or you used the python for recognition ?

Sure, source codes located at [github](https://github.com/stereomatchingkiss/blogCodes2/tree/master/mxnet_face_recognition)
Writing a blog for this small example, will post it at here after it is done.

If you need more helps, you can find my upwork account [at here](https://www.upwork.com/freelancers/~01f3549a37067cfdd0).

By the way, that youtube video,  the algorithm is finding most similar faces in 25 faces.

**Comment by MyraBaba** [comment]
Thanks.. I looked .  It developed in windows so little bir painfull for linux :)

will touch you

**Comment by stereomatchingkiss** [comment]
I know, this is one of the biggest drawback of c++ if you ask me(another is
tiny standard library).
You can try vcpkg, it is a package manager create for c++, maybe save you
some paint of building different libraries on different platform

MyraBaba <notifications@github.com> 於 2019年2月17日 週日 上午4:39寫道：

**Comment by stereomatchingkiss** [comment]
Post a [blog](https://qtandopencv.blogspot.com/2019/02/face-recognition-with-mxnet-dlib-and.html) to explain how to use opencv, dlib and mxnet to create a face recognition application.

**Comment by MyraBaba** [comment]
@stereomatchingkiss 

did you try to align face with mtcnn ? Is there any way in c++ align faces after detecting with mtcnn ? I am detecting with mtcnn so I have mtcnn square and the 5 points .

**Comment by stereomatchingkiss** [comment]
>did you try to align face with mtcnn ?

No, don't think it worth the troubles

>Is there any way in c++ align faces after detecting with mtcnn ?

There are a few ways

1. Write the alignment algorithm algorithm by yourself
2. Use the class in [cpp-align](https://github.com/deepinsight/insightface/tree/master/cpp-align)
3. Use the function of dlib--extract_image_chip

**Comment by MyraBaba** [comment]
is dlib extract image requires to detect faces again after mtcnn ? 

is there any small working example of the cpp-align usage ? 

best

**Comment by stereomatchingkiss** [comment]
>is dlib extract image requires to detect faces again after mtcnn ?

no, you can use face detector of dlib, it is a marvelous one

>small working example of the cpp-align usage

don't know, never tried it before, and don't have much interest

**Comment by MyraBaba** [comment]
We used dlib thats very good. 

But when you need to run on CPU dlib slower than the mtcnn (dlib non DNN face detection)

**Comment by stereomatchingkiss** [comment]
You can use opencv, dlib or mtcnn to detect face, alignment is an algorithm
independent with face detect algorithm

MyraBaba <notifications@github.com> 於 2019年2月19日 週二 下午9:06寫道：

**Comment by njvisionpower** [comment]
I implement the full insightface cpp pipeline recognition with camera, and also some optimization on mtcnn, make speed up than original python version:
[mxnet-insightface-cpp](https://github.com/njvisionpower/mxnet-insightface-cpp)
This project only depends on mxnet and opencv. Hope it's helpful.

**Comment by MyraBaba** [comment]
@stereomatchingkiss 

Hi,

We have 1080p RTSP video feed and 1060ti Nvidia card. It looks like a bit slow and can't reach the video feed even we reduce the fps 14.
Do we need to have another step to increase DlibCNN detector such as sending two frames at once?
what is your suggestion for 1080p RTSP video stream for fast and accurate detection?

**Comment by youthM** [comment]
> I implement the full insightface cpp pipeline recognition with camera, and also some optimization on mtcnn, make speed up than original python version:
> [mxnet-insightface-cpp](https://github.com/njvisionpower/mxnet-insightface-cpp)
> This project only depends on mxnet and opencv. Hope it's helpful.
Hi, the link can't be opened.

**Comment by youthM** [comment]
Hi, the link can't be opened. @njvisionpower

**Comment by symisc** [comment]
@MyraBaba  Checkout the SOD project which handle face detection and recognition at real-time on the CPU (No GPU needed). https://sod.pixlab.io

**Comment by stereomatchingkiss** [comment]
> 
> 
> @stereomatchingkiss
> 
> Hi,
> 
> We have 1080p RTSP video feed and 1060ti Nvidia card. It looks like a bit slow and can't reach the video feed even we reduce the fps 14.
> Do we need to have another step to increase DlibCNN detector such as sending two frames at once?
> what is your suggestion for 1080p RTSP video stream for fast and accurate detection?

I convert the model to onnx model and load it by opencv, works well, much easier to make it work compare with mxnet
