### ISSUE TITLE
my verification acc on lfw is only 95%？

### ISSUE THREAD

**Issue by ParadoxZW** [deepinsight/insightface#402]
I use mtcnn to detect face and face_preprocess.py to align, then use your pre-trained model 34e to do verification. But the accuracy I got is only 95%. Your readme.md mentioned that the accuracy should be 99%. Can you please tell me the parameters you set when you do the verification test, such as verification threshold, det_factor, det_minisize, det_threshold and det_type? Please help me. 
Best wishes!

**Comment by ParadoxZW** [comment]
And you cropped images to what size,112*112 or 112*96?

**Comment by ParadoxZW** [comment]
and alignment strategy？

**Comment by ParadoxZW** [comment]
What strategy do you use then? The scipt from Facenet github repo or the script from Mxnet-mtcnn github repo. Or is it the detect_type I use(I set 0, detect from beginning) that cause this low accuracy problem? When I set 1, the detect task collapsed. In some images, it didn’t recognize the face there. So I chose the 0 detect_type. What type do you use? And if it is 1, then can you please help me figure out how to do the detecting and aligning successfully?

**Comment by nttstar** [comment]
Check the code in face_preprocess.py

**Comment by ParadoxZW** [comment]
Can you please copy me the aligned lfw file so that I can test to make sure I did make wrong in the alignment procedure other than other steps?

**Comment by ParadoxZW** [comment]
I've found your pre-aligned lfw bin in Cloud. And I succeeded to achieve the acc of 99. But I still don’t know what align strategy you use to make this bin. The align strategy from facenet or the strategy from dlib?

**Comment by popeye315** [comment]
> 
> 
> I've found your pre-aligned lfw bin in Cloud. And I succeeded to achieve the acc of 99. But I still don’t know what align strategy you use to make this bin. The align strategy from facenet or the strategy from dlib?

I want to test pre-trained model on lfw. Where can I get the pre-aligned lfw bin? Can you please share the URL?

**Comment by xiakj** [comment]
@popeye315 I also want this lfw.bin

**Comment by zhangcong2009** [comment]
> @popeye315 I also want this lfw.bin

I finally got these files but I forgot how did I get that. In my impression, I probably got the lfw.bin from some link provided in this repo.
