### ISSUE TITLE
signal-to-noise level for the provided train dataset

### ISSUE THREAD

**Issue by ifangcheng** [deepinsight/insightface#406]
As noted in  README.md :

Training Data
All face images are aligned by MTCNN and cropped to 112x112:
Refined-MS1M@BaiduDrive, Refined-MS1M@GoogleDrive

Just wondering is the  Refined-MS1M a totally clean dataset？ is there any or how much noise  in it？

**Comment by nttstar** [comment]
I don't know. There must be some noises.
