### ISSUE TITLE
where can i find the insightface loss in this project

### ISSUE THREAD

**Issue by LiuWeiLun** [deepinsight/insightface#407]
In this project, there is a folder named 'losses'. But in this folder, i can only find the center loss. Where can i find the source code of the insightface loss and the sphereface loss in this project.

**Comment by LiuWeiLun** [comment]
I find the source code of the insightface loss. But about the sphereface loss, it is use the function mx.sym.LSoftmax(). In the Official website of the MXnet, i can not find this function. Could you please copy its resoures code for me? Thank you very much!

**Comment by insikk** [comment]
https://github.com/deepinsight/insightface/blob/master/src/train.py#L388

**Comment by LiuWeiLun** [comment]
thank you very much!
