### ISSUE TITLE
Verification or VR@FAR10^6 score on megaface

### ISSUE THREAD

**Issue by cavalleria** [deepinsight/insightface#409]
{
	"cmc" : 
	[
		[ 0, 275, 1000000 ],
		[ 0.9857323169708252, 0.9957365989685059, 1.0 ]
	],
	"roc" : 
	[
		
		[
			0.0,
			9.999999939225290e-09,
			1.999999987845058e-08,
			5.999999785899490e-08,
			2.799999947455944e-07,
			0.0006921099848113954,
			1.0
		],
		
		[
			0.8836455345153809,
			0.9026387333869934,
			0.9641355276107788,
			0.9759168028831482,
			0.9859926700592041,
			0.9960035085678101,
			1.0
		]
	],
	"traditional_cmc" : 
	[
		[ 0, 182, 1000079 ],
		[ 0.9860869646072388, 0.9961445331573486, 0.9999974966049194 ]
	]
}
how can i get VR@FAR10^6(because no FAR1e-6 in roc block)?
thx

_Originally posted by @cavalleria in https://github.com/deepinsight/insightface/issues/251#issuecomment-408306183_

**Comment by nttstar** [comment]
should be 0.9859926700592041

**Comment by cavalleria** [comment]
@nttstar thx for your reply. I don't quite understand  why the VR@FAR10^6 is 0.9859926700592041.Is this accurate enough? For example, the following instance, what is VR@FAR10^6 ? thx
{
    "cmc" :
    [
        [ 0, 9360, 1000000 ],
        [ 0.9880820512771606, 0.9980863332748413, 1.0 ]
    ],
    "roc" :
    [

        [
            0.0,
            1.999999987845058e-08,
            5.999999785899490e-08,
            7.999999951380232e-08,
            1.399999973727972e-07,
            4.804999844054691e-05,
            1.0
        ],

        [
            0.8240624070167542,
            0.9400262832641602,
            0.9533696770668030,
            0.9740942716598511,
            0.985042393207550,
            0.9950531721115112,
            1.0
        ]
    ],
    "traditional_cmc" :
    [
        [ 0, 5043, 1000079 ],
        [ 0.9877681136131287, 0.9977965950965881, 0.9999983310699463 ]
    ]
}

**Comment by nttstar** [comment]
select the closest rate to 1e-6 which is `1.399999973727972e-07` in your last case

**Comment by HaoLiuHust** [comment]
@cavalleria what's your train dataset and backbone?
