### ISSUE TITLE
finetune with arcloss

### ISSUE THREAD

**Issue by DevelopJoy** [deepinsight/insightface#410]
I try to train a model with r50 on 'faces_emore' dataset and set --emb-size=1024;
firstly, I train a new model with softmax, and secondly, I finetune it with arcloss; but got a problem like:
mxnet.base.MXNetError: [09:58:00] src/operator/nn/../tensor/../elemwise_op_common.h:123: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected [1024,512], got [1024,25088]

How to fix the problem?
thank you!

**Comment by DevelopJoy** [comment]
Solved， VERSION="E" ，forgot to set

**Comment by cccober** [comment]
what's the "VERSION="E""?
thank you!

**Comment by cccober** [comment]
I set  version_output='E' but still got the same problem
expected [512,512], got [512,25088]
