### ISSUE TITLE
pre-trained model for dataset_merge.py

### ISSUE THREAD

**Issue by test4fest** [deepinsight/insightface#412]
I am running dataset_merge.py in order to remove duplicate images from two datasets. 
I wonder if I can use any pre-trained model? 
when I download LResNet50E-IR model and put it in the folder "../model/LResNet50E-IR"
do I need to add epoch number at the end of model path or I have to change model name in "LResNet50E-IR, 50".
I have tried both cases and got the following error:

loading models/model-r50-am-lfw/model-symbol 50
Traceback (most recent call last):
  File "src/data/dataset_merge.py", line 292, in <module>
    main(args)
  File "src/data/dataset_merge.py", line 102, in main
    sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/model.py", line 438, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py", line 2594, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [09:43:54] src/io/local_filesys.cc:199: Check failed: allow_null  LocalFileSystem::Open "models/model-r50-am-lfw/model-symbol-symbol.json": No such file or directory

Thanks for providing such a great model.

**Comment by Gabit07** [comment]
> I am running dataset_merge.py in order to remove duplicate images from two datasets.
> I wonder if I can use any pre-trained model?
> when I download LResNet50E-IR model and put it in the folder "../model/LResNet50E-IR"
> do I need to add epoch number at the end of model path or I have to change model name in "LResNet50E-IR, 50".
> I have tried both cases and got the following error:
> 
> loading models/model-r50-am-lfw/model-symbol 50
> Traceback (most recent call last):
> File "src/data/dataset_merge.py", line 292, in 
> main(args)
> File "src/data/dataset_merge.py", line 102, in main
> sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
> File "/usr/local/lib/python2.7/dist-packages/mxnet/model.py", line 438, in load_checkpoint
> symbol = sym.load('%s-symbol.json' % prefix)
> File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py", line 2594, in load
> check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
> File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 252, in check_call
> raise MXNetError(py_str(_LIB.MXGetLastError()))
> mxnet.base.MXNetError: [09:43:54] src/io/local_filesys.cc:199: Check failed: allow_null LocalFileSystem::Open "models/model-r50-am-lfw/model-symbol-symbol.json": No such file or directory
> 
> Thanks for providing such a great model.

I have the same problem. DId you solve?
