### ISSUE TITLE
How to change image size to 160x160

### ISSUE THREAD

**Issue by larsonwu0220** [deepinsight/insightface#416]
I want to training mobilefacenet with image size 160x160. I have modified mobilefacenet structure, but the data size is 112x112.
How to change size of dataset in Dataset Zoo?
Thanks~

**Comment by nttstar** [comment]
Set image-size to 160 in training script, we already support this.  (Not real high resolution, but 112x112 images will be resized to 160)

**Comment by larsonwu0220** [comment]
@nttstar  Thanks for your reply. 
But I only use your dataset in the datazoo，my training script is tensorflow version : [MobileFaceNet_TF](https://github.com/sirius-ai/MobileFaceNet_TF).
I need the original data resize to 160x160 and feed to mobilefacenet_tf.
Could you offer MS1M-refine-v2 or VGGface2 etc with size 160x160，or how to convert .rec and .idx file to change size ？
Thank you so much.

**Comment by LCorleone** [comment]
+1
I also want to know how to convert .rec and .idx file into real image.

**Comment by leolordwz** [comment]
> +1
> I also want to know how to convert .rec and .idx file into real image.

[612](https://github.com/deepinsight/insightface/issues/612)

**Comment by guli333** [comment]
Hello!
Do you support setting the image-size (ex. to 64x64) in training script in Insightface-Pytorch?

Thanks ~
