### ISSUE TITLE
face preprocess before send to model.get_feature ?

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#418]
Hi,

I am porting to inference to c++ and successfully move forwarding.

I need to understan what I need to be take steps before I send the detected faces to the model?

I saw in python : 

>   def get_input(self, face_img):
    ret = self.detector.detect_face(face_img, det_type = self.args.det)
    if ret is None:
      return None , None
    bbox, points = ret
    if bbox.shape[0]==0:
      return None
    bbox = bbox[0,0:4]
    points = points[0,:].reshape((2,5)).T
    #print(bbox)
    #print(points)
    nimg = face_preprocess.preprocess(face_img, bbox, points, image_size='112,112')
    nimg = cv2.cvtColor(nimg, cv2.COLOR_BGR2RGB)
    aligned = np.transpose(nimg, (2,0,1))
    return aligned , points

so:
1- detect face
2- nimg = face_preprocess.preprocess(face_img, bbox, points, image_size='112,112')
3- nimg = cv2.cvtColor(nimg, cv2.COLOR_BGR2RGB)
 4- aligned = np.transpose(nimg, (2,0,1))

also I found FacePreprocess.h . in the cppalign folder.

Is this FacePreprocess.h is enough for preprocessing before sending get_features . ?

**Comment by Lane565** [comment]
I use python, and I just send the cropped face_images to def get_input.

**Comment by MyraBaba** [comment]
get_input making preprocess & detect faces etc.

I need c++ counterpart for get_input

**Comment by deimsdeutsch** [comment]
@Lane565 

Why would you run 2 face detectors ?
First to detect and then to align.. this is not efficient.

**Comment by Lane565** [comment]
I modified the codes and ran face detector once

**Comment by Lane565** [comment]
I modified the codes and ran face detector once only.

**Comment by Lane565** [comment]
I changed the codes and ran face detector once only.

**Comment by deimsdeutsch** [comment]
@Lane565 
Are you aligning the face on the detector or later while matching ?

**Comment by Lane565** [comment]
I employ recognition algorithms based on the boxes of MTCNN（including both face detection and alignment）to extract features, then  do classification.

**Comment by barzan-hayati** [comment]
> 3- nimg = cv2.cvtColor(nimg, cv2.COLOR_BGR2RGB)

Is it necessary to do 3'th step before feature extraction?
