### ISSUE TITLE
When test, Why normalize using the whole test dataset's features?

### ISSUE THREAD

**Issue by huyangc** [deepinsight/insightface#42]
I think the codes [here](https://github.com/deepinsight/insightface/blob/master/src/eval/verification.py#L240-L249) shows that you normalize each feature on the whole test dataset's features. 

It is some tricks or I misunderstood the codes?

**Comment by nttstar** [comment]
This is just for calculating average L2 norm of all test feature embeddings.

**Comment by huyangc** [comment]
thank you! And I have another question about the input image. As the code [here](https://github.com/deepinsight/insightface/blob/master/deploy/test.py#L16-L22) shows that the only thing to do is to input the image cropped by detection bounding box, am I right? No need to enlarge the bounding box? Because some tight box only contains the face.

And thank you very much to implement so many losses function in mxnet, because I am a big fans of mxnet.

**Comment by nttstar** [comment]
some margin is preferred.

**Comment by huyangc** [comment]
Thanks!
