### ISSUE TITLE
RuntimeError: simple_bind error. Arguments:

### ISSUE THREAD

**Issue by horizonheart** [deepinsight/insightface#421]
![image](https://user-images.githubusercontent.com/16372054/47849157-9fb13f00-de0b-11e8-8a08-83935ba43eb6.png)
![image](https://user-images.githubusercontent.com/16372054/47849177-ab9d0100-de0b-11e8-8e1e-6b80642ff382.png)
![image](https://user-images.githubusercontent.com/16372054/47849194-b9eb1d00-de0b-11e8-94f1-994fed78a27b.png)

**Comment by Simplesss** [comment]
I have similar questions.How did you solve it?

**Comment by SirLPS** [comment]
I have the same problem.Who has solved it? Thanks a lot!
