### ISSUE TITLE
How to do batch inference?

### ISSUE THREAD

**Issue by nmzszxsl01** [deepinsight/insightface#423]
In deploy/face_embedding.py, the inference code is like this,
"
      input_blob = np.expand_dims(aligned, axis=0)
      data = mx.nd.array(input_blob)
      db = mx.io.DataBatch(data=(data,))
      self.model.forward(db, is_train=False)
      _embedding = self.model.get_outputs()[0].asnumpy()
"
Now I get a lot of pictures to get embeddings, how can I do batch inference to accelerate the whole process.

**Comment by Edwardmark** [comment]
@nttstar how can I do batch inference for detection using mtcnn?

**Comment by AnakTeka** [comment]
+1

Is there any way to do batch inference when using mtcnn?
