### ISSUE TITLE
test.py detecting face fails

### ISSUE THREAD

**Issue by DANNALI35** [deepinsight/insightface#424]
i am trying to use 'test.py' to infer the original lfw images, but 'model.get_input(img)' sometimes outputs 'None', meaning **Mtcnn model fails to locate the face and crop it**. there are several hundreds of images among Ifw that Mtcnn model failed to detect the face.

any idea that i can always manage to get the cropped face? or if i just resize the original Ifw images to 112*112 without face alignment, dose this affect the insightface performance a lot?

**Comment by Lane565** [comment]
I encountered the same problem as you, waiting for answers !

**Comment by zylxadz** [comment]
I have the same problem as you when testing age model.
Appreciate for answers,too!
