### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'？

### ISSUE THREAD

**Issue by yang0817manman** [deepinsight/insightface#426]

**Comment by yang0817manman** [comment]
hello,this problem have been solved.The training dataset is right but the batchsize set too large.

**Comment by yang0817manman** [comment]
hi ,the code is running well,but i cannot see the change of loss value on the screen,merely acc.How to modify the codes make loss changes print on the screen?Can you help me? @nttstar

**Comment by xinxliu** [comment]
Hi, I meet the same problem, how you solve this?

**Comment by xinxliu** [comment]
> Make sure you're using the right training dataset

I met this problem too. I have downloaded the recommended dataset MS1M-Arcface from https://pan.baidu.com/s/1S6LJZGdqcZRle1vlcMzHOQ. Could you please help me with this?

**Comment by yang0817manman** [comment]
Is imgsize true?112,112.
