### ISSUE TITLE
About noise in facescrub list

### ISSUE THREAD

**Issue by tiandunx** [deepinsight/insightface#430]
Hi, thanks for your noise text file. I found that Peggy_McCay_48889.png, which is not included in facescrub_noises.txt,, is not photo of Peggy_McCay. It's Aneta Corsaut. Can you update the facescrub_noise.txt?
.

**Comment by khawar-islam** [comment]
@tiandunx You can download cleaned version from here, if dataset is helpful for you, please consider to cite it
https://github.com/khawar-islam/FPVT_BMVC22
