### ISSUE TITLE
two ids  belong to the same people in faces_emore

### ISSUE THREAD

**Issue by guangdongliang** [deepinsight/insightface#431]
After got the "faces_emore"  , I extracted all the images from it and  used the model named "LResNet100E-IR,ArcFace@ms1m-refine-v2"  to get their embeddings . For each id ,I calculated and normalized its mean embedding , however there were some ids whose  cosine distance of mean embeddings was around 0.9(very close) . after my checking ,they were actually the same person!
![image](https://user-images.githubusercontent.com/16490080/48110550-c6e29300-e287-11e8-92e2-9c5fd206bf16.png)

**Comment by AmigoCDT** [comment]
I don't know much about the faces_emore. Following is my thought about GLint Dataset.
In Glint Dataset:
    I think this is normal. When I try to clean the Glint dataset, I found about 700 pairs ID are same person(my similar threshhold is 0.8). Maybe the 700 pairs IDs or 1400 IDs are too few for totally 170k IDs to make much effect.
    After clean Glint dataset by merge similar IDs, my training result also provide my thought. This doesn't matter much cause the count is few for total ID num. the cfp_fp acc just get 0.1%~0.2% improvement.

**Comment by AmigoCDT** [comment]
maybe you can count the similar IDs, get the ratio to total IDs num.

**Comment by guangdongliang** [comment]
> I don't know much about the faces_emore. Following is my thought about GLint Dataset.
> In Glint Dataset:
> I think this is normal. When I try to clean the Glint dataset, I found about 700 pairs ID are same person(my similar threshhold is 0.8). Maybe the 700 pairs IDs or 1400 IDs are too few for totally 170k IDs to make much effect.
> After clean Glint dataset by merge similar IDs, my training result also provide my thought. This doesn't matter much cause the count is few for total ID num. the cfp_fp acc just get 0.1%~0.2% improvement.

I agree with you . But my key point is that why the model trained from faces_emore can still be used to clean this dataset . I got about 3000 similar pairs using the threadhold 0.65.

**Comment by xiang-burlington** [comment]
Very useful information. Thanks for sharing.

By the way, how did you extract images from the binary file? Is there any tools for such purpose or you wrote your own code? I have been looking for such tools for a while and will greatly appreciate it if you share the information.

**Comment by HaoLiuHust** [comment]
@xiang-burlington you can use recordio.unpack to unpack a record, and the use mx.image.imdecode to decode it to an image, you can find it in the data iterator part

**Comment by AmigoCDT** [comment]
@xiang-burlington  read the insightface/src/data/face2rec.py . It is easy to write a script unpacking the emore.rec

**Comment by xiang-burlington** [comment]
@AmigoCDT @HaoLiuHust That's very helpful. Thanks a lot.

**Comment by xiang-burlington** [comment]
Just in case anyone has the same interest as mine of extracting training images from rec file, below is the code that do the job, please note that the outcome are bgr images, not rgb:
https://github.com/TreB1eN/InsightFace_Pytorch/blob/master/data/data_pipe.py

**Comment by guangdongliang** [comment]
> I don't know much about the faces_emore. Following is my thought about GLint Dataset.
> In Glint Dataset:
> I think this is normal. When I try to clean the Glint dataset, I found about 700 pairs ID are same person(my similar threshhold is 0.8). Maybe the 700 pairs IDs or 1400 IDs are too few for totally 170k IDs to make much effect.
> After clean Glint dataset by merge similar IDs, my training result also provide my thought. This doesn't matter much cause the count is few for total ID num. the cfp_fp acc just get 0.1%~0.2% improvement.

Thank you for your reply!
      do you have the acc of model trained on cleaned glint on cfp_fp or lfw  ? mine on cfp_fp is 96.57% . because this value is nearly 100% ,so 0.1%~0.2% improvement is worthy.

**Comment by clhne** [comment]
> I don't know much about the faces_emore. Following is my thought about GLint Dataset.
> In Glint Dataset:
> I think this is normal. When I try to clean the Glint dataset, I found about 700 pairs ID are same person(my similar threshhold is 0.8). Maybe the 700 pairs IDs or 1400 IDs are too few for totally 170k IDs to make much effect.
> After clean Glint dataset by merge similar IDs, my training result also provide my thought. This doesn't matter much cause the count is few for total ID num. the cfp_fp acc just get 0.1%~0.2% improvement.

May I know what method did u use to clean the Glint dataset ?

Thanks.

**Comment by clhne** [comment]
> > I don't know much about the faces_emore. Following is my thought about GLint Dataset.
> > In Glint Dataset:
> > I think this is normal. When I try to clean the Glint dataset, I found about 700 pairs ID are same person(my similar threshhold is 0.8). Maybe the 700 pairs IDs or 1400 IDs are too few for totally 170k IDs to make much effect.
> > After clean Glint dataset by merge similar IDs, my training result also provide my thought. This doesn't matter much cause the count is few for total ID num. the cfp_fp acc just get 0.1%~0.2% improvement.
> 
> Thank you for your reply!
> do you have the acc of model trained on cleaned glint on cfp_fp or lfw ? mine on cfp_fp is 96.57% . because this value is nearly 100% ,so 0.1%~0.2% improvement is worthy.

I get the cfp_fp accuracy of 98.80% when use ms1m training set.
