### ISSUE TITLE
landmarks annotations of vggface2 dataset

### ISSUE THREAD

**Issue by lbwang2006** [deepinsight/insightface#44]
can you share the landmarks annotations of vggface2 dataset？

**Comment by nttstar** [comment]
It was simply achieved by MTCNN.

**Comment by lbwang2006** [comment]
I have tried, but only 50w faces of images were detected, totally 300w images?

**Comment by nttstar** [comment]
You can check `src/align/align_insight.py`, this is a common face image alignment script which uses tf MTCNN.

**Comment by lbwang2006** [comment]
so how many face images are detected？

**Comment by nttstar** [comment]
almost all

**Comment by lbwang2006** [comment]
I use caffe mtcnn, and the performance is not so good, this is the mtcnn parameters you used for vggface2
minsize = 20
threshold = [0.6,0.7,0.9]
factor = 0.85
