### ISSUE TITLE
about setting lr-steps?

### ISSUE THREAD

**Issue by yang0817manman** [deepinsight/insightface#442]
hi,thanks for your sharing.I want to set "ls-steps" value by myself and trained res50 with ms1m dataset but the error appeared in running.the command lines settings and the error are respectively as following:
"CUDA_VISIBLE_DEVICES='0' python -u train_softmax.py --network r50 --loss-type 4 --margin-m 0.5 --data-dir ../datasets/faces_ms1m_112x112 --per-batch-size 8 ---lr-steps [80000,150000,200000] --prefix ../model-r50"

"ver agedb_30
Traceback (most recent call last):
  File "train_softmax.py", line 502, in <module>
    main()
  File "train_softmax.py", line 499, in main
    train_net(args)
  File "train_softmax.py", line 427, in train_net
    lr_steps = [int(x) for x in args.lr_steps.split(',')]
ValueError: invalid literal for int() with base 10: '[80000'
"
Can you help me? Thanks a lot.

**Comment by nttstar** [comment]
--lr-steps '80000,150000,200000'

**Comment by yang0817manman** [comment]
Thanks.

**Comment by TimVerion** [comment]
Warning!  Unknown mxnet op:_copy
Solved?
