### ISSUE TITLE
model size of mobilefacenet is 16209K

### ISSUE THREAD

**Issue by jstzwjr** [deepinsight/insightface#454]
train command :  --network y1  --emb-size 512     model size:225,333KB
after remove the fc layer params by deploy/model_slim.py, the model size reduce to 53,849KB

train command :  --network y1  --emb-size 128     model size:16,209KB
after remove the fc layer params by deploy/model_slim.py, the model size reduce to 16,209KB, which is still much bigger than 4M

What can I do now? Thanks!

**Comment by nttstar** [comment]
Last fc layer was not removed in your second case as the model size was not changed.

**Comment by wjr1990** [comment]
> Last fc layer was not removed in your second case as the model size was not changed.

The model size was 59,080KB before i reduced the last fc layer, I wrote it incorrectly in the above question.

**Comment by nttstar** [comment]
Make sure about ``--version-output GDC``
