### ISSUE TITLE
How about the effect of intra loss

### ISSUE THREAD

**Issue by huyangc** [deepinsight/insightface#456]
As I see, the intra loss is update in the code, and for which I know that it is to constrained the same class's cos distance as little as possible. But the Softmax layer also do the same thing. I am curious of the effect of the intra loss. Does anyone use that loss to do experiment?

**Comment by nttstar** [comment]
You may check our latest arcface paper on arxiv

**Comment by huyangc** [comment]
After reading the new arxiv version, I get that. Thanks for the great job.
