### ISSUE TITLE
Evaluation/IJB/ 中的代码能提供下国内的下载地址吗 

### ISSUE THREAD

**Issue by tianxingyzxq** [deepinsight/insightface#460]
Evaluation/IJB/ 中的代码能提供下国内的下载地址吗, 或者把tar包分割下，dropbox上下载经常断 @nttstar

**Comment by jiankangdeng** [comment]
https://pan.baidu.com/s/1oer0p4_mcOrs4cfdeWfbFg
我们没有release 数据的权限，这个只是为了方便大家得到 notebook 的figure 和 table

**Comment by tianxingyzxq** [comment]
好的，非常感谢！
