### ISSUE TITLE
Edge Computing ie: Raspberry 3B+ or Hikey970

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#461]
Hi,

Is there anybody can run the facerecognition (ie: deploy/test.py) on any Edge devices like Raspberry 3 B+ pr Hikey970 ? Any experience or benchmark ?

What would be the suggestion for Egde Device for det & recognition ?

Best

**Comment by MyraBaba** [comment]
what did you mean for face_recognition ? is it a script in thsi repo ?

**Comment by kaisark** [comment]
@MyraBaba  https://github.com/ageitgey/face_recognition

**Comment by MyraBaba** [comment]
It is python based (mainly dlib) . right?

**Comment by Evan-D** [comment]
> It is python based (mainly dlib) . right?

Yes,u can use them on pi3 according to resize the pic

**Comment by shree970** [comment]
You can implement on any edge device using this OS: http://shunyaos.org/.
