### ISSUE TITLE
gpu memory usage

### ISSUE THREAD

**Issue by changya1990** [deepinsight/insightface#463]
Hi，thanks for share your work. When i used this code to get face embeddings for a large number of  images(~4w) continuously, the GPU memory usage are always increased until it‘s full, and then repeat this process. (ps. the images' shorter side are resized to a fixed value)
Is this normal? How to solve it if not.

![image](https://user-images.githubusercontent.com/41245857/49555026-35734900-f939-11e8-8311-53c64fc6ee4b.png)
![image](https://user-images.githubusercontent.com/41245857/49555039-458b2880-f939-11e8-8f45-a53c7c47e8c3.png)

**Comment by khanhnt** [comment]
Hi @changya1990 , did you find any solution for this issue ? we are facing the same problem.

**Comment by xingha** [comment]
we are facing the same problem.

**Comment by Chenyangzh** [comment]
Facing the same problem! Maybe it's a feature of mxnet for higher performance.

**Comment by Chenyangzh** [comment]
Finally, I found the reason is the irregular size of images. I just resize and pad images into a same size.

**Comment by njho** [comment]
Is this using the face analysis from this URL?
http://insightface.ai/build/examples_face_analysis/demo_analysis.html

Having the same issue where it seems to be taking a very large amount of GPU memory for inference
