### ISSUE TITLE
A bug in FaceImageIter

### ISSUE THREAD

**Issue by cheerss** [deepinsight/insightface#464]
An instance of FaceImageIter with shuffle works well, however, an instance without shuffle would throw an error because label in dataset is a list rather than a number.(rec dataset is generated with face2rec.py)

When Shuffle=True, in FaceImageIter.next_sample(), 
`if not isinstance(label, numbers.Number):
                label = label[0]`
ensure label must be a number.

When shuffle=False, the clause won't be executed, `batch_label[i][:] = label` in FaceImageIter.next() would raise an exception as `operands could not be broadcast together with remapped shapes [original->remapped]: (2,) and requested shape (1,)`

**Comment by orlevit** [comment]
@cheerss @nttstar 
I am facing the same problem.
Have you solved the problem? would you kindly share the solution?

Thanks!
