### ISSUE TITLE
cfp dataset is different? and the .rec file is RGB while .bin is BGR?

### ISSUE THREAD

**Issue by LCorleone** [deepinsight/insightface#467]
hi, excellent work! 
but i find that the bin data of cfp-ff and cfp-fp is different in face_emore file and face_ms1m_112x112 file.
Maybe the alignment is different? i use the same model to test and the acc is different.
thanks.

**Comment by LCorleone** [comment]
Another question.
I found that the .rec file in face_emore and face_ms1m_112x112 is of RGB format. while for .bin file, they are  BGR format. Am I right?
if yes, I donot find any transformation in the verification step. should you transform the BGR into RGB?
thanks!

**Comment by SueeH** [comment]
> Another question.
> I found that the .rec file in face_emore and face_ms1m_112x112 is of RGB format. while for .bin file, they are BGR format. Am I right?
> if yes, I donot find any transformation in the verification step. should you transform the BGR into RGB?
> thanks!
recently,i also checked this. Function “image_encode” in face2rec.py did this(call face_preprocess).So I guess data in .rec is BGR format. How did you find .rec file is RGB format？
