### ISSUE TITLE
Cannot reproduce the results in IJB

### ISSUE THREAD

**Issue by luzai** [deepinsight/insightface#470]
Dear insightface: 
I have tried python2/python3 and mxnet-cu80/mxnet-cu90. But I cannot reproduce the results in <https://github.com/deepinsight/insightface/blob/master/Evaluation/IJB/IJBC_Evaluation_MS1MV2.ipynb>. 

After running through the notebook, my ROC curve is somewhat strange: 
![image](https://user-images.githubusercontent.com/14788650/49707221-63bc9580-fc65-11e8-8e75-236b217e9725.png)
![image](https://user-images.githubusercontent.com/14788650/49707234-70d98480-fc65-11e8-952d-a658a3155633.png)

If I directly use the downloaded results file (*.npy), rather than the file generated by myself, the ROC curve is normal. 
![image](https://user-images.githubusercontent.com/14788650/49707351-e9d8dc00-fc65-11e8-9a61-6c20a537e0f0.png)

I also investigate the features at images level, the cluster pattern can be observed, which means that the extracted features of the starting 128 images are correct.
![image](https://user-images.githubusercontent.com/14788650/49707467-5653db00-fc66-11e8-80cf-d36099cde518.png)

When reproducing, 
I modify `similarity_score = np.sum(feat1 * feat2, -1)` to `similarity_score = np.sum(feat1 * feat2, -1).flatten()`. For python2, I do not change anything else; for python3, I modifies  
`img_input_feats = img_feats[:,0:img_feats.shape[1]/2]` to `img_input_feats = img_feats[:,0:img_feats.shape[1]//2]`. 

Could you help me find out the problem? 
Thanks a lot!

**Comment by luzai** [comment]
I try to reimplement the procedure of evaluation.
In [test_ijbc2](https://github.com/luzai/insightface/blob/master/src/test_ijbc2.py), the ROC curve is strange; And in [test_ijbc3](https://github.com/luzai/insightface/blob/master/src/test_ijbc3.py) the ROC curve is normal. 
And the same in pytorch version, [test_ijbc2](https://github.com/luzai/InsightFace_Pytorch/test_ijbc2.py) [test_ijbc3](https://github.com/luzai/InsightFace_Pytorch/test_ijbc3.py).

**Comment by jiankangdeng** [comment]
Could you please help to try this?
 
score[s] = similarity_score
-->
score[s] = similarity_score.flatten()

Actually, I never got the wrong curves by the code ......

**Comment by luzai** [comment]
It seems the there is some problem in `np.loadtxt`. There is no problem in the label `p11` loaded by myself. 
![image](https://user-images.githubusercontent.com/14788650/50040431-382f1600-007e-11e9-8e66-6ef1cbdb30e4.png)
Could you tell me the version of numpy you use?

**Comment by nttstar** [comment]
It is numpy-1.13.1 on my server and it works well after ``score[s] = similarity_score.flatten()``

**Comment by luzai** [comment]
I think it is related to the version of numpy. 

![image](https://user-images.githubusercontent.com/14788650/50042178-7edf3900-009b-11e9-950b-b326390533e1.png)

**Comment by shiyuanyin** [comment]
I have the same error ,but the different numpy version ,the out is the same 
,finally, I found the reason ,  because dtype=str ,save error , I modify int , the out t1 t2 is correct.
pairs = np.loadtxt(path, dtype=int)


def read_template_pair_list(path):
    pairs = np.loadtxt(path, dtype=int)
    t1 = pairs[:,0].astype(np.int)
    t2 = pairs[:,1].astype(np.int)

**Comment by Light--** [comment]
i also can not reproduce the result, details: [here](https://github.com/deepinsight/insightface/issues/1228)
even change numpy version...
