### ISSUE TITLE
how about the compression rate and time consumption about translate data to rec file?

### ISSUE THREAD

**Issue by zjz19960805** [deepinsight/insightface#477]
Hello, I got pictures of more than 200G to be my dataset. Three days before I use face2rec.py to translate them into rec files. But until now I still not finish my translation. How much time did you consume when you translate VGG data into rec file?

**Comment by nttstar** [comment]
Several hours. Not including the time of face alignment.

**Comment by ddxu** [comment]
@nttstar when I use face2rec.py to generate my rec file, the speed is really slow, about 25s per 1000 images. How to speed up ?

![screenshot from 2019-02-01 09-40-01](https://user-images.githubusercontent.com/10184043/52097429-f9d9c000-2605-11e9-919f-72a50c36a537.png)

The params are : 
 args.prefix = os.path.abspath(args.prefix)
 args.recursive = True
 args.shuffle = True
args.num_thread = 4

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md
