### ISSUE TITLE
Toy Example in Paper

### ISSUE THREAD

**Issue by KeremTurgutlu** [deepinsight/insightface#479]
I am trying to replicate the toy example plots in order to see class center vectors on a circle using 2D features. I am currently using resnet backbone + custom head with a weight matrix (2 - n_features, 10 n_classes) with MNIST data but can't achieve very good results as I would using a larger feature size like 512. What am I am missing in order to reproduce those 2D toy plots in the paper?

Thanks

**Comment by borisgribkov** [comment]
The same problem, I have used LeNet++ with ArcFace (but caffe version) on MNIST and got about 99.5% with 128 dim output, reduce the output to 2 for visualization -> no convergence at all

**Comment by amirhfarzaneh** [comment]
Which optimizer are you guys using? I had better luck with Adam!
