### ISSUE TITLE
Input settings and network question

### ISSUE THREAD

**Issue by maria8899** [deepinsight/insightface#48]
Hi,
I have 2 questions related to the paper:
- section 3.2.1, can you confirm when you say"instead of conv 7x7 and stride 2", that are you referring to ResNet first convolution layer? You are changing to 3x3 stride 1 so that the input can be 112x112?
- In table 10, which CNN do you use for Softmax and CosineFace?
Thank you

**Comment by nttstar** [comment]
1. All input is 112x112 and we do not reduce the feature map resolution in its first convolution block.
2. LResNet100E.

**Comment by maria8899** [comment]
Thanks for the quick answer. Yes, I understand you do not reduce the feature map resolution, to do so you are only changing the first convolution layer parameters.
