### ISSUE TITLE
CELEB-500K数据

### ISSUE THREAD

**Issue by yhl41001** [deepinsight/insightface#482]
你好，请问训练是否使用了CELEB-500K数据集，使用的话数据是不是做了清洗，能否提供一下清洗后的信息？

**Comment by nttstar** [comment]
没有

**Comment by TccccD** [comment]
@yhl41001 你好 我用了你们提供的CASIA-Webface数据，用FaceImageIter()读取，然后将数据根据FaceImageIter.seq切分成train和val，但是训练时training能到0.99，eval只能0.65

**Comment by dl8207531** [comment]
@yhl41001请问是否有CELEB-500K原始数据？如果有能否提供下，我可以来清洗

**Comment by yhl41001** [comment]
@dl8207531 不好意思，我现在手上也没有这个数据！

**Comment by yhl41001** [comment]
@dl8207531 CELEB-500K原始数据我简单下载了一部分，发现数据非常脏！

**Comment by dl8207531** [comment]
@yhl41001 能提供下地址吗？我们共同看看能不能清洗下

**Comment by yhl41001** [comment]
@dl8207531 这个我网上找到了url，然后自己用脚步下载，https://github.com/JiajiongCao/CELEB-500K，这个地址里包含了下载的脚本和url的下载链接。但脚本有错误，需要自己修改一下。

**Comment by dl8207531** [comment]
@yhl41001 谢谢 我下载下先

**Comment by yhl41001** [comment]
@dl8207531 好，你看看数据是不是很脏，可以在这里回复一下！辛苦啦！

**Comment by dl8207531** [comment]
昨天下了快一天，翻墙下才下了5000多张图，太慢了，这个速度得几年才下完，哎
另外这个数据确实脏需要长时间清洗

**Comment by yhl41001** [comment]
@dl8207531 是啊，我这边下载的速度还凑合，就是数据太脏，而且有些数据不能下载！

**Comment by ctgushiwei** [comment]
@yhl41001 how to download celeb500k?
