### ISSUE TITLE
MTCNN is not robust enough in application, any better face detection algorithm?

### ISSUE THREAD

**Issue by Lane565** [deepinsight/insightface#483]
Help~

**Comment by nttstar** [comment]
Yeah, please keep eyes on insightface.

**Comment by MyraBaba** [comment]
than ,what is the recommended face DetecTion algorithm ? is it already placed in the insightface ?

Best

**Comment by uday60** [comment]
@nttstar Any update ?

**Comment by GNAYUOHZ** [comment]
@nttstar Any update ?+1

**Comment by jamessmith90** [comment]
@nttstar 
Any update ?

**Comment by nttstar** [comment]
soon
