### ISSUE TITLE
Is 112x112 aligned training set used directly for training

### ISSUE THREAD

**Issue by WIll-Xu35** [deepinsight/insightface#484]
In the readme file, download links to aligned and cropped ms1m and vgg2 are provided.

I'm wondering if those 112x112 aligned images given are used directly to train the model or not. I think during inference, after mtcnn procedure, a warp process (using original image and 5 landmark points) is necessary for the model to have a good performance. But the training set description never mentioned this and says any mtcnn will work. So I'm not sure if those data are warped or not.

Can anyone explain this to me.
Much appreciated.

**Comment by nttstar** [comment]
Training and testing both need aligned faces.
