### ISSUE TITLE
Cannot achieve similar result from pretrained Caffe model

### ISSUE THREAD

**Issue by WIll-Xu35** [deepinsight/insightface#485]
I have tested the pretrained LResNet50E-IR mxnet model on my own dataset and it works very well. However, when I use the same mtcnn and alignment method, then feed the aligned image to the pretrained caffe model. The embeddings looks completely different compared with the embeddings of the same image from the mxnet model. And the distance between different people's images is not much larger than the same people's images, and sometimes it's even smaller.

I'm wondering if there is any difference between those two models, maybe they need different input channel order, different normalization method? And another question, is the transformed caffe model supposed to have the exact same output as the mxnet model?

Does anyone has anyone idea what may have caused this?
Thanks

**Comment by nttstar** [comment]
We do not care about Caffe models right now.

**Comment by xiakj** [comment]
@WIll-Xu35 have you repaired this problem? how?

**Comment by WIll-Xu35** [comment]
@xiakj mxnet model contains image preprocessing while caffe does not. In order to get the same output from caffemodel, for every pixel input value, minus 127,5 and then divides by 128.
