### ISSUE TITLE
is there any improvement for inference with mxnet+NNPACK 

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#486]
Is there any body tested inference mxnet+nnpack ? any improvement ?

is it worth to try for improve inference speed?

**Comment by szad670401** [comment]
TVM is a light weight better choice to deploy model.
I haved released a deploy tutorial in wiki.

**Comment by MyraBaba** [comment]
I saw the TVM instruction thanks.

Is it possible to make below with your c++ code ? 
preproces image (get_input)
get feature
calculate dist and sim.

have you a minimal example like below in c++
```

img = cv2.imread('123457.jpg')
img  = model.get_input(img)

f2 = model.get_feature(img)
dist = np.sum(np.square(f1-f2))
sim = np.dot(f1, f2.T)
```

**Comment by szad670401** [comment]
The cpp example has been released in  wiki.

**Comment by YaoQ** [comment]
I have followed the [Wiki](https://github.com/deepinsight/insightface/wiki/Tutorial:-Deploy-Face-Recognition-Model-via-TVM) to compile the m1 model and deploy it with CPP.
I managed to run the compiled model with Python test code , but after I compile the CPP code and do Inferencing via TVM runtime,  but failed.

Environment:
- Ubuntu16.04, x86 (CPU only)
- TVM 0.4.0
- LLVM 6.0
- OpenCV3.4.2
```
[14:48:29] /usr/tvm/src/runtime/threading_backend.cc:63: The thread affinity cannot be set when the number of workersis larger than the number of available cores in the system.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [14:48:29] /usr/tvm/include/tvm/runtime/./packed_func.h:732: Check failed: i < num_args (1 vs. 1) not enough argument passed, 1 passed but request arg[1].

Stack trace returned 7 entries:
[bt] (0) ./pyface_tvm(dmlc::StackTrace[abi:cxx11]()+0x1bc) [0x404a6c]
[bt] (1) ../../3rdparty/tvm/lib/libtvm_runtime.so(tvm::runtime::TVMArgs::operator[](int) const+0x6eb) [0x7fa9064ccefb]
[bt] (2) ../../3rdparty/tvm/lib/libtvm_runtime.so(+0x85ec7) [0x7fa906531ec7]
[bt] (3) ./pyface_tvm() [0x405cf5]
[bt] (4) ./pyface_tvm() [0x40358d]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fa905861830]
[bt] (6) ./pyface_tvm() [0x4038f9]

```

I will appreciate if you have any suggestion. @szad670401 
Thank you very much.

**Comment by YaoQ** [comment]
After I changed to from LLVM6.0 to LLVM 5.0, the error is resolved.

**Comment by portgasray** [comment]
> After I changed the LLVM6.0 to LLVM 5.0, the error is resolved.

how to change that?

**Comment by cyrusbehr** [comment]
I compare the inference speed of a few inference engines (running in single thread mode due to use case) with the insightface model: https://github.com/cyrusbehr/benchmarks/tree/master/inferenceSpeed
