### ISSUE TITLE
what the effect about parameter：beta、beta_freeze and beta_min、gamma

### ISSUE THREAD

**Issue by zjz19960805** [deepinsight/insightface#487]
hello, in your code, I have seen several line codes like this:
      if mbatch<=args.beta_freeze:
        _beta = args.beta
      else:
        move = max(0, mbatch-args.beta_freeze)
        _beta = max(args.beta_min, args.beta*math.pow(1+args.gamma*move, -1.0*args.power))
      os.environ['BETA'] = str(_beta)
And I discover that the same parameter beta has also appear on Lsoftmax, but I don't know what their usage, Could you please help me solve this problem? thank you very much.

**Comment by nttstar** [comment]
Used by sphereface loss, not recommended now.
