### ISSUE TITLE
Where can I find the steps to align VGGFACE2?

### ISSUE THREAD

**Issue by twmht** [deepinsight/insightface#488]
Hi,
align_insight.py (https://github.com/deepinsight/insightface/blob/master/src/align/align_insight.py) does mention VGGFACE2, but it has no alignment steps. 

Clearly, the code only detect faces but not use the landmarks.

So given the bounding boxes and landmarks, where can I find the alignment process of VGGFACE2?

**Comment by nttstar** [comment]
You can write by yourself.
