### ISSUE TITLE
iBUG_DeepInsight

### ISSUE THREAD

**Issue by d4nst** [deepinsight/insightface#49]
I have seen that the current top algorithm in the MegaFace challenge is iBug_DeepInsight, with an accuracy that corresponds with your latest update: *2018.02.13: We achieved state-of-the-art performance on MegaFace-Challenge-1, at 98.06*

After reading your paper and the README in this repo, it seems to me that this accuracy is achieved using the cleaned/refined MegaFace dataset. Is this correct?

**Comment by nttstar** [comment]
Right.

**Comment by d4nst** [comment]
In that case, I don't think it's fair to publish those results in the public results page of the MegaFace challenge. As far as I know, it's not allowed to modify the evaluation set when reporting results, as this would obviously make impossible to compare the accuracy of the different algorithms. I suggest that you report the results obtained using the original dataset instead.

**Comment by MartinDione** [comment]
It's worth to mention to be fair you should publish this cleaned data just to let other researchers to validate it.

**Comment by d4nst** [comment]
Don't get my wrong, I think it's great that you made everything clear and open source and as a fellow researcher I thank you for that!

As you say, it's very easy to cheat on these type of challenges. However, the assumption is that all the teams would work with the same test set and would not tamper the submitted results. Otherwise, as I said before, it would be impossible to compare the accuracy between algorithms. I agree with you that the best way to test is with a clean dataset and your paper clearly shows how this affect the accuracy of the algorithm. My problem with your submission is that nowhere in the MegaFace website says that you used a cleaned test set. Neither there is a link to this repo or to your paper, where this information is provided. 

I think that at least you should let the organisers know about this, and let them decide what to do. I think adding a note under the "Method details" section could work as well.

**Comment by MartinDione** [comment]
I think this affects the companies and the business of face technologies which cost us a huge budget, to be fair I believe you should delete this repository.

**Comment by d4nst** [comment]
@MartinDione I'm not sure what are you talking about but that has nothing to do with this discussion

**Comment by MartinDione** [comment]
I'm talking about the megaface objectives to develop the facial recognition. When you publish such this code you affect other companies, like Vocord they invested a lot of money on the development to achieve state-of-the-art performance on MegaFace.

**Comment by d4nst** [comment]
I won't even bother replying to that... Again, that has nothing to do with the issue we are discussing here.

**Comment by nttstar** [comment]
We will put the noise list on this repo soon. But read the notes carefully at that time.

**Comment by nttstar** [comment]
@MartinDione It is unbelievable if vocord spend a lot of money on a public competition like MegaFace.

**Comment by ivazhu** [comment]
@MartinDione Vocord didn't spend it :)
@nttstar And what have you done with errors in FaceScrub subset which is used in Megaface Challenge?

**Comment by nttstar** [comment]
It was described in our paper.

**Comment by ivazhu** [comment]
@nttstar I have read your article and now I absolutely disagree that you are playing fair game. First of all you have changed test dataset, not deleted smth wrong, but changed FaceScrub "wrong" images with another images! More over you are writing that additional artificial features was added to your feature vectors that highlight "bad" images in distractor dataset. It is the same as using manual annotation! Megaface rules deny the first and the second. Also I would like to mention that your method of "cleaning" dataset creates "clear for your algorithm" dataset. I am sure that community will find mistakes in your "error" list when you publish it.

P.S. And have you thought that Megaface team have clear correspondence list? If they will recompute the results with it your team will take the last place cause images of different people will give you very high FAR (it is about your image replacing)

**Comment by nttstar** [comment]
@ivazhu I'm confused about the words 'deleted' and 'changed' in your comment. Anyway what you said was almost the same with d4nst's and I don't want to clear my position again. Megaface team had checked our list and solution, otherwise the result would not be on the leaderboard.

**Comment by ivazhu** [comment]
@nttstar From your article: "During testing, we change the noisy face to another right face" and "During testing, we add one additional feature dimension to distinguish these noisy faces"
From Megaface Challenge: "1. Download MegaFace and FaceScrub datasets and development kit 2.Run your algorithm to produce features for both datasets"

In your article you declare that you are not using provided dataset and augmenting features with manual labels. It's obvious for all that you broke the Megaface rules.

**Comment by aktiger** [comment]
Does the noise list opensourced?  @nttstar

**Comment by nttstar** [comment]
@ivazhu How can you achieve 91% without removing these noises? It's beyond my imagination.

**Comment by chichan01** [comment]
@nttstar 
  I have read your paper and also your noise list and codes under https://github.com/deepinsight/insightface/tree/master/src/megaface as well.  I got a bit confuse.
In Your text, "We manually clean the FaceScrub dataset and finally
find 605 noisy face images. During testing, we change the
noisy face to another right face, which can increase the identification
accuracy by about 1%. In Figure 6(b), we give the
noisy face image examples from the MegaFace distractors.
All of the four face images from the MegaFace distractors
are Alec Baldwin. We manually clean the MegaFace distractors
and finally find 707 noisy face images. During testing,
we add one additional feature dimension to distinguish
these noisy faces, which can increase the identification accuracy
by about 15%."
In your noise list, megaface_noises.txt have 719 noisy face images and Facescrub have 605 noisy face images.
In remove_noises.py, 
for facescrub set, the noisy image(feature) is replaced by the subject class center with random uniform noise.
center = fname2center[a]
    g = np.zeros( (feature_dim+feature_ext,), dtype=np.float32)
    g2 = np.random.uniform(-0.001, 0.001, (feature_dim,))
    g[0:feature_dim] = g2
    f = center+g
    _norm=np.linalg.norm(f)
    f /= _norm
    feature_path_out = os.path.join(args.facescrub_feature_dir_out, a, "%s_%s.bin"%(b, out_algo))
    write_bin(feature_path_out, f)
however, for Megaface set, I don't know what you do in there.  My first reading seems that you try to fill the feature with 100, but after I read your load_bin function, it is not the case as you update those filled 100 feature with the original extracted feature from the noise image.
your code:
      feature = load_bin(feature_path, 100.0)
      write_bin(feature_path_out, feature)
and load_bin function:
def load_bin(path, fill = 0.0):
  with open(path, 'rb') as f:
    bb = f.read(4*4)
    #print(len(bb))
    v = struct.unpack('4i', bb)
    #print(v[0])
    bb = f.read(v[0]*4)
    v = struct.unpack("%df"%(v[0]), bb)
    feature = np.full( (feature_dim+feature_ext,), fill, dtype=np.float32)
    feature[0:feature_dim] = v
    #feature = np.array( v, dtype=np.float32)
  #print(feature.shape)
  #print(np.linalg.norm(feature))
  return feature

1. Is there something I misunderstand? please give an advice.

2. did you use your codes and list to reproduce your result for megaface or it is typo error? if you have update your code or lists, would you like to tell us what is your updated result on megaface. Please verify it on your pretrained model.

**Comment by ivazhu** [comment]
@nttstar First of all - WE DIDN'T CHANGE THE DATASET as you did. There are some secrets :) For instance, think what to do if you see more than one face on "error" distractor image.

And also, as I promised, take a look on Alley_Mills_52029, Lindsay_Hartley_33188, Michael_Landes_43643, ... These are not ERRORS. These are errors of your algorithm. In your "work" you simply deleted all samples which your alg was not working correctly on. 

Any more questions?

**Comment by chichan01** [comment]
@ivazhu ,
  What do mean  "more than one face on "error" distractor image"? In verification, it is a pair matching, how can it be more than a face? Also what do you mean "one face on "error" distractor image"?

**Comment by ivazhu** [comment]
It can be more than one face on a image

ср, 28 февр. 2018 г. в 11:41, Chi Ho CHAN <notifications@github.com>:

**Comment by chichan01** [comment]
Do you mean that there can be more than a face in the image, no matter it is in facescrub subset or distractor set?
So you do not use their provided json as a landmark reference in your case.

**Comment by ivazhu** [comment]
We didn't anything with Facescrub dataset cause there is not FAIR method to
correct this type of errors.
What about distractors - yes, there are some samples with more than one
face - one face from Facescrub and one another.

About megaface json - read megaface docs - you should use megaface json in
the case you can't detect a face only

ср, 28 февр. 2018 г. в 11:50, Chi Ho CHAN <notifications@github.com>:

**Comment by chichan01** [comment]
I see.  I think this can be a  discussion.
This trick may also not be good as you only do on mageface dataset, which means that any images more than one face can be denoted as disaster.  In other words, you have already known that one of your pair is disaster. so you can do whatever to make it as a disaster score.  I think this also violate the verification protocol as well.

**Comment by nttstar** [comment]
@ivazhu Choosing one face from multiple faces in one image according to your own knowledge is also a data trick. It is the same as data noises cleaning.

**Comment by nttstar** [comment]
@chichan01 Adding random noises to centre vectors can avoid identical feature vectors. The result will not change if no noise applied.

**Comment by chichan01** [comment]
@nttstar 
so would you like to tell me what you want to do on the disaster set..?

**Comment by nttstar** [comment]
@chichan01 What do you mean by 'want to do'?

**Comment by chichan01** [comment]
I do not understand how you solve the noise in the disaster (megaface set).
Please read what I post.
However, for Megaface set, I don't know what you do in there. My first reading seems that you try to fill the feature with 100 for those noise images, but after I read your load_bin function, it is not the case as you update those filled 100 feature with the original extracted feature from the noise image.
your code about noise in megaface:
feature = load_bin(feature_path, 100.0)
write_bin(feature_path_out, feature)
and load_bin function:
def load_bin(path, fill = 0.0):
with open(path, 'rb') as f:
bb = f.read(4*4)
#print(len(bb))
v = struct.unpack('4i', bb)
#print(v[0])
bb = f.read(v[0]*4)
v = struct.unpack("%df"%(v[0]), bb)
feature = np.full( (feature_dim+feature_ext,), fill, dtype=np.float32)
feature[0:feature_dim] = v
#feature = np.array( v, dtype=np.float32)
#print(feature.shape)
#print(np.linalg.norm(feature))
return feature

**Comment by nttstar** [comment]
Maybe you're missing something...
The solution is to add one more dimension with a large value(here 100.0) on those noisy distractor images.
So the L2 distance of 'noisy distractors' to all facescrub images will be large enough.
```
v = struct.unpack('4i', bb)
feature = np.full( (feature_dim+feature_ext,), fill, dtype=np.float32)
feature[0:feature_dim] = v
```
`v` is the original feature. `Shape(feature)=(513,)` and `feature_dim=512`.

**Comment by chichan01** [comment]
Thx.. so your feature dimension is 513 and the last dimension is 0 or 100 depending on whether it is noisy image or not.

**Comment by nttstar** [comment]
Right.

**Comment by chichan01** [comment]
@nttstar  since your code and the number of images in the list are not same in your paper, did you update your result on your pretrained model?

**Comment by nttstar** [comment]
We have duplicated items in original megaface noises file(megaface_image_path -> Facescrub_identity_name). For example, one megaface image with two facescrub names. But we're sure they belongs to at least one Facescrub identity.

**Comment by chichan01** [comment]
@nttstar what do you mean?
your paper->707 noisy face images in megaface
your list-> 719 noisy face images
your paper-> We manually clean the FaceScrub dataset and finally
find 605 noisy face images. During testing, we change the
noisy face to another right face
your code->Adding random noises to centre vectors
so you can see the difference.. I believe your result will be difference..

**Comment by nttstar** [comment]
do `sort -u` on the megaface noise list.

**Comment by chichan01** [comment]
Thx, although I do not agree to clean the testing dataset, I should appreciate that you released the code for public, so that others can reproduce their result using your code and lists.

**Comment by ivazhu** [comment]
We did not choose according to your own "knowledge". We choose less similar
from the image. So the process is automatic, no manual annotation.

Jia, and what about errors in your "error" list. Are you going to accept
that your results are not fair?

ср, 28 февр. 2018 г. в 12:48, Jia Guo <notifications@github.com>:

**Comment by nttstar** [comment]
@ivazhu what do you mean by 'less similar from the image'?

**Comment by chichan01** [comment]
@ivazhu 
Well, as I mentioned that you only works on disaster set and you use the face detection to detect those face.  I can imagine that you can use the lowest confidence sore of face detection to represent a face in the image and then you can extract feature from that face and compute the so-called' less similar from the image'.  In fact, it can be a non-face image. let say you have a very poor face detection alg... you can easy to achieve a good mismatch score by using this trick. please remember that you do not do it on facescurb.

**Comment by ivazhu** [comment]
No, you are not right. The detector for facescrub set and for distractors
set is the same. I speak about recognition score. Imagine that you have two
faces of different people on image and you know that one of it must be
distractor for facescrub dataset - it is not very difficult to make a
choice in this situation :)

ср, 28 февр. 2018 г. в 14:44, Chi Ho CHAN <notifications@github.com>:

**Comment by nttstar** [comment]
@ivazhu I can get 100% on Megaface challenge by using your approach - to detect dozens of faces from each megaface distractor image and choose the one with lowest similarity to facescrub dataset, even sometimes it's not a real face.  You can't use the knowledge of facescrub dataset when you're doing something with megaface.
I'm very surprised that you and vocord do think this is a normal procedure.

**Comment by ivazhu** [comment]
I wonder how then images from facescrub would be compared!

P.S. It is very funny to hear about 100% from the man who added a dimension
with labels to his features

ср, 28 февр. 2018 г. в 16:25, Jia Guo <notifications@github.com>:

**Comment by d4nst** [comment]
I think this whole discussion proves my point. Both of your teams (Deepinsight and Vocord) have not strictly followed the MegaFace protocol, so it is pointless to compare the performance of your algorithms with the rest of participants.

**Comment by ivazhu** [comment]
Daniel, please show where I didn't follow the protocol?

ср, 28 февр. 2018 г. в 19:37, Daniel Saez <notifications@github.com>:

**Comment by d4nst** [comment]
@nttstar and @chichan01 have already explained this, but I'll try to make it more clear...

As I understand, this is what you do: in the FaceScrub set, you always crop the correct face (using the provided landmarks or bounding box as a reference). In the MegaFace distractor set, you are cropping all the detected faces, comparing them against the probe face and selecting the lowest score as the "valid" score. 

The problem with your approach is that you are using your knowledge about the origin of the image (probe set or distractor set) to make a decision. You know that a probe and a distractor image shouldn't match, so you just take the lowest score. As others have pointed out, you could use a poor face detector that doesn't even detect faces and this approach would give you a very high accuracy. 

If you really wanted to take the lowest score, you should do it all the time, not just for distractor images, i.e. when you add the matching face from the probe set to the distractor set, you should also compare against all the detected faces and take the lowest score. If you do that, your performance will probably be much worse.

Lastly, just think about a real identification system in which you don't know anything about the origin of the faces. I'm sure that you would agree with me that always selecting the lowest score from all the detected faces would be a very poor design.

Please let me know if my assumptions about your approach are wrong.

**Comment by ivazhu** [comment]
Not quite. First of all I compute detector settings so that there is no
fail detections in FaceScrub dataset. It let me hope that there is no such
detections in Megaface dataset. To tell the truth I checked it manually -
there is no fail detections in Megaface with computed settings. So I just
choose the real distractor from two real face.

There is another more important problem - there are images without faces in
Megaface dataset. Nevertheless we had to compute "features" by
json-coordinate. These "features" are something completely different from
face feature. I'd like to mention that the better learned algorithm than
worse results would be on such samples.

P.S. Daniel, we don't talk about real identification system here. There are
very different problem there :)

2018-02-28 22:06 GMT+03:00 Daniel Saez <notifications@github.com>:

**Comment by chichan01** [comment]
@nttstar   I have just found that you also released your result on FGNet megaface challenge as well.  I have questions regarding on your result.
1. Do you only use the same training set (i.e. your provided MS-1M-celeb) to train the deep network?
2. If yes, it means that I can use your pretrained model to test on FGNet. would you mind to tell me which pretrained model you  released for testing on FGNet.?
3. did you also clean the testing dataset as well? if yes, would you mind to release the list?
4. will you update your paper by including the results of FGNet?

**Comment by chichan01** [comment]
@ivazhu 
Would you mind to address what different problems between the megaface challenge and the real identification and verification here??

My point and others @d4nst and @nttstar  agree that you only treat the disaster set specially and this is not the case in the real scenario as we don't have any side information of the image pair.
I agree that @nttstar result cannot be comparable with other works because other participants did not do that, but they give the list and also some code, so that we can regard that they propose a new protocol.  Therefore, the former and the later participants can do a bit extra work to follow this new protocol to produce the result.

On the other hand, your work will be much more difficult to follow and reproduce as you do not release your paper document.  Also, the most important is that your proposed trick violates the fundamental principle of face verification and identification.

**Comment by happynear** [comment]
It is a common knowledge in face recognition community that the absolute performance of MegaFace is **meaningless**. Lots of cheating methods can be applied to achieve very high scores and MegaFace don't have the mechanism to prevent them.

What we can trust is the relative scores, which means, one can only compare with himself on MegaFace. As in this issue, models evaluated on the cleaned list should only be compared with the ones evaluated on the same list. The authors have these experiments in their paper. That's already enough, not to mention that they released their codes and will release the cleaned list.

The only problem is that the official MegaFace organizer should make two leaderboards after they got aware of the existence of the "cleaned list". However, they don't have the willings to do so and they choose to put them on the same leaderboard. This is the problem. The authors of InsightFace did nothing wrong.

**Comment by HaoLiuHust** [comment]
appreciate Vocoord let us know what they have done to the dataset

**Comment by d4nst** [comment]
@ivazhu the point of my comment was not about the failed detections. It was about treating probe and distractor images in a different way when in a real setting you wouldn't have this information.

**Comment by nttstar** [comment]
@chichan01 
1. Yes. The refined MS1M 
2. Yes. By using resnet100 model. You can get similar performance. 
3. Some mis-aligned faces are rectified and some potential wrong labels are checked. However, on FGNET, the lablel noise has smaller affect on the performance compared to that on FaceScrub. Due to the age span, noisy label selection is hard, and J Deng is confirming some of these noise labels. You can send email to enquiry with him. 
4. Maybe. We may update the results on FGNET into the paper.

**Comment by nttstar** [comment]
@d4nst 
As you can see from this thread, I believe lots of submitted results were using cleaned list implicitly or explicitly, especially those >85% acc. Some teams even do not realize it.

**Comment by d4nst** [comment]
@nttstar Yes, I have realised that. However, that doesn't make things any better. The MegaFace leaderboard seems pretty meaningless to me now. We need a reliable benchmark similar to ImageNet in the face recognition community

**Comment by ivazhu** [comment]
Daniel, see the megaface forum - I have suggested it yet. Moreover we
offered the megaface team to clean up their dataset two years ago. Also guy
from google wrote that he informed them about the errors at the beginning
of the challenge.

I suggest to discuss new challenge at some big conference. There are a lot
of problems to create fair for all competitions.

чт, 1 марта 2018 г. в 9:58, Daniel Saez <notifications@github.com>:

**Comment by nttstar** [comment]
Another big issue I want to say here is: Test set(megaface distractor set) cleaning is a MUST-DO work to test your algorithms/models, otherwise the results will not be solid even you just compare the relative scores. Take an example from our paper. `SphereFace(m=4, lambda=5)` achieves 82.95%, 97.43% on 'before-cleaning' and 'after-cleaning' protocols respectively, while `ArcFace(m=0.4)` gets 82.29% and 98.10%(`ArcFace(m=0.5)` gets 98.36% for reference). Watching the scores before refinement we may judge that SphereFace is better than `ArcFace under m=0.4` setting but actually not.

**Comment by ivazhu** [comment]
Jia, it may be due to your cleaning process and its errors. Except errors
in your error list there are some "bad" (not corresponding) images that you
didn't catch. For example:

Peggy_McCay_48889
Adrienne_Barbeau_4246
Alley_Mills_52003

So I can say that you didn't prove the statement above


2018-03-01 16:31 GMT+03:00 Jia Guo <notifications@github.com>:

**Comment by ivazhu** [comment]
*Peggy_McCay_48889*
*Adrienne_Barbeau_4246*
*Alley_Mills_52003*

These are FaceScrub errors. Did you fix them? If yes, why your error list
doesn't contain them?

2018-03-01 16:41 GMT+03:00 Jia Guo <notifications@github.com>:

**Comment by nttstar** [comment]
You can open a standalone issue to describe it. Noisy list must be refined over and over, not just from our team.
And this three items will not lead to much differences(<0.1% I believe, as 600 facescrub noises just increase the acc by about 1%). I don't think it will break my argument above.

**Comment by ivazhu** [comment]
1. These three names are only examples of your errors
2. There are only 3530 images from FaceScrub in Megaface protocol. And I
think (I know the real number) )the intersection with 600 "facescrub
noises" is about 20-30 images. So even three noises (and I repeat that
there are more such cases) are very important.
3. Jia, you deleted several not noise images in your experiments. After
that your "big issue" can be explained by these mistakenly deleted images.

2018-03-01 16:54 GMT+03:00 Jia Guo <notifications@github.com>:

**Comment by nttstar** [comment]
@ivazhu I'm wasting my time to reply to you.  From +0.66% to -0.67%, so you mean that your three items can affect the acc by larger than 1% in one direction? Stop please.

**Comment by ivazhu** [comment]
Jia, I think you are in the subject but it seems you are not. Think how
many positives pairs (pairs of images of the same person) you have. After
that look how many images of *Peggy_McCay *there are in the Facescrub
subset from Megaface. Even if there are only one not detected by you error
then there are N positives pairs which are not positive. But you managed to
miss more than one error *Peggy_McCay *image!

2018-03-01 17:11 GMT+03:00 Jia Guo <notifications@github.com>:

**Comment by nttstar** [comment]
I will give you the results soon.

**Comment by chibai** [comment]
用英文聊这么久，辛苦了~

**Comment by terencezl** [comment]
I can attest to the statement by @nttstar that denoising the facescrub probe set only changes the final score 1%. Out of the 3530 probes, 24 show up on the noise list from @nttstar, and 24 is a small portion of 3530. More importantly, if you check those pictures, they are mostly still celebrities, and should not find matches with any distractors. In other words, you end up with less score increase than what 24/3530 might indicate.

The reason why 707 mislabeld distractors play such a huge influence on the final score, is that you are not comparing 707 with 1M distractors, you are comparing them with 3530 probes. If any of the mislabeled distractors gets into a higher similarity than the probe's similarity, your rank 1 score is ruined. In that case, rank 5, 10 might be a better metric, because that allows for some noises. But megaface's devkit only prints out rank 1 score. Oh well.

**Comment by terencezl** [comment]
> As you can see from this thread, I believe lots of submitted results were using cleaned list implicitly or explicitly, especially those >85% acc. Some teams even do not realize it.

It's a very good point. Having a public noise list and letting everyone examine, and follow suit is the right way to go. If someone is organizing a new contest, I think the organizer should have the following rules:

Ideally each pic contains 1 face. Remove wrongly labeled ones. For pics containing more than 1 face, make sure the provided face bbox corresponds to the correct face, and urge participants to use that bbox to generate landmarks, align and generate reps.

Urge participants to use the exact same procedure for images from probe and distractor sets.

**Comment by Liuftvafas** [comment]
What do you guys think of NIST's FRVT Ongoing https://www.nist.gov/programs-projects/face-recognition-vendor-test-frvt-ongoing for a benchmark? Many commercial vendors use it for quite a fair comparison of their face recognition algorithms. FRVT requires to use face detection and does not provide landmarks but I guess MTCNN does a decent job in solving this issue.

**Comment by ivazhu** [comment]
Hi, Justas

The problem is that FRVT requires your algorithm without any kind of
protection. You give your alg to american government and they use it
whereever they want.
And another one for you - the recognition error for best algs on FRVT is
several times less than  MTCNN detection error.

Ivan

2018-04-11 10:39 GMT+03:00 Justas Kranauskas <notifications@github.com>:

**Comment by delveintodetail** [comment]
With the non-cleaned megaface and facescrub, all results above > ~85-86% are cheating in some ways(willful or unmeant).

With the cleaned megaface, evaluations are unfair to other methods that are conducted on previous non-cleaned protocol, such as sphereface, tencentface, and papers before Mar. 

Angular Margins are very tricky, you can always mess up methods from others and pretend your method performs better. If possible, do not introduce more parameters, because parameters are always fit to the training datasets, if small datasets, no strong constraints used, if larger datasets, maybe stronger constraints, who knows??

You use three parameters and show you are rich having tens of GPUs. Report all your results trained on CASIA, MS-Celebrities, VGGFace2, because most previous methods are trained on CASIA.

That is no fair in face recognition area. Probably, blind test and protocol may be ok. 

Megaface protocol sucks.......... Let us try something else...........
