### ISSUE TITLE
error with backtrace

### ISSUE THREAD

**Issue by maylad31** [deepinsight/insightface#492]
*** Error in `python': free(): invalid pointer: 0x00007f1ed814cb50 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f1f5d6da7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f1f5d6e337a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f1f5d6e753c]
/usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXExecutorReshape+0x1852)[0x7f1f13593ce2]
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c)[0x7f1f44076e40]
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb)[0x7f1f440768ab]
/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f)[0x7f1f442863df]
/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82)[0x7f1f4428ad82]
python(PyEval_EvalFrameEx+0x578d)[0x4c166d]
python(PyEval_EvalCodeEx+0x306)[0x4b9b66]

i have cuda 9 installed and i use mxnet-cu90 using pip

please help me

**Comment by galip** [comment]
Hello,

I have the same problem. If you found the solution, please let me know.

**Comment by DecentMakeover** [comment]
Same problem

**Comment by goodloop** [comment]
same here

**Comment by mahxn0** [comment]
save here
