### ISSUE TITLE
What face detection algorithm is used in demo?

### ISSUE THREAD

**Issue by WIll-Xu35** [deepinsight/insightface#499]
Hi all,

The new demo is very impressive. I'm interested in the face detection algorithm used in the demo. Is it mtcnn with some extra process (since original mtcnn's result is a bit jumpy), or is it some other algorithm?

And is the time it take to generate this demo longer than the length of the original video (can this detection and recognition algorithm work in real time)?

**Comment by jiankangdeng** [comment]
Thanks for your interest.
The detector is a one-shot style detector. 

When the input is 720* 1280, the system can run at ~15FPS with the large model (real-time with the small model).

**Comment by mlourencoeb** [comment]
Are these FPS CPU or GPU-based computations?

Is this new upcoming detector? Impressive results!

**Comment by WIll-Xu35** [comment]
@jiankangdeng Thank you for your reply. Looking forward to your paper about this detector and maybe an open source implementation of it.

BTW, is it some upgraded version of the detector from your 'Face_Detection_Alignment' repo?

**Comment by fmbahrt** [comment]
Is the source code for the video example available?

**Comment by lucl1** [comment]
When the source code for the video demo available? 
Thanks.

**Comment by ThanhPham1987** [comment]
When the source code for the video demo available?
Thanks.
