### ISSUE TITLE
Why the train-cele dataset size is different in Dataset Zoo and #256

### ISSUE THREAD

**Issue by bing1zhi2** [deepinsight/insightface#505]
In the dataset zoo ,the train-cele dataset size is 30G ，but the first release in #256 is 90G ，is there any difference?

**Comment by nttstar** [comment]
What 90G stands for?

**Comment by bing1zhi2** [comment]
@nttstar  http://trillionpairs.deepglint.com/data   train_celebrity.tar.gz  91G

**Comment by bing1zhi2** [comment]
@nttstar sorry,I  made a mistake,In the dataset zoo ,the train-cele dataset  is 12.96G  ,not 30G

**Comment by bing1zhi2** [comment]
after download all the two dataset ,It turns out that in the dataset zoo,the data contains 7 files:
faces_glintasia/cfp_ff.bin  
faces_glintasia/train.rec  
faces_glintasia/train.lst  
faces_glintasia/agedb_30.bin  
faces_glintasia/property  
faces_glintasia/train.idx  
faces_glintasia/lfw.bin  
faces_glintasia/cfp_fp.bin
Is this dataset has  the same structure  as the Asian-Celeb who has 93979 ids ?

**Comment by bing1zhi2** [comment]
thanks
