### ISSUE TITLE
acc=0并且lossvalue始终很小

### ISSUE THREAD

**Issue by zjz19960805** [deepinsight/insightface#512]
你好，首先感谢您开源的代码。
我的问题比较大：
在使用softmax训练时，在vgg数据集上我的acc可以做到从0增大，ce-loss从40开始减小，我认为这非常好
当使用我自己的数据集时，ce-loss初始值在8-11左右（我认为这个loss值很小，不是很正常）当跑完大概12000个batch后，acc依然为0，ce-loss始终保持在5-8左右震荡。
我的数据集大小为57733类*210张图片，其中大多数图片为增强的图片。
我想请问我的ce-loss是否正常，或者针对我的数据集应该做参数的调整？
非常感谢您！
![image](https://user-images.githubusercontent.com/44387104/51320883-32bd5500-1a9c-11e9-957e-d691ad7614ba.png)
上面是我的loss图

**Comment by nttstar** [comment]
确认一下打包的数据集是否有问题, softmax理应acc涨的比较快
