### ISSUE TITLE
Made a minimalistic usage example

### ISSUE THREAD

**Issue by kiselev1189** [deepinsight/insightface#514]
Hi guys, nice project. 
I made a minimalistic insightface repack that works for inference out of the box.
Original code is quite bloated and hard to navigate if all you want is to do inference with pre-trained models. I ommited anything that is not related to inference and provide some additional error handling and a Jupyter Notebook usage example.
https://github.com/kiselev1189/insightface-just-works

Mind to include it into third-party reimplemetations list?

**Comment by alekhka** [comment]
Hey, this is amazing, thank you!
