### ISSUE TITLE
num_class

### ISSUE THREAD

**Issue by nizhaofeng1** [deepinsight/insightface#515]
why num_class=85142?my train dataset set 85742

**Comment by nttstar** [comment]
where is 85142?

**Comment by nizhaofeng1** [comment]
LResnet34E,train.log
gpu num: 4
num_layers 34
image_size [112, 112]
num_classes 85164

**Comment by nttstar** [comment]
too old, ignore it.

**Comment by nizhaofeng1** [comment]
affect lfw accuracy?
