### ISSUE TITLE
questions about the model name?

### ISSUE THREAD

**Issue by LCorleone** [deepinsight/insightface#516]

**Comment by LCorleone** [comment]
I am confused about the model name.
for example, LResnet100E-IR, what's  the L, E, and  IR stands for?
LmobileNet-GAP, what's the GAP stands for?
thanks!

**Comment by nttstar** [comment]
You can check our v1 paper on arxiv.

**Comment by LCorleone** [comment]
@nttstar thanks, i will back for v1.

**Comment by LCorleone** [comment]
@nttstar  hi, in paper v1, did you train SE-Lresnet100E-IR and the performance?
thanks
