### ISSUE TITLE
训练时遇到的奇怪问题

### ISSUE THREAD

**Issue by bigbao9494** [deepinsight/insightface#517]
我在src目录下训练时如果作下面这些设置，就会出现训练非常慢，速度大概
Speed: 50 samples/sec这样，如果不作这些设置会快很多大概
Speed: 1122.83 samples/sec（硬件：4X1080TI，48核CPU），感觉训练的
AAC上升比较慢
export MXNET_CPU_WORKER_NTHREADS=24
export MXNET_CUDNN_AUTOTUNE_DEFAULT=0
export MXNET_ENGINE_TYPE=ThreadedEnginePerDevice

下面是刚刚开始10分钟左右的打印：
./train_mobilefacenet_step1.sh 
/usr/local/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[10:42:49] src/engine/engine.cc:55: MXNet start using engine: ThreadedEnginePerDevice
gpu num: 4
num_layers 1
image_size [112, 112]
num_classes 85742
Called with argument: Namespace(batch_size=512, beta=1000.0, beta_freeze=0, beta_min=5.0, bn_mom=0.9, ce_loss=False, ckpt=2, color=0, ctx_num=4, cutoff=0, data_dir='/ssd1/faces_emore', easy_margin=0, emb_size=128, end_epoch=100000, fc7_lr_mult=1.0, fc7_no_bias=False, fc7_wd_mult=10.0, gamma=0.12, image_channel=3, image_h=112, image_size='112,112', image_w=112, images_filter=0, loss_type=0, lr=0.1, lr_steps='240000,360000,440000', margin=4, margin_a=1.0, margin_b=0.0, margin_m=0.1, margin_s=32.0, max_steps=140002, mom=0.9, network='y1', num_classes=85742, num_layers=1, per_batch_size=128, power=1.0, prefix='../model-y1-test/model', pretrained='', rand_mirror=1, rescale_threshold=0, scale=0.9993, target='lfw,cfp_fp,agedb_30', use_deformable=0, verbose=2000, version_act='prelu', version_input=1, version_multiplier=1.0, version_output='GDC', version_se=0, version_unit=3, wd=4e-05)
init mobilefacenet 1
INFO:root:loading recordio /ssd1/faces_emore/train.rec...
header0 label [5822654. 5908396.]
id2range 85742
5822653
rand_mirror 1
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000, 3, 112, 112)
ver lfw
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
loading bin 13000
(14000, 3, 112, 112)
ver cfp_fp
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000, 3, 112, 112)
ver agedb_30
lr_steps [240000, 360000, 440000]
call reset()
/usr/local/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py:505: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (0.25 vs. 0.001953125). Is this intended?
  optimizer_params=optimizer_params)
[10:43:30] src/kvstore/././comm.h:745: only 4 out of 12 GPU pairs are enabled direct access. It may affect the performance. You can set MXNET_ENABLE_GPU_P2P=0 to turn it off
[10:43:30] src/kvstore/././comm.h:754: .v..
[10:43:30] src/kvstore/././comm.h:754: v...
[10:43:30] src/kvstore/././comm.h:754: ...v
[10:43:30] src/kvstore/././comm.h:754: ..v.
[10:43:30] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:Epoch[0] Batch [0-20]	Speed: 1132.30 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [20-40]	Speed: 1056.72 samples/sec	acc=0.000098
INFO:root:Epoch[0] Batch [40-60]	Speed: 1123.02 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [60-80]	Speed: 1130.13 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [80-100]	Speed: 1123.67 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [100-120]	Speed: 1127.47 samples/sec	acc=0.000195
INFO:root:Epoch[0] Batch [120-140]	Speed: 1133.34 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [140-160]	Speed: 1106.65 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [160-180]	Speed: 1116.96 samples/sec	acc=0.000098
INFO:root:Epoch[0] Batch [180-200]	Speed: 1122.83 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [200-220]	Speed: 1119.48 samples/sec	acc=0.000098
INFO:root:Epoch[0] Batch [220-240]	Speed: 1124.47 samples/sec	acc=0.000098
INFO:root:Epoch[0] Batch [240-260]	Speed: 1126.63 samples/sec	acc=0.000195
INFO:root:Epoch[0] Batch [260-280]	Speed: 1112.80 samples/sec	acc=0.000293
INFO:root:Epoch[0] Batch [280-300]	Speed: 1116.77 samples/sec	acc=0.000391
INFO:root:Epoch[0] Batch [300-320]	Speed: 1112.81 samples/sec	acc=0.000195
INFO:root:Epoch[0] Batch [320-340]	Speed: 1111.72 samples/sec	acc=0.000195
INFO:root:Epoch[0] Batch [340-360]	Speed: 1109.62 samples/sec	acc=0.000293
INFO:root:Epoch[0] Batch [360-380]	Speed: 1099.48 samples/sec	acc=0.000195
INFO:root:Epoch[0] Batch [380-400]	Speed: 1110.43 samples/sec	acc=0.000098
INFO:root:Epoch[0] Batch [400-420]	Speed: 1104.34 samples/sec	acc=0.000098
INFO:root:Epoch[0] Batch [420-440]	Speed: 1111.38 samples/sec	acc=0.000098
INFO:root:Epoch[0] Batch [440-460]	Speed: 1067.16 samples/sec	acc=0.000488
INFO:root:Epoch[0] Batch [460-480]	Speed: 1102.03 samples/sec	acc=0.000195
INFO:root:Epoch[0] Batch [480-500]	Speed: 1096.34 samples/sec	acc=0.000586
INFO:root:Epoch[0] Batch [500-520]	Speed: 1124.60 samples/sec	acc=0.000293
INFO:root:Epoch[0] Batch [520-540]	Speed: 1108.92 samples/sec	acc=0.000195
INFO:root:Epoch[0] Batch [540-560]	Speed: 1114.52 samples/sec	acc=0.000391
INFO:root:Epoch[0] Batch [560-580]	Speed: 1100.79 samples/sec	acc=0.000391
INFO:root:Epoch[0] Batch [580-600]	Speed: 1102.83 samples/sec	acc=0.000391
INFO:root:Epoch[0] Batch [600-620]	Speed: 1111.57 samples/sec	acc=0.000293
INFO:root:Epoch[0] Batch [620-640]	Speed: 1113.79 samples/sec	acc=0.000684
INFO:root:Epoch[0] Batch [640-660]	Speed: 1112.91 samples/sec	acc=0.000293
INFO:root:Epoch[0] Batch [660-680]	Speed: 1105.92 samples/sec	acc=0.000488
INFO:root:Epoch[0] Batch [680-700]	Speed: 1105.13 samples/sec	acc=0.000488
INFO:root:Epoch[0] Batch [700-720]	Speed: 1095.20 samples/sec	acc=0.000391
INFO:root:Epoch[0] Batch [720-740]	Speed: 1102.56 samples/sec	acc=0.000977
INFO:root:Epoch[0] Batch [740-760]	Speed: 1113.49 samples/sec	acc=0.000684
INFO:root:Epoch[0] Batch [760-780]	Speed: 1094.19 samples/sec	acc=0.000195
INFO:root:Epoch[0] Batch [780-800]	Speed: 1078.27 samples/sec	acc=0.000586
INFO:root:Epoch[0] Batch [800-820]	Speed: 1085.61 samples/sec	acc=0.001270
INFO:root:Epoch[0] Batch [820-840]	Speed: 1104.80 samples/sec	acc=0.000684
INFO:root:Epoch[0] Batch [840-860]	Speed: 1083.88 samples/sec	acc=0.000684
INFO:root:Epoch[0] Batch [860-880]	Speed: 1102.90 samples/sec	acc=0.000586
INFO:root:Epoch[0] Batch [880-900]	Speed: 1098.46 samples/sec	acc=0.000879
INFO:root:Epoch[0] Batch [900-920]	Speed: 1117.42 samples/sec	acc=0.001074
INFO:root:Epoch[0] Batch [920-940]	Speed: 1105.74 samples/sec	acc=0.000781
INFO:root:Epoch[0] Batch [940-960]	Speed: 1106.28 samples/sec	acc=0.000879
INFO:root:Epoch[0] Batch [960-980]	Speed: 1099.08 samples/sec	acc=0.000684
lr-batch-epoch: 0.1 999 0
INFO:root:Epoch[0] Batch [980-1000]	Speed: 1104.30 samples/sec	acc=0.000879
INFO:root:Epoch[0] Batch [1000-1020]	Speed: 1111.57 samples/sec	acc=0.000977
INFO:root:Epoch[0] Batch [1020-1040]	Speed: 1115.43 samples/sec	acc=0.001465
INFO:root:Epoch[0] Batch [1040-1060]	Speed: 1105.48 samples/sec	acc=0.000488
INFO:root:Epoch[0] Batch [1060-1080]	Speed: 1099.90 samples/sec	acc=0.001367
INFO:root:Epoch[0] Batch [1080-1100]	Speed: 1111.54 samples/sec	acc=0.000586
INFO:root:Epoch[0] Batch [1100-1120]	Speed: 1095.31 samples/sec	acc=0.000879
INFO:root:Epoch[0] Batch [1120-1140]	Speed: 1114.35 samples/sec	acc=0.001074
INFO:root:Epoch[0] Batch [1140-1160]	Speed: 1099.33 samples/sec	acc=0.001660
INFO:root:Epoch[0] Batch [1160-1180]	Speed: 1093.73 samples/sec	acc=0.001465
INFO:root:Epoch[0] Batch [1180-1200]	Speed: 1111.13 samples/sec	acc=0.000488
INFO:root:Epoch[0] Batch [1200-1220]	Speed: 1088.15 samples/sec	acc=0.000684
INFO:root:Epoch[0] Batch [1220-1240]	Speed: 1104.83 samples/sec	acc=0.001563
INFO:root:Epoch[0] Batch [1240-1260]	Speed: 1061.60 samples/sec	acc=0.000586
INFO:root:Epoch[0] Batch [1260-1280]	Speed: 1124.20 samples/sec	acc=0.001074
INFO:root:Epoch[0] Batch [1280-1300]	Speed: 1112.04 samples/sec	acc=0.000586
INFO:root:Epoch[0] Batch [1300-1320]	Speed: 1082.62 samples/sec	acc=0.001172
INFO:root:Epoch[0] Batch [1320-1340]	Speed: 1096.77 samples/sec	acc=0.000781
INFO:root:Epoch[0] Batch [1340-1360]	Speed: 1111.64 samples/sec	acc=0.000781
INFO:root:Epoch[0] Batch [1360-1380]	Speed: 1120.92 samples/sec	acc=0.001855
INFO:root:Epoch[0] Batch [1380-1400]	Speed: 1105.31 samples/sec	acc=0.001270
INFO:root:Epoch[0] Batch [1400-1420]	Speed: 1118.48 samples/sec	acc=0.001270
INFO:root:Epoch[0] Batch [1420-1440]	Speed: 1114.02 samples/sec	acc=0.000977
INFO:root:Epoch[0] Batch [1440-1460]	Speed: 1114.85 samples/sec	acc=0.001953
INFO:root:Epoch[0] Batch [1460-1480]	Speed: 1104.04 samples/sec	acc=0.001563
INFO:root:Epoch[0] Batch [1480-1500]	Speed: 1113.21 samples/sec	acc=0.001367
INFO:root:Epoch[0] Batch [1500-1520]	Speed: 1125.47 samples/sec	acc=0.000586
INFO:root:Epoch[0] Batch [1520-1540]	Speed: 1119.58 samples/sec	acc=0.000684
INFO:root:Epoch[0] Batch [1540-1560]	Speed: 1111.21 samples/sec	acc=0.001563
INFO:root:Epoch[0] Batch [1560-1580]	Speed: 1115.98 samples/sec	acc=0.001172
INFO:root:Epoch[0] Batch [1580-1600]	Speed: 1110.14 samples/sec	acc=0.001367
INFO:root:Epoch[0] Batch [1600-1620]	Speed: 1096.98 samples/sec	acc=0.000781
INFO:root:Epoch[0] Batch [1620-1640]	Speed: 1124.20 samples/sec	acc=0.001563
INFO:root:Epoch[0] Batch [1640-1660]	Speed: 1108.31 samples/sec	acc=0.001172
INFO:root:Epoch[0] Batch [1660-1680]	Speed: 1091.27 samples/sec	acc=0.001660
INFO:root:Epoch[0] Batch [1680-1700]	Speed: 1106.60 samples/sec	acc=0.001855
INFO:root:Epoch[0] Batch [1700-1720]	Speed: 1111.52 samples/sec	acc=0.001660
INFO:root:Epoch[0] Batch [1720-1740]	Speed: 1097.61 samples/sec	acc=0.001855
INFO:root:Epoch[0] Batch [1740-1760]	Speed: 1089.44 samples/sec	acc=0.000977
INFO:root:Epoch[0] Batch [1760-1780]	Speed: 1096.06 samples/sec	acc=0.001855
INFO:root:Epoch[0] Batch [1780-1800]	Speed: 1103.87 samples/sec	acc=0.001758
INFO:root:Epoch[0] Batch [1800-1820]	Speed: 1115.11 samples/sec	acc=0.001953
INFO:root:Epoch[0] Batch [1820-1840]	Speed: 1085.17 samples/sec	acc=0.001270
INFO:root:Epoch[0] Batch [1840-1860]	Speed: 1114.05 samples/sec	acc=0.001953
INFO:root:Epoch[0] Batch [1860-1880]	Speed: 1104.16 samples/sec	acc=0.001074
INFO:root:Epoch[0] Batch [1880-1900]	Speed: 1103.52 samples/sec	acc=0.001660
INFO:root:Epoch[0] Batch [1900-1920]	Speed: 1100.42 samples/sec	acc=0.001563
INFO:root:Epoch[0] Batch [1920-1940]	Speed: 1110.85 samples/sec	acc=0.002441

**Comment by bigbao9494** [comment]
不知道为什么编辑不了上面的内容，补充一下，数据是放在SSD上的，MXNET版本是1.3

**Comment by bigbao9494** [comment]
@nttstar 
感谢你的回复
还有一个问题想请教一下：
    最新的训练方法是使用recognition/train.py
    (4). Fine-turn the above Softmax model with Triplet loss.
           CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train.py --network m1 --loss triplet --lr 0.005 --pretrained ./models/m1-softmax-emore,1

    使用的是Triplet loss，而你以前的方法是使用src/train_softmax.py，做fine-turn时使用的
     loss_type是4，为何不一样呢？

     感谢！

**Comment by clhne** [comment]
> Now do not set MXNET_CPU_WORKER_NTHREADS or set it to 1.

请问什么时候需要设置为1，或者不设置？

**Comment by wting861006** [comment]
@bigbao9494 你好，我的机器也是4*1080ti，我的速度只有200左右，想问一下你的训练速度如何达到1000多的？
Speed: 204.23 samples/sec

**Comment by EtheneXiang** [comment]
> 我在src目录下训练时如果作下面这些设置，就会出现训练非常慢，速度大概
> Speed: 50 samples/sec这样，如果不作这些设置会快很多大概
> Speed: 1122.83 samples/sec（硬件：4X1080TI，48核CPU），感觉训练的
> AAC上升比较慢
> export MXNET_CPU_WORKER_NTHREADS=24
> export MXNET_CUDNN_AUTOTUNE_DEFAULT=0
> export MXNET_ENGINE_TYPE=ThreadedEnginePerDevice
> 
> 下面是刚刚开始10分钟左右的打印：
> ./train_mobilefacenet_step1.sh
> /usr/local/anaconda3/lib/python3.6/site-packages/h5py/**init**.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
> from ._conv import register_converters as _register_converters
> [10:42:49] src/engine/engine.cc:55: MXNet start using engine: ThreadedEnginePerDevice
> gpu num: 4
> num_layers 1
> image_size [112, 112]
> num_classes 85742
> Called with argument: Namespace(batch_size=512, beta=1000.0, beta_freeze=0, beta_min=5.0, bn_mom=0.9, ce_loss=False, ckpt=2, color=0, ctx_num=4, cutoff=0, data_dir='/ssd1/faces_emore', easy_margin=0, emb_size=128, end_epoch=100000, fc7_lr_mult=1.0, fc7_no_bias=False, fc7_wd_mult=10.0, gamma=0.12, image_channel=3, image_h=112, image_size='112,112', image_w=112, images_filter=0, loss_type=0, lr=0.1, lr_steps='240000,360000,440000', margin=4, margin_a=1.0, margin_b=0.0, margin_m=0.1, margin_s=32.0, max_steps=140002, mom=0.9, network='y1', num_classes=85742, num_layers=1, per_batch_size=128, power=1.0, prefix='../model-y1-test/model', pretrained='', rand_mirror=1, rescale_threshold=0, scale=0.9993, target='lfw,cfp_fp,agedb_30', use_deformable=0, verbose=2000, version_act='prelu', version_input=1, version_multiplier=1.0, version_output='GDC', version_se=0, version_unit=3, wd=4e-05)
> init mobilefacenet 1
> INFO:root:loading recordio /ssd1/faces_emore/train.rec...
> header0 label [5822654. 5908396.]
> id2range 85742
> 5822653
> rand_mirror 1
> loading bin 0
> loading bin 1000
> loading bin 2000
> loading bin 3000
> loading bin 4000
> loading bin 5000
> loading bin 6000
> loading bin 7000
> loading bin 8000
> loading bin 9000
> loading bin 10000
> loading bin 11000
> (12000, 3, 112, 112)
> ver lfw
> loading bin 0
> loading bin 1000
> loading bin 2000
> loading bin 3000
> loading bin 4000
> loading bin 5000
> loading bin 6000
> loading bin 7000
> loading bin 8000
> loading bin 9000
> loading bin 10000
> loading bin 11000
> loading bin 12000
> loading bin 13000
> (14000, 3, 112, 112)
> ver cfp_fp
> loading bin 0
> loading bin 1000
> loading bin 2000
> loading bin 3000
> loading bin 4000
> loading bin 5000
> loading bin 6000
> loading bin 7000
> loading bin 8000
> loading bin 9000
> loading bin 10000
> loading bin 11000
> (12000, 3, 112, 112)
> ver agedb_30
> lr_steps [240000, 360000, 440000]
> call reset()
> /usr/local/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py:505: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (0.25 vs. 0.001953125). Is this intended?
> optimizer_params=optimizer_params)
> [10:43:30] src/kvstore/././comm.h:745: only 4 out of 12 GPU pairs are enabled direct access. It may affect the performance. You can set MXNET_ENABLE_GPU_P2P=0 to turn it off
> [10:43:30] src/kvstore/././comm.h:754: .v..
> [10:43:30] src/kvstore/././comm.h:754: v...
> [10:43:30] src/kvstore/././comm.h:754: ...v
> [10:43:30] src/kvstore/././comm.h:754: ..v.
> [10:43:30] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
> INFO:root:Epoch[0] Batch [0-20]	Speed: 1132.30 samples/sec	acc=0.000000
> INFO:root:Epoch[0] Batch [20-40]	Speed: 1056.72 samples/sec	acc=0.000098
> INFO:root:Epoch[0] Batch [40-60]	Speed: 1123.02 samples/sec	acc=0.000000
> INFO:root:Epoch[0] Batch [60-80]	Speed: 1130.13 samples/sec	acc=0.000000
> INFO:root:Epoch[0] Batch [80-100]	Speed: 1123.67 samples/sec	acc=0.000000
> INFO:root:Epoch[0] Batch [100-120]	Speed: 1127.47 samples/sec	acc=0.000195
> INFO:root:Epoch[0] Batch [120-140]	Speed: 1133.34 samples/sec	acc=0.000000
> INFO:root:Epoch[0] Batch [140-160]	Speed: 1106.65 samples/sec	acc=0.000000
> INFO:root:Epoch[0] Batch [160-180]	Speed: 1116.96 samples/sec	acc=0.000098
> INFO:root:Epoch[0] Batch [180-200]	Speed: 1122.83 samples/sec	acc=0.000000
> INFO:root:Epoch[0] Batch [200-220]	Speed: 1119.48 samples/sec	acc=0.000098
> INFO:root:Epoch[0] Batch [220-240]	Speed: 1124.47 samples/sec	acc=0.000098
> INFO:root:Epoch[0] Batch [240-260]	Speed: 1126.63 samples/sec	acc=0.000195
> INFO:root:Epoch[0] Batch [260-280]	Speed: 1112.80 samples/sec	acc=0.000293
> INFO:root:Epoch[0] Batch [280-300]	Speed: 1116.77 samples/sec	acc=0.000391
> INFO:root:Epoch[0] Batch [300-320]	Speed: 1112.81 samples/sec	acc=0.000195
> INFO:root:Epoch[0] Batch [320-340]	Speed: 1111.72 samples/sec	acc=0.000195
> INFO:root:Epoch[0] Batch [340-360]	Speed: 1109.62 samples/sec	acc=0.000293
> INFO:root:Epoch[0] Batch [360-380]	Speed: 1099.48 samples/sec	acc=0.000195
> INFO:root:Epoch[0] Batch [380-400]	Speed: 1110.43 samples/sec	acc=0.000098
> INFO:root:Epoch[0] Batch [400-420]	Speed: 1104.34 samples/sec	acc=0.000098
> INFO:root:Epoch[0] Batch [420-440]	Speed: 1111.38 samples/sec	acc=0.000098
> INFO:root:Epoch[0] Batch [440-460]	Speed: 1067.16 samples/sec	acc=0.000488
> INFO:root:Epoch[0] Batch [460-480]	Speed: 1102.03 samples/sec	acc=0.000195
> INFO:root:Epoch[0] Batch [480-500]	Speed: 1096.34 samples/sec	acc=0.000586
> INFO:root:Epoch[0] Batch [500-520]	Speed: 1124.60 samples/sec	acc=0.000293
> INFO:root:Epoch[0] Batch [520-540]	Speed: 1108.92 samples/sec	acc=0.000195
> INFO:root:Epoch[0] Batch [540-560]	Speed: 1114.52 samples/sec	acc=0.000391
> INFO:root:Epoch[0] Batch [560-580]	Speed: 1100.79 samples/sec	acc=0.000391
> INFO:root:Epoch[0] Batch [580-600]	Speed: 1102.83 samples/sec	acc=0.000391
> INFO:root:Epoch[0] Batch [600-620]	Speed: 1111.57 samples/sec	acc=0.000293
> INFO:root:Epoch[0] Batch [620-640]	Speed: 1113.79 samples/sec	acc=0.000684
> INFO:root:Epoch[0] Batch [640-660]	Speed: 1112.91 samples/sec	acc=0.000293
> INFO:root:Epoch[0] Batch [660-680]	Speed: 1105.92 samples/sec	acc=0.000488
> INFO:root:Epoch[0] Batch [680-700]	Speed: 1105.13 samples/sec	acc=0.000488
> INFO:root:Epoch[0] Batch [700-720]	Speed: 1095.20 samples/sec	acc=0.000391
> INFO:root:Epoch[0] Batch [720-740]	Speed: 1102.56 samples/sec	acc=0.000977
> INFO:root:Epoch[0] Batch [740-760]	Speed: 1113.49 samples/sec	acc=0.000684
> INFO:root:Epoch[0] Batch [760-780]	Speed: 1094.19 samples/sec	acc=0.000195
> INFO:root:Epoch[0] Batch [780-800]	Speed: 1078.27 samples/sec	acc=0.000586
> INFO:root:Epoch[0] Batch [800-820]	Speed: 1085.61 samples/sec	acc=0.001270
> INFO:root:Epoch[0] Batch [820-840]	Speed: 1104.80 samples/sec	acc=0.000684
> INFO:root:Epoch[0] Batch [840-860]	Speed: 1083.88 samples/sec	acc=0.000684
> INFO:root:Epoch[0] Batch [860-880]	Speed: 1102.90 samples/sec	acc=0.000586
> INFO:root:Epoch[0] Batch [880-900]	Speed: 1098.46 samples/sec	acc=0.000879
> INFO:root:Epoch[0] Batch [900-920]	Speed: 1117.42 samples/sec	acc=0.001074
> INFO:root:Epoch[0] Batch [920-940]	Speed: 1105.74 samples/sec	acc=0.000781
> INFO:root:Epoch[0] Batch [940-960]	Speed: 1106.28 samples/sec	acc=0.000879
> INFO:root:Epoch[0] Batch [960-980]	Speed: 1099.08 samples/sec	acc=0.000684
> lr-batch-epoch: 0.1 999 0
> INFO:root:Epoch[0] Batch [980-1000]	Speed: 1104.30 samples/sec	acc=0.000879
> INFO:root:Epoch[0] Batch [1000-1020]	Speed: 1111.57 samples/sec	acc=0.000977
> INFO:root:Epoch[0] Batch [1020-1040]	Speed: 1115.43 samples/sec	acc=0.001465
> INFO:root:Epoch[0] Batch [1040-1060]	Speed: 1105.48 samples/sec	acc=0.000488
> INFO:root:Epoch[0] Batch [1060-1080]	Speed: 1099.90 samples/sec	acc=0.001367
> INFO:root:Epoch[0] Batch [1080-1100]	Speed: 1111.54 samples/sec	acc=0.000586
> INFO:root:Epoch[0] Batch [1100-1120]	Speed: 1095.31 samples/sec	acc=0.000879
> INFO:root:Epoch[0] Batch [1120-1140]	Speed: 1114.35 samples/sec	acc=0.001074
> INFO:root:Epoch[0] Batch [1140-1160]	Speed: 1099.33 samples/sec	acc=0.001660
> INFO:root:Epoch[0] Batch [1160-1180]	Speed: 1093.73 samples/sec	acc=0.001465
> INFO:root:Epoch[0] Batch [1180-1200]	Speed: 1111.13 samples/sec	acc=0.000488
> INFO:root:Epoch[0] Batch [1200-1220]	Speed: 1088.15 samples/sec	acc=0.000684
> INFO:root:Epoch[0] Batch [1220-1240]	Speed: 1104.83 samples/sec	acc=0.001563
> INFO:root:Epoch[0] Batch [1240-1260]	Speed: 1061.60 samples/sec	acc=0.000586
> INFO:root:Epoch[0] Batch [1260-1280]	Speed: 1124.20 samples/sec	acc=0.001074
> INFO:root:Epoch[0] Batch [1280-1300]	Speed: 1112.04 samples/sec	acc=0.000586
> INFO:root:Epoch[0] Batch [1300-1320]	Speed: 1082.62 samples/sec	acc=0.001172
> INFO:root:Epoch[0] Batch [1320-1340]	Speed: 1096.77 samples/sec	acc=0.000781
> INFO:root:Epoch[0] Batch [1340-1360]	Speed: 1111.64 samples/sec	acc=0.000781
> INFO:root:Epoch[0] Batch [1360-1380]	Speed: 1120.92 samples/sec	acc=0.001855
> INFO:root:Epoch[0] Batch [1380-1400]	Speed: 1105.31 samples/sec	acc=0.001270
> INFO:root:Epoch[0] Batch [1400-1420]	Speed: 1118.48 samples/sec	acc=0.001270
> INFO:root:Epoch[0] Batch [1420-1440]	Speed: 1114.02 samples/sec	acc=0.000977
> INFO:root:Epoch[0] Batch [1440-1460]	Speed: 1114.85 samples/sec	acc=0.001953
> INFO:root:Epoch[0] Batch [1460-1480]	Speed: 1104.04 samples/sec	acc=0.001563
> INFO:root:Epoch[0] Batch [1480-1500]	Speed: 1113.21 samples/sec	acc=0.001367
> INFO:root:Epoch[0] Batch [1500-1520]	Speed: 1125.47 samples/sec	acc=0.000586
> INFO:root:Epoch[0] Batch [1520-1540]	Speed: 1119.58 samples/sec	acc=0.000684
> INFO:root:Epoch[0] Batch [1540-1560]	Speed: 1111.21 samples/sec	acc=0.001563
> INFO:root:Epoch[0] Batch [1560-1580]	Speed: 1115.98 samples/sec	acc=0.001172
> INFO:root:Epoch[0] Batch [1580-1600]	Speed: 1110.14 samples/sec	acc=0.001367
> INFO:root:Epoch[0] Batch [1600-1620]	Speed: 1096.98 samples/sec	acc=0.000781
> INFO:root:Epoch[0] Batch [1620-1640]	Speed: 1124.20 samples/sec	acc=0.001563
> INFO:root:Epoch[0] Batch [1640-1660]	Speed: 1108.31 samples/sec	acc=0.001172
> INFO:root:Epoch[0] Batch [1660-1680]	Speed: 1091.27 samples/sec	acc=0.001660
> INFO:root:Epoch[0] Batch [1680-1700]	Speed: 1106.60 samples/sec	acc=0.001855
> INFO:root:Epoch[0] Batch [1700-1720]	Speed: 1111.52 samples/sec	acc=0.001660
> INFO:root:Epoch[0] Batch [1720-1740]	Speed: 1097.61 samples/sec	acc=0.001855
> INFO:root:Epoch[0] Batch [1740-1760]	Speed: 1089.44 samples/sec	acc=0.000977
> INFO:root:Epoch[0] Batch [1760-1780]	Speed: 1096.06 samples/sec	acc=0.001855
> INFO:root:Epoch[0] Batch [1780-1800]	Speed: 1103.87 samples/sec	acc=0.001758
> INFO:root:Epoch[0] Batch [1800-1820]	Speed: 1115.11 samples/sec	acc=0.001953
> INFO:root:Epoch[0] Batch [1820-1840]	Speed: 1085.17 samples/sec	acc=0.001270
> INFO:root:Epoch[0] Batch [1840-1860]	Speed: 1114.05 samples/sec	acc=0.001953
> INFO:root:Epoch[0] Batch [1860-1880]	Speed: 1104.16 samples/sec	acc=0.001074
> INFO:root:Epoch[0] Batch [1880-1900]	Speed: 1103.52 samples/sec	acc=0.001660
> INFO:root:Epoch[0] Batch [1900-1920]	Speed: 1100.42 samples/sec	acc=0.001563
> INFO:root:Epoch[0] Batch [1920-1940]	Speed: 1110.85 samples/sec	acc=0.002441

哇，我的是八卡1080ti，64核CPU,256G内存，为什么训练速度这么慢，都没上100.
![image](https://user-images.githubusercontent.com/49241737/59818823-0615ae00-9358-11e9-8fea-15d4d5ba713c.png)

**Comment by wting861006** [comment]
@EtheneXiang 去掉export MXNET_CPU_WORKER_NTHREADS=24试试

**Comment by EtheneXiang** [comment]
那请问一下，你是否在启动训练的时候遇到过这个问题：
UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (0.25 vs. 0.001953125). Is this intended?
请教一下，这个咋解决，我不知道有什么影响。非常感谢

**Comment by wting861006** [comment]
@EtheneXiang 我也有这个提示，我也不明白这句话的涵义，所以我忽略了它

**Comment by EtheneXiang** [comment]
@wting861006 
我用了你刚才告诉我的办法，速度还是一样，没变化，我用的HDD。
还有就是收敛很慢很慢
batchsize 48，训练了200来个batch，acc还是全0，这个正常吗。loss也一直在45左右。

**Comment by wting861006** [comment]
不正常，你用哪个目录下的train.py？我用的insightface\recognition\train.py训练的，另外你可以尝试train_parall.py，据说对多卡有优化，我还没来得及验证。另外作者说用编译安装mxnet对性能也有提升。

**Comment by EtheneXiang** [comment]
@wting861006 
我也是用的recognition这个目录下的train文件，我知道在src下面还有个train文件，那个好像是老版本了。现目前作者的GitHub上也是用的recognition下面的train文件.
哈哈，我好像是apt安装的，不是源代码安装。我去试试你说的parall文件，再次表示感谢

**Comment by EtheneXiang** [comment]
@wting861006  老哥，我尝试了下，你说的parall这个文件，直接报错了。我就仅仅把命令行里面的train.py换成了train_parall.py，没做其他任何改动：错误信息如下：，求指点迷津。

Traceback (most recent call last):
  File "train_parall.py", line 336, in <module>
    main()
  File "train_parall.py", line 333, in main
    train_net(args)
  File "train_parall.py", line 188, in train_net
    assert False
AssertionError

关于这个问题，我看作者自己给的例子也是这样说的https://github.com/deepinsight/insightface/tree/master/recognition
Note: Replace train.py with train_parall.py in following examples if you want to use parallel acceleration.

**Comment by chwangteng** [comment]
> 不正常，你用哪个目录下的train.py？我用的insightface\recognition\train.py训练的，另外你可以尝试train_parall.py，据说对多卡有优化，我还没来得及验证。另外作者说用编译安装mxnet对性能也有提升。

请问您使用recognition下的train.py训练的时候过程正常吗？我用TITAN XP训练了一天左右之后LFW验证集上有99多的准确率，但是在我下载的作者的MS1M-ArcFace (85K ids/5.8M images) [5,7] (Recommend)这个数据集上准确率一直只有个位数。

**Comment by chwangteng** [comment]
我用recognition下的train.py训练我自制的vggface数据集，几分钟训练的准确率就九十多了，而且经常波动很大，请问有朋友遇到吗？也请别人做过vggface数据集，训练还是这样。loss用的是arcface。有朋友知道如果直接用src下的train的话，arcface的loss是填几呢？

**Comment by chwangteng** [comment]
我在两台显卡相同的机器上训练（CPU也都还行，都是固态，内存也不满，显卡都是四张TITAN XP），速度差异很大。不知道为什么。

**Comment by tmprun** [comment]
我训练刚开始可以两张卡，后来只能一张卡，两张卡报错：

**Comment by liweilalala** [comment]
mxnet cannot find engine ThreadedEnginePerDevice    这是什么情况啊
