### ISSUE TITLE
The feature's norm is correlated with the quality of image

### ISSUE THREAD

**Issue by huyangc** [deepinsight/insightface#518]
As my experiments, the feature's norm is highly correlated with the image's quality, high quality image has little norm and low quality image has large norm. I can not figure it out why this happen, is it because of the low quality image have lots of noise?

**Comment by mifenfeifen** [comment]
@huyangc 
    I wonder which type of norm you had selected? I tried with L2 (`norm = np.sqrt((feature**2).sum())`), and found that hign quality image has higher norm.

By the way, it seems that the L2 norm can only presenet the pose of the face, not the clearness of the face (blur of shake has little impact of the norm)
