### ISSUE TITLE
how to create the bin dataset file

### ISSUE THREAD

**Issue by longchr123** [deepinsight/insightface#520]
this is load dataset code:
bins, issame_list = pickle.load(open(os.path.join(args.eval_db_path, db_name + '.bin'), 'rb'), encoding='bytes')

but how to create the bin file, like lfw.bin in https://github.com/deepinsight/insightface/wiki/Model-Zoo

**Comment by freeearth** [comment]
Hello!
This is an example https://mxnet.incubator.apache.org/versions/master/faq/recordio.html
(Step 2) by im2rec executable (not implemented in python im2rec)

**Comment by khawar512** [comment]
Hi @longchr123 

Did you make a bin file of FGNET?

Regards,
Khawar

**Comment by Rushikeshkoli15** [comment]
hello there.
I am trying to create . bin file using this command " python im2rec.py img.lst root_path_of_images output.bin resize=256" which i got from https://mxnet.apache.org/versions/1.8.0/api/faq/recordio .
But i am getting an error which is "im2rec.py: error: unrecognized arguments: output.bin resize=256".
can anyone help me in this??

**Comment by Siirsalvador** [comment]
@Rushikeshkoli15 did you solve this? currently dealing with the same issue
