### ISSUE TITLE
input image color channel order

### ISSUE THREAD

**Issue by li-js** [deepinsight/insightface#524]
Thanks for sharing the code, but I am confused about one issue. Is the input image to the trained face recognition model in RGB or BGR?

The input here https://github.com/deepinsight/insightface/blob/master/deploy/test.py#L21 is RGB,
but the input here https://github.com/deepinsight/insightface/blob/master/deploy/test.py#L28 is BGR. 
Which one is correct? I.e. which color channel order was used during training? 

Ps. actually #L28 is not able to execute as the color channel is not swapped from index 2 to index 0 yet. 

Thanks in advance!

**Comment by nttstar** [comment]
Always RGB. I will remove L28 later

**Comment by WIll-Xu35** [comment]
Hi, does anyone know the reason why use CHW order instead of HWC and RGB instead of BGR?

**Comment by williamCorrea85** [comment]
Hi, I just found that the images encoded on the bin files used for verification are in bgr format, as mentioned as well by https://github.com/deepinsight/insightface/issues/467. Has someone an explanation for this ? Thanks in advance

**Comment by kylemcdonald** [comment]
Hello, I'm also interested in the correct channel order.

The demo server uses RGB ordering: https://github.com/deepinsight/insightface/blob/master/src/api/app.py

But there are many instances in the code of converting from BGR to RGB: https://github.com/deepinsight/insightface/search?q=COLOR_BGR2RGB&unscoped_q=COLOR_BGR2RGB

Including in the face recognition code, this is one of the first things that happens:

https://github.com/deepinsight/insightface/blob/master/python-package/insightface/model_zoo/face_recognition.py#L49

This implies that the correct input should be BGR. Unless `COLOR_BGR2RGB` is incorrect and it should really say `COLOR_RGB2BGR` (even though they do the same thing).

**Comment by mlourencoeb** [comment]
@kylemcdonald models take as input RGB. In the last example, the demo version in here www.insightface.ai used open CV to decode the image previous to call get_embedding. Hope this helps.

**Comment by kylemcdonald** [comment]
Thanks, I understand now. This means that the models themselves are RGB. But the Python package code assume that you are using OpenCV, so you should call `FaceRecognition.get_embedding` or `FaceAnalysis.get` with a BGR image.

I just extracted embeddings for 500k faces encoded as RGB by calling `FaceAnalysis.get`, so I will run it again :)

**Comment by off99555** [comment]
> Thanks, I understand now. This means that the models themselves are RGB. But the Python package code assume that you are using OpenCV, so you should call `FaceRecognition.get_embedding` or `FaceAnalysis.get` with a BGR image.
> 
> I just extracted embeddings for 500k faces encoded as RGB by calling `FaceAnalysis.get`, so I will run it again :)

Are you sure that you should pass BGR image to the `FaceAnalysis.get` function?

Look at this code, it's calling the model on the image directly without any conversion so maybe you need to pass the image as RGB. This library really need documentation man.
https://github.com/deepinsight/insightface/blob/30295de48907e04077d6d22a9a8f580b525822ce/python-package/insightface/app/face_analysis.py#L75

**Comment by off99555** [comment]
![image](https://user-images.githubusercontent.com/15215732/220151677-7d52d96d-469c-4c82-a2a1-48136be77442.png)
From experimentation, it seems to me that `FaceAnalysis.get()` function probably accepts BGR format because I can see the sex and age prediction on this image correctly when I feed BGR format to the function. If I feed RGB format to the function, it predicts female for every face in this specific image.
Please confirm that the get() function does indeed accept BGR format as input. Thanks.
