### ISSUE TITLE
Is my result of glint-challenge  normal ?

### ISSUE THREAD

**Issue by lynneHuang10** [deepinsight/insightface#529]
Thanks for Sharing! @nttstar 
About the glint-challenge i am puzzled for the result.
i use the  LResNet100E-IR,ArcFace@ms1m-refine-v2 model and generate the feature file for glint test data, the result are as flows. 

1.Identification: 0.70841   TPR@FPR=1e-3
2.Verification:0.39500    TPR@FPR=1e-9

the result is lower than most of the submitted algorithms, therefore, there is any mistake or i need to train the algorithm  with deep glint training dataset?

Thanks very much!

**Comment by nttstar** [comment]
no, you should get 0.8+ for identification
