### ISSUE TITLE
Pre-Trained Models Trained on Which Data Set?

### ISSUE THREAD

**Issue by ahkarami** [deepinsight/insightface#534]
Dear @yingfeng & @nttstar,
Thank you for your nice work. I have one question about the released face recognition pre-trained models on the [Model Zoo](https://github.com/deepinsight/insightface/wiki/Model-Zoo) section. Your pre-trained models trained on which data set? (i.e., MegaFace or LFW or MS1M)

**Comment by nttstar** [comment]
You can see the model name of 'ArcFace@ms1m-refine-v2'.

**Comment by ahkarami** [comment]
Thank you for your reply.
