### ISSUE TITLE
Train on My Own Data Set

### ISSUE THREAD

**Issue by ahkarami** [deepinsight/insightface#537]
Dear @yingfeng, @nttstar, @yuzhichang,
I have a face data set with the following format:
```
FaceDataSet/
    ID1/
        face_imageID1_1.jpg
        face_imageID1_2.jpg
        face_imageID1_3.jpg
    ID2/
        face_imageID2_1.jpg
        face_imageID2_2.jpg
...
```
Would you please kindly guide me to how I can train your models (e.g., with ArcFace Loss) on my own data set?

**Comment by hustzeyu** [comment]
You need to pack all your jpgs into rec and mxnet has that function

**Comment by eliaY** [comment]
@hustzeyu i am still a beginner in this stuff can you please provide me with the steps.
 thanks

**Comment by borisgribkov** [comment]
Look at the first post here https://github.com/deepinsight/insightface/issues/256, TrillionParts data has the same format as yours. But I guess you have no landmarks for your data, so maybe some modifications of face2rec2.py will be needed.

**Comment by Ffmydy** [comment]
@ahkarami
Is your own face data set under the camera?Could you please share me?

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md

**Comment by hande6688** [comment]
The format tool uses labelme, and the format is json. How to convert your face data set into a more extensive format described by the author for training? I also want to consult this question？
