### ISSUE TITLE
finetune pretrained model?

### ISSUE THREAD

**Issue by yang0817manman** [deepinsight/insightface#539]
Hi ，thanks for sharing your work.I want to try to finetune my model by freezon the layers before the layer of  "fc7",what I should do and how to modify the codes.Can you help me?Thx a lot!

**Comment by aiyakuangkuang** [comment]
finetune_lr = {k: 0 for k in arg_params}
    for key in aux_params:
        finetune_lr[key]=0
    opt.set_lr_mult(finetune_lr)
    #print(aux_params['fc7_weight'])
    #print(arg_params.keys())

    model.fit(train_dataiter,
        begin_epoch        = begin_epoch,
        num_epoch          = 1,
        eval_data          = val_dataiter,
        eval_metric        = eval_metrics,
        kvstore            = args.kvstore,
        optimizer          = opt,
        #optimizer_params   = optimizer_params,
        initializer        = initializer,
        arg_params         = arg_params,
        aux_params         = aux_params,
        allow_missing      = True,
        batch_end_callback = _batch_callback,
        epoch_end_callback = epoch_cb )
    for key in finetune_lr:
        finetune_lr[key]=args.lr
    opt.set_lr_mult(finetune_lr)
    print('start train the structure')
    model.fit(train_dataiter,
              begin_epoch=1,
              num_epoch=100,
              eval_data=val_dataiter,
              eval_metric=eval_metrics,
              kvstore=args.kvstore,
              optimizer=opt,
              # optimizer_params   = optimizer_params,
              initializer=initializer,
              arg_params=arg_params,
              aux_params=aux_params,
              allow_missing=True,
              batch_end_callback=_batch_callback,
              epoch_end_callback=epoch_cb)
like this

**Comment by yang0817manman** [comment]
thanks a lot!------------------ 原始邮件 ------------------
发件人: "aiyakuangkuang"<notifications@github.com>
发送时间: 2019年4月30日(星期二) 上午8:49
收件人: "deepinsight/insightface"<insightface@noreply.github.com>;
抄送: "yang0817manman"<3276181394@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [deepinsight/insightface] finetune pretrained model? (#539)



finetune_lr = {k: 0 for k in arg_params}
 for key in aux_params:
 finetune_lr[key]=0
 opt.set_lr_mult(finetune_lr)
 #print(aux_params['fc7_weight'])
 #print(arg_params.keys())
 model.fit(train_dataiter,     begin_epoch        = begin_epoch,     num_epoch          = 1,     eval_data          = val_dataiter,     eval_metric        = eval_metrics,     kvstore            = args.kvstore,     optimizer          = opt,     #optimizer_params   = optimizer_params,     initializer        = initializer,     arg_params         = arg_params,     aux_params         = aux_params,     allow_missing      = True,     batch_end_callback = _batch_callback,     epoch_end_callback = epoch_cb ) for key in finetune_lr:     finetune_lr[key]=args.lr opt.set_lr_mult(finetune_lr) print('start train the structure') model.fit(train_dataiter,           begin_epoch=1,           num_epoch=100,           eval_data=val_dataiter,           eval_metric=eval_metrics,           kvstore=args.kvstore,           optimizer=opt,           # optimizer_params   = optimizer_params,           initializer=initializer,           arg_params=arg_params,           aux_params=aux_params,           allow_missing=True,           batch_end_callback=_batch_callback,           epoch_end_callback=epoch_cb)  
like this
 
&mdash;
