### ISSUE TITLE
English Speakers Cannot Access Data

### ISSUE THREAD

**Issue by matthew-mcateer** [deepinsight/insightface#54]
The training Datasets available from Google Drive have been very useful, but data like the modified VGGFace2 are not accessible.

The dataset files on Baidu are large enough that downloading them requires the Baidu Network Tool, which is not available in English. Could links to these Datasets (VGGFace2 from Part 1) on Google Drive be made available in the README?

**Comment by nttstar** [comment]
I will upload vggface2 to google drive, please wait for some days.

**Comment by nttstar** [comment]
https://drive.google.com/open?id=1KORwx_DWyIScAjD6vbo4CSRu048APoum
