### ISSUE TITLE
Failed to allocate CPU memory

### ISSUE THREAD

**Issue by freeearth** [deepinsight/insightface#540]
Hello!
From time to time we get Exception Failed to allocate CPU memory.
From the debugging, we find it occurs on 362 - 364 lines while face detecting 
in mtcnn_detector.py 
It seems like sometimes stage of memory released is omitted by python.
We use python x86 (try both 3.6, 2.7) on 64 bit windows 7.
Exception occurs only for relatively large images (>400 KB)

**Comment by Gabit07** [comment]
I had the same problem. Didn't you solve it?

**Comment by cyrojyro** [comment]
It seems that that exception occurs when train.bin file is too big.
maybe try writting smaller pairs.txt
