### ISSUE TITLE
Where is the code for the demo video?

### ISSUE THREAD

**Issue by MILOTIDE** [deepinsight/insightface#541]
Hello,is there anyone know where is the code for the video demo?Thanks.

**Comment by nttstar** [comment]
nowhere

**Comment by MILOTIDE** [comment]
Could you provide it?Thanks.

**Comment by jiankangdeng** [comment]
after we release our face detector next month

**Comment by alekhka** [comment]
Can you provide it now? Thanks!

**Comment by clhne** [comment]
Can you provide it now? Thanks!

**Comment by lucl1** [comment]
> after we release our face detector next month
Please let me know when you release face detector and demo code. 
Many thanks.

**Comment by syedmustafa54** [comment]
@jiankangdeng @nttstar did you guys have any update video demo code

**Comment by ThanhPham1987** [comment]
@jiankangdeng @nttstar 
Please let me know when you release face detector and demo code.
Many thanks.

**Comment by dragen1860** [comment]
+1

**Comment by xiaozhi2015** [comment]
+1 @jiankangdeng
