### ISSUE TITLE
multi-task learning

### ISSUE THREAD

**Issue by guangdongliang** [deepinsight/insightface#546]
Have anyone trained model using multi-task learning as the following figure , for example ms1m+vgg2+two softmax .
![image](https://user-images.githubusercontent.com/16490080/52939674-be7a1800-339f-11e9-9ed2-24be20fd580b.png)

**Comment by jiankangdeng** [comment]
Similar motivation:
http://openaccess.thecvf.com/content_ECCV_2018/papers/Yu_Liu_Transductive_Centroid_Projection_ECCV_2
018_paper.pdf

**Comment by guangdongliang** [comment]
> Similar motivation:
> http://openaccess.thecvf.com/content_ECCV_2018/papers/Yu_Liu_Transductive_Centroid_Projection_ECCV_2
> 018_paper.pdf

i have tried , but the model trained with two dataset is not as good as trained with only ms1m !
https://github.com/XiaohangZhan/cdp/issues/5#issuecomment-464634610
