### ISSUE TITLE
LResNet100E-IR InsightFace time

### ISSUE THREAD

**Issue by wu-ruijie** [deepinsight/insightface#552]
I use LResNet100E-IR （arcface loss） train my data, and ininference it spend more than 1000ms, Is it normal? thanks!
GPU: GeForce GTX 1080TI
here is my codes(deploy/test.py):

t1 = time.time()
f1 = model.get_feature(img)
t2 = time.time()
print('time:' + str((t2 - t1) * 1000))   =>time:1082.615852355957

**Comment by nttstar** [comment]
Not normal for 1080TI.

**Comment by wuruijie123** [comment]
the first time call ‘model.get_feature’， it take a long time (~1000ms),
than I call it once again, it become very fast(~20ms); thanks very much !

t1 = time.time()
f1 = model.get_feature(img1)
t2 = time.time()
print('time1:' + str((t2 - t1) * 1000)) =>time1: 1004.5194625854492

t1 = time.time()
f1 = model.get_feature(img2)
t2 = time.time()
print('time2:' + str((t2 - t1) * 1000)) =>time2: 23.93484115600586
