### ISSUE TITLE
face emore dataset, binary to image

### ISSUE THREAD

**Issue by WIll-Xu35** [deepinsight/insightface#560]
I've downloaded face_emore dataset and unpacked it, but it's all in binary.

Any idea how to transfer it back to image file? Thanks.

**Comment by yunkchen** [comment]
Hi, you may find the answer in https://github.com/deepinsight/insightface/blob/master/src/image_iter.py#L56, with added code:
`header, img = mx.recordio.unpack(img_info)
  encoded_jpg_io = io.BytesIO(img)
  image = PIL.Image.open(encoded_jpg_io)`

**Comment by WIll-Xu35** [comment]
Thanks, I'll give it a try.
