### ISSUE TITLE
Help regarding tvm !

### ISSUE THREAD

**Issue by uday60** [deepinsight/insightface#561]
I have ported the models to TVM but how do i call functions in the original code like get_input and get_feature in TVM to get the vector of the face ?

Thanks.

**Comment by szad670401** [comment]
please refer to our wiki.

**Comment by uday60** [comment]
@szad670401 
Thanks for replying.

In the section titled "Inferencing Test base on TVM Runtime."

The python code does not load the image and doesn't call the get_input and get_feature methods like the code given in C++ section. 
Please help.

Thanks.

**Comment by 1976277169** [comment]
> 
> 
> @szad670401
> Thanks for replying.
> 
> In the section titled "Inferencing Test base on TVM Runtime."
> 
> The python code does not load the image and doesn't call the get_input and get_feature methods like the code given in C++ section.
> Please help.
> 
> Thanks.

你可以参考我的博客：https://blog.csdn.net/sinat_31425585/article/details/89442713
