### ISSUE TITLE
use verification in a Multiprocessing manner

### ISSUE THREAD

**Issue by ahkarami** [deepinsight/insightface#563]
Dear @nttstar,
I want to use your pre-trained models (just for test [i.e., inference]) in a python multi-processing manner. However it has the following error: 
```
File "/usr/local/lib/python3.5/dist-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:33:22] src/storage/storage.cc:65: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: initialization error
```

Would you please kindly help me to address this problem?

**Comment by szad670401** [comment]
mxnet doesn't support multi-process。

**Comment by ahkarami** [comment]
@szad670401,
Thank you for your reply. Are you sure about it? There isn't any other solution for sing MXNet models via python multiprocessing?

**Comment by szad670401** [comment]
You can use tvm to deploy, please refer to our wiki ,the example and tutorial has been provided.
