### ISSUE TITLE
how to convert .rec and .bin files to images

### ISSUE THREAD

**Issue by tomriddle54** [deepinsight/insightface#564]
Hello @yingfeng 

I have Downloaded faces_emore and faces_glint data but everything is in .rec or .bin formate I want to convert it into images formate .jpg or.png formate anyone know how can i do this

**Comment by yunkchen** [comment]
Hi, FYI:
https://github.com/auroua/InsightFace_TF/blob/master/data/mx2tfrecords.py#L33

**Comment by leolordwz** [comment]
Extract images from rec or bin files: 
https://github.com/wujiyang/Face_Pytorch/blob/master/utils/load_images_from_bin.py

**Comment by tengerye** [comment]
@yunkchen @leolordwz Hi, is there a way to do this in pure python or pytorch?

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md

**Comment by sourabhyadav** [comment]
> @yunkchen @leolordwz Hi, is there a way to do this in pure python or pytorch?

Did you find any script for converting rec files to images?

**Comment by kormalev** [comment]
@sourabhyadav, see [above](https://github.com/deepinsight/insightface/issues/564#issuecomment-488530491)

And yes, you'll need to have MXNet installed since the data is stored in MXNet's native format.
