### ISSUE TITLE
Pre-Trained Models in PyTorch

### ISSUE THREAD

**Issue by ahkarami** [deepinsight/insightface#568]
Dear @nttstar, @yingfeng, @yuzhichang, @ppwwyyxx and @zhangxu19830126,
Thank you for your fantastic repository. I have attempted to convert your pre-trained models into PyTorch via [MMdnn](https://github.com/Microsoft/MMdnn); however, I couldn't do that (some error occurred during converting the model weights into the MMdnn IR representation). I think the issue related to the dimension of your models. Have you ever attempted to convert the pre-trained models into PyTorch? Would you please kindly help me to address this issue?

**Comment by szad670401** [comment]
You can convert the model to ONNX by Mxnet build-in ONNX-convert tools.
