### ISSUE TITLE
TVM output vs Mxnet output... Mismatch ? Is this normal ?

### ISSUE THREAD

**Issue by deimsdeutsch** [deepinsight/insightface#575]
Hi,

First of all thanks for taking time and helping us out.

I have converted the models to TVM and now checking the output of the encodings. 

Is it normal to have completely different encodings from the normal mxnet output ?
Is there an accuracy drop when we switch to TVM ?

**Comment by aneesh0** [comment]
same issue. after converting to TVM output features are different and it reduces accuracy. please suggest

**Comment by szad670401** [comment]
Usually.It won't make big difference in accurccy when using tvm.

**Comment by dataman-py** [comment]
> Hi,
> 
> First of all thanks for taking time and helping us out.
> 
> I have converted the models to TVM and now checking the output of the encodings.
> 
> Is it normal to have completely different encodings from the normal mxnet output ?
> Is there an accuracy drop when we switch to TVM ?

hi

i have same problem

can you solve it?

**Comment by dataman-py** [comment]
> Usually.It won't make big difference in accurccy when using tvm.

hi

how many n_trial do you set for tuning?

i wanna use tvm and set n_trial = 120 but accuracy is very bad

do you have any suggastion?

i want compile model-r100-ii to tvm


tnx

**Comment by erinyangst** [comment]
Hi,
I have encountered the same issue when running model-r100-ii on tvm. The accuracy is significantly lower than that by mxnet. I have tried to remove values of model params lower than 1e-4, as suggested in the other post. It does not help with the accuarcy. Apparently there is a mismatch between results produced by these two platform. Can anymore solve this issue?
