### ISSUE TITLE
issue of alignment dataset 

### ISSUE THREAD

**Issue by w11m** [deepinsight/insightface#577]
hi @nttstar thank you for the great work 
i want to train the 2D alignment 
but the baidu cloud is to slow for me
is that possible upload to dropbox or google drive? 

Thank for your assistance

**Comment by yunkchen** [comment]
Hi, This could help you:
https://github.com/liuzhuoling2011/baidupcs-web

**Comment by w11m** [comment]
> Hi, This could help you:
> https://github.com/liuzhuoling2011/baidupcs-web

@yunkchen i'll try to use it thx a lot
