### ISSUE TITLE
two questions,thanx

### ISSUE THREAD

**Issue by dongdongmaster** [deepinsight/insightface#58]
1.test.py,some of my jpgs can not detect feature,most is side face pics,but other algorithm works well,
2.what is the similarity value for face recognition as one person,0.6? 0.7?0.8?

**Comment by dongdongmaster** [comment]
for question1,face_embedding.py,"ret" is None,then returned

ret = self.detector.detect_face_limited(face_img, det_type = self.args.det)
    if ret is None:
      return None

**Comment by nttstar** [comment]
MTCNN failed, I think. You may need to change the parameters of MTCNN or use stronger facial landmarks detector to deal with it.

Cosine threshold may differ in different environments. To find a optimal value by cross validation.

**Comment by dongdongmaster** [comment]
thank u @nttstar

**Comment by dongdongmaster** [comment]
sorry,
"MTCNN failed, I think. You may need to change the parameters of MTCNN" ,where i can do this,change this value?
test.py
"parser.add_argument('--det', default=2, type=int, help='mtcnn option, 2 means using R+O, else using O')"

**Comment by nttstar** [comment]
thresholds, min-size, etc...   Read the source code.

**Comment by brealisty** [comment]
> for question1,face_embedding.py,"ret" is None,then returned
> 
> ret = self.detector.detect_face_limited(face_img, det_type = self.args.det)
> if ret is None:
> return None

I also meet the same problem，I do it in insight_pytorch get the face_bbox(ret not none), but this code is always return None. And I change the ret to 2 or some other interger, face_bbox performence not well
