### ISSUE TITLE
What is the threshold for mobilefacenet model ?

### ISSUE THREAD

**Issue by uday60** [deepinsight/insightface#580]
What is the threshold to use since it is calculating 128 points ?

**Comment by WIll-Xu35** [comment]
Threshold should be determined using a labelled dataset. Basically you test different threshold values and see which one is the best.

**Comment by uday60** [comment]
@WIll-Xu35 
True ...but i just want to know what is threshold used to calculate the accuracy on LFW dataset.
Plz reply.

**Comment by WIll-Xu35** [comment]
@uday60 
https://github.com/deepinsight/insightface/blob/b10bb0fb41bd5b0dd1e0db284fdb27470b28635f/src/eval/lfw.py#L151

**Comment by dear-john** [comment]
What is the threshold if i use mobilefacenet  in mobile devices with only two images?
