### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by hsqaihkl** [deepinsight/insightface#582]
Hi，
My gpu is 1050ti , I want to train this net but the dataset or testset is too large .Could you tell me how to modify the code or which dataset/testset I can run in it？

**Comment by LiuWeiLun** [comment]
maybe the per_batch_size set too large??

**Comment by hsqaihkl** [comment]
I hava set the batchsize=16 , it can read the image data fot training but for the first epoch0 (image=46000),I met this error

**Comment by hsqaihkl** [comment]
@LiuWeiLun

**Comment by hsqaihkl** [comment]
@LiuWeiLun could you add my wechat?   wechat number: 18025361214

**Comment by LiuWeiLun** [comment]
Maybe you can post your results. Let me see what the problem is. But I don't understand it very well.

**Comment by LiuWeiLun** [comment]
If you can get the result"Running performance tests to find the best convolution algorithm, this can take a while... ". I think it you can fix it by setting the parameters.

**Comment by hsqaihkl** [comment]
@LiuWeiLun maybe ,I hava run the deploy/test.py process,but want to train the model and test the result of author's !

**Comment by LiuWeiLun** [comment]
My results as follow, I hope it can help you.
ssh://student908@10.108.250.110:22/home/student908/anaconda2/envs/liu_py27/bin/python2.7 -u /home/student908/Harddisk/liuweilun/insight_mxnet/src/train_softmax5.py
gpu_list: 1,2,3
Called with argument: Namespace(batch_begin=0, batch_count=[0], batch_size=192, beta=1000.0, beta_freeze=0, beta_min=5.0, bn_mom=0.9, ce_loss=False, ckpt=1, color=0, ctx_num=3, cutoff=0, data_dir='/home/student908/liuweilun/InsightFace_TF-master/datasets/faces_ms1m_112x112', easy_margin=0, emb_size=512, end_epoch=200, fc7_lr_mult=1.0, fc7_no_bias=False, fc7_wd_mult=1.0, fraction=[0.0], fraction_max=0.0, fraction_step=5e-06, gamma=0.12, image_channel=3, image_h=112, image_size='112,112', image_w=112, images_filter=0, loss_type=5, lr=0.1, lr_steps=[133333, 213333, 266666, 306666, 320000, 328000], margin=4, margin_a=1.0, margin_b=0.0, margin_m=0.5, margin_s=64.0, max_steps=0, mom=0.9, network='r50', num_layers=50, per_batch_size=64, power=1.0, prefix='/home/student908/Harddisk/liuweilun/insight_mxnet/model/m=0.5/1/', pretrained='', rand_mirror=1, scale=0.9993, target='lfw,cfp_fp,agedb_30', use_deformable=0, verbose_show=100, verbose_varf=1000, version_act='prelu', version_input=1, version_multiplier=1.0, version_output='E', version_se=0, version_unit=3, wd=0.0005)
train_dataset num_classes:  85164
loading vali_dataset: lfw
(12000L, 3L, 112L, 112L)
loading vali_dataset: cfp_fp
(14000L, 3L, 112L, 112L)
loading vali_dataset: agedb_30
(12000L, 3L, 112L, 112L)
init resnet 50
0 1 E 3 prelu
INFO:root:loading recordio /home/student908/liuweilun/InsightFace_TF-master/datasets/faces_ms1m_112x112/train.rec...
header0 label [3804847. 3890011.]
id2range 85164
3804846
rand_mirror 1
call reset()
/home/student908/anaconda2/envs/liu_py27/lib/python2.7/site-packages/mxnet/module/base_module.py:504: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (0.333333333333 vs. 0.00520833333333). Is this intended?
  optimizer_params=optimizer_params)
[15:48:40] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:Epoch[0] Batch [100]	Speed: 628.94 samples/sec	acc=0.000000

**Comment by LiuWeiLun** [comment]
If the error appear when you load the dataset, It’s really not enough memory. This has nothing to do with the model.

**Comment by LiuWeiLun** [comment]
You have to change the Function to read data.

**Comment by hsqaihkl** [comment]
@LiuWeiLun  I set the batchsize=4， but I also met the error


lr-batch-epoch: 0.1 46999 0
INFO:root:Epoch[0] Batch [46980-47000]	Speed: 20.79 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47000-47020]	Speed: 20.81 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47020-47040]	Speed: 20.78 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47040-47060]	Speed: 20.84 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47060-47080]	Speed: 20.59 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47080-47100]	Speed: 20.53 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47100-47120]	Speed: 20.63 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47120-47140]	Speed: 20.85 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47140-47160]	Speed: 20.65 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47160-47180]	Speed: 20.85 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47180-47200]	Speed: 20.94 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47200-47220]	Speed: 20.92 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47220-47240]	Speed: 20.55 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47240-47260]	Speed: 20.85 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47260-47280]	Speed: 20.90 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47280-47300]	Speed: 20.87 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47300-47320]	Speed: 20.69 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47320-47340]	Speed: 20.77 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47340-47360]	Speed: 20.88 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47360-47380]	Speed: 20.86 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47380-47400]	Speed: 20.74 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47400-47420]	Speed: 8.68 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47420-47440]	Speed: 20.93 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47440-47460]	Speed: 20.67 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47460-47480]	Speed: 21.01 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47480-47500]	Speed: 20.99 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47500-47520]	Speed: 20.75 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47520-47540]	Speed: 20.79 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47540-47560]	Speed: 21.01 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47560-47580]	Speed: 21.01 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47580-47600]	Speed: 20.98 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47600-47620]	Speed: 20.99 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47620-47640]	Speed: 21.02 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47640-47660]	Speed: 20.96 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47660-47680]	Speed: 20.97 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47680-47700]	Speed: 20.92 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47700-47720]	Speed: 21.05 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47720-47740]	Speed: 20.97 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47740-47760]	Speed: 20.81 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47760-47780]	Speed: 21.02 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47780-47800]	Speed: 20.95 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47800-47820]	Speed: 20.96 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47820-47840]	Speed: 20.85 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47840-47860]	Speed: 21.04 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47860-47880]	Speed: 20.93 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47880-47900]	Speed: 21.01 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47900-47920]	Speed: 20.80 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47920-47940]	Speed: 20.88 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47940-47960]	Speed: 20.85 samples/sec	acc=0.000000
INFO:root:Epoch[0] Batch [47960-47980]	Speed: 20.99 samples/sec	acc=0.000000
lr-batch-epoch: 0.1 47999 0
testing verification..
Traceback (most recent call last):
  File "/home/water/PycharmProjects/insightface/src/train.py", line 1029, in <module>
    main()
  File "/home/water/PycharmProjects/insightface/src/train.py", line 1026, in main
    train_net(args)
  File "/home/water/PycharmProjects/insightface/src/train.py", line 1020, in train_net
    epoch_end_callback = epoch_cb)
  File "/home/water/.local/lib/python3.7/site-packages/mxnet/module/base_module.py", line 553, in fit
    callback(batch_end_params)
  File "/home/water/PycharmProjects/insightface/src/train.py", line 951, in _batch_callback
    acc_list = ver_test(mbatch)
  File "/home/water/PycharmProjects/insightface/src/train.py", line 901, in ver_test
    acc1, std1, acc2, std2, xnorm, embeddings_list = verification.test(ver_list[i], model, args.batch_size, 10, data_extra, label_shape)
  File "/home/water/PycharmProjects/insightface/src/eval/verification.py", line 269, in test
    embeddings = sklearn.preprocessing.normalize(embeddings)
  File "/home/water/.local/lib/python3.7/site-packages/sklearn/preprocessing/data.py", line 1554, in normalize
    estimator='the normalize function', dtype=FLOAT_DTYPES)
  File "/home/water/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 573, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/water/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by LiuWeiLun** [comment]
set a small learning rate

**Comment by damvantai** [comment]
> set a small learning rate
hi @LiuWeiLun, Why learning rate affect to out of memory? I don't understand
