### ISSUE TITLE
SDU alignment training: loss value is NAN

### ISSUE THREAD

**Issue by lightwind002** [deepinsight/insightface#583]
Issue statement:
Traing SDU: train.py --network sdu, the loss value is NAN after about 300 batch.

Test environment:
Ubuntu 16.04, Python 2.7, Mxnet-cu80
CPU: I7
GPU: 1080Ti

Reproduce steps:
1. Download 2d face training validation dataset according to README.md.
2. copy sample_config.py as config.py
3. Run: train.py --network sdu

Log:
(venv) xxx@xxx-desktop:~/Workspace/insightface/alignment$ python train.py --network sdu
Call with Namespace(batch_size=20, ckpt=1, ctx_num=1, dataset='i2d', exf=1, frequent=20, lr=0.00025, lr_step='16000,24000,30000', network='sdu', norm=0, optimizer='nadam', per_batch_size=20, prefix='model/A', pretrained='', verbose=200, wd=0.0) {'net_binarize': False, 'net_d
cn': 3, 'gaussian': 0, 'net_block': 'cab', 'dataset': 'i2d', 'record_img_size': 384, 'landmark_type': '2d', 'net_coherent': False, 'base_scale': 256, 'val_targets': ['ibug', 'cofw_testset', '300W'], 'network': 'sdu', 'net_stacks': 2, 'losstype': 'heatmap', 'input_img_size': 
128, 'net_sta': 1, 'multiplier': 1.0, 'num_classes': 68, 'output_label_size': 64, 'label_xfirst': False, 'per_batch_size': 20, 'net_n': 3, 'dataset_path': './data_2d'}
INFO:root:loading recordio ./data_2d/train.rec...
('train size', 15683)
('train size after reset', 15683)
binarize False
use_coherent False
use_STA 1
use_N 3
use_DCN 3
per_batch_size 20
128 64 2
initializing upsampling_weight sta0_upsampling_w3_h3_weight
initializing upsampling_weight sta1_upsampling_w2_h3_weight
initializing stack1_ll_conv_offset_weight
initializing heatmap_offset_bias
initializing upsampling_weight sta0_upsampling_w2_h2_weight
initializing heatmap0_offset_weight
initializing stack0_out3_offset_bias
initializing stack0_ll_conv_offset_weight
initializing heatmap0_offset_bias
initializing upsampling_weight sta1_upsampling_w2_h2_weight
initializing upsampling_weight sta0_upsampling_w2_h3_weight
initializing heatmap_offset_weight
initializing upsampling_weight sta1_upsampling_w3_h3_weight
initializing stack0_out3_offset_weight
initializing stack0_ll_conv_offset_bias
initializing stack1_ll_conv_offset_bias
lr-steps [16000, 24000, 30000]
/home/elvin/Workspace/insightface/venv/local/lib/python2.7/site-packages/mxnet/module/base_module.py:505: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.05). Is this intended?
  optimizer_params=optimizer_params)
[12:59:53] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[12:59:58] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:Epoch[0] Batch [0-20] Speed: 18.89 samples/sec        lossvalue=0.001960
INFO:root:Epoch[0] Batch [20-40]        Speed: 19.08 samples/sec        lossvalue=0.001518
INFO:root:Epoch[0] Batch [40-60]        Speed: 19.14 samples/sec        lossvalue=0.001268
INFO:root:Epoch[0] Batch [60-80]        Speed: 19.22 samples/sec        lossvalue=0.001184
INFO:root:Epoch[0] Batch [80-100]       Speed: 19.01 samples/sec        lossvalue=0.001074
INFO:root:Epoch[0] Batch [100-120]      Speed: 18.99 samples/sec        lossvalue=0.001023
INFO:root:Epoch[0] Batch [120-140]      Speed: 18.84 samples/sec        lossvalue=0.000993
INFO:root:Epoch[0] Batch [140-160]      Speed: 18.46 samples/sec        lossvalue=0.000965
INFO:root:Epoch[0] Batch [160-180]      Speed: 18.63 samples/sec        lossvalue=0.000941
INFO:root:loading recordio ./data_2d/ibug.rec...
('train size', 135)
[200][ibug]NME: 0.196805
INFO:root:loading recordio ./data_2d/cofw_testset.rec...
('train size', 507)
[200][cofw_testset]NME: 0.163290
INFO:root:loading recordio ./data_2d/300W.rec...
('train size', 600)
[200][300W]NME: 0.171441
saving 1
INFO:root:Saved checkpoint to "model/A-0001.params"
INFO:root:Epoch[0] Batch [180-200]      Speed: 7.98 samples/sec lossvalue=0.000900
INFO:root:Epoch[0] Batch [200-220]      Speed: 18.55 samples/sec        lossvalue=0.000865
INFO:root:Epoch[0] Batch [220-240]      Speed: 19.11 samples/sec        lossvalue=0.000879
INFO:root:Epoch[0] Batch [240-260]      Speed: 19.05 samples/sec        lossvalue=0.000852
INFO:root:Epoch[0] Batch [260-280]      Speed: 18.93 samples/sec        lossvalue=0.000839
INFO:root:Epoch[0] Batch [280-300]      Speed: 18.91 samples/sec        lossvalue=0.000843
INFO:root:Epoch[0] Batch [300-320]      Speed: 18.94 samples/sec        lossvalue=0.000861
**INFO:root:Epoch[0] Batch [320-340]      Speed: 19.85 samples/sec        lossvalue=nan
INFO:root:Epoch[0] Batch [340-360]      Speed: 19.35 samples/sec        lossvalue=nan
INFO:root:Epoch[0] Batch [360-380]      Speed: 19.67 samples/sec        lossvalue=nan**
INFO:root:loading recordio ./data_2d/ibug.rec...
('train size', 135)
[400][ibug]NME: 0.569571

**Comment by nttstar** [comment]
Hi, here's my starting training log with sdu and batchsize=40(10*4)
```
INFO:root:Epoch[0] Batch [20]   Speed: 44.82 samples/sec        lossvalue=0.001892
INFO:root:Epoch[0] Batch [40]   Speed: 43.47 samples/sec        lossvalue=0.001390
INFO:root:Epoch[0] Batch [60]   Speed: 43.63 samples/sec        lossvalue=0.001170
INFO:root:Epoch[0] Batch [80]   Speed: 43.68 samples/sec        lossvalue=0.001054
INFO:root:Epoch[0] Batch [100]  Speed: 43.47 samples/sec        lossvalue=0.000999
INFO:root:Epoch[0] Batch [120]  Speed: 43.61 samples/sec        lossvalue=0.000947
INFO:root:Epoch[0] Batch [140]  Speed: 43.61 samples/sec        lossvalue=0.000898
INFO:root:Epoch[0] Batch [160]  Speed: 43.60 samples/sec        lossvalue=0.000861
INFO:root:Epoch[0] Batch [180]  Speed: 43.52 samples/sec        lossvalue=0.000850
INFO:root:Epoch[0] Batch [200]  Speed: 43.56 samples/sec        lossvalue=0.000837
INFO:root:Epoch[0] Batch [220]  Speed: 43.57 samples/sec        lossvalue=0.000806
INFO:root:Epoch[0] Batch [240]  Speed: 43.50 samples/sec        lossvalue=0.000785
INFO:root:Epoch[0] Batch [260]  Speed: 43.47 samples/sec        lossvalue=0.000772
INFO:root:Epoch[0] Batch [280]  Speed: 43.45 samples/sec        lossvalue=0.000747
INFO:root:Epoch[0] Batch [300]  Speed: 43.50 samples/sec        lossvalue=0.000726
INFO:root:Epoch[0] Batch [320]  Speed: 43.46 samples/sec        lossvalue=0.000740
INFO:root:Epoch[0] Batch [340]  Speed: 43.48 samples/sec        lossvalue=0.000720
INFO:root:Epoch[0] Batch [360]  Speed: 43.48 samples/sec        lossvalue=0.000718
INFO:root:Epoch[0] Batch [380]  Speed: 43.38 samples/sec        lossvalue=0.000691
INFO:root:Epoch[0] Train-lossvalue=0.000695
INFO:root:Epoch[0] Time cost=367.313
('train size after reset', 15683)
INFO:root:Epoch[1] Batch [20]   Speed: 44.28 samples/sec        lossvalue=0.000688
INFO:root:Epoch[1] Batch [40]   Speed: 43.48 samples/sec        lossvalue=0.000681
INFO:root:Epoch[1] Batch [60]   Speed: 43.49 samples/sec        lossvalue=0.000672
INFO:root:Epoch[1] Batch [80]   Speed: 43.45 samples/sec        lossvalue=0.000694
INFO:root:Epoch[1] Batch [100]  Speed: 43.44 samples/sec        lossvalue=0.000650
INFO:root:Epoch[1] Batch [120]  Speed: 43.41 samples/sec        lossvalue=0.000658
INFO:root:Epoch[1] Batch [140]  Speed: 43.46 samples/sec        lossvalue=0.000653
INFO:root:Epoch[1] Batch [160]  Speed: 43.42 samples/sec        lossvalue=0.000650
INFO:root:Epoch[1] Batch [180]  Speed: 43.29 samples/sec        lossvalue=0.000639
INFO:root:Epoch[1] Batch [200]  Speed: 43.37 samples/sec        lossvalue=0.000641
INFO:root:Epoch[1] Batch [220]  Speed: 43.30 samples/sec        lossvalue=0.000631
INFO:root:Epoch[1] Batch [240]  Speed: 43.41 samples/sec        lossvalue=0.000645
INFO:root:Epoch[1] Batch [260]  Speed: 43.40 samples/sec        lossvalue=0.000623
INFO:root:Epoch[1] Batch [280]  Speed: 43.40 samples/sec        lossvalue=0.000625
INFO:root:Epoch[1] Batch [300]  Speed: 43.30 samples/sec        lossvalue=0.000616
INFO:root:Epoch[1] Batch [320]  Speed: 43.29 samples/sec        lossvalue=0.000607
INFO:root:Epoch[1] Batch [340]  Speed: 43.30 samples/sec        lossvalue=0.000615
INFO:root:Epoch[1] Batch [360]  Speed: 43.43 samples/sec        lossvalue=0.000599
INFO:root:Epoch[1] Batch [380]  Speed: 43.37 samples/sec        lossvalue=0.000613
INFO:root:Epoch[1] Train-lossvalue=0.000619
INFO:root:Epoch[1] Time cost=359.079
('train size after reset', 15683)
INFO:root:Epoch[2] Batch [20]   Speed: 44.18 samples/sec        lossvalue=0.000594
INFO:root:Epoch[2] Batch [40]   Speed: 43.38 samples/sec        lossvalue=0.000586
INFO:root:Epoch[2] Batch [60]   Speed: 43.40 samples/sec        lossvalue=0.000597
INFO:root:Epoch[2] Batch [80]   Speed: 43.35 samples/sec        lossvalue=0.000592
INFO:root:Epoch[2] Batch [100]  Speed: 43.22 samples/sec        lossvalue=0.000596
INFO:root:Epoch[2] Batch [120]  Speed: 43.32 samples/sec        lossvalue=0.000583
INFO:root:Epoch[2] Batch [140]  Speed: 43.41 samples/sec        lossvalue=0.000574
INFO:root:Epoch[2] Batch [160]  Speed: 43.21 samples/sec        lossvalue=0.000583
INFO:root:Epoch[2] Batch [180]  Speed: 43.40 samples/sec        lossvalue=0.000569
INFO:root:Epoch[2] Batch [200]  Speed: 43.40 samples/sec        lossvalue=0.000588
lr-batch-epoch: 0.00025 219 2
INFO:root:Epoch[2] Batch [220]  Speed: 43.39 samples/sec        lossvalue=0.000571
INFO:root:Epoch[2] Batch [240]  Speed: 43.36 samples/sec        lossvalue=0.000583
INFO:root:Epoch[2] Batch [260]  Speed: 43.33 samples/sec        lossvalue=0.000576
INFO:root:Epoch[2] Batch [280]  Speed: 43.46 samples/sec        lossvalue=0.000561
INFO:root:Epoch[2] Batch [300]  Speed: 43.41 samples/sec        lossvalue=0.000568
```

**Comment by lightwind002** [comment]
It will show out of memory when I changed the batch size to 40 since there is only one 1080Ti in my computer. I noticed that this is a waring from Mxnet:
UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.05). Is this intended?
Is it a possible reason?

**Comment by notconvergingwtf** [comment]
Try reducing your lr. https://github.com/deepinsight/insightface/issues/572#issue-415588778

**Comment by nttstar** [comment]
@lightwind002 I mean batch-size 10 * 4 GPUs.

**Comment by lightwind002** [comment]
@notconvergingwtf ,  reduce lr to 1e-6 according to #572, there will be no NaN but the final loss value is 0.0011, which means the network is not trained good enough.
INFO:root:Saved checkpoint to "model/A-0149.params"
INFO:root:Epoch[38] Batch [140-160]     Speed: 8.16 samples/sec lossvalue=0.001109
INFO:root:Epoch[38] Batch [160-180]     Speed: 19.10 samples/sec        lossvalue=0.001112
INFO:root:Epoch[38] Batch [180-200]     Speed: 19.06 samples/sec        lossvalue=0.001109
INFO:root:Epoch[38] Batch [200-220]     Speed: 19.06 samples/sec        lossvalue=0.001106
INFO:root:Epoch[38] Batch [220-240]     Speed: 19.05 samples/sec        lossvalue=0.001114
INFO:root:Epoch[38] Batch [240-260]     Speed: 19.06 samples/sec        lossvalue=0.001107
INFO:root:Epoch[38] Batch [260-280]     Speed: 19.05 samples/sec        lossvalue=0.001085
INFO:root:Epoch[38] Batch [280-300]     Speed: 19.03 samples/sec        lossvalue=0.001109
INFO:root:Epoch[38] Batch [300-320]     Speed: 19.03 samples/sec        lossvalue=0.001103
INFO:root:Epoch[38] Batch [320-340]     Speed: 19.02 samples/sec        lossvalue=0.001104
lr change to 8e-09
lr-batch-epoch: 8e-09 348 38
INFO:root:loading recordio ./data_2d/ibug.rec...
('train size', 135)
[30000][ibug]NME: 0.180059
INFO:root:loading recordio ./data_2d/cofw_testset.rec...
('train size', 507)
[30000][cofw_testset]NME: 0.148820
INFO:root:loading recordio ./data_2d/300W.rec...
('train size', 600)
[30000][300W]NME: 0.162151
saving 150

**Comment by notconvergingwtf** [comment]
@lightwind002 True, but you can try to remove lr decreasement (you got 8e-09). Imo its too low. Anyway, there is another solution [here](https://github.com/deepinx/sdu-face-alignment/issues/1). But, as i've already mentioned, after some training time spikes still appear for both methods for me :(

**Comment by xiakejiang** [comment]
> @lightwind002 I mean batch-size 10 * 4 GPUs.

hi, have you release the pre-trained model of stacked u-net?

**Comment by xiakejiang** [comment]
> @lightwind002 I mean batch-size 10 * 4 GPUs.

how to generate .rec and .idx file for my own training?
thanks

**Comment by JackWolftoMc** [comment]
> > @lightwind002 I mean batch-size 10 * 4 GPUs.
> 
> how to generate .rec and .idx file for my own training?
> thanks

go and download an im2rec.py, you can refer to this blog which I referred to before.
https://blog.csdn.net/hanjiangxue_wei/article/details/86566348

**Comment by xiakejiang** [comment]
> Hi, here's my starting training log with sdu and batchsize=40(10*4)
> 
> ```
> INFO:root:Epoch[0] Batch [20]   Speed: 44.82 samples/sec        lossvalue=0.001892
> INFO:root:Epoch[0] Batch [40]   Speed: 43.47 samples/sec        lossvalue=0.001390
> INFO:root:Epoch[0] Batch [60]   Speed: 43.63 samples/sec        lossvalue=0.001170
> INFO:root:Epoch[0] Batch [80]   Speed: 43.68 samples/sec        lossvalue=0.001054
> INFO:root:Epoch[0] Batch [100]  Speed: 43.47 samples/sec        lossvalue=0.000999
> INFO:root:Epoch[0] Batch [120]  Speed: 43.61 samples/sec        lossvalue=0.000947
> INFO:root:Epoch[0] Batch [140]  Speed: 43.61 samples/sec        lossvalue=0.000898
> INFO:root:Epoch[0] Batch [160]  Speed: 43.60 samples/sec        lossvalue=0.000861
> INFO:root:Epoch[0] Batch [180]  Speed: 43.52 samples/sec        lossvalue=0.000850
> INFO:root:Epoch[0] Batch [200]  Speed: 43.56 samples/sec        lossvalue=0.000837
> INFO:root:Epoch[0] Batch [220]  Speed: 43.57 samples/sec        lossvalue=0.000806
> INFO:root:Epoch[0] Batch [240]  Speed: 43.50 samples/sec        lossvalue=0.000785
> INFO:root:Epoch[0] Batch [260]  Speed: 43.47 samples/sec        lossvalue=0.000772
> INFO:root:Epoch[0] Batch [280]  Speed: 43.45 samples/sec        lossvalue=0.000747
> INFO:root:Epoch[0] Batch [300]  Speed: 43.50 samples/sec        lossvalue=0.000726
> INFO:root:Epoch[0] Batch [320]  Speed: 43.46 samples/sec        lossvalue=0.000740
> INFO:root:Epoch[0] Batch [340]  Speed: 43.48 samples/sec        lossvalue=0.000720
> INFO:root:Epoch[0] Batch [360]  Speed: 43.48 samples/sec        lossvalue=0.000718
> INFO:root:Epoch[0] Batch [380]  Speed: 43.38 samples/sec        lossvalue=0.000691
> INFO:root:Epoch[0] Train-lossvalue=0.000695
> INFO:root:Epoch[0] Time cost=367.313
> ('train size after reset', 15683)
> INFO:root:Epoch[1] Batch [20]   Speed: 44.28 samples/sec        lossvalue=0.000688
> INFO:root:Epoch[1] Batch [40]   Speed: 43.48 samples/sec        lossvalue=0.000681
> INFO:root:Epoch[1] Batch [60]   Speed: 43.49 samples/sec        lossvalue=0.000672
> INFO:root:Epoch[1] Batch [80]   Speed: 43.45 samples/sec        lossvalue=0.000694
> INFO:root:Epoch[1] Batch [100]  Speed: 43.44 samples/sec        lossvalue=0.000650
> INFO:root:Epoch[1] Batch [120]  Speed: 43.41 samples/sec        lossvalue=0.000658
> INFO:root:Epoch[1] Batch [140]  Speed: 43.46 samples/sec        lossvalue=0.000653
> INFO:root:Epoch[1] Batch [160]  Speed: 43.42 samples/sec        lossvalue=0.000650
> INFO:root:Epoch[1] Batch [180]  Speed: 43.29 samples/sec        lossvalue=0.000639
> INFO:root:Epoch[1] Batch [200]  Speed: 43.37 samples/sec        lossvalue=0.000641
> INFO:root:Epoch[1] Batch [220]  Speed: 43.30 samples/sec        lossvalue=0.000631
> INFO:root:Epoch[1] Batch [240]  Speed: 43.41 samples/sec        lossvalue=0.000645
> INFO:root:Epoch[1] Batch [260]  Speed: 43.40 samples/sec        lossvalue=0.000623
> INFO:root:Epoch[1] Batch [280]  Speed: 43.40 samples/sec        lossvalue=0.000625
> INFO:root:Epoch[1] Batch [300]  Speed: 43.30 samples/sec        lossvalue=0.000616
> INFO:root:Epoch[1] Batch [320]  Speed: 43.29 samples/sec        lossvalue=0.000607
> INFO:root:Epoch[1] Batch [340]  Speed: 43.30 samples/sec        lossvalue=0.000615
> INFO:root:Epoch[1] Batch [360]  Speed: 43.43 samples/sec        lossvalue=0.000599
> INFO:root:Epoch[1] Batch [380]  Speed: 43.37 samples/sec        lossvalue=0.000613
> INFO:root:Epoch[1] Train-lossvalue=0.000619
> INFO:root:Epoch[1] Time cost=359.079
> ('train size after reset', 15683)
> INFO:root:Epoch[2] Batch [20]   Speed: 44.18 samples/sec        lossvalue=0.000594
> INFO:root:Epoch[2] Batch [40]   Speed: 43.38 samples/sec        lossvalue=0.000586
> INFO:root:Epoch[2] Batch [60]   Speed: 43.40 samples/sec        lossvalue=0.000597
> INFO:root:Epoch[2] Batch [80]   Speed: 43.35 samples/sec        lossvalue=0.000592
> INFO:root:Epoch[2] Batch [100]  Speed: 43.22 samples/sec        lossvalue=0.000596
> INFO:root:Epoch[2] Batch [120]  Speed: 43.32 samples/sec        lossvalue=0.000583
> INFO:root:Epoch[2] Batch [140]  Speed: 43.41 samples/sec        lossvalue=0.000574
> INFO:root:Epoch[2] Batch [160]  Speed: 43.21 samples/sec        lossvalue=0.000583
> INFO:root:Epoch[2] Batch [180]  Speed: 43.40 samples/sec        lossvalue=0.000569
> INFO:root:Epoch[2] Batch [200]  Speed: 43.40 samples/sec        lossvalue=0.000588
> lr-batch-epoch: 0.00025 219 2
> INFO:root:Epoch[2] Batch [220]  Speed: 43.39 samples/sec        lossvalue=0.000571
> INFO:root:Epoch[2] Batch [240]  Speed: 43.36 samples/sec        lossvalue=0.000583
> INFO:root:Epoch[2] Batch [260]  Speed: 43.33 samples/sec        lossvalue=0.000576
> INFO:root:Epoch[2] Batch [280]  Speed: 43.46 samples/sec        lossvalue=0.000561
> INFO:root:Epoch[2] Batch [300]  Speed: 43.41 samples/sec        lossvalue=0.000568
> ```

how you set per_batch_size and CUDA_VISIBLE_DEVICES ? I have 4 RTX-2080， when I set per_batch_size 40 and CUDA_VISIBLE_DEVICES='0,1,2,3'， the 'out of memory' proble alse happend.  And I also meet the NAN loss problem.
