### ISSUE TITLE
megaface align

### ISSUE THREAD

**Issue by LiuWeiLun** [deepinsight/insightface#584]
When I use align_facescrub.py to aligh the facescrub dataset of the megaface, I can't find the file facescrub_uncropped_features_list.json. Where can I download one?

**Comment by LiuWeiLun** [comment]
if you know the answer, please tell me, thank you very much!

**Comment by amjltc295** [comment]
I think it is in the devkit on the MegaFace website: http://megaface.cs.washington.edu/participate/challenge.html
