### ISSUE TITLE
Best Strategy for 10 Live cameras

### ISSUE THREAD

**Issue by uday60** [deepinsight/insightface#590]
Hi I am going to be testing insight face at an upcoming event and I was wondering what would be the best  strategy for implementing insightface. So far I have thought of the following:

1. Run mtcnn detector on RTSP stream along with tracking and send 5 cropped faces per tracker id to a queue.
2. Run the client app to fetch the data from queue and send the cropped face to the insightface inference server and calculate the distance and update the database.

Please share your thoughts regarding this architecture and suggest improvements to implement insightface in the best possible manner.

Thanks.

**Comment by MyraBaba** [comment]
I think it could be a very useful information how we can make a multithreaded inference ? As I saw in the mxnet 1.4 multithread is supported. 

Basiclly can we get features of the 10 faces same time in the same python code ? is the multithreaded queue can help ? 

Do we need to assign more model copy inside the code ? 

How we can process 10 faces simultaneously specially . this part :

```
model.get_input(img)

model.get_feature(img)

```
