### ISSUE TITLE
Could you please share the strategy to generate pairs of AgeDB30?

### ISSUE THREAD

**Issue by MccreeZhao** [deepinsight/insightface#593]
Rencently I've download the raw AgeDB30 and I want use different method to allign them and test my models' performance on it.  Since I don't know your strategy to generate face pairs, I can't compare the performance from MTCNN and my allignment method. Could you please share the pair list?

**Comment by nttstar** [comment]
I will provide them later.

**Comment by MccreeZhao** [comment]
Waiting for that~
Thanks and nice work!

**Comment by clhne** [comment]
@MccreeZhao @nttstar 
Had your guys got the pair list?
Thanks.

**Comment by suryaprakaz** [comment]
Hi,

Is the pair list made available?
Thanks
