### ISSUE TITLE
run_experiment.py

### ISSUE THREAD

**Issue by zeeshanahmedkhan** [deepinsight/insightface#596]
I am un-able to find  "run_experiment.py" for Megaface testing
please guide me

**Comment by xiezheng-cs** [comment]
> I am un-able to find "run_experiment.py" for Megaface testing
> please guide me
megaface：http://megaface.cs.washington.edu/participate/challenge.html

**Comment by zeeshanahmedkhan** [comment]
thanks

**Comment by 2151330** [comment]
Can you give a baidu network disk link？I cannot download the Linux Development Kit (.zip) from the link above
