### ISSUE TITLE
Do we need to align the cropped facescrub dataset?

### ISSUE THREAD

**Issue by lymanblue** [deepinsight/insightface#598]
Hi~

Thank you for the great work!

We are confused about the usage of align_facescrub.py.
Should we apply align_facescrub.py to the cropped facescrub dataset?
Or Is the align_facescrub.py only utilized for the uncropped one?

Thank you.

**Comment by khawar-islam** [comment]
@lymanblue  You can download cleaned version from here, if dataset is helpful for you, please consider to cite it
https://github.com/khawar-islam/FPVT_BMVC22
