### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by xiaosuzhang** [deepinsight/insightface#601]
I follow your steps, but i meet the problem:
 src/storage/./pooled_storage_manager.h:143: cudaMalloc failed: out of memory.
When i set the  default.per_batch_size = 1, it also meet the problem. How should i do?

**Comment by Be-carefull** [comment]
I meet same problem too.do you have solved it?

**Comment by Wxsang** [comment]
@Be-carefull 
I have the same problem,but i has used mx-90 with cuda9.
I test the train.py in two deffirent machine(GTX TITAN X *4, Tesla P100*4), but i meet the same problem.
Could you give more details about the problem, I will appreciate it.
