### ISSUE TITLE
meet the problem

### ISSUE THREAD

**Issue by xiaosuzhang** [deepinsight/insightface#602]
When i follow your steps, i meet the problem,how should i do?
 CUDA_VISIBLE_DEVICES='0' python -u train.py --network r100 --loss arcface --dataset emore
gpu num: 1
prefix ./models/r100-arcface-emore/model
image_size [112, 112]
num_classes 85742
Called with argument: Namespace(batch_size=128, ckpt=3, ctx_num=1, dataset='emore', frequent=20, image_channel=3, kvstore='device', loss='arcface', lr=0.1, lr_steps='100000,160000,220000', models_root='./models', mom=0.9, network='r100', per_batch_size=128, pretrained='', pretrained_epoch=1, rescale_threshold=0, verbose=2000, wd=0.0005) {'loss_m1': 1.0, 'loss_m2': 0.5, 'loss_m3': 0.0, 'net_act': 'prelu', 'emb_size': 512, 'data_rand_mirror': True, 'num_layers': 100, 'loss_name': 'margin_softmax', 'val_targets': ['lfw', 'cfp_fp', 'agedb_30'], 'ce_loss': True, 'net_input': 1, 'image_shape': [112, 112, 3], 'fc7_lr_mult': 1.0, 'ckpt_embedding': True, 'net_unit': 3, 'net_output': 'E', 'num_workers': 1, 'data_images_filter': 0, 'dataset': 'emore', 'num_classes': 85742, 'fc7_no_bias': False, 'loss': 'arcface', 'data_color': 0, 'loss_s': 64.0, 'dataset_path': '../datasets/face', 'data_cutoff': False, 'net_se': 0, 'net_multiplier': 1.0, 'fc7_wd_mult': 1.0, 'network': 'r100', 'net_name': 'fresnet', 'workspace': 256, 'max_steps': 0, 'bn_mom': 0.9}
0 1 E 3 prelu
INFO:root:loading recordio ../datasets/face/train.rec...
header0 label [ 3804847.  3890011.]
id2range 85164
3804846
rand_mirror True
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver lfw
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
loading bin 13000
(14000L, 3L, 112L, 112L)
ver cfp_fp
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver agedb_30
lr_steps [100000, 160000, 220000]
call reset()
/home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/module/base_module.py:505: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.0078125). Is this intended?
  optimizer_params=optimizer_params)
[20:14:28] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[20:14:28] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "train.py", line 366, in <module>
    main()
  File "train.py", line 363, in main
    train_net(args)
  File "train.py", line 358, in train_net
    epoch_end_callback = epoch_cb )
  File "/home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/module/base_module.py", line 539, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/module/module.py", line 773, in update_metric
    self._exec_group.update_metric(eval_metric, labels, pre_sliced)
  File "/home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 639, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/metric.py", line 304, in update_dict
    metric.update_dict(labels, preds)
  File "/home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/metric.py", line 132, in update_dict
    self.update(label, pred)
  File "/home/wr506/insightface/recognition/metric.py", line 20, in update
    pred_label = pred_label.asnumpy().astype('int32').flatten()
  File "/home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/ndarray/ndarray.py", line 1980, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:14:28] src/operator/nn/./cudnn/cudnn_convolution-inl.h:909: Failed to find any forward convolution algorithm.  with workspace size of 268435456 bytes, please consider reducing batch/model size or increasing the workspace size

Stack trace returned 10 entries:
[bt] (0) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x3f042a) [0x7fbe41f8742a]
[bt] (1) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x3f0a41) [0x7fbe41f87a41]
[bt] (2) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x37096b4) [0x7fbe452a06b4]
[bt] (3) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x370da8d) [0x7fbe452a4a8d]
[bt] (4) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x36f975c) [0x7fbe4529075c]
[bt] (5) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x36f9beb) [0x7fbe45290beb]
[bt] (6) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x36faf53) [0x7fbe45291f53]
[bt] (7) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x36fbfc3) [0x7fbe45292fc3]
[bt] (8) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x3701ff1) [0x7fbe45298ff1]
[bt] (9) /home/wr506/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2cbba39) [0x7fbe44852a39]

**Comment by skyeyeCV** [comment]
Have you solved this problem yet?I met this problem,too.

**Comment by conghau0112** [comment]
@skyeyeCV  Have you solved this problem yet?I met this problem,too.... Can you help me
