### ISSUE TITLE
Mismatch Error in IJB Verification module

### ISSUE THREAD

**Issue by zeeshanahmedkhan** [deepinsight/insightface#604]
Hi 
While executing the IJB evaluaion file, I am getting shape mis-match error while executing "Step 4" (Pic atached). I am just running the given file as  it is, on pretrained model.   
https://github.com/deepinsight/insightface/blob/master/Evaluation/IJB/IJBB_Evaluation_MS1MV2.ipynb

Please guide me, Thanks

![Screenshot from 2019-03-21 14-36-33](https://user-images.githubusercontent.com/16646791/54736775-a9cfb080-4be7-11e9-8454-cab57edd325e.png)

**Comment by nttstar** [comment]
``score[s]  = similarity_score.flatten()`` may help

**Comment by zeeshanahmedkhan** [comment]
Hi nttstar
Thanks, 
Yes, now it is working
