### ISSUE TITLE
please update video demo code

### ISSUE THREAD

**Issue by westpilgrim** [deepinsight/insightface#608]
author said he will update the new face detector and video demo code this month, but he has not done it yet. I tried to implement the video demo code myself, but found the result is far worse than the author's .
can you pls update the code?

**Comment by GSlog** [comment]
i have no idea about the video demo. could i get your code for the demo video? or give me some ideas.

**Comment by westpilgrim** [comment]
> i have no idea about the video demo. could i get your code for the demo video? or give me some ideas.

see sphere face's video demo description :https://github.com/wy1iu/sphereface     I believe the two are the same.

**Comment by GSlog** [comment]
thx！

**Comment by GSlog** [comment]
i have finished it!

**Comment by GSlog** [comment]
> > i have no idea about the video demo. could i get your code for the demo video? or give me some ideas.
> 
> see sphere face's video demo description :https://github.com/wy1iu/sphereface I believe the two are the same.

thx！i have finished it.

**Comment by clhne** [comment]
@GSlog Can you share your's demo code.
Many thanks.

**Comment by GSlog** [comment]
> @GSlog Can you share your's demo code.
> Many thanks.

可以

**Comment by GSlog** [comment]
把这三个文件放到insightface项目的deploy文件夹下面，一个是做人脸识别库的，一个是做视频的，另外一个不用管用就完事了






------------------ 原始邮件 ------------------
发件人: "Just do it"<notifications@github.com>;
发送时间: 2019年6月4日(星期二) 中午11:27
收件人: "deepinsight/insightface"<insightface@noreply.github.com>;
抄送: "快乐小星"<1056318261@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [deepinsight/insightface] please update video demo code (#608)




@GSlog Can you share your's demo code.
 Many thanks.
