### ISSUE TITLE
Extract image from train.rec in Ms1M-ArcFace

### ISSUE THREAD

**Issue by estarpro** [deepinsight/insightface#612]
@nttstar .I know how to extract image from train.rec in Ms1M-ArcFace.And I want to divide different people's images into different folder.Obviously,it's too slow classified by people.Is there any data structure in train.rec to record image's class？Thank you for any reply.

**Comment by fengxxue** [comment]
The script is in insightface/recognition/rec2image.py

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md
