### ISSUE TITLE
How to generate "/raid5data/dplearn/megaface/megaface_mtcnn_112x112/lst"?

### ISSUE THREAD

**Issue by neveriveup** [deepinsight/insightface#614]

**Comment by nttstar** [comment]
Use the new megaface evaluation toolkit at https://github.com/deepinsight/insightface/tree/master/Evaluation/Megaface

**Comment by neveriveup** [comment]
@nttstar  您好，我按照上面的步骤操作了但是出现以下问题Traceback (most recent call last):
  File "gen_megaface.py", line 179, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "gen_megaface.py", line 114, in main
    img = read_img(image_path)
  File "gen_megaface.py", line 24, in read_img
    img = cv2.imread(image_path, cv2.CV_LOAD_IMAGE_COLOR)
AttributeError: 'module' object has no attribute 'CV_LOAD_IMAGE_COLOR'
还有我想问下ROOT=$(dirname `which $0`)中的dirname是否也得改？

**Comment by neveriveup** [comment]
@nttstar  您好，我按照上面的步骤操作了但是出现以下问题Traceback (most recent call last):
  File "gen_megaface.py", line 179, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "gen_megaface.py", line 114, in main
    img = read_img(image_path)
  File "gen_megaface.py", line 24, in read_img
    img = cv2.imread(image_path, cv2.CV_LOAD_IMAGE_COLOR)
AttributeError: 'module' object has no attribute 'CV_LOAD_IMAGE_COLOR'
还有我想问下ROOT=$(dirname `which $0`)中的dirname是否也得改？
