### ISSUE TITLE
dataset download link

### ISSUE THREAD

**Issue by cassie101** [deepinsight/insightface#616]
Hi @nttstar, I read your paper on Stacked Dense U-Nets with Dual Transformers for Robust Face Alignment from [here](
https://github.com/deepinsight/insightface/tree/master/alignment) and would like to run the experiment. 
However, I do not have access to baidu pan to download the training and testing dataset, just wondering could you provide the download link using google drive or dropbox? Thank you.

**Comment by nttstar** [comment]
ok we will do it soon

**Comment by zisianw** [comment]
@nttstar thank you for your prompt reply, look forward to a pre-trained model too.

**Comment by jiankangdeng** [comment]
I have added a dropbox link to download the training data.

**Comment by BonacimPacer** [comment]
Hi @jiankangdeng, the Dropbox link is not available anymore. Would really appreciate if a new link was posted since I can't download from Baidu.
