### ISSUE TITLE
how to run age test.py

### ISSUE THREAD

**Issue by m3m3-chan** [deepinsight/insightface#619]
Hello,
How can I run the age/gender detection test.py file without using GPU?
I get the following error regarding GPU value : 

`RuntimeError: simple_bind error. Arguments:
data: (1, 3, 112, 112)
[14:32:59] C:\Jenkins\workspace\mxnet-tag\mxnet\src\storage\storage.cc:143: Compile with USE_CUDA=1 to enable GPU usage`

**Comment by ImOmid** [comment]
Hi,
You can change set line 46 in face_model.py to elif args.gpu==-1: and pass -1 for --gpu while running the code. So, mxnet will run on CPU.
python test.py --gpu -1

**Comment by m3m3-chan** [comment]
Hi @ImOmid ,
thanks for the reply. There's something I couldn't understand in the solution you provided. In face_model.py file the lines 45-46 are: 
```
45    self.args = args
46   ctx = mx.gpu(args.gpu)
```
How do I add this line "elif args.gpu==-1:" ?  I would appreciate it if you could explain more specifically what to change. Based on my understanding I tried the below 2 ways  but both failed.
way 1: 
```
self.args = args
if args.gpu==-1:
  ctx = mx.gpu(args.gpu)
```
resulted error:
```
  File "C:\Users\malabdou\Documents\Python\PyProj\GenderAge\X1insightface-master\deploy\helper.py", line 156, in detect_first_stage
    output = net.predict(input_buf)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\mxnet\model.py", line 699, in predict
    self._init_predictor(data_shapes, type_dict)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\mxnet\model.py", line 622, in _init_predictor
    self.ctx[0], grad_req='null', type_dict=type_dict, **shapes)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\mxnet\symbol\symbol.py", line 1529, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
conv2_weight: (16, 10, 3, 3)
conv2_bias: (16,)
conv4_2_bias: (4,)
prelu1_gamma: (10,)
conv3_bias: (32,)
data: (1, 3, 68, 68)
conv4_1_bias: (2,)
prelu3_gamma: (32,)
conv4_2_weight: (4, 32, 1, 1)
conv3_weight: (32, 16, 3, 3)
conv1_weight: (10, 3, 3, 3)
prelu2_gamma: (16,)
conv1_bias: (10,)
conv4_1_weight: (2, 32, 1, 1)
[15:59:03] C:\Jenkins\workspace\mxnet-tag\mxnet\include\mxnet/base.h:299: Please compile with CUDA enabled for cuda features
```

2nd Way: 
```
    self.args = args
    if args.gpu==-1: 
      ctx = mx.cpu()
    else:
      ctx = mx.gpu(args.gpu)
```
resulted error:
```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    gender, age = model.get_ga(img)
  File "C:\Users\malabdou\Documents\Python\PyProj\GenderAge\X1insightface-master\deploy\face_model.py", line 107, in get_ga
    self.ga_model.forward(db, is_train=False)
AttributeError: 'NoneType' object has no attribute 'forward'
```

**Comment by ImOmid** [comment]
Hi @m3m3-chan,
Try the following

`if args.gpu>=0:
      ctx = mx.gpu(args.gpu)
 elif args.gpu==-1:
      ctx = mx.cpu()`

so when you run the test with --gpu -1 it will run on cpu.

**Comment by m3m3-chan** [comment]
thank you @ImOmid  I tried your way & now I have this error below
```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    gender, age = model.get_ga(img)
  File "C:\Users\malabdou\Documents\Python\PyProj\Age\4insightface-master\deploy\face_model.py", line 103, in get_ga
    self.ga_model.forward(db, is_train=False)
```
I read somehwere that model.forward(input) is similar to model(input) so I tried that but it didn't work, error `TypeError: 'NoneType' object is not callable
`
This got me thinking is it not reading the model at all?

**Comment by ImOmid** [comment]
Hi @m3m3-chan,

My version of code are as follows, are yours the same? It should work fine.
```
import face_model
import argparse
import cv2
import sys
import numpy as np
import datetime

parser = argparse.ArgumentParser(description='face model test')
# general
parser.add_argument('--image-size', default='112,112', help='')
parser.add_argument('--image', default='Tom_Hanks_54745.png', help='')
parser.add_argument('--model', default='model/model,0', help='path to load model.')
parser.add_argument('--gpu', default=0, type=int, help='gpu id') # pass -1 for CPU
parser.add_argument('--det', default=0, type=int, help='mtcnn option, 1 means using R+O, 0 means detect from begining')
args = parser.parse_args()

model = face_model.FaceModel(args)
#img = cv2.imread('Tom_Hanks_54745.png')
img = cv2.imread(args.image)
img = model.get_input(img)
#f1 = model.get_feature(img)
#print(f1[0:10])
for _ in range(5):
  gender, age = model.get_ga(img)
time_now = datetime.datetime.now()
count = 200
#for _ in range(count):
#  gender, age = model.get_ga(img)
#time_now2 = datetime.datetime.now()
#diff = time_now2 - time_now
#print('time cost', diff.total_seconds()/count)
print('gender is',gender)
print('age is', age)
```

**Comment by m3m3-chan** [comment]
Hi @ImOmid 
Thanks for the reply.
After comparing your code with mine, I found out I was running the wrong version of test.py. The one I was running was in the deploy/test.py while the one on gender-age/test.py matches your code.
So I ran the code but still got an error! :
```
hs = int(math.ceil(height * scale))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```
I did some basic print testing & seems like the scale value is passed as None which is what causes an issue ... any idea to why this error occurs?

Thank you in advance,

**Comment by JAYM629** [comment]
> Hi @ImOmid ,
> thanks for the reply. There's something I couldn't understand in the solution you provided. In face_model.py file the lines 45-46 are:
> 
> ```
> 45    self.args = args
> 46   ctx = mx.gpu(args.gpu)
> ```
> 
> How do I add this line "elif args.gpu==-1:" ? I would appreciate it if you could explain more specifically what to change. Based on my understanding I tried the below 2 ways but both failed.
> way 1:
> 
> ```
> self.args = args
> if args.gpu==-1:
>   ctx = mx.gpu(args.gpu)
> ```
> 
> resulted error:
> 
> ```
>   File "C:\Users\malabdou\Documents\Python\PyProj\GenderAge\X1insightface-master\deploy\helper.py", line 156, in detect_first_stage
>     output = net.predict(input_buf)
>   File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\mxnet\model.py", line 699, in predict
>     self._init_predictor(data_shapes, type_dict)
>   File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\mxnet\model.py", line 622, in _init_predictor
>     self.ctx[0], grad_req='null', type_dict=type_dict, **shapes)
>   File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\mxnet\symbol\symbol.py", line 1529, in simple_bind
>     raise RuntimeError(error_msg)
> RuntimeError: simple_bind error. Arguments:
> conv2_weight: (16, 10, 3, 3)
> conv2_bias: (16,)
> conv4_2_bias: (4,)
> prelu1_gamma: (10,)
> conv3_bias: (32,)
> data: (1, 3, 68, 68)
> conv4_1_bias: (2,)
> prelu3_gamma: (32,)
> conv4_2_weight: (4, 32, 1, 1)
> conv3_weight: (32, 16, 3, 3)
> conv1_weight: (10, 3, 3, 3)
> prelu2_gamma: (16,)
> conv1_bias: (10,)
> conv4_1_weight: (2, 32, 1, 1)
> [15:59:03] C:\Jenkins\workspace\mxnet-tag\mxnet\include\mxnet/base.h:299: Please compile with CUDA enabled for cuda features
> ```
> 
> 2nd Way:
> 
> ```
>     self.args = args
>     if args.gpu==-1: 
>       ctx = mx.cpu()
>     else:
>       ctx = mx.gpu(args.gpu)
> ```
> 
> resulted error:
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 23, in <module>
>     gender, age = model.get_ga(img)
>   File "C:\Users\malabdou\Documents\Python\PyProj\GenderAge\X1insightface-master\deploy\face_model.py", line 107, in get_ga
>     self.ga_model.forward(db, is_train=False)
> AttributeError: 'NoneType' object has no attribute 'forward'
> ```

Have you solve this problem? I also meet this problem
