### ISSUE TITLE
测试megaface都很正常，但没输出Rank 1的值

### ISSUE THREAD

**Issue by wzj5133329** [deepinsight/insightface#621]
这是后面全部的输出，请问有人碰到过这种情况吗？
Done matching! Score matrix size: 3530 1000000
Saving to ../../mx_results/otherFiles/facescrub_megaface_r100ii_1000000_1.bin
Computing test results with 1000000 images for set 1
Loaded 3530 probes spanning 80 classes
Loading from ../../mx_results/otherFiles/facescrub_facescrub_r100ii.bin
Probe score matrix size: 3530 3530
distractor score matrix size: 3530 1000000
Done loading. Time to compute some stats!
/home/asd/Install/insightface/Evaluation/Megaface

**Comment by nttstar** [comment]
可能是机器内存不够

**Comment by wzj5133329** [comment]
谢谢回复，在这次失败前我测试成功过，我将去杀掉其他进程再重新试试。

**Comment by RiverJWang** [comment]
> 谢谢回复，在这次失败前我测试成功过，我将去杀掉其他进程再重新试试。
成功了吗？是内存不够的？我16GB

**Comment by Bryan-bai** [comment]
@bgbofficial yes，32GB at least
