### ISSUE TITLE
IBM: Diversity in Faces Dataset

### ISSUE THREAD

**Issue by meanmee** [deepinsight/insightface#625]
This is a very new dataset released by IBM recently. Compared to those facial image dataset released before, DiF(Diversity in Faces Dataset) provides a more balanced distribution and broader coverage of facial images.

Anyone want to give it a try? 
We can show our results in this issue.

**Comment by IrvingShu** [comment]
I found that there is no label of the identities. Did you have the labels of the  identities.

**Comment by meanmee** [comment]
No, I haven't download it. We've found some cases what the data set described exist actually. for example, when our face model encountered facial images of Asia race, especially the people comes from Southeast Asia countries, the performance is much lower than white which have a huge proportion in training set.

**Comment by ebagdasa** [comment]
@IrvingShu  did you manage to understand ITA field? It doesn't make sense to me.
