### ISSUE TITLE
mobilefacenet手机端测试

### ISSUE THREAD

**Issue by aa12356jm** [deepinsight/insightface#629]
我使用model zoo中提供的mobilefacenet模型转换到ncnn中，在手机端测试（小米8，高通845），cpu 4线程跑的速度需要40ms左右。
mobilefacenet的作者在论文中给的性能指标是在高通820处理器，cpu，4线程可以跑到24ms。
感觉速度差异太大了， 没发现问题在哪里，@nttstar 大佬这个是为啥啊？谢谢

**Comment by szad670401** [comment]
尝试删除模型参数中的极小值。

**Comment by aa12356jm** [comment]
论文中说的是没有量化的情况下做到的，并且这样量化也会影响精度吧？

**Comment by szad670401** [comment]
这个不是量化操作，模型中接近0的值(<e-4)会导致模型运行速度缓慢。

**Comment by aa12356jm** [comment]
ok，我试试哈，谢谢
