### ISSUE TITLE
Can we still get the models whose 'fc7' layers' weights are not deleted yet? many thanks!

### ISSUE THREAD

**Issue by Isaver23** [deepinsight/insightface#633]
For some reason, I may need to finetune models on emore datasets with 'fc7' layers weights, since I don't want to retrain the last 'fc7' layers. so is there any chance we could still get the not deleted version of models? 

Thanks a lot for your great works again!

**Comment by Isaver23** [comment]
@nttstar

**Comment by nttstar** [comment]
``config.ckpt_embedding=False``

**Comment by Isaver23** [comment]
> config.ckpt_embedding=False

Thanks for your reply! I have learned how to save 'fc7' layers weights in my training as you said, but what I really need is the  models on your model-zoo, whose 'fc7' layers are already deleated as far as I know.

**Comment by nttstar** [comment]
No, never come back.. You may need to train it by yourself.

**Comment by Isaver23** [comment]
> No, never come back.. You may need to train it by yourself.

Sad. Thanks anyway!
