### ISSUE TITLE
代码改成CPU上跑

### ISSUE THREAD

**Issue by zzjiang** [deepinsight/insightface#636]
您们好，我可以请教两大问题吗？
1. 目前的环境是 Centos7+python2.7+mxnet+cpu。于是想将代码中有关的GPU改成CPU，改着改着，错误百出。所以请问作者有何解决方案。
2.目前想用mtcnn（人脸检测）+insightface（人脸识别），来实现人脸识别功能。。但是无法从根目录《readme》查找的执行程序的入口。。请问最新版本中，哪个文件是生成底图的特征值；哪个文件是基于欧氏距离比对图形的。

Lastly，I am  in shanghai too。 Thanks!

**Comment by JiaoPaner** [comment]
看deploy/test.py 就有

**Comment by zzjiang** [comment]
> 看deploy/test.py 就有

谢谢哈

**Comment by zzjiang** [comment]
邮件已收到，谢了~~
