### ISSUE TITLE
LResNet100E-IR run on tvm cpu performance

### ISSUE THREAD

**Issue by felix-lyj** [deepinsight/insightface#637]
Hello guys,

The CPU I used is Xeon(R) CPU E5-2650 v3. 

LResNet100E-IR run on mxnet cpu takes about 300ms to get one face feature.

LResNet100E-IR compiled with tvm target llvm -mcpu=haswell takes 100ms to get one face feature when I run in a tvmai/demo-cpu docker container. The container has a tvm 0.4 version. The result is not so impressive as yours in tvm benchmark which is 45ms.

Then I git clone the latest tvm 0.6 src to the tvmai/demo-cpu container and build it. The new built tvm get following warnings when compile LResNet100E-IR with the same code as before.

Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 3, 112, 112, 'float32'), (64, 3, 3, 3, 'float32'), (1, 1), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 64, 112, 112, 'float32'), (64, 64, 3, 3, 'float32'), (1, 1), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 64, 112, 112, 'float32'), (64, 64, 3, 3, 'float32'), (2, 2), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 64, 112, 112, 'float32'), (64, 64, 1, 1, 'float32'), (2, 2), (0, 0), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 64, 56, 56, 'float32'), (128, 64, 3, 3, 'float32'), (1, 1), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 128, 56, 56, 'float32'), (128, 128, 3, 3, 'float32'), (2, 2), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 128, 28, 28, 'float32'), (256, 128, 3, 3, 'float32'), (1, 1), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 256, 28, 28, 'float32'), (256, 256, 3, 3, 'float32'), (2, 2), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 256, 14, 14, 'float32'), (512, 256, 3, 3, 'float32'), (1, 1), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
Cannot find config for target=llvm -mcpu=haswell, workload=('conv2d', (1, 512, 14, 14, 'float32'), (512, 512, 3, 3, 'float32'), (2, 2), (1, 1), (1, 1), 'NCHW', 'float32'). A fallback configuration is used, which may bring great performance regression.
WARNING:autotvm:Cannot find config for target=llvm -mcpu=haswell, workload=('dense', (1, 25088, 'float32'), (512, 25088, 'float32'), (512, 'float32')). A fallback configuration is used, which may bring great performance regression.

Although the model is compiled, it costs 190ms, very great performance regression.

So is there any trick when you build tvm to get the 45ms performance? How do you set the config.cmake file? Thanks.

**Comment by szad670401** [comment]
Try to remove minimal value(<e-4) in model parameters,These value will cause performance problem .

**Comment by jake221** [comment]
> Try to remove minimal value(<e-4) in model parameters,These value will cause bad performance.

My CPU is Intel(R) Xeon(R) Silver 4109T CPU @ 2.00GHz (8cores).

I remove minimal value (<e-10) in model parameters and I need 70ms to get 512 dim features for each face image. And then I remove minimal value (<e-4) in model parameters and it still takes around 70ms to obtain face features. So I guess the minimal value is not the main bottleneck in inferencing acceleration.

**Comment by lynneHuang10** [comment]
> > Try to remove minimal value(<e-4) in model parameters,These value will cause bad performance.
> 
> My CPU is Intel(R) Xeon(R) Silver 4109T CPU @ 2.00GHz (32cores).
> 
> I remove minimal value (<e-10) in model parameters and I need 70ms to get 512 dim features for each face image. And then I remove minimal value (<e-4) in model parameters and it still takes around 70ms to obtain face features. So I guess the minimal value is not the main bottleneck in inferencing acceleration.

can you give me an example code about the minimal value(<e-4) removal in model parameters？ thanks

**Comment by jake221** [comment]
> Try to remove minimal value(<e-4) in model parameters,These value will cause bad performance.


@TVM | @MXNet(pip install) | OpenCV-DNN
-- | -- | --
E5-2650 v4 2.20GHz @ 24 Threads | 45ms | 600ms | TODO
Macbook r2015 2.2G@4 threads | 178ms | 433ms | TODO
Nvidia GTX 1080 | 8.40ms | 31ms | TODO

**Comment by jinjunkuang** [comment]
there are many types of parameters in LResNet100E-IR model, such as weight、β、γ, which one should be remove?

**Comment by jinjunkuang** [comment]
With latest tvm version @0.6,  e5-2680v4 one thread need about 400ms to process one face feature, the input is 128*128 aligned picture. @szad670401

**Comment by tranvanhoa533** [comment]
> Try to remove minimal value(<e-4) in model parameters,These value will cause bad performance.

Can you share with me how to do it ?

**Comment by gasgallo** [comment]
Interested in the procedure to remove minimal values..

**Comment by gasgallo** [comment]
@jinjunkuang 

> With latest tvm version @0.6, e5-2680v4 one thread need about 400ms to process one face feature, the input is 128*128 aligned picture. @szad670401

How did you obtain that result? I'm currently running the same model on e5-2630v4 with even a smaller input image and inference takes more than 600ms on single thread

**Comment by szad670401** [comment]
Thr results in the table are multi-threads.

**Comment by gasgallo** [comment]
> Thr results in the table are multi-threads.

I quoted @jinjunkuang comment that mentions single-thread inference

**Comment by gasgallo** [comment]
I answer myself about the removal of small weights. I've used the following code:
```
   if removeSmallWeights:
      count = 0
      thresh = 1e-10
      for key, value in params.items():
         value_np = value.asnumpy()

         if len(value_np.shape) == 1:
            for idx, v in enumerate(value_np):
               if abs(v) < thresh:
                  value_np[idx] = 0
                  count += 1
            params[key] = tvm.ndarray.array(value_np, ctx=tvm.cpu())
         # elif len(value_np.shape) == 4:
         #    for x in range(value_np.shape[0]):
         #       for y in range(value_np.shape[1]):
         #          for z in range(value_np.shape[2]):
         #             for d in range(value_np.shape[3]):
         #                v = value_np[x, y, z, d]
         #                # print(v)
         #                if abs(v) < thresh:
         #                   value_np[x, y, z, d] = 0
         #                   count += 1
         #    params[key] = tvm.ndarray.array(np.asarray(value_np, dtype=np.float32), ctx=tvm.cpu())

      print('Removed weights: {}'.format(count))
```
I've noticed that the first part is enough to improve model performance by 30% while removing only 0.002% of the weights.

@jinjunkuang @tranvanhoa533 if you were still wondering about how to do it

**Comment by gasgallo** [comment]
@jinjunkuang any update about your model performance?

**Comment by Counterfeiter** [comment]
On my i7 I can reach with tvm build the the mxnet performance... but no improvement.
On my raspberry pi 4b (64 bit) I can't reach the mxnet baseline.

@gasgallo on tvm opt_level=3 it fails to set zeros... I have to set the threshold, not zero...
This degrades the cosines distance compared to mxnet output to 0.99999 with a random vector.

```
  def remove_denorm(params):
      thresh = 1e-10
      for key, value in params.items():
          value_np = value.asnumpy()
          value_np[abs(value_np) < thresh] = np.float32(thresh)
          params[key] = tvm.nd.array(value_np, ctx=tvm.cpu())
```

**Comment by Counterfeiter** [comment]
I build the the model with TVM and ARMs ComputeLibrary for the raspberry again. I got the same inference time like mxnet. So, mxnet and TVM has no major difference on my tests... but there are so much options and I didn't run the auto tuning... It will took days I think.  
If someone has good settings for Cortex A72 64bit contact me please...
