### ISSUE TITLE
loss NAN problem

### ISSUE THREAD

**Issue by chenshen03** [deepinsight/insightface#638]
I follow the tutorial and run with `CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train.py --network r100 --loss arcface --dataset emore`. But it encountered the loss NAN problem.

![image](https://user-images.githubusercontent.com/20432947/56454068-3784f400-637e-11e9-859c-dff9c34120c2.png)

**Comment by chenshen03** [comment]
solved

**Comment by joey20130608** [comment]
> solved

how did u solved？

**Comment by lrain-CN** [comment]
> I follow the tutorial and run with `CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train.py --network r100 --loss arcface --dataset emore`. But it encountered the loss NAN problem.
> 
> ![image](https://user-images.githubusercontent.com/20432947/56454068-3784f400-637e-11e9-859c-dff9c34120c2.png)
请问这问题怎么解决的， 谢谢

**Comment by miraj7789** [comment]
I am also having similar issue. Has anyone figured this out?
