### ISSUE TITLE
how to pretrain in parallel training ?

### ISSUE THREAD

**Issue by maryhh** [deepinsight/insightface#640]
https://github.com/deepinsight/insightface/blob/1a8f0fc6b6aad73594c5e8f45704192c4185e168/recognition/parall_module_local_v1.py#L148
why not Initialize arg_params and aux_params here? esym:[fc1,label].asym[fc7],only initialize parameter until fc1.

_Originally posted by @maryhh in https://github.com/deepinsight/insightface/issues/574#issuecomment-485400205_

**Comment by nttstar** [comment]
PR is welcome
