### ISSUE TITLE
YouTube Face dataset

### ISSUE THREAD

**Issue by zeeshanahmedkhan** [deepinsight/insightface#641]
Hi 
I tried to execute the Youtube Face Dataset as per your YTF file "https://github.com/deepinsight/insightface/blob/master/src/eval/ytf.py" on the pre-trained model of LResNet100E-IR and I am getting the accuracy of 91%.
It is a request, if you can upload your cropped and aligned Youtube Face Dataset in Dataset Zoo, it would be a great help.

Thanks

**Comment by Po-Shin** [comment]
You can crop it by yourself actually, I changed the code in ytf.py a bit and the accuracy that I got from averaging 100 pics(if #pics>100 else #pics) is 97%. Just for you know:)

**Comment by zeeshanahmedkhan** [comment]
Hi Po-Shin
Sorry to say, can you please elaborate a little, I didnt get it
Thanks

**Comment by latstars** [comment]
@Po-Shin
Hello, I want to reproduce the result of ytf test-dataset, but I only get about 93% of accuracy. I align the ytf dataset(frame_images_DB) use the code src/align/align_insight.py, and run the test code src/eval/ytf.py. However, this can't promise a desirable result in YTF.
Would you mind sharing the details of ytf aligning and how should we change the code in ytf.py. (random 100 pics or the first 100 pics, use the mean feature or use the function main2() in ytf.py)
Thanks very much!

**Comment by dru9** [comment]
Hi. I also got almost same result with LResNet100E-IR(Dataset Zoo), 93.88% not 98.02%. I also align the ytf dataset(frame_images_DB) use the code src/align/align_insight.py, and run the test code src/eval/ytf.py. And I also apply limitation of 100 pics when collecting frame freatures within get_feature function in ytf.py. Is there anything I should do for reproducing 98.02%? Thank you!

**Comment by dru9** [comment]
@latstars 
I found solution. Use aligned_images_DB and splits_corrected.txt. You can find them in official YTF site.

**Comment by latstars** [comment]
@dru9 Thanks very much! I will try your suggestion in the near future.

**Comment by lbc402** [comment]
Hi @latstars, I used src/align/align_insight.py to handle aligned_image_DB as you said, and then used ytf.py and splits_corrected.txt to get only 92% acc. Are there any additional actions I have not performed. Thanks.
![image](https://user-images.githubusercontent.com/38685373/72433934-6af19380-37d5-11ea-859a-54d035d4f77b.png)

**Comment by latstars** [comment]
> Hi @latstars, I used src/align/align_insight.py to handle aligned_image_DB as you said, and then used ytf.py and splits_corrected.txt to get only 92% acc. Are there any additional actions I have not performed. Thanks.
> ![image](https://user-images.githubusercontent.com/38685373/72433934-6af19380-37d5-11ea-859a-54d035d4f77b.png)

Hi, sorry for the late reply, maybe you should try the suggestions from dru9.
1. align the official aligned_images_DB with src/align/align_insight.py 
2. download the splits_corrected.txt [splits_corrected.txt](http://www.cs.tau.ac.il/~wolf/ytfaces/splits_corrected.txt), replace the splits2.txt with splits_corrected.txt (maybe need some modifications).
3. retry the ytf.py script.
