### ISSUE TITLE
mobilefacenet分值分部交差大，如何缩小？

### ISSUE THREAD

**Issue by tomingliu** [deepinsight/insightface#642]
我在LFW上跑了一次测试，1：1和1：N的分值交差较大

1：1上限分值在98.8，集中分布在80到98.8之间
1：N（不同人）上限分值在88.2，集中分布在50到88.2

测试基数是3006人，从结果来看，80到88.2为交差严重的分值，也就是说，如果以3006为基数做1：N比对情况，为达到不误识别，需要将预值至少设为88.2，如果从88.2来算，通过率只有(3006-1079)/3006=64.105123087159015302727877578177%

[人脸识别算法测试报告.xlsx](https://github.com/deepinsight/insightface/files/3110336/default.xlsx)

**Comment by tomingliu** [comment]
没有人关注到这个问题不？我换了model-r100-arcface-ms1m-refine-v2再次测试发现，不同人比对分值同样偏高
![match_wrong](https://user-images.githubusercontent.com/1046303/56705204-a083b780-6742-11e9-8e94-fcedb6b29c66.png)
目前我是用NCNN执行库来测试的

**Comment by nttstar** [comment]
输入有问题

**Comment by tomingliu** [comment]
Mat MTCNN::alignFace(float *feat_points, Mat &img_)
{
    assert(img_.rows > 20 && img_.cols > 20);

    Mat dst(256/*height*/, 256/*width*/, CV_8UC3);
    Mat tform = getTformMatrix(feat_points, 256.f/256);
    warpAffine(img_, dst, tform, dst.size(), INTER_CUBIC, BORDER_CONSTANT);
    // Model needs RGB format
    cvtColor(dst, dst, CV_BGR2RGB);
//    {
//        char buf[255];
//        sprintf(buf, "/sdcard/avatar-%lu.jpg", random());
//        cv::imwrite(buf, dst);
//    }
    return dst;
}

**Comment by jackchinor** [comment]
@nttstar 我测试也发现了，靠相似度区分同一个人和不同人的时候，是有重叠的，也就是，同一个人的相似度也可能很低，不同的人的相似度也可能很高。这样就无法获得理想的FRR和FAR结果。想问一下可以在哪些方面改进么？输入有问题是指什么？十分感谢！

**Comment by bleakie** [comment]
请问这个分值接近的问题如何解决的呢？

**Comment by tomingliu** [comment]
模型精度损失

**Comment by bleakie** [comment]
什么意思呢？就是可以在训练的时候调节哪些参数可以改善呢？

**Comment by bleakie** [comment]
> 模型精度损失

请教：模型精度损失的方法只能在得分阈值上下文章吧，在训练的时候有没有改善分值的方法呢？

**Comment by tomingliu** [comment]
我这里是转换后出现的损失，与转换工具有关，具体细节没有研究
