### ISSUE TITLE
Unable to download RetinaFace-R50 pretrained model from Baidu

### ISSUE THREAD

**Issue by vvicel77** [deepinsight/insightface#643]
Hi,
Is it possible to share RetinaFace-R50 somewhere else?

**Comment by jamessmith90** [comment]
+1 Unable to download Please share google drive link if possible.

**Comment by gmvidooly** [comment]
+1 Please share google drive link if possible.

**Comment by ashuezy** [comment]
@nttstar i have downloaded the model can i share the google drive link here ?

**Comment by nttstar** [comment]
@ashuezy Yes you can, and we will provide dropbox link later.

**Comment by jamessmith90** [comment]
https://drive.google.com/open?id=1nEkmQz3bGumI_pBc72AXMmIvcpK9BfxA

**Comment by vvicel77** [comment]
thanks!

**Comment by sanazkhalili** [comment]
> https://drive.google.com/open?id=1nEkmQz3bGumI_pBc72AXMmIvcpK9BfxA

Thanks.
