### ISSUE TITLE
Need Top1M_MidList.Name.tsv!

### ISSUE THREAD

**Issue by yunkchen** [deepinsight/insightface#647]
I can't find any dataset donwload link on [official website](https://www.microsoft.com/en-us/research/project/ms-celeb-1m-challenge-recognizing-one-million-celebrities-real-world/).     And the mapping file about celebrity names to images is which I need. Would anyone share me the file Top1M_MidList.Name.tsv. Sincerely hope for your useful reply.

**Comment by ivazhu** [comment]
Did you find this list?

**Comment by yunkchen** [comment]
> Did you find this list?
No；But this problem is covered by using Baidu person api.

**Comment by ivazhu** [comment]
> > Did you find this list?
> > No；But this problem is covered by using Baidu person api.

Oh, could you please tell more about Baidu person API. Is it available not from China?
I just need some list of top 100K-200K celebrities around the world.

Thanks

**Comment by yunkchen** [comment]
> > > Did you find this list?
> > > No；But this problem is covered by using Baidu person api.
> 
> Oh, could you please tell more about Baidu person API. Is it available not from China?
> I just need some list of top 100K-200K celebrities around the world.
> 
> Thanks

https://ai.baidu.com/tech/imagecensoring
