### ISSUE TITLE
OpenCV Error: Assertion failed (src.cols > 0 && src.rows > 0) in warpAffine, file 

### ISSUE THREAD

**Issue by MrWwei** [deepinsight/insightface#649]
I want to train asian dataset and follow #256  . When I run  python face2rec2.py /home/xxx/insightface/src/data/glint_data, I get the error.
multiprocessing not available, fall back to single threaded encoding
OpenCV Error: Assertion failed (src.cols > 0 && src.rows > 0) in warpAffine, file /io/opencv/modules/imgproc/src/imgwarp.cpp, line 5584
Traceback (most recent call last):
  File "face2rec2.py", line 253, in <module>
    image_encode(args, i, item, q_out)
  File "face2rec2.py", line 99, in image_encode
    img = face_preprocess.preprocess(img, bbox = item.bbox, landmark=item.landmark, image_size='%d,%d'%(args.image_h, args.image_w))
  File "../common/face_preprocess.py", line 106, in preprocess
    warped = cv2.warpAffine(img,M,(image_size[1],image_size[0]), borderValue = 0.0)
cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:5584: error: (-215) src.cols > 0 && src.rows > 0 in function warpAffine

**Comment by oopsodd** [comment]
did you check list-image matching?

**Comment by Xin-327** [comment]
I had the same problem, did you solve it?
