### ISSUE TITLE
ask for refined-MS1M dataset

### ISSUE THREAD

**Issue by jackchinor** [deepinsight/insightface#650]
can you give me a link of  the raw refined-MS1M dataset? my input size is larger than 112*112, and I want to align face using other method  and output a larger size of aligned face. Really appreciate.

**Comment by borisgribkov** [comment]
There are some "clear lists" here, try to search in Issues. Brute force method: download original MSCeleb (with the original resolution and non-cropped faces) and compare it with the existing dataset in Wiki. 
I'm a bit curious, what type of alignment method you want to use?

**Comment by jackchinor** [comment]
@borisgribkov  my input face size  is larger than 112 , so I have to make my own dataset. now, my training dataset using @nttstar 's  refined-MS1M, but my testing data using a private align method , I found the inconsistent align method make a big difference on the final inference result. So I want to make train and test phase the same align method.

**Comment by borisgribkov** [comment]
If I understand you correctly...  Initial MS-Celeb has larger than 112 face resolution and contains not aligned images, so I guess you need to download original MS-Celeb and remove "dirty" images. Two ways here: find clean list or process the original dataset according the images in MSCeleb dataset in Wiki here

**Comment by leolordwz** [comment]
> There are some "clear lists" here, try to search in Issues. Brute force method: download original MSCeleb (with the original resolution and non-cropped faces) and compare it with the existing dataset in Wiki.
> I'm a bit curious, what type of alignment method you want to use?

@borisgribkov I downloaded MS1M-IBUG dataset from Dataset Zoo, but cannot find an image list, which can be mapped to the original dataset. Do you have any ideas about finding such an image list?

**Comment by borisgribkov** [comment]
just compare IBUG dataset you downloaded with the original file by file

**Comment by belgraviton** [comment]
Discussion:
https://github.com/deepinsight/insightface/issues/19

There is list for MS1M-IBUG dataset on baidu and google drive

**Comment by flyduck** [comment]
@jackchinor hi，did you download the original MS1M data? could you share? thanks!
