### ISSUE TITLE
How to decide the optimal values of s and m if I want to use the arcface loss on other kinds of dataset?

### ISSUE THREAD

**Issue by hathawayxxh** [deepinsight/insightface#652]
I want to employ the arcface loss for a three-class classification task, but I don't know how to decide the values of the scale s and margin m. I want to know if there are any criteria to decide the values? And also, does anyone know how to draw the theta distribution like in Figure 4 in the Arcface paper. Thanks.

**Comment by INHTVD** [comment]
I want to konw  how to draw the theta distribution like in Figure 4 in the Arcface paper. Thanks.
