### ISSUE TITLE
Emore+DeepGlint Asia

### ISSUE THREAD

**Issue by mlourencoeb** [deepinsight/insightface#653]
Can someone clarify if both datasets can be blindly merge using dataset_merge.oy, i.e. by setting model to None?

Cheers

**Comment by xsacha** [comment]
They both use ms1m so there will be overlap.

**Comment by mlourencoeb** [comment]
@xsacha I don't mean merge msra part but only asian set with emore. Is asian subset also based on ms1m, or completely separate and can be blindly merged?

Thanks

**Comment by mlourencoeb** [comment]
Dataset cannot be merged blindly. There is considerable amount of overlap.
