### ISSUE TITLE
ImportError: No module named anchors

### ISSUE THREAD

**Issue by kk52099** [deepinsight/insightface#655]
when i trained the retinaface ,the question occurred

**Comment by YangYangya** [comment]
hi, the question occurred as well,how can i deal with it

**Comment by EtheneXiang** [comment]
me too, the question occurred as well, how to deal? @kk52099 thx

**Comment by kk52099** [comment]
change the "anchors" version according to the error prompt

**Comment by EtheneXiang** [comment]
> change the "anchors" version according to the error prompt

how to??i no not know what you mean

**Comment by zerollzeng** [comment]
the question occurred to me as well, does anyone know how to solve it? thx

**Comment by nuanxinqing** [comment]
have u solved this problem? how?It occured to me also.

**Comment by nuanxinqing** [comment]
I find the problem. because I skipped the step '3.Type make to build cxx tools.' In the install part. After done make,the error disappeared.
