### ISSUE TITLE
ValueError: there are multiple outputs with name "_plus0_output"

### ISSUE THREAD

**Issue by kk52099** [deepinsight/insightface#656]
when i used "retinaface" to train the widerface dataset,the problem occurred,how to solve it?

**Comment by nttstar** [comment]
I never met this problem, what is your training configuration?

**Comment by kk52099** [comment]
I used the provided configuration file "rcnn/sampleconfigure.py", only moddifyed the network to resnet-50, and used the provied pre-training model "retinaface-R50.zip" .

**Comment by kk52099** [comment]
I used the provided configuration file "rcnn/sample_config.py", only moddifyed the network to resnet-50, and used the provied pre-training model "retinaface-R50.zip" .

**Comment by kk52099** [comment]
I used the provided configuration file "rcnn/sampleconfigure.py", only moddifyed the network to resnet-50, and used the provied pre-training model "retinaface-R50.zip" . when the program executes to the line of code "sym = eval(‘get_’ + args.network + '_train')(sym)" , at line 93 of  the file "train.py"

**Comment by nttstar** [comment]
Please use the imagenet pretrained model, I already provided it.

**Comment by kk52099** [comment]
I‘ve already used it, The problem is the same,it happens on line 90 of the file"train.py", ValueError: there are multiple outputs with name "_plus0_output", Do I  need to  change the model file?

**Comment by nttstar** [comment]
Not retinaface-R50, use the imagenet resnet-50 as training pretrained model

**Comment by kk52099** [comment]
I‘ve already used the imagenet resnet-50, The problem is the same,

**Comment by kk52099** [comment]
the problem has been solved,when i used the imagenet resnet-50,   i added "print(sym.get_internals())" in the file "train.py".  but if i don't use the pretrained model , can I  train the model properly？

**Comment by zoezhu** [comment]
I just met the same problem and already solved it.
In the latest version of code by now, in file 'symbol_common.py' there is a line 'stride2layer[stride] = all_layers[name]' around line 207, change it to 'stride2layer[stride] = all_layers[i]' works fine for me.

**Comment by mifan0208** [comment]
Have you solved it? This problem occurs after the trained model of the pre-trained model is invoked

**Comment by faderani** [comment]
@nttstar So how to resume from a checkpoint? Every time the error in the title shows up. This has been an old common problem which is not addressed yet. Would appreciate your help.

**Comment by MariusIlie14** [comment]
> Please use the imagenet pretrained model, I already provided it.

which is the imagenet pretrained model ? where can it be found ?
