### ISSUE TITLE
Retina Face with ResNet50 on gpu

### ISSUE THREAD

**Issue by marcomiglionico94** [deepinsight/insightface#657]
I was trying to run RetinaFace using ResNet50 as backbone. I am using CUDA 10.0 so I installed mxnet-cu100 using `pip install mxnet-cu100`. The code is working the only probelm is that it seems the GPU is not being used. I tried to measure the time on GPU and CPU and it is the same. Did I miss something?
I am using Python3.6 and CUDA 10.0.

**Comment by nttstar** [comment]
training or testing?

**Comment by marcomiglionico94** [comment]
Ok nothing, I already solved it. It was a mistake of my code. I was using the wrong GPU id. It is working on GPU right now.
Thanks

**Comment by MyraBaba** [comment]
@nttstar @marcomiglionico94 

have you any chance to test on the Jetson TX2 ?  I tried and its not working just freezing ? is it because of the gpu architecture?

**Comment by MyraBaba** [comment]
@marcomiglionico94 

Hi I am testing the retinanet on my 2080Txi and feeding 2Mp video . Gpu utilization only %12 and I have get 6 fps *

how can I use full power of the gpu ? is this normal or am I missing something ?

**Comment by ashuezy** [comment]
@MyraBaba 
RetinaFace is not suppose to be used on live video.

**Comment by MyraBaba** [comment]
@ashuezy  Than What is the usage purpose ?  only for pictures ?

**Comment by marcomiglionico94** [comment]
@ashuezy @MyraBaba I was able to run it on GPU in real time using an Nvidia Titan V

**Comment by MyraBaba** [comment]
@marcomiglionico94 Hi,

What is the resolution and what is the GPU usgae ?

**Comment by dexception** [comment]
@marcomiglionico94 
On Nvidia Titan V i can run 10 cameras handle 10 cameras in real time with same accuracy.

**Comment by xxcheng0708** [comment]
MXNET_CUDNN_AUTOTUNE_DEFAULT = 0 useless when run ResNet50 model, Anybody come across that ?

**Comment by MyraBaba** [comment]
@dexception  what is the resolution ? any specific configuration ?

**Comment by dexception** [comment]
@MyraBaba 
Again as @nttstar pointed about AP scores are for competitions.
Please check the accuracy in real world. 

Resolution is 2K. 
Model would be SqueezeNET Light SSD.

**Comment by xiakejiang** [comment]
> training or testing?

can you explain my question [https://github.com/deepinsight/insightface/issues/889](url)
thank you very much
