### ISSUE TITLE
1:1 verification on FRVT questions

### ISSUE THREAD

**Issue by cassie101** [deepinsight/insightface#659]
Hi @nttstar @jiankangdeng, very great work on 1:1 verification! and thanks for sharing your solution on face recognition model. 
If you don't mind, is it possible to share with us which face detector did you use? Is it based on MTCNN or RetinaFace (resnet based, mobilenet based) or others? thank you very much!

> 2019.04.04: Arcface achieved state-of-the-art performance (5/109) on the NIST Face Recognition Vendor Test (FRVT) (1:1 verification) report (name: Imperial-000). Our solution is based on [MS1MV2+DeepGlintAsian, ResNet100, ArcFace loss].

**Comment by xianyujie** [comment]
@cassie101 Hi, the 1:1 verification on FRVT has some requirements as follows:
```
Implementations must run in single-threaded mode, because NIST will parallelize the test 
by dividing the workload across many cores and many machines. Implementations must ensure 
that there are no issues with their software being parallelized via the fork() function. 
Developers should take caution with checking threading when using third-party frameworks 
(e.g., TensorFlow, MXNet, etc.).
```
How to run mxnet in single-thread mode?
