### ISSUE TITLE
ms1m清洗数据集图片文件名

### ISSUE THREAD

**Issue by HansonSun** [deepinsight/insightface#66]
您好，
请问下，清洗后的数据集的文件名怎么和原始的图片文件名对应上
清洗后的文件名格式如下：
./m.0933t2/0.jpg
./m.0933t2/10.jpg
./m.0933t2/12.jpg
原始的文件名是下面的格式
m.0109kg/14-FaceId-0.jpg
m.0109kg/58-FaceId-0.jpg
m.010bk0/7-FaceId-0.jpg

谢谢

**Comment by nttstar** [comment]
#19
