### ISSUE TITLE
src/train.py和recognition/train.py里面arcface的差别

### ISSUE THREAD

**Issue by fengsky401** [deepinsight/insightface#661]
src/train.py里面在[0,pi]之间使用的是arcface，在[0,-pi]使用的是cosface
recognition/train.py里面[-pi,pi]使用的都是arcface
请问这样差异的初衷是什么，哪一种效果更好呢

**Comment by konioyxgq** [comment]
我也有这样的问题，你是怎么理解的，你现在用的是src/train.py  还是recognition/train.py啊？
