### ISSUE TITLE
为什么使用的vgg2项目中的list

### ISSUE THREAD

**Issue by zclion** [deepinsight/insightface#665]
1. IJB-C原始数据中，1:1 verification中match.txt是template-based，代码中应该是对每个template的features进行了np.mean，请问为什么使用的vgg2项目中的list而不是使用的IJB数据集中自带的？
2. vgg2项目中生成filelist的原理是什么呢？

不胜感激

**Comment by shiyuanyin** [comment]
> 
> 
>     1. IJB-C原始数据中，1:1 verification中match.txt是template-based，代码中应该是对每个template的features进行了np.mean，请问为什么使用的vgg2项目中的list而不是使用的IJB数据集中自带的？
> 
>     2. vgg2项目中生成filelist的原理是什么呢？
> 
> 
> 不胜感激

@zclion 
 ijbc_face_tid_mid.txt and ijbc_template_pair_label.txt, 

分别是 图片名字 和id编号，但是我不理解这两个文件如何生成，所以我也不是很理解  IJBC评估，Step3: Get Template Features，的一个实现过程？，请问你现在了解txt文件生成的过程了吗

**Comment by darshangera** [comment]
can you please provide ijbc_face_tid_mid.txt and ijbc_template_pair_label.txt files?
