### ISSUE TITLE
megaface上测试一些问题

### ISSUE THREAD

**Issue by heyanglearning** [deepinsight/insightface#667]
进入Evaluation/Megaface根据README下载并解压缩到./data中。
修改了model路径，运行run.sh。
开始生成特征并remove_noise。
然后在运行run_experience.py时候，卡在0.99800然后程序就不动了，有人遇见过吗。

**Comment by fucker007** [comment]
> 进入Evaluation/Megaface根据README下载并解压缩到./data中。
> 修改了model路径，运行run.sh。
> 开始生成特征并remove_noise。
> 然后在运行run_experience.py时候，卡在0.99800然后程序就不动了，有人遇见过吗。

Hi, 我用insightface上的resnet100_arcface 模型，在megaface上測試，其rank 1只有0.05 ， 請問這是什麼原因導致的呢？ 你知道嗎？
