### ISSUE TITLE
RetinaFace c++

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#671]
is there any c++ implementation of the RetinaFace ?

**Comment by hanson-young** [comment]
There is a C++ implementation by caffe.I just saw it.
[https://github.com/Charrin/RetinaFace-Cpp](https://github.com/Charrin/RetinaFace-Cpp) @MyraBaba

**Comment by MyraBaba** [comment]
I looked , promising. but there is no MakeFile or cmake so couldt compile so far.
