### ISSUE TITLE
RetinaFace Performance

### ISSUE THREAD

**Issue by deimsdeutsch** [deepinsight/insightface#673]
I just tried the latest retinaface on video on my GTX 1060

nvidia-smi -i 0 --query-gpu=index,timestamp,utilization.gpu,power.draw,temperature.gpu --format=csv -l 1

0, 2019/05/11 18:23:01.597, 46 %, 48.72 W, 73
0, 2019/05/11 18:23:02.599, 41 %, 48.10 W, 73
0, 2019/05/11 18:23:03.601, 52 %, 54.85 W, 73
0, 2019/05/11 18:23:04.603, 40 %, 45.49 W, 73
0, 2019/05/11 18:23:05.606, 51 %, 49.02 W, 73
0, 2019/05/11 18:23:06.611, 39 %, 33.45 W, 73
0, 2019/05/11 18:23:07.614, 52 %, 68.18 W, 73
0, 2019/05/11 18:23:08.620, 39 %, 32.07 W, 73
0, 2019/05/11 18:23:09.623, 39 %, 52.84 W, 73
0, 2019/05/11 18:23:10.634, 45 %, 53.29 W, 73
0, 2019/05/11 18:23:11.636, 41 %, 42.51 W, 73
0, 2019/05/11 18:23:12.638, 40 %, 59.88 W, 73
0, 2019/05/11 18:23:13.640, 50 %, 34.41 W, 73
0, 2019/05/11 18:23:14.642, 40 %, 57.18 W, 73
0, 2019/05/11 18:23:15.645, 46 %, 35.81 W, 73
0, 2019/05/11 18:23:16.649, 41 %, 84.70 W, 73
0, 2019/05/11 18:23:17.658, 40 %, 34.26 W, 73
0, 2019/05/11 18:23:18.660, 41 %, 52.11 W, 73
0, 2019/05/11 18:23:19.663, 38 %, 33.10 W, 73
0, 2019/05/11 18:23:20.665, 48 %, 44.43 W, 73

nvidia-smi
|    0     12286      C   python3                                      623MiB |

It seems to be taking less memory but taking lot of cuda cores.

Thanks.

**Comment by dexception** [comment]
@nttstar Can we convert this to TVM ?
