### ISSUE TITLE
What is theconfiguration of the test.py  to get maximum faces from big Selfie  ?

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#674]
Hi,

I read in the paper that we can deetct 900 faces from the mentioned selfie ? Wha is the configuration for the test.pf for this ? I can get only 515 faces ?

**Comment by jiashu-zhu** [comment]
Have you solved this problems?

**Comment by MyraBaba** [comment]
not yet

**Comment by MyraBaba** [comment]
I wonder is there c++ implementation og the retinaface ?

**Comment by jiashu-zhu** [comment]
> I wonder is there c++ implementation og the retinaface ?

I use resnet-152, and get 91.7% mAP on widerface hard set, but I can get only 606 faces on the 'world largest selfie'
what resolution is your 'largest selfie'? mine is 898*1600,

**Comment by nttstar** [comment]
Use multi scale test

**Comment by zhukkang** [comment]
@jiashu-zhu  @nttstar  as i trained with resnet152, after training to test ,
got error with 
    proposals = proposals[order, :]
IndexError: index 768 is out of bounds for axis 0 with size 768

can you help to give more detail about use of resnet152  (about config and test)
thanks ~
