### ISSUE TITLE
if use more landmark to align image?

### ISSUE THREAD

**Issue by flyduck** [deepinsight/insightface#676]
hi, first very thank you for this great work!
I have some questiones about the alignment process in the data preprocess:
(1)what is the matrix 'src 'in the preprocess function in your code face_preprocess.py? How to get this matrix?:
  if landmark is not None:
    assert len(image_size)==2
    src = np.array([
      [30.2946, 51.6963],
      [65.5318, 51.5014],
      [48.0252, 71.7366],
      [33.5493, 92.3655],
      [62.7299, 92.2041] ], dtype=np.float32 )
    if image_size[1]==112:
      src[:,0] += 8.0
    dst = landmark.astype(np.float32)
(2)did you try some other alignment algorithm? if the landmark is more than 5, I say for example 68 or more, how to align the images?

thanks very much!

**Comment by Walstruzz** [comment]
[Sphereface](https://github.com/wy1iu/sphereface/blob/master/preprocess/code/face_align_demo.m) has the same matrix `src`.
