### ISSUE TITLE
Inferencing with cpp via TVM runtime.

### ISSUE THREAD

**Issue by notebookdata** [deepinsight/insightface#677]
Hi, @nttstar @jiankangdeng using your [tutorial](https://github.com/deepinsight/insightface/wiki/Tutorial:-Deploy-Face-Recognition-Model-via-TVM#inferencing-with-cpp-via-tvm-runtime) I am able inference tvm runtime for llvm I am facing issue while Inferencing with Cuda and OpenCL.

            DLTensor* input;
            constexpr int dtype_code = kDLFloat;
            constexpr int dtype_bits = 32;
            constexpr int dtype_lanes = 1;
            constexpr int device_type = kDLGPU;
            constexpr int device_id = 0;
            constexpr int in_ndim = 4;
            const int64_t in_shape[in_ndim] = {1, 3, 112, 112};
            TVMArrayAlloc(in_shape, in_ndim, dtype_code, dtype_bits, dtype_lanes, device_type, device_id, &input);//

here when I try to access or do memset(input->data, 0, img_size); i am getting segmentation fault.

**Comment by szad670401** [comment]
You need to compiled tvm runtime with cuda .Here is an example.https://github.com/szad670401/tvm_benchmark_cpp

**Comment by myproject24** [comment]
Hi, @szad670401 I hope for dynamic deploy we don't need to compile with tvm runtime, for dynamic deploy we link libtvm_runtime.so while compiling.

**Comment by ashuezy** [comment]
@szad670401 
TVM is working fine.. but can i do auto tune ?

**Comment by xizi** [comment]
@szad670401 hi,  i run the cpp_benchmark.cpp meet 
tvm/apps/howto_deploy/../../src/runtime/registry.cc:79: Check failed: override: Global PackedFunc __tvm_set_device is already registered error. how can i solve it?
