### ISSUE TITLE
Windows Support For RetinaFace

### ISSUE THREAD

**Issue by Neltherion** [deepinsight/insightface#679]
Would you please consider supporting Windows for RetinaFace?

The `bbox` and other cython related codes are written to make use of Linux's GCC to compile and without Linux we can't test the code on Windows platforms.

Thanks for the great support.

**Comment by nttstar** [comment]
You can select the python implementation, instead of cxx.

**Comment by Neltherion** [comment]
@nttstar Thanks for the followup. By "python implementation" you mean `bbox_overlaps_py`? even if I change `bbox_overlaps` to `bbox_overlaps_py` there's another problem with `anchors_cython` which doesn't have a python implementation.

**Comment by Ancho5515** [comment]
@Neltherion you can rewrite the .pyx files under ./rcnn/cython into .py files, and it will be very slow on web_cam demo

**Comment by Neltherion** [comment]
@Ancho5515 Thanks, but as you said, that would be a really bad approach. I'm still not familiar enough with Cython but would be really be that hard to change the code to also work on Windows too?

**Comment by miwaliu** [comment]
@Neltherion https://github.com/miwaliu/Retinaface for windows

**Comment by Neltherion** [comment]
@miwaliu Thanks... Checking it...

**Comment by Neltherion** [comment]
@miwaliu If I'm not mistaken, you're using the Python Wrappers instead of the Cython code... Am I right?

**Comment by loscheris** [comment]
Instead of using python implementation, you can try to compile \*.pyx files into windows binaries (\*.pyd) :

1. Replace `setup.py` in `RetinaFace/rcnn/cython` dir to:

```python
# setup.py
from distutils.core import setup, Extension
from Cython.Build import cythonize
import numpy

setup(
    ext_modules=cythonize(["bbox.pyx", "anchors.pyx", "cpu_nms.pyx"]),
    include_dirs=[numpy.get_include()]
)
```

2.  Use cmd to run `python setup.py build_ext --inplace` in `RetinaFace/rcnn/cython` dir

3.  Copy the three windows binaries (\*.pyd) generated in `RetinaFace/rcnn/cython/rcnn/cpython` to `RetinaFace/rcnn/cython`

4. Run the test code : )

**Comment by github-luffy** [comment]
@loscheris ，just do step by step as you do，but still wrong. I don't know WHY.

**Comment by github-luffy** [comment]
@loscheris，just do step by step as you do，I got ￼anchors.c, anchors.cp36-win_amd64.pyd and anchors.pyx, and bbox.c, bbox.cp36-win_amd64.pyd and bbox.pyx, and cpu_nms.c, cpu_nms.cp36-win_amd64.pyd and cpu_nms.pyx.  ￼but still wrong. I don't know WHY.

**Comment by 791136190** [comment]
@github-luffy you can change the cpu_nms.pyx line 25 to :
cdef np.ndarray[np.int_t, ndim=1] order = scores.argsort()[::-1].astype('int32')

**Comment by zhjikoshlizhzc** [comment]
> 1. python setup.py build_ext --inplace
Hi，when I run python setup.py build_ext --inplace, something went wrong.
(mxnet36) D:\RetinaFace\rcnn\cython>python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    class custom_build_ext(build_ext):
NameError: name 'build_ext' is not defined

**Comment by zhjikoshlizhzc** [comment]
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    faces, landmarks = detector.detect(img, thresh, scales=scales, do_flip=flip)
  File "D:\RetinaFace\retinaface.py", line 441, in detect
    keep = self.nms(pre_det)
  File "D:\RetinaFace\rcnn\processing\nms.py", line 17, in _nms
    return cpu_nms(dets, thresh)
  File "cpu_nms.pyx", line 25, in rcnn.cython.cpu_nms.cpu_nms
ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'

**Comment by zhjikoshlizhzc** [comment]
> @791136190
> I have changed the cpu_nms.pyx line 25 to : cdef np.ndarray[np.int_t, ndim=1] order = scores.argsort()[::-1].astype('int32')
> But still wrong. Please help me!
> Traceback (most recent call last):
> File "test.py", line 38, in
> faces, landmarks = detector.detect(img, thresh, scales=scales, do_flip=flip)
> File "D:\RetinaFace\retinaface.py", line 441, in detect
> keep = self.nms(pre_det)
> File "D:\RetinaFace\rcnn\processing\nms.py", line 17, in _nms
> return cpu_nms(dets, thresh)
> File "cpu_nms.pyx", line 25, in rcnn.cython.cpu_nms.cpu_nms
> ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'

I have solved the problem, I need to rerun the code `python setup.py build_ext --inplace` in RetinaFace/rcnn/cython dir

**Comment by mlourencoeb** [comment]
Why don't you give a try to pip install insightface?

It has a pure python implementation and it is pretty efficient.

**Comment by robosina** [comment]
In my case I have run the below code to cythonize python files:

```
setup(
    cythonize(["bbox.pyx", "anchors.pyx", "cpu_nms.pyx"]),
    include_dirs=[numpy.get_include()]
)
```

After that for creating `pyd` files (don't forget `--inplace` argument) I comment the above code and then re-run code by the below setup( I know this is not best way to resolve the issue but It's a simple workaround)

```
setup(
    ext_modules=[Extension('bbox', ['bbox.c']),
                 Extension('anchors', ['anchors.c']),
                 Extension('cpu_nms', ['cpu_nms.c'])],
    include_dirs=[numpy.get_include()]
)

```
I use `msvc` compiler.

**Comment by DanWaffle** [comment]
> 1. python setup.py build_ext --inplace

doing this results in `error: Unable to find vcvarsall.bat` for me

**Comment by TMaysGGS** [comment]
> Why don't you give a try to pip install insightface?
> 
> It has a pure python implementation and it is pretty efficient.

Thanks, I think your solution is the most straightforward when I just want to use the face detection function with pretrained models.

**Comment by maycuatroi** [comment]
I fixed this issues with change compile method. Hope it work for you https://github.com/deepinsight/insightface/pull/1032
![image](https://user-images.githubusercontent.com/5876946/118957954-29ee2e00-b98b-11eb-8044-5006417dd7a3.png)
