### ISSUE TITLE
How Utilise full GPU power for RetinaFace ?

### ISSUE THREAD

**Issue by MyraBaba** [deepinsight/insightface#680]
Hi,

I ran the test.py with 2Mp video on the i9 & 2080Ti Gpu and got only 16 fps.

On the other hand Gpu only utilised %10 .

How we can push the full limit for RetinaFace on gpu ?

any idea ? 

best

**Comment by wanjinchang** [comment]
I also meet your problem.I have some doubt about RetinaFace inference time,maybe the method I tested was wrong??!!

**Comment by syedmustafa54** [comment]
same question did any one found out how to use 80% of it
