### ISSUE TITLE
create my own .bin by pairs.txt 

### ISSUE THREAD

**Issue by MrWwei** [deepinsight/insightface#682]
I have prepared my pairs.txt.  like:
name                                                       picID1    picID2
0a5611aa-f909-451d-ad37-bcfe0aaadf0d	7	7
0a5611aa-f909-451d-ad37-bcfe0aaadf0d	9	2
name1                                                        picID1     name2                                                   picID2
0ab60387-a2bf-4ce1-878b-c77f671cdf56	113	0a226558-f0f4-406c-9d7f-1d7fc6aa0ef7	7     3
0a39a7cf-84a3-4bd3-84cf-83154dcbf658	1	0a422ae9-8df6-4edc-bb67-a7c9ff5d9ac9	0
0adf3bd8-f17b-4516-9477-7494f6845fb4	11	0a422ae9-8df6-4edc-bb67-a7c9ff5d9ac9	1

Is this pairs.txt format correct?

And then:
I use lfw2pack.py to create .bin file. 

But when I train the netword, i get this error:
Traceback (most recent call last):
  File "train_softmax.py", line 601, in <module>
    main()
  File "train_softmax.py", line 598, in main
    train_net(args)
  File "train_softmax.py", line 592, in train_net
    epoch_end_callback = epoch_cb )
  File "/home/heisai/.local/lib/python2.7/site-packages/mxnet/module/base_module.py", line 560, in fit
    callback(batch_end_params)
  File "train_softmax.py", line 530, in _batch_callback
    acc_list = ver_test(mbatch)
  File "train_softmax.py", line 489, in ver_test
    acc1, std1, acc2, std2, xnorm, embeddings_list = verification.test(ver_list[i], model, args.batch_size, 10, None, None)
  File "eval/verification.py", line 282, in test
    _, _, accuracy, val, val_std, far = evaluate(embeddings, issame_list, nrof_folds=nfolds)
  File "eval/verification.py", line 181, in evaluate
    np.asarray(actual_issame), 1e-3, nrof_folds=nrof_folds)
  File "eval/verification.py", line 152, in calculate_val
    val[fold_idx], far[fold_idx] = calculate_val_far(threshold, dist[test_set], actual_issame[test_set])
  **File "eval/verification.py", line 169, in calculate_val_far
    far = float(false_accept) / float(n_diff)
ZeroDivisionError: float division by zero**

**Comment by nttstar** [comment]
https://github.com/deepinsight/insightface/blob/master/recognition/data/build_eval_pack.py

**Comment by nttstar** [comment]
Please check the above utility and one example pairs_label.txt was given for LFW dataset.

**Comment by MrWwei** [comment]
@nttstar thx！It works.

**Comment by YokkaBear** [comment]
> @nttstar thx！It works.

Sorry but I met the same problem, and I'll appreciate it if you could share with me how you fix the 'ZeroDIvisionError' error through the writer's instruction? Since after I have generated the same format of 'pairs_label.txt', I still receive this error. Thank you!
