### ISSUE TITLE
RetinaFace - How to determine what `scales` values are proper for our image size?

### ISSUE THREAD

**Issue by Neltherion** [deepinsight/insightface#684]
Hi @nttstar 

Could you please elaborate on the values of `scales` when testing RetinaFace?

For example if we have (640,640) images as input, should we make `scales = [640,640]` or should we leave it at `scales = [1024, 1980]` ?

Is there any documentation on how `scales` works? I read the paper but couldn't pinpoint how to exactly use `scales` in the test code.

Thanks as always for your great support.

**Comment by baishiruyue** [comment]
I have the same question, have you solve it?

**Comment by yjhuasheng** [comment]
Have you solve it? I have the same question.

**Comment by yjhuasheng** [comment]
Have you solve it? I have the same question, and the boxes are offset!!!!!!!

**Comment by MyraBaba** [comment]
@nttstar  any answer ?

**Comment by marcobarnobi** [comment]
same question. Could you please explain? 

The model is loaded in retinaface.py in __init__, (around line 158):
`   image_size = (640, 640)`
    `self.model = mx.mod.Module(symbol=sym, context=self.ctx, label_names = None)
    elf.model.bind(data_shapes=[('data', (1, 3, image_size[0], image_size[1]))], for_training=False)
    self.model.set_params(arg_params, aux_params)`

So I expect it to only get inputs of shape [1, 3, 640, 640]. Am I wrong? 

However...  then detect() in  retinaface.py takes the scale (which is defined in test.py) as input and does some strange operations, which lead to an input size that could very well be different than [1, 3 ,640, 640]. How can this work? 

How should we choose scales = [..., ...] in test.py?

**Comment by jinpeijie217** [comment]
same problem. And if you use the different predefined scales, the detection result could be different. My detector can detect one face with the set of [512,990], but it doesn't work with the set of [1024,1980]. This is quite unpredictable.
