### ISSUE TITLE
Cannot find Dense Regression Loss of RetinaFace.

### ISSUE THREAD

**Issue by linVdcd** [deepinsight/insightface#687]
Thank you for such wonderful work. I’m reading the code now. But didn't find the Dense Regression Loss. Do i miss something? Please help me.

**Comment by jiankangdeng** [comment]
Thanks for your interest in our work. We delay the release time of our best model (including the dense branch) to take part in the wider challenge. http://wider-challenge.org/2019.html

To make our own challenge https://ibug.doc.ic.ac.uk/resources/lightweight-face-recognition-challenge-workshop/ reproducible from the system view, we have released the 5pts annotation and training code.
Welcome to participate in the LFR 2019 challenge. ^_^

**Comment by XinjieInformatik** [comment]
@jiankangdeng Thanks for your great work, I'm also very interested in your Mesh Decoder part, when you release the code, please kindly tell us. Thanks!

**Comment by TangShengqin** [comment]
期待大佬早日放出 Mesh Decoder part

**Comment by borarak** [comment]
Any timelines on this? Thanks!

**Comment by alexkoltun** [comment]
Any news regarding this?

**Comment by yuangan** [comment]
Any updates?
