### ISSUE TITLE
Dose anyone have ever tried to train a face recognition model using face images which are not aligned？ 

### ISSUE THREAD

**Issue by meanmee** [deepinsight/insightface#688]

**Comment by meanmee** [comment]
From my experiment results, The differences of face recognition performance among using different face alignment method are quite huge. So It's critical to deploy a so sophisticated system. I wonder if we could remove the stage of face alignment in such a system to simplify our face recognition works.

**Comment by borisgribkov** [comment]
You could remove 5-points alignment method and use something else, check this https://arxiv.org/abs/1701.07174 for example. But I have never seen that recognition nets works better without alignment at all.

**Comment by zhangjinhong17** [comment]
I tested the accuracy in megaface dataset, without alignment, This pre-trained model. the accuracy drop off much.

Thanks
Jinhong

**Comment by borisgribkov** [comment]
That's right, to test it you should train your model with not-aligned images as well.

**Comment by xsacha** [comment]
Probably what you want is a network that aligns the face and then generates the feature.
Obviously the network needs to have the face aligned to compare like-for-like.
Benefits if having an integrated alignment are that if the alignment method changes or differs slightly it will not ruin accuracy.

**Comment by borisgribkov** [comment]
@xsacha spatial transformer, projective or something else?

**Comment by vizakshat** [comment]
David Sandberg tried this with his repo facenet. Results were not as good as with aligned face images. 
Not aligning may require bigger datasets to generalize.
