### ISSUE TITLE
where is the face_preprocess module? 

### ISSUE THREAD

**Issue by alphinside** [deepinsight/insightface#69]
Hi guys, it's a very impressive work you've done. 
I want to reproduce your result and found that the face_preprocess and face_image module is missing. Can you share them? Thank you

**Comment by terencezl** [comment]
Should be in `https://github.com/deepinsight/insightface/tree/master/src/common`. `sys.path` was altered before import.

**Comment by christer1114** [comment]
Hi, I am also encountering the same issue. Was the the src folder deleted? I couldn't find it. Was it altered when the repo was refined?

**Comment by kormalev** [comment]
The way I see it, `face_preprocess.preprocess`  does essentially the same thing as `face_align.norm_crop'.

**Comment by kormalev** [comment]
You can see the implementation here: https://github.com/deepinsight/insightface/blob/9fc3cc9c0bd18dbd7255c9eb855a2dd9e4f9934b/src/common/face_preprocess.py

**Comment by nttstar** [comment]
https://github.com/deepinsight/insightface/blob/master/deploy/face_model.py
https://github.com/deepinsight/insightface/blob/master/python-package/insightface/utils/face_align.py
