### ISSUE TITLE
retinaface inference time

### ISSUE THREAD

**Issue by yja1** [deepinsight/insightface#690]
TITAN X
mobilenet0.25
I run test.py and calc faces, landmarks = detector.detect(img, thresh, scales=scales, do_flip=flip) time

img:640*640  26ms
img:1920*1080  126ms

is this right?
in paper 1920*1080 time is 6.1ms!!!

**Comment by Neltherion** [comment]
@yja1  Why did you close the issue? did you solve the problem?

**Comment by yja1** [comment]
detector.detect  contain imread time and resize time 
so I m thinking maybe should calc time of self.model.forward(db, is_train=False)

but the self.model.forward time always 0.3 ms

**Comment by Neltherion** [comment]
@yja1 That's it. The Model at least takes 0.3 ms to forward the data (which is pretty short), all the rest of processing which contains processing anchors and detecting landmarks takes more time than the model forward itself.

@nttstar Do you think there is a way to decreases the anchor and landmarks processing time (whatever that happens after `model.forward`)? I did some benchmarks and the CPU NMS is fast enough but the processing of `proposals`, `scores` and `landmarks` after it is a bit slow, especially if you want to process the input data in batches (and not one image per `detect` call).

**Comment by yxchng** [comment]
@Neltherion Have you found a solution to process in batch?
