### ISSUE TITLE
RetinaFace re-implement in tensorflow or caffe?

### ISSUE THREAD

**Issue by BrownOfSummer** [deepinsight/insightface#693]
Not familiar with mxnet， anyone plan to implement retinaface in tensorflow or caffe. Hope to work together.

**Comment by AnaRhisT94** [comment]
Also would love to know if there can be a re-implementation of it in TensorFlow.

**Comment by meitianjinbu** [comment]
I'm in.

AnaRhisT <notifications@github.com> 于2019年5月29日周三 下午9:22写道：

**Comment by sanrahul** [comment]
https://github.com/Fei-Wang/insightface
