### ISSUE TITLE
Running performance tests to find the best convolution algorithm, this can take a while

### ISSUE THREAD

**Issue by meixitu** [deepinsight/insightface#694]
Hi ,
Thanks for your wonderful work.
I tried to use your pre-trained Retinaface-R50 model to run inference.

When I run inference for megaface dataset, it always has below infomation:
Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)

This test slow down the inference so much, I set the MXNET_CUDNN_AUTOTUNE_DEFAULT=0 in environment, but it is not disabled.

I use mxnet-cu10.0 1.3.0 version, Is anyone can help me?

**Comment by bityigoss** [comment]
in the R50-symbol.json file, reset param cudnn_tune's value with "None" would help. the default value of cudnn_tune is limited_workspace.
[mxnet reference](http://mxnet.incubator.apache.org/versions/master/api/python/symbol/symbol.html?highlight=cudnn_tune)

**Comment by zzh928253398** [comment]
i reset param cudnn_tune's value with "off", it works.

cudnn_tune: enable this option leads to higher startup time but may give faster speed. Options are
    off: no tuning
    limited_workspace:run test and pick the fastest algorithm that doesn’t exceed workspace limit.
    fastest: pick the fastest algorithm and ignore workspace limit.
    None (default): the behavior is determined by environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT. 
    0 for off, 
    1 for limited workspace (default), 
    2 for fastest.

**Comment by pasa13142** [comment]
Does accuracy change with these values ?

**Comment by Programmerwyl** [comment]
I set 
```
os.environ["MXNET_CUDNN_AUTOTUNE_DEFAULT"] = "2"
```
but it does not work,how to set it 
thanks

**Comment by KEVIN666666666** [comment]
> I set
> 
> ```
> os.environ["MXNET_CUDNN_AUTOTUNE_DEFAULT"] = "2"
> ```
> 
> but it does not work,how to set it
> thanks

os.environ['MXNET_CUDNN_AUTOTUNE_DEFAULT'] = '0'

This works for me.

**Comment by qzylalala** [comment]
> in the R50-symbol.json file, reset param cudnn_tune's value with "None" would help. the default value of cudnn_tune is limited_workspace.
> [mxnet reference](http://mxnet.incubator.apache.org/versions/master/api/python/symbol/symbol.html?highlight=cudnn_tune)

Thanks,   I follow your suggestion, it works for me.  howerver the accuracy declines so much on my test

**Comment by j-t-fraser** [comment]
The following steps combined removed all autotunes for me. Neither of the two steps worked alone:
- Replacing the "limited_workspace" with "off" in the R50-symbol.json file
- `os.environ['MXNET_CUDNN_AUTOTUNE_DEFAULT'] = '0'`

**Comment by nanhui69** [comment]
> The following steps combined removed all autotunes for me. Neither of the two steps worked alone:
> 
> * Replacing the `cudnn_tune` value `"limited_workspace"` with `"off"` in the R50-symbol.json file
> * `os.environ['MXNET_CUDNN_AUTOTUNE_DEFAULT'] = '0'`
how to set the first one " cudnn_tune value "limited_workspace" with "off" "?

**Comment by nanhui69** [comment]
> in the R50-symbol.json file, reset param cudnn_tune's value with "None" would help. the default value of cudnn_tune is limited_workspace.
> [mxnet reference](http://mxnet.incubator.apache.org/versions/master/api/python/symbol/symbol.html?highlight=cudnn_tune)

how to set this value [ cudnn_tune ] ?

**Comment by jasonchenPJ** [comment]
@nanhui69 
you could replace the "cudnn_tune" setting in downloaded "R50-symbol.json".
(the default path maybe is /home/.insightface/models/retinaface_r50_v1/...)

And it's work for me:
before(MXNET_CUDNN_AUTOTUNE_DEFAULT no setting, cudnn_tune=limited_workspace):
 img 1: size=(428, 642, 3), time=19.829s
 img 2: size=(300, 401, 3), time=5.720s
 img 3: size=(264, 470, 3), time=5.822s
 img 4: size=(240, 320, 3), time=4.511s
 img 5: size=(196, 336, 3), time=5.511s

after(MXNET_CUDNN_AUTOTUNE_DEFAULT=0, cudnn_tune=off):
 img 1: size=(428, 642, 3), time=0.321s
 img 2: size=(300, 401, 3), time=0.220s
 img 3: size=(264, 470, 3), time=0.225s
 img 4: size=(240, 320, 3), time=0.201s
 img 5: size=(196, 336, 3), time=0.200s

but it's still slowly....
my gpu is P100, run on Retinaface-R50 model.
