### ISSUE TITLE
Accuracy error 

### ISSUE THREAD

**Issue by kalenforn** [deepinsight/insightface#697]
This problem is when I run ${DIR}/recognition/train.py
After two days of  train, the Fmobilefacenet model is stil have very low accuracy.
The accuracy has been kept at around 40% when the EPOCH exceeds 7,The accuracy has not changed for more than a day.
The initial learning rate I set is 0.01,(the other parameters are defaule value, I used the pre_train model of model-y1-test2.the dataset is faces_emore)but now it has been trained more than 80W times.the accuracy has been 0.4 since 20W times.
I would like to ask if I set some parameters wrong,do I need to stop training and run begin or wait?
could anyone give me some advice?

this is the result:
INFO:root:Epoch[19] Batch [12700-12720]	Speed: 962.42 samples/sec	acc=0.428906	lossvalue=6.046267
INFO:root:Epoch[19] Batch [12720-12740]	Speed: 963.09 samples/sec	acc=0.427344	lossvalue=5.902352
INFO:root:Epoch[19] Batch [12740-12760]	Speed: 964.05 samples/sec	acc=0.405469	lossvalue=6.006512
INFO:root:Epoch[19] Batch [12760-12780]	Speed: 963.62 samples/sec	acc=0.417578	lossvalue=5.868161
INFO:root:Epoch[19] Batch [12780-12800]	Speed: 964.76 samples/sec	acc=0.417187	lossvalue=5.869784
INFO:root:Epoch[19] Batch [12800-12820]	Speed: 963.46 samples/sec	acc=0.411719	lossvalue=5.908864
INFO:root:Epoch[19] Batch [12820-12840]	Speed: 964.05 samples/sec	acc=0.421875	lossvalue=5.642534
INFO:root:Epoch[19] Batch [12840-12860]	Speed: 962.02 samples/sec	acc=0.414844	lossvalue=5.834743
INFO:root:Epoch[19] Batch [12860-12880]	Speed: 962.71 samples/sec	acc=0.444141	lossvalue=5.611831
INFO:root:Epoch[19] Batch [12880-12900]	Speed: 962.17 samples/sec	acc=0.423828	lossvalue=5.923916
INFO:root:Epoch[19] Batch [12900-12920]	Speed: 960.92 samples/sec	acc=0.426563	lossvalue=6.021607
INFO:root:Epoch[19] Batch [12920-12940]	Speed: 961.78 samples/sec	acc=0.428906	lossvalue=5.919426
INFO:root:Epoch[19] Batch [12940-12960]	Speed: 963.17 samples/sec	acc=0.445703	lossvalue=5.512040
INFO:root:Epoch[19] Batch [12960-12980]	Speed: 964.21 samples/sec	acc=0.428906	lossvalue=5.967726
INFO:root:Epoch[19] Batch [12980-13000]	Speed: 962.44 samples/sec	acc=0.425781	lossvalue=5.983425
INFO:root:Epoch[19] Batch [13000-13020]	Speed: 965.38 samples/sec	acc=0.411719	lossvalue=6.059293
INFO:root:Epoch[19] Batch [13020-13040]	Speed: 965.50 samples/sec	acc=0.444531	lossvalue=5.542191
INFO:root:Epoch[19] Batch [13040-13060]	Speed: 962.32 samples/sec	acc=0.425391	lossvalue=5.960517
INFO:root:Epoch[19] Batch [13060-13080]	Speed: 961.57 samples/sec	acc=0.433203	lossvalue=5.703861
INFO:root:Epoch[19] Batch [13080-13100]	Speed: 962.33 samples/sec	acc=0.427734	lossvalue=5.952133
INFO:root:Epoch[19] Batch [13100-13120]	Speed: 961.56 samples/sec	acc=0.429297	lossvalue=5.969763
INFO:root:Epoch[19] Batch [13120-13140]	Speed: 961.73 samples/sec	acc=0.429297	lossvalue=5.904568
INFO:root:Epoch[19] Batch [13140-13160]	Speed: 960.38 samples/sec	acc=0.430469	lossvalue=5.789618
INFO:root:Epoch[19] Batch [13160-13180]	Speed: 961.28 samples/sec	acc=0.413281	lossvalue=6.073223
INFO:root:Epoch[19] Batch [13180-13200]	Speed: 896.69 samples/sec	acc=0.440234	lossvalue=5.846615
INFO:root:Epoch[19] Batch [13200-13220]	Speed: 963.65 samples/sec	acc=0.420703	lossvalue=5.787654
INFO:root:Epoch[19] Batch [13220-13240]	Speed: 963.00 samples/sec	acc=0.432031	lossvalue=5.570357
INFO:root:Epoch[19] Batch [13240-13260]	Speed: 963.06 samples/sec	acc=0.429688	lossvalue=5.887249
INFO:root:Epoch[19] Batch [13260-13280]	Speed: 959.40 samples/sec	acc=0.421875	lossvalue=5.919816
INFO:root:Epoch[19] Batch [13280-13300]	Speed: 963.92 samples/sec	acc=0.419531	lossvalue=5.864249
INFO:root:Epoch[19] Batch [13300-13320]	Speed: 962.32 samples/sec	acc=0.426563	lossvalue=5.908086
INFO:root:Epoch[19] Batch [13320-13340]	Speed: 960.50 samples/sec	acc=0.425391	lossvalue=5.949596
INFO:root:Epoch[19] Batch [13340-13360]	Speed: 965.47 samples/sec	acc=0.419531	lossvalue=5.906333
INFO:root:Epoch[19] Batch [13360-13380]	Speed: 962.36 samples/sec	acc=0.402734	lossvalue=6.195996
INFO:root:Epoch[19] Batch [13380-13400]	Speed: 960.74 samples/sec	acc=0.419531	lossvalue=6.070377
INFO:root:Epoch[19] Batch [13400-13420]	Speed: 960.01 samples/sec	acc=0.424219	lossvalue=5.838836
INFO:root:Epoch[19] Batch [13420-13440]	Speed: 960.15 samples/sec	acc=0.417187	lossvalue=6.094613
INFO:root:Epoch[19] Batch [13440-13460]	Speed: 962.03 samples/sec	acc=0.421094	lossvalue=5.768937
INFO:root:Epoch[19] Batch [13460-13480]	Speed: 964.95 samples/sec	acc=0.424609	lossvalue=5.965929
INFO:root:Epoch[19] Batch [13480-13500]	Speed: 963.47 samples/sec	acc=0.425781	lossvalue=5.824329
INFO:root:Epoch[19] Batch [13500-13520]	Speed: 962.11 samples/sec	acc=0.415234	lossvalue=6.084083
INFO:root:Epoch[19] Batch [13520-13540]	Speed: 959.87 samples/sec	acc=0.414062	lossvalue=5.965085
INFO:root:Epoch[19] Batch [13540-13560]	Speed: 961.37 samples/sec	acc=0.403516	lossvalue=5.991571
INFO:root:Epoch[19] Batch [13560-13580]	Speed: 965.02 samples/sec	acc=0.423047	lossvalue=5.960075
INFO:root:Epoch[19] Batch [13580-13600]	Speed: 963.58 samples/sec	acc=0.430078	lossvalue=5.924636
INFO:root:Epoch[19] Batch [13600-13620]	Speed: 961.85 samples/sec	acc=0.417578	lossvalue=5.853987
INFO:root:Epoch[19] Batch [13620-13640]	Speed: 960.35 samples/sec	acc=0.423438	lossvalue=5.940636
INFO:root:Epoch[19] Batch [13640-13660]	Speed: 963.53 samples/sec	acc=0.442188	lossvalue=5.928348
INFO:root:Epoch[19] Batch [13660-13680]	Speed: 962.81 samples/sec	acc=0.441797	lossvalue=5.847528
INFO:root:Epoch[19] Batch [13680-13700]	Speed: 958.40 samples/sec	acc=0.426563	lossvalue=5.718157
lr-batch-epoch: 1e-05 13708 19
testing verification..
(12000, 128)
infer time 5.692380000000002
[lfw][878000]XNorm: 11.473797
[lfw][878000]Accuracy-Flip: 0.99450+-0.00422
testing verification..
(14000, 128)
infer time 6.6363949999999985
[cfp_fp][878000]XNorm: 9.717314
[cfp_fp][878000]Accuracy-Flip: 0.93700+-0.01510
testing verification..
(12000, 128)
infer time 5.682969999999998
[agedb_30][878000]XNorm: 11.312865
[agedb_30][878000]Accuracy-Flip: 0.95650+-0.01063
[878000]Accuracy-Highest: 0.95933
INFO:root:Epoch[19] Batch [13700-13720]	Speed: 95.56 samples/sec	acc=0.423047	lossvalue=6.061180
INFO:root:Epoch[19] Batch [13720-13740]	Speed: 963.14 samples/sec	acc=0.410938	lossvalue=5.823772
INFO:root:Epoch[19] Batch [13740-13760]	Speed: 961.95 samples/sec	acc=0.413672	lossvalue=6.148740
INFO:root:Epoch[19] Batch [13760-13780]	Speed: 962.54 samples/sec	acc=0.416406	lossvalue=6.151298
INFO:root:Epoch[19] Batch [13780-13800]	Speed: 961.03 samples/sec	acc=0.422266	lossvalue=5.950473
INFO:root:Epoch[19] Batch [13800-13820]	Speed: 963.65 samples/sec	acc=0.430078	lossvalue=5.755674
INFO:root:Epoch[19] Batch [13820-13840]	Speed: 961.82 samples/sec	acc=0.432812	lossvalue=5.677666
INFO:root:Epoch[19] Batch [13840-13860]	Speed: 964.20 samples/sec	acc=0.417969	lossvalue=6.021457
INFO:root:Epoch[19] Batch [13860-13880]	Speed: 961.87 samples/sec	acc=0.420312	lossvalue=6.127388
INFO:root:Epoch[19] Batch [13880-13900]	Speed: 964.52 samples/sec	acc=0.415234	lossvalue=5.956756
INFO:root:Epoch[19] Batch [13900-13920]	Speed: 962.92 samples/sec	acc=0.418750	lossvalue=5.817868
INFO:root:Epoch[19] Batch [13920-13940]	Speed: 962.17 samples/sec	acc=0.433984	lossvalue=5.877563
INFO:root:Epoch[19] Batch [13940-13960]	Speed: 962.69 samples/sec	acc=0.419922	lossvalue=6.022497
INFO:root:Epoch[19] Batch [13960-13980]	Speed: 961.04 samples/sec	acc=0.435156	lossvalue=5.622451
INFO:root:Epoch[19] Batch [13980-14000]	Speed: 960.89 samples/sec	acc=0.436719	lossvalue=5.697604

I used GTX 2080 ,cpu i7-7800.

**Comment by kalenforn** [comment]
Unlucky,accidentally pressed ctrl c..........................................

**Comment by 2151330** [comment]
I have the same problem with you. Is it normal?

**Comment by kalenforn** [comment]
> I have the same problem with you. Is it normal?
It is a normal problem,but it is not a problem.in every line's "acc=" is not the accuracy when you training,this may be the other information from this train,the real accuracy like this: 

[lfw][878000]XNorm: 11.473797
[lfw][878000]Accuracy-Flip: 0.99450+-0.00422
testing verification..
(14000, 128)
infer time 6.6363949999999985
[cfp_fp][878000]XNorm: 9.717314
[cfp_fp][878000]Accuracy-Flip: 0.93700+-0.01510
testing verification..
(12000, 128)
infer time 5.682969999999998
[agedb_30][878000]XNorm: 11.312865
[agedb_30][878000]Accuracy-Flip: 0.95650+-0.01063
[878000]Accuracy-Highest: 0.95933

you while watch this when it training epoch attain some condition.I forgot this condition.because I am prepare for my exam. you can find this condition in the source code.
good luck for you! I can only help you so far.
@2151330
