### ISSUE TITLE
问个问题：ssh只能检测人脸框，如果想和mtcnn一样输出关键点，怎么训练呢？多加个loss分支？

### ISSUE THREAD

**Issue by westnight** [deepinsight/insightface#698]

**Comment by oftenliu** [comment]
github有人做了这个工作 你可以去搜索下

**Comment by westnight** [comment]
搞定了，就是多加个head

**Comment by nttstar** [comment]
It was included in our code

**Comment by mohuazheliu** [comment]
Could you tell me more about it?

**Comment by youthM** [comment]
> 搞定了，就是多加个head

能详细说下吗？

**Comment by youthM** [comment]
> It was included in our code

Can you tell the place of the part is in your code?
