### ISSUE TITLE
CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by portgasray** [deepinsight/insightface#699]
![20190524233757](https://user-images.githubusercontent.com/17681580/58339855-0e73e980-7e7d-11e9-8e44-ea73c5169972.png)
`ver agedb_30
lr_steps [100000, 160000, 220000]
call reset()
[15:35:02] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
/mxnet/python/mxnet/module/base_module.py:466: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.125). Is this intended?
  optimizer_params=optimizer_params)
terminate called after throwing an instance of 'dmlc::Error'
  what():  [15:35:02] src/engine/./threaded_engine.h:359: [15:35:02] src/operator/contrib/./../linalg_impl.h:140: Check failed: e == CUBLAS_STATUS_SUCCESS (13 vs. 0) cuBLAS: CUBLAS_STATUS_EXECUTION_FAILED

Stack trace returned 10 entries:
[bt] (0) /mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x5a) [0x7f36c804e59a]
[bt] (1) /mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7f36c804f138]
[bt] (2) /mxnet/python/mxnet/../../lib/libmxnet.so(void linalg_gemm<mshadow::gpu, float>(mshadow::Tensor<mshadow::gpu, 2, float> const&, mshadow::Tensor<mshadow::gpu, 2, float> const&, mshadow::Tensor<mshadow::gpu, 2, float> const&, float, float, bool, bool, mshadow::Stream<mshadow::gpu>*)+0x40a) [0x7f36cac5667a]
[bt] (3) /mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::op::FullyConnectedOp<mshadow::gpu, float>::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0xb1c) [0x7f36cadc6cdc]
[bt] (4) /mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::op::OperatorState::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x363) [0x7f36ca5969a3]
[bt] (5) /mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::exec::StatefulComputeExecutor::Run(mxnet::RunContext, bool)+0x69) [0x7f36cab3a549]
[bt] (6) /mxnet/python/mxnet/../../lib/libmxnet.so(+0x33f1170) [0x7f36cab0d170]
[bt] (7) /mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x93) [0x7f36caa88983]
[bt] (8) /mxnet/python/mxnet/../../lib/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>)+0xcb) [0x7f36caa90cab]
[bt] (9) /mxnet/python/mxnet/../../lib/libmxnet.so(std::_Function_handler<void (std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#3}::operator()() const::{lambda(std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>&&)+0x63) [0x7f36caa90ea3]

A fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

Stack trace returned 9 entries:
[bt] (0) /mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x5a) [0x7f36c804e59a]
[bt] (1) /mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7f36c804f138]
[bt] (2) /mxnet/python/mxnet/../../lib/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x332) [0x7f36caa88c22]
[bt] (3) /mxnet/python/mxnet/../../lib/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>)+0xcb) [0x7f36caa90cab]
[bt] (4) /mxnet/python/mxnet/../../lib/libmxnet.so(std::_Function_handler<void (std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#3}::operator()() const::{lambda(std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>&&)+0x63) [0x7f36caa90ea3]
[bt] (5) /mxnet/python/mxnet/../../lib/libmxnet.so(std::thread::_Impl<std::_Bind_simple<std::function<void (std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>)> (std::shared_ptr<mxnet::engine::ThreadPool::SimpleEvent>)> >::_M_run()+0x4a) [0x7f36caa8b07a]
[bt] (6) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f36d83ebc80]
[bt] (7) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f36ef85d6ba]
[bt] (8) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f36ef5933dd]
`

**Comment by portgasray** [comment]
cuda 10.1
cudnn 7.5

**Comment by 1frey** [comment]
Any news? I ran into the same issue.

cuda 9.0
cudnn 7.6.2

**Comment by mhtrinh** [comment]
I got this error too. I solve it by trial and error, matching a bunch of cudnn and cuda version ... What worked :
cuda 9.0.176 + cudnn 7.6.4-for-cuda-9.0
cuda 9.0.176 + cudnn 7.6.2-for-cuda-9.2 (surprisingly this worked ... but the previous sounds more sane)

**Comment by LiFXe** [comment]
Hi, have you got the solution?

**Comment by mhtrinh** [comment]
My solution was to upgrade to :
- mxnet 1.5.0-cu101
- Cuda 10.1.243
- Cudnn 7.6 (I am not sure that it even need this !)
