### ISSUE TITLE
Angular-Triplet-Loss

### ISSUE THREAD

**Issue by MartinDione** [deepinsight/insightface#7]
You have made a great work here. However, I believe that adding Angular Triplet Loss (https://github.com/KaleidoZhouYN/Angular-Triplet-Loss) will definitely improve the results on Megaface and LFW. Unfortunately, I do not have enough experience to implement it in MxNet. Hope someone will try it out soon.

Did you try this new loss? or willing to try it?

**Comment by nttstar** [comment]
Thank you. Maybe we will try it later.
