### ISSUE TITLE
pickle.load  failed

### ISSUE THREAD

**Issue by 1018365842** [deepinsight/insightface#70]
Hello everyone. when I use the train_softmax.py , the program went wrong when execute this statement pickle.load(open(lfw.bin, 'rb'), the error message is : UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128).   Who knows how to solve this problem? thanks.

**Comment by mike07026** [comment]
pickle.load(open(path, 'rb'), encoding='bytes')
