### ISSUE TITLE
converted RetinaFace mnet.25 caffemodel

### ISSUE THREAD

**Issue by Charrin** [deepinsight/insightface#700]
I convert the mnet.25 mxnet model (trained by [yangfly](https://github.com/yangfly) ) to caffe model, and implement a simple c++ code
please check https://github.com/Charrin/RetinaFace-Cpp

**Comment by borisgribkov** [comment]
Did you compare the output for MxNet and Caffe models? Is it the same?

**Comment by Charrin** [comment]
> Did you compare the output for MxNet and Caffe models? Is it the same?

yes, the outputs are the same, and you can check it by yourself

**Comment by borisgribkov** [comment]
Thanks for the answer, I'm a bit curious, because I have tried several MxNet to Caffe converters previously and did't see the same output. That's great, did you develop converter yourself or use something available?

**Comment by Charrin** [comment]
> Thanks for the answer, I'm a bit curious, because I have tried several MxNet to Caffe converters previously and did't see the same output. That's great, did you develop converter yourself or use something available?

I use MMDNN, but need add deconv/crop/reshape support by myself

**Comment by Charrin** [comment]
> Thanks for the answer, I'm a bit curious, because I have tried several MxNet to Caffe converters previously and did't see the same output. That's great, did you develop converter yourself or use something available?

If you have checked the output be the same, please reply to make the converted model more reliable, thank you :)

**Comment by zhly0** [comment]
@Charrin ，Hi,Charrin:
    can you make your convert code open source？The mmdnn does not support several operations，like upsampling，and crop.I could add operation upsampling,but failed to add crop.Thanks.

**Comment by Charrin** [comment]
> @Charrin ，Hi,Charrin:
> can you make your convert code open source？The mmdnn does not support several operations，like upsampling，and crop.I could add operation upsampling,but failed to add crop.Thanks.

@zhly0 
I add the upsampling/crop/reshape support, but they are temporary and not correct, it just makes MMDNN generating prototxt file without error,  I must modity the prototxt after generated

**Comment by Charrin** [comment]
> @Charrin ，Hi,Charrin:
> can you make your convert code open source？The mmdnn does not support several operations，like upsampling，and crop.I could add operation upsampling,but failed to add crop.Thanks.

@zhly0 
you can modify "concat function" to "crop function", they are similarity, both need two bottom blobs and output one top blob.

**Comment by zhly0** [comment]
@Charrin ，Thanks.

**Comment by 791136190** [comment]
@Charrin can you share your MMDNN tools?

**Comment by EtheneXiang** [comment]
hello,can u share you convert script from mxnet to caffe?@Charrin  thx very much

**Comment by ideaRunner** [comment]
@Charrin It is awesome that you convert RetinaFace model via mmdnn tools.

**Comment by zt1112** [comment]
@ideaRunner Have you solve this problem?I tried convert  RetinaFace-R50caffemodel->onnx->.pb, upsample and reshape op can be converted successfully, but crop op can't.

**Comment by ideaRunner** [comment]
No, Still facing that problem, the mxnet op is so weird.



---Original---

**Comment by gasgallo** [comment]
Interested in how to convert from mxnet to caffe...

**Comment by zheshipinyinMc** [comment]
https://github.com/zheshipinyinMc/arcface_retinaface_mxnet2caffe
