### ISSUE TITLE
Imperial template size 2048?? Isn't it 512 sized embedding?

### ISSUE THREAD

**Issue by vizakshat** [deepinsight/insightface#703]
Are you using multiple models for FRVT??

**Comment by mlourencoeb** [comment]
Educated guess, the 512 float template is being copied Ingo a byte array.

**Comment by vizakshat** [comment]
Thanks, this seems to be the answer but does truncate floats to lesser digits have an impact on accuracy?

**Comment by mlourencoeb** [comment]
No, matching the two templates properly requires to copy back to float arrays. No decrease in accuracy.
