### ISSUE TITLE
In IJBC_Evaluation_MS1MV2.ipynb, What does the "use_flip_test" do?

### ISSUE THREAD

**Issue by AmigoCDT** [deepinsight/insightface#705]
In IJBC_Evaluation_MS1MV2.ipynb, we set "F2", i.e. `use_flip_test=True`
Then `img_input_feats = img_feats[:,0:img_feats.shape[1]/2] + img_feats[:,img_feats.shape[1]/2:]`
I wanna know What this code is doing? I cannot get it.
Thank you.

**Comment by vizakshat** [comment]
It's a left-right flip. As face images have symmetry across the vertical axis, embedding generated with LR flip can be used to take the mean. The 512D point will be an average of two embeddings. This may increase accuracy but definitely will increase the cost.

**Comment by AmigoCDT** [comment]
@vizakshat I guess so, too.
But I don't think the model can learn symmetric embeddings as we hope.
If not so:
we assume two 4D embeddings: X=[x_1, x_2, x_3, x_4], Y=[y_1, y_2, y_3, y_4]
    If we straightly use the embeddings: 
        sim(X, Y) = X*Y = sum(x_i * y_i)
    If we do flip operation (here don't consider the following normalization): 
        sim(X_F, Y_F) = sum(x_i * y_i) + x_1*y_3 + x_3*y_1 + x_2*y_4 +x_4*y_2
        Probablity, the extra part could not help to increase the accuracy, even decrease it.
