### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'image_shape'

### ISSUE THREAD

**Issue by biexiangduo** [deepinsight/insightface#706]
(base) pf@pf:~/insightface/recognition$ CUDA_VISIBLE_DEVICES='0' python -u train.py --network r100 --loss arcface --dataset emore
[09:05:04] src/engine/engine.cc:55: MXNet start using engine: ThreadedEnginePerDevice
gpu num: 1
prefix ./models/r100-arcface-emore/model
Traceback (most recent call last):
  File "train.py", line 377, in <module>
    main()
  File "train.py", line 374, in main
    train_net(args)
  File "train.py", line 167, in train_net
    args.image_channel = config.image_shape[2]
AttributeError: 'EasyDict' object has no attribute 'image_shape'

anyone met these problem?
or dose it require the size of gpu?

**Comment by AmigoCDT** [comment]
Does [this line](https://github.com/deepinsight/insightface/blob/master/recognition/sample_config.py#L113) exist?

**Comment by ab2010do** [comment]
me too, i have the  same problem.

**Comment by ab2010do** [comment]
Hi amigoCDT
did you fix the problem

**Comment by AmigoCDT** [comment]
@ab2010do Sorry, I never met this problem. 
As the Error Message said: this is caused by lost of `dataset.emore.image_shape = (112,112,3)`. 
If you are using your private dataset, you need to add such `dataset.dataset_name = edict()` and its info.

**Comment by azuru28** [comment]
> @ab2010do抱歉，我没遇到过这个问题。 正如错误消息所说：这是由于丢失了 造成的`dataset.emore.image_shape = (112,112,3)`。 如果您使用的是私有数据集，则需要添加此类`dataset.dataset_name = edict()`及其信息。

你好，我使用的时自定义数据集，请问你说的添加`dataset.dataset_name = edict()`及其信息具体该怎么做
