### ISSUE TITLE
ubuntu18.04下运行train.py卡死

### ISSUE THREAD

**Issue by wting861006** [deepinsight/insightface#710]
硬件配置：
GPU:nvidia 1080ti *4
CPU:amd 2960x
内存:128G
操作系统：ubuntu 18.04
python:2.7
nvidia显卡驱动：nvidia-driver-430
cuda:10.0
mxnet:mxnet-cu100

<
wangting@wangting:~/insightface/recognition$ CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train.py --network r100 --loss arcface --dataset emore
gpu num: 4
prefix ./models/r100-arcface-emore/model
image_size [112, 112]
num_classes 85742
Called with argument: Namespace(batch_size=64, ckpt=3, ctx_num=4, dataset='emore', frequent=20, image_channel=3, kvstore='device', loss='arcface', lr=0.1, lr_steps='100000,160000,220000', models_root='./models', mom=0.9, network='r100', per_batch_size=16, pretrained='', pretrained_epoch=1, rescale_threshold=0, verbose=2000, wd=0.0005) {'loss_m1': 1.0, 'loss_m2': 0.5, 'loss_m3': 0.0, 'net_act': 'prelu', 'emb_size': 512, 'data_rand_mirror': True, 'num_layers': 100, 'loss_name': 'margin_softmax', 'val_targets': ['lfw', 'cfp_fp', 'agedb_30'], 'ce_loss': True, 'net_input': 1, 'image_shape': [112, 112, 3], 'net_blocks': [1, 4, 6, 2], 'fc7_lr_mult': 1.0, 'ckpt_embedding': True, 'net_unit': 3, 'net_output': 'E', 'count_flops': True, 'num_workers': 1, 'batch_size': 64, 'memonger': False, 'data_images_filter': 0, 'dataset': 'emore', 'num_classes': 85742, 'fc7_no_bias': False, 'loss': 'arcface', 'data_color': 0, 'loss_s': 64.0, 'dataset_path': '/home/wangting/insightface/datasets/faces_ms1m_112x112', 'data_cutoff': False, 'net_se': 0, 'net_multiplier': 1.0, 'fc7_wd_mult': 1.0, 'network': 'r100', 'per_batch_size': 16, 'net_name': 'fresnet', 'workspace': 256, 'max_steps': 0, 'bn_mom': 0.9}
0 1 E 3 prelu False
Network FLOPs: 24.2G
INFO:root:loading recordio /home/wangting/insightface/datasets/faces_ms1m_112x112/train.rec...
header0 label [3804847. 3890011.]
id2range 85164
3804846
rand_mirror True
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver lfw
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
loading bin 13000
(14000L, 3L, 112L, 112L)
ver cfp_fp
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver agedb_30
lr_steps [100000, 160000, 220000]
call reset()
/home/wangting/.local/lib/python2.7/site-packages/mxnet/module/base_module.py:505: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (0.25 vs. 0.015625). Is this intended?
  optimizer_params=optimizer_params)
>
程序运行到此处就不再往下运行了，没有报错
<img width="634" alt="image" src="https://user-images.githubusercontent.com/25969464/58548996-18129e00-823d-11e9-877b-9a1e283617d7.png">

sudo kill -9 27155强行kill进程时无效，系统直接死机。
我反复重装系统，确保没有其他干扰，尝试过cuda9.0+mxnet-cu90和cuda10.0+mxnet-cu100，都是同样的效果。
我在windows10下运行则一切正常，排除硬件故障。请问我应该如何做才能正常运行？

**Comment by wting861006** [comment]
经过测试，发现单独使用一块显卡的时候不会卡死，这个现象在windows下不会出现。另外，我在ubuntu下使用darknet训练物体检测，使用4块gpu是能够正常工作的，是不是mxnet有bug？我使用的是1.4.1版本

**Comment by wting861006** [comment]
windows下可以训练，为什么还要到ubuntu下训练？
我是新手，学习insightface有半个月了，聊一下我遇到的一些问题吧。
1、训练速度：
1.1、我看了一下其他人的反馈，用4块1080ti训练的per-batch-size设置成128可以正常运行，而我设置成60就会出现menory out，我设置成50.
1.2、我用4块gpu训练，得到的速度是200左右，我有看到其他人说把dataset放到ssd上能达到1000以上，我试过了没有什么效果。我还有一台电脑上有一块titanV的GPU，在这台机上训练速度能达到180左右，这种现象让我很困惑。4块1080ti的性能只比1块titanv快20？
2、acc、lossvalue、verification
使用--loss arcface，acc=0.98，lossvalue=0.4 verification（lfw，cfp-fp，age-db）=0.5左右
我使用--loss softmax，--pretrained加载arcface保存的model，acc=0,lossvalue=10,verification（lfw，cfp-fp，age-db）=0.5左右
基于以上两点，我开始怀疑是不是环境有问题。难道就我遇到这样的问题吗？

**Comment by nttstar** [comment]
@wting861006 尝试下编译安装mxnet, 数据尽量都放在SSD

**Comment by AmigoCDT** [comment]
Res50在12G显存上batch大概可以设置为128，Res100的batch最大应该只能设置到64。。。你的batch是50，会不会是没有用`train_parall.py`或者没有做`cp train_parall.py train.py`？

**Comment by wting861006** [comment]
我没有cp train_parall.py，用的是原来的那个train.py。1080ti batch最多设到52，再多就mem out了。

**Comment by AmigoCDT** [comment]
可以试下train_parall.py，这个脚本对多卡做了优化，使用多卡的时候可以增大Batch_size。。。如果用train.py，数据集的类别越多，相同显存下可以设置的Batch_size越小。

**Comment by wting861006** [comment]
好的，我编译安装一下mxnet后试试。谢谢你的热心回答

**Comment by mnikitin** [comment]
@nttstar @AmigoCDT Hello, guys! I have some issues with the batch size, too. 
Using my own dataset and running train_parall.py on 1080ti GPUs server, I can train resnet50 with per_batch_size=92. 
At the same time, I can set roughly the same per_batch_size for mxnet's Module.fit() which doesn't do any center matrix optimizattions. It works slower then parallel training, but memory consumption is the same.

Any ideas why train_parall.py doesn't let me use bigger batch_size?

**Comment by EtheneXiang** [comment]
@AmigoCDT 
老哥，请教一个问题，我尝试了下，你说的parall这个文件，直接报错了。我就仅仅把命令行里面的train.py换成了train_parall.py，没做其他任何改动【使用方法全部安装官方的来的，用train.py就可以启动训练】我的训练命令如下：

export MXNET_CPU_WORKER_NTHREADS=24
export MXNET_CUDNN_AUTOTUNE_DEFAULT=0
export MXNET_ENGINE_TYPE=ThreadedEnginePerDevice
CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7' python2 -u train.py --dataset xxxx--network r100 --loss arcface 

错误信息如下：，求指点迷津。

Traceback (most recent call last):
File "train_parall.py", line 336, in 
main()
File "train_parall.py", line 333, in main
train_net(args)
File "train_parall.py", line 188, in train_net
assert False
AssertionError
下面是错误提示的地方
![image](https://user-images.githubusercontent.com/49241737/59846454-848f4180-9392-11e9-81be-6beb78c44f85.png)

关于这个问题，我看作者自己给的例子也是这样说的https://github.com/deepinsight/insightface/tree/master/recognition
Note: Replace train.py with train_parall.py in following examples if you want to use parallel acceleration.

**Comment by wting861006** [comment]
@nttstar 我重装了一个新系统，编译安装mxnet，在使用多gpu train.py或train_parall.py训练的时候依然卡死，对此你能给我一些建议来排查问题吗？谢谢！

**Comment by zfs1993** [comment]
> 可以试下train_parall.py，这个脚本对多卡做了优化，使用多卡的时候可以增大Batch_size。。。如果用train.py，数据集的类别越多，相同显存下可以设置的Batch_size越小。

你好，train_parall.py，这个脚本不输出acc和loss，那我通过看什么指标来调节参数呀

**Comment by speshowBUAA** [comment]
@wting861006 
/home/wangting/.local/lib/python2.7/site-packages/mxnet/module/base_module.py:505: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (0.25 vs. 0.015625). Is this intended?
请问出现这句话是什么意思呢？需要解决吗？
