### ISSUE TITLE
insightface models runing time on arm cpu with TVM

### ISSUE THREAD

**Issue by lynneHuang10** [deepinsight/insightface#714]
Hi Jack, i have referenced the instruction about how to run on TVM. however i still have some questions.
1.  the MobileFace running time is not the same as you report.I deploy the model on Huawei Mate20 and it use 61ms@400%CPU while as you report Firefly Rk 3399@A72 * 1 | 69.24ms. it only use 100% CPU?

2. the tvm benchmark models are auto-fined with autoTVM? 

3. Try to remove minimal value(<e-4) in model parameters,These value will cause bad performance. it means set these minimal value to 0,or remove it? can you give me the example code ?

4. i plan deploy the LResNet50-IR on arm device,but the model size is very big,can you give me some advise about how to slim them?

thanks very much, and looking forward you feedback

**Comment by xdcesc** [comment]
Could you please show details of using TVM to implement model? @lynneHuang10
