### ISSUE TITLE
Training/testing with different face detection alignment algorithms?

### ISSUE THREAD

**Issue by vizakshat** [deepinsight/insightface#716]
What would happen if I train the network using Retinaface aligned dataset and test it on MTCNN aligned dataset? Would the performance improve by using Retina face in training?

**Comment by yangfly** [comment]
You'd better use the same alignment tool.

**Comment by MyraBaba** [comment]
@yangfly  What is the preferred Alignment tool/way for Retinaface ? Paper said its improving the accuracy ?

**Comment by yangfly** [comment]
If you want to use RetinaFace in your deploy environment, you'd better use RetinaFace aligned faces to train your insightface. So is MTCNN.

**Comment by MyraBaba** [comment]
both training and the deployment should use the same face detection and same alignment right ?

Best

**Comment by hemameh** [comment]
Is aligning done the same way for retinaface as mtcnn, i.e same code ? Want to check the improvement in face recognition for using retinaface alignment instead of mtcnn but don't know how to do it correctly using the same code.

**Comment by yangfly** [comment]
Yes for both.

**Comment by MyraBaba** [comment]
@yangfly  @hemameh 
So Can I use Retina face detected face (bbox and points) to give insightface pretrained model for future extraction ? 

Also some bad photos cant be detected as face (gray , black&white etc) SO I I crop the face and than manually point the 5 landmark point is it a good idea to give this information to : 

`    nimg = face_preprocess.preprocess(face_img, bbox, points, image_size='112,112')
     nimg = cv2.cvtColor(nimg, cv2.COLOR_BGR2RGB)
    aligned = np.transpose(nimg, (2,0,1))
`

to have a preprocessed image ready for extract futures ?

**Comment by syedmustafa54** [comment]
@MyraBaba did you used retina face instead of mtcnn on `nimg = face_preprocess.preprocess(face_img, bbox, points, image_size='112,112')` how was your output because when I tried to change from mtcnn  to retina face it got full frame instead of crop  align image

**Comment by Coderx7** [comment]
You need to note that, regardless of your choice of detector/aligner, they need to be trained using the very same preprocessing regime. if your detector preprocess the input image differently than it was used for example with mtcnn, then you will see huge false positive rate in your detection as the embeder was also trained on images that were cropped/aligned using a different preprocessing method.
