### ISSUE TITLE
Different Landmarks order in RetinaFace output

### ISSUE THREAD

**Issue by oljike** [deepinsight/insightface#717]
If you want to use RetinaFace in deploy, please, remove "reshape(2, 5).T" for RetinaFace landmarks, because the are already ordered as follows -> [[x1, y1], [x2, y2], ... [x5, y5]]

**Comment by olzhaskabdolov** [comment]
https://github.com/deepinsight/insightface/blob/f61956fda322db9977a9bc250031c079c2eb6192/deploy/face_model.py#L78
