### ISSUE TITLE
YTF dataset

### ISSUE THREAD

**Issue by renyanfei12321** [deepinsight/insightface#720]
Thank you very much for providing your code, I hope you can provide the aligned YTF dataset.
I didn't get the desired results on my own data set.
thank you very much

**Comment by Talgin** [comment]
Hi, what was your accuracy? 
We're also going to train on our custom dataset and wanted to know the results of others. How many classes did you have, and the number of images, and how did you align them? 
We created our custom dataset by aligning using facenet's alignment (mtcnn), but before this we cropped the images and did revision of images automatically/by hand (removing not similar persons).
