### ISSUE TITLE
RetinaFace running with r50 cost too much time

### ISSUE THREAD

**Issue by mingzhang96** [deepinsight/insightface#732]
I just follow your `test.py` and add some code like following:
```
count = 10
for c in range(count):
    start = time.time()
    faces, landmarks = detector.detect(img, thresh, scales=[im_scale])
    end = time.time()
    print(end - start)
    print(c, faces.shape, landmarks.shape)
```
but find it running slowly, it takes 10 more seconds to forward an image.
```
12.197124958
(0, (1, 5), (1, 5, 2))
0.05788397789
(1, (1, 5), (1, 5, 2))
0.0318050384521
(2, (1, 5), (1, 5, 2))
0.030042886734
(3, (1, 5), (1, 5, 2))
0.0293989181519
(4, (1, 5), (1, 5, 2))
0.0300710201263
(5, (1, 5), (1, 5, 2))
0.0289559364319
(6, (1, 5), (1, 5, 2))
0.0285160541534
(7, (1, 5), (1, 5, 2))
0.0282299518585
(8, (1, 5), (1, 5, 2))
0.0288300514221
(9, (1, 5), (1, 5, 2))
```

Can you please help me to solve this problem? I am using `mxnet-cu90 (1.4.1)` testing on 1080Ti. Thanks!

**Comment by nttstar** [comment]
It is slow only for the first time, warm up.

**Comment by kingsley851102** [comment]
i have this problem，have you solve the problem?

**Comment by mahxn0** [comment]
@nttstar @kingsley851102   如果输入图像的尺度在不断变化(图片来自目标检测抠出来的行人), 检测时间也变得很慢. 固定尺寸耗时15ms   尺寸变化每一帧都要500-1000ms左右   是不是哪个参数需要改  求指教

**Comment by rabysam28** [comment]
@nttstar why do we have this _count_ parameter to run a loop? it seems that it is operating on the same image multiple times.
