### ISSUE TITLE
threshold problem in RetinaFace/test_widerface.py

### ISSUE THREAD

**Issue by jiashu-zhu** [deepinsight/insightface#733]
Why the default threshold is 0.02?
  When I change it to 0.5 and run it to test R50 model, the mAP of Hard subset is just 84.9 which is far below 90.4(the author said)

**Comment by oftenliu** [comment]
同问？

**Comment by nlatuha** [comment]
Do you find answer?

**Comment by zhukkang** [comment]
for weiderface test , it is better to have more bbox for small face ,as will cause some error detect,
i test with 0.3 of R50 ,got easy 96.3 middle 95 and hard is 86.8
