### ISSUE TITLE
How to run on mobile phone ?

### ISSUE THREAD

**Issue by mdv3101** [deepinsight/insightface#734]
Hi,

I would like to run this repo on mobile phone ?
Is this possible ?

Thanks.

**Comment by mdv3101** [comment]
Any pointers for on device usage ?

**Comment by nttstar** [comment]
Model inference is easy, training on edge device is not much possible.

**Comment by Neltherion** [comment]
@nttstar How is Model Inference easy on an Android phone? is there a walkthrough for that ?

**Comment by mdv3101** [comment]
@nttstar 
Thanks for replying.

Can you share some insight on how to run MobileFaceNet model on an Android device ?

**Comment by dexception** [comment]
@nttstar Any updates for inference on Android ?

**Comment by ligbyte** [comment]
> @nttstar  I need the answer also!
> Thanks for replying.
> 
> Can you share some insight on how to run MobileFaceNet model on an Android device ?
