### ISSUE TITLE
如何用多机器多GPU进行分布式训练？

### ISSUE THREAD

**Issue by haoa060101** [deepinsight/insightface#735]
当ID数太多，训练时报GPU显存不够，有办法么？例如三千万ID。能改改recognition/train_parall.py，来支持多机器多GPU训练么？非常感谢！

**Comment by haoa060101** [comment]
我设置好多台机器免密ssh，配好hosts，改好config.py，再做如下操作，能实现多机器多GPU训练么？谢谢！
cp  parall_module_local_v1.py  parall_module_dist.py
launch.py -s 1 -n 2 --launcher ssh -H hosts CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train_parall.py --network r50 --loss softmax --dataset emore --per-batch-size 100  --kvstore dist_sync

**Comment by ZHAIXINGZHAIYUE** [comment]
@haoa060101 多机训练部分的代码，作者并没有上传。需要我们自己来搞

**Comment by haoa060101** [comment]
@nttstar 老大，有多机训练的代码么？上千万甚至上亿ID的那种，谢谢老大！

**Comment by nttstar** [comment]
暂不开源

**Comment by haoa060101** [comment]
@nttstar 好的，也谢谢老大呢

**Comment by ZHAIXINGZHAIYUE** [comment]
@nttstar 您好，多机训练时你是如何实现特征在不同机器上同步的？
