### ISSUE TITLE
Didn't find landmark annotations in wider face validation set in provided link.

### ISSUE THREAD

**Issue by YongtaoGe** [deepinsight/insightface#736]
In retinaface paper, the authors test five point landmarks accuracy on both aflw dataset and wider face validation dataset. But I did not find wider face validation dataset's landmark annotations in the given baiduyun link and dropbox link.

**Comment by fmbahrt** [comment]
According to the paper 18.5k faces has been annotated with facial landmarks in the WIDERFACE validation set. I would love to know if those are publicly available.

**Comment by lamhoangtung** [comment]
I'm having the same question :3

**Comment by aidansmyth95ifx** [comment]
I would love to know this too
