### ISSUE TITLE
new age gender model

### ISSUE THREAD

**Issue by zhly0** [deepinsight/insightface#737]
insightface's age gender model maybe the best model for asian in open source.
here is a new age gender model,comparing with insightface's:
https://www.youtube.com/watch?v=Bec7roJJHzY&feature=youtu.be

**Comment by nttstar** [comment]
It's a good demo.

**Comment by tranvansanghust** [comment]
Your model is so cool.
Can you share your it?

**Comment by zhly0** [comment]
@tranvansanghust ，Thanks for interests，but they are not open source now.maybe in the future.

**Comment by zhanglaplace** [comment]
@zhly0 看了下demo，似乎在中远距离的时候，识别出的年龄都非常的小，好像看到了一个3岁

**Comment by zhly0** [comment]
@zhanglaplace ，有两种情况，一种是确实有可能会将很小的人脸识别错，另一种是人脸较小时，人脸框上的年龄字体比较大，两位数字中右边的一位被性别字符给遮挡了。

**Comment by devin730** [comment]
@zhly0 效果很稳定，期待分享你research的idea :)

**Comment by nttstar** [comment]
@zhly0 发现一个问题，在你算法的视频流里面检测器更稳一点, 左边的人脸框更抖动, 这可能是造成年龄稳定度差异的主要原因

**Comment by zhly0** [comment]
@nttstar,insightface很强大，包括人脸检测,识别，基于insightface的人脸识别，开发了基于人脸识别的人脸属性识别，人脸属性不在抖动，一旦识别，基本不会再跳动，多人时fps>25，单人>30fps(检测+识别+关键点定位+属性识别+人脸选优，cpu i7-7700 3.6GHz):https://youtu.be/xYNr0JsDAQA

**Comment by devin730** [comment]
> 
> 
> @nttstar,使用基于人脸识别的属性识别，就没有稳定性问题了，基于insightface的人脸识别，开发了基于人脸识别的人脸属性识别，人脸属性不在抖动，一旦识别，基本不会再跳动，多人时fps>25，单人>30fps(检测+识别+关键点定位+属性识别+人脸选优，cpu i7-7700 3.6GHz):https://youtu.be/xYNr0JsDAQA

请问您有没有试过在ARM开发板上部署这一套人脸识别技术？目前，我正在有RK3399芯片的开发板上进行研发部署，如果也能达到您说的FPS，那才是真的很棒呢！：）

**Comment by zhly0** [comment]
@devin730,板上方案稍有区别，视觉体验一致,未进行板上移植，板上方案pc>100fps
