### ISSUE TITLE
fresnet resnet50

### ISSUE THREAD

**Issue by sukibean163** [deepinsight/insightface#740]
in fresnet.py resnet50 units = [3, 4, 14, 3] and  filter_list = [64, 64, 128, 256, 512], not the same to
 https://github.com/tornadomeet/ResNet/blob/master/symbol_resnet.py
and the paper:
Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun. "Identity Mappings in Deep Residual Networks", is there something wrong?

**Comment by buaazyz** [comment]
I have the same problem, this project just add 8  conv4_x based on resnet34 to get resnet50,  but I don't know why
