### ISSUE TITLE
Retinaface, py2 test.py,ImportError: No module named builtins

### ISSUE THREAD

**Issue by Wxsang** [deepinsight/insightface#744]
Thanks for your code.
pip install builtins 
ERROR: Could not find a version that satisfies the requirement builtins (from versions: none)
ERROR: No matching distribution found for builtins
i cant find any useful information.
thanks.

**Comment by Wxsang** [comment]
@nttstar

**Comment by EtheneXiang** [comment]
pip install future
@Wxsang

**Comment by EtheneXiang** [comment]
a new problem occurred:
ImportError: No module named anchors
i do not know how to deal with it

**Comment by zys1994** [comment]
@EtheneXiang  i have succeed deal with it,sharing with you
in generate_anchor.py add pyximport like this
```
import pyximport
pyximport.install()
from ..cython.anchors import anchors_cython
```

**Comment by EtheneXiang** [comment]
yeah,it works,thx @zys1994 
but there are many warnings,i do not know will those warnings  influence my training, those warnings:

/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/xxxx/insightface/RetinaFace/rcnn/cython/anchors.pyx

/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
