### ISSUE TITLE
the inference speed of retinaface

### ISSUE THREAD

**Issue by zyg11** [deepinsight/insightface#746]
GTX 1080
mobilenet0.25
I run test.py with the image (640*640）and found that the detect time is 120ms.
But I found the forward time is near 0.3ms. It's confused me. Is there any tricks to speed up detect time.?

**Comment by Neltherion** [comment]
@zyg11 The slowness happens AFTER the forward time where we're trying to use the network's output to find the exact location of faces. the Cython parts of the code speeds up the process a bit but overall I think this part needs the most optimization.

**Comment by zyg11** [comment]
I got it. Thanks !

**Comment by SongQingChe** [comment]
I cant download this mobilenet0.25 retinaface model, could you please give a download link? thanks@

**Comment by zyg11** [comment]
You can found it in the Third-party Models which made from yangfly!

**Comment by khanhnt** [comment]
> @zyg11 The slowness happens AFTER the forward time where we're trying to use the network's output to find the exact location of faces. the Cython parts of the code speeds up the process a bit but overall I think this part needs the most optimization.

No, the slowness happens exactly at the forward command, because the ndarray ops executes in asynchornous mode. if you add nd.waitall() just after forward (as bellow), you will see the inference time is about 3s, not 3ms as mentioned in the paper

**Comment by nttstar** [comment]
It is the warmup time cost. You should not include the first inference time for the performance test.

**Comment by khanhnt** [comment]
> It is the warmup time cost. You should not include the first inference time for the performance test.
Hi @nttstar, 
Is there any way to perform the warmup only one time to detect many images ?  It seems when I call the detect function, it will warmup again.

**Comment by edumucelli** [comment]
Experiencing same effect than @khanhnt

**Comment by zhengjiawen** [comment]
> > It is the warmup time cost. You should not include the first inference time for the performance test.
> 
> Hi @nttstar,
> Is there any way to perform the warmup only one time to detect many images ? It seems when I call the detect function, it will warmup again.

Hi @khanhnt , I encountered the same problem, have you soloved the problem?

**Comment by cannguyen275** [comment]
@zyg11 I faced the same issue. Did you solve it?

**Comment by mremise** [comment]
Same issue for me on GPU

**Comment by HeshanMountteen** [comment]
> > 这是预热时间成本。您不应包括性能测试的第一次推理时间。
> 
> 嗨@nttstar，
> 有没有办法只执行一次预热以检测许多图像？似乎当我调用检测功能时，它会再次预热。

use mx_float instead of ndarray
