### ISSUE TITLE
When run train_parall.py, acc and loss_value is nan

### ISSUE THREAD

**Issue by clhne** [deepinsight/insightface#747]
@nttstar 
Hi, nttstar
When run the train_parall.py, the acc and loss_value is nan:
INFO:root:Epoch[0] Batch [60-80]        Speed: 606.04 samples/sec       acc=nan lossvalue=nan
and I want to know the root cause of this.
Thanks.

**Comment by nttstar** [comment]
``train_parall.py`` should not output acc and lossvalue.

**Comment by clhne** [comment]
why train_parall.py should not output acc and lossvalue? Is it not implemented in the code?
Thanks.

**Comment by zfs1993** [comment]
hello, i wanna know how can i adjust the parameters without acc and lossvalue？
