### ISSUE TITLE
how to resume the training from a checkpoint for retinaface?

### ISSUE THREAD

**Issue by smarengin** [deepinsight/insightface#748]
I have reviewed the code and cannot find it? can anyone tell me how?thanks

**Comment by yjhuasheng** [comment]
Do you mean that you want to save model with some epoch?
I replace epoch_end_callback=checkpoint and set num_epoch=5. So I can save model with five epoch pre

**Comment by yjhuasheng** [comment]
Maybe you can set the value of begin_epoch?

**Comment by hanjw123** [comment]
@smarengin Have you resolved this problem？how to resume a trained model and continue to train?
I try to load my trained model, but get this " ValueError: Duplicate names detected".
thanks!

**Comment by WallZFE** [comment]
@hanjw123 hello，I have the same problem as you，Have you solved it？Thanks

**Comment by AnhVPB** [comment]
I have the same problem, anyone solved it?

**Comment by hanjw123** [comment]
@smarengin I'm not familiar with mxnet, so I simply replace my trained symbol.json file with the original pretrained symbol.json file to avoid duplicate names. Have you solved it in the code?

**Comment by hanjw123** [comment]
@WallZFE I'm not familiar with mxnet, so I simply replace my trained symbol.json file with the original pretrained symbol.json file to avoid duplicate names. Have you solved it in the code?

**Comment by WallZFE** [comment]
sorry,No solution was found

**Comment by vjsrinivas** [comment]
Are there any updates on this? I've been trying to do something similar to #932 but I keep getting this type of error: `ValueError: There are multiple outputs with name "_plus0_output"`

**Comment by faderani** [comment]
@vjsrinivas Did you manage to solve this problem?
