### ISSUE TITLE
change Retinaface training input size from square to rectangle

### ISSUE THREAD

**Issue by mochakai** [deepinsight/insightface#761]
Hello, thanks for your awesome code.

I'm trying to change the input size of training RetinaFace from square(640x640) to rectangle(320x480 for example) using resnet-50 pretrained model.

I changed the code of **get_sym_conv** function in **rcnn/symbol/symbol_common.py**

from
```
def get_sym_conv(data, sym):
    all_layers = sym.get_internals()

    isize = 640
    _, out_shape, _ = all_layers.infer_shape(data = (1,3,isize,isize))
...
   stride = isize//shape[2]
```
to
```
...
    isize = (320, 480)
    _, out_shape, _ = all_layers.infer_shape(data = (1,3,isize[0],isize[1]))
...
   stride = isize[0]//shape[2]
```
and **get_resnet_conv** function in **rcnn/symbol/symbol_resnet.py**

from
```
def get_resnet_conv(data, sym):
    all_layers = sym.get_internals()
    isize = 640
    _, out_shape, _ = all_layers.infer_shape(data = (1,3,isize,isize))
...
      if c1 is None and shape[2]==isize//16:
...
      if c2 is None and shape[2]==isize//32:
...
      if shape[2]==isize//32:
...
```

to
```
def get_resnet_conv(data, sym):
    all_layers = sym.get_internals()
    isize = (320, 480)
    _, out_shape, _ = all_layers.infer_shape(data = (1,3,isize[0],isize[1]))
...
      if c1 is None and shape[2]==isize[0]//16:
...
      if c2 is None and shape[2]==isize[0]//32:
...
      if shape[2]==isize[0]//32:
...
```
It works when I change the training param **config.SCALES** to (320, 320)

Besides above modification, I was wondering if there is other codes that I need to change?

I tried to change **max_data_shape** param in train_maskrcnn.py, train_rcnn.py, train_rpn.py, test_rcnn.py, test_rpn.py, but I have no idea how to change it. So I just change **config.SCALES** in training param.

What is the relationship between config.SCALES and my input size of network?

How to determine my config.SCALES? For my example, (320, 320) or (480, 480) or other?

**Comment by nttstar** [comment]
why you need this?

**Comment by mochakai** [comment]
Because I might need more flexible input in my future work, and it's associated with performance.

**Comment by nttstar** [comment]
Test size can be arbitrary. Just use training input-size=640.

**Comment by mochakai** [comment]
My training data & test data has an aspect ratio of 3:2 (length x height).
I want to accelerate inference speed, so I try to train a smaller and more suitable input size model.

**Comment by nttstar** [comment]
Model size is nothing related to the training input size.
