### ISSUE TITLE
Why no automated testing?

### ISSUE THREAD

**Issue by cclauss** [deepinsight/insightface#763]
There are multiple syntax errors in the codebase.  Why is there no automated testing on this repo?

**Comment by nttstar** [comment]
Please give me some error examples

**Comment by cclauss** [comment]
pip install [flake8](http://flake8.pycqa.org) ; flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

**Comment by nttstar** [comment]
Please show me the syntax errors directly.

**Comment by cclauss** [comment]
Focusing only on the __E9__ errors and only on legacy Python:
$ python2 -m flake8 . --count --select=E9 --show-source --statistics
```
./gender-age/add_age_rec.py:44:6: E999 IndentationError: unexpected indent
      stat[age_group] = 0
     ^
./gluon/blocks/embedding.py:29:39: E999 IndentationError: expected an indented block
    def __init__(self, args, **kwargs):
                                      ^
2     E999 IndentationError: unexpected indent
2
```
For other issues, change to __--select=E9,F63,F7,F82__ and also try on Python 3.

**Comment by nttstar** [comment]
OK, these files are hardly be used and I will clean them later, Thanks!
