### ISSUE TITLE
When running retinaface test_widerface.py, cudnn autotune repeats.

### ISSUE THREAD

**Issue by Edwardmark** [deepinsight/insightface#764]
src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)

And setting the MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 is not working, any clues?

**Comment by Edwardmark** [comment]
in the R50-symbol.json file, reset param cudnn_tune's value with "None" would help. the default value of cudnn_tune is limited_workspace.
in vim run：
:%s/\"cudnn_tune\": \"limited_workspace\"/\"cudnn_tune\": \"None\"/g
can solve the issure.

**Comment by hdjsjyl** [comment]
@Edwardmark , after replacing cudnn_tune:"None", my program still does not work. Do you have any other advice? Thanks

**Comment by Zheweiqiu** [comment]
Try replacing "cudnn_tune": "limited_workspace" with "cudnn_tune": "None" **AND** setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0. You need to do both to get rid of this issue.

**Comment by Edwardmark** [comment]
@Zheweiqiu you are totally right, thank you, guy!
