### ISSUE TITLE
rpn_fpn_ohem3 

### ISSUE THREAD

**Issue by yjhuasheng** [deepinsight/insightface#770]
I run the "test.py" with replacing trained model, I find the error: "Cannot find custom operator rpn_fpn_ohem3 ". 
Anyone can explain these?

**Comment by levotrea** [comment]
Hi @yjhuasheng,

I probably won't be able to help you with your issue, but to make it easier for others to identify what the problem could be, you should specify which test.py you tried to launch. Is it the test script for RetinaFace ?

You should also put the whole stack trace of the error, to see at which point of the execution it occured.

**Comment by nttstar** [comment]
The output symbols of your saved model are wrong.

**Comment by yjhuasheng** [comment]
Thank you very much, can you explain more clearly?

**Comment by yjhuasheng** [comment]
Sorry, I may not have expressed it clearly.
     I mean that I use "train.py" and wild datasets training, then I get the new file of params and json. But when I run test.py to test my model, I find the error: "Cannot find custom operator rpn_fpn_ohem3 ". 


Traceback (most recent call last):
  File "E:/face_references/Retinaface/Retinaface-master/test.py", line 16, in <module>
    detector = RetinaFace('./mnet.25/mx_mlp', 1, gpuid, 'net3')
  File "E:\face_references\Retinaface\Retinaface-master\retinaface.py", line 113, in __init__
    sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
  File "D:\Anaconda3\lib\site-packages\mxnet\model.py", line 437, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "D:\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 2620, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "D:\Anaconda3\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:01:58] C:\Jenkins\workspace\mxnet-tag\mxnet\src\operator\custom\custom.cc:104: Check failed: CustomOperator::Get()->Find(params.op_type) != nullptr Cannot find custom operator rpn_fpn_ohem3

**Comment by levotrea** [comment]
I found this github thread from the MXNet repository where they talk about a similar issue : [https://github.com/apache/incubator-mxnet/issues/8801](https://github.com/apache/incubator-mxnet/issues/8801).

So maybe try adding this import at the start of `retinaface.py` : `from rcnn.PY_OP import rpn_fpn_ohem3`.

Hope this helps.
