### ISSUE TITLE
jenkins file directory error / verification.py

### ISSUE THREAD

**Issue by seokhyeonSong** [deepinsight/insightface#771]
Hi, I'm a student who studies CV, deeplearning
Your work is so great and we study your work at university
I'm trying to open verification.py but directory error occurs..
This tries to access to your jenkins folder but it says that there's no such directory or files
The file i'm trying to open is ../model/softmax-symbol.json
It would be very thankful when you could answer..

**Comment by Talgin** [comment]
Hi @seokhyeonSong ,
Try choosing the whole path to directory where your model is stored, e.g. --model /home/ti/Downloads/insightface/models/model-r100-ii/model,0

Hope this helps. Good luck!
