### ISSUE TITLE
I found this github thread from the MXNet repository where they talk about a similar issue : [https://github.com/apache/incubator-mxnet/issues/8801](https://github.com/apache/incubator-mxnet/issues/8801).

### ISSUE THREAD

**Issue by yjhuasheng** [deepinsight/insightface#772]
I found this github thread from the MXNet repository where they talk about a similar issue : [https://github.com/apache/incubator-mxnet/issues/8801](https://github.com/apache/incubator-mxnet/issues/8801).

So maybe try adding this import at the start of `retinaface.py` : `from rcnn.PY_OP import rpn_fpn_ohem3`.

Hope this helps.

_Originally posted by @levotrea in https://github.com/deepinsight/insightface/issues/770#issuecomment-508521365_

**Comment by yjhuasheng** [comment]
you are right. Thank you very much

**Comment by levotrea** [comment]
Glad this helped :+1: 

(Did you mean to open an other issue though ? Or did you just want to close the previous one ?)
