### ISSUE TITLE
GridFace中思路如果应用的ArcFace中，会不会有提升？

### ISSUE THREAD

**Issue by lijinchao2007** [deepinsight/insightface#773]
GridFace的思路来源在STN。我看到STN就觉得可能可以应用到人脸检测阶段中。STN应用人脸方面的研究只搜到GridFace。但GridFace的STN思路不是应用在检测阶段，而是直接参与识别模型的训练。所以我就想如果引入到ArcFace中，会不会有效果？

**Comment by lijinchao2007** [comment]
而且 我看到新引入的RetinaFace检测，思路也是朝着矫正人脸的思路走。如果直接加入到识别阶段，应该会有提升吧？ @nttstar

**Comment by youthM** [comment]
hello,你有实现吗 @lijinchao2007

**Comment by lijinchao2007** [comment]
只是想想，没动手实验

**Comment by youthM** [comment]
> 只是想想，没动手实验
哦哦，GridFace是不是没开源？

**Comment by youthM** [comment]
> 只是想想，没动手实验

哦哦，GridFace是不是没开源？
