### ISSUE TITLE
Two or more faces in one image

### ISSUE THREAD

**Issue by syedmustafa54** [deepinsight/insightface#776]
@nttstar Hello,
I am trying to get two or more faces from one image and extract landmarks and print number of faces with mtcnn in `deploy/mtcnn_detector.py` when I am printing `print(total_boxes)` on [ line no](https://github.com/deepinsight/insightface/blob/master/deploy/mtcnn_detector.py#L513)   I am getting the output as `[[265.23931277 257.99892117 529.48574665 602.69352765   0.99998236]
 [554.60383058 311.6666975  579.33545327 341.22184038   0.97458839]]
` if there are two faces I am getting the same output 
I am running `deploy/test.py` how can I get two faces from one image

**Comment by khanhnt** [comment]
As mentioned in the detect_face funciton, the returned values are:   

> bboxes: numpy array, n x 5 (x1,y2,x2,y2,score)
>                 bboxes
> points: numpy array, n x 10 (x1, x2 ... x5, y1, y2 ..y5)
>               landmarks
So I think you just need get len of bboxes.

**Comment by syedmustafa54** [comment]
Solved it
