### ISSUE TITLE
问个小白的问题，一张图片多个人脸 如何获取每个人脸的特征呢

### ISSUE THREAD

**Issue by xxllp** [deepinsight/insightface#777]
看代码没有这个功能，每个有谁知道咋搞吗

**Comment by levotrea** [comment]
Hi @xxllp,

I'm sorry, I don't speak any chinese, but if I understood correctly from how Google translated your question, you want to know how to access the different characteristics of each face in a picture. (I'm guessing you are talking about face detected using Retinaface).

Did you take a look at the code of test.py ? In particular, at this section : 

```
for c in range(count):
  faces, landmarks = detector.detect(img, thresh, scales=scales, do_flip=flip)
  print(c, faces.shape, landmarks.shape)

if faces is not None:
  print('find', faces.shape[0], 'faces')
  for i in range(faces.shape[0]):
    #print('score', faces[i][4])
    box = faces[i].astype(np.int)
    #color = (255,0,0)
    color = (0,0,255)
    cv2.rectangle(img, (box[0], box[1]), (box[2], box[3]), color, 2)
    if landmarks is not None:
      landmark5 = landmarks[i].astype(np.int)
      #print(landmark.shape)
      for l in range(landmark5.shape[0]):
        color = (0,0,255)
        if l==0 or l==3:
          color = (0,255,0)
cv2.circle(img, (landmark5[l][0], landmark5[l][1]), 1, color, 2)
```

The `detect` function returns two objects : faces and landmarks.

`faces` is an list of 4-dimensional arrays, each array containing two pairs of (x,y) coordinates corresponding to the box containing a face (one pair for the upper left corner of the box, the other one for the bottom right corner if I'm not mistaken).

`landmarks` is list of 5-dimensional arrays, each containing 5 pairs of points, (x,y) coordinates for the landmarks of each detected face (the two eyes, the nose, and the two corners of the mouth).

So to access characteristics of the detected faces, you have to create two lists with a call to the `detect` function as done here `faces, landmarks = detector.detect(img, thresh, scales=scales, do_flip=flip)`, and then access the the characteristics by navigating through the two lists as done in the code above.

I hope I didn't misunderstood your question and that my answer helped you.

**Comment by xxllp** [comment]
thx ，but I want to get the feature of each face  use of the `model.make_feature` ,not get  landmarks

**Comment by levotrea** [comment]
Alright, I'm sorry that I can't be of any help then.

**Comment by cassie101** [comment]
The current code supports 1 face per image, check `ijbc_name_5pts_score.txt`, you could modify the  codes in the relevant part to handle feature extraction of multiple faces within an image.

**Comment by xxllp** [comment]
I  use  the code  in deloy  to slove it

**Comment by JackWolftoMc** [comment]
> I use the code in deloy to solve it

deloy下的py能做到你标题中描述的问题么

**Comment by xxllp** [comment]
稍微借用下代码就行了，我主要是要做个人脸库搜索

**Comment by DCC-lzhy** [comment]
I am sure what you say is about face representation, you can see https://github.com/deepinsight/insightface/blob/master/deploy/face_embedding.py

**Comment by HeshanMountteen** [comment]
当你不知道怎么做的时候，尝试打印函数的返回值。When u dont know how to solve it, try to print func's returned val
