### ISSUE TITLE
facescrub error images

### ISSUE THREAD

**Issue by auroua** [deepinsight/insightface#79]
I find lots of  images in `facescrub` datasets can't open correctly. The image have error, and can't open by software, like `Brianna Brown_10391.jpg`. The `facescrub_images_112x112.tar` dataset doesn't contain these images. Can you share the code that used to clean the error images?

**Comment by nttstar** [comment]
Error images are not required by MegaFace challenge.

**Comment by auroua** [comment]
I want to delete the error images, but I don't know the image names.
Where I can download the list about the error image names? Thanks!

**Comment by nttstar** [comment]
Why don't you output the names when they're corrupted? I'm not quite sure about this as facescrub images were aligned by J Deng.

**Comment by auroua** [comment]
OK, I will use the image names in your `facescrub_images_112x112.tar` file.
