### ISSUE TITLE
RetinaFace-R50  AP dismatch with  the report

### ISSUE THREAD

**Issue by ShoufaChen** [deepinsight/insightface#794]
Dose anyone run the `test.py` based on the released mode **RetinaFace-R50**  ([baidu cloud](https://pan.baidu.com/s/1C6nKq122gJxRhb37vK0_LQ) or [dropbox](https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0))

I ran this `test.py` and got the final results like follows:
```
[3222] recall 1.0 (32, 71) all: 0.858467975701
[3223] recall 1.0 (1, 2) all: 0.858471543076
[3224] recall 0.9473684210526315 (19, 46) all: 0.858514095684
[3225] recall 1.0 (4, 11) all: 0.858528352268
```
It shows the final over all result is about 0.858, which doesn't match with the reported :
```
WiderFace validation mAP: Easy 96.5, Medium 95.6, Hard 90.4.
```
Actually, it's belower than even the Hard result: 90.4 
Please note me if there is something I'm wrong.

**Comment by ShoufaChen** [comment]
I misunderstood the results.
The results of released  model `RetinaFace-R50` are same as the report.

**Comment by Li505358678** [comment]
@ShoufaChen  
Do you know how get map?
