### ISSUE TITLE
小白问题，麻烦帮忙看一下，如何解决？谢谢

### ISSUE THREAD

**Issue by 875798590** [deepinsight/insightface#796]
CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train.py --prefix ./model/mnet --network mnet
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from rcnn.symbol import *
  File "/opt/RetinaFace/rcnn/symbol/__init__.py", line 2, in <module>
    from .symbol_mnet import *
  File "/opt/RetinaFace/rcnn/symbol/symbol_mnet.py", line 9, in <module>
    from symbol_common import get_sym_train
ModuleNotFoundError: No module named 'symbol_common'

**Comment by jinghann** [comment]
请问你是怎么解决的呢?我也遇到了同样的问题

**Comment by TMaysGGS** [comment]
将symbol_mnet.py和symbol_resnet.py中的“from symbol_common import get_sym_train”改为“from rcnn.symbol.symbol_common import get_sym_train”。

Change the line "from symbol_common import get_sym_train" in symbol_mnet.py & symbol_resnet.py to "from rcnn.symbol.symbol_common import get_sym_train".
