### ISSUE TITLE
how to calculate accuracy on lfw

### ISSUE THREAD

**Issue by tejas35** [deepinsight/insightface#799]

**Comment by tejas35** [comment]
Please, reply asap.

**Comment by StevenLei2017** [comment]
part code of insightFace is copy of facenet project, facenet project has document which teach you calculate accuracy of lfw dataset, the document url:https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw
i used facenet project pretrained weights finished validation, you can put you model in right path and try it.
