### ISSUE TITLE
About face2rec2.py

### ISSUE THREAD

**Issue by meanmee** [deepinsight/insightface#80]
Hi, InsightFace is an awesome work and I want to use the codes to run my own data. So I use face2rec2.py to generate the .rec and .idx files, but it seems like something goes wrong, In my image lst file,there are around 12500000 samples, But when I use face2rec2.py to generate .rec and .idx files. It seems like the samples has been doubled:

time: 0.0756740570068  count: 25365000
time: 0.0772049427032  count: 25366000
time: 0.0759220123291  count: 25367000
time: 0.0757720470428  count: 25368000
time: 0.0775549411774  count: 25369000
time: 0.0764980316162  count: 25370000
time: 0.0752458572388  count: 25371000
time: 0.0749001502991  count: 25372000
time: 0.0766618251801  count: 25373000
time: 0.0772252082825  count: 25374000
time: 0.0776269435883  count: 25375000
time: 0.0763609409332  count: 25376000
time: 0.0765709877014  count: 25377000
time: 0.0757031440735  count: 25378000
time: 0.0767087936401  count: 25379000
time: 0.0764360427856  count: 25380000
wuxiaomin@taas5:~/code/SeetaBrushRanking/insightface/src/data$ ls -l -h

**Comment by nttstar** [comment]
Can you post some lines of your lst file here?

**Comment by meanmee** [comment]
1       /data/d/wxm/data/PAtrain/PAID_quwa_lf256_30Aug/PAID_quwa_lf256/242791/242791_wa_0_20.jpg        127056
1       /data/d/wxm/data/PAtrain/PAST2_train256_30Aug/PAST2_train256/200976/200976_lf_0_5_Aug.jpg       976
1       /data/d/wxm/data/PAtrain/PAST2_train256_30Aug/PAST2_train256/237092/237092_id_0_18.jpg  37092
1       /data/d/wxm/data/PAtrain/PAST2_train256_30Aug/PAST2_train256/265632/265632_lf_0_18.jpg  65632
1       /data/d/wxm/data/PAtrain/PAID_quwa_lf256_30Aug/PAID_quwa_lf256/112491/112491_lf_0_1_Aug.jpg     74828
1       /data/d/wxm/data/PAtrain/PAST2_train256_30Aug/PAST2_train256/256949/256949_lf_0.jpg     56949
1       /data/d/wxm/data/PAtrain/PAST2_train256_30Aug/PAST2_train256/221722/221722_lf_0_25.jpg  21722
1       /data/d/wxm/data/PAtrain/PAST2_train256_30Aug/PAST2_train256/237139/237139_lf_0_29.jpg  37139
1       /data/d/wxm/data/PAtrain/PAST2_train256_30Aug/PAST2_train256/225065/225065_id_0_20.jpg  25065
1       /data/d/wxm/data/PAtrain/PAID_quwa_lf256_30Aug/PAID_quwa_lf256/210284/210284_wa_0_7_Aug.jpg     113464
1       /data/d/wxm/data/PAtrain/PAST2_train256_30Aug/PAST2_train256/257578/257578_lf_0_7_Aug.jpg       57578
1       /data/d/wxm/data/PAtrain/PAID_quwa_lf256_30Aug/PAID_quwa_lf256/186392/186392_wa_0_6_Aug.jpg     104103
1       /data/d/wxm/data/PAtrain/PAST2_train256_30Aug/PAST2_train256/269416/269416_id_0_3_Aug.jpg       69416

**Comment by nttstar** [comment]
Please make sure that the 3rd column is label id(person_id). It should be identical for images from the same person.

**Comment by meanmee** [comment]
It is the label id the 3rd column in my lst file， It contains 180000 identities.

**Comment by nttstar** [comment]
You need to adjust the line order to ensure the images from same id is continuous. And also label id should start from 0.

**Comment by zhyj3038** [comment]
@meanmee    have you trained you data seccussfully?

**Comment by aitaoquanyi** [comment]
@nttstar I have the same problem. the images from same id muse be continuous? like 
idx  path label_x
idx  path label_x
idx  path label_x

**Comment by aitaoquanyi** [comment]
@nttstar the format of list is? can you add description? thanks

**Comment by nttstar** [comment]
Format:
1 img_path1 0
1 img_path2 0
...
1 img_path3 1
1 img_path4 1
....
...
1 img_path5 10000
1 img_path6 10000

The starting `1` indicates that this image is already aligned, it's not index.

**Comment by aitaoquanyi** [comment]
@nttstar get it,thanks!

**Comment by meanmee** [comment]
close this issue because it is solved：
Format:
1 img_path1 0
1 img_path2 0
...
1 img_path3 1
1 img_path4 1
....
...
1 img_path5 10000
1 img_path6 10000

The starting 1 indicates that this image is already aligned, it's not index.

**Comment by YuChenXiAn** [comment]
您的lst文件是如何生成的?

**Comment by chenkingwen** [comment]
I parse the MS1M .rec file to images folder, but when I use im2rec.py to make the .rec file, the size of .rec increase to 17GB.  Do you compress the image before the converting? thank you.@nttstar

**Comment by LCorleone** [comment]
@chenkingwen 
hi, i'm new to mxnet, could you share the code how to convert the rec file into images?
thank you!

**Comment by chenkingwen** [comment]
@LCorleone reference https://github.com/sirius-ai/MobileFaceNet_TF/blob/master/utils/data_process.py
