### ISSUE TITLE
For anchor num

### ISSUE THREAD

**Issue by lao-jiu** [deepinsight/insightface#806]
why is 102300 how to get it?

**Comment by ShoufaChen** [comment]
![retina](https://user-images.githubusercontent.com/28682908/61587300-5fbd0280-abba-11e9-8a2b-61871005e759.png)

Form this table, there are 5 heads, every pixel in every head will have 3 anchors,
so the number of total anchors is:
(160*160+80*80+40*40+20*20+10*10)*3 = 102300

**Comment by lao-jiu** [comment]
thank you !@ShoufaChen
