### ISSUE TITLE
大量特征进行比对，np.dot(fc1,fc2.T)是否有其他办法提升效率

### ISSUE THREAD

**Issue by wting861006** [deepinsight/insightface#812]
hi，大家好。我使用for循环调用100万次np.dot(fc1,fc2.T)，总共耗时3秒。如果我有大量特征需要进行比对（1：N），请问是否有其他方法可以提升这个效率?

**Comment by AmigoCDT** [comment]
如果是从100w特征中找一个或k个最接近的特征，这个是ANN问题，可以从下面这个repo中找一个方法试试。
[ann-benchmark](https://github.com/erikbern/ann-benchmarks)

**Comment by wting861006** [comment]
非常感谢，我试试。

**Comment by ZHAIXINGZHAIYUE** [comment]
也可以尝试使用cuda进行加速。

**Comment by wting861006** [comment]
我有大量的特征需要比对，cuda的显存可能会不够，我记得以前有一个哥们把cpu指令给优化了，比对的速度一秒钟300万左右，可惜优化cpu指令这活我干不了

**Comment by ZHAIXINGZHAIYUE** [comment]
@wting861006 显卡多的话可以把大矩阵拆分一下，放到不同的卡上

**Comment by wting861006** [comment]
我也是这么想的。现在在cpu上，我用python计算100万0.97秒左右的样子（不包括排序和similarity筛选），我试试看用c++能不能得到较大的提升，实在不行只能走多gpu拆分的路子了。

**Comment by endlesshh** [comment]
> hi，大家好。我使用for循环调用100万次np.dot(fc1,fc2.T)，总共耗时3秒。如果我有大量特征需要进行比对（1：N），请问是否有其他方法可以提升这个效率?

使用向量引擎去比对
