### ISSUE TITLE
Speed up  the whole process of retinaface inference ?

### ISSUE THREAD

**Issue by khanhnt** [deepinsight/insightface#817]
Hi,

I found that the whole process of  retinaface inference is quite slow, because the mxnet.ndarray operations execute in asynchronous mode. So that for the first time you run ndarray op (`scores = net_out[idx].asnumpy()` at line 221 of retinaface.py), GPU/CPU must wait for the other computations. Here, it seem that it wait for the foward command. 

Do you have any idea to change this by other one, in ordet to reduce the retinaface inference time ?

**Comment by fadybaly** [comment]
I'm facing the same issue here. on cpu it takes a few seconds for the first time it indexes the net_out, then it's near zero.
did u find a solution?

**Comment by khanhnt** [comment]
No, I still do not find the solution for process each image at time. But if you want to process a batch of images (many files), you can extract all images before perform any other computations. It will reduce the time, as recommened here [https://stackoverflow.com/questions/55572623/how-to-run-inference-on-an-image-classification-model-simultaneously-for-multipl](url)

**Comment by azmathussain76** [comment]
Also looking for a solution for this.  I'm trying to process live video, so I don't know the entire batch at the time of inference.  I'm hoping there is already a solution to this.
