### ISSUE TITLE
Some questions about remove_noises.py

### ISSUE THREAD

**Issue by taylover-pei** [deepinsight/insightface#82]
Hi! Congratulations, you have done a great work. I have some questions about the remove_noises.py.
![image](https://user-images.githubusercontent.com/27360803/37131526-ac34f1f8-22c3-11e8-8d5c-46fabe404435.png)
In this code, there are 'a' and 'b', because I can not see the '/raid5data/dplearn/megaface/facescrubr/small_lst' file, so what's the meaning of 'a' and 'b'?
Looking forward to you reply

**Comment by taylover-pei** [comment]
Sorry, I have solved the problem. But another problem appears.
What is your idea about remove the noises?
I saw that, in Facesrub, you just add one additional feature dimension. 
![image](https://user-images.githubusercontent.com/27360803/37135416-3c4abb74-22d8-11e8-84e0-655d63a0df9a.png)
While in Megaface, you did not do anything. 
![image](https://user-images.githubusercontent.com/27360803/37135428-48c08ffa-22d8-11e8-9937-41913ecb6ae5.png)
Is that right? So, why do you do that? Thank you.

**Comment by nttstar** [comment]
1. Use centre-vector to replace the noise images.
2. Keep L2-norm large enough between noisy distractors and all probe-set.
