### ISSUE TITLE
The similarity of features between abnormal faces was high.

### ISSUE THREAD

**Issue by Linzaer** [deepinsight/insightface#823]
Hi, @nttstar , this project is great and I have some questions to ask you.

If the two photos in the comparison are abnormal faces, such as very blurred faces, non-faces, and extreme side faces, their feature vectors will have a similar degree of similarity such as 70% or more (I guess because they don’t already have the characteristics of normal faces, so the inferred features are not comparable to the features of normal faces, but the feature vectors between non-face images will be similar). 

In the production environment, if the bottom library has unclean photos, and the front-end camera also accidentally pushes the undetected non-face photo, an error comparison will occur. In addition to ensuring the cleanliness of the database and improving the accuracy of camera face detection, what are the options for optimizing the face recognition model to avoid this problem?

Thank you! Looking forward to your favourable reply.

**Comment by westpilgrim** [comment]
hi ,have you solve this problem?

**Comment by Linzaer** [comment]
@westpilgrim Try to improve the accuracy of camera face detection.

**Comment by cesarandreslopez** [comment]
Sorry to reopen this @Linzaer but how does one increase the accuracy of camera face detection? Does this mean that one makes face detection more strict so it doesn't feed into abnormal faces?
