### ISSUE TITLE
Dense Regression Loss in RetinaFace

### ISSUE THREAD

**Issue by israelwei** [deepinsight/insightface#828]
Hi,
Thanks for your great contribution. I am a researcher that want to reproduce your results, but I didn't find in the code of RetinaFace project the Dense Regression Loss from the differentiable 3D mesh renderer. It seems its function is imported inside symbol_common: 
from rcnn.PY_OP import rpn_3d_mesh
but this file (rpn_3d_mesh) is missing in this repository. Is it possible to share this file publicly?
Also, is the pretrained model of Retinaface trained with this dense regression loss from the 3D mesh renderer?

**Comment by levotrea** [comment]
I think the question has already been answered in #687 .
