### ISSUE TITLE
Alignment problems in Deploy 

### ISSUE THREAD

**Issue by eladrich** [deepinsight/insightface#83]
Hi,
I've been trying to use the deploy/test.py script on two easy examples from LFW, but encountered several problems. 

First, the predefined threshold does not pass any of the images. Now, even when reducing the threshold the cosine similarity is really low (~0.1).

Looking at the images fed into the network 
it seems like there is a problem with the MTCNN alignment, the images are badly cropped, and look different from the images inside the LFW verification bin.

Any ideas?

**Comment by Wisgon** [comment]
I use pyseeta to alignment see #68

**Comment by zhyj3038** [comment]
i replace the mxnet version mtcnn with dlib to detect face

**Comment by eladrich** [comment]
The thing is using a different alignment process than used during training could result in performance drop, so I would still like to use the original process.

**Comment by nttstar** [comment]
Hi all, my scripts under `deploy/` is a toy example which suppose that you already have a face detector to crop the face from raw image. MTCNN can also be used as a face detector.

**Comment by eladrich** [comment]
@nttstar, so which detector did you use for generating the training data? Is the alignment code the same?

**Comment by nttstar** [comment]
Yes, MTCNN for training dataset.

**Comment by eladrich** [comment]
OK, great :-)
What's the purpose of detect_face_limited? Because using the original detect_face seems to solve the problem with the detection.

**Comment by nttstar** [comment]
Yes, right. My previous idea was to allow third-party face detectors.

**Comment by tinatiant** [comment]
how to use dlib  in face_embedding.py? could u display the code please？

**Comment by tinatiant** [comment]
@zhyj3038

**Comment by stereomatchingkiss** [comment]
I use dlib to detect and align face too(mmod face detector and shape_predictor_5_face_landmarks), would this bring serious performance degradation?
