### ISSUE TITLE
loss不变了

### ISSUE THREAD

**Issue by U-ft** [deepinsight/insightface#834]
我用adam在vggface2上训练，逐渐衰减lr到0.001，模型的loss衰减到1.45几乎不再变化了（8631分类的training acc在81%。）感觉很迷惑，这是遇到极值点了吗。我应该怎样避免呢。

还是说这个时候模型的性能已经很好了，对图像对进行test能达到比较高的精度（>90%）？

**Comment by a26908456** [comment]
你的training acc是在training過程輸出的那些嗎?
那個準確率是用處理過margin softmax的output去計算的，
例如選cosine face，gt_label的那個人的在算softmax值之前已經被扣了m3，
所以算softmax出來的機率會變得比較低，
這樣就會變得比較不準，但這只是training用的，
因此training時輸出的那個acc是被低估的，實際上應該會更高，
而真的要測準確率應該要用還沒扣m3的去算。

**Comment by FaceGg** [comment]
> 我用adam在vggface2上训练，逐渐衰减lr到0.001，模型的loss衰减到1.45几乎不再变化了（8631分类的training acc在81%。）感觉很迷惑，这是遇到极值点了吗。我应该怎样避免呢。
> 还是说这个时候模型的性能已经很好了，对图像对进行test能达到比较高的精度（>90%）？

要看你用的哪个损失函数。如果是softmax ，那应该这个模型就是这样了，提升空间不大。要是用softmax的那几个变种，loss和acc是有惩罚的，不是实际中用的衡量标准，比咱们正常用的softmax低。
