### ISSUE TITLE
retinaface finds repetitive faces

### ISSUE THREAD

**Issue by taninaim** [deepinsight/insightface#835]
I'm running RetinaFace/test.py (with default settings + the pretrained model) and it found 153 faces in a picture of 6 faces. Turned out that it's drawing multiple bounding boxes on the same face. What may be going wrong? 
<img width="600" alt="Screen Shot 2562-08-05 at 23 28 50" src="https://user-images.githubusercontent.com/7446985/62481084-a6764380-b7db-11e9-8c5f-b2d918cd1e7f.png">

**Comment by nnnnew** [comment]
I think you should update your Nvidia driver.

**Comment by ngoquocquang** [comment]
I'm running RetinaFace/test.py but I don't know to solve the error: https://github.com/deepinsight/insightface/issues/870
help me, please. I can't run this code for a week. Please.

**Comment by nmnhut0208** [comment]
> I'm running RetinaFace/test.py but I don't know to solve the error: #870
> help me, please. I can't run this code for a week. Please.

a ơi cho em xin fb a Dc k ạ em còn vài thắc mắc khi train RetinaFace

**Comment by zoezhou1999** [comment]
I have the same problem.. How can I solve it? Thank you so much!
