### ISSUE TITLE
RetinaFace人脸检测速度问题

### ISSUE THREAD

**Issue by safehumeng** [deepinsight/insightface#839]
麻烦咨询一下关于RetinaFace检测速度问题，使用项目中提供的RetinaFace代码，模型使用的是项目提供的基于ResNet50训练模型，使用的gpu是Tesla P100，同一张图片第一次预测时间是
![image](https://user-images.githubusercontent.com/16226299/62589787-ee40bc00-b8fc-11e9-8f5d-a80bf39c9667.png)第二次预测时间是
![image](https://user-images.githubusercontent.com/16226299/62591419-17b01680-b902-11e9-8d62-97776a0768fa.png)
不同的照片第一次预测都是一样都时间

**Comment by safehumeng** [comment]
把图片resize到同一大小就可以加速了，请问一下在使用到时候是resize到长边640然后短边padding好呢还是直接rezie到固定大小好呢

**Comment by Zheweiqiu** [comment]
> 把图片resize到同一大小就可以加速了，请问一下在使用到时候是resize到长边640然后短边padding好呢还是直接rezie到固定大小好呢

长边640，短边等比例放缩然后padding吧，不然人脸变形监测可能不准。
