### ISSUE TITLE
mxnet.base.MXNetError:   .........        expected [64], got [32]

### ISSUE THREAD

**Issue by 2151330** [deepinsight/insightface#843]
When I run recongnition /train.py,this question occured,I don't know the reason,Can you help me?
 The parameters I set are as follows:
CUDA_VISIBLE_DEVICES='0' python -u train.py --network y1   --lr 0.005 --per-batch-size 80  --ckpt 2  --pretrained /home/mi5/insightface/models/model-y1/models  --models-root ../models/model-y1-7
![image](https://user-images.githubusercontent.com/41284417/62750301-3fce7f80-ba92-11e9-9611-3bb4a5ca0979.png)

**Comment by mehrdadazizi72** [comment]
@2151330 check your embedding size, it should be same
