### ISSUE TITLE
ijbc test question

### ISSUE THREAD

**Issue by shiyuanyin** [deepinsight/insightface#844]
Methods                             | 1e-06  | 1e-05  | 0.0001 | 0.001  |  0.01  |  0.1   |
+----------------------------------------------------------------+--------+--------+--------+--------+--------+--------+
|          glint-Mobilefacenet     | 0.5317 | 0.7009 | 0.8463 | 0.9272 | 0.9667 | 0.9867 |
|            glint-ResNet50           | 0.8722 | 0.9262 | 0.9501 | 0.9673 | 0.9803 | 0.9892 |
**|          glint_vggfine_res50     | 0.0021 | 0.0986 | 0.6721 | 0.9003 | 0.9731 | 0.9898 |**

请问你碰到过这个现象吗
ijbc 测试中代码我没有更改，只是换了模型读取，far 1e-06 1e-05 出现断崖式减少，请问是可能是什么原因吗，我总觉得有错误，但是我只是改动了模型的读取路径
@jiankangdeng 
@nttstar

**Comment by njtuzzy** [comment]
@ shiyuanyin did you find the reason?
