### ISSUE TITLE
face alignment retinaface or mtcnn?

### ISSUE THREAD

**Issue by HuanJiML** [deepinsight/insightface#846]
@nttstar 
* Are the all datasets availabe from this repo is aligned by mtcnn or retinaface?
* if the datasets are aligned with mtcnn, retinaface should be used only for inference?
* During the inference, should we use mtcnn or retinaface?

**Comment by BeginnerW** [comment]
@HuanJiML did you figure it out?
Is there a difference recognition performance between mtcnn and retinaface?

**Comment by chenghan1995** [comment]
Hello, how to get the dataset ms1m-retinaface-t1 ?

**Comment by clhne** [comment]
@chenghan1995 t1 is not in this repo.
