### ISSUE TITLE
does similarity transform matrix depend on the image size?

### ISSUE THREAD

**Issue by vkasojhaa** [deepinsight/insightface#849]
I am trying to align image with different size (182x182) but I am not getting good results. The alignment looks good if I pass the default image_size (112x112). So, I am wondering if the
`

      src = np.array([
      [30.2946, 51.6963],
      [65.5318, 51.5014],
      [48.0252, 71.7366],
      [33.5493, 92.3655],
      [62.7299, 92.2041] ], dtype=np.float32 )

    if image_size[1]==112:
      src[:,0] += 8.0`
matrix given is for 112x112 images only,

**Comment by mlourencoeb** [comment]
The reference points are dimensioned for 112x112 output.

**Comment by vkasojhaa** [comment]
@mlourencoeb can you explain more about rescaling the values according to the input size. Do you mean like adding constants to the matrix like done in the code like this?
`if image_size[1]==112:
        src[:,0] += 8.0`

**Comment by mlourencoeb** [comment]
Not really. After that line where the shift is applied all you needed to do is:

src = src * 182/ 112

**Comment by mlourencoeb** [comment]
Don't forget to close the issue if your  question has been answered.

**Comment by vkasojhaa** [comment]
@mlourencoeb Thank you, rescaling the values like you told resolved the issue.
