### ISSUE TITLE
train with my own data set

### ISSUE THREAD

**Issue by 2151330** [deepinsight/insightface#854]
I tested with my own data set, with 30,000 pairs of positive and negative samples respectively. This problem occurred when running train.py. Could you help me？
![image](https://user-images.githubusercontent.com/41284417/62986371-d70a4d00-be6d-11e9-8df7-95c8d3134ca2.png)

**Comment by minhdc** [comment]
@2151330 could you specify how did you create your own training set?

**Comment by hande6688** [comment]
@2151330 The format tool uses labelme, and the format is json. How to convert your face data set into a more extensive format described by the author for training? I also want to consult this question？
