### ISSUE TITLE
Why I better result on WiderFace val set, but detect less faces on 'Worlds Largest Selfie'?

### ISSUE THREAD

**Issue by jiashu-zhu** [deepinsight/insightface#857]
Hi @nttstar  ,thanks for the great work and for the effort of sharing it here.

1. I use stride[4, 8, 16, 32, 64] with mobilenet0.25 backbone on retinaface,and get 0.928, 0.918, 0.833 on widerface easy, medium, hard set respectively, which is a better result than just using stride [8, 16, 32]. But I can detect 150 less faces than just using stride [8, 16, 32].
  I can't figure out why.

2. Why I get worse result with using dense anchor on 'World Largest Selfie'?
  I just add dense anchor, but detect 100 less faces than not using dense anchor, and the minimum face I can detect became bigger

Looking forward to your reply
Thanks in advance

**Comment by Liuqiyuan670** [comment]
hello,i also trained a mobilenet0.25 model ,however ,my test  process reported an error，could you tell me how you teat your model .
