### ISSUE TITLE
retina-R50 model to onnx

### ISSUE THREAD

**Issue by Zheweiqiu** [deepinsight/insightface#858]
Hi,
I tried to convert retina-R50 model to onnx following http://mxnet.incubator.apache.org/versions/master/tutorials/onnx/export_mxnet_to_onnx.html instruction. But I got an error. I also tried insightface model and everything just worked. Do you have any idea how that happens?
Any help will be appreciate!

**Comment by 17702513221** [comment]
Please tell me can you result this problem?

**Comment by 17702513221** [comment]
I get a error :No conversion function registered for op type SoftmaxActivation yet
Can you help me

**Comment by Zheweiqiu** [comment]
@17702513221 https://github.com/apache/incubator-mxnet/issues/15892. https://github.com/cholihao/Retinaface-caffe/issues/4, check these two out for reference.

**Comment by luan1412167** [comment]
@17702513221 do you resolve it?

**Comment by HoiM** [comment]
I was trying to convert the model to onnx. Firstly I also encountered this problem but revising the json file by changing SoftmaxActivation to softmax can erase this error. However, after that, a new problem occured. It seemed that onnx did not support upsampling. So I currently don't know what to do next.

**Comment by xingha** [comment]
@HoiM I meet the same problem, did you have solved it?

**Comment by SehgalDivij** [comment]
Likewise. Same problem is still there even though it was taken up few months back and a PR was added as well.

**Comment by zheshipinyinMc** [comment]
https://github.com/zheshipinyinMc/arcface_retinaface_mxnet2onnx
https://zhuanlan.zhihu.com/p/166267806

**Comment by nadaboulares** [comment]
how to test recognition of onnx file model??
