### ISSUE TITLE
MS1M-IBUG和MS1M-ArcFace有什么区别？

### ISSUE THREAD

**Issue by blueapplehe** [deepinsight/insightface#860]
MS1M-IBUG和MS1M-ArcFace有什么区别？

**Comment by taoxunqiang** [comment]
都是清洗的MS1M，可能清洗的方法和力度不一样。
MS1M-IBUG又叫MS1M-v1。
MS1M-ArcFace又叫MS1M-v2。
实际训练的时候MS1M-ArcFace训练性能要高。
