### ISSUE TITLE
recognition speed

### ISSUE THREAD

**Issue by mehrdadazizi72** [deepinsight/insightface#864]
@nttstar thanks for your great work.
I tried to feed batch to
https://github.com/deepinsight/insightface/blob/5aa877e1ac861bbe6fb1e1f2002bd9d1351bca5f/deploy/face_model.py#L90
but in the speed of model compared to a single image not change.
why this is happening?

**Comment by Reddyforcode** [comment]
is normal that the first time that you compare tho images, takes a while because of the model loading time, from the second comparison is where you can be worry about
