### ISSUE TITLE
The Dataset

### ISSUE THREAD

**Issue by Jimzhou82sub** [deepinsight/insightface#865]
Hi, I'm inspired when I read your code, but I can't get the MS1MV2 and DeepGlint-Face , Could you sent the download link to me, my email is 1607625471@qq.com. Thanx !

**Comment by taoxunqiang** [comment]
Actually, the authors have provided the download link in Dataset-Zoo: https://github.com/deepinsight/insightface/wiki/Dataset-Zoo
MS1MV2 is MS1M-ArcFace (85K ids/5.8M images) [5,7] (Recommend);
DeepGlint-Face is DeepGlint (181K ids/6.75M images) [8] (Recommend).
