### ISSUE TITLE
LResnet100-IR trained from scratch on cpu inference time is too slow(从头训练的模型，CPU推理速度太慢)

### ISSUE THREAD

**Issue by asonee** [deepinsight/insightface#866]
hey, when I trained LResnet100-IR on glintasia dataset from scratch, the cpu inference time is aroud 8 seconds, but when i fintune same model on glintasia dataset from pretrained  LResnet100-IR（download from BaiduYun）, the cpu inference time is arourd 300 ms， I am wondering why? Any help will be appreciate!
(当在glintasia数据集上从头训练LResnet100E-IR 和 利用百度云上的LResnet100E-IR 在数据集上finetune得到的模型，他们在cpu上的推理速度相差非常大，分别是8秒中和300毫秒，非常奇怪, 困扰了我很久了，有人知道原因吗? 非常感谢！）

**Comment by asonee** [comment]
besides,  model trained from scratch and model from  fintune,  gpu inference time is nearly same. (另外，从头训练的模型和finetune得到的模型，他们在gpu上推理的时间是相同的，没有差异)

**Comment by szad670401** [comment]
related issue.[#637](https://github.com/deepinsight/insightface/issues/637)
