### ISSUE TITLE
请问在src/image_iter.py里面有很多数据增广函数，为什么这些函数都没有使用？

### ISSUE THREAD

**Issue by AmigoCDT** [deepinsight/insightface#869]
如题。
请问是因为增广后会导致数据量膨胀，训练速度变慢吗？还是其它什么原因？

**Comment by FaceGg** [comment]
> 如题。
> 请问是因为增广后会导致数据量膨胀，训练速度变慢吗？还是其它什么原因？

数据增强不是任何情况下都有意义，尤其是数据量足够的时候
