### ISSUE TITLE
how to finetune

### ISSUE THREAD

**Issue by zhyj3038** [deepinsight/insightface#87]
Appreciate for you goog work!  first I train on ms1m dataset until acc is 90% on train dataset.  then I  wan to finetune on my own data. I have make the *.rec and *.idx.  but when I begun to finetune, the program load the pr-trained model, and crash. warning that the number of my dataset classes is not equeal to the ms1m.  it seems we should freezen the FC layer.

is your code offer the function of finetuneing?

**Comment by nttstar** [comment]
Which algorithm(loss) did you use when doing finetuning?

**Comment by zhyj3038** [comment]
CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train_softmax.py \
--network r100 \
--loss-type 4 \
--margin-m 0.5 \
--prefix ../model-r100 \
--pretrained '../model-r100, 287' > ../model-r100.log 2>&1 &   


  I use ArchLoss

**Comment by zhyj3038** [comment]
now I have added some code according to the official finetune example.  but when I load the pre-trained model and new dataset, error occurs saying: out of memory!

**Comment by nttstar** [comment]
Have to discard the weight of fc7 layer, as the number of output is not the same.

**Comment by zhyj3038** [comment]
I have  done it hours ago, but not quite sure. because the acc on new train dataset starts from 0,  there maybe somethings else wrong.

**Comment by oukohou** [comment]
@myfighterforever  Using deploy/model_slim.py, as is named, this script can slim model.
Just in case you need it still.
