### ISSUE TITLE
why train ArcFace with LResNet100E-IR can not found train.rec?

### ISSUE THREAD

**Issue by CL1432** [deepinsight/insightface#873]
execute 
`CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train.py --network r100 --loss arcface --dataset emore`
Error prompted
`raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:09:27] src/io/local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "home/cl/insightface/datasets/faces_emore/train.rec": No such file or directory
`
But the file exists in this path

**Comment by zzj0402** [comment]
How did you resolve it?

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md
