### ISSUE TITLE
请问为什么在使用LResNet100E-IR训练ArcFace时报错找不到train.rec

### ISSUE THREAD

**Issue by CL1432** [deepinsight/insightface#874]
执行此语句后
`CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train.py --network r100 --loss arcface --dataset emore`
提示错误：
`raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:09:27] src/io/local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "home/cl/insightface/datasets/faces_emore/train.rec": No such file or directory
`
但是train.rec文件的目录检查过没有问题，为什么会报错呢？

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md
