### ISSUE TITLE
Image normalization 

### ISSUE THREAD

**Issue by srinivasnisha** [deepinsight/insightface#875]
For image normalization shouldn't the formula be (pixel_val-127.5/127.5) instead of (pixel_val-127.5/128) ?

or is the standard deviation calculated = 128?

What does 128 represent? I understand that 127.5 represents the mean value of pixel if the pixel values range from [0,255].

**Comment by ngoquocquang** [comment]
can you help me? https://github.com/deepinsight/insightface/issues/870
