### ISSUE TITLE
RetinaFace train batch size

### ISSUE THREAD

**Issue by skyeyeCV** [deepinsight/insightface#876]
In the RetinaFace config.py file,the default setting of  mnet train batch size is 16 and resnet train batch size is 8,why use so small batch size？ Can I use batch size of 128 or even bigger to get better training result when the memory of GPU is enough?

**Comment by ngoquocquang** [comment]
can you run test.py file? i am running it, have error: https://github.com/deepinsight/insightface/issues/870
can you help me? please
