### ISSUE TITLE
Joining two datasets and custom dataset dir2rec code

### ISSUE THREAD

**Issue by vizakshat** [deepinsight/insightface#878]
I wanted to know how can I join two datasets given in the data zoo.
I also wanted to know if there is anything else that needs to be done if my dataset is containing only two images per person and the files are being created via custom for-loops in dir_to_rec.py file.
I have labeled the data as 0,0,1,1,2,2,3,3, ... 
While training the accuracy and loss values are shown to be zero forever. r100, arc face loss

Attached is my custom dir2rec and build_

[build_eval.txt](https://github.com/deepinsight/insightface/files/3540293/build_eval.txt)
[dir2rec.txt](https://github.com/deepinsight/insightface/files/3540294/dir2rec.txt)

eval code, images are pre-cropped via MTCNN:

**Comment by Cocoalate** [comment]
Hi, I'm wondering which two datasets you are using and what are they like. I'm trying to merge vggface2 and deepglint datasets together as my training data. Any suggestions?

**Comment by Bruce-GuoS** [comment]
> Hi, I'm wondering which two datasets you are using and what are they like. I'm trying to merge vggface2 and deepglint datasets together as my training data. Any suggestions?

Have you successfully merged vggface2 and deepglint datasets together?  How big is the dataset? How many IDs and images? Thank you.

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md
