### ISSUE TITLE
Loss Function Error

### ISSUE THREAD

**Issue by taylover-pei** [deepinsight/insightface#88]
I use the Center Loss Function of yours. But when I run my code, some errors show like this:

[21:05:56] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [21:05:56] src/pass/gradient.cc:159: Check failed: (*rit)->inputs.size() == input_grads.size() (5 vs. 2) Gradient function not returning enough gradient

Stack trace returned 10 entries:
[bt] (0) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7f4206bef7cc]
[bt] (1) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2d67afa) [0x7f4209781afa]
[bt] (2) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xf9aa1f) [0x7f42079b4a1f]
[bt] (3) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2d58f78) [0x7f4209772f78]
[bt] (4) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe0fcae) [0x7f4207829cae]
[bt] (5) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe6bfe5) [0x7f4207885fe5]
[bt] (6) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5a8d8) [0x7f42078748d8]
[bt] (7) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5b28f) [0x7f420787528f]
[bt] (8) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5cfd0) [0x7f4207876fd0]
[bt] (9) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5dcd4) [0x7f4207877cd4]

/home/jiayunpei/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL
=======train model========
Traceback (most recent call last):
  File "/home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/symbol.py", line 1473, in simple_bind
    ctypes.byref(exe_handle)))
  File "/home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/base.py", line 129, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:05:56] src/pass/gradient.cc:159: Check failed: (*rit)->inputs.size() == input_grads.size() (5 vs. 2) Gradient function not returning enough gradient

Stack trace returned 10 entries:
[bt] (0) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7f4206bef7cc]
[bt] (1) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2d67afa) [0x7f4209781afa]
[bt] (2) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xf9aa1f) [0x7f42079b4a1f]
[bt] (3) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2d58f78) [0x7f4209772f78]
[bt] (4) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe0fcae) [0x7f4207829cae]
[bt] (5) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe6bfe5) [0x7f4207885fe5]
[bt] (6) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5a8d8) [0x7f42078748d8]
[bt] (7) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5b28f) [0x7f420787528f]
[bt] (8) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5cfd0) [0x7f4207876fd0]
[bt] (9) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5dcd4) [0x7f4207877cd4]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiayunpei/mxnet_train/megaface_symbol/resnet_50/train.py", line 17, in <module>
    softmax_label=(int(cfg.batch_size / len(cfg.gpus)),))
  File "/home/jiayunpei/mxnet_train/megaface_symbol/resnet_50/memonger.py", line 132, in search_plan
    cost = get_cost(sym, type_dict, **kwargs)
  File "/home/jiayunpei/mxnet_train/megaface_symbol/resnet_50/memonger.py", line 110, in get_cost
    **kwargs)
  File "/home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/symbol.py", line 1479, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (65, 3, 248, 248)
softmax_label: (65,)
[21:05:56] src/pass/gradient.cc:159: Check failed: (*rit)->inputs.size() == input_grads.size() (5 vs. 2) Gradient function not returning enough gradient

Stack trace returned 10 entries:
[bt] (0) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7f4206bef7cc]
[bt] (1) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2d67afa) [0x7f4209781afa]
[bt] (2) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xf9aa1f) [0x7f42079b4a1f]
[bt] (3) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2d58f78) [0x7f4209772f78]
[bt] (4) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe0fcae) [0x7f4207829cae]
[bt] (5) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe6bfe5) [0x7f4207885fe5]
[bt] (6) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5a8d8) [0x7f42078748d8]
[bt] (7) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5b28f) [0x7f420787528f]
[bt] (8) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5cfd0) [0x7f4207876fd0]
[bt] (9) /home/jiayunpei/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xe5dcd4) [0x7f4207877cd4]

Do you know why is that?
Thanks for you replying.

**Comment by nttstar** [comment]
Do not use center-loss, it's not fully tested.
