### ISSUE TITLE
Error in training : ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by vizakshat** [deepinsight/insightface#880]
Using Python3.6, arcface loss, r34 architecture.

INFO:root:Epoch[0] Batch [41820-41840]  Speed: 204.01 samples/sec       acc=0.991797    lossvalue=4.493365
INFO:root:Epoch[0] Batch [41840-41860]  Speed: 204.65 samples/sec       acc=0.991797    lossvalue=4.486666
INFO:root:Epoch[0] Batch [41860-41880]  Speed: 203.98 samples/sec       acc=0.992188    lossvalue=4.490592
INFO:root:Epoch[0] Batch [41880-41900]  Speed: 204.16 samples/sec       acc=0.992188    lossvalue=4.476994
INFO:root:Epoch[0] Batch [41900-41920]  Speed: 204.53 samples/sec       acc=0.991797    lossvalue=4.494334
INFO:root:Epoch[0] Batch [41920-41940]  Speed: 207.40 samples/sec       acc=0.991797    lossvalue=4.485728
INFO:root:Epoch[0] Batch [41940-41960]  Speed: 205.71 samples/sec       acc=0.942578    lossvalue=nan
INFO:root:Epoch[0] Batch [41960-41980]  Speed: 206.47 samples/sec       acc=0.000000    lossvalue=nan
lr-batch-epoch: 0.001 41999 0
testing verification..
Traceback (most recent call last):
  File "train.py", line 377, in <module>
    main()
  File "train.py", line 374, in main
    train_net(args)
  File "train.py", line 369, in train_net
    epoch_end_callback = epoch_cb )
  File "/usr/local/lib/python3.6/dist-packages/mxnet/module/base_module.py", line 560, in fit
    callback(batch_end_params)
  File "train.py", line 305, in _batch_callback
    acc_list = ver_test(mbatch)
  File "train.py", line 274, in ver_test
    acc1, std1, acc2, std2, xnorm, embeddings_list = verification.test(ver_list[i], model, args.batch_size, 10, None, None)
  File "eval/verification.py", line 272, in test
    embeddings = sklearn.preprocessing.normalize(embeddings)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py", line 1614, in normalize
    estimator='the normalize function', dtype=FLOAT_DTYPES)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by mohuazheliu** [comment]
I have the same error,Could you tell me how to solve it?

**Comment by Vietdung113** [comment]
anyone solved it?

**Comment by RunningLeon** [comment]
Same werid problem when training fmobilenet with lr=0.001 on face_emore dataset.
lossvalue is NaN and validation on lfw is worse than random guess.
lr-batch-epoch: 0.001 9627 1
testing verification..
(12000, 128)
infer time 4.288807
[calfw][21000]XNorm: 7.012466
[calfw][21000]Accuracy-Flip: 0.50167+-0.00307
testing verification..
(12000, 128)
infer time 4.351312
[lfw][21000]XNorm: 5.910034
[lfw][21000]Accuracy-Flip: 0.49950+-0.00248

INFO:root:Epoch[1] Batch [10160-10180]  Speed: 1118.20 samples/sec      acc=0.989160    lossvalue=4.304033
INFO:root:Epoch[1] Batch [10180-10200]  Speed: 1104.27 samples/sec      acc=0.988965    lossvalue=4.292909
INFO:root:Epoch[1] Batch [10200-10220]  Speed: 1134.59 samples/sec      acc=0.989160    lossvalue=4.281045
INFO:root:Epoch[1] Batch [10220-10240]  Speed: 1134.25 samples/sec      acc=0.989453    lossvalue=4.301128
INFO:root:Epoch[1] Batch [10240-10260]  Speed: 1129.99 samples/sec      acc=0.296582    lossvalue=nan
INFO:root:Epoch[1] Batch [10260-10280]  Speed: 1123.79 samples/sec      acc=0.000000    lossvalue=nan
INFO:root:Epoch[1] Batch [10280-10300]  Speed: 1086.07 samples/sec      acc=0.000000    lossvalue=nan
INFO:root:Epoch[1] Batch [10300-10320]  Speed: 1132.76 samples/sec      acc=0.000000    lossvalue=nan

**Comment by ccsone** [comment]
@ChienWong  have u solved it ?

**Comment by xuyingzhongguo** [comment]
> Same werid problem when training fmobilenet with lr=0.001 on face_emore dataset.
> lossvalue is NaN and validation on lfw is worse than random guess.
> lr-batch-epoch: 0.001 9627 1
> testing verification..
> (12000, 128)
> infer time 4.288807
> [calfw][21000]XNorm: 7.012466
> [calfw][21000]Accuracy-Flip: 0.50167+-0.00307
> testing verification..
> (12000, 128)
> infer time 4.351312
> [lfw][21000]XNorm: 5.910034
> [lfw][21000]Accuracy-Flip: 0.49950+-0.00248
> 
> INFO:root:Epoch[1] Batch [10160-10180] Speed: 1118.20 samples/sec acc=0.989160 lossvalue=4.304033
> INFO:root:Epoch[1] Batch [10180-10200] Speed: 1104.27 samples/sec acc=0.988965 lossvalue=4.292909
> INFO:root:Epoch[1] Batch [10200-10220] Speed: 1134.59 samples/sec acc=0.989160 lossvalue=4.281045
> INFO:root:Epoch[1] Batch [10220-10240] Speed: 1134.25 samples/sec acc=0.989453 lossvalue=4.301128
> INFO:root:Epoch[1] Batch [10240-10260] Speed: 1129.99 samples/sec acc=0.296582 lossvalue=nan
> INFO:root:Epoch[1] Batch [10260-10280] Speed: 1123.79 samples/sec acc=0.000000 lossvalue=nan
> INFO:root:Epoch[1] Batch [10280-10300] Speed: 1086.07 samples/sec acc=0.000000 lossvalue=nan
> INFO:root:Epoch[1] Batch [10300-10320] Speed: 1132.76 samples/sec acc=0.000000 lossvalue=nan

Have you solved it?@RunningLeon

**Comment by tuannguyen1999xxx** [comment]
Try to change your batch_size and learning rate. I've solved it.
