### ISSUE TITLE
accuracy problem with my own dataset

### ISSUE THREAD

**Issue by cyrojyro** [deepinsight/insightface#881]
I made my own dataset and suffering from the accuracy loss..
I have tried changing lr,
number of classes of dataset,
number of images  of a person in dataset,
training loss f, 
aligning method..

any tips will be greatly appreciated

**Comment by ThanhPham1987** [comment]
Hi @cyrojyro,
Would you like to share how to build a own dataset?
Best regards,
PeterPham
