### ISSUE TITLE
New package models

### ISSUE THREAD

**Issue by mlourencoeb** [deepinsight/insightface#882]
Hi @nttstar,

This is more a question than an issue.

Thanks for open your code to the community. Noticed the new package, thanks a lot for that also.

Are the models included in the package the ones from insightface model zoo of or the lightweight face recognition challenge?

Thanks,
Miguel

**Comment by nttstar** [comment]
Hi, just wait for our more complete version and I will give some introduction at that time.

**Comment by mlourencoeb** [comment]
Thanks for the quick reply.
