### ISSUE TITLE
3D-alignment

### ISSUE THREAD

**Issue by Wisgon** [deepinsight/insightface#89]
Hi, thanks for the greate job. It's very powerful, and much more accurate than other repo I had used before such as dlib.
So I heard about that you may going to provide a 3D-alignment library later in #29 , I know there is a project that provide 3D-alignment, it's https://github.com/1adrianb/face-alignment, and it's using pytorch.
I don't know if it can help you, but I'm very looking forward to your 3D-alignment based recognition.
Close it when you read it,thanks.

**Comment by nttstar** [comment]
Yes we're going to provide a similar thing and it will help on profile faces,  thanks for your attention.
