### ISSUE TITLE
could you tell me how can I construct annotations?

### ISSUE THREAD

**Issue by ghost** [deepinsight/insightface#890]
HI, I have some question for annotations，show
below：
![{1B376AC9-10D7-4A86-9F86-45F5CAFAE851}_20190904143617](https://user-images.githubusercontent.com/43072388/64231175-72e52100-cf21-11e9-9720-7a31709ff04c.jpg)

thanks for your help

**Comment by gray2bgr** [comment]
![{FAAA62C0-E753-42C1-A0E2-6AA8A6246977}_20190904143505](https://user-images.githubusercontent.com/43072388/64231103-40d3bf00-cf21-11e9-8355-4e2ad446d7dd.jpg)
