### ISSUE TITLE
import cv2 is missing in face_detection.py

### ISSUE THREAD

**Issue by rebotnix** [deepinsight/insightface#895]
please add 

from __future__ import division
import mxnet as mx
import numpy as np
import mxnet.ndarray as nd
import cv2

in your face_detection.py

or you will get an issue when you change scaling call in your tutorial example when you want to resize the image cause cv2 is missing.

bboxes, landmark = model.detect(img, threshold=0.5, scale=0.5)

**Comment by nttstar** [comment]
Right, thank you!. Updated.
