### ISSUE TITLE
Boost Accuracy by 10-20%

### ISSUE THREAD

**Issue by jamessmith90** [deepinsight/insightface#896]
https://books.google.co.in/books?id=QeJEDwAAQBAJ&pg=PA503&lpg=PA503&dq="G-Log+algorithm"&source=bl&ots=ceQWD29NdA&sig=ACfU3U3b0dLmBZDGbnz85AEzvVDp9a8brQ&hl=en&sa=X&ved=2ahUKEwiW86PBkLzkAhWMK48KHawiBpYQ6AEwAHoECAYQAQ#v=onepage&q="G-Log%20algorithm"&f=false

An implementation of G-Log image enhancement Algorithm will definitely boost accuracy. 
I suggest we will implement this algorithm in this repository.

**Comment by 1frey** [comment]
Have you tried it? Or how can you mention the 10%-20%?

**Comment by jamessmith90** [comment]
Go through the entire article they have mentioned the improvements in accuracy.
