### ISSUE TITLE
RetinaFace test with resnet152 error

### ISSUE THREAD

**Issue by zhukkang** [deepinsight/insightface#898]
as i trained the retinaface with resnet152 with config as below ,

network.resnet.pretrained = 'model/resnet-152'
network.resnet.pretrained_epoch = 0
network.resnet.lr_step = '1,2,3,4,5,55,68,80'
network.resnet.lr = 0.001
network.resnet.PIXEL_MEANS = np.array([0.0, 0.0, 0.0])
network.resnet.PIXEL_STDS = np.array([1.0, 1.0, 1.0])
network.resnet.PIXEL_SCALE = 1.0
network.resnet.FIXED_PARAMS = ['^stage1', '^.*upsampling']
network.resnet.BATCH_IMAGES = 2
network.resnet.HEAD_FILTER_NUM = 256
network.resnet.CONTEXT_FILTER_RATIO = 1
#network.resnet.USE_DCN = 2
network.resnet.USE_DCN = 0
network.resnet.RPN_BATCH_SIZE = 256
network.resnet.RPN_ANCHOR_CFG = RAC_RETINA

After trained 10 epoch , i test got error below , plz help to check the issue 
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    faces, landmarks = detector.detect(img, thresh, scales=scales, do_flip=flip)
  File "/home/ai/big_disk/GearRoundSpace/SOTA/insightface/RetinaFace/retinaface.py", line 296, in detect
    proposals = proposals[order, :]
IndexError: index 768 is out of bounds for axis 0 with size 768

**Comment by jiashu-zhu** [comment]
you must check your config, and make sure your anchor setting is same between training and inference
I have met this problem, you can check 'config.DENSE_ANCHOR' in config.py and 'dense_anchor' at line 105 in retinaface.py

**Comment by zhukkang** [comment]
@jiashu-zhu  as i checked both the config of anchor is set to false 
dense_anchor = False

config.DENSE_ANCHOR = False

**Comment by jiashu-zhu** [comment]
if you use 'net5' in test.py line15?

**Comment by jiashu-zhu** [comment]
@zhukkang

**Comment by zhukkang** [comment]
detector = RetinaFace('./model/retina-125000', 0, gpuid, 'net5') 
fixed to net5 is ok now ,so thanks 
@jiashu-zhu
