### ISSUE TITLE
can not align facescrub

### ISSUE THREAD

**Issue by delveintodetail** [deepinsight/insightface#9]
python align_facescrub.py --input-dir ~/face/megaface/facescrub/ --output-dir ./facescrub_align 
Martin Henderson/Martin Henderson_40499
Rebecca Budig/Rebecca Budig_10788
Pamela Anderson/Pamela Anderson_2367
valid keys 3530
Creating networks and loading parameters

AttributeError: 'EasyDict' object has no attribute 'landmark'

**Comment by delveintodetail** [comment]
more information, I successfully run align_megaface.py but cannot run align_facescrub.py.

**Comment by delveintodetail** [comment]
2018-01-24 16:04:26.818465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-01-24 16:04:26.818471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-01-24 16:04:26.818480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0)
Processing 0, ([0 0 0 0 0])
Traceback (most recent call last):
  File "align_facescrub.py", line 274, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "align_facescrub.py", line 169, in main
    if fimage.landmark is not None:
AttributeError: 'EasyDict' object has no attribute 'landmark'

**Comment by nttstar** [comment]
Hi delveintodetail, plz update the repo and try again. 
Align facescrub is a little bit tricky, you may need to put some additional files into the 'input dir'. You can review the code firstly, the files we need is obvious and hard-coded.
Based on this fact, we will consider to release aligned facescrub images directly if there's no legal problem.

**Comment by delveintodetail** [comment]
I have put facescrub_actors.xt, facescrub_actresses.txt and facescrub_upcropped_feature_list.json in the 'input dir'. I upgrade the code, still the same problem...

**Comment by nttstar** [comment]
Check it again now.

**Comment by qixianbiao** [comment]
![default](https://user-images.githubusercontent.com/3202327/35323320-0a7d7fc2-0128-11e8-8678-73abae0453a6.png)

**Comment by delveintodetail** [comment]
~/Face_scrub/facescrub/Adrienne Frantz/Adrienne Frantz_27768.jpg: cannot identify image file '~/Face_scrub/facescrub/Adrienne Frantz/Adrienne Frantz_27768.jpg'

OpenCV Error: Unspecified error (could not find a writer for the specified extension) in imwrite_, file /opt/conda/conda-bld/opencv_1491943414359/work/opencv-3.1.0/modules/imgcodecs/src/loadsave.cpp, line 459
Traceback (most recent call last):
  File "align_facescrub.py", line 273, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "align_facescrub.py", line 256, in main
    cv2.imwrite(target_file, bgr)

**Comment by delveintodetail** [comment]
should the facescrub be the original uncropped or the provide cropped directory???   if it is the cropped facescrub director, the result looks like 
![default](https://user-images.githubusercontent.com/35760622/35323959-44eba68c-012a-11e8-84aa-74bd07742326.png)

**Comment by nttstar** [comment]
You need to use uncropped images to align.
By the way, you can detect landmarks by any public available MTCNN and then do similarity transform to 112x112.  The result should be the same.

**Comment by delveintodetail** [comment]
I still cannot obtain good detection results with your code for uncrossed images (align_facescrub.py). 
in your code:
if fimage.landmark is not None:

if warped is None and fimage.bbox is not None:

but for the uncrossed images, there are no landmark and bbox,  can you pls show your detected code? 
if possible, can you provide the code and run script???

**Comment by delveintodetail** [comment]
def get_dataset_facescrub(input_dir):
  ret = []
  label = 0
  person_names = []
  for person_name in os.listdir(input_dir):
    person_names.append(person_name)
  person_names = sorted(person_names)
  for person_name in person_names:
    subdir = os.path.join(input_dir, person_name)
    if not os.path.isdir(subdir):
      continue
    for _img in os.listdir(subdir):
      fimage = edict()
      fimage.id = os.path.join(person_name, _img)
      fimage.classname = str(label)
      fimage.image_path = os.path.join(subdir, _img)
      fimage.landmark = None
      fimage.bbox = None
      ret.append(fimage)
    label += 1
  return ret

bbox and lardmark is none, then in your code, so although we input the uncrossed images, the code in align_facescrub.py will not use face_detection.face_detection().    I am confused how you do this???
Thanks for your information in advance.

**Comment by delveintodetail** [comment]
can you pls show your detected face images???

**Comment by nttstar** [comment]
I remember facescrub has its own defined bounding-box. You can parse it and add them in face_image.py.  Recently we just use another piece of mtcnn code to align the facescrub images. 

To make our result reproducible, we may put the aligned facescrub images in our repo soon.

**Comment by nttstar** [comment]
@delveintodetail I just fixed the issue of align_facescrub.py, plz try it again.

**Comment by nttstar** [comment]
and the output file name follows the template of aligned facescrub set(firstname_lastname.png)

**Comment by delveintodetail** [comment]
megafaces/Face_scrub/facescrub/Harry Connick Jr./Harry Connick Jr._22911
Traceback (most recent call last):
  File "align_facescrub.py", line 288, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "align_facescrub.py", line 156, in main
    img_id = int(body)
ValueError: invalid literal for int() with base 10: 'Harry Connick Jr'

**Comment by nttstar** [comment]
file name is Harry Connick Jr._22911.jpg on my disk, try to fix it by yourself.
