### ISSUE TITLE
How to compare 2 ArcFace features?

### ISSUE THREAD

**Issue by pango99** [deepinsight/insightface#903]
I use cosine similarity to calculate 2 features similarity,but I am not sure whether it is the best way, so whether cosine similarity is suite for arcface's feature comparing? Is there any other ways to do the feature comparing?

**Comment by cyrojyro** [comment]
you can use sum of squared error
np.sum(np.square(f1 - f2))
(from deploy/test.py)

**Comment by pango99** [comment]
> 
> 
> you can use sum of squared error
> np.sum(np.square(f1 - f2))
> (from deploy/test.py)

thank you, how accurate is it ? the formuler looks like euler distance

**Comment by Walstruzz** [comment]
U can also use Cosine Similarity.
```Python
embedding_1, embedding_2 = normalize(embedding_1), normalize(embedding_2)
sim = embedding_1 @ embedding_2
```
-1 <= sim <= 1.

**Comment by pango99** [comment]
> ```python



> 
> 
> U can also use Cosine Similarity.
> 
> ```python
> # if embedding_1.shape is (1, emb_size,), use:
> embedding_1, embedding_2 = normalize(embedding_1), normalize(embedding_2)
> sim = embedding_1 @ embedding_2.T
> ```
> 
> -1 <= sim <= 1.

thank you,but I am a c language programmer,I'm using mxnet c api to use ArcFace model,and I'm a python language starter,so I cant understand the meaning of below line code:
sim = embedding_1 @ embedding_2.T

what's the meaning of "@" symbol?

**Comment by yuanbit** [comment]
@pango99: how do you extract ArcFace feature vectors using your own dataset and the pretrained models?

**Comment by pango99** [comment]
> 
> 
> @pango99: how do you extract ArcFace feature vectors using your own dataset and the pretrained models?

use MXNet C API

**Comment by lebionick** [comment]
@pango99 
same question, it's not obvious from the formula of loss, but these guys just use cosine dist
https://www.groundai.com/project/arcface-additive-angular-margin-loss-for-deep-face-recognition/1
>During testing, the score is computed by the Cosine Distance of two feature vectors. Nearest neighbour and threshold comparison are used for face identification and verification tasks.
