### ISSUE TITLE
face2rec2.py error 

### ISSUE THREAD

**Issue by xysong1201** [deepinsight/insightface#904]
When I use face2rec.py all goes well, but in the end I have this error below:
`Traceback (most recent call last):
  File "face2rec2.py", line 253, in <module>
    image_encode(args, i, item, q_out)
  File "face2rec2.py", line 105, in image_encode
    s = mx.recordio.pack(header, '')
  File "/home/song/miniconda3/lib/python3.7/site-packages/mxnet/recordio.py", line 393, in pack
    s = label.tostring() + s
TypeError: can't concat str to bytes
`
It seems like there is something in the last line of .lst file
( I seperate the .lst file into 2 files, error persists.)
Hi someone could help to explain this error?

**Comment by xysong1201** [comment]
Find the answer in another post 
Just modify 
`mx.recordio.pack(header, b'')` in face2rec.py line 105

**Comment by clhne** [comment]
> Find the answer in another post
> Just modify
> `mx.recordio.pack(header, b'')` in face2rec.py line 105

[This post?](https://github.com/deepinsight/insightface/issues/127#issuecomment-441990147)
You're right.b means for bytes

**Comment by xysong1201** [comment]
> > Find the answer in another post
> > Just modify
> > `mx.recordio.pack(header, b'')` in face2rec.py line 105
> 
> [This post?](https://github.com/deepinsight/insightface/issues/127#issuecomment-441990147)
> You're right.b means for bytes

yes ;)

**Comment by ThanhPham1987** [comment]
Hi @xysong1201,
Would you like to share how to run face2rec2.py file?
Best regards,
PeterPham
