### ISSUE TITLE
实际使用在老人和小孩上表现比较差

### ISSUE THREAD

**Issue by 13718413797** [deepinsight/insightface#905]
实际使用在老人和小孩上表现比较差，不同的老人和老人，小孩和小孩相似的都很高，有什么办法吗？  有覆盖老人和小孩的数据集重新训练一下吗？

**Comment by FaceGg** [comment]
> 实际使用在老人和小孩上表现比较差，不同的老人和老人，小孩和小孩相似的都很高，有什么办法吗？  有覆盖老人和小孩的数据集重新训练一下吗？

你都知道问题出在哪了，为什么不自己针对性的去收集一些数据？

**Comment by xuguozhi** [comment]
中青年男性人脸识别系统
