### ISSUE TITLE
single gpu training can't achieve the effect on paper

### ISSUE THREAD

**Issue by HansonSun** [deepinsight/insightface#91]
为什么我将batch size改小了，然后CUDA_VISIBLE_DEVICES设为０去训练无法达到论文中的效果，
CUDA_VISIBLE_DEVICES='0' python -u train_softmax.py --network r50 --loss-type 2 --margin-m 0.35 --data-dir ../datasets/faces_ms1m_112x112 --prefix ../model-r50-amsoftmax
我训练epoch为12时，lfw 准确率只有９７％　后面基本不会变了
谢谢

**Comment by nttstar** [comment]
Batch size should be at least 128. All my experiments were done with batch-size=512(128*4)
