### ISSUE TITLE
Core Dumped at Last Epoch Save

### ISSUE THREAD

**Issue by vjsrinivas** [deepinsight/insightface#915]
When I try to train RetinaFace with the following command:  `CUDA_VISIBLE_DEVICES='0' python -u train.py --prefix ./model/retina --network resnet` it trains all the way to whatever epoch I have set, and then crashes during "save_model()" with the message:

```
terminated without active exception
Aborted (core dumped)
```
Any idea as to why?

More details:
GPU: Nvidia 2080TI
Starting weight: ResNet50 training weights
I also just used the default values in config.py

**Comment by vjsrinivas** [comment]
Nvm, it was a problem caused by running it with python3 instead of python2.

**Comment by nttstar** [comment]
why? it should be no problem with py3
