### ISSUE TITLE
Hello, I want to ask, which version of python2.7 are you using here when training? Is there a difference between using train.py and train_softmax during training?I can't run train_softmax.py. I hope you can answer for me.Thanks

### ISSUE THREAD

**Issue by wbj1995** [deepinsight/insightface#916]

**Comment by AGenchev** [comment]
Have you tried with python3 ? They might switched to the newer python. (at least I would)

**Comment by jolastar** [comment]
Under `src`, `train_softmax.py` is the "official" training script, while `train.py` script is experimental, for the authors' usage. You can notice that the first line in the latter file states:

```# THIS FILE IS FOR EXPERIMENTS, USE train_softmax.py FOR NORMAL TRAINING.```

As for the python version, you can use the distribution of Python 2.7 that you prefer - I use Miniconda2. And you need to install MXNet for Python 2: you can get help with the installation command at https://mxnet.apache.org/get_started. I've installed version MXNet version 1.5.0 for GPU `mxnet-cu100mkl` from PyPi with the command `pip install mxnet-cu100mkl`.

**Comment by wbj1995** [comment]
Thank you very much for your reply. This problem occurred when I used MXNET to extract features.I used test.py under the "deploy" folder, and I changed the code a little to extract the features of 10,000 faces and save them in an NPY file. Could you explain it for me? Thank you very much.

error：    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator conv0: [20:43:49] C:\Jenkins\workspace\mxnet-tag\mxnet\src\operator\nn\convolution.cc:152: Check failed: dshp.ndim() == 4U (1 vs. 4) : Input data should be 4D in batch-num_filter-y-x
  5%|▍         | 1600/33536 [01:18<26:10, 20.34it/s]






------------------ 原始邮件 ------------------
发件人: "JS"<notifications@github.com>;
发送时间: 2019年10月6日(星期天) 晚上8:40
收件人: "deepinsight/insightface"<insightface@noreply.github.com>;
抄送: "佳欣婧"<1056176004@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [deepinsight/insightface] Hello, I want to ask, which version ofpython2.7 are you using here when training? Is there a difference betweenusing train.py and train_softmax during training?I can't run train_softmax.py.I hope you can answer for me.Thanks (#916)




Under src, train_softmax.py is the "official" training script, while train.py script is experimental, for the authors' usage. You can notice that the first line in the latter file states:
 
# THIS FILE IS FOR EXPERIMENTS, USE train_softmax.py FOR NORMAL TRAINING.
 
As for the python version, you can use the distribution of Python 2.7 that you prefer - I use Miniconda2. And you need to install MXNet for Python 2: you can get help with the installation command at https://mxnet.apache.org/get_started. I've installed version MXNet version 1.5.0 for GPU mxnet-cu100mkl from PyPi with the command pip install mxnet-cu100mkl.

**Comment by jolastar** [comment]
It looks like you're not feeding the data in the correct shape to the model so it fails with the first convolution. It expects 4D input, as the error message says ("batch-num_filter-y-x") and it got 1D data.

I also modified `deploy/test.py` to compute embeddings on some sample pictures. Here's the relevant part of the code for me (the images are already cropped and aligned, so I skip `img = model.get_input(img)`:

```python
embeddings_normalized_output = open('embeddings_normalized.txt', 'w')

for file in sorted(os.listdir('my_images')):
    print(file)
    try:
        img = cv2.imread('my_images/' + file)
        # img = model.get_input(img)
        nimg = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        timg = np.transpose(nimg, (2, 0, 1))
        f1, f1_norm = model.get_feature(timg)
        embeddings_normalized_output.write(file + "," + ",".join([str(x) for x in f1_norm]) + "\n")
    except Exception as e:
        print('Failed: ' + file)
        print(e)
        # import pdb;pdb.set_trace()
```

**Comment by WIll-Xu35** [comment]
The src directory was last updated 10 months ago and seems a bit outdated. And according  to the readme file, the author suggests using the train.py under recognition directory.
