### ISSUE TITLE
whether cosine similarity has negative value?

### ISSUE THREAD

**Issue by pango99** [deepinsight/insightface#917]
Hi:
   I use below cpp code to calculate cosine similarity between 2 face features:

float FaceFeaturesCompare_CosSimilarity(const float *f1,const float *f2,int nb)
{
	float  product = 0;
	float l2_sum0 = 0;
	float  l2_sum1 = 0;
	for (size_t i = 0; i < nb; i++)
	{
		product += f1[i] * f2[i];
		l2_sum0 += f1[i] * f1[i];
		l2_sum1 += f2[i] * f2[i];
	}
	return abs(product / (std::sqrt(l2_sum0) * std::sqrt(l2_sum1)));
}

because I use abs() function,so the return similar is in [0,1], but I found many people use below python code to calculate:
sim = np.dot(t1,t2.T)
the returned similar is in [-1,1], so my question is whether cosine similarity has negative value? if 2 face features similar is -0.9, is it a same person? or not?

**Comment by cyrojyro** [comment]
cosine similarity is like an inner product.
if angle between two vector is larger than 90 degree, the value is negative.
which means two faces(features) are clearly distinguishable.

**Comment by pango99** [comment]
> 
> 
> Cosine similarity is like an inner product.
> If angle between two vector is larger than 90 degree, the value is negative,
> and that means that two faces(features) are clearly distinguishable.

Oh,so my  cosine similarity cpp code is wrong, I should get rid of calling abs(), is it?

**Comment by 17702513221** [comment]
How can I judge the same person? When I judge the side face, I get a negative value or a very small value which is smaller than the normal value, which causes interference. How can I compare the value to the meter?

**Comment by pango99** [comment]
> 
> 
> How can I judge the same person? When I judge the side face, I get a negative value or a very small value which is smaller than the normal value, which causes interference. How can I compare the value to the meter?

I judge the same person if cosine similarity is large than 0.5, negative or very small value means different person
