### ISSUE TITLE
Could not reproduce the training - Out of memory

### ISSUE THREAD

**Issue by siyiding1216** [deepinsight/insightface#92]
[00:17:52] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
/home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/module/base_module.py:466: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (0.25 vs. 0.001953125). Is this intended?
  optimizer_params=optimizer_params)
call reset()
terminate called after throwing an instance of 'dmlc::Error'
  what():  [00:18:12] src/engine/./threaded_engine.h:359: [00:18:12] src/storage/./pooled_storage_manager.h:107: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2ab998) [0x7f4d17152998]
[bt] (1) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2abda8) [0x7f4d17152da8]
[bt] (2) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x29071ef) [0x7f4d197ae1ef]
[bt] (3) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x290a4c8) [0x7f4d197b14c8]
[bt] (4) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x6c9c6f) [0x7f4d17570c6f]
[bt] (5) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2459726) [0x7f4d19300726]
[bt] (6) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x245f3c0) [0x7f4d193063c0]
[bt] (7) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x243fe0d) [0x7f4d192e6e0d]
[bt] (8) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24446fb) [0x7f4d192eb6fb]
[bt] (9) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24448d6) [0x7f4d192eb8d6]

A fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

Stack trace returned 9 entries:
[bt] (0) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2ab998) [0x7f4d17152998]
[bt] (1) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2abda8) [0x7f4d17152da8]
[bt] (2) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24400b4) [0x7f4d192e70b4]
[bt] (3) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24446fb) [0x7f4d192eb6fb]
[bt] (4) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24448d6) [0x7f4d192eb8d6]
[bt] (5) /home/ubuntu/miniconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24411ab) [0x7f4d192e81ab]
[bt] (6) /home/ubuntu/miniconda2/bin/../lib/libstdc++.so.6(+0xafc5c) [0x7f4d42feac5c]
[bt] (7) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f4d994f76ba]
[bt] (8) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f4d98b1d41d]

Aborted (core dumped)

GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:00:17.0     Off |                    0 |
| N/A   38C    P8    27W / 149W |      2MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:00:18.0     Off |                    0 |
| N/A   35C    P8    29W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 0000:00:19.0     Off |                    0 |
| N/A   39C    P8    26W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 0000:00:1A.0     Off |                    0 |
| N/A   36C    P8    29W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           On   | 0000:00:1B.0     Off |                    0 |
| N/A   39C    P8    26W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           On   | 0000:00:1C.0     Off |                    0 |
| N/A   36C    P8    31W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           On   | 0000:00:1D.0     Off |                    0 |
| N/A   42C    P8    25W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           On   | 0000:00:1E.0     Off |                    0 |
| N/A   37C    P8    29W / 149W |      0MiB / 11439MiB |      0%      Default |

**Comment by siyiding1216** [comment]
Are u also using 12G memory

**Comment by nttstar** [comment]
#32
