### ISSUE TITLE
In Evaluation/IJB how did you get ijbc_face_tid_mid.txt

### ISSUE THREAD

**Issue by xysong1201** [deepinsight/insightface#920]
Hi, you mentioned in the post https://github.com/deepinsight/insightface/issues/556#issuecomment-466807654
that the ijbc_face_tid_mid.txt is from [vgg_face2]( https://github.com/ox-vgg/vgg_face2/tree/master/standard_evaluation).
But the file vgg_face2 they provide is based on IJBB.
could you also share your ijbc related files?
Thank you.

**Comment by xysong1201** [comment]
Hi, problem solved. a simple script could be created to generate ijbc_face_tid_mid.txt from the IJBC protocol database

**Comment by jlamperez** [comment]
Hi @xysong1201,

Can you tell me how you have solved the problem?

**Comment by xysong1201** [comment]
> Hi @xysong1201,
> 
> Can you tell me how you have solved the problem?

Hi @jlamperez , I think you should download the IJBC original database. and in the csv files they provided you could extract the information you want. [my extraction example](https://github.com/xysong1201/Face-recognition_preprocessing)

**Comment by lbc402** [comment]
Hi @xysong1201, I ran the official jupyter script to evaluate IJBC, but I couldn't get the correct results. 
   Methods      | 1e-06  | 1e-05  | 0.0001 | 0.001  |  0.01  |  0.1   |
+------------------+--------+--------+--------+--------+--------+--------+
|       ex1        | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.5146 | 0.5612 |
| ex-vgg-(N1D1F1)  | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.5085 | 0.5740 |
| ex1-vgg-(N1D1F1) | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.5085 | 0.5739 |
| ex-vgg2-(N1D1F1) | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.5093 | 0.5739 |
+------------------+--------+--------+--------+--------+--------+--------+
Do you know why?
In addition, the IJBB dataset is reproducible.

**Comment by wangxianliang** [comment]
> Hi @xysong1201, I ran the official jupyter script to evaluate IJBC, but I couldn't get the correct results.
> Methods | 1e-06 | 1e-05 | 0.0001 | 0.001 | 0.01 | 0.1 |
> +------------------+--------+--------+--------+--------+--------+--------+
> | ex1 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.5146 | 0.5612 |
> | ex-vgg-(N1D1F1) | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.5085 | 0.5740 |
> | ex1-vgg-(N1D1F1) | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.5085 | 0.5739 |
> | ex-vgg2-(N1D1F1) | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.5093 | 0.5739 |
> +------------------+--------+--------+--------+--------+--------+--------+
> Do you know why?
> In addition, the IJBB dataset is reproducible.

Did you solve the issue?
