### ISSUE TITLE
What's the relationship between AgeDB-30 and the original AgeDB ?

### ISSUE THREAD

**Issue by ingjieye** [deepinsight/insightface#926]
Hi. I've downloaded both AgeDB-30 by yours and the original AgeDB by iBUG. How ever the AgeDB-30 is aligned already and I wanna do align by myself. I've looked into AgeDB-30 and the original AgeDB but I couldn't find out the relationship between this two.

So my question is that what's the relationship between the two db? Is there any private dataset in the  AgeDB-30 ?

**Comment by daisyhaohao** [comment]
@ingjieye According to AgeDB paper, "...we split AgeDB in 10 folds, with each fold consisting of 300 intra- class and 300 intra-class pairs. The main difference among the protocols is that in each protocol the age difference of each pair’s faces is equal to a fixed, predefined value, i.e., 5, 10, 20 and 30 years", obviously AgeDB-30 is part of AgeDB.  
I also downloaded original AgeDB from i-bug, but can not unzip without zip password. Could you help provide me an unzip password ? my email, daisyhaohao@163.com

**Comment by ingjieye** [comment]
@daisyhaohao Yeah that's what paper said but if you look into this two dataset you'll find out that there is some image inside AgeDB-30 provided by deepinsight is not in the original AgeDB dataset.

**Comment by daisyhaohao** [comment]
@ingjieye 不清楚你是怎么来比对图片发现这个问题的，但是我看到 src/data/agedb2pack.py 和 agedb2pack2.py 这两个脚本都读取了 "04_FINAL_protocal_30_years.mat" 文件来打包agedb-30.bin, 拿到这个文件应该就能知道了。

**Comment by clhne** [comment]
Hi @ingjieye @daisyhaohao AgeDB的解压密码方便发给我吗？谢谢！

**Comment by Light--** [comment]
>password ? my email, [daisyhaohao@163.com](mailto:daisyhaohao@163.com)

hi, could u pls. share the password?

**Comment by Hzzone** [comment]
I have requested the mat file from the authors.

**Comment by zhangfenfang12138** [comment]
> Hi. I've downloaded both AgeDB-30 by yours and the original AgeDB by iBUG. How ever the AgeDB-30 is aligned already and I wanna do align by myself. I've looked into AgeDB-30 and the original AgeDB but I couldn't find out the relationship between this two.
> 
> So my question is that what's the relationship between the two db? Is there any private dataset in the AgeDB-30 ?

您好，请问可以给我一份AgeDB-30数据集么，给官方数据集发邮件不回复，十分感谢大哥
