### ISSUE TITLE
megaface dataset

### ISSUE THREAD

**Issue by 6sephiruth** [deepinsight/insightface#927]
Good morning. We are working on your arcface.
This time we are going to megaface. We downloaded the megaface from washington university. But the dataset at washington is not refined. The arcface paper seems to have refined the megaface. Can I share the refined megaface?

**Comment by edward0909** [comment]
Hi @6sephiruth, 
what you mean is here https://github.com/deepinsight/insightface/tree/master/Evaluation/Megaface

**Comment by CryptoSeminar** [comment]
I'm really new. Can you teach me why?
I created a data folder in the insightface / Evaluation / Megaface directory and put the unzip file.

![image](https://user-images.githubusercontent.com/55975935/66337543-4ede8a80-e97a-11e9-84bc-04bdfcf19a58.png)

![image](https://user-images.githubusercontent.com/55975935/66337594-6ae22c00-e97a-11e9-881b-7d9719559b10.png)

**Comment by skyuuka** [comment]
@ghost  I checked the Megaface folder, and found that it depends on ` /raid5data/dplearn/megaface/devkit`.  Do you know where to get that?  Thanks :)
