### ISSUE TITLE
Feature Embedding - question

### ISSUE THREAD

**Issue by AGenchev** [deepinsight/insightface#930]
I'm just trying to understand what's behind the "feature embedding" term/function:
1. If when the deep ANN is training it's goal is to become a good face feature extractor, then it should not embed any face feature in itself, OK ? Then where the features to be embedded go ?

2. If when training, the goal is to "embed" all face features **in** ANN weights (and have say 10k outputs for 10k persons to classify),  then the "**embedding**" already happened during training (which requires lot of passes and samples). So how then the "feature embedding" which takes only 17 mS (as written in the .md file) works ?  E.t. where does it embed features ?

**Comment by nttstar** [comment]
'Embedding' means (image -> feature-vector) mapping.

**Comment by AGenchev** [comment]
Thank you ! You helped me a lot for a practical use !
If I write "Embedding" = "feature vector **calculation**" will I be right ?

If so, then to find the closest class (person) we need to compare this vector with all feature vectors
we have stored somewhere to find which one has the **minimum distance** in the 512-D space, right ?
Then, the pre-trained model can be applied to any face out of the data-set and it will calculate it's vectors. So your trained model / network can be used for non-existing faces in the dataset ?   
If I "embed" **n**-faces of a new person, non-existing in the training dataset (from my company), then I'll get a cluster of **n** 512-D vectors with a geometric center somewhere. And the closest to this **center** vector indicates most similar face.
Is this right ?

**Comment by nttstar** [comment]
@AGenchev Right
