### ISSUE TITLE
How to get output of retinaface model?

### ISSUE THREAD

**Issue by luan1412167** [deepinsight/insightface#941]
I'm converting retina face to onnx. I get output like the image. How I can get bounding box and landmark?
![Screenshot from 2019-10-15 13-07-16](https://user-images.githubusercontent.com/37315746/66804520-d9ac2000-ef4c-11e9-9759-0e5f5ff5dce0.png)

**Comment by WIll-Xu35** [comment]
Pretrained Retinaface model outputs 9 arrays. There are 3 different strides, each stride outputs its scores, bboxes, landmarks. So in your image, ends of the branches are model outputs (9 outputs layer in total). For post processing of the network outputs, read the code in Retinaface/test.py and Retinaface/retinaface.py
