### ISSUE TITLE
Is insightface suitable for ARM64?

### ISSUE THREAD

**Issue by congphase** [deepinsight/insightface#948]
Hello everybody, I intend to use this awesome work on Nvidia Jetson Nano (arm64), is this okay?

Btw, what is the best strategy to use this work so that it provides the fastest inference speed but also acceptable accuracy? Because the faces I intended to recognize are nearly frontal, purple-colored at night (captured with Waveshare IMX219-160IR night vision camera).

Did anyone have prior experience with Jetson devices or have any related benchmark? Please give me some advices on this. Thank you a lot!!

**Comment by yy2536298120** [comment]
> Hello everybody, I intend to use this awesome work on Nvidia Jetson Nano (arm64), is this okay?
> 
> Btw, what is the best strategy to use this work so that it provides the fastest inference speed but also acceptable accuracy? Because the faces I intended to recognize are nearly frontal, purple-colored at night (captured with Waveshare IMX219-160IR night vision camera).
> 
> Did anyone have prior experience with Jetson devices or have any related benchmark? Please give me some advices on this. Thank you a lot!!
有一个异构的MXNET 在github上有 还有操作说明 你看看 可以加我 微信：yy2526298120 手机：13180977920

**Comment by 17702513221** [comment]
人脸检测模型我记得有人转成功了，30FPS在nano板卡上，但是人脸识别模型还没看到
