### ISSUE TITLE
Age gender model

### ISSUE THREAD

**Issue by xysong1201** [deepinsight/insightface#950]
hi, i'm trying to understand your age and gender modle and I saw there is BS * 101 output for your modle, could you explain more on the your algorithm? Thank you

**Comment by WIll-Xu35** [comment]
https://github.com/deepinsight/insightface/blob/master/gender-age/face_model.py#L89-L98

**Comment by yy2536298120** [comment]
> hi, i'm trying to understand your age and gender modle and I saw there is BS * 101 output for your modle, could you explain more on the your algorithm? Thank you

你好 咱俩可以加一下微信 我也在弄这个 在自动化所 微信：yy2526298120 手机：13180977920

**Comment by gengyanlei** [comment]
请问你们弄懂了gender-age这个项目了么？传授一下经验，十分感谢

**Comment by yy2536298120** [comment]
加我微信：yy2526298120



---Original---

**Comment by 205418367** [comment]
hi,这个性别年龄识别的输入尺寸是多少，均值和方差是多少，需要做人脸对齐么？
