### ISSUE TITLE
关于1：n识别

### ISSUE THREAD

**Issue by idchangyifan** [deepinsight/insightface#96]
您好，首先感谢您的工作！
初学者想请问一下1：N具体是体现在什么地方呢？
看了verification.py的源码，好像做的还是1:1的对比啊。

**Comment by wangzhechn** [comment]
特征值比对吧，是不是把所有人脸特征值提取出来，然后逐个比对

**Comment by idchangyifan** [comment]
@wangzhechn 这个原理我知道哈~我意思是，代码里面根据什么来做的准确度判断。比如lfw就是根据pairs.txt来做的1:1的准确度判断。我想知道MegaFace1M的1：n是怎么做的，难道是比较1个人和所有人的特征值距离吗？萌新一枚，求指点。。

**Comment by nttstar** [comment]
Megaface有搜索模版.

**Comment by idchangyifan** [comment]
@nttstar 感谢您的回复，但是不是很明白您的意思。。。
可能我描述的不是很清楚，insightface做到的98+%的准确率是指给一张人脸，然后在Megaface100万张人脸中找出同一个人的其他相片吗？

**Comment by nttstar** [comment]
可以这么理解, 仔细看一下MegaFace Challenge的说明.

**Comment by idchangyifan** [comment]
@nttstar 实在太感谢您了！
