### ISSUE TITLE
License of the training data

### ISSUE THREAD

**Issue by believeitmyway** [deepinsight/insightface#962]
I found a license description as below:

The training data containing the annotation (and the models trained with these data) are available for non-commercial research purposes only.

If we use VGG2 in Dataset Zoo for model training, are the obtained models available for commercial use?
The original VGG2  is under a Creative Commons license.

**Comment by believeitmyway** [comment]
In my understanding, the MIT license applies only to the source codes. I would like to know the type of license applied to data other than the source code included in this project.

**Comment by believeitmyway** [comment]
I'm sorry to comment many times.
VGGFace2 is covered under a Creative Commons Attribution 4.0 International license. , so I think that we can't put new restrictions on redistribution.
Is this right?

Licenses are very important for industry research.
I will be glad to get your reply.

**Comment by nttstar** [comment]
License of insightface is just for our code.

**Comment by believeitmyway** [comment]
Thank you for your reply!
I understood your license policy.

**Comment by ayush431** [comment]
can any one tell me about pretrained intial weights are under commercial use or not ?
