### ISSUE TITLE
mx.model.load_checkpoint() raise error    JSONReader: Unknown field attrs

### ISSUE THREAD

**Issue by Nathanielll** [deepinsight/insightface#97]
mxnet.base.MXNetError: [17:20:56] g:\deeplearn\mxnet\dmlc-core\include\dmlc\./json.h:842: JSONReader: Unknown field attrs, candidates are: 
"attr"
"backward_source_id"
"control_deps"
"inputs"
"name"
"op"
"param"

**Comment by nttstar** [comment]
Make sure your mxnet version>=0.12
