### ISSUE TITLE
Pretrained model for Face Alignment

### ISSUE THREAD

**Issue by nicolaerosia** [deepinsight/insightface#974]
Is there a pre-trained model available for use with the implementation of "Stacked Dense U-Nets with Dual Transformers for Robust Face Alignment" available at https://github.com/deepinsight/insightface/tree/master/alignment ?

Thank you

**Comment by nicolaerosia** [comment]
Kind ping @nttstar

**Comment by nttstar** [comment]
currently no

**Comment by nicolaerosia** [comment]
ok, thank you
