### ISSUE TITLE
Error occur after loading bin

### ISSUE THREAD

**Issue by ymcasky** [deepinsight/insightface#98]
Dear all,

I have error as following.
It seems like load data successfully but occur error after training start...
can anyone help me?

# Here is my command:
nux/insightface/src$ CUDA_VISIBLE_DEVICES='0' python -u train_softmax.py --network r100 --loss-type 4 --margin-m 0.5 --data-dir ../datasets/faces_ms1m_112x112  --prefix ../model-r100

# Here is my log:
gpu num: 1
num_layers 100
image_size [112, 112]
num_classes 85164
Called with argument: Namespace(batch_size=128, beta=1000.0, beta_freeze=0, beta_min=5.0, c2c_mode=-10, c2c_threshold=0.0, center_alpha=0.5, center_scale=0.003, ckpt=1, coco_scale=8.676161173096705, ctx_num=1, cutoff=0, data_dir='../datasets/faces_ms1m_112x112', easy_margin=0, emb_size=512, end_epoch=100000, gamma=0.12, image_channel=3, image_h=112, image_w=112, images_per_identity=0, incay=0.0, logits_verbose=0, loss_type=4, lr=0.1, lr_steps='', margin=4, margin_a=0.0, margin_b=0.0, margin_m=0.5, margin_s=64.0, margin_verbose=0, max_steps=0, mom=0.9, network='r100', noise_sgd=0.0, num_classes=85164, num_layers=100, output_c2c=0, patch='0_0_96_112_0', per_batch_size=128, power=1.0, prefix='../model-r100', pretrained='', rand_mirror=1, rescale_threshold=0, retrain=False, scale=0.9993, target='lfw,cfp_fp,agedb_30', train_limit=0, triplet_alpha=0.3, triplet_bag_size=3600, triplet_max_ap=0.0, use_deformable=0, use_val=False, verbose=2000, version_act='prelu', version_input=1, version_output='E', version_se=0, version_unit=3, wd=0.0005)
init resnet 100
0 1 E 3 prelu
INFO:root:loading recordio ../datasets/faces_ms1m_112x112/train.rec...
/home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/recordio.py:370: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  header = header._replace(label=np.fromstring(s, np.float32, header.flag))
header0 label [3804847. 3890011.]
id2range 85164
0 0 3804846
c2c_stat [0, 85164]
3804846
rand_mirror 1
(128,)
[18:19:03] src/engine/engine.cc:55: MXNet start using engine: ThreadedEnginePerDevice
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
(12000L, 3L, 112L, 112L)
ver lfw
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
loading bin 13000
loading bin 14000
(14000L, 3L, 112L, 112L)
ver cfp_fp
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
(12000L, 3L, 112L, 112L)
ver agedb_30
lr_steps [400000, 560000, 640000]
[18:20:46] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
/home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/module/base_module.py:466: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.0078125). Is this intended?
  optimizer_params=optimizer_params)
call reset()
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:20:56] src/engine/./threaded_engine.h:359: [18:20:56] src/storage/./pooled_storage_manager.h:107: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2ab998) [0x7f6b6eecd998]
[bt] (1) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2abda8) [0x7f6b6eecdda8]
[bt] (2) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x29071ef) [0x7f6b715291ef]
[bt] (3) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x290a4c8) [0x7f6b7152c4c8]
[bt] (4) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x6c9c6f) [0x7f6b6f2ebc6f]
[bt] (5) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2459726) [0x7f6b7107b726]
[bt] (6) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x245f3c0) [0x7f6b710813c0]
[bt] (7) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x243fe0d) [0x7f6b71061e0d]
[bt] (8) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24446fb) [0x7f6b710666fb]
[bt] (9) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24448d6) [0x7f6b710668d6]

A fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

Stack trace returned 9 entries:
[bt] (0) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2ab998) [0x7f6b6eecd998]
[bt] (1) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2abda8) [0x7f6b6eecdda8]
[bt] (2) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24400b4) [0x7f6b710620b4]
[bt] (3) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24446fb) [0x7f6b710666fb]
[bt] (4) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24448d6) [0x7f6b710668d6]
[bt] (5) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24411ab) [0x7f6b710631ab]
[bt] (6) /home/jiewei/anaconda3/envs/mxnet/lib/python2.7/site-packages/scipy/sparse/../../../../libstdc++.so.6(+0xafc5c) [0x7f6b9ee69c5c]
[bt] (7) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f6ba60ea6ba]
[bt] (8) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f6ba571041d]

**Comment by ymcasky** [comment]
It it simply out of memory...
I use r50 + batchsize = 64 can train in 8G's 1070 GPU!!!

**Comment by zhyj3038** [comment]
can not you see OOM??  decrease you batch size!

**Comment by ymcasky** [comment]
Thanks for your reply!
I already answer myself.
