### ISSUE TITLE
关于人脸检测数据集的标注

### ISSUE THREAD

**Issue by gray2bgr** [deepinsight/insightface#991]
您好，很感谢您的代码
我想用您的代码 训练自己的数据，看不懂数据的标注。我想请问数据标注的格式
#图片名称
{}x y w h （人脸框）}， {x1,y1,f1}， {x2,y2,f2}， {x3,y3,f3}， {x4,y4,f4}，val
其中xn,yn应该是代表landmark的坐标，fn的是代表点是否可见么
最后的浮点数val的含义是什么？
有些标注是负1的，是不是代码这个人脸的landmark不可见

**Comment by nttstar** [comment]
fn/val全部写0就可以

**Comment by gray2bgr** [comment]
> fn/val全部写0就可以

ok，谢谢

**Comment by gray2bgr** [comment]
@nttstar 您好，您的代码网络的定义是从预训练模型中load进来的，我是否可以自己设计网络然后训练呢

**Comment by gray2bgr** [comment]
谢谢您的指导，我看懂您的代码了
